### ISSUE TITLE
ADFS federated services like Office365 and Teams not working. Blank page when re-directed.

### ISSUE THREAD

**Issue by larssb** [ramboxapp/community-edition#1002]
### Steps to reproduce
1. Use a proxy
2. ADFS should be in use.
3. Try to add 1 of the following account types: Office365 or Teams.
3. Write your company e-mail 
3a. let the Office365 website re-direct you to your company ADFS website.
3b. wait wait wait.... 

### Expected behavior
After being re-directed to your company ADFS website the company ADFS website should be shown.

### Actual behavior
Instead of the company ADFS website showing a blank page is what you get. Resulting in, being unable to login to Offce365 and related federated services.

### Tests
Login to for example Office365 works fine outside Rambox.

### ENVIRONMENT
> Rambox: v0.5.10
> Electron: v1.7.4
> Chromium: v58.0.3029.110
> Node: 7.9.0
> OS: Windows 7 x64
> Arch: x64
> Proxy used = true.

**Comment by bundyo** [comment]
This is probably connected to the missing ADFS login dialog (the same as the basic authentication one here #378).

**Comment by gugahoi** [comment]
Some feedback on this would be appreciated.

**Comment by thosil** [comment]
I have the same problem with teams-for-linux (https://github.com/ivelkov/teams-for-linux).
The workaround I use to do is add something like this on the electron app: 
```
app.on("login", (event, webContents, request, authInfo, callback) => {
  event.preventDefault();
  callback("my-user", "my-secret-pass");
});
```

but I have no idea where something like this must be implemented in rambox

**Comment by manuc66** [comment]
Hi,

Is it be possible as a workaround to define the kind of script provided by @thosil with [custom JavaScript code](https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code) ?

**Comment by astafyev** [comment]
There is the same [issue]( https://github.com/ivelkov/teams-for-linux/issues/14) for [teams-for-linux](https://github.com/ivelkov/teams-for-linux). It seems that Wavebox got the [workaround](https://github.com/wavebox/waveboxapp/commit/2c2e7170929a9f352333e22bfe6fdf28289da392).

**Comment by evancaldwell** [comment]
Any update on this issue? Trying to get Outlook to work properly.

**Comment by astafyev** [comment]
Still an issue.

**Comment by crollcomp** [comment]
I would also like to comment that this is still an issue and am requesting that it is opened up again.

**Comment by pszemus** [comment]
Still an issue!
