### ISSUE TITLE
Rambox window will not show

### ISSUE THREAD

**Issue by nvaken** [ramboxapp/community-edition#1003]
### Steps to reproduce

1. Open Rambox
2. Try getting your window to show and note that it's actually there, but transparent or something (see GIF attachment).

![pxpcbesfxg](https://user-images.githubusercontent.com/503360/28364465-d651ef2c-6c84-11e7-9dfa-f99af2e03f66.gif)

### Expected behavior

Show the window

### Actual behavior

The window seems to be there, but transparent, only detectable by right clicking the system tray icon and select "Show all windows". There are no errors and even the counter badge seems to show the right amount of notifications.

Also, all other windows are inaccesible under `Rambox` (Preferences, About Rambox, etc..) without errors when clicking those options.

This issue has been present for a while now (weeks?) and I also tried reinstalling the app, which did not work. 

### ENVIRONMENT

> Rambox: _Not able to find out, About Rambox does not show_

> OS: macOS Sierra - Version 10.12

> MacBook Pro (Retina, 13-inch, Early 2015) - 2.9 GHz Intel Core i5

**Comment by saenzramiro** [comment]
Wow! Is this still happening in latest release? In my Mac works ok.

**Comment by nmat** [comment]
tested on my macbook also and working. Can you test to:

1. Close all other apps and only start Rambox from scratch
2. Check that there is no window (or other application that does some effect third party effect in MacOS that causes this to not render)?
3. Create a new user and quick change to that and install rambox to see if a completely new install on a new user works as intended

All of the above will minimize the error searching a bit.

**Comment by nvaken** [comment]
Thanks for the suggestions @nmat, I've tried creating a new user and opening the already installed Rambox in `/Applications`. In this new user I've been able to open up Rambox, so it's probably an issue in my current user. 

I know that this issue is now probably out-of-scope for Rambox, seeing that this is a local problem, but do you guys have any suggestions to find out what is causing this behaviour? I have been able to fetch the installed version on that separate user: `0.5.10`. So that is a bit out of date, I'm downloading `0.5.12` as we speak. 

Is there any way I can revert Rambox to default settings? I was searching for a dotfolder in my homedir, but couldn't find one.

**Comment by nvaken** [comment]
Update about the version upgrade, I've just:

1. Downloaded the latest `.dmg` from https://rambox.pro/
2. Dragged-and-dropped the Rambox.app into Applications, confirmed overwriting
3. Tried starting Rambox.

Still same.

**Comment by ahoereth** [comment]
I am running into the exactly same problem, latest macOS and Rambox versions. Interestingly Rambox works fine when switching to full screen mode.

**Comment by nvaken** [comment]
Oh yeah, fullscreen mode works for me too!

**Comment by gunnarbeutner** [comment]
I ran into the same problem. What I've noticed while restoring the Rambox window to non-fullscreen mode was that the animation gives you a hint as to where the window really is. In my case it was wedged into the left-most column of pixels on my screen. By hovering over the left screen edge I was able to find the resize control for the window which in turn allowed me to restore the window to its proper size.

I suspect that Rambox remembers its window position when it's restarted. Except, well, in my case apparently the window size was something like 50 pixels by 0 pixels.

**Comment by marvwhere** [comment]
Installed tonight, worked fine, now couple hours later, running into this bug. 

Someone ever found a solution to this? Or do I need to go back to Franz? )=

**Comment by matthias-maennich** [comment]
I was able to fix it by getting Rambox into fullscreen mode and then quitting the application through Command-Q. When I reopened Rambox it was back to normal.

**Comment by nvaken** [comment]
Wow, that seems to do the trick for me as well.

**Comment by bmasci** [comment]
Confirmed matthias's trick worked for me too.

**Comment by Gaudenz77** [comment]
Hi there I am using Rambox in windows 10. since today, it does not work anymore. I see the Icon in the taskbar, under Apps but it does not start. Can anyone help me? Best Gaudenz

**Comment by degoya** [comment]
has anyone a solution for this? i'm on windows 10 and the latest version. After a crash of my system the window doesn't show up anymore. i've reinstalled but still no window to see. i've tried to maximize or whatever no luck.

**Comment by degoya** [comment]
ok i found a solution. i just renamed the folder c:\Users\XXXXX\AppData\Roaming\Rambox\ restarted Rambox then the folder gets build again, then i moved my partitions from my old folder to the new one and voila the window appears again with all my accounts.
