### ISSUE TITLE
Stop forcing Rambox into login items

### ISSUE THREAD

**Issue by josephrexme** [ramboxapp/community-edition#1007]
I'm currently using 0.5.10 of Rambox on my macOS Sierra. When I downloaded rambox at 0.5.7 and noticed it was added to login items I removed it, then came 0.5.8 and it was there again and I removed it, and 0.5.9 and now 0.5.10. Can we stop forcing this? It's becoming uncomfortable to keep doing that if there'd always be updates.

**Comment by saenzramiro** [comment]
This behaviour is weird because it should keep sessions alive between versions.

**Comment by josephrexme** [comment]
Yeah I found it weird. I found out it wasn't just on updates but every time
