### ISSUE TITLE
Remove icon bounce effect on macOS on new notifications

### ISSUE THREAD

**Issue by MountainDev** [ramboxapp/community-edition#1008]
### Steps to reproduce

1. Be (VERY) busy with your tasks
2. Wait until You receive any notification
3. Try not to throw your computer through the window after you see constantly bouncing Rambox icon in the dock.

At least make it as an option, please.

### Expected behavior

NOT BOUNCING 

### Actual behavior

BOUNCING

### ENVIRONMENT

> Rambox: v0.5.10

> OS: macOS 10.12.5

> Arch: x64

**Comment by Korni22** [comment]
I wouldn't recommend removing it all together, I'd make it optional, if possible :)

**Comment by perzanko** [comment]
@Korni22 not possible.

**Comment by ImagoPL** [comment]
It's very frustrating thing especially when you're using fullscreen app.

**Comment by ajacobs21e** [comment]
I am no longer able to turn on "do not disturb" mode. This app used to be a lifesaver and now it makes me want to end all my friendships and work relationships so I never have to get another notification.

**Comment by MountainDev** [comment]
Hello?
