### ISSUE TITLE
Download Files is removing extension format

### ISSUE THREAD

**Issue by Statty** [ramboxapp/community-edition#1009]
I am a MacBook Air user. On Rambox, I am using Gmail, Basecamp, Rocket Chat, Whatsapp.
Whenever i download a file, the extension of the file is getting removed. 
Example: I download an attachment in gmail named "Resume.docx", after download is complete, only the name "Resume" is getting stored on the system, the ".docx" extension name is getting removed.

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> darwin x64 16.6.0

**Comment by olybop** [comment]
Hello there. I have the same issue (macbook pro- sierra 10.12.6)

**Comment by sbakopanos** [comment]
Same issue here. Sierra 10.12.6. Presumably an easy fix?

	> Rambox 0.5.10
	> Electron 1.7.4
	> darwin x64 16.7.0

**Comment by synoptase** [comment]
Same here.

	> Rambox 0.5.12
	> Electron 1.7.5
	> darwin x64 16.7.0

**Comment by JustinShenk** [comment]
Apparently a bug [fixed](https://github.com/electron/electron/pull/10469/commits/511e82de6723bf1e89365bbc38d15bf454069691) in the latest version of electron:

**Comment by dipan15** [comment]
No answer from GitHub  for this ??
