### ISSUE TITLE
Bottom status (ready) bar mouseover text box prevents closing the bar at lower resolutions

### ISSUE THREAD

**Issue by brendanjones** [ramboxapp/community-edition#1014]
### Steps to reproduce

1. Display Rambox in a window smaller than...at a guess, 1280px width?
2. Mouseover the X to close the status bar
3. Mouseover text box covers the X, meaning the status bar can't be closed.

Like so:

![screen shot 2017-07-21 at 13 29 47](https://user-images.githubusercontent.com/16049594/28462002-8526ed3c-6e19-11e7-8466-f953e76dc77f.png)

Even better, remove the status bar forever, as per #933 . It's superfluous.

### Expected behavior

Mouseover text box always displays above the blue status bar.

### Actual behavior

Mouseover text box covers the X to close the status bar.

### ENVIRONMENT

> Rambox: latest

![screen shot 2017-07-21 at 11 59 42](https://user-images.githubusercontent.com/16049594/28461989-7853b64e-6e19-11e7-84ab-0052d2584c6f.png)

**Comment by alexcroox** [comment]
Just experienced this, gif if it helps:

![ss](https://d3vv6lp55qjaqc.cloudfront.net/items/3s133l3R1O0K3K2G363n/Screen%20Recording%202017-08-25%20at%2010.52%20am.gif)

**Comment by jerry1970** [comment]
Also on Linux and large screens. Useless mouseover text - the X says it all. And an option "never show status bar" would be very nice indeed.

**Comment by webserviceXXL** [comment]
Had the same problem. With version 0.5.12 it's working for me.

**Comment by brendanjones** [comment]
Nope, still happening in 0.5.12 for me. Not that it matters much, as I've got status bars turned off.

**Comment by nmat** [comment]
just tested it on MacOS. The way I can reproduce it is to change the size of the window to a smaller size and the text moves over the statusbar. If the window is a bit bigger there it changes the text again to be in 1 line.

This is dependent on the window size it seems.

**Comment by brendanjones** [comment]
Yup, below 1460px width is the problem size, from my testing.

**Comment by jerry1970** [comment]
Please just remove the tooltip, it's superfluous. "Ooh, what does that X mean?" :stuck_out_tongue:

**Comment by alexcroox** [comment]
I quickly realised closing it was a waste of time as it just comes back on next restart :(

**Comment by marvinestreet** [comment]
Having the same issue as well. This is annoying enough, I may just switch back to Franz.

**Comment by marvinestreet** [comment]
Also bumping this issue. @brendanjones how did you disable the status bars?

**Comment by brendanjones** [comment]
@marvinestreet turn this fella off

![screen shot 2017-12-04 at 10 58 50 am](https://user-images.githubusercontent.com/16049594/33546787-3eb99046-d8e2-11e7-9ddf-584630073582.png)

**Comment by Bak3y** [comment]
@brendanjones there should be a global toggle for this, but that did fix this issue for me.
