### ISSUE TITLE
No Audio for teams

### ISSUE THREAD

**Issue by SZUPEK** [ramboxapp/community-edition#1020]
Normal chat activity has no audio so when someone from my team messages me, I dont know it. Debian Jessie x64

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> linux x64 3.16.0-4-amd64

**Comment by saenzramiro** [comment]
Did you check if Don't Disturb mode is OFF and "Mute all sounds" setting of the service is unchecked?
