### ISSUE TITLE
No Internet Connection-Please, check your internet connection and restart Rambox. If you use a Proxy, please go to Preferences to configure it

### ISSUE THREAD

**Issue by liwenjing93** [ramboxapp/community-edition#1025]
Hi, I get get this problem: http://prntscr.com/g01sja
"**Please, check your internet connection and restart Rambox. If you use a Proxy, please go to Preferences to configure it**."

My internet connection still good

After I click OKAY, it show blank page, all service: http://prntscr.com/g01tcb

I quit this software then open it again, still error.

I am using latest version: http://prntscr.com/g01tp8

Version: 0.5.10
Platform: win32 (x64)
Electron: 1.7.4
Chromium: 58.0.3029.110
Node: 7.9.0

Thank you very much!!!

**Comment by keihino** [comment]
+1

**Comment by kxguo** [comment]
same here

**Comment by kusumy** [comment]
Same with me .. although i have set Proxy settings, the application still wont connect.

Version: 0.5.13
Platform: win32 (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by mike4git** [comment]
+1
Same for me:
It's connecting if I have proxy and I can work, but when I'm in a proxyless area I can not deactivate it anymore.
Anyway in the config.json file I can see proxy is deactivated:
...
	"proxy": false,
...
Versions: 
Rambox 0.5.13
Ubuntu 16.04 LTS

**Comment by mike4git** [comment]
Ok to be honest, I've solved my problem: Proxy was manually set in the network settings and so Rambox always tried to find it. But in this way I do not understand why I have to set proxy settings in the application itself if they could be managed by the operating system and overwrite settings of Rambox itself.
