### ISSUE TITLE
Services edges cut off

### ISSUE THREAD

**Issue by lightwing3** [ramboxapp/community-edition#1028]
Hello all, 

Recently Rambox has been cutting off the edges of all my services, and I cannot access the typing box. The right side and the bottom of the services spill over past the edges of the window. Even if I try to zoom to actual size or resize the window, thees elements are still being cut off, making it unusable. 

Appreciate any advice.  

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> darwin x64 16.7.0

**Comment by DroWnThePoor** [comment]
This also affects me, specifically with Skype, FB Messenger seems to be fine.

-
> Rambox 0.5.10
> Electron 1.1.0
> Elementary OS 0.4-Lok(Ubuntu 16.04 based)

**Comment by m4rcu5** [comment]
Hi, 

I can replicate this issue by zooming the main GUI of Rambox. At normal zoom level the GUI works fine. When zooming out the main GUI, the edges get cut off.
You can zoom the GUI of the service without any issues. See examples below;

**Main GUI: 100%, Service GUI: < 100%**
![2017-08-15-105746_1451x990_scrot](https://user-images.githubusercontent.com/219754/29309383-c56e3f5a-81a9-11e7-9936-70731faf9419.png)

**Main GUI: < 100%**
![2017-08-15-105810_1451x990_scrot](https://user-images.githubusercontent.com/219754/29309411-e35e3b14-81a9-11e7-8a1d-489292cec941.png)

I am running Rambox on a HiDPI display, and therefore zooming out is a must for me.

**Comment by aoot** [comment]
@lightwing3 Reset the Global GUI zoom, and then set each services zoom level individually should solve the issue.

**Comment by pietro909** [comment]
This issue was such a pain and a waste of time to fix, that I'd like to write it clear for whoever comes here:

1. open Rambox
2. stay in the main tab, the one where you can see the whole list of services
3. in the top bar, click `View -> Actual size`
4. do the same for each service's tab
