### ISSUE TITLE
Como puedo ver los logs para saber por que rambox no abre en LINUX?

### ISSUE THREAD

**Issue by soycamiloypunto** [ramboxapp/community-edition#1032]
### Steps to reproduce

Yo quisiera saber de alguna forma por qué rambox dejó de abrir en mi equipo.

### ENVIRONMENT

> Rambox: última versión

> OS: Deepin 15.4.1

> Arch: x64

**Comment by saenzramiro** [comment]
¿Estás usando la versión oficial o una propia?
