### ISSUE TITLE
"Keep in tray" option errors

### ISSUE THREAD

**Issue by Gittyperson** [ramboxapp/community-edition#1034]
Trying to use the 2 below options together, but it seems not possible. I want Rambox in the Taskbar when open, and minimised to the tray when closed (ideally when minimised, but this is not available).

_Display behaviour: Show in Taskbar
When closing the main window: Keep in tray_

When I try to save this configuration, I get a Javascript error (see attached). The one time I managed to save the Preferences with no error, it didn't work. When I pressed 'X' to minimise to tray, Rambox kept running but it disappeared from both tray and Taskbar. Selecting _"Display behaviour: Show in Taskbar and Tray Icon"_ gives no errors. Windows 10 Pro x64, Rambox 0.5.10 (installer).

![javascript error](https://user-images.githubusercontent.com/7165208/28727341-2eeae57c-73cd-11e7-856d-d3b9fb2d5e08.jpg)

**Comment by saenzramiro** [comment]
Is this still happening in the latest version?
