### ISSUE TITLE
backup/restore does not work

### ISSUE THREAD

**Issue by edmundlaugasson** [ramboxapp/community-edition#1036]
### Steps to reproduce
1. add more than 25 accounts
2. save backup
3. try to restore - services are messed up, most of them are deleted

There were more than 25 accounts configured. These accounts that exceeded 25, were not displayed. Deleting some of them did not work - after reopening Rambox the old settings were back: deleted accounts were restored and recently added accounts were deleted.

### Expected behavior
Configuration saved and restored properly.

### Actual behavior
Restored services did not contain what were backed up. Almost all saved services were deleted.

### ENVIRONMENT
> Rambox: v0.5.9
> OS: Linux Mint 18.2 MATE
> Arch: x64

**Comment by New1997** [comment]
Backup does not work
It display : "please wait... saving backup..." in loop for hours
number of enabled services:11
rambox version: 0.6.1
os: ubuntu 18.04
install from: Rambox-0.6.1-linux-x86_64.AppImage

**Comment by jasinai** [comment]
I have the same problem as @New1997. There are some errors in the dev tools.
`PATCH https://rambox.auth0.com/api/v2/users/auth0... 401`
`POST https://rambox.auth0.com/delegation 401 ()`
`ResponseText: "{"error":"invalid_client","error_description":"OIDC conformant clients cannot use /delegation","statusCode":401}"`
And if you log out, all your services are gone. How can I readd them from my local backup?

Rambox 0.6.1
Electron 2.0.8
os: ubuntu 18.04
linux x64 4.15.0-36-generic

**Comment by jurgenhaas** [comment]
It's not fixed for my use case, I still get this error message:

![2018-10-18 08 35 22 screen](https://user-images.githubusercontent.com/1475675/47135569-5c4dc100-d2a0-11e8-94cd-c6bcae4995a8.jpg)

**Comment by Ash258** [comment]
How could it be fixed when there was no new release? Closing issue doesn't mean it will be automatically aplied to your installation. It will be "fixed" in new release.

**Comment by jurgenhaas** [comment]
@Ash258 it was announced in the Gitter channel that this has been fixed and added to the version 0.6.2 - @saenzramiro asked people there to test and confirm that.

**Comment by carcam** [comment]
This is not fixed in the Mac release. Also Linux release cannot restore the last backup I have on my account from March. What information do you need besides knowing I am in the latest release in both OS ?

**Comment by jaklan** [comment]
Ubuntu, backup doesn't work.
