### ISSUE TITLE
Twitter becomes extremely slow after some time

### ISSUE THREAD

**Issue by MrChick** [ramboxapp/community-edition#1043]
### Steps to reproduce

1. Add Twitter as service
2. leave it open on your feed for few hours while regularly clicking the link to load new tweets

### Expected behavior

Everything works decently without major lags

### Actual behavior

The whole tab becomes extremely slow and sluggish, taking multiple seconds to load new tweets or even the hover-popups

### ENVIRONMENT

Version: 0.5.10
Platform: win32 (x64)
Electron: 1.7.4
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by saenzramiro** [comment]
Is this still happening in latest release?

**Comment by MrChick** [comment]
yes

**Comment by MrChick** [comment]
Version: 0.5.13
Platform: win32 (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

Had twitter open for about an hour, loading newest tweets from time to time, reeeeeeeally slow. The twitter tab on itself is using ~170mb ram and constantly 2-10% cpu, even when idling.

I don't have that problem when using Chrome Browser so I think it's actually something with rambox

**Comment by saenzramiro** [comment]
I don't know what can be... maybe a ton of elements rendered because Twitter gets new ones every X seconds and the auto-play for GIFs and videos.

Do you have autoplay videos enabled? If so... please try by disabling it.

**Comment by MrChick** [comment]
Alright, I've disabled autoplay. I'll keep an eye on it!
