### ISSUE TITLE
Issues found with Heap Profiler

### ISSUE THREAD

**Issue by NatGra** [ramboxapp/community-edition#1045]
### Uncovering DOM memory leaks
As depicted in the snapshot of the heap, there are several DOM elements marked with yellow and red. Even if the red elements are detached from the yellow tree node, they still hold wrapper objects which refer to data. Following these data can’t be collected and deleted.

![bildschirmfoto 2017-08-03 um 12 23 03](https://user-images.githubusercontent.com/10546494/28965844-761d5c40-7913-11e7-825a-54af10f82804.png)

### Performance Audit
Furthermore, performance issues were detected by using the Audit function of the Heap Profiler. 

![bildschirmfoto 2017-08-03 um 14 01 49](https://user-images.githubusercontent.com/10546494/28965892-aea22e1a-7913-11e7-8fd5-39e087ca3946.png)

### ENVIRONMENT

> Rambox: v0.5.10

> OS: macOS Sierra

> Arch: x64

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
