### ISSUE TITLE
Feature request: Ability to set which browser that links open in on per service basis.

### ISSUE THREAD

**Issue by TMartinPPC** [ramboxapp/community-edition#1048]
I have no idea if it's even possible but I'd love to see the option to have links open in a specified Browser other than the default.

Example: Default browser for OS is set to Chrome but also have Chrome Canary installed. Rambox has two services, Gmail for personal use and Slack for work use. Logged into personal accounts on Chrome and work accounts in Chrome Canary. In options for Slack service, have the ability to change the browser that links open in to Chrome Canary.

**Comment by FabrizioRomanoGenovese** [comment]
That would be very useful. I mainly work behind TOR and my default browser is TOR browser. Still, when I click on a link it is opened in Firefox. Is there a way to tell Rambox that I want to use TOR browser instead?

**Comment by kreuzman** [comment]
+1

**Comment by mcortinas** [comment]
+1
