### ISSUE TITLE
Feature Request: allow to permanently disable status bar

### ISSUE THREAD

**Issue by V3XATI0N** [ramboxapp/community-edition#1049]
Please allow me to permanently disable the useless blue "status bar" that shows up at the bottom of every connection for no reason whatsoever. I don't need Rambox to tell me whether or not it is "Ready". I can tell based on whether or not the app in that tab works or not.

> Rambox: v0.5.10

> OS: Debian 8/9, Ubuntu 17.04, Deepin 15.4

> Arch: x64

**Comment by jakejoh** [comment]
there is a setting for each service to disable it. However, it still appears during loading, which leaves a white bar at the bottom with Wire.

**Comment by blahah** [comment]
I would be so incredibly grateful for this feature. I have severe ADHD and I cannot use any given tab in rambox until I have closed the status bar. It's completely useless from a user-serving functionality perspective, takes up screen real estate, and is just very distracting (for me at least). If you are amenable to a PR I would happily implement it. The options as I see it are:

- remove the status bar completely (my preference)
- add a global option to hide it

**Comment by igalic** [comment]
sometimes the tool-tip `close status bar until next time` will get in your way of actually closing it ☹

**Comment by Bak3y** [comment]
There should be a global toggle for this.

**Comment by 613TheEvil** [comment]
We do not need it. It has to go. End of story.

**Comment by igalic** [comment]
it is useful for seeing where links will go, but that could be dealt with … differently.

**Comment by igalic** [comment]
dear @stale bot

this issue  is still open and hasn't moved because no dev has commented
