### ISSUE TITLE
Facebook does not refresh after system sleep

### ISSUE THREAD

**Issue by mirfilip** [ramboxapp/community-edition#1052]
It doesn't happen everytime but:
### Steps to reproduce

1. Sleep the system with Rambox running and Facebook active
2. Wake the system
3. Go back to Rambox

### Expected behavior
Rambox reconnects with Facebook and is ready to receive messages.

### Actual behavior
Rambox doesn't receive new messages nor tries to reconnect.

### ENVIRONMENT
Version: 0.5.9
Platform: darwin (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0
OS: macOS 10.12.5 (16F73)

### Comments
I run Rambox with WhatsApp and Facebook. There are no problems with WhatsApp. I noticed this couple of Rambox versions back but it only happens rarely, so I didn't bother to report the problem.

It's frustrating as you learn about new messages after you see it on other channel (phone, FB in other browser).

I can see
> (7) Start loading... https://www.messenger.com/login/

In developer console after waking up but nothing happens. Looks like it tries many times. When I click on Facebook tab and reload, it comes back to normal, just one

>Start loading... https://www.messenger.com/login/

**Comment by saenzramiro** [comment]
Is this still happening in latest version?

**Comment by mirfilip** [comment]
I still have the problem sometimes but most of the times there is an extra UI indicator "Messenger is currently unavailable" in red. I then reload the service and it starts working.

**Comment by mirfilip** [comment]
The same with:
```
Version: 0.5.13
Platform: darwin (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0
```

and there are 142 messages in Dev Console:
```
app.js:1 Start loading... https://www.messenger.com/login/
```
