### ISSUE TITLE
SIzing of all messenger apps creates "offscreen" text entry.

### ISSUE THREAD

**Issue by DroWnThePoor** [ramboxapp/community-edition#1057]
### Steps to reproduce

1. Open Rambox 
2. Pick any messenger
3. Cannot enter new text as it is offscreen.

### ENVIRONMENT

> Rambox: v0.5.10

> OS: Linux: Ubuntu 16.04 (specifically Elemetnary OS)

> Arch: x64

>Eletctron version: 1.7.4

>Node 7.9.0

![image](https://user-images.githubusercontent.com/16339020/29237829-d0efa588-7ef4-11e7-8338-b11ddcb5887c.png)
Where the text entry field is below the margin's of the window, even if fullscreen.

**Comment by wzwizu** [comment]
Same problem over here, with every messenger service.

**Comment by ericzawo** [comment]
Same problem here.

**Comment by nmat** [comment]
in next release there is a fix https://github.com/saenzramiro/rambox/pull/1091

It could fix this issue.

**Comment by metal3d** [comment]
The problem persists here:

Version: 0.5.17
Plateforme: linux (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

Fedora 27, RPM package

**Comment by metal3d** [comment]
I set max-height and max-with : without
![image](https://user-images.githubusercontent.com/100080/42336114-e8fb060a-8082-11e8-8b3f-25f8acc1783f.png)

with 91%:

![image](https://user-images.githubusercontent.com/100080/42336121-f25453b4-8082-11e8-8af3-2d289cce8cb8.png)
