### ISSUE TITLE
High resource use

### ISSUE THREAD

**Issue by ErinMoriarty42** [ramboxapp/community-edition#1059]
### Expected behavior

Rambox uses a similar resource amount to firefox or chrome open to the same sites

### Actual behavior

With 2 gmail accounts, a fb messenger account, and a skype account open, and 5 more accounts sitting on login page, Rambox consumes from 60% to 140% cpu usage on a i5 6200u (2 core, 4 thread)

### ENVIRONMENT

> Rambox: 0.5.10

> OS: ubuntu 16.04 (cinnamon 3.2.8)

> Arch: x64

**Comment by varlesh** [comment]
I confirm this.
Rambox: 0.5.10
OS: KDE Neon 5.10.4 (Ubuntu 16.04) amd64
CPU: Intel Core i5 7400
Rambox use 92% CPU - it's very high. On app activate only Gmail service.
![image](https://user-images.githubusercontent.com/8083855/29549035-a66f89de-8716-11e7-9260-c653ccdc7f08.png)

**Comment by touilleMan** [comment]
Same thing here.
I tried with and without GPU acceleration, CPU consumption stays the same at ~50%

Interestingly the consumption drops to a normal level as soon as I minimize rambox. I guess the issue is in electron's renderer system.

```
Version: 0.5.10
Platform: linux (x64)
Electron: 1.7.4
Chromium: 58.0.3029.110
Node: 7.9.0
```

**Comment by varlesh** [comment]
I'm enable Hardware Acceleration and not nothing changed, minimize maximize or on tray - always 87-100% CPU usage.

**Comment by somepaulo** [comment]
Same thing here.

![rambox](https://user-images.githubusercontent.com/15643750/30867884-1539d5d4-a2d5-11e7-806b-e1337a25f292.png)
Tried with Gnome 3.24 and 3.26, with Wayland and X - same behaviour.
An open Rambox window with 10 accounts consumes around 50% CPU whether focused or not.
Minimizing it drops Rambox CPU usage to about 4% as @touilleMan pointed out.
Opening the same accounts in Gnome's Web (Epiphany) has a much smaller footprint both on memory and CPU usage.

````
Version: 0.5.12
Platform: Arch linux (x64)
Electron: 1.7.5
Chromium: 58.0.3029.110
Node: 7.9.0`

**Comment by barredijkstra** [comment]
This problem still occurs with 0.15.3 on Ubuntu 16.04-LTS.
I haven't dove into the framework causing the problems, but thought I'd confirm the issue on the latest version.

Following htop screenshot is for a minimized Rambox.

![rambox-htop](https://user-images.githubusercontent.com/2154343/31576473-d72552d4-b0fb-11e7-967e-d5c14f17e7de.png)

System
```
CPU:  Intel i7-7820HQ (4 cores, 8-threads @ 3.9GHz)
RAM: 32GB
Kernel: #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017
```
Rambox version
```
Version: 0.5.13
Platform: linux (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0
```

**Comment by bserem** [comment]
I did not get high CPU usage, not that much to get me worried at first, but powertop reports that Rambox is the most consuming task running, preceded only by hardware components.
Two services: hipchat + facebook.
```
                Usage       Events/s    Category       Description
             18.8 ms/s     110.2        Process        /opt/Rambox/rambox --type=renderer --no-sandbox --primordial-pipe-token=5B81145F98BF221658E9AEABAAEEED1B --lang=en-US --app-pat
```

**Comment by Fil** [comment]
same issue for me, rambox 5.0.17 is eating all the cpu & power
![capture d ecran 2018-06-27 a 16 50 26](https://user-images.githubusercontent.com/7001/41982013-a3a109e6-7a2a-11e8-9286-188df6f50cde.png)
