### ISSUE TITLE
Google Hangouts - unable to hear sound on calls

### ISSUE THREAD

**Issue by BlackCatte** [ramboxapp/community-edition#1062]
This issue started happening maybe 4 days ago. Whenever I place a call, I am unable to hear any sounds. I don't hear ringing or anything. I have only tried making calls to landlines or cell phones, I have not tried calling any Hangouts users.

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 10.0.15063

**Comment by saenzramiro** [comment]
What about other services inside Rambox?

**Comment by BlackCatte** [comment]
Other services work fine, but Hangouts is the only voice chat service I 
use on Rambox.
I noticed that Hangouts voip is temporarily no longer supported by newer 
versions of Firefox, so I was wondering if that's somehow related.

Ramiro Saenz wrote:

**Comment by saenzramiro** [comment]
Did you check if "Mute all sounds" option in service is unchecked?

**Comment by BlackCatte** [comment]
That option is unchecked for Hangouts.

Ramiro Saenz wrote:
