### ISSUE TITLE
BUG: Riot constant notifications

### ISSUE THREAD

**Issue by GitZin** [ramboxapp/community-edition#1065]
Using Riot via RamBox: Constant notifications 

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 6.1.7601

**Comment by saenzramiro** [comment]
Is this still happening in latest release?

**Comment by GitZin** [comment]
nope, everything is fine now.great new features btw., thank you!‎the only thing we are still missing: editing messages which are already sent, like you can do it on skype. this feature would make it perfect.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Von: Ramiro SaenzGesendet: Dienstag, 10. Oktober 2017 16:39An: saenzramiro/ramboxAntwort an: saenzramiro/ramboxCc: GitZin; AuthorBetreff: Re: [saenzramiro/rambox] BUG: Riot constant notifications (#1065)Is this still happening in latest release?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/saenzramiro/rambox","title":"saenzramiro/rambox","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/saenzramiro/rambox"}},"updates":{"snippets":[{"icon":"PERSON","message":"@saenzramiro in #1065: Is this still happening in latest release?"}],"action":{"name":"View Issue","url":"https://github.com/saenzramiro/rambox/issues/1065#issuecomment-335494659"}}}
