### ISSUE TITLE
[Feature Request] Office 365 Calendar Notifications

### ISSUE THREAD

**Issue by sengelbert** [ramboxapp/community-edition#1071]
Would like to get notifications for upcoming calendar events in Office 365

**Comment by jerry1970** [comment]
I managed to combine the unread emails and calendar notifications in Franz but I only just installed Rambox so I have no clue on how this works in Rambox yet.

**Comment by pdelre** [comment]
It appears it can be read from `$("#O365_Notifications_ButtonID").text().trim()`. I don't see a way on my Mac to test without doing a full build, etc, but hopefully that will point people in the right direction.

**Comment by pdelre** [comment]
I was able to add basic functionality via the `Custom Code` field. The popup message still references new emails, but at least it's a notification.

https://github.com/saenzramiro/rambox/blob/3d7ae58fa91d27b44e064522a94119f016e3ec0c/app/util/Notifier.js#L27

```
function checkUnread(){
  var a=$(".subfolders [role=treeitem]:first .treeNodeRowElement").siblings().last().text() + $("#O365_Notifications_ButtonID").text().trim();
  updateBadge(""===a?0:parseInt(a))
}
```

**Comment by nmat** [comment]
@pdelre is it possible you can add this as a pull request so that ramiro can look at the code?

**Comment by pdelre** [comment]
@nmat IMO, a PR that just adds my snippet is incomplete for handling a new feature. To properly implement the full feature, the messaging would also need to be changed to match what the user is being notified about (email vs meeting). Hopefully my workaround will help those who are waiting for the feature or the person with the resources to implement a complete solution.

**Comment by dominikzogg** [comment]
the problem did not disappear
