### ISSUE TITLE
Question about Direct Write

### ISSUE THREAD

**Issue by RitzyBusiness** [ramboxapp/community-edition#1073]
I am wondering if this is running the later chromium builds or if there was a way to disable directwrite.  I use mactype which won't work with it otherwise.    

Disabling hardware acceleration does not seem to do anything for me.

**Comment by saenzramiro** [comment]
In version 0.5.13 we are using version `58.0.3029.110` of Chromium.

Sorry but I don't know Direct Write so I can't help you. But I will take a chance to say this: try adding `--disable-gpu` to Rambox shortcut.
