### ISSUE TITLE
Reload doesn't work in KiwiIRC

### ISSUE THREAD

**Issue by notNSANE** [ramboxapp/community-edition#1079]
### Steps to reproduce

1. Load KiwiIRC
2. Right Click the tab then use the "Reload" option

### Expected behavior

KiwiIRC reloads

### Actual behavior

KiwiIRC doesn't reload

### ENVIRONMENT

> Rambox: v0.5.10

> OS: Windows

> Arch: x64

**Comment by MrChick** [comment]
yeah, kiwi has its own reload handled which seems to stop the event from bubbling up...  It's been bugging me for quite some time but I didn't get around to look for a workaround yet other than removing the entire DOM in dev tools and then reloading

**Comment by saenzramiro** [comment]
So because it's a KiwiIRC behavior, can we close this?

**Comment by MrChick** [comment]
I'd prefer to have that fixed/circumvented instead of just closing it. Here's what's working for me: 
- remove the entire DOM
- set window.location to the service location (default or user defined)
