### ISSUE TITLE
No dot notification (Slack) in Dock in macOS

### ISSUE THREAD

**Issue by drskullster** [ramboxapp/community-edition#1080]
### Steps to reproduce

1. add a Slack team
2. get a notification for a message but not mention (eg., notification is a dot (.) instead of an unread count). Use an Incoming webhook with default example for easy testing : https://api.slack.com/incoming-webhooks

### Expected behavior

Dock icon should display a badge when getting a notification without an unread count.

### Actual behavior

Dock Notifications are only displayed if there's an unread notification in Slack, and not a message notification (dot). Dot notifications work fine in service tray.

**Note:** I'm currently using workaround from #1072 since slack changed their CSS selectors, but problem appeared before that.

### ENVIRONMENT

> Rambox: v0.5.10

> OS: macOS Sierra (10.12.5)

> Electron: 1.7.4

> Chromium: 58.0.3029.110

> Node: 7.9.0

> Arch: darwin (x64)

**Comment by Thalagyrt** [comment]
I posted a workaround in #1072, and a fix in PR #1076 - hopefully the patch gets merged soon, but my comment in the issue should help you get sorted for now.

**Comment by nmat** [comment]
@Thalagyrt and @drskullster there are also a work in progress for using a dot in rambox for the unread in the tray icon. See: https://github.com/saenzramiro/rambox/pull/806

**Comment by drskullster** [comment]
@Thalagyrt thanks for the workaround, I'm already using it but I still have no notification in the Dock when there's an unread message, only when there's a mention.

@nmat when you say _tray icon_, you're talking about the dock ? so this feature is not implemented yet ? 

I guess what I'm asking is : is the fact that I have notifications only when there's a number in it (meaning, when I get a mention) the expected behavior or do I have a bug ?

![image](https://user-images.githubusercontent.com/1693766/29558276-e7d05ede-872b-11e7-9d22-e57384958754.png)

**Comment by nmat** [comment]
AFAIK....now do not take me word for word...but I think the idea is to have a kind of dot like notification icon in the tray icon in the future. Not the number. Since there might be 1000 notifications (email for example) it could cause the icon to flood with numbers. However I could be wrong.

**Comment by Thalagyrt** [comment]
Whoops! I see what you mean now, and yeah that'd be useful.

**Comment by nniesen** [comment]
The same issue exists with the Windows 10 tray icon. Only Slack "Direct Message" unread counts are displayed, no "Channel Message" unread dot.

Version: 0.5.12
Platform: win32 (x64)
Electron: 1.7.5
Chromium: 58.0.3029.110
Node: 7.9.0
