### ISSUE TITLE
Teams notifications not showing for channels

### ISSUE THREAD

**Issue by nmat** [ramboxapp/community-edition#1081]
Channel notifications does not show up. Only private conversations.

### Steps to reproduce

1. Normal run of teams

### Expected behavior

Notifications on all areas not just private messages. 

### Actual behavior

I only get notifications from private messages

### ENVIRONMENT

> Rambox: v0.5.10
> OS: windows 10
> Arch: x64

**Comment by biffster** [comment]
I know I'm a month behind on this one, but I'd like to say "me too!"

**Comment by npichot** [comment]
Hi !
I have this problem too with chat conversation. But it seems a bit random. Maybe it's something with active process and background process. Wild guess.
Anyway it's not so practical.
I stay available if help is needed to fix it.
Best regards

**Comment by nmat** [comment]
There is work being done for the notifications. I know the notifications will be there eventually. :)

**Comment by AKFourSeven** [comment]
Having this problem as well, the notification are rarely showing, I don't know if it is a problem to do with Teams or with Rambox itself. When you access team in it you see the notifications, but Rambox itself is not notifying you like for other apps/tabs.

**Comment by rodolphopivetta** [comment]
Same problem here

**Comment by tarnagas** [comment]
Same problem

```
Rambox: v0.5.14
OS: Ubuntu 17.10
Arch: x86_64
```

**Comment by AKFourSeven** [comment]
Do we have any update on this ? there have been updates of the application but the issue still stands and we still don't know where it stems from...

**Comment by jamesraylittle** [comment]
I am having the same issue, but for all message types. I do not get any notifications.

I am on MacOS 10.14 (beta).

Version: 0.5.17
Platform: darwin (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1
