### ISSUE TITLE
Multiple tray icons for each service

### ISSUE THREAD

**Issue by pioneer** [ramboxapp/community-edition#1086]
It'd be great to have so-called "split window" mode, as if each service is a separate app with its own window and tray icon. Or, it can be mixed, some of the services are in the main Rambox window, some separated. I'm mostly using a very few number of services, and the idea of this feature is to be able to: 1) quickly spot which service has notifications 2) quickly switch to exactly that service.

**Comment by timsayshey** [comment]
I was coming here to request the same feature. Really hope this gets added. It will also make Rambox fill the void for users when Chrome deprecates "Apps" from Mac, Windows, and Linux in early 2018.

**Comment by dbfin** [comment]
+1 as an option so those who dislike keep one icon
