### ISSUE TITLE
Rambox app scaling issues on HiDPI display

### ISSUE THREAD

**Issue by alexdevero** [ramboxapp/community-edition#1088]
### Steps to reproduce

1. Download / install Rambox
2. Open the app
3. Add any channel.

### Expected behavior

Rambox app and all "window/tabs" are scaled properly on HDPI screen.

### Actual behavior

Rambox app and all "window/tabs" are not scaled properly on HDPI screen - panels and content are much larger than they should be. Problem is caused by scaling issue (https://github.com/electron/electron/issues/9691) in electron.

### ENVIRONMENT

> Rambox: v0.5.10

> OS: Win 10 (15063 - Creators update)

> Arch: x64

> Scaling: 125%

### Screen
(Firefox in the background is scaled properly)
![broken rambox win](https://user-images.githubusercontent.com/4237724/29617746-2ed1e074-8816-11e7-99bd-8cf9ddb30983.JPG)

**Comment by alexdevero** [comment]
Fix for this issue is including following snippet in the file with `{app} = require('electron')` reference.
```
if (process.platform === 'win32') {
  app.commandLine.appendSwitch('high-dpi-support', 'true')
  app.commandLine.appendSwitch('force-device-scale-factor', '1')
}
```

**Comment by nmat** [comment]
interesting..... @alexdevero can you create a pull request for this? and maybe link to where you have seen the fix in the electron docs?

**Comment by alexdevero** [comment]
The fix is in https://github.com/electron/electron/issues/9417, see comment from KagamiChan, 10 May.

**Comment by moritzschaefer** [comment]
@alexdevero As the PR is merged, can this be closed? Is the issue resolved?

**Comment by alexdevero** [comment]
@moritzschaefer Don't ask me 😄. @saenzramiro is the owner of this repo and project.

**Comment by poisonborz** [comment]
Still an issue, Win10 on a Macbook Pro 2017

**Comment by riprop** [comment]
Hi, 
I also have an issue with  Rambox on HiDpi screen, on gmail I cant see nor access elements (buttons,...) on the far right and at the very button.
Zooming in/out change part of gmail application being seen, but no chance to show complete application.
Switching on/off hidpi support do not influence problem.
 
Version: 0.5.17
Platform: linux (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
HW: Macbook pro Retina 13"
OS: Linux Xubuntu 18.04
Node: 8.2.1

**Comment by pauby** [comment]
I'd like to throw my hat into this and confirm this is still an issue for me:

Windows 10 Pro Version 1803 Build 17134.112
Display: 3440 x 2160 250% scale (4k screen)

I use WhatsApp, Slack, Gitter and TweetDeck in mine and all of them are much smaller than they should  and fill about half width and half height of the Rambox window. 

Zooming has it's own issues in that when I zoom in it starts to cut off the right or bottom of the display window even though it's not at the edge of the Rambox window.

**Comment by pauby** [comment]
I'd actually like to update this one. I'm not going to say this will work for everybody but it did for me!]

Turn off 'Fix Scaling for Apps' under Windows Settings (Windows 10 it's All Settings -> System -> Display -> Advanced Scaling Settings -> Fix Scaling for Apps <- Turn to OFF. Ironically this fixed Rambox (and some other apps but strangely not the MS Office splash screens). Might be worth a try. I also have no scaling settings on the Rambox executable either.
