### ISSUE TITLE
Problema ao carregar audios do WhatsApp

### ISSUE THREAD

**Issue by ruancorreia** [ramboxapp/community-edition#1090]
Audio nao carrega no WhatsApp, dou play e nao sai som.

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 6.1.7601

**Comment by anabellaspinelli** [comment]
Mismo problema que @ruancorreia , no es que los audios no se escuchen, directamente no avanza la reproducción, es como que no cargan.

Lo mismo pasa en telegram, o messenger.

Ayuda por favor!

**Comment by ruancorreia** [comment]
Descobri o problema, é só ativar o audio na guia, infelizmente ele desativa nao só os de notificações mas os audios que mandam tbm.
deveriam ter uma opção pra só silenciar as notificações e não tudo junto.
