### ISSUE TITLE
Clicking on Gmail notifications opens default browser to blank page

### ISSUE THREAD

**Issue by ugachmaaz** [ramboxapp/community-edition#1098]
When I get 'new email' system tray notifications from Gmail and I click on them, an empty Rambox window opens with a "Gmail" title, but then the default browser is launched with a mail.google.com/..../.... URL. The page, however, remains blank and does not open to the new email. I have to close the browser and manually return to Rambox's Gmail tab to view the email. 

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 10.0.15063

**Comment by johnnyasantoss** [comment]
Related to #834

**Comment by maxerbox** [comment]
Fixed in #1864
