### ISSUE TITLE
[Feature] Show which keyboard shortcut shows which service

### ISSUE THREAD

**Issue by jvdmeij** [ramboxapp/community-edition#1099]
The keyboard shortcut to directly show one service (command-#) is great. But sometimes it is hard to figure out which number related to which service.

An (optional, configured in the settings perhaps) idea is to show which number related to which 'tab'. This could be visualised as follows:

<img width="790" alt="screenshot 2017-08-26 10 34 22" src="https://user-images.githubusercontent.com/7727264/29739917-76151100-8a4a-11e7-93f0-907f9612bfaa.png">

**Comment by starpause** [comment]
You can do something similar to this yourself simply by renaming the services

<img width="727" alt="screen shot 2018-07-02 at 9 58 52 am" src="https://user-images.githubusercontent.com/408953/42191893-3e05fe7c-7e1a-11e8-9173-32b734fdf997.png">
