### ISSUE TITLE
[Feature Request] Implement WeeChat connectivity

### ISSUE THREAD

**Issue by jsaalfeld** [ramboxapp/community-edition#1110]
[WeeChat](https://github.com/weechat/weechat) is an extensible chat client with a growing community. I heavily use it on my server to maintain a stable IRC connection, mostly to stay online 24/7. I currently use 2 messenger windows on my system, one for the ssh connection to my server to look at IRC (with a bridge, also XMPP and ICQ) and rambox (of course).
WeeChat has (since some time) an [open source Android App](https://github.com/ubergeek42/weechat-android) which I use and there is also an [open source JavaScript based desktop-application called "glowing-bear"](https://github.com/glowing-bear/glowing-bear). I didn't use glowing-bear but just heard from people that its good.
However, the Android App and glowing-bear are just (glowing-bear maybe even directly implementable into rambox; I'm not very familiar with the new JS-world) examples for implementing the [WeeChat Relay Protocol](https://weechat.org/files/doc/stable/weechat_relay_protocol.en.html) and I'd love to see that implemented. It would make rambox much more extensible and customizable, since WeeChat is that in every way.

**Comment by nmat** [comment]
Glowing bear could be implemented as a service in rambox.

For now you can add it as a custom service in rambox:
Go to Rambox Tab
Search for: "Custom Service"
Fill in the information below:

Name glowing bear
URL: https://www.glowing-bear.org/
Logo: https://www.glowing-bear.org/assets/img/glowing-bear.svg

And the settings you want. And just add the service.

Do this until someone has had a look at the request and test it out.

**Comment by jsaalfeld** [comment]
Thank you for your reply!

The issue is though, that I use a self-signed certificate and I need to add an exception somehow to rambox to use it. I tried to go the "normal browser" way, like i did in ff or chromium, but i wasn't able to add my ssl certificate for an exception.

**Comment by nmat** [comment]
hmmm not really following here. you are using a self signed cert on the service where weechat is running and glowing bear normal from the site does not work either or only in rambox it does not work?

**Comment by jsaalfeld** [comment]
I use a self signed certificate for my weechat instance (to secure the communication channel via the weechat relay). This was introduced in this Blogpost: https://weechat.org/blog/post/2012/07/27/SSL-in-Relay-plugin

Many people I know use the self signed cert to communicate securely with their weechat relay, without having the troubles to buy a cert or hassle around with Lets Encrypt or StartSSL. So there needs to be a way to add an own root certificate to rambox in order to use it with glowing bear.

So glowing bear does only work from browser, because i can accept my self signed certificate there. But it doesn't work from rambox, beacuase i can't accept my self signed certifcate there.

**Comment by diegombeltran** [comment]
Interesting. Would like to see glowing-bear support.

**Comment by BKPepe** [comment]
Yeah, me too! Currently I miss notifications, when I added glowing-bear manually.

**Comment by diegombeltran** [comment]
They work, but not always

**Comment by jsaalfeld** [comment]
A somewhat official answer would be nice.
