### ISSUE TITLE
[Feature Request] Display service in system notification (MacOS)

### ISSUE THREAD

**Issue by Eeram** [ramboxapp/community-edition#1116]
Oy,

On MacOS, when receiving a message, a system notification is displayed. Could you add a way to know on which service (ex: Whatsapp) the notification was received? 

Either by displaying the service icon (ex: WhatsApp icon) in place of the Rambox icon in the notification, or by concatenating the service name (ex: "WhatsApp") to the notification title?

Thanks!

PS: Love Rambox, keep up the great work 👌

**Comment by vraravam** [comment]
I dont think this should be `stale` - this is definitely a needed feature.

**Comment by D4NNYX** [comment]
+1
