### ISSUE TITLE
2 MySMS issues

### ISSUE THREAD

**Issue by LaurentBerder** [ramboxapp/community-edition#1119]
Hello,
I have 2 issues with the MySMS integration:

- Login through Google doesn't work. It opens the webpage, I click to login, and it just keeps loading. So I just log in through my phone number instead, but it's less handy.
- The MySMS tab keeps disconnecting when I reboot my computer. It's not systematic, but pretty often.

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 10.0.15063

**Comment by Ash258** [comment]
Second issue should be resolved by 0.5.12.

**Comment by LaurentBerder** [comment]
Nope, it still needs me to re-login after startups.

**Comment by Ash258** [comment]
Check your version of Rambox and then check if you can reload service and be logge.
For me its working 100%. After computer restart and service restart.
![Working](https://image.prntscr.com/image/43RfVQM3QLGlYcrzDwEyTQ.gif "Working")

**Comment by LaurentBerder** [comment]
I logged in, then reloaded the service: it asks me to log in.
Version: 0.5.12

**Comment by Ash258** [comment]
That is strange. For me and coworkers it work like charm after 0.5.12.
Developers will investigate it.

**Comment by LaurentBerder** [comment]
Anyone has news about the 2 issues?

- login required for mysms at each startup

- login through google not working (opening a browser page, link not functioning)
