### ISSUE TITLE
Feature Request: maintain order of enabled services, whether enabled or not

### ISSUE THREAD

**Issue by brendanjones** [ramboxapp/community-edition#1128]
Order the Enabled Services list alphabetically, and maintain their position whether they're enabled or not.

Maybe this'll be fixed in 1.0.0, but right now I've no idea how enable services are ordered in the Enabled Services list. They're not grouped by active/inactive, they're not alphabetical...it appears random. Also, they move around when you enable/disable them, but with a tiny bit of lag. This makes quickly enabling/disabling more than one service a minefield, because if you go too fast the list might move and you'll (de)select a different service to the one you intended.

**Comment by brendanjones** [comment]
Or, order services in the enable/disable section by the order you've got them in the menu bar. But whatever the ordering system, don't move them in the enable/disable list when you change their status.

**Comment by Foggalong** [comment]
I would also like to see this. The older system where they stayed in the bar but greyed out is preferable to this because now every time I re-enable a service I have to muck about with the ordering again. Maybe that but add a menu button to reenable it from there?
