### ISSUE TITLE
copy paste not working anymore

### ISSUE THREAD

**Issue by DavidBabel** [ramboxapp/community-edition#1133]
:(

**Comment by nmat** [comment]
Works for me on windows 10 and on MacOS

Need a bit more information on what you are doing and what service. Tested on facebook messenger and gitter.

**Comment by ryanpcmcquen** [comment]
I have a friend on Mac OS that cannot copy and paste in Wire.

**Comment by bretterer** [comment]
I was having this issue too.   It seems the new update has fixed things

Version: 0.5.14
Platform: darwin (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0
