### ISSUE TITLE
[Feature request] User Agent configurability or stealth

### ISSUE THREAD

**Issue by guyhughes** [ramboxapp/community-edition#1135]
### Steps to reproduce

1. Open DevTools
2. In the console, examine the output of`window.navigator.userAgent` 
    `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Rambox/0.5.12 Chrome/58.0.3029.110 Electron/1.7.5 Safari/537.36"`
3. Alternatively, examine the User-Agent header in the Network tab, Headers subtab, under the Request Headers folding section.
    `User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Rambox/0.5.12 Chrome/58.0.3029.110 Electron/1.7.5 Safari/537.36`

### Expected behavior

User-Agent header and window.navigator.userAgent may disclose that Rambox is being used but the version numbers should be withheld or masked, or this should be configurable after compilation.

### Actual behavior

User-Agent header and window.navigator.userAgent both disclose that Rambox is being used, and its version, and its component libraries' versions.

### ENVIRONMENT
Rambox: v0.5.12

OS: all? (macOS confirmed)

Arch: all? (x64 confirmed)

**Comment by wokawoka** [comment]
+1

**Comment by padok** [comment]
+1

Microsoft only allows the lite version of the Outlook Webapp (owa) on linux pcs.
