### ISSUE TITLE
Google Inbox Unread Badge and Notifications should not work outside folder Inbox

### ISSUE THREAD

**Issue by MarcusSpecht** [ramboxapp/community-edition#1136]
### Steps to reproduce

1. Open Google Inbox
2. Switch to any other folder (Snoozed, Done, Spam, etc.)
3. Or keyword search globally to get results from different folders

### Expected behavior

In Google Inbox you often move mails to done or snoozed without actually reading them. Those mails should not trigger a badge update or notification since they have already left the inbox.

### Actual behavior

While browsing for mails the Badge constantly changes and notifications are firing.

### ENVIRONMENT

> Rambox: 0.5.10
> Elevtron: 1.7.4
> Node: 7.9.0
> OS: Windows 10 (up to date)
> Arch: win32 (x64)

**Comment by eindiran** [comment]
I reproduced the problem in the following environment:

Rambox: 0.5.12
Electron: 1.7.5
Node: 7.9.0
Chromium: 58.0.3029.110
OS: Ubuntu 16.04, running kernel 4.4.0
Arch: x86_64

**Comment by mikeboltonca** [comment]
I can reproduce this problem as well. In Inbox, I can select another container (e.g. Done, Sent, Spam) or perform a mail search; the messages that get displayed are added to Inbox's notification counter. As I scroll and reveal more messages, they get added as well.
