### ISSUE TITLE
Can't call in Skype (Linux)

### ISSUE THREAD

**Issue by averageunicorn** [ramboxapp/community-edition#1138]
### Steps to reproduce

1. Try to make an audio call in Skype

### Expected behavior
The other person receives the call and can answer it. If for some reason it can't work, I shouldn't be able to call, or it should fail visibly.

### Actual behavior
It looks like it is ringing from my side, but the other person doesn't receive a call.

(I didn't have a chance to ask what OS they were on, and I don't call people frequently enough to know if this is always the case. It did, however, work when I switched to the android skype app, so the problem wasn't on their side.)

### ENVIRONMENT

> Rambox: v0.5.12

> OS: Ubuntu 16.04

> Arch: x64

**Comment by nmat** [comment]
Please see: https://github.com/saenzramiro/rambox/wiki/Skype

**Comment by averageunicorn** [comment]
@nmat thank you, I read that, but it says that for an audio call that you initiate, every combination should work.

**Comment by MurkBRA** [comment]
Need change the userAgent

`navigator.__defineGetter__('userAgent', function(){

return 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586';

});`

**Comment by saenzramiro** [comment]
@MurkBRA @averageunicorn User Agent is currently set up: https://github.com/saenzramiro/rambox/blob/592fa1eb09121cd19a61fb06dd7baa9ee140d146/app/store/ServicesList.js#L68

@averageunicorn Can you confirm if still not working?
