### ISSUE TITLE
Unable to view Rambox screen

### ISSUE THREAD

**Issue by rajsharma1612** [ramboxapp/community-edition#1139]
When I launch Rambox, it is hidden. Unable to view its screen but I am able to view all the menus.
By going to Window and selecting Enter full screen I am able to view. But again when I select exit full screen It gets hidden.
[Sep 11 2017 5-50 PM.webm.zip](https://github.com/saenzramiro/rambox/files/1291929/Sep.11.2017.5-50.PM.webm.zip)

	
	-
	> Rambox 0.5.12
	> Electron 1.7.5
	> darwin x64 15.6.0

**Comment by saenzramiro** [comment]
Did you change the display and close behavior in Preferences? What options did you select?

To fix it temporarily, please read here:

https://github.com/saenzramiro/rambox/issues/909#issuecomment-305854689
https://github.com/saenzramiro/rambox/wiki/Edit-configuration-manually

**Comment by Gaudenz77** [comment]
Not working, sorry.
