### ISSUE TITLE
Share Screen not available

### ISSUE THREAD

**Issue by ryanesizemore** [ramboxapp/community-edition#1141]
On both Slack and Hangouts, share screen does not function. Not sure if there is a way to fix this or not, but thought I would report it.
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 10.0.15063

**Comment by igalic** [comment]
I have 0.5.13 (the current latest version) on Linux.
when you try to share screen, electron isn't catching the request to pass it on (i suppose)

**Comment by alien2003** [comment]
Does not work on Wire too

**Comment by guzzard** [comment]
Discord not working either

**Comment by saenzramiro** [comment]
We will take a look.

**Comment by MurzNN** [comment]
This is problem in Chromium engine, it miss screen access api before 70 version (without installing special extension), in 70 version this api seems implemented: https://groups.google.com/forum/#!msg/discuss-webrtc/Uf0SrR4uxzk/uO8sLrWuEAAJ
Can you update chromium engine to 70 and recheck this problem?

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
