### ISSUE TITLE
[Feature Request] Custom logos in advance options

### ISSUE THREAD

**Issue by ryanesizemore** [ramboxapp/community-edition#1142]
For duplicates of services with different accounts, that aren't custom services, I would like the option to load different icons to more easily distinguish between them.

**Comment by wokawoka** [comment]
Indeed, that would be great

**Comment by jkischel** [comment]
Helpful might also be a CSS filter for the icons (if the icons are HTML/DOM objects) described [here](https://www.w3schools.com/cssref/css3_pr_filter.asp).

sample code:
`filter: hue-rotate(275deg);`
(should be nicely configurable via slide and preview, of course!)

This example explains what I mean:
Imagine you have three skype accounts. Changing hue and saturation would enable you to have one "blue" skype icon, one "red" and one "grey" skype icon, so you can differ between on first sight without having to waste space with text labels.

**Comment by vekexasia** [comment]
Maybe it could be enable through custom code injection?
