### ISSUE TITLE
[Request] Add pushover to the list of services

### ISSUE THREAD

**Issue by wokawoka** [ramboxapp/community-edition#1147]
Pushover (https://pushover.net/) is a very nice notification service similar to pusbullet (cheaper and overall much better in my opinion).

Pushover  already works perfectly on rambox by adding it as a custom service with the address https://pushover.net/clients/desktop and logging in+registering the device and then by using the address https://clients.pushover.net/ .

If someone would like to test it, it needs a cheap license of 5$ to work (for each platform needed: desktop, android or ios) but it's possible to try it for 7 days for free.

**Comment by jkischel** [comment]
Wouldn't it be easier to post your request in [this](https://github.com/saenzramiro/rambox-services-contrib) repository?
