### ISSUE TITLE
Mastodon / Slack: Custom Logos

### ISSUE THREAD

**Issue by igalic** [ramboxapp/community-edition#1153]
### Steps to reproduce

1. Add another mastodon / slack instance 
2. Notice that all the Logos look the same
3. look confused

### Expected behavior

Either the Logo is pulled from the instance, _or_ we are given a Logo URL to fill

### Actual behavior

All Mastodon / Slack logos look the same.
This is mildly confusing.

### ENVIRONMENT

> Rambox: v0.5.12

> OS:  linux (x64)

> Arch: x64

**Comment by bretterer** [comment]
Slack Reference: https://github.com/saenzramiro/rambox/issues/113

**Comment by saenzramiro** [comment]
Slack will be added in next release.

For Mastodon, let's see if someone can make a PR for that. :)
