### ISSUE TITLE
Fails to mark window as urgent or flash taskbar.

### ISSUE THREAD

**Issue by kingy9000** [ramboxapp/community-edition#1155]
### Steps to reproduce
1. Have Rambox unfocused.
2. Receive message.

### Expected behavior
Rambox would "Flash taskbar" or mark itself as urgent as it did in previous versions.

### Actual behavior
Rambox doesn't mark itself as urgent even with "Flash Taskbar on new message" set in preferences.

Have tried reinstalling Rambox after removing all config files but issue still persists.
Issue could be with i3-wm but I believe it's with Rambox.

### ENVIRONMENT
> Rambox: v0.5.12

> OS: i3-wm 4.14 running on Arch Linux

> Arch: x64

Thanks for your time

**Comment by wedens** [comment]
I have the same problem with 0.5.13. It worked before, after https://github.com/saenzramiro/rambox/issues/665 was implemented.

**Comment by t-animal** [comment]
Same here using xfce4 on arch linux.

**Comment by flexo3001** [comment]
Urgent hint isn't working for me too.

Version: 0.5.17
Platform: linux (x64) (Fedora with i3wm)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

**Comment by wedens** [comment]
Rambox already calls `win.flashFrame`: https://github.com/saenzramiro/rambox/blob/3a4c89bd65c23284640d3f098c0b449f96ab6075/electron/main.js#L296.

For some reason it doesn't work.
