### ISSUE TITLE
Rambox prevents the screen from being turned off

### ISSUE THREAD

**Issue by tracktraps** [ramboxapp/community-edition#1158]
Rambox prevents the screen from being turned off, whether open window or minimized as tray icon.

### Steps to reproduce

1. Open Rambox
2. Try to turn off the screen (I use usually slock (https://tools.suckless.org/slock/) in a bash script with xset dpms 0 0 30)

### Expected behavior

Screen should be turned off.

### Actual behavior

Screen remains on. The screen can only be switched off when Rambox is completely closed.

### ENVIRONMENT

Version: 0.5.12
Platform: linux (x64)
Electron: 1.7.5
Chromium: 58.0.3029.110
Node: 7.9.0
OS: 4.12.12-1-ARCH x86_64 (native) and Ubuntu 16.04 x86_64 (in a docker container)

**Comment by ehartmann** [comment]
I have the same issue with 0.5.13.
