### ISSUE TITLE
always asking for login and pass to each gmail account.

### ISSUE THREAD

**Issue by MANOJ91** [ramboxapp/community-edition#117]
## 

> Rambox 0.4.0
> Electron 1.2.6
> darwin x64 15.5.0

**Comment by saenzramiro** [comment]
Are you checking the checkbox for remembering? I suppose it's a yes.

Try to logout, and re-login again. If you don't have any account, try removing all your services, restart Rambox, add a Gmail service, login and restart Rambox to see if session still alive.

**Comment by MANOJ91** [comment]
I don't think there's a checkbox to remember me

I've logged into rambox
I've removed all Gmail services and added again 1 Gmail
And quit and reopened

I logged in to the added Gmail service
And quit and reopened rambox
It asks the login and password for the service
I'm still logged in rambox

**Comment by MANOJ91** [comment]
i uninstalled-using appdelete
empty bin
reinstalled
logged in to rambox with manoj91@gmail
stay signed in - gmail option always yes.

added 1 other gmail
quit, reopened
still logged into the gmail service
added gmail service no 2

quit
reopened and need to re enter login and pass for all 2 gmail services

still logged into rambox with manoj91@gmail


--
Manoj Keswani
manoj91@gmail.com
+852 6039 2099

**Comment by MANOJ91** [comment]
when logging into gmail , stay signed in is always checkbox ticked.
i leave that ticked yes.





--
Manoj Keswani
manoj91@gmail.com
+852 6039 2099
