### ISSUE TITLE
[Feature Request] Auto-start Do Not Disturb at specific time

### ISSUE THREAD

**Issue by nSimonFR** [ramboxapp/community-edition#1171]
This might be related to issues like #829, but I really like the __Do Not Disturb__ mode.

I find myself using it very often, which is why I think it could be enhanced, like I'd love to have __DND__ automatically launch at specific time *(9pm-8am for example)*, so that it synchronises with my Mac settings.

Or maybe just programmatically add a way to start it, so that people could make a script for it, instead of having to use the default __F1__ key or closing the application.

I know this fall at the bottom of the list of features you plan on for the future of Rambox, but I'm just leaving that out here !

**Comment by MurzNN** [comment]
Also will be good to enable DND mode on system idle, here is Node module that can check idle: https://github.com/bithavoc/node-desktop-idle
