### ISSUE TITLE
Skype - searching contacts issue

### ISSUE THREAD

**Issue by AmuleSolo** [ramboxapp/community-edition#1172]
On Skype via Rambox, cannot search contacts with the search bar (added or non-added contacts). Typing a name results in an infinite loading.
![image](https://user-images.githubusercontent.com/25842742/30694358-ab3e0040-9ee4-11e7-85bf-cfda62b66c80.png)

	
	-
	> Rambox 0.5.12
	> Electron 1.7.5
	> win32 x64 6.1.7601

**Comment by tdchien** [comment]
I'm facing this problem too.

![image](https://user-images.githubusercontent.com/1614393/31418849-8de16af4-ae62-11e7-9932-fe5910846ba1.png)

Version:
![image](https://user-images.githubusercontent.com/1614393/31418854-9960c80c-ae62-11e7-861c-61b0a1909e07.png)

**Comment by mayurdw** [comment]
I face the same issue

Rambox : v0.5.13
Platform: Windows 10 ( x64 )
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by youlogix** [comment]
I am also facing the same issue.

Version: 0.5.13
Platform: darwin (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by rkandilarov** [comment]
Same problem.
Version: 0.5.13
Platform: linux (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by rkandilarov** [comment]
Smth really strange... The same version on Ubuntu 16.04 does not have the error with the search box, only on 14.04...
