### ISSUE TITLE
Protonmail: no login/passwd autio connection

### ISSUE THREAD

**Issue by ghost** [ramboxapp/community-edition#1180]
Hi!

### Steps to reproduce

When start Rambox and open Protonmail, I must always enter login/passwd: no problem with other services (Tweetdeck, Mastodon...)

### Expected behavior

I hope my Protonmail account already connected !

### Actual behavior

No automatic connection.

### ENVIRONMENT

Portable Windows 32bits version under Windows 8. Same problem with AppImage version on Solus OS.

Thanks!

**Comment by dddw** [comment]
isn't this a security feature of protonmail?

**Comment by tiubuk** [comment]
Yeah, maybe.
I see that I'm mistaken in my request: autologin is probably not possible, but if Rambox could remember the login/password, it would be great! (This is the case on Firefox.) Then, I would simply click on the button to connect:)

Thank you

**Comment by M-arcus** [comment]
What about a user-script, that looks for the login-box, then enters your name and password and then submits the form? (very unsave of course, your password is saved in plaintext)

**Comment by maxmckenzie** [comment]
mmmm I had thought about this, but you don't want to expose your passwords like that.

maybe you could give ram box programmatic access to some entries in your keychain (mac) and whatever that is in windows/linux
