### ISSUE TITLE
Make it visible in all tabs that "Don't Disturb" is enabled

### ISSUE THREAD

**Issue by CreamyCookie** [ramboxapp/community-edition#1182]
Recently I wondered why I couldn't hear a friend, even though he could hear me. After lots of messing around, it turned out that "Don't Disturb" was enabled. It would be great if there was an always visible icon or so to indicate that that it's enabled.

**Comment by rootwork** [comment]
Ideas:

• Color the tab bar
• Add a toggle to the tab bar, showing current state
• Color the status bar in every app (bottom of screen)
• Add a toggle to the status bar in every app
• Add a menu item to enable/disable that is checked or unchecked (not sufficiently visible on its own in my opinion -- there's a ticket for this in #1520)
• Add a badge to the app icon itself (seems like this might be trickier across OSes)

Other ideas?

**Comment by CreamyCookie** [comment]
Yeah, I think it makes sense to allow users to enable "Don't disturb" per Service, so the best option is probably to have status bar that displays something like

> "Don't disturb" is active for this Service | [Disable?](http://github.com)

or if it's active for Rambox as a whole:

> "Don't disturb" is active | [Disable?](http://github.com)

I think it would be best, if this was a "top bar" (just like the one that tells you there's a new version), rather than a status bar (at the bottom), since the former is harder to miss. 

To activate "Don't disturb" for a Service, you would right click on the respective tab and chose "Enable 'Don't disturb'".

**Comment by antoine-morisseau** [comment]
I plusse this feature.
I found this functionality quite useful but quite annoying since i forgot that i enabled the "do not disturb" mode.
a muted ring bell on the rambox icon in the taskbar and on the rambox tab would be a first solution.

**Comment by CreamyCookie** [comment]
Why wontfix?

**Comment by rootwork** [comment]
Yeah, it's stale because there hasn't been any recent conversation.

Is anyone interested in working on an option? I'm agnostic as to potential solutions suggested by others and myself above, so maybe if someone wanted to just pick one and put it up as a PR we could discuss it?

(I realize I don't have time to work on it myself, so this isn't an attempt to guilt others into doing the work. Just hoping that among the folks who think this would be useful, there might be someone who would be able to take it on.)

**Comment by maxerbox** [comment]
Bump

**Comment by CreamyCookie** [comment]
I don't get why "stale" bugs should get a `wontfix` label. It's normal in software development that certain non-priority bugs stay open for a long time (as others issues are more important), but that doesn't necessarily mean they will not be fixed. I think `wontfix` makes only sense when a developer has some reason for not fixing an issue / implementing a feature.

**Comment by CreamyCookie** [comment]
bad bot

**Comment by saenzramiro** [comment]
Ok, in new version 0.6.7 the tabbar is turned gray if DND is enabled. Hopefully this helps for you guys!

**Comment by CreamyCookie** [comment]
Awesome, thanks! :)
