### ISSUE TITLE
Windows 10 People Bar

### ISSUE THREAD

**Issue by Ludomancer** [ramboxapp/community-edition#1183]
Suggestion;

Windows 10 Creators Update People Bar integration.

Not sure if it is possible at all but People Bar has an Apps list with some similar apps like Skype etc. Would be nice to have RamBox integration as well.

I'm assuming Windows 10 would have some sort of API to tap into People Bar.

**Comment by saenzramiro** [comment]
It's a good idea, but we will have to wait until Electron release a native integration to do it, or via a Node JS library.
