### ISSUE TITLE
Keybase Teams support

### ISSUE THREAD

**Issue by nc623XH** [ramboxapp/community-edition#1190]
Not sure if it's technically possible, but it would be great to get Keybase.io or Keybase Teams support to Rambox.

Details: https://keybase.io/blog/introducing-keybase-teams

**Comment by DreamFlasher** [comment]
Is there keybase chat support for rambox available at all? (https://keybase.io/blog/keybase-chat)

**Comment by saenzramiro** [comment]
ASAIK, Keybase is a service you install it in any server and can be accessed via any browser. Am I wrong?

If so, you can use Custom Service option to add it to Rambox for now. In the future, we can see if this service needs a special code injected to read "unread messages".

**Comment by Trollwut** [comment]
Anyone got hands on that? Some experience?

**Comment by saenzramiro** [comment]
Not from me but I will add it to next release.

**Comment by Upgreydd** [comment]
@saenzramiro any news? Meybe your'e able to add keybase chat support? They have electron app.

**Comment by saenzramiro** [comment]
After a quick investigation, to use Keybase you need to install a Chrome extension and we currently don't support that.

Am I wrong?

**Comment by fvulich** [comment]
It seems that Keybase doesn't provide a web app, until this happen we can't add it to Rambox.
