### ISSUE TITLE
Account connection doesn't work

### ISSUE THREAD

**Issue by ghost** [ramboxapp/community-edition#1191]
Hi, when I want to create a new account within the app, I have just this popup :
![account_error](https://user-images.githubusercontent.com/31392275/31025496-1fb0893e-a543-11e7-955b-7054d6ad26ce.jpg)

Also on AppImage version.

	
	-
	> Rambox 0.5.12
	> Electron 1.7.5
	> win32 ia32 6.3.9600

**Comment by Ash258** [comment]
Not relevant anymore? Feel free to open if this problem still persists.

This anyway looks like temporary server issue.
