### ISSUE TITLE
How about QQ

### ISSUE THREAD

**Issue by hh23485** [ramboxapp/community-edition#12]
QQ is the most popular IM in China, which i'll use everyday. So how about to support the QQ (Tencent Inc.)?

**Comment by saenzramiro** [comment]
Sounds cool! I will take a look for next release. Thanks!

**Comment by saenzramiro** [comment]
For now you can add it manually.

https://github.com/saenzramiro/rambox/wiki/Add-a-Custom-Service

**Comment by saenzramiro** [comment]
Hey @hh23485, I have some question's about QQ:

1. Did you install QQ as a Custom Service? If yes, continue.
2. What URL did you use?
3. Are badges in tab worked? Or did you have to add a javascript code in advanced section?

Thanks!

**Comment by Xujiayang12** [comment]
Soooooo great
