### ISSUE TITLE
Telegram starts in mobile mode

### ISSUE THREAD

**Issue by yaron-tracxpoint** [ramboxapp/community-edition#1201]
### Steps to reproduce

1. Restart Rambox
2. Switch to the Telegram tab
3. The interface presented is the mobile one, not the desktop webogram

### Expected behavior

Start in desktop mode for webogram

### Actual behavior

Starts in mobile mode for webogram

### Bypass method

Right click the Telegram tab and select refresh

### ENVIRONMENT

> Rambox: v0.5.12

> OS: Manjaro 17.0.5 (Kernel 4.13.3)

> Arch: x64

**Comment by infinitesupermagic** [comment]
same thing happens on osx, rambox 0.5.13

**Comment by yaron-tracxpoint** [comment]
No news yet?
