### ISSUE TITLE
Start minimized no longer works after updating to 0.5.13

### ISSUE THREAD

**Issue by kennethso168** [ramboxapp/community-edition#1205]
### Steps to reproduce

1. Configure preferences as below
![image](https://user-images.githubusercontent.com/5262487/31228819-5c8e52aa-aa11-11e7-8982-ab5191ddce95.png)

2. Quit and start Rambox again

### Expected behavior

Rambox will start minimized at the system tray. (Tested and this works in 0.5.12)

### Actual behavior

Rambox will start with a window present in 0.5.13. Toggling start minimized has no effect.

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Manjaro KDE (installed from Arch User Repository)

> Arch: x64

### Notes

I am sure this is a regression as it works in 0.5.12 but not in 0.5.13.
Upon further testing, start minimized works again in 0.5.13 by setting "Display behaviour" to "Show tray icon" only.
This issue may also be related to issue #909 being fixed. Thank you.

**Comment by glolsh** [comment]
Same on Xubuntu x64 16.04.3

**Comment by Bulletninja** [comment]
I'm having the same problem in MacOS High Sierra, I'm pretty sure I have the latest version, unfortunately I can't confirm the current version in the about section because is not displayed either.

**Comment by orschiro** [comment]
Can confirm on Fedora 27.
