### ISSUE TITLE
 Incorrect Notifications When You Rename a Service

### ISSUE THREAD

**Issue by manuegzl** [ramboxapp/community-edition#1212]
Hello community, I would like to contribute to solving a Rambox problem. In configuration you can change the name to the services, well if you do that and put a number, example m.gonzalez2 (one of my emails), there will always be two notifications even if all the crimes have been read when minimizing the program, if you put an 8 as it is known that there are 8 notifications unread and so on. Please fix it, thank you.

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.15063

**Comment by thedonquixotic** [comment]
How do you rename a tab?

**Comment by Ash258** [comment]
@thedonquixotic 
1. Just go to rambox tab, find service you want to rename
1. Click gear icon (configure) ![hint](https://i.imgur.com/jj9j5gh.png "hint")
1. Change name

@manuegzl This issue should already be solved in #1250 (version 0.5.14)
