### ISSUE TITLE
[Request] Add Upwork to the list of services

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [ramboxapp/community-edition#1214]
Upwork is the №1 platform for freelancers, and it includes a chat system. It would be great to include it to the list of services.

It already works correctly using Custom Service.

URL: https://www.upwork.com/messages/
Logo: https://www.upwork.com/favicon.ico

**Comment by kovtunos** [comment]
> It already works correctly using Custom Service.

But doesn't show notifications.

**Comment by ZimM-LostPolygon** [comment]
> But doesn't show notifications.
Obviously. Custom notification code needs to be written first.

**Comment by ZimM-LostPolygon** [comment]
@kovtunos 
Correction. Desktop notifications work just fine, only the unread message counter doesn't.

**Comment by BirsanStefan** [comment]
Hi,
I've also added upwork to rambox.
Here is the code for the unread message counter that works for me. Feel free to improve on it:

function checkUnread() {
    var e = document.getElementsByClassName("room-list-item unread");
    updateBadge(e.length);
}

function updateBadge(e) {
    e >= 1 ? document.title = "(" + e + ") " + originalTitle : document.title = originalTitle
}
var originalTitle = document.title;
setInterval(checkUnread, 5000);

**Comment by Ash258** [comment]
@BirsanStefan I would suggest only small tweak inside `updateBadge` function:

```js
function updateBadge(e){
    e >= 1
        ? rambox.setUnreadCount(e)
        : rambox.clearUnreadCound()
}
```

**Comment by BirsanStefan** [comment]
@Ash258 Thanks! Looks cleaner and better!
