### ISSUE TITLE
Rearranging of tabs not working properly

### ISSUE THREAD

**Issue by hubitor** [ramboxapp/community-edition#1215]
### Steps to reproduce
1. Select a tab with left mouse button. 
2. Move the tab to the left or right by dragging. 

### Expected behavior
All tabs can be moved left or right by selecting and dragging with the left mouse button. 

### Actual behavior
Sometimes rearranging of tabs work sometimes it doesn't. In particular the last tab is stuck, it cannot be moved to the left.

### ENVIRONMENT
> Rambox: v0.5.13
> OS: Arch
> Arch: x64

**Comment by theCyanEYED** [comment]
Same issue here (v0.5.13, Windows x64)
