### ISSUE TITLE
Got a JavaScript error after changing the tab

### ISSUE THREAD

**Issue by ollrich** [ramboxapp/community-edition#1220]
As you can see in the screenshot. When my PC was in Sleep and woke up I got this JavaScript Error in Rambox after changing a tab

![rambox_error](https://user-images.githubusercontent.com/26229613/31355307-ffbd0b8a-ad39-11e7-8a75-6bdd565b7b11.gif)

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.15063

**Comment by Bebef** [comment]
Is this error reproducible?

**Comment by ZimM-LostPolygon** [comment]
I'm getting the same error as well.

**Comment by WillPresley** [comment]
The main way that I reproduce is definitely changing the tab once the error appears.

**Comment by Ash258** [comment]
Continue in #1656
