### ISSUE TITLE
All services are misplaced!

### ISSUE THREAD

**Issue by jendigital** [ramboxapp/community-edition#1222]
I can't chat anymore because the input never appear on slack / whatsapp / messenger, i can't send mail cauz i can't see gmail button to send e-mail 😭😱

**Comment by Bebef** [comment]
Have you tried clearing the cache?

**Comment by jcalonso** [comment]
Same problem here, clearing cache doesn't fix it.

**Comment by jcalonso** [comment]
Another issue related to this: https://github.com/saenzramiro/rambox/issues/1221

**Comment by Bebef** [comment]
Maybe the issue is related to the HiDPI-Settings?

**Comment by jcalonso** [comment]
@bebef I think is related to this commit: https://github.com/saenzramiro/rambox/commit/9dd5380f60d96e0da70bb057192aa67d59efd50f#diff-0e18ebb3897085a90a855cb2dee76f8b

Another dupe: https://github.com/saenzramiro/rambox/issues/1226

**Comment by aliusratio** [comment]
Having the same issue. I can zoom some apps enough to see the input but the fonts are like one inch tall. Under Hangouts I can just get the top left corner of a chat window to appear with zoom.
This occurs under both HiDPI and without HiDPI. 

>inxi -S
Kernel: 4.4.0-89-generic x86_64 (64 bit)
Desktop: Cinnamon 3.2.7  
Distro: Linux Mint 18.1 Serena

**Comment by Paaltomo** [comment]
I'm not exactly sure what I did, but I got around this by:

- Checking hidpi + hardware accelleration are disabled
- Maximizing the window
- Selecting "View" > "Actual Size" from the menu
- Reloaded, seems to still be fixed

@jcalonso your tip about the commit made me think it could be a multi-monitor + Linux issue. Let me know if there's any extra info or logs I can send to show what fixed it. 

```
Version: 0.5.13
Platform: linux (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0
```

**Comment by jcalonso** [comment]
thanks, @Paaltomo  in my case Enabling HDPI and resetting zoom (View-> Actual size) did the trick.

**Comment by saenzramiro** [comment]
@jendigital Did this fix your problem?

**Comment by jendigital** [comment]
no i've abandonned rambox to franz cauz of the zoomin issue even if i
founded the former version of rambox more attractive

2017-10-24 16:40 GMT+02:00 Ramiro Saenz <notifications@github.com>:
