### ISSUE TITLE
extremly slow startup because hooks.tooltip.io times out.

### ISSUE THREAD

**Issue by macrozone** [ramboxapp/community-edition#1224]
### Steps to reproduce

1. Install rambox freshly
2. launch it

### Expected behavior

Should show configure screen after < 5seconds

### Actual behavior

It shows the loading animation (the monkey) for nearly a minute!

### ENVIRONMENT

> Rambox: 0.5.13

> OS: mac os high sierra

> Arch: x64

Problem seems that, `https://hooks.tooltip.io/player/fetch/sEF8shc4KSuqtHMx0ztmTFdcrQO0cAVpszZ9Y…lback=jQuery22407261543144170797_1507626338505&format=json&_=1507626338506 `

times out. It should not wait on that resource to launch. Rambox should not rely on external code to launch

**Comment by gingerbeardman** [comment]
tooltip is garbage, it should be removed

**Comment by gingerbeardman** [comment]
Stale but still an issue
