### ISSUE TITLE
Better UI Layout with Example

### ISSUE THREAD

**Issue by ylluminate** [ramboxapp/community-edition#1225]
There is a much superior way to present the services in the UI. This is currently done in a program called One Chat. It is much better with the wider monitors that now proliferate the world. Here's an example of how the bar can be displayed vertically to excellent effect:
![example](https://cl.ly/1T0q223s1Y1K/Image%202017-10-10%20at%2012.17.51%20PM.png)

Here is a "normal" mode that has a wider bar, but the narrower option above is most certainly superior for most users:
![normal example](https://cl.ly/0N122J3v172O/Image%202017-10-10%20at%2012.18.19%20PM.png)

**Comment by Shmasya** [comment]
Bad of you designer.

**Comment by vraravam** [comment]
I am also searching for a way to make the nav bar or tab bar be vertical. Also, having an option to only show the icon vs icon + text would also be great!
This is in the CE version 0.5.17
