### ISSUE TITLE
Chat/text field at the bottom of messaging panes are missing

### ISSUE THREAD

**Issue by arjones2009** [ramboxapp/community-edition#1226]
I am new to RamBox and decided to try it today.  I added all of my accounts and now I am noticing on all messaging/collaborations accounts, the box to type messages into is missing. It appears that many of them are missing because the size is too large(the content).  I've zoomed out as far as it will let me and it still will not show up.  However, even slack zooms out all the way, but still does not display a place to enter text to post.  I've tried searching everywhere and I can't find a fix for it.  Any ideas?

![image](https://user-images.githubusercontent.com/12838450/31408411-a9bac600-adc5-11e7-9ae0-a6fcb300ed07.png)

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> darwin x64 17.0.0

**Comment by superted17** [comment]
Thanks - btw you should update your comment, it's included your phone number from your email sig

**Comment by superted17** [comment]
I got it working. I'm on Ubuntu and I had to totally remove the binaries and desktop entry, and re-install but this time using the deb package

**Comment by metal3d** [comment]
Seems to be linked to #1057 - the problem can be temporary fixed using devtools and changing max-width and max-height to 90% 

But why is that happens on certain configuration and not on others ?
