### ISSUE TITLE
Black screen, reloading does not work, developer tools do not show

### ISSUE THREAD

**Issue by svenMOrd** [ramboxapp/community-edition#1228]
When I open rambox, all I see is a black screen (see attachment) , I cannot open settings or developer tools. But when I click developer tools and press F5 the screen flickers for a moment and then turns black again. 

![rb](https://user-images.githubusercontent.com/24450744/31430192-6cd36b24-ae70-11e7-8b43-00abc94d101f.png)

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 6.1.7601

**Comment by Paaltomo** [comment]
I also ran into this issue after an update and shows similar results:

![Screenshare](https://media.giphy.com/media/3ohjV0MxFX7dCXGn9m/giphy.gif)

Disabling hardware acceleration fixed it, after finding the solution here: https://github.com/saenzramiro/rambox/issues/181#issuecomment-247207471

```
Version: 0.5.13
Platform: linux (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0
```

**Comment by vytasek** [comment]
Same issue here after the last 0.5.13 update on multiple Windows 7 machines. Disabling acceleration helps.

**Comment by svenMOrd** [comment]
Disabling the acceleration does indeed help. I created a shortcut with the parameter, but windows doesn't use that one at boot, so I changed it in the settings. It is annoying that that option cannot be set when I had the black screen, because the settings screen is not usable.  
Could it maybe be moved to a real menu item? So people can use it if they have the problem? 

Thanks

**Comment by Paaltomo** [comment]
Hey @svenMOrd, there should be an option in the preferences menu on the Rambox tab to the left. 

![Preferences menu](https://i.imgur.com/xhsHOIk.png)

It's there almost at the bottom

**Comment by svenMOrd** [comment]
There is indeed an option, 
but the preferences screen was also entirely black, so I could not enable it when I had the problem, only after I started with the command line switch.

**Comment by YMRTN** [comment]
Hi svenMOrd, 

I wasn't able to disable hardware acceleration, but a clean install fixed the issue for me.

**Comment by rwese** [comment]
Updated today, now I've got a black screen too.
Also with ``rambox.exe --disable-gpu`` I have a black screen.

I'm on Windows 7, Multi-Screen.

**Comment by liwenjing93** [comment]
Hi everyone, i got a problem with black screen, but because it is black screen so I can not see anything in preference, then I can not disable hardware acceleration, how can I fix it? Thanks

**Comment by liwenjing93** [comment]
Hi everyone, I found the solution now, check this link: https://github.com/saenzramiro/rambox/issues/1202

Change the config file in %appdata%\Rambox , disable hardware acceleration, kill all the Rambox Processes and start it again.

![screenshot_1](https://user-images.githubusercontent.com/9654732/33248680-cf0be35e-d358-11e7-9286-cb12f51b58a2.jpg)
