### ISSUE TITLE
Stop missive from opening links in the app

### ISSUE THREAD

**Issue by ghost** [ramboxapp/community-edition#1229]
I got missive connected and whenever I click an email link, it opens in the default mac browser, but it also opens it inside of missive, essentially replacing the missive inbox. I'd have to manually select the back button which is annoying because there isn't any shortcut for it :(

Couple of questions:
1. Is there a short for the `Back` button when i right click an app?
2. Is there a way to block links that open in default mac browser?
3. Is there a way to block missive from following web links?

Cheers,
Piotr

**Comment by Mumrau** [comment]
I'd like to up this issue as I'm facing the same issue and it gets pretty annoying.

(I'm using CTRL+R, which reloads just the currently used service. Given the fact that missive is pretty lightweight, it goes fast enough.)
