### ISSUE TITLE
JavaScript error after resuming from hibernation.

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [ramboxapp/community-edition#1233]
### Steps to reproduce

1. Put computer to hibernation.
2. Exit the hibernation.
3. Observe error (sometimes).

### Expected behavior

Rambox should work normally after computer is resumed from hibernation.

### Actual behavior

After exiting the hibernation, I occasionally get this error:
![default](https://user-images.githubusercontent.com/928550/31483333-30ef942c-af2c-11e7-8ba9-5c77abe051be.png)

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Windows 10 Home

> Arch: x64

**Comment by ZimM-LostPolygon** [comment]
The error just happened again while I was typing a comment (not when exiting from hibernation).
The path is different, though.
https://github.com/saenzramiro/rambox/issues/1220

**Comment by toineenzo** [comment]
Same problem here:
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.15063

I get this same error message after getting out of hibernation and most of the time when I receive a Whatsapp message in the background

**Comment by WillPresley** [comment]
I also have this error after coming out of sleep. I can very easily reproduce it by changing to other tabs in Rambox. Each time causes the same dialog as shown above.

**Comment by Ash258** [comment]
Continue in #1656
