### ISSUE TITLE
Rambox tray icon not showing notifications (aka turning red) when Slack has new messages

### ISSUE THREAD

**Issue by hermco** [ramboxapp/community-edition#1237]
### Expected behavior

Rambox tray icon should turn red (show notification) when Slack has new messages.

### Actual behavior

Rambox tray icon not showing notifications (aka turning red) when Slack has new messages.
In Rambox, the slack tab works fine and shows notifications just fine.
I have checked "Show System Tray indicator on unread messages".

### ENVIRONMENT

> Rambox: latest, don't know where to find the number.

> OS: W10

> Arch: x64

**Comment by hermco** [comment]
Seems that this behavior is because I have chosen to be notified only for direct messages & stuff. 

I thought the tray indicator had the same behavior than Slack's one, aka when there is a new message a blue dot appears on the indicator. But that is not the case, Rambox's tray indicator works purely with raw notifications. In my case that means when I'm mentionned or receive a personal message.

Is there a way to have Rambox tray indicator to behave like Slack and the blue dot ? Aka any message and Rambox indicator turns red, even if it is not strictly a notification (mention or mp) ?

**Comment by wmertens** [comment]
Came here to ask the same thing - so Rambox would need to support both a notification count and a  generic "things changed" status.

**Comment by kreuzman** [comment]
I have exactly same problem with Slack.

Version: 0.6.2
Platform: linux (x64)
Electron: 2.0.8
Chromium: 61.0.3163.100
Node: 8.9.3
