### ISSUE TITLE
Problem with displaying apllication window

### ISSUE THREAD

**Issue by tomciak** [ramboxapp/community-edition#1242]
Hello
After the last update I have problem with display application window. The application window is still black:-(

Regards,
Tom

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 6.1.7601

**Comment by ccoulang** [comment]
Same issue for me with last Update 0.5.13  (Windows 7 x64 Enterprise /  Intel HD Graphics 520)
