### ISSUE TITLE
Can't install the 0.5.13 version on Fedora 26

### ISSUE THREAD

**Issue by johnnyasantoss** [ramboxapp/community-edition#1243]
### Steps to reproduce

1. Get a fresh Fedora 26 installation
2. Download x64 rpm in GitHub releases of Rambox's repository.
3. Install and try to execute.

### Expected behavior

Open without errors

### Actual behavior

It fails with this error:
```bash
/opt/Rambox/rambox
/opt/Rambox/rambox: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```

### ENVIRONMENT

> Rambox: v0.5.13
> OS: Fedora 26
> Arch: x64

**Comment by bartmanus** [comment]
Missing dynamically linked libraries on vanilla F27 beta install:
```$ cat /etc/redhat-release 
Fedora release 27 (Twenty Seven)
$ ldd /usr/local/bin/rambox | grep not\ found
	libnode.so => not found
	libXss.so.1 => not found
	libffmpeg.so => not found```

**Comment by diego-go** [comment]
I got the same issue as @bartmanus, I already installed libXScrnSaver and nothing, still got the problem message:
`./rambox: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`

**Comment by diego-go** [comment]
I got the same issue as @bartmanus but finally I resolve it doing `pkcon install libXScrnSaver` and Rambox start well

**Comment by Ash258** [comment]
Duplicate of #1035
