### ISSUE TITLE
The links won't open in the default browser

### ISSUE THREAD

**Issue by peinfant54** [ramboxapp/community-edition#1251]
Every time that I push in a link, Rambox open a new empty window (has all the menus at the top). I haven't found any options in the configuration, to set a browser...... What can I do?

Thanks

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.10.0-37-generic

**Comment by youlogix** [comment]
Even I am facing the same issue. Kindly suggest.

**Comment by Bloggerschmidt** [comment]
I have the same behavior by clicking a link in TweetDeck and Mastodon. Rambox opens a blank white new window in Chrome, even when the browser is already open.

**Comment by markkorput** [comment]
+1

**Comment by evancaldwell** [comment]
+1

**Comment by Regaddi** [comment]
+1

**Comment by Regaddi** [comment]
Rollback doesn't solve the problem.

**Comment by Regaddi** [comment]
Seems to be an issue with Chrome itself. After updating and restarting Chrome I can open links again.

**Comment by ryanmcstay** [comment]
Updating and restarting Chrome fixed the issue for me
