### ISSUE TITLE
Really want sound in Rambox to work

### ISSUE THREAD

**Issue by AndrewL733** [ramboxapp/community-edition#1253]
I am a huge fan of what Rambox is trying to do.  Having 4 or 5 or more different IM's is a pain, and tying them all together in one UI is a fantastic idea.  But, it's becoming an exercise in frustration for audio, at least on OS X (for those who care, OS X 10.12.4 and Rambox v0.5.13)

The biggest issue seems to be that the audio devices selected by Rambox don't make any sense.  You might be listening through bluetooth across all apps on the Mac, but then Rambox tries to play the audio through a different device -- and of course you don't hear anything.  It's not using the automatic selections that other Mac apps seem to manage to use correctly.  Sometimes I find Rambox trying to play through Airport or Headphones when I'm not using either. So, I can't hear people on phone calls/voice chats.  Then I have to go into Rambox settings and change the audio output. 

Same for input.  I'll be using my built-in Mac mic for everything, but I'll go into Rambox (when it's not working) and see that it has "line in" selected.  So, people can't hear me.  

Hangouts and Skype audio are both sporadic, and there's no WhatsApp audio.  Sometimes quitting and restarting helps.  Sometimes not. 

As I said, I want to like Rambox and use it  instead of 4 other IM apps, but it's becoming a no-go for me. Is there a solution for this?

**Comment by cirelli94** [comment]
The same is happening to me on Arch Linux.
