### ISSUE TITLE
whatsapp flickering

### ISSUE THREAD

**Issue by dobe** [ramboxapp/community-edition#1259]
when using whatsapp the content gets messed up when moving the mouse. also sometimes the text input field starts to flicker every second. it looks like a redraw issue. no issues on the main views of other services - however viewing pdfs i gmail sometimes is broken.

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.4.0-97-generic

**Comment by ghennequin** [comment]
same issue here, though not only with whatsapp (slack, and especially in the service configuration pop-ups where after moving the mouse around the entire window ends up flickering and eventually disappearing)
