### ISSUE TITLE
A Javascript error occurred in the main process message

### ISSUE THREAD

**Issue by PeterVerzijl** [ramboxapp/community-edition#1264]
### Steps to reproduce

1. I don't know. I just happened while running in the background. See the following image for the error that I received.
2. Now that I think about it, could it have something to do with me updating node for personal projects? (I also use electron and node for projects.)

![image](https://user-images.githubusercontent.com/5670225/32120116-b2f74bcc-bb57-11e7-805c-228da755fd2b.png)

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Windows 10 Fall Anniversary Edition (Version	10.0.16299 Build 16299)

> Arch: x64 system and os

If you have any other questions, feel free to ask.

**Comment by Ash258** [comment]
Continue in #1656
