### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by ghost** [ramboxapp/community-edition#1269]
### Steps to reproduce

1. Get a new message in Skype

### Actual behavior

Error window opens

> Rambox: v0.5.13

> OS: Windows 10 Pro

> Arch: x64
![2017-10-29 17_12_21-error](https://user-images.githubusercontent.com/25160711/32145708-6c72900e-bccd-11e7-933a-62cc134ceced.png)

**Comment by Ash258** [comment]
Continue in #1656
