### ISSUE TITLE
Rambox eats a lot of RAM, possible memory leak?

### ISSUE THREAD

**Issue by sonicolasj** [ramboxapp/community-edition#1276]
I'm sorry if it's a bit fuzzy, and I'm not sure anybody'll be able to reproduce it, but Rambox ended up eating something like 13GB of my RAM, after leaving the computer idling for some time.

### Steps to reproduce

1. Configure Rambox to use Facebook Messenger, Skype, Discord, and PushBullet
2. Leave the computer idling for more than an hour

### Expected behavior

Rambox should use a reasonable amount of RAM (up to 1 GB for 4 services?).

### Actual behavior

Rambox uses a *huge* amount of RAM, up to 13GB. 

![rambox_2017-11-01_17-28-04](https://user-images.githubusercontent.com/5695526/32285812-c0fac438-bf2b-11e7-9b4f-670aae17a0f7.png)
![taskmgr_2017-11-01_17-27-44](https://user-images.githubusercontent.com/5695526/32285813-c11a7616-bf2b-11e7-998a-fd0b628bd14b.png)

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Windows 10 N (with Media Features Pack)

> Arch: x64

**Comment by threewholefish** [comment]
Same issue, with Messenger, Whatsapp, Inbox, Pushbullet, Mattermost and Discord. v0.5.13, Windows 10 Pro, x64

**Comment by Doideira** [comment]
I didn't get this kind of problem (yet)... with Telegram, Whatsapp, Skype, FB Messenger, Hangouts, OpenMailBox and Gmail, Rambox eats about 1,5 Gb, v0.5.13 on Debian 9.1 (amd64).
Btw, I think 1,5 Gb already is a huge amount of RAM (for an app that, I suppose, only sits there and pings net seeking for a notification... sorry, I'm not a programmer, I don't really know the requirements for the task).

**Comment by mirfilip** [comment]
OSX 10.12.6
Version: 0.5.13
Platform: darwin (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

Since `0.5.12`, something leaks. Always had two services: WhatsApp, FB Messenger. These numbers are a norm, regardless of usage patterns:
![image](https://user-images.githubusercontent.com/1812341/32597195-43e65ed8-c536-11e7-9239-70bdc65bf385.png)

Granted, I don't shutdown my mac book and I have Rambox running all the time, but I'd expect a proper garbage collecting.

Also, I noticed `coreaudiod` can take up to 2GB of memory when Rambox is running. When I kill all Rambox processes and `coreaudiod`, the latter restarts and takes around 200MB. As soon as I start Rambox, `coreaudiod` gradually takes more and more. This is too strong of a correlation.

**Comment by Paaltomo** [comment]
Have you tried disabling Hardware Accelleration and HiDPI support in the Rambox settings? This seems to be a common fix for this issue.

**Comment by Doideira** [comment]
In my case, both hardware acceleration and HiDPI support were already disabled.

**Comment by mirfilip** [comment]
In my case, HiDPI is disabled, Hardware Acceleration is enabled. Why would I want to disable it? It should lessen the CPU / memory burden when enabled, unless it's buggy.

**Comment by M0UL** [comment]
both my gmail tabs are using more then 200mb ram with is twice the ram other tabs uses for me.

**Comment by luishdez** [comment]
Same problem in Mac it goes to 3Gb of Ram usage and keeps going up with Whatsapp and Skype.

**Comment by Mikpol** [comment]
Same issue, this time on Linux with Gmail, Discord, Skype, Whatsapp and Steam

**Comment by localhorst** [comment]
Using Rambox on Windows 10. 

Version: 0.5.17
Platform: win32 (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

I had memory issues with Pushbullet, around 7.5GB RAM where in use just for the Pushbullet tab. 

Hardware Acceleration was enabled,
HiDPI was disabled. 

After removing Pushbullet, values went back to normal. 
Disabling Hardware Acceleration seems to get values back to a bareable limit (< 150MB per tab)

Greets: Mateng

**Comment by iBobik** [comment]
12 services on a macOS, a few minutes after start:
![snimek obrazovky 2018-10-08 v 14 08 51](https://user-images.githubusercontent.com/614232/46608082-c11c5500-cb03-11e8-85fd-d85f52ffa920.png)

When I kill that first process eating 1GB the whole Rambox UI restarts, so this is probably Rambox itself and not some service.

**Comment by cryoff** [comment]
I have similar issue on ubuntu 16.04, rambox 0.6.1: eats 1.6 GB with WhatsApp, FB, hangouts and Discord

**Comment by iBobik** [comment]
The issue still occurs.
