### ISSUE TITLE
Problem with telegram

### ISSUE THREAD

**Issue by rehannali** [ramboxapp/community-edition#1284]
I have a problem with telegram service. All chat clients are working fine and telegram keep saying "connecting" or "waiting for network".
Any suggestions related to this problem. I uploaded screenshot related to this problem.
Thanks

![screenshot_5](https://user-images.githubusercontent.com/22426977/32364191-568e3d12-c095-11e7-91b0-2331018d87db.png)

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.16299

**Comment by Nikela0s** [comment]
The same issue. Telegram is not connecting while in Chrome browser everything is ok.
To temporary solve the issue it is necessary to use proxy (could be in the same country, e.g. Russia) in the app. So the problem is not in country network restrictions.

> Rambox: v0.6.2
> OS: Win10pro
> Arch: x64
