### ISSUE TITLE
No audio in discord, neither notification sounds nor voice 

### ISSUE THREAD

**Issue by sxe** [ramboxapp/community-edition#1287]
### Steps to reproduce

1. Add the discord service

### Expected behavior

When i use discord i want to be able to speak and her things (notifications or voices from other people). Neither works.

### Actual behavior

Silence (I don't even see a device popping up in my pulse audio audio device list)

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Arch Linux

> Arch: x64

**Comment by Tgo1014** [comment]
Can't manage to make my mic work either. Using rambox 0.5.13 on windows.

**Comment by lalaithan** [comment]
I'm having this problem on openSUSE.

**Comment by 14night** [comment]
Same exact problem, also Arch.
