### ISSUE TITLE
Automatic installation script for Linux - Ubuntu

### ISSUE THREAD

**Issue by Nifled** [ramboxapp/community-edition#1288]
This isn't really an issue but I don't know where this could be added. I recently installed a new distro (Mint KDE) and decided to make a script for installing Rambox automatically and I was able to do so succesfully. I feel like this can help out the Linux community, specifically people with Ubuntu based distros. I'm not sure if this can be added to the Wiki or not.

[Here is the script.](https://gist.github.com/Nifled/57e67090968ab402ceb2f86b5ac7e9fc)
It can be run using `curl`:
```bash
curl -s https://gist.githubusercontent.com/Nifled/57e67090968ab402ceb2f86b5ac7e9fc/raw/7402c0e4ca71664857aa97271c8b62662eaddf7e/install-rambox.sh | sh
```

The script downloads, installs, and references the Rambox desktop entry so everything is done automatically.

**Comment by Nifled** [comment]
Sorry, but why am I getting thumbs down???

**Comment by Nifled** [comment]
Is there a reason as to why I get downvotes for trying to make the installation process painless?

**Comment by rootion** [comment]
I don't know why the downvotes but the script is very helpful. Thank you!

**Comment by azahra1** [comment]
No

Pada tanggal 1 Jan 2018 20:06, "Cy" <notifications@github.com> menulis:

**Comment by 317** [comment]
It worked perfectly on Ubuntu 18.04. Thank you!

**Comment by Nifled** [comment]
Glad it could be of help to someone.

**Comment by el3ctrician** [comment]
Very helpful , worked like a charm on Linux mint mate 18.3
