### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by plasorak** [ramboxapp/community-edition#1291]
Heya,

So I think there is problem with the zooming. Essentially, I don't think you should be able to zoom or unzoom with the trackpad on a Mac, that makes the software very sensitive to trackpad movement and sometimes leads to unexpected behaviour. Or maybe there should be a way of "blocking" the trackpad zoom.
Also I'm not sure how it happened, but after such unwanted zoom, the write bar (where you type the message) just disappeared off the window with Slack, which is quite annoying. I don't really know how to reproduce the problem, except zoom and unzoom.
I've tried cmd-r or "reset zoom" or "zoom in", "zoom out". Also tried to restart, to move in and out of full screen and resize the window, without any luck.
I did manage to fix it previously but I can't actually remember how, and since this is the second time it happens today, well, I thought this was a potential improvement.

Anyway great app otherwise!
Cheers

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> darwin x64 17.2.0

**Comment by mirfilip** [comment]
Agree. Zooming seems totally obsolete here. I had many problems when using FB Messenger, clicking on a photo from the conversation, trying to zoom it to see some details -> it would lead to at least 3 different, weird behaviours throughout different versions of Rambox.

**Comment by Paaltomo** [comment]
> Also I'm not sure how it happened, but after such unwanted zoom, the write bar (where you type the message) just disappeared off the window with Slack, which is quite annoying. I don't really know how to reproduce the problem, except zoom and unzoom.

This could be related to a similar issue (https://github.com/saenzramiro/rambox/issues/1222) that was resolved by toggling HiDPI and Hardware Acceleration options in the settings. 

> I've tried cmd-r or "reset zoom" or "zoom in", "zoom out". Also tried to restart, to move in and out of full screen and resize the window, without any luck.

Try clearing your local cache and seeing if that helps at least with resetting it back to normal. If that doesn't work try removing the service, resetting the cache again, and re-adding it in the dashboard. Worked for me in the past.

> Zooming seems totally obsolete here.

I disagree here - with higher resolutions and some custom services, I've found it highly useful to be able to fit things just right in a certain window size.

**Comment by plasorak** [comment]
I get the following error:
```
VM745:1 Uncaught TypeError: Cannot read property 'keydown' of undefined
    at <anonymous>:1:12
  | (anonymous) | @ | VM745:1
-- | -- | -- | --
```
the command: `  if (event.ctrlKey == true) {` is offending?

I also tried what you proposed, but I'm afraid none of the solutions you mentioned worked.

https://github.com/saenzramiro/rambox/issues/1308
The new bug described here is describing the same problem.

**Comment by igoteasy** [comment]
This is what worked for me: 
[https://stackoverflow.com/a/40437495/8127262](url)

>$(document).ready(function(){
    document.body.addEventListener("wheel", zoomShortcut);
});

>function zoomShortcut(e){
  if(e.ctrlKey){            
    event.preventDefault();  
    if(e.deltaY<0){        
        return false;
    }
    if(e.deltaY>0){        
        return false;
    }
  }
}

Just add it as a custom script in the Service.

**Comment by dyorgio** [comment]
The solution above don't work on macbook-pro trackpad, zooming needs to have a option do disable.
