### ISSUE TITLE
Video call is not allowed in Teams

### ISSUE THREAD

**Issue by noamtamim** [ramboxapp/community-edition#1292]
### Steps to reproduce

1. Open Teams on Rambox
2. Try a video call

### Expected behavior

The video call button should be enabled and allow starting a video call.

### Actual behavior

The video call button is disabled; a tooltip says video is not yet supported in my browser.

### ENVIRONMENT

Version: 0.5.13
Platform: darwin (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by Paaltomo** [comment]
Video calls may not be supported, similar to the issue affecting Skype: 

https://github.com/saenzramiro/rambox/wiki/Skype

**Comment by brad** [comment]
@noamtamim I've made a PR to fix this. Until a build is made with the fix, you can fix it yourself by editing Teams configuration, opening the advanced settings, and pasting this:
```javascript
navigator.__defineGetter__('userAgent', function(){
    return 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.2883.87 Safari/537.36 Edge/12.246';
});
```
