### ISSUE TITLE
Disabling sounds in Skype also disables receiving audio during calls

### ISSUE THREAD

**Issue by j0ju** [ramboxapp/community-edition#1293]
If you enable "Mute all sounds" in settings for a skype account, you get no sounds as expected.
But you cannot do audio calls properly, you get now audio from  the other side as sounds are disabled.
The other side can hear you.
This might affect other account types.

### Steps to reproduce
1.  Create as Skype account.
2. Set "Mute all sounds"
3. Do a call

### Expected behavior

I do not get notifications sounds but can do calls properly.

### Actual behavior

I do net get notifications, but I cannot hear the other side during the call.

### ENVIRONMENT
Rambox: v0.5.13
OS: Linux Debian Jessie, Debian Stretch, Ubuntu Xenial
Arch: x64
Desktop Environmen: Tested on KDE4/5 or Fluxbox

**Comment by Paaltomo** [comment]
I believe that muting all sounds will also affect audio in calls. 

One way to work around this is to edit the settings within Skype to disable audio notifications while still allowing audio in the Rambox settings.

**Comment by j0ju** [comment]
Yes this work around would work.
In contrary disabling audio notifications is a global setting in Skype, so it would disable it on all rambox instances. My use case was to have clients with different notifications settings, but might be a special one.
I am not even sure if you can distinguish between notifcations sounds and audio furing calls.
Decide if that is interesting or not, I am unsure if this is a real bug.
