### ISSUE TITLE
Downloading image shared through Skype crashes Rambox

### ISSUE THREAD

**Issue by danorr** [ramboxapp/community-edition#1297]
Whenever I get sent an image file (or any file type for that matter) in skype, when I double click on it, Rambox crashes and a restart is required.

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.10586

**Comment by wiryonolau** [comment]
Hi mine crash on whatsapp

If I open received / sent image file by double clicking then choose download, then it will stuck there. Have to kill Rambox process. But if I choose download option in the chat directly without opening the image it's work.

Rambox 0.5.13
Electron 1.7.8
Linuxmint 18.3

**Comment by petercipov** [comment]
This is still an issue

Version: 0.6.2
Platform: darwin (x64)
Electron: 2.0.8
Chromium: 61.0.3163.100
Node: 8.9.3
