### ISSUE TITLE
service not working with (NET::ERR_CERT_AUTHORITY_INVALID)

### ISSUE THREAD

**Issue by Toncek** [ramboxapp/community-edition#1298]
Blank page if i add service like rocket chat ( or custom plugin ) working on our local network.

In chromium it usually show something like "Your connection is not private" and ERR as i wrote in tittle.

 
	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.13.0-kali1-amd64

**Comment by BuildTheRobots** [comment]
Do you have a custom CA set up or just a generic self-signed certificate?

If it's a custom CA then I've done the following to make it work on ubuntu:

- Add CA to **Mozilla Firefox** certificate store (through browser settings)
- Add CA to **Chromium** certificate store (through browser settings)
- Add CA to `/usr/local/share/ca-certificates/mySSL.crt` and then symlink from that to `/etc/ssl/certs/mySSL.pem`
