### ISSUE TITLE
Problem with window size!

### ISSUE THREAD

**Issue by ducarpit** [ramboxapp/community-edition#1299]
I have just installed RamBox in my Windows PC but unfortunatly i can't see the windows in my screen size.
For example i use whatsapp and slack but their windows are smaller than my window tipical screen!
Why?
Thanks a lot

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.15063

**Comment by Nicolas71100** [comment]
I have the same issue and when I click on a link on any services, it doesn't "open" the link the way it should
