### ISSUE TITLE
Clicking a mail address in Gmail opens a blank Gmail-Window and empty browser tab

### ISSUE THREAD

**Issue by Herrner** [ramboxapp/community-edition#1303]
Seems to be related to #1098 and (maybe) #834
Might be related to Chromes handler for mailto: links? 
`navigator.registerProtocolHandler("mailto", "https://mail.google.com/mail/?extsrc=mailto&url=%s","Gmail");`

### Steps to reproduce

1. Click on mail adress in Gmail tab
2. done!

### Expected behavior

Email compose window opens either in Rambox or browser

### Actual behavior

Empty Rambox windows titled "Gmail" opens in Rambox, new Gmail-Tab without content opens in Chrome

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Windows 10 1703 15063.674
> Arch: x64

**Comment by pivotal-mikegresham** [comment]
This issue is appearing in all Electron apps, as GitKraken is having the same issue with links that open in the browser. They all show up as blank, new browser windows. I think its an electron issue.

**Comment by js931** [comment]
Is there any new info/solution for this? It's a really annoying bug for me ;-)
