### ISSUE TITLE
error updating the app 

### ISSUE THREAD

**Issue by ghazayel** [ramboxapp/community-edition#1305]
![capture](https://user-images.githubusercontent.com/8275031/32899342-28e80af4-cb04-11e7-8128-29044c0ebe2b.JPG)

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 6.1.7601

**Comment by saenzramiro** [comment]
Seems like you have missing libraries from Windows. Do you have the latest updates for Windows?
