### ISSUE TITLE
Websites cropped

### ISSUE THREAD

**Issue by jakroniker** [ramboxapp/community-edition#1308]
All tabs are cropped at the bottom and the right side about 10% I couldnt fix it with reloading or installing updates. Now I cant even write whatsapp or telegram messages, because the writing-line is cropped

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> darwin x64 17.2.0

**Comment by rnyberg** [comment]
Same problem on latest Windows version on Win 10 and 4K monitor.

**Comment by spex66** [comment]
same here on Win10, 1080p monitor
that's annoying and is rendering Skype and Slack unusable

no one having a reliable solution?

**Comment by rnyberg** [comment]
Whenever this still (sometimes) occurs, I need to reset zoom of the tab and then fully restart Rambox.

**Comment by spex66** [comment]
Reset zoom on tab has not worked (tested different variants, settings, restarts).
But the top menu "View > Actual Size" magically made a difference!

weird.. but at last Skype, Slack have their boxes at bottom back :)

**Comment by rschaerer** [comment]
I hope I found a reproducible fix for this issue. I was struggling with the "services windows do not take the full rambox window size but are cropped) some weeks until now.

## Solution

**Go to the _MAIN_ rambox tab (the one with all the services listed) and press in the top menu** `View` > `Actual Size`. All other tabs take the full window size. If not, do the "Actual Size" thing for all tabs.

As soon as the main tab has not the "Actual Size" set, and especially if the main tab is **zoomed in**, the canvas sizes of the services (as WhatsApp, Slack, etc.) get cropped.

:question: @spex66 , @redfellow & @jakroniker can you confirm this behavior?

**Comment by Ickerday** [comment]
Can confirm, had the same issue and `View -> Actual Size` has fixed it.

**Comment by JoshuaJarman** [comment]
This fixes the cuttoff, but restarting the app goes right back!
i have to do this every time the app starts.

_(It also doesn't stop the related service zoom issue.)_

**Comment by rschaerer** [comment]
:heavy_check_mark: I have the same behavior as @JoshuaJarman : the zoom settings aren't persistent over a app restart and I have to do this every time the app starts.
