### ISSUE TITLE
too many startup items

### ISSUE THREAD

**Issue by M0UL** [ramboxapp/community-edition#1309]
can somebody explain this:
![image](https://user-images.githubusercontent.com/5436726/32983629-ec60d13e-cc97-11e7-85f7-290ed09cde5e.png)

rambox version: 0.5.13
os: windows 10.

**Comment by Grui** [comment]
Reproduced with High memory consumption with rambox 0.5.13

**Comment by saenzramiro** [comment]
Probably each one is for a different version you had. Seems like a bug we will have to investigate.

Can you see the properties of each one or investigate if is like I said?

**Comment by M0UL** [comment]
al rambox items points to same .exe file.

**Comment by mloskot** [comment]
@saenzramiro 
> Probably each one is for a different version you had. Seems like a bug we will have to investigate.

Yes, possible indeed. See my #1542
