### ISSUE TITLE
Can't click any buttons on the Google external login window

### ISSUE THREAD

**Issue by Skweezyy** [ramboxapp/community-edition#1315]
### Steps to reproduce

1. Click Google sign-in on a web page which allows it
2. Enter email, click "next" to proceed to password entry.
3. The button does the material design click animation, but nothing else happens.

### Expected behavior

The login flow should progress to the password entry stage.

### Actual behavior

Button animations run, but the screen doesn't actually progress to the password entry field. In addition, the forgot your password link doesn't work.

### ENVIRONMENT

> Browser: Firefox

> OS: Windows 10

### OTHER NOTES

Exactly the same as #839, though changing the language then trying doesn't work. #839 has also been solved, I don't think this issue has.

**Comment by Skweezyy** [comment]
Bump

**Comment by hisairness23** [comment]
Having the same problem. Doesn't work for me on Chrome, FF or Opera. However, it works on a virtual machine. Could it be a problem because of a new Windows Update or JavaScript?

**Comment by u2live79** [comment]
I'm having the same issue on a clients computer. Anybody figure it out? I can't get any google buttons to work on IE, Firefox or Chrome.

**Comment by ekaterinatishina** [comment]
I'm having the same issue on my computer. HELP!

**Comment by Skrolk** [comment]
Same issue for me (win 10 with Edge, Firefox and Chrome) but not on a virtual machine (ubuntu) and not on Opera Browser (Version : |49.0.2725.64)

Any solution ?

**Comment by ekaterinatishina** [comment]
I solved the problem!!!! 
I had a virus. Google Locker or something like that
Once it was deleted, I was able to sign in to my account and all buttons appeared that were not displayed in the mail
