### ISSUE TITLE
blank black screen

### ISSUE THREAD

**Issue by allstarleb** [ramboxapp/community-edition#1323]
for some reason there is a black blank screen every time i start the application. i restarted the application twice, no luck. Any idea what is going on? 	

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 6.1.7601

**Comment by Fellfalla** [comment]
same for me:

To reproduce:
- Update to following windows version:
![image](https://user-images.githubusercontent.com/10533063/33239336-0f468c62-d2a0-11e7-9f45-8fa0079d4a0d.png)

- Specs: 

> Computer:      LENOVO ThinkPad W520
> CPU:           Intel Core i7-2820QM (Sandy Bridge-MB SV, D2)
>                2300 MHz (23.00x100.0) @ 797 MHz (8.00x99.7)
> Motherboard:   LENOVO 42823HG
> Chipset:       Intel QM67 (Cougar Point) [B3]
> Memory:        12288 MBytes @ 664 MHz, 9-9-9-24
>                - 2048 MB PC10600 DDR3 SDRAM - SK Hynix HMT325S6BFR8C-H9
>                - 4096 MB PC12800 DDR3 SDRAM - SK Hynix HMT451S6BFR8A-PB
>                - 2048 MB PC10600 DDR3 SDRAM - SK Hynix HMT325S6BFR8C-H9
>                - 4096 MB PC12800 DDR3 SDRAM - SK Hynix HMT451S6BFR8A-PB
> Graphics:      Intel Sandy Bridge-MB GT2+ - Integrated Graphics Controller [D2/J1/Q0] [Lenovo]
>                Intel HD Graphics 3000, 2108 MB 
> Graphics:      NVIDIA Quadro 1000M [Lenovo]
>                NVIDIA Quadro 1000M, 2048 MB DDR3 SDRAM
> Drive:         SAMSUNG SSD 830 Series, 500.1 GB, Serial ATA 6Gb/s @ 6Gb/s
> Drive:         Optiarc DVD RW AD-7710H, DVD+R DL
> Sound:         Intel Cougar Point PCH - High Definition Audio Controller [B2]
> Network:       Intel 82579LM (Lewisville) Gigabit Ethernet Controller
> Network:       Intel Centrino Ultimate-N 6300 AGN 3x3 HMC
> OS:            Microsoft Windows 10 Professional (x64) Build 16299.64
> 

-Open Rambox -> View stays black

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 10.0.16299

**Comment by saenzramiro** [comment]
Please follow this issue #1202
