### ISSUE TITLE
Outlook 365 Doesn't Load

### ISSUE THREAD

**Issue by AllanWang** [ramboxapp/community-edition#1324]
When creating an outlook 365 account, a blank page is shown.

In the console, there is the error
```
Uncaught ReferenceError: $ is not defined
    at checkUnread (<anonymous>:1:30)
```

and in the DOM, there is an empty body.

Other services, including outlook and slack, work.

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Linux (Antergos)

**Comment by eryshev** [comment]
Same issue. I suppose it's linked with redirection to corporate authentication page.

**Comment by AllanWang** [comment]
It ended up being some issue with outlook itself. Often times it wouldn't load at all at home for some reason.
