### ISSUE TITLE
Feature: Show unread counter for mentions only

### ISSUE THREAD

**Issue by SevereOverfl0w** [ramboxapp/community-edition#1326]
I'm part of some community slacks, which means I do not care when there is unread messages there. It would be nice if I could turn off the general unread counter there, and only show the red box when there are unread _mentions_ (or some other measure of "high priority" alert).

**Comment by Paaltomo** [comment]
You can change these settings in Slack itself by altering your notification settings.

**Comment by SevereOverfl0w** [comment]
Which option are you referring to? I'm not concerned about notifications, just about the unread counter.

**Comment by Paaltomo** [comment]
My apologies, I'm not sure - will try to find out
