### ISSUE TITLE
No Connection to Whatsapp

### ISSUE THREAD

**Issue by Neverknown** [ramboxapp/community-edition#1330]
When Rambox starts it doesnt find the Whatsapp/ Handy and says there is no Connection to the Phone. When you try to reconnect or you clean the data and Cache, a scan of the QR Code is not possible the Handy app didnt recordnice the Rambox Code.

> Rambox 0.5.13
> Electron 1.7.8
> win32 x64 10.0.16299

**Comment by saenzramiro** [comment]
Sounds like it's a WhatsApp problem. Is this still happening?
