### ISSUE TITLE
glitches in high sierra

### ISSUE THREAD

**Issue by flowen** [ramboxapp/community-edition#1334]
### Steps to reproduce
After installing High Sierra, this seems to happen just randomly. 

### Expected behavior
to just work, nothing else. 

### Actual behavior
everything glitches, hangs. I can still write and send messages, but I can't read what the message is. I know this, because the UI updates, but in a way like Windows 95 used to have hanging applications. 

### ENVIRONMENT

> Rambox: v0.5.13
> OS: OSX High Sierra 10.13.1
> Arch: x64

**Comment by macrozone** [comment]
update to latest electron should solve that issue: https://github.com/electron/electron/releases/tag/v1.7.10

**Comment by flowen** [comment]
fixed!
