### ISSUE TITLE
Newly Added Custom Service not Appearing on List

### ISSUE THREAD

**Issue by e58** [ramboxapp/community-edition#1335]
### Steps to reproduce

1. Add Google Keep (or any custom service)
2. Add https://www.facebook.com as a custom service

### Expected behavior

1. Google Keep (or any custom service) should appear as a tab and under the list of **Enabled Services**
2. Facebook should appear as a tab and under the list of **Enabled Services**

### Actual behavior

1. https://keep.google.com (or any) custom service:
- tab would appear, but not under the list of **Enabled Services**
https://i.imgur.com/IeBMiQu.png

2. https://www.facebook.com custom service:
- Rambox will get stuck on the **Add _Custom Service** window
- Facebook service would be added, but its tab would not appear
- Rambox will start to misbehave once the **Add _Custom Service** window gets closed (e.g. _Don't Disturb_, _Lock Rambox_, _Syncronize Configuration_ will not work when clicked)
https://i.imgur.com/TKB0a3a.png

-- tried restarting the app
-- tried re-downloading portable version
-- tried backing up and restoring configuration

### ENVIRONMENT

> Rambox: v0.5.13 (portable)

> OS: Windows 10 Pro (v1703 b15063.726)

> Arch: x64

**Comment by saenzramiro** [comment]
Seems like services configuration is broken and after that, all will be broken. Sorry but the only way to fix it is start over by removing all the services, clearing cache and localStorage and then, start adding one by one.

**Comment by e58** [comment]
Can this be fixed on the next release? Or is there a way to avoid it? I followed your workaround (which was tedious) and it worked. Unfortunately it happened again.
