### ISSUE TITLE
Unable to see the Rambox main window

### ISSUE THREAD

**Issue by Grui** [ramboxapp/community-edition#1339]
Hello,

Precondition : Active the option to ask a password when rambox is launched

### Steps to reproduce

1.  Launch rambox
2. Click on the rambox icon in the windows taskbar in order to view the main window

### Expected behavior

Rambox main window appear

### Actual behavior

Nothing appears.
Random Issue, but once it is reproduced, impossible to retrieve the main window even after a reboot.

### ENVIRONMENT

> Rambox: v0.5.13

> OS:  Microsoft Windows 10

> Arch: x64 

> Using multi screens (3)

Best regards,

Fabien

**Comment by saenzramiro** [comment]
Did you try by holding Windows key and press Left/Right arrows on your keyboard to move the window? Seems like it's hidden in your other screens.

**Comment by Grui** [comment]
Hello !

 

Thanks for your answer.

Yes I tried windows key + up / windows key + left / etc. Nothing appears. If I do the same for any other window app it work.

 

 

 

Envoyé: mardi 5 décembre 2017 à 15:44
De: "Ramiro Saenz" <notifications@github.com>
À: saenzramiro/rambox <rambox@noreply.github.com>
Cc: Grui <arctylos@hotmail.com>, Author <author@noreply.github.com>
Objet: Re: [saenzramiro/rambox] Unable to see the Rambox main window (#1339)


Did you try by holding Windows key and press Left/Right arrows on your keyboard to move the window? Seems like it's hidden in your other screens.

**Comment by saenzramiro** [comment]
Try by closing Rambox and edit the configuration file manually, set the X and Y properties to 0.

https://github.com/saenzramiro/rambox/wiki/Edit-configuration-manually

**Comment by Grui** [comment]
Hello,

Ok, next time I got this bug I will do that.

Thanks

**Comment by Grui** [comment]
Hello,

I faced the same bug again. I tried the workaround you given and it works well. The Y was initialy set to a minus value. 

Best regards
