### ISSUE TITLE
[Feature] XMPP Omemo Support

### ISSUE THREAD

**Issue by coxtor** [ramboxapp/community-edition#1341]
It would be great to see XMPP OMEMO support. 
Thanks

**Comment by arthurlogilab** [comment]
On which service ?

**Comment by arthurlogilab** [comment]
Am in favor of keeping this issue open, related to #1611

**Comment by DreamFlasher** [comment]
ConverseJS now supports Omemo (see https://github.com/conversejs/converse.js/issues/497), so supporting conversejs as a service would solve the Omemo support. (https://github.com/ramboxapp/community-edition/issues/1611)
