### ISSUE TITLE
icloud plugin - reply or forward message opens in default browser

### ISSUE THREAD

**Issue by dan6003** [ramboxapp/community-edition#1344]
when reply or forward a e-mail using the icloud plugin, the pop-up tries to open in the default browser instead of using the plug-in. Creating a new mail, the pop-up opend in the plugin.

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.16299

**Comment by brossow** [comment]
To add to this, not only does it open in the browser, but it also creates an empty (new) message with no subject or recipient(s). This severely restricts its usefulness.
