### ISSUE TITLE
Outlook 365 new mail indicator tray icon is always red when tab is open and new messages are not indicated.

### ISSUE THREAD

**Issue by ThomasRitter75** [ramboxapp/community-edition#1349]
### Steps to reproduce

1. Set up Outlook 365
2. Log in to Outlook 365
3. Change to Outlook 365 tab

### Expected behavior

Red 'new messages" indicator in tray only when there are new messages

### Actual behavior

As long as the Outlook 365 tab is in front, the "new messages" tray indicator is red, when another tab is chosen, it is blue/white, regardless of new messages in Outlook 365.

### ENVIRONMENT

> Rambox: 0.5.13-108 (deb package)

> OS: Linux/Ubuntu/Xenial

> Arch: x64

**Comment by jerry1970** [comment]
+1

**Comment by ThomasRitter75** [comment]
Update: Since yesterday, the icon is not always red anymore, but new mails are not indicated either.

**Comment by ThomasRitter75** [comment]
Update: In the current version of Rambox, new mail notification works as expected for the main inbox, but does not work for other folders with new and unread mails inside.
