### ISSUE TITLE
Clicking on links opens a blank chrome browser tab

### ISSUE THREAD

**Issue by origal** [ramboxapp/community-edition#1357]
### Steps to reproduce

1. Click a link on a message. (Tested on WhatsApp and Slack)

### Expected behavior

Link should open in existing browser window

### Actual behavior

New blank tab is opened regardless of link URL

### ENVIRONMENT

> Rambox: v0.5.13

> OS: macOS High Sierra version 10.13.2

> Arch: x64

**Comment by szada92** [comment]
Hi!

I had the same problem, it's a OS X related bug.

See the solution here: https://discussions.apple.com/thread/8151536
Basically you just have to re-set the default browser.

**Comment by origal** [comment]
hey @szada92 , thanks for your answer.
I've tried it with no luck. anything else I can try?

**Comment by origal** [comment]
Thanks @szada92  ! It works.

**Comment by T0T4R4** [comment]
I have this problem on Fedora Linux with 0.5.14. Blank screen.

**Comment by dmeza** [comment]
For anyone still looking. It is a Chromium issue with updates not being applied yet. The solution seems to be coming with Chromium 65 in beta right now. The thread of the issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=777863#c18

**Comment by vk-sourcefuse** [comment]
I'm seeing this with Slack on Chrome 67.0.3396.87 (Official Build) (64-bit)

**Comment by vk-sourcefuse** [comment]
This simple solution worked for in https://askubuntu.com/questions/820900/slack-fails-to-open-links-in-ubuntu-14-04
