### ISSUE TITLE
Donation popup shows up on every startup

### ISSUE THREAD

**Issue by yegortimoshenko** [ramboxapp/community-edition#1361]
See: https://github.com/NixOS/nixpkgs/pull/32741

It would be better to implement donation popup locally, without `tooltip.io`, and check for a file or cookie at launch. Related: https://github.com/saenzramiro/rambox/issues/414, https://github.com/saenzramiro/rambox/issues/948#issuecomment-310247822

**Comment by saenzramiro** [comment]
Yes, because seems like tooltip.io never fixes the issue related with "Only once" per user. Seems like some users see this popup on every startup.
