### ISSUE TITLE
AIM not working

### ISSUE THREAD

**Issue by paco3346** [ramboxapp/community-edition#1362]
### Steps to reproduce

1. Enter AIM credentials
2. Cry

### Expected behavior

I'd love to message all of my friends but I can't log into AIM.

### Actual behavior

A prank page stating that AIM no longer exists opens. I think I got haxxed.

### ENVIRONMENT

It's very sad over here.

> Rambox: v0.5.13

> OS: Arch Linux

> Arch: x64

**Comment by paco3346** [comment]
But in all seriousness- I think this plugin can be removed now.

**Comment by ssteinerx** [comment]
AIM is discontinued, title of this should be changed to "Remove AIM support; discontinued."
