### ISSUE TITLE
Hangouts notifications for the conversations with the notifications turned off

### ISSUE THREAD

**Issue by zelenilav** [ramboxapp/community-edition#1365]
I keep getting notifications for the conversation(s) (one group chat, haven't tested it on others) in which the notifications are turned off. This isn't an issue in a similar app (Franz).

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 10.0.16299

**Comment by 8restcoop8** [comment]
This happens to me too.
