### ISSUE TITLE
Tela escura

### ISSUE THREAD

**Issue by ruancorreia** [ramboxapp/community-edition#1371]
Após atualização a tela fica escura e nao consigo acessar os serviços 
![image](https://user-images.githubusercontent.com/8524018/34327275-1e3a7cde-e8a7-11e7-8739-b841038ef8a8.png)

	
	-
	> Rambox 0.5.13
	> Electron 1.7.8
	> win32 x64 6.1.7601

**Comment by danielmotaleite** [comment]
Tenta actualizar os drivers da placa gráfica e claro, fazer um reboot ao windows

Se ainda falhar, tenta ir a janela-> ferramentas de desenvolvedor e ve se o browser reporta algum problema extra

**Comment by danielmotaleite** [comment]
possivelmente relacionado com o https://github.com/saenzramiro/rambox/issues/1202
