### ISSUE TITLE
Rambox is freezing when trying to download an image from WhatsApp

### ISSUE THREAD

**Issue by kenshiwara** [ramboxapp/community-edition#1372]
### Steps to reproduce

1. Tune any WhatsApp account.
2. Click on any image to view it.
3. Click on the download button and try to save it.

### Expected behavior

We expect the image to get downloaded.

### Actual behavior

The whole screen is freezing until we exit the program.

### ENVIRONMENT

> Rambox: v0.5.13
> OS: Kubuntu 17.10
> Arch: x64

**Comment by MakisH** [comment]
I have the same issue. It's not exactly the whole desktop that is freezing, I can still use the keyboard to change windows (to show the Desktop actually). But when the Rambox windows are shown (main window and file manager), everything looks frozen.

Environment:

Rambox: v0.5.15
OS: Ubuntu 16.04 (x64)
Electron: 1.8.2
Chromium: 59.0.3071.115
Node: 8.2.1

**Comment by ozzyjr** [comment]
Same problem here. I already uninstalled and installed again, updated and nothing to solve.

**Comment by atoppi** [comment]
Same issue on Ubuntu 18.04

**Comment by shnigi** [comment]
If somebody sends me a picture the view freezes, the same thing happens in rambox and franz app. OSX.
