### ISSUE TITLE
Rambox opens links in default browser and in Rambox window

### ISSUE THREAD

**Issue by takahashi64** [ramboxapp/community-edition#1380]
Steps to reproduce:
Click a link on a link. 

Expected behavior:
Link should *only* open in default browser

Actual behavior:
New blank tab is opened in Rambox and default browser regardless of link URL

ENVIRONMENT

Rambox: 0.5.13-x64-win
OS: Windows 10
Arch: x64

**Comment by m106** [comment]
Which Browser are you using? Chrome? Try restarting Chrome, I think its a Chrome issue.

**Comment by jebbster88** [comment]
Same issue here on 0.5.14, Windows 10

Click a link in Rambox, link opens in a new tab in my default browser (firefox) AND a rambox popup window.

**Comment by jozydapozy** [comment]
It seems that it doesn't happen on regular target=_blank links but only on onclick="window.open(href,target); return false".

**Comment by hc-romens** [comment]
Is there a way to block this?

**Comment by Boosik** [comment]
Try adding this to the custom script of the service:
`
window.open = function (url, name, features) {
     var form = document.createElement("form");
     form.method = "GET";
     form.action = url;
     form.target = features;
     document.body.appendChild(form);
     form.submit();
};`

**Comment by lednine** [comment]
That worked. Thanks
