### ISSUE TITLE
Office365 DE Cloud Support

### ISSUE THREAD

**Issue by mfuhrmann** [ramboxapp/community-edition#1381]
Microsoft has different clouds. US, EU, DE cloud. So the german cloud has http://office.de. 

### Steps to reproduce

1. Login with your DE account credentials
2. 
3. 

### Expected behavior

Login to DE cloud.

### Actual behavior

"Sorry, but we’re having trouble signing you in.
We received a bad request."
![image](https://user-images.githubusercontent.com/4995222/34760838-97e353ca-f5e1-11e7-878d-f37bc1dacf7a.png)

### ENVIRONMENT

> Rambox: 0.5.13

> OS: Ubuntu 16.04 LTS

> Arch: x64

**Comment by tz1010** [comment]
Same issue here. This should be easily fixed by adding a configuration for the office login URL

**Comment by tayfuuun** [comment]
+1

**Comment by mrmnmly** [comment]
+1

**Comment by Insasse** [comment]
+1
