### ISSUE TITLE
Service not maximized to window size

### ISSUE THREAD

**Issue by vaisov** [ramboxapp/community-edition#1382]
### Steps to reproduce

1. After installing DisplayFusion software service window size is smaller than app window size. This can also be a coincidence, as uninstalling DisplayFusion didn't solve the issue.

### Expected behavior

Service window should be maximized to the size of app window.

### Actual behavior

Service window is smaller than actual app window size. (Screenshot attached)
![clip2net_180110094633](https://user-images.githubusercontent.com/3081137/34761132-2d353200-f5eb-11e7-99a5-4ef94087bf4d.png)

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Windows 10 Pro (1709, OS Build 16299.192)

> Arch: x64

**Comment by smoors** [comment]
I have a similar issue. I cannot write any message because it does not fit into the app window. (I do not have DisplayFusion).
Env:
Rambox: v0.5.13
OS: Ubuntu 16.04
Arch: x64

**Comment by askembris** [comment]
I have the same issue with several (well, all, really) my services - WhatsApp, Skype, Hangouts on my laptop by on the desktop all seems to be working fine (same services). 

The laptop has a resolution of 1920*1080 and is using the intel graphics drivers. 
![screenshot_20180326_151030](https://user-images.githubusercontent.com/37801919/37905764-9047b43c-3108-11e8-94d8-ebed26268a00.png)

Disabling HiDPI, hardware acceleration (together and separately) did not work. 

On my desktop, with higher resolution monitors and the open-source radeon drivers everything is as expected. 

Both machines are running KDE on openSUSE Tumbleweed. 

It should be noted that no cropping seems to take place, it's just the whole window's size is not utilised.

**Comment by vaisov** [comment]
Solved that by logging off, logging in.

**Comment by askembris** [comment]
Problem still present with version 0.5.17

**Comment by rschaerer** [comment]
I have the same issues with all services except the home tab, which is full width and full height.

Display resolution size: 2280 x 1800 

Rambox specs:
Version: 0.5.17
Platform: linux (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

OS: Ubuntu 18.04
