### ISSUE TITLE
Microsoft Teams still not working well

### ISSUE THREAD

**Issue by MJae** [ramboxapp/community-edition#1394]
### Steps to reproduce

1. Run Rambox
2. Open Microsoft Teams

### Expected behavior

Teams should load and function properly.

### Actual behavior

It loads Teams, but only so. The chats, whether individual or through channels, do not load properly. The last it loaded are conversations from December 2017. (It still works properly, though, if you uncheck "Select Automatically" from "User Agent".)

### ENVIRONMENT

> Rambox: v0.5.14

> OS: Windows 10

> Arch: x64

**Comment by saenzramiro** [comment]
Is anyone having this problem also?

**Comment by Najkon** [comment]
Nope, I'm using RAMBOX on Linux! :D and don't have any problem with M$ Teams - work great!

**Comment by T0T4R4** [comment]
I'm using RAMBox on Fedora Linux and have the same issue. Passed the corporate microsoft authentication, a message shows up that this 'browser' is not supported.

**Comment by carceneaux** [comment]
@saenzramiro This issue popped up 2-3 months ago. As @toC1421 mentioned, the latest build does not have this issue.
