### ISSUE TITLE
Clicking on a link opens it in random Chrome profile

### ISSUE THREAD

**Issue by mirfilip** [ramboxapp/community-edition#1396]
### Steps to reproduce
1. Have two Chrome profiles open, first in Workspace 1, second (main profile) in Workspace 2.
2. Have Rambox open in Workspace 2 along Chrome main profile.
3. Open a link sent to you via WhatsApp or Messenger (that's what I use, but I presume it's not dependant on a service).

### Expected behavior
Link opens in Chrome in the browser profile that's in the same Workspace as Rambox or it always uses a main profile. Any way, but consistent.

### Actual behavior
Random. Sometimes it opens in first and sometimes in second profile. It's not a matter of which profile has been used last. 

### ENVIRONMENT
```
Version: 0.5.13
Platform: darwin (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0
```

**Comment by danielmotaleite** [comment]
rambox should be using the default browser (but i do not know exactly how to check the default browser on a mac), so you probably have both chromes defining that they should always set itself as the default chrome. please check that

**Comment by mirfilip** [comment]
@danielmotaleite I don't understand what you want me to check.

Google Chrome is set as a default browser. There is an alias for one of the profiles, it's called `Default`, it always opens a default profile.

E.g. I can open it from CLI: `open -a "Google Chrome" --args --profile-directory=Default`, but it doesn't work when you rename profiles and no longer have a profile called `Default`.

Anyway, FWIW, when you create two terminal windows, have two Chrome windows open and segregate windows so that one terminal window + one Chrome windows goes to one Workplace, and the same for the second Workpace. You can then go to terminal window on particular terminal and issue `open -a "Google Chrome"` - it always opens the profile present on *that Workpace*.

**Comment by danielmotaleite** [comment]
open both chromes/profiles, check if both are trying to be the default browser. you can only have one of then as the default browser, the other one should not try to register itself as the default browser:
https://support.google.com/chrome/answer/95417?co=GENIE.Platform%3DDesktop&hl=en

After doing this, test to see if this improved your setup (at least should be more consistent)
