### ISSUE TITLE
Rambox updates to the wrong CPU architecture

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [ramboxapp/community-edition#1399]
I specifically always install x86 version of Rambox to save a little of memory, since Rambox consumes a good 1/16 portion of it already. However, when auto-update arrives, it installs x64 version. I then have to visit the website and manually install the latest x86 version.

### Steps to reproduce

1. Install an x86 version of Rambox
2. Wait for an update to be released.
3. Relaunch Rambox so the update is installed.
4. Observe that Rambox is updated to a x64 version.

### Expected behavior

Rambox is updated to the build with the same CPU architecture as the one currently running.

### Actual behavior

On a x64, Rambox is updated to x64 version even if x86 version was installed.

### ENVIRONMENT

> Rambox: v0.5.4

> OS: Windows 10 

> Arch: ia32

**Comment by ZimM-LostPolygon** [comment]
The issue is still here.

**Comment by Ash258** [comment]
Even on 0.6.2?? 🤔

**Comment by ZimM-LostPolygon** [comment]
@Ash258 Well.. Just tried updating from 0.6.1 to 0.6.2. Now Rambox doesn't even start:
![default](https://user-images.githubusercontent.com/928550/47494704-9431a700-d852-11e8-864a-f0e1d0dc8f03.png)
It seems like updater completely messed it up:
![default](https://user-images.githubusercontent.com/928550/47494734-a57ab380-d852-11e8-88af-d9f464b40864.png)

**Comment by ZimM-LostPolygon** [comment]
@Ash258 And if I visit the installation folder - yes, it is now x64.
![default](https://user-images.githubusercontent.com/928550/47494842-eb377c00-d852-11e8-97b2-faca8a996ed5.png)

**Comment by ZimM-LostPolygon** [comment]
Wait... It seems like the installer for Windows x86 is completely gone?

**Comment by Ash258** [comment]
Installer is NSIS packed. It holds both architecture versions. NSIS decide what to install.

**Comment by ZimM-LostPolygon** [comment]
@Ash258 How does it decide? I want to install 32-bit version on a 64-bit Windows to conserve some ram. Is there a command line flag to force a specific architecture?

**Comment by Ash258** [comment]
Easily. When you are running 64 bit. It install 64bit. 

https://www.electron.build/configuration/nsis#32-bit-64-bit

**Comment by ZimM-LostPolygon** [comment]
@Ash258 Which is exactly what I don't want :) Is there a way to install 32-bit Rambox on 64-bit system? Previously, I just downloaded 32-bit installer.

**Comment by Ash258** [comment]
https://www.electron.build/configuration/nsis#32-bit-64-bit

**Comment by ZimM-LostPolygon** [comment]
So... That means no? :) This page is about building an installer, not running it with specific target architecture.
