### ISSUE TITLE
Link from site to download deb is not functional

### ISSUE THREAD

**Issue by agharbeia** [ramboxapp/community-edition#1401]
On the project's site, rambox.pro, the link to download the Rambox for Linux DEB, i.e [https://getrambox.herokuapp.com/download/linux_64?filetype=deb], leads instead to downloading a tar.gz file that most Ubuntu users would not know what to do with.

### Steps to reproduce
1. Open the website http://rambox.pro
2. go to the download section
3. click on the link to download Linux DEB, either for 32 or 64 bit

### Expected behavior

The browser prompts the user to save a .deb file

### Actual behavior

The browser prompts the user to save a .tar.gz file

### ENVIRONMENT

The project's website.

**Comment by Ash258** [comment]
Dup of #1164 #1148 #1096
But this is the best issue report from all of them.

**Comment by fungs** [comment]
Found the same issue, deb link resolves to tar.gz

**Comment by DaDummy** [comment]
It's been two months since the issue was reported.

Since the homepage is what users usually visit when they want to try a (new) software and since this should be as easy as fixing a typo in a link, that fact kind of gives the impression that the project has been abandoned or at least is in no healthy state developer-activity-wise.

**Comment by fungs** [comment]
@DaDummy Maybe it needs more manpower

**Comment by fungs** [comment]
Same for version 0.5.17 now

**Comment by JokerGermany** [comment]
Why does nobody fix this?

**Comment by Ash258** [comment]
Because it's code is hosted somewhere else then this repo, so it could be fixed only by @saenzramiro and its priority is pretty low.

**Comment by manuelleduc** [comment]
One way to get around this issue is to go directly to https://github.com/saenzramiro/rambox/releases/latest and download the latest deb from here.

**Comment by fungs** [comment]
Website has changed and links to deb packages have been removed. This is one way to resolve the issue. On the front page, Linux users can now download appimage (60 MiB) or snap (110 MiB) packages but the deb package (40 MiB) is still on the GitHub page.
