### ISSUE TITLE
Slack Icon

### ISSUE THREAD

**Issue by Slind14** [ramboxapp/community-edition#1408]
Hi there,
for some of my slack servers it is showing the slack workspace icon, for others it doesn't. I tried re-adding them but that didn't seem to fix it. Any idea what could be the cause?

**Comment by nderscore** [comment]
I've noticed this issue happening sometimes as well. It doesn't happen always, but it always happens to the same slack server(s).

I'll look into what's causing it and post an update later.

**Comment by briankendall** [comment]
I'm seeing this issue too. Every time I launch the app or reload, around half of my slack workspaces don't have the proper icon. Sometimes none of them load. If I remove and then re-add the whole service the icon comes back, until the next time it's reloaded.

**Comment by nderscore** [comment]
I'm pretty sure it's being caused by a race condition between when the icon becomes available on the page and when the script that grabs it is being injected. I haven't had a chance to look into the internals to confirm or find a fix though.

**Comment by KHarker** [comment]
If it helps, I was able to work around this issue by right-clicking the tab of any channels that failed to load the icon correctly and clicking 'reload'. I've done this about eight times and had a 100% success rate of it loading the correct icon.

**Comment by briankendall** [comment]
For me it's like a 20% success rate. Sometimes it doesn't work at all until I restart the app. Not sure why.

**Comment by briankendall** [comment]
Actually this issue has gotten quite bad for me. I can barely get any slack icons to load at all. Reloading the service doesn't have any effect, and when I reload the whole app, sometimes one or two of the icons will load but none of the rest will.

Is there any kind of workaround I can use while waiting for a fix? (Like some custom javascript I could add to each service?)

**Comment by DDoerner** [comment]
Any updates on this issue? It reached a point for me that not a single one out of 11 workspaces loads the custom workspace icon. Reloading does not work either.

**Comment by Mte90** [comment]
Quite sad of this issue, now that finally we have the vertical bar for services

**Comment by schwartzman** [comment]
I'm afraid that this still appears to be an issue in 0.6.2.

**Comment by nderscore** [comment]
Yeah, I'm still seeing this happen. Though, the failure rate has been reduced!

I think adding a 1 second timer ( 6b3166e ) is not an ideal way to solve a race condition.
