### ISSUE TITLE
Removing, skipping, hiding Messenger notifications from Facebook tab

### ISSUE THREAD

**Issue by adlibdalom** [ramboxapp/community-edition#1410]
### Steps to reproduce

1. Connect both Facebook Messenger and Facebook
2. Receive a Facebook message
3. Notice notification on both service's tabs

### Expected behavior

I want the notifications to only appear on the Messenger service.

### Actual behavior

Getting notification on both services.

### ENVIRONMENT

> Rambox: v0.5.14
> OS: Windows 10 Education (version 1709, build 16299.192)
> Arch: x64

**Comment by Ash258** [comment]
Just disable notifications on facebook?? 😕
![Settings](https://i.imgur.com/sOMTlIp.png "settings")

**Comment by adlibdalom** [comment]
@Ash258, but I want the notifications for Facebook. I just don't want the notifications for Facebook _Messenger_ on both Messenger and Facebook tabs.
