### ISSUE TITLE
[Documentation] Javascript injection examples

### ISSUE THREAD

**Issue by magnific0** [ramboxapp/community-edition#1412]
The javascript injection is one of the more powerful features of Rambox. However, it is not really accessible to everyone and missing good examples and documentation. 

Can we start a list of user examples? This would allow us to share solutions to common problems, discover clever tricks and open up this feature to a wider audience. 

Unfortunately GH Wiki is not very friendly to outside contributors (no PRs). So perhaps a seperate md file in the project root which people can contribute to, which could be periodically merged into the wiki.

Just to start the ball rolling, I'd like to share is a (dangerous) autologin feature that I use on a local service:

```
//
// AUTO LOG-IN
//
// Use Element Inspector in your browser to figure out the id names
// WARNING: this script is not secure. It stores your password in plain text on your disk and submits your password to any form with matching elements id's.
document.getElementById('username').value="myusername";
document.getElementById('password').value="mypassword";
document.getElementById('persistent').checked='checked';
document.forms[0].submit();
```

**Comment by Shmasya** [comment]
Your code may not work everywhere. I think it's a useless idea. You have JS injection, it is enough just to look in Google for a solution on JS and you will be happy.

**Comment by magnific0** [comment]
Thanks! I think you misunderstand the idea here though. This issues argues for some documentation / examples on JS injection applied to Rambox. Not the usefulness of my example, which is the focus of your message.

To reiterate, the documentation (vs. leaving everything for the user to find out) is about collecting examples to start from if you want to use JS injection in Rambox. Part is showcasing ideas and possibilities, which is useful for users of all levels and something you haven't addressed. Other part is practical examples to start from, which saves you and me a Google but might actually get less coding experienced users to use this very nice feature of Rambox (which is guaranteed not the case right now). 

My example is not a copy-paste for any service, but that's not the point. That is simply the difference between an example and a recipe. The very same goes for your suggestion (just Google a solution).

**Comment by Shmasya** [comment]
@magnific0  hm, ok. I think mini concrete examples for apps is viable.
