### ISSUE TITLE
Whatsapp gif support

### ISSUE THREAD

**Issue by MannekenPils** [ramboxapp/community-edition#1413]
Hey there, 
from time to time it happens that when I try to send a gif via whatsapp it says 'no preview available for the selected file' (actually this is only vaguely how I remember it right now). And once I sent one, the others work properly. 

Now that I think about it, this could be a Whatsapp problem, not a Rambox problem, just wanted to give a heads up.

Cheers

	-
	> Rambox 0.5.14
	> Electron 1.7.8
	> win32 x64 10.0.16299

**Comment by mdaehnert** [comment]
I can agree on that. For me every first preview of an image fails. The second click on it will succeed.
