### ISSUE TITLE
Telegram: full-width

### ISSUE THREAD

**Issue by pztrn** [ramboxapp/community-edition#142]
Right now Telegram isn't take 100% of window width. To force it just inject this snippet into CSS:

```
  .tg_head_split, .im_page_wrap, .im_message_wrap, .im_send_panel_wrap, .im_send_form, .tg_head_peer_title {
    max-width: -moz-calc(100% - 3em) ;
  }

  .im_dialogs_col_wrap, .tg_head_logo_wrap {
    width: 20%;
  }

  .im_history_col_wrap, .tg_head_main_wrap {
    width: 80%;
  }

  .composer_rich_textarea, .composer_textarea {
    font-size: 1em;
  }
 }
```

Or maybe it's better to add ability to inject user-entered CSS into service's pages? For example, I have some custom theming in Skype and would like to use it. Or even just force my preferred font everywhere :)

**Comment by saenzramiro** [comment]
Yes, one of the future features will be that. Right now I'm working in more important bugs but then I will start adding new things like this.

This is related with #107.

**Comment by noerw** [comment]
Also noteworthy:
Photo- & GIF-thumbnails are displayed really small (compared to the actual web client).
Thats especially annoying for GIFs, as you can't zoom them onclick

**Comment by rickinbsb** [comment]
@noerw happens with stickers too

**Comment by rickinbsb** [comment]
@noerw Changing language to force telegram to reload the app fixes it temporarily

**Comment by unmultimedio** [comment]
Changing language actually fixes the issue, and reloads after that does not return to small sizes. New stickers and images are sent in bigger size.

Before reload, and actually I took the screenshot to report the bug until I found this thread. (Left: Rambox, Right: Chrome)
![rambox1](https://cloud.githubusercontent.com/assets/4431392/25603150/0a2cd7b6-2ebf-11e7-8042-621995c45fbd.jpg)

And after reloading language, and closing Rambox with a manual reload (Cmd+Shift+R), still bigger size, so… Awesome! (Left: Rambox, Right: Chrome)
![rambox2](https://cloud.githubusercontent.com/assets/4431392/25603190/433b3f66-2ebf-11e7-8035-e68fff3afc06.jpg)

**Comment by saenzramiro** [comment]
Sweet!

**Comment by rodneyrod** [comment]
Any progress on this one? Would be great to have this supported out of the box and automated.

**Comment by rodneyrod** [comment]
I've got a workaround that seems to not have issues, if you put the following in the JS field everything seems to work fine:

`function applycss(css){
    var head = document.getElementsByTagName('head')[0];
    var s = document.createElement('style');
    s.setAttribute('type', 'text/css');
    s.appendChild(document.createTextNode(css));
    head.appendChild(s);
 }
applycss(`
  .tg_head_split,
  .im_page_wrap,
  .im_send_panel_wrap,
  .im_send_form { 
    max-width: unset; 
  }
  
  .im_message_wrap { 
    max-width: 100%;
  }
`);
`

**Comment by Excidion** [comment]
Documented my solution via the custom code options [here](https://github.com/Excidion/rambox_telegram_js_injection), works like a charm.
