### ISSUE TITLE
Messenger desktop notifications turns off at each restart of Rambox

### ISSUE THREAD

**Issue by TheHaso** [ramboxapp/community-edition#1420]
### Steps to reproduce

1. Add facebook messenger to Rambox
2. Turn on desktop notifications from the messenger settings
3. Restart Rambox
4. Desktop notifications are now off again 

### Expected behavior

The setting should not turn off itself, though, the change could be from the messenger side.

### ENVIRONMENT
> Rambox: v0.5.14
> OS: Windows 10 1709 Build 16299.192 
> Arch: x64

**Comment by MxRay** [comment]
I can confirm same behavior.

Env:
> Version: 0.5.14
> Platform: win32 (x64) - Windows 10 Pro 1709 Build 16299.192 
> Electron: 1.7.8
> Chromium: 58.0.3029.110
> Node: 7.9.0

**Comment by ManInBlack0007** [comment]
I can confirm it, too. And the choosen colour for skintone is reseted. 

Version: 0.5.14
Plattform: win32 (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0
