### ISSUE TITLE
Cannot delete Discord tab after adding it once

### ISSUE THREAD

**Issue by practiseo** [ramboxapp/community-edition#1422]
### Steps to reproduce

1. Open app, and click on Discord as an action to add a new Service
2. Focus tab[n] where Discord is running
3. Go back to the first tab - Rambox tab
4. On the side click on the trash bin in the Discord line
5. Confirm with Yes
6. See how the screen is not ending

### Expected behavior

To be removed and that's it

### Actual behavior

The removing screen runs forever. No hotkey action possible. No way to escape the hang interface. Had to kill the app.

### ENVIRONMENT

Windows10 v1709
Rambox 0.5.14 x64
Electron: 1.7.8

**Comment by saenzramiro** [comment]
Seems like is hanging because it can't remove the session data from your PC.

https://github.com/saenzramiro/rambox/blob/003a5349a14378987380d181256313b1e59c83d4/app/view/main/MainController.js#L137-L152

Is Discord enabled? Is so... try to remove it when Discord finished loading (check the bottom toolbar to show a "Ready" status), and then remove it.

Works?

**Comment by simonszu** [comment]
I have the same issue sometimes. A workaround is to exit rambox completely, restarting it, and removing the service again.

**Comment by ArtursO** [comment]
This stupid issue coupled with the fact that doing the sync between computers creates a bunch of duplicate accounts has made using Rambox for me completely unbearable. 

I'm trying to delete all these duplicate accounts, I turn all of them back on, start deleting them one by one (each taking about 5-10 seconds to be deleted), and then at some point one of the services I'm trying to delete (that I've already re-enabled) sticks me in an infinite delete load bar loop from which I can't get out, then I restart Rambox and poof! all the services I just tried deleting are back.

My options are
1. make a new account
2. delete rambox and use something else

I know this is free software and it's open source which is great but just giving you my user experience here.
