### ISSUE TITLE
problem with telegram

### ISSUE THREAD

**Issue by mathieu-stg** [ramboxapp/community-edition#1424]
hello, I have a problem with my application, when he connects me with telegram the page is not displayed entirely, I can not read my last messages that are cut
how can I do?
thxs!

	
	-
	> Rambox 0.5.14
	> Electron 1.7.8
	> win32 x64 10.0.16299

**Comment by ManInBlack0007** [comment]
Does the shortcut Ctrl+0 in the telegram tab solve your problem?

As an alternative press the shortcut Ctrl+- for zooming out.
