### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Airgreg** [ramboxapp/community-edition#1425]
Hello!
There is no sound playing video at any applications.

	
	-
	> Rambox 0.5.14
	> Electron 1.7.8
	> win32 x64 6.3.9600

**Comment by joaotorres** [comment]
Are you sure your "Don't disturb" mode isn't turned on? I just created an issue about this here: https://github.com/saenzramiro/rambox/issues/1475

**Comment by heber-junior** [comment]
I had this problem and I solved reinstalling the application.
I do not know what happened to be without sound.

**Comment by hknoener** [comment]
I'm facing the same problem.

There's no sound for audios from any of the services. They were working until last night without any problem. There was also no update during this time, no version difference.

Services that I have tried are Facebook Messenger, Whatsapp, Discord, Slack and Rocket Chat.

Rambox: 0.5.17
Platform: Darwin (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1
