### ISSUE TITLE
Disable Content security Policy for custom code.

### ISSUE THREAD

**Issue by noonien** [ramboxapp/community-edition#1432]
### Steps to reproduce

1. Try to load custom userstyle for WhatsApp using the following script:
```js
(function(url) {
    var s = document.createElement('link');
    s.setAttribute('rel', 'stylesheet');
    s.setAttribute('type', 'text/css');
    s.setAttribute('href', url);
    document.getElementsByTagName('head')[0].appendChild(s);
})('https://userstyles.org/styles/134440.css');
```

### Expected behavior

`link` element added to DOM and style loaded.

### Actual behavior

`link` element added to DOM, style not loaded, console shows error: 
```
Refused to connect to 'https://userstyles.org/styles/134440.css' because it violates the following Content Security Policy directive: "connect-src 'self' wss://*.web.whatsapp.com https://*.whatsapp.net https://dyn.web.whatsapp.com https://*.giphy.com https://*.tenor.co blob: https://crashlogs.whatsapp.net/wa_clb_data https://crashlogs.whatsapp.net/wa_fls_upload_check https://www.bingapis.com/api/v6/images/search".
```

### ENVIRONMENT

> Rambox: v0.5.14

> OS: XUbuntu 17.10

> Arch: x64

**Comment by Ash258** [comment]
Offtopic!
If you download it as `https://userstyles.org/styles/{STYLEID}.css`. Does its content changes on update?

**Comment by noonien** [comment]
I'm not sure, however, if the style id does not change with an update, I believe it's safe to make that assumption.

**Comment by Ash258** [comment]
@noonien Yeah it's content is changing on update (Tested on my userstyle). You changed my life with this 😱👍

**Comment by noonien** [comment]
Any updates on this?
