### ISSUE TITLE
Tweetdeck does not show arrival of new Tweets in tab and global unread counter

### ISSUE THREAD

**Issue by knut-hildebrandt** [ramboxapp/community-edition#1434]
I've got two Twitter-Accounts added to Rambox. In both "Display tab unread counter" AND "Include in global unread counter" are checked. Nevertheless the arrival of new tweets does neither change the taskbar icon nor show in the tab. Within Tweetdeck I selected various options to display notifications. In some timelines I enabled "Sound" AND "Desktop Notifications" enabled and in others either or neither of them. That all makes no difference. Furthermore in one account "Show notifications" is enabled in the other not. I do not see any difference neither. Thus I wonder what the correct setup is to get notified via the "Unread counters" while not getting "Desktop notifications" all the time.

Besides the two Twitter-Accounts I've Skype, WhatsApp and Wire enabled. For these accounts the "Unread counters" work at least as long Rambox is running while the messages arrive.

### ENVIRONMENT

> Rambox: v0.5.14

> OS: Chakra Linux

> Arch: x64

**Comment by knut-hildebrandt** [comment]
No change with v0.5.15

**Comment by Ash258** [comment]
Do you get notifications in normal browser? (like Chrome and Firefox) When I enable all type of notifications for messages, notifications and home panel in normal browser I don't receive any notification. Unread count could be possible for Messages and notifications I think.

**Comment by knut-hildebrandt** [comment]
If I enable "desktop notifications" and "sound" in tweetdeck and do not disable them in the Rambox settings for the tweetdeck account I get notifications shown through the Plasma notifier. That works as good as it does for Skype, WhatsApp and Wire. What does not work is, that the ram turns red on new tweets. Neither the tweetdeck tap of the account that the tweet arrived to is marked red. For Skype & Co. that works fine.

BTW, neither the taskbar icon nor the tabs indicate new arrived messages or tweets when these arrived while Rambox was not running. Only messanges arriving while Rambox is running will be indicated.

**Comment by Ash258** [comment]
@knut-hildebrandt You can get unread counter for new messages with this custom code:
```javascript

function checkUnread() {
	const elements = document.querySelectorAll('.msg-unread-count');
	let count = 0;
	if (elements[0]) {
		count = parseInt(elements[0].innerHTML, 10);
	}
	updateBadge(count);
}

function updateBadge(count) {
	if (count && count >= 1) {
		rambox.setUnreadCount(count);
	}
	else {
		rambox.clearUnreadCount();
	}
}

setInterval(checkUnread, 1e3);
```

I cannot test some other code because it'd difficult to test some use cases only for me. 
New tweets doesn't have any counter in Tweetdeck, so there could be only sound notifications and normal. Not working notifications need to be investigated, but in Firefox I didn't receive any notifications.

**Comment by knut-hildebrandt** [comment]
@Ash258 I'm not sure if I got it right. If I copy above mentioned JavaScript into the custom code area of the TweetDeck account the ram will turn red on arrival of new messages as well as their number will be shown in the accounts tab? Well, I tried it but it did not work.

For test purposes I added my twitter account directly through the website twitter.com and counter work fine.

**Comment by knut-hildebrandt** [comment]
> Do you get notifications in normal browser? (like Chrome and Firefox) When I enable all type of notifications for messages, notifications and home panel in normal browser I don't receive any notification. Unread count could be possible for Messages and notifications I think.
Since I got a message, that this thread will be closed soon I re-read your message and saw that I somehow misunderstood it. Well, neither in Firefox nor in Chrome tabs, not even within Tweetdeck, are marked on the arrival of new tweets. That is why I suppose this is a Tweetdeck issue and not one related to Rambox.Thus this issue can be closed as unresolvable ;-) Thanks for looking into the matter.
