### ISSUE TITLE
Remove rambox tab?

### ISSUE THREAD

**Issue by shaun-sweet** [ramboxapp/community-edition#1437]
I'm not finding a way to remove the rambox tab.  Am I just missing how to do that?  Otherwise, are you open to a PR for support with this?

**Comment by DavidHazeldenUK** [comment]
Yeah same problem, I added Skype twice and couldn't remove.
There is an option in Edit >> Delete, but it doesn't seem to work on the tab.

**Comment by bmadjic** [comment]
Go to main menu (by clicking on the logo). You should arrive to page with all services available. 
On the right you should have all the services you use, to delete one just hover it and click on the trash

**Comment by DavidHazeldenUK** [comment]
I had an old version, as it was installed from a package manager, my bad, thanks for replying, appreciate it.

**Comment by kentoku24** [comment]
I feel that it would be more convenient if there is "remove" menu when I right-click a tab.

**Comment by brady-young** [comment]
@kentoku24 totally agree.  This is a must have feature request.
