### ISSUE TITLE
Master Password - Can't paste passwords

### ISSUE THREAD

**Issue by Soraph** [ramboxapp/community-edition#1439]
If you set the master password you cannot paste the password in the login screen when the program is opened, forcing you to expose the password untill you have typed it all.

If this is a security feature it is pretty dumb

	
	-
	> Rambox 0.5.14
	> Electron 1.7.8
	> darwin x64 17.4.0

**Comment by TheHaso** [comment]
If you are able to copy your master password from somewhere, its even dumber.

**Comment by jacebenson** [comment]
@TheHaso 
Regardless how the user has the password stored, this program shouldn't dictate if or how the user can input it.  It may be from a password manager, in which case it would be argued it's more secure.

**Comment by Soraph** [comment]
So, news about this? It is really annoying to be forced to type in the password for no reason
