### ISSUE TITLE
Option to disable clipboard access in tabs

### ISSUE THREAD

**Issue by poisonborz** [ramboxapp/community-edition#1440]
Modern webapps have easy access to clipboard contents.
Messenger's new "feature" is that if you press ctrl-v,  and your clipboard content is an image, it gets posted without any further warning, and obviously without any method to delete your message afterwards.
This is a huge potential privacy risk, a wrong keystroke can expose whatever you currently have copied. Other Rambox services might behave similarly. As Rambox is used more like a chat app instead of browser tabs, these kind of incidents could happen more often.

Creating a per-service or global option to set this Chrome flag is probably a minor task, and it would make a good boost in privacy.

**Comment by Soraph** [comment]
Is not just Messenger, is most of the modern chat systems via web or not (just to name some: discord, slack, watsapp, teelgram).
