### ISSUE TITLE
Can't Scroll Down or Type - Help!

### ISSUE THREAD

**Issue by terrapin421** [ramboxapp/community-edition#1444]
My Rambox is cut off on the bottom and sides. I can't scroll down to the bottom to type and I can't see the sides. I've tried adjusting zooms/going full screen etc. etc.

	
	-
	> Rambox 0.5.14
	> Electron 1.7.8
	> darwin x64 17.3.0

**Comment by derekprice** [comment]
I'm seeing this issue too. It's making Rambox unusable since the update, since all apps are affected. I am not able to see the message field in any of the apps. I've attached a sample below. 

<img width="1430" alt="screen shot 2018-02-08 at 3 24 54 pm" src="https://user-images.githubusercontent.com/24576813/35999246-c7e8b1a4-0ce4-11e8-8071-465167ff0acc.png">

**Comment by derekprice** [comment]
Update: View > Actual Size fixed it, and I'm free to zoom in and out from there. Not sure why this fixed it, but it did.

**Comment by terrapin421** [comment]
That did not work for me

**Comment by terrapin421** [comment]
yeah it's like everything is aligned down and to the right.... anyone?

**Comment by wvankuipers** [comment]
I have the same issue, the fix suggested by @derekprice didn't work for me....

**Comment by gitlon** [comment]
I had this same problem - Rambox seemed to be drawing its contents in a window bigger than the application, meaning the bottom and right contents were lost.

This persisted across uninstall/reinstall and version changes (I tried downgrading), making Rambox unuseable. 

I fixed it by uninstalling AND deleting the application 'preferences' or 'config' file - on my Mac it was something like `~/Library/Application Support/Rambox/config.json` (but I dont recall the exact file, sorry). Then reinstall.

That config file seemed to contain "window height" and "window width" values for the app, which got broken/unmodifiable somehow (just my guess).

**Comment by visomar** [comment]
This just happened to me too, and I'm not sure what triggered it (no change of configuration, no moving between screens,...).
![2018-04-26 10_55_58-rambox - slack](https://user-images.githubusercontent.com/7437402/39296310-df70c3be-4940-11e8-98fa-a266040841ca.png)
System: Windows 10
