### ISSUE TITLE
Problem of scale

### ISSUE THREAD

**Issue by bmadjic** [ramboxapp/community-edition#1451]
Hi, 
first of all, thank you for developing this applicatio. it's a very nice one and big timesaver.
I just have issue with the scale. The applications don't fit to the windows.

Here's to picrture to illustrate.	
![image](https://user-images.githubusercontent.com/25118724/36203918-95a1d6e0-1189-11e8-971c-f10b5f0105d8.png)

Best regards, Benjamin

Just launch the application normally on windows 10 

	
	-
	> Rambox 0.5.14
	> Electron 1.7.8
	> win32 x64 10.0.16299

**Comment by Ash258** [comment]
@bmadjic Could you provide your windows resolution (dxdiag should be enough)?

**Comment by bmadjic** [comment]
![image](https://user-images.githubusercontent.com/25118724/36233915-95514efa-11e8-11e8-8cf7-b9c3e79b598b.png)

**Comment by rosoft2001** [comment]
I have the same problem: Windows 10, 4K monitor, all services use only about 75% of width.

![image](https://user-images.githubusercontent.com/113961/36852214-217e0c46-1d39-11e8-90a7-ddee3a46aa84.png)

**Comment by fsimonis** [comment]
Same Problem independent of the resolution and DPI setting.

> Rambox 0.6.1
> Electron 2.0.8
> linux x64 4.18.12-arch1-1-ARCH

**Comment by fsimonis** [comment]
Is there any progress on this issue?

**Comment by fsimonis** [comment]
The problem persists, Mr stale bot.
