### ISSUE TITLE
Badge notifications on Mac does not update consistently

### ISSUE THREAD

**Issue by vTide** [ramboxapp/community-edition#1452]
Badge notifications on Mac does not update consistently (or not at all).  I am running a Mac, and I use Rambox for Microsoft Teams, Slack and Whatsapp

	
	-
	> Rambox 0.5.14
	> Electron 1.7.8
	> darwin x64 17.4.0

**Comment by Ash258** [comment]
@vTide Please go to https://github.com/saenzramiro/rambox/issues/1446#issuecomment-365288366 and use this solution. WhatsApp has a bug in rambox.
Do you still have issue after that temporary solution? 

WhatsApp has bug and the others should be fine.
