### ISSUE TITLE
Microsoft Teams - notification banner

### ISSUE THREAD

**Issue by Najkon** [ramboxapp/community-edition#1463]
Only in M$ Teams have a notification banner inside in program of RAMBOX
notification banner does show in system like other.

Just look on ScreenShot, on one we have notification banner from SLACK, they it shows up correctly in system
but there no anyone notification banner from M$ Teams
but when we have opened M$ Temas "notification banner" are show as a internal notification banner.

Anyone have that same inconvenience?

### ENVIRONMENT

Version: 0.5.14
Platform: linux (x64) - Debian 9
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0
![ss_20180220091136](https://user-images.githubusercontent.com/6454092/36414706-82c4e0e6-1623-11e8-9b9a-164254213cd4.jpg)
![ss_20180220083305](https://user-images.githubusercontent.com/6454092/36414707-82e00bd2-1623-11e8-895b-38a6ad265f55.jpg)

**Comment by PaulGallon** [comment]
Yes, I'm experiencing the same issue. This would be an extremely useful feature.

**Comment by oscarrenalias** [comment]
I'm having the same issue on MacOS 10.12 and 10.13. I don't think it's a problem with Rambox because other apps that I'm using (Telegram, WhatsApp) use system notifications just fine.

**Comment by Najkon** [comment]
I think this can be a problem with interpretation of notifications only for Teams by Rambox that's why it shows internal notifications only.
it seems to me that it possible to redirect internal notifications to external for the system.

**Comment by dzek69** [comment]
Same issue. It can be hard without source code to find what triggers inner notification and overwrite it with native solution.

**Comment by dzek69** [comment]
bump

**Comment by dzek69** [comment]
mr bot, please don't. this issue is still relevant imo

**Comment by dzek69** [comment]
Activity

**Comment by maxerbox** [comment]
They aren't native Notification, I mean notification used by web browser to say something out of the browser.
You can check if there is a setting for that, or make a little script that watch for new notification from Ms team, and push them
That's maybe also a MS team behavior, when it's embedded inside electron : does there are browser notifications of you launch it in your browser ?

**Comment by SyntaxErrol** [comment]
This is weird, because they are standard notifications when running Teams in a browser. Even Windows 10 native ones, when enabling a setting in Firefox about:config. The standalone Teams client doesn't use native notifications though, but manages to push the custom banner to the desktop.
