### ISSUE TITLE
Add Google Keep to services

### ISSUE THREAD

**Issue by Logmytech** [ramboxapp/community-edition#1481]
I added Google Keep manually by adding

https://keep.google.com

Here is a logo of this

https://commons.wikimedia.org/wiki/File:Antu_google-keep.svg

However it'd be good if it was available as a service by default in Rambox

**Comment by yafp** [comment]
As i am using Keep myself as well i was wondering if i could just add it to the related [rambox-services-contrib](https://github.com/saenzramiro/rambox-services-contrib) repo.

Is that the way to go?

**Comment by yafp** [comment]
Well i would still know if adding keep to the raombox-services.contrib repo is the way to go or not? ;)

**Comment by benswolo** [comment]
I would like keep as well, although it isn't too bad to add it manually. I don't think rambox recognizes .svg files, though, and I can't find an exceptional web-hosted picture of keep...

**Comment by benswolo** [comment]
bump
