### ISSUE TITLE
Hipchat not loading any more

### ISSUE THREAD

**Issue by yourpositionZH** [ramboxapp/community-edition#1489]
Since the update today Hipchat is not loading any more

Steps:
- Restart Rambox
- Hipchat not loading (Load Image never stops)
- Create new Hipchat Connection
- Open Hipchat = blank page

	
	-
	> Rambox 0.5.15
	> Electron 1.8.2
	> win32 x64 10.0.16299

**Comment by Rabusek** [comment]
I have the same issue with other service (Glip), and noticed that going down to .14 version resolves the issue.

You can find it here:
https://github.com/saenzramiro/rambox/releases/tag/0.5.14
@yourpositionZH

**Comment by ethanosullivan** [comment]
Downgrading does work. However, Rambox auto updates it to the latest version if I restart the application. is there a way to set updates to be manual?

**Comment by 88scythe** [comment]
Same issue with Asana. Stuck on the loading icon. Indeed solved when downgrading to 0.5.14.
@yourpositionZH maybe update bug title?
