### ISSUE TITLE
Mac version isnt opening links in the browser properly

### ISSUE THREAD

**Issue by KITSJamesWalker** [ramboxapp/community-edition#1490]
### Steps to reproduce

1. On a mac, click a link to a web page
2.  Chrome opens a new browser but does not navigate to url
3. 

### Expected behavior

If Chrome is open, it opens a new tab an navigates to the url

### Actual behavior

New chrome window opens and does not navigate to url

### ENVIRONMENT

> Chrome 64.0.3282.167

> Rambox: v0.5.14

> OS: OSX high Sierra 10.13.3

> Arch: x64

**Comment by jlorencelim** [comment]
Experienced the same issue with  `Rambox v0.5.15`. It opens a new chrome window with an empty url.

**Comment by raghunat** [comment]
Reopening chrome and updating to 0.5.15 fixed this for me. Perhaps chrome just pushed a new version, my version of chrome is `Version 64.0.3282.186 (Official Build) (64-bit)`
