### ISSUE TITLE
Audio no funciona

### ISSUE THREAD

**Issue by arqnogues** [ramboxapp/community-edition#1492]
Hola, hace tiempo tengo instalado Rambox, pero a partir de ayer, con la última versión no funciona el audio, pueden ayudarme? Gracias
Andrés

	
	-
	> Rambox 0.5.15
	> Electron 1.8.2
	> win32 x64 10.0.16299

**Comment by NgoHuy** [comment]
try clear cache and local storage, it worked for me, bro
