### ISSUE TITLE
Steam chat issue

### ISSUE THREAD

**Issue by Akimace** [ramboxapp/community-edition#1494]
1. since the update I'm always offline. 
2. Before this update I didn't need to start steam to be online.
3. I tryed to relog on steam chat but always offline.

> Version: 0.5.15

> W10

> win32 (x64

**Comment by Rabusek** [comment]
I have the same issue with other service (Glip), and noticed that going down to .14 version resolves the issue.

You can find it here:
https://github.com/saenzramiro/rambox/releases/tag/0.5.14
@Akimace

**Comment by Akimace** [comment]
@Rabusek if I down to .14 I have this issue : #1386
