### ISSUE TITLE
Modal to say the internet connection is not ready is a bit annoying

### ISSUE THREAD

**Issue by jerry1970** [ramboxapp/community-edition#1501]
When I boot my laptop (Ubuntu 17.10) with Rambox 0.5.15 set up to start with the system, sometimes the wifi connection is not up yet when Rambox is already starting.

Rambox then shows a modal telling me I have to check the internet connection. I have to click OK to close the modal, while the internet connection may have been established in the meantime. Rambox stops working and stays in view, while it usually minimizes when there is a connection.

Is it possible / easy to not show a modal but show the message in the status bar or even in a centered message? So I don't have to click OK. And if Rambox notices the connection is there, it can continue by itself.

Version: 0.5.15
Platform: linux (x64)
Electron: 1.8.2
Chromium: 59.0.3071.115
Node: 8.2.1

Thanks!

**Comment by percona-csalguero** [comment]
Agree. It is really really annoying.
I have to type a password in order to enable the wifi but I have to wait for this annoying modal to show, otherwise i have to switch the focus several times.

**Comment by jerry1970** [comment]
Wouldn't mind having a team member reply to this. No reply and then close it, not a good way to fix things, right?
