### ISSUE TITLE
Rambox does not allow access to any enabled services

### ISSUE THREAD

**Issue by dln949** [ramboxapp/community-edition#1503]
Ubuntu 17.10, Gnome 3.26.2 (Xorg); Rambox 0.5.15 linux (x64)

When I start Rambox, I get a screen that lists all the services Rambox offers on the left, and on the right I get all the services I have enabled.  However, nothing appears across the top, none of my enabled services appear.  In the top left corner is a Rambox icon, but clicking on it does nothing.  In the top right corner is my email address, but clicking on it does nothing.  If I decide to view preferences, all that happens is that the Rambox screen changes to a much lesser contrast, and in the bottom corner appears these two sentences:  "English is the only language that has full translation.  We are working with all the others, help us!"  

I do not know what is wrong, nor do I know what to do to fix this.  I have tried reinstalling Rambox, but that does not help.

**Comment by mkljun** [comment]
The same issue here afren an update to 0.5.15 on macOS High Sierra. 

<img width="1220" alt="screen shot 2018-03-04 at 14 00 39" src="https://user-images.githubusercontent.com/11471872/36945891-ccb15a3c-1fb4-11e8-9a66-8e28b7ab4976.png">
See the screenshot.

**Comment by mkljun** [comment]
Solved by completely uninstalling Rambox and starting adding services from scratch. 
A bit annoying if this needs to be done after every upgrade.

**Comment by dln949** [comment]
Yep, that is the EXACT same issue I am having.  

I have not yet tried a COMPLETE uninstallation and reinstallation.  

Instead of adding all my services again from scratch, is there a Rambox configuration file I can preserve?  Or, wouldn't it work to add them from the Rambox central cloud location (I forgot what that is called)?

**Comment by dln949** [comment]
Just now installed the 0.5.16 (64 bit debian) version of Rambox.  Still the exact same problem as described in my original post of this issue thread.

**Comment by mkljun** [comment]
Interesting. I upgraded yesterday and it picked up previously enabled services. Not sure what causes this problem.

**Comment by qwaal** [comment]
Exact same issue as above, but after upgrading to 0.6.1
