### ISSUE TITLE
Rambox doesn't launch

### ISSUE THREAD

**Issue by Plop** [ramboxapp/community-edition#1506]
### Steps to reproduce

1. Close/update Rambox
2. Try to open it
3. ???

### Expected behavior

Rambox should be launched if I want it to be launched.

### Actual behavior

It doesn't launch, I can't even reinstall it, I have to fully uninstall it and reinstall it

### ENVIRONMENT

> Rambox: Every version.

> OS: Windows 10

> Arch: x64

**Comment by HarsharanSingh007** [comment]
Same here and Can't able to remove also

**Comment by erlioniel** [comment]
Same.
OS: Win10
Arch: x64

**Comment by Corchoneitor** [comment]
Hi Plop.

I cannot reproduce this. Is this happens only when updating? Can you give me more information?

Thanks.

**Comment by Plop** [comment]
Hi,

No, I have this issue quite often actually. Almost 8/10 times when I close the app or update.

I had already talk about it on the Gitter : 

@Plop
sept. 27 2017 11:35

Hi. I don't know if this is a known issue as I don't find it on github, but I have some troubles launching Rambox (latest version, and since a while) on W10. I closed it, and now that I want to launch it again, it only shows up as 2 process in windows task manager, but it doesn't launch. It's not hidden, the process will just disappear after a few seconds, and I can't launch it without rebooting my computer.


I can't really give more info, as I don't understand what's going it.
It's really just "I close/update the app, I can't launch it again, I have to reboot my computer in order to make it work again".

**Comment by erlioniel** [comment]
The only way how it was able to run rambox in my case - full reinstall with settings cleanup to the previous version. Not sure that the root cause was the update.
