### ISSUE TITLE
"Certification Warning" message on Wrike custom service tab

### ISSUE THREAD

**Issue by ZaLiTHkA** [ramboxapp/community-edition#1508]
Since updating to Rambox 0.5.15, the status bar for my custom service tab pointing to `https:www.wrike.com` has been showing "Certification Warning" and many of the interface images don't seem to load.

Checking through the latest version Chrome, the certificate is issued by "Go Daddy Secure Certification Authority - G2" and is still valid until "2020-08-30".

Any suggestions here?

	
	-
	> Rambox 0.5.15
	> Electron 1.8.2
	> win32 x64 10.0.14393

**Comment by Corchoneitor** [comment]
Hi ZaLiTHkA.

Have you tried to select "Trust invalid authority certificates" in the Custom Service form?

**Comment by ZaLiTHkA** [comment]
Hmm... To be honest, i didn't actually see an option like that. I'll try that in the morning when i get back to work (GMT+2 over here). Thanks for the tip.

However, I'm still curious about why this is coming up though.. Is this related to the Chromium version in the Electron update in the new Rambox?

**Comment by saenzramiro** [comment]
Yes, it's an Electron's bug. They fixed it in 1.8.3 as you can see here: https://electronjs.org/releases#1.8.3

I will release an update ASAP.

**Comment by ZaLiTHkA** [comment]
Cool beans.. Thanks Ramiro, appreciate that. :)

For what it's worth, the "Trust invalid authority certificates" option was already on, but toggling it's state (and restarting Rambox) doesn't seem to make any difference here.

Fortunately, the Wrike interface itself is still usable and I haven't found any broken functionality, so it's not the end of the world... But it does look a bit funny.

**Comment by ZaLiTHkA** [comment]
Just a quick note: looks like Rambox 0.5.16 has resolved this one. Even with "Trust invalid authority certificates", my custom Wrike tab is loading correctly again with no warnings.

Feel free to close this ticket whenever you like. :)

**Comment by ZaLiTHkA** [comment]
as per my last comment, this was actually resolved anyway. :)
