### ISSUE TITLE
Rambox v0.5.15 - Portable Fails to Delete Account

### ISSUE THREAD

**Issue by mcodexx** [ramboxapp/community-edition#1509]
### Steps to reproduce

1. Fails to delete an account
2. 
3. 

### Expected behavior

Deleting account

### Actual behavior

Spinning cursor won't stop

### ENVIRONMENT

Desktop

> Rambox: v0.5.15 - Portable

> OS: Win10Pro v10.00 Build 16299 RS3

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi mcodexx.

Accounts delete fine in my computer after some testing. Can you give us more information on how to reproduce this?

Thanks.

**Comment by joserebelo** [comment]
I can reproduce this 100% of the time when I try to delete a disabled account. If the account is enabled the problem doesn't happen. I'm running 0.5.16, installed.
