### ISSUE TITLE
Rocket chat external logins are not working

### ISSUE THREAD

**Issue by hwoarang** [ramboxapp/community-edition#1517]
### Steps to reproduce

1. Install 0.5.15 linux (x64)
2. Install rocket chat service which requires authentication in new window
3. No action

### Expected behavior

Rambox should prevent opening links to external browser but it should capture such behavior and open the links in rambox itself for authentication to work.

### Actual behavior

So one of the rocket chat instances I want to use creates a new window to enter the login credentials. This works fine in the browser, but in rambox/rocket chat, a new browser window is created. Once I enter my details in the browser, the rocket chat service in rambox doesn't react on it.

### ENVIRONMENT

linux x64 (openSUSE tumbleweed)

> Rambox: v0.5.15

> OS: Linux

> Arch: x64

**Comment by saenzramiro** [comment]
Yes, this is a known bug since first release. SSO with popups are not working, but if use redirects instead of popup works ok.

For Rocket.Chat there is an open issue in their repo to change popup to redirection. See here: RocketChat/Rocket.Chat/issues/8840

**Comment by ryanwest6** [comment]
Has a workaround been found? I'd like to start using Rambox but I use Rocketchat a lot and I'd like it to be integrated as well.
