### ISSUE TITLE
Feature Request: more info on tab bar

### ISSUE THREAD

**Issue by jerry1970** [ramboxapp/community-edition#1527]
By default, I see the Rambox window title bar and the tab bar (with the Rambox tab and the service tabs), not the menu bar. Having more information on the tab bar would make things easier

I regularly use the Do Not Disturb function. I know the shortcut F1 and it gives me a toast notification, but after that I only see whether it's enabled or disabled by clicking the Rambox tab.

I also regularly disable services to preserve memory and enable them briefly when needed (like google drive). When I disable a service, the tab is removed and I have to go to the Rambox tab to enable it.

Feature requests:
* Add an icon to the tab bar for Do Not Disturb, and clicking would not open any tab but simply enable/disable DND. It can be at the left or right or maybe shown in the "Enabled Services" so I can move its location.
* Let the tab bar show disabled services but in a disabled way so I can quickly access and enable them. The contents for a disabled service only needs to show a button to enable the service.
* Let the tab right-click menu have an option to enable/disable the service.
* Let the tab right-click menu have an option to edit the settings for that service.

### ENVIRONMENT

Version: 0.5.16
Platform: linux (x64)
Electron: 1.8.3
Chromium: 59.0.3071.115
Node: 8.2.1

**Comment by echosa** [comment]
> Let the tab right-click menu have an option to edit the settings for that service.

This is exactly what I would like to see.

**Comment by jerry1970** [comment]
So people don't react and you the issue no longer exists? Not even a reaction from the team?
