### ISSUE TITLE
Usability Improvement

### ISSUE THREAD

**Issue by CoalaJoe** [ramboxapp/community-edition#1529]
### Steps to reproduce

1. Open a messager inside rambox
2. Press Ctrl+W or Cmd+W

### Expected behavior

Close that messenger

### Actual behavior

Closes rambox

### ENVIRONMENT

> Rambox: v0.5.16

> OS: High Sierra

> Arch: x64

**Comment by Lazza** [comment]
This is not specific to macOS though.

**Comment by CoalaJoe** [comment]
@Lazza Thanks. Updated issue.

**Comment by Ash258** [comment]
@CoalaJoe How should **Close that messenger** should looks like? What should rambox do? LIke move to another service or what?

**Comment by CoalaJoe** [comment]
@Ash258 Disable would be okay.

**Comment by 88scythe** [comment]
I'm not sure if this is really the intended behaviour of Rambox, disabling or "closing" services on the spot seems to go against the whole intent of Rambox.

**Comment by marczz** [comment]
It depends what kind of user you are, may be you want never miss a message or a notification, and all your services are always needed. Personally there are some of services I seldom use, and many I just check once a day. I don't want to keep 150M of resident memory for these inactive services, so I disable/re-enable them in the service tab. A keyboard shortcut is not necessary, but using Ctrl-W to disable the service as propose @CoalaJoe  would be coherent with the web browser behavior where Ctrl-W close the tab in focus, while Ctrl-Q close the application. Ctrl-W to close rambox is an odd behavior.
