### ISSUE TITLE
Decrease height of tab bar on top

### ISSUE THREAD

**Issue by siwan05** [ramboxapp/community-edition#1537]
I think that the height of the tab bar on top is too big, we should be able to set the height of it or it should at least be smaller than it is today.

### ENVIRONMENT

> Rambox: 0.5.16

> OS: macos 10.13.3

> Arch: x64

<img width="1487" alt="screen shot 2018-03-16 at 09 26 29" src="https://user-images.githubusercontent.com/6042171/37511102-eb3493dc-28fd-11e8-91d7-0f1e6648e051.png">

**Comment by jerry1970** [comment]
Or accept custom CSS styling for the interface...

**Comment by rnyberg** [comment]
Here's a workaround until the developer implements it: https://github.com/saenzramiro/rambox/issues/1532

**Comment by siwan05** [comment]
Thanks, will go with that for now!
