### ISSUE TITLE
Unable to Use Yahoo Mail

### ISSUE THREAD

**Issue by frag-o-matic** [ramboxapp/community-edition#1540]
### Steps to reproduce

1. Open Rambox
2. Add/Open Yahoo Mail as a service
3. Open the Yahoo Mail tab

### Expected behavior

Able to view Yahoo Mail Inbox screen

### Actual behavior

Looks to be the same/similar issue as #1054 
See Screenshot below: 
![Screenshot](https://i.imgur.com/eZGFflq.png)

### ENVIRONMENT

> Rambox: v0.5.16

> OS: Linux (Ubuntu 16.04)

> Arch: x64

**Comment by GarciaPL** [comment]
Did you try to update Rambox to version 0.5.17 and try once again ?

**Comment by frag-o-matic** [comment]
@GarciaPL nope, moved to Franz.
