### ISSUE TITLE
Rambox.appimage Icon from the taskbar is missing  

### ISSUE THREAD

**Issue by Lvaskz** [ramboxapp/community-edition#1541]
Linuxmint 18.3
64 bits
Cinnamon 3.6 Desktop 
When I use rambox appimage the icon from the taskbar is missing. Deb package has it.

**Comment by jerry1970** [comment]
Same here:
Ubuntu 17.10
64 bits
XFCE desktop 4.12

The notification area has an icon but the taskbar icon is missing.

![image](https://user-images.githubusercontent.com/5627407/37831044-743c5650-2ea4-11e8-9c38-46223b2fc8d0.png)

**Comment by yafp** [comment]
- Ubuntu 16.04
- XFCE

Icon is missing in taskbar.

In addition: the icon is as well missing in the window-preview of the app-switcher (via TAB-key)

**Comment by brunofunnie** [comment]
Same here, I even tried to create the rambox.desktop file but no luck with the dock's icon

![image](https://user-images.githubusercontent.com/5279392/39378724-98fc97ec-4a2f-11e8-8bbd-bd3341aa2842.png)

**Comment by Lvaskz** [comment]
any progress?

**Comment by jerry1970** [comment]
Icon still missing though.
