### ISSUE TITLE
Idioma de autorrección

### ISSUE THREAD

**Issue by MauricioAedo** [ramboxapp/community-edition#1550]
Estimado, principalmente utilizando Imbox para redactar correos me doy cuenta que el corrector ortográfico e idioma no funciona como en el navegador normal de mi PC sin marcar ni corregir nada. ¿Cómo se puede configurar éste?

Cabe mencionar que esto pasa en todas las aplicaciones que tengo en Rambox como WhatsApp, etc.

Quedo atento, saludos.

	
	-
	> Rambox 0.5.16
	> Electron 1.8.3
	> win32 x64 10.0.16299

**Comment by Ash258** [comment]
This should be duplicate of #509 if i get it right.
