### ISSUE TITLE
Autologin for IRC

### ISSUE THREAD

**Issue by BGMcoder** [ramboxapp/community-edition#1551]
Version: 0.5.16
Platform: windows 7 (x64)

So I would like to replace my normal IRC client with one in RamBox.  I normally connect to freenode, and so I see three options: FreeNode, Kiwi IRC and IRCCloud.

However, even though I specify my login credentials and channels that I want to join, I have to re-enter these every time.  Is there a way to store credentials so it just works automatically?

**Comment by mloskot** [comment]
Looks like dup of #1170
