### ISSUE TITLE
 Error when I always receive message from whatsapp

### ISSUE THREAD

**Issue by daridimas** [ramboxapp/community-edition#1552]
Error when I always receive message from whatsapp.

![image](https://user-images.githubusercontent.com/37401029/37882282-2aec3388-30cc-11e8-8cfa-b442e2229179.png)

	
	-
	> Rambox 0.5.16
	> Electron 1.8.3
	> win32 x64 10.0.16299

**Comment by keplerk** [comment]
Same here, it started about one our ago

**Comment by skick3** [comment]
I have the same Problem at my Windows 10x64 System
The Problem begins if the PC/Notebook was locked (not SleepModus) and i get WhatsApp Messages

**Comment by Ash258** [comment]
Continue in #1656
