### ISSUE TITLE
Spotify in Rambox?

### ISSUE THREAD

**Issue by Perflyst** [ramboxapp/community-edition#1554]
The spotify client needs a lot of RAM and I think it would be less if there was a way to open spotify in rambox.
If I add spotify as a custom service, I get linked to https://support.spotify.com/de/using_spotify/system_settings/enable-the-spotify-web-player/

They tell me to enable `Allow site to play protected content`.
Is it possible to enable this?

**Comment by rnyberg** [comment]
Spotify requires a browser that supports Widewine encryption. I suspect Electron does not have it, or then Spotify just does a poor job of detecting the feature.

**Comment by Perflyst** [comment]
I found this: https://github.com/electron/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md

It allows you to play drm protected content with electron.

**Comment by saenzramiro** [comment]
I will take a look on that and see if we can enable it.

**Comment by saenzramiro** [comment]
As in [Electron docs](https://electronjs.org/docs/tutorial/using-widevine-cdm-plugin) said, we will need to build this Widevine for each version of Electron we use in Rambox and it will take so much time to do it. There's an [npm library](https://www.npmjs.com/package/electron-widevinecdm) that could help but is deprecated.
This lib seems to do all the job automatically but it doesn't support Windows. We will need to wait until someone can follow developing that lib so we can add it to Rambox. Hopefully someone of our community can help with this. 😃
