### ISSUE TITLE
Color label support in Gmail

### ISSUE THREAD

**Issue by EerieBits** [ramboxapp/community-edition#1555]
Rambox doesn't show colored labels in Gmail, they are all gray.

> Rambox: v0.5.16

> OS: macOS High Sierra 10.13.3

> Arch: x64

**Comment by bretterer** [comment]
Colors are working for me.

<img width="60" alt="screen shot 2018-05-01 at 4 40 27 pm" src="https://user-images.githubusercontent.com/1906920/39492696-6f1f8b64-4d5e-11e8-90ef-0abeecabea50.png">


> Rambox 0.5.17
> Electron 1.8.4
> darwin x64 17.5.0

**Comment by EerieBits** [comment]
Yeah, it seems to be working now. It didn’t when I made the labels.

Thanks.


On May 1, 2018 at 15:41:48, Brian Retterer (notifications@github.com) wrote:

Colors are working for me.

[image: screen shot 2018-05-01 at 4 40 27 pm]
<https://user-images.githubusercontent.com/1906920/39492696-6f1f8b64-4d5e-11e8-90ef-0abeecabea50.png>

Rambox 0.5.17
Electron 1.8.4
darwin x64 17.5.0

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/saenzramiro/rambox/issues/1555#issuecomment-385783629>,
or mute the thread
