### ISSUE TITLE
Unread counter is wrong when slack url ends with a number

### ISSUE THREAD

**Issue by AllanWang** [ramboxapp/community-edition#1577]
We have a slack that ends with a number (2018), and the unread counter is constantly at 2018:

![image](https://user-images.githubusercontent.com/6251823/38448842-bcca1312-39d5-11e8-9ce5-46f010107c38.png)

Note that the tab name has nothing to do with the number, as I have already tried changing it.

	
	-
	> Rambox 0.5.16
	> Electron 1.8.3
	> linux x64 4.15.15-1-ARCH

**Comment by Ash258** [comment]
Rambox version? OS? Why did you delete issue template?

**Comment by AllanWang** [comment]
Sorry, I sent the issue again through Rambox to update the versions.
