### ISSUE TITLE
I do not get any flashing taskbar notifications for new messages, no matter what I try.

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#1578]
### Expected behavior

I expect to see the program flash in the toolbar a few times whenever there is a new message, much like skype messenger does, for example. I think in theory this is possible, no? I've tried with the program kept in try and taskbar too. Nothing.

### Actual behavior

But instead, the only thing that happens is the icon of Rambox changing from blue-white to blue-red. As a result I can miss messages and I end up checking the icon all the time when I am in a conversation while doing something else. In short, the notifications are totally broken for me and I am thinking to try another program like Franz, although this too has issues with its notifications.

### ENVIRONMENT

> Rambox: v0.5.16

> OS: Windows 7 64bit

> Arch: Rambox says win32 (x64) in the About menu, so I am not sure what to make of it.

![clipboard01](https://user-images.githubusercontent.com/32174327/38453008-6f5a22ac-3a57-11e8-8633-6e3e69fe981c.png)

**Comment by Ash258** [comment]
Windows 7 does not support html5 notifications. So if you want them to be working upgrade from old system. No alternative program will help you with notifications.

**Comment by 613TheEvil** [comment]
I am sorry I won't change OS just for that... I hope a way can be found.
