### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [ramboxapp/community-edition#1580]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. This issue is not saying that your current logo is unsatisfactory, I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by GarciaPL** [comment]
It seems that there is one open PR, so maybe you might propose smth and just create PR, so wider audience might have a look on it.

**Comment by jbeguna04** [comment]
Thank you

**Comment by GarciaPL** [comment]
Do you still have a plan to do it or did you decide to leave it as it is?

**Comment by jbeguna04** [comment]
Im still making the designs. Sorry for the wait

**Comment by GarciaPL** [comment]
There is no problem at all, just take your time 👍

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/39662108-874c720e-508f-11e8-8349-1f4d4cc32067.png)

**Comment by jbeguna04** [comment]
sir do i need to make a pull request on this?

**Comment by GarciaPL** [comment]
I think that you might, so author and the wider audience might have a look at it. :+1:

**Comment by jbeguna04** [comment]
can i ask whats your role in this project sir?

**Comment by GarciaPL** [comment]
I am just a big fan of this project and maybe I might resolve few issues later on via PR's as well :smile:

**Comment by jbeguna04** [comment]
thank you sir
