### ISSUE TITLE
QUESTION: Does Rambox support Windows 10 toast notifications?

### ISSUE THREAD

**Issue by vpontin** [ramboxapp/community-edition#1583]
I didnt used this program for a while, and give up last time because some services wont show their notifications in anyway.

Does this changed in last updates?

Thanks in advance!

**Comment by g-uru** [comment]
Yeah +1 it doesnt show notifications for any app in Windows notification center.. Tried reinstalling, readding services..

**Comment by Ash258** [comment]
Sure it support notifications.

Enable notifications on service setting page insider Rambox ![Settings](https://i.imgur.com/KIaX4Kv.png)
_For some services you need to explicit enable notifications inside service. (Like Discord, FB messenger)_

**Comment by vpontin** [comment]
I mean the notification system isnt integrated with Windows 10 one, it shows in same way Chromium-based products does (Google Chrome, Vivaldi). In Google Chrome this situation will [change](https://windowsreport.com/google-chrome-action-center-notifications/) [soon](https://www.xda-developers.com/chrome-supports-windows-10-notifications/).

**Comment by g-uru** [comment]
I get audio notifications but no visual notifications whatsoever.. is this behavior normal?

**Comment by g-uru** [comment]
2 weeks have passed, so it is normal that there is no visual pop up like notifications about new messages?

**Comment by Ash258** [comment]
Don't use any of these you mention.
No.

**Comment by g-uru** [comment]
Noted, Do you maybe use Skype or Discord?

**Comment by g-uru** [comment]
Ok I tested it with a friend now. There are no toast notifications for Skype or Whatsapp, only the Symbol in SysTray turns red.

**Comment by spinda** [comment]
Windows 10 toasts aren't showing up for me either. The tray icons turns red, but there's no other indication, visual or auditory.

**Comment by spinda** [comment]
Notably, under "Notifications & actions" in the Windows settings app, Rambox doesn't appear in the list of notification senders.

**Comment by Ash258** [comment]
Electron has problem with latests windows versions. (https://github.com/electron/electron/issues/10864)

**Comment by vpontin** [comment]
@Ash258 but there's a workaround (`app.setAppUserModelId(process.execPath);`) as described on latest comments on that thread.

**Comment by spinda** [comment]
@vpontin It looks like Rambox is already doing something similar: https://github.com/saenzramiro/rambox/blob/3a4c89bd65c23284640d3f098c0b449f96ab6075/electron/main.js#L58
