### ISSUE TITLE
Outlook 365: Downloading mail attachments not working

### ISSUE THREAD

**Issue by somecoder42** [ramboxapp/community-edition#1584]
### Steps to reproduce

1. Add Office 365 Service and log in
2. Open an Email with an attachment
3. Click on the arrow and then "Download"

### Expected behavior

* File is downloaded within Rambox

### Actual behavior

* The link is opened in the external Browser (Firefox in my case)
* As the login session is not valid in this browser, the download is not possible that way

### ENVIRONMENT

Version: 0.5.16
Platform: linux (x64)
Electron: 1.8.3
Chromium: 59.0.3071.115
Node: 8.2.1

**Comment by somecoder42** [comment]
I tried to find the exact HTML tag used for the Download button with the developer tools to try some custom javascript to workaround the issue.
But I am only able to inspect the Rambox application, not the actual service (outlook 365 website).
How to do that?

**Comment by Tr4il** [comment]
I noticed this as well. It does work when you just click on the attachment so that it opens within the website, and then click the "Download" button.

**Comment by K5HV** [comment]
You can download attachments on "Preview" site. It'll be nice to have it working on normal view.

**Comment by alexthamm** [comment]
@K5HV Thanks for the tip! Unfortunately it doesn't work with json files because there is no preview available.
