### ISSUE TITLE
Implement wrapper for local Electron apps in Rambox tab

### ISSUE THREAD

**Issue by MurzNN** [ramboxapp/community-edition#1586]
At now many popular messaging and email apps are created via Electron technology, so works via Chromium browser engine like Rambox. Eg: Mailspring, Viber, VK Messenger, Skype (with group call feature), Signal, etc.

Is this possible to integrate external Electron apps into Rambox tab as frame wrapper, and intercept app indicator, unread counts, etc?

if we find some way, we can integrate more apps into Rambox, so solve issues like #1585, #847 etc.

**Comment by MurzNN** [comment]
https://stackoverflow.com/questions/36489955/combine-multiple-atom-electron-apps may be help with implementing

**Comment by alien2003** [comment]
Viber does not use Electron. It's native Qt

**Comment by MurzNN** [comment]
Related issue in Electron: https://github.com/electron/electron/issues/2438
