### ISSUE TITLE
Tabs are blank

### ISSUE THREAD

**Issue by BGMcoder** [ramboxapp/community-edition#1589]
My Rambox's tabs are empty.

They aren't *really* empty, though - they just are all white.  When I move the mouse over the window, I can see the cursor changing depending on the controls underneath it.  It's not antivirus either; sometimes it works.

Restarting the app doesn't fix it, and neither does restarting the computer.
I tried disabling and reenabling the services, but it didn't make any difference.
I tried disabling hardware acceleration and that didn't work either.

![screenshot_rambox_001](https://user-images.githubusercontent.com/1699670/38620464-22e03744-3d64-11e8-87a1-b5c7ff36348e.png)

So I ran the installer again, and now everything is black.
![screenshot_rambox_002](https://user-images.githubusercontent.com/1699670/38622306-7d6ea9b2-3d68-11e8-8008-1090b9a349a1.png)

And if I happen to "toggle developer's tools" then it creates a big black box on the side of the window.

	
	-
	> Rambox 0.5.16
	> Electron 1.8.3
	> win32 x64 6.1.7601

**Comment by BGMcoder** [comment]
Ah - I think I got it working...  I had to disable hardware acceleration AND enable high dpi support (I have three monitors running at 1920x1080.

**Comment by BGMcoder** [comment]
Okay, I'm having this problem again, and the hardware acceleration setting makes no difference.  I've restarted RamBox over and over, and reloaded the service, etc.  I can't get Microsoft Teams to show anything but a black area.

**Comment by GarciaPL** [comment]
Do you have still that issue?

**Comment by BGMcoder** [comment]
Sometimes - it is intermittent.  I'm wondering if it has to do with my graphics drivers.  I'm using an MSI z37 board with an i5-8600k with Windows 7.  Since Intel doesn't support win 7 with 8th gen processors, that means the onboard graphics does not work, so I have to use two graphics cards instead (for 3 monitors).  Sometimes the tabs black out in Rambox though.  I can't figure out a rhythm to it.

**Comment by GarciaPL** [comment]
Not sure if this ticket might help https://github.com/electron/electron/issues/10863 so you might play with this **disable-gpu** flag.
