### ISSUE TITLE
How to route connection through Tor on Tails OS?

### ISSUE THREAD

**Issue by 181519** [ramboxapp/community-edition#1591]
I have tried going into settings and setting proxy as localhost and 9050 but that doesn't fix it, still no connection to the internet.

Tails OS latest.

**Comment by KsenZ** [comment]
I have same problem

**Comment by TheRusedGnu** [comment]
This is the same problem https://github.com/saenzramiro/rambox/issues/740, there needs to be SOCKS support for it to work with tails also.
