### ISSUE TITLE
wechat login needs to scan QR code every time

### ISSUE THREAD

**Issue by RunningDongxu** [ramboxapp/community-edition#1592]
### Steps to reproduce

Every time when we login the wechat, we need to scan the QR code just like the web page version. If it is exactly same as the web version, then why we use a client?

### ENVIRONMENT

> Rambox: v0.5.16

> OS: Ubuntu

> Arch: 64

**Comment by shanness** [comment]
I fixed this by adding
```
setInterval(function(){location.reload();}, 600000);
```
to the custom code.  Has been stable for a few days now.
