### ISSUE TITLE
Ryver is displaying the mobile version instead of the desktop/web browser version . 

### ISSUE THREAD

**Issue by IAmNotAJerk** [ramboxapp/community-edition#1593]
1) add ryver and stay logged in (desktop view)
2) restart rambox 
3) ryver turninto mobile view

	
	-
	> Rambox 0.5.16
	> Electron 1.8.3
	> win32 x64 10.0.16299

**Comment by thennequin** [comment]
Temporary solution: you can reload the tab after resizing Rambox
![image](https://user-images.githubusercontent.com/2106096/39116754-80f55b04-46e5-11e8-83f1-db5de8e88453.png)

**Comment by Simon0Harms** [comment]
FYI:
I contacted the ryver support in the mid of last year.

Me:
> I use the Multi Messenger Browser http://rambox.pro/.
> The Problem is, that Rambox mostly use the mobile web Interface of Ryver.
> 
> Is there a possibility to force the Ryver Web Interface showing the
> Desktop Mode by using a specific url or inject java script code?

Ryver:
> Sorry about the issues with Rambox. That's certainly not an app we have tested with, but I THINK they use Chromium (embeddable Google Chrome), which should work fine with Ryver. The only reason it should be loading in "mobile" mode is if the browser window is less than about 610 pixels either horizontally or vertically. I'm curious...are you able to expand the Rambox browser window to make sure it larger than 610 pixels both horizontally and vertically, and reload Ryver? Once it loads in "desktop mode", it should stay there even if you then shrink your browser window.
> 
> We're also going to look into removing the code that puts Ryver into phone mode based on just the view size, and go off of the reported user agent instead.

Me:
> thanks for your answer
>  My Display is 1366*768
> I have on top and one bottom bar and then the place (Ubuntu Mate) and then the space which rambox need...
> => My Problem is the vertical size...
> 
> I wonder that you check the vertical size.
> If the horizontal size is to small, using ryver in desktop mode could be difficult but not if the vertical size is too small.
> 
> When i make the window bigger than my screen at the start it works.

Ryver:
> Thanks for the update on your screen size. I can see where that small height would cause problems. The reason the code is checking for either height or width is because not all devices were consistent in their reporting of screen size when we rolled out the mobile client. Sometimes the height would be reported as the width. So we ended up just looking for either one. 
> 
> I'll check with the mobile developer on that, and see if we can do something about it in the short term.

At the moment i can not force ryver to use the mobile Version with rambox oO

**Comment by thennequin** [comment]
Still present in 0.6.1

**Comment by thennequin** [comment]
Still present in 0.6.3
