### ISSUE TITLE
[WhatsApp] A workaround to listen to audio messages but keep sound muted?

### ISSUE THREAD

**Issue by orschiro** [ramboxapp/community-edition#1598]
Hi all, 

I would appreciate any ideas for a workaround to being able to listen to WhatsApp audio messages while keeping WhatsApp general sound muted. I don't like getting sound for incoming new messages but need to be able to listen to audio messages.

Any ideas how to achieve this are welcome!

**Comment by heber-junior** [comment]
I had this problem and I solved reinstalling the application.
I do not know what happened to be without sound.
