### ISSUE TITLE
ZoHo is logged out when closing and reopening app

### ISSUE THREAD

**Issue by Lillecarl** [ramboxapp/community-edition#1599]
### Steps to reproduce

1. Get a ZoHo account
2. Log in
3. Close Rambox
4. Open Rambox

### Expected behavior

Should pop in directly at my inbox

### Actual behavior

Ends up on a splash page about how great ZoHo is (https://www.zoho.eu/mail/)

### ENVIRONMENT

	> Rambox 0.5.16
	> Electron 1.8.3
	> darwin x64 17.5.0

**Comment by Lillecarl** [comment]
It might be worth noting that when doing the same steps in Google Chrome it doesn't leave me logged out, which should mean it's not on ZoHo's end it's broken 😄

**Comment by Lillecarl** [comment]
If i right click and reload it it'll also log out.

**Comment by rjacobs-r7** [comment]
The same thing happens with Google Inbox (using Okta as a single sign-on). Same thing, it works fine in the browser.

**Comment by Esteban-Rocha** [comment]
Hipchat does this too, I opted out to use native or in browser web apps, at this current status Rambox it's utterly useless for me until this is fixed.

I opened an issue on this too but maintainer not been responsive.

**Comment by rjacobs-r7** [comment]
Well that's one way to make it seem like your project has fewer bugs...

**Comment by ontherunvaro** [comment]
Way to go, closing unresolved issues because of no comments!

**Comment by ontherunvaro** [comment]
This is a problem with the Zoho domain (.eu vs .com), see https://github.com/TheGoddessInari/rambox/issues/64 for details, if anyone is interested.
