### ISSUE TITLE
[Feature Request] Add USERAGENT to options on creating custom service

### ISSUE THREAD

**Issue by ArmeF97** [ramboxapp/community-edition#1600]
Simply add an option to set the useragent in a custom service
It should be easy to do, because it's already possible to set a global one

**Comment by ArmeF97** [comment]
It's a feature request

**Comment by ArmeF97** [comment]
It has been implemented, but not as I mentioned.

As for now, you can set a global user agent.

The feature request is to set a single user agent different for every service I'm using

**Comment by ArmeF97** [comment]
it's still open

**Comment by ArmelliniFederico** [comment]
It's still open

**Comment by ArmeF97** [comment]
It's still open
