### ISSUE TITLE
NaN above my Slack icon

### ISSUE THREAD

**Issue by zufanka** [ramboxapp/community-edition#1610]
Getting a NaN above my Slack channel icon.
This is the only one, other don't have it.

![image](https://user-images.githubusercontent.com/2411066/39176300-c345474a-47ac-11e8-85a1-890f6e0a6db7.png)

### Steps to reproduce

Not sure about this. These are my settings:

![image](https://user-images.githubusercontent.com/2411066/39176278-b31fdcf4-47ac-11e8-9d16-3c128987ca8a.png)

It disappears if I uncheck "Display tab unread counter"

### Expected behavior

No Nan

### ENVIRONMENT

> Rambox: v0.5.16

> OS: Fedora 24

> Arch: x64

**Comment by Ash258** [comment]
Cannot reproduce with version 0.5.17. Try updating to latest version.
