### ISSUE TITLE
Jabber

### ISSUE THREAD

**Issue by HackerBaron** [ramboxapp/community-edition#1611]
There is one of the very first and popular protocols - XMPP (jabber.org, xmpp.org)

	
	-
	> Rambox 0.5.16
	> Electron 1.8.3
	> win32 x64 6.1.7601

**Comment by MurzNN** [comment]
It can be easily integrated via some public Jabber XMPP client, that works in browser, eg https://jwchat.org

**Comment by HackerBaron** [comment]
Hello!

jwchat.org does not work

2018-04-25 17:06 GMT+05:00 Alexey Murz Korepov <notifications@github.com>:

**Comment by MurzNN** [comment]
I add more links to Jabber web clients.

**Comment by arthurlogilab** [comment]
* https://movim.eu/
* http://getkaiwa.com/

**Comment by MurzNN** [comment]
Best solution at now is https://conversejs.org/ - we can integrate it with "Jabber" name and add small js that show counter.

**Comment by arthurlogilab** [comment]
+1 to keep this issue open

**Comment by MurzNN** [comment]
+1

**Comment by MurzNN** [comment]
Bump

**Comment by jkary** [comment]
Hey MurzNN,

I'm am also interested in Jabber integration.  Have you started anything?  Can you share?  I am happy to help out.

Jason

**Comment by MurzNN** [comment]
Bump

**Comment by arthurlogilab** [comment]
bump
