### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by Akimace** [ramboxapp/community-edition#1618]
Hello,
if it's possible, maybe add the instagram's chat?
Have a nice day

--

Si c'est possible, peut-être ajouter le chat d'instagram ?
La bonne journée !

> Rambox: v0.5.16

> OS: W10

> Arch: x64

**Comment by Ash258** [comment]
What webpage provide instagram chat?

**Comment by Akimace** [comment]
I though it's like messenger.

**Comment by filipe-silva** [comment]
This guy made it work with Web only, maybe it can be forked and adapted into rambox
https://github.com/ifedapoolarewaju/igdm

**Comment by brunorsini** [comment]
Instagram is the #1 thing I'm missing too. It should be possible because there is a Mac client for it, Flume. 

Already donated but will now subscribe to Pro in the hopes of helping fund this development! In any case, thanks for all the great work on Rambox
