### ISSUE TITLE
No Tray Icon on Ubuntu 18.04

### ISSUE THREAD

**Issue by Insasse** [ramboxapp/community-edition#1631]
### Steps to reproduce

1. Update from 5.13 to 5.17
2. clear cache

### Expected behavior

There is a tray icon.

### Actual behavior

There is no tray icon.
![screenshot from 2018-05-03 08-58-00](https://user-images.githubusercontent.com/13465328/39563368-203e10d0-4eb0-11e8-891d-ef7ee01381af.png)

### ENVIRONMENT

> Rambox: v0.5.17

> OS: Ubuntu 18.04 x64

**Comment by Lvaskz** [comment]
I suffer the same with rambox.snap, tray icon is not

**Comment by pszabo75** [comment]
This happens on all distributions that has Gnome 3.28. This version of Gnome completely breaks all system tray extensions. I tried "Topicon Plus" and "(K)StatusNotifierItem/AppIndicator Support" and  neither of those show any old style system tray icon. I think the solution here would be directly support status icons in Gnome Shell.
https://wiki.gnome.org/Initiatives/StatusIconMigration/
This should be a feature request.

**Comment by Faoc** [comment]
Doesn't seem to affect all Ubuntu systems, tried it with a fresh Ubuntu 18.04 x64 install and the tray icon works as expected.
![grafik](https://user-images.githubusercontent.com/14792436/40181709-075f0fb6-59ea-11e8-8187-52992cc2891e.png)
On a different Ubuntu 18.04 x64 system (with some installed extensions) it also works. 

Maybe you could some information on installed GNOME extensions.

**Comment by Insasse** [comment]
In my case I had to restart my gnome shell and it was there *_*

**Comment by pszabo75** [comment]
An update came out for Topicon Plus. Now I have tray icon.

**Comment by drazik** [comment]
Same problem here. Do we have to install some GNOME extension to get the tray icon back ?
