### ISSUE TITLE
Password cannot be pasted into master password field

### ISSUE THREAD

**Issue by R3J3CT3D** [ramboxapp/community-edition#1635]
### Steps to reproduce

1. Set master password
2. Close and re-open app
3. Cannot paste password into master password field

### Expected behavior

To be able to paste password into the field.

### Actual behavior

Command+V does nothing in master password field.
It works great before the last update.
I use a randomly generated password so I need to be able to paste it.
Also, in the master password field, I can't write the '^' and the '`' character 

### ENVIRONMENT

> Rambox: v0.5.17

> OS: MacOS High Sierra 10.13.4

> Arch: x64

**Comment by dkgndianko** [comment]
I have the same issue.
Using rambox V**0.5.17** on MacOs High Sierra **10.13**
My password is stored with a password manager I can't copy and paste it in the field.
I tried to type it manually but I have some special characters that the field doesn't accept.

**Comment by dkgndianko** [comment]
Finally I used [asar](https://github.com/electron/asar).

1. unpack the file app.asar from **/Applications/Rambox.app/Contents/Resources**. `asar extract app.asar fake`
2. Then I modifed the file **masterpassword.html** (removed `onkeyup="doValidate(event, this.value)"`and replaced `type="password"`by `type="text"`
3. I repacked all (`asar pack fake fake.asar && cp fake.asar app.asar`)
