### ISSUE TITLE
Left mouse button on systray icon does not work in KDE 5

### ISSUE THREAD

**Issue by lashkevi** [ramboxapp/community-edition#1645]
When I am pressing the left mouse button on the systray icon in KDE Plasma 5, nothing happens. I need to press the right button, and then to the "Show/Hide" menu line to get the window.

	
	-
	> Rambox 0.5.16
	> Electron 1.8.3
	> linux x64 4.4.126-48-default

**Comment by Ash258** [comment]
Try double left click 🙂

**Comment by lashkevi** [comment]
Just the same. No use.
