### ISSUE TITLE
No red dot notif for the new Gmail interface

### ISSUE THREAD

**Issue by rogejr** [ramboxapp/community-edition#1649]
### Steps to reproduce

1. add Gmail service
2. switch to new gmail interface

### Expected behavior

a red dot should be on the rambox icon whenever there's an unread email.

### Actual behavior

no red dot.

### ENVIRONMENT

> Rambox: v0.5.17

> OS: macOS High Sierra 10.13.4

> Arch: x64

**Comment by Ash258** [comment]
What is "new gmail interface"? Could you provide screenshot?

**Comment by M0UL** [comment]
it looks like thise: ![image](https://user-images.githubusercontent.com/5436726/39923887-d4c98bc6-5525-11e8-8f10-475df7295ddc.png)

**Comment by ashvagan** [comment]
Here is how I fixed it:

- Add Gmail as a _Custom Service
- While adding, in advanced, add the following code:

```
function checkUnread() {
    var e = document.getElementsByClassName("bsU");
    var t = 0;
    for( i = 0; i < e.length; i++ ) t += parseInt(e[i].innerHTML.trim());
    updateBadge(t);
}

function updateBadge(e) {
    e >= 1 ? document.title = "(" + e + ") " + originalTitle : document.title = originalTitle
}
var originalTitle = document.title;
setInterval(checkUnread, 3000);
```

**Comment by 1dot44mb** [comment]
@ashvagan You can change it to show unread mail count only (not sum of all folders) by changing the `for` loop to this;

~~`for( i = 0; i < e.length; i++ ) t += parseInt(e[i].innerHTML.trim());`~~

    if (e.length > 0) {
        t += parseInt(e[0].innerHTML.trim());
    }

**Comment by chadxz** [comment]
for the element selection portion of the script, i made this change:

```diff
- var e = document.getElementsByClassName("bsU");
+ var e = document.querySelectorAll(".ain .bsU");
```

**Comment by pauby** [comment]
Why has this been closed? The code supplied is a workaround, not a fix. Rambox should support this natively.

**Comment by zippeurfou** [comment]
@Ash258 when is the next released planned? Gmail is forcing everyone to move to the new design it would be nice to have rambox ready for it.

**Comment by Ash258** [comment]
Soon. After @saenzramiro finish CI/CD problems / tweaks and relese it.

![Soon](https://i.imgur.com/pLyKMbf.png)
