### ISSUE TITLE
Autoupdate link in osx version leads to windows version

### ISSUE THREAD

**Issue by karmacoma7** [ramboxapp/community-edition#165]

**Comment by saenzramiro** [comment]
I tested in my Mac and works ok. Download the DMG file.

**Comment by MrChick** [comment]
My update notification lead me to Rambox.Setup.0.4.1-ia32.exe (which also lead to a smartscreen alert), even though I'm running 

> Version: 0.4.0
> Platform: win32 (x64)
> Electron: 1.2.6
> Chromium: 51.0.2704.106
> Node: 6.1.0

Should have been Rambox.Setup.0.4.1-x64.exe.

Sorry for hijacking the OSX-Thread, but I think it's the same base issue

**Comment by saenzramiro** [comment]
@MrChick Yes, I was aware of that. It's a Nuts bug, but I fix it in 0.4.1. Hopefully all users using x64 notice that and download it from the rambox.pro website.
