### ISSUE TITLE
A JavaScript error occurred in the main process - Uncaught Exception: TypeError: Error processing argument at index 0, conversion failure from ... Icon.ico

### ISSUE THREAD

**Issue by dzek69** [ramboxapp/community-edition#1656]
Looks like #1386 isn't fixed yet (it's closed and I can't reopen, so I started another one).

### Steps to reproduce

1. Add Slack on Windows machine
2. Use it for a while
3. Let some notfications pile up (from both channels and DM)
4. Switch from/to Slack service

### Expected behavior

Normal switch should happen

### Actual behavior

Error pops up every time I switch
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from C:\Users\dzek\AppData\Local\Rambox\app-0.5.17\resources\app.asar\resources\Icon.ico
    at Object.exports.setBadge (C:\Users\dzek\AppData\Local\Rambox\app-0.5.17\resources\app.asar\electron\tray.js:76:10)
    at updateBadge (C:\Users\dzek\AppData\Local\Rambox\app-0.5.17\resources\app.asar\electron\main.js:282:7)
    at BrowserWindow.mainWindow.on (C:\Users\dzek\AppData\Local\Rambox\app-0.5.17\resources\app.asar\electron\main.js:219:52)
    at emitTwo (events.js:125:13)
    at BrowserWindow.emit (events.js:213:7)
    at WebContents.webContents.on (C:\Users\dzek\AppData\Local\Rambox\app-0.5.17\resources\electron.asar\browser\api\browser-window.js:82:10)
    at emitThree (events.js:135:13)
    at WebContents.emit (events.js:216:7)

[OK]
```

Additionally `NaN` is visible near Slack icon instead of notifications count when I edit Slack service.
It looks like that: 
![rambox_2018-05-17_15-36-31](https://user-images.githubusercontent.com/4936805/40180931-3ba89096-59e8-11e8-8425-35efcff049dd.png)

BTW: I don't know if this is a feature but Slack usually shows me dot instead of notifications count: 
![rambox_2018-05-17_15-37-58](https://user-images.githubusercontent.com/4936805/40181005-64388cd2-59e8-11e8-86a3-e5ac591b32ea.png)

### ENVIRONMENT

> Rambox: v0.5.17 (current newset)

> OS: Windows 10 ver 1803 build 17134.48

> Arch: x64

**Comment by fyby** [comment]
I have exactly same issue. I have latest version, 64bit on Windows 10. Im using Linkedin, Skype, Slack, WhatsApp and Messenger plugins.

**Comment by nniesen** [comment]
Same issue with W10:
```
Version: 0.5.17
Platform: win32 (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1
```
Usually "File > Quit Rambox" clears it up for a few days and then it comes back.

**Comment by MRNiemeier** [comment]
Same exact error. It can't set the notification icon properly for some reason. Other times the icon in the task bar just stays a blank page.

**Comment by taylorjdawson** [comment]
I have the same issue:

![rambox_error_li](https://user-images.githubusercontent.com/29665732/41875589-2c13b14a-7880-11e8-9bfe-e8aa30c0487c.jpg)


Using:
- Pulse SMS
- GroupMe
- Allo
- Messenger
- WhatsApp
- Gitter
- Wire
- Inbox



> Rambox 0.5.17
> Electron 1.8.4
> win32 x64 10.0.17134

**Comment by oliversalzburg** [comment]
What exactly is holding off a fix for this issue?

**Comment by oliversalzburg** [comment]
Disabling the tray icon seems to work around the issue for the time being:

![image](https://user-images.githubusercontent.com/1658949/42383870-dde6d6ac-8138-11e8-8d9a-be2739ef1be4.png)

**Comment by camrodam** [comment]
bump - the bug has popped up again..

**Comment by arnobbhanja** [comment]
> 
> 
> So it looks like that there may be a solution [here](https://github.com/electron/electron/issues/7657/#issuecomment-368236509)?

will 've to work with this ~until~ **IF** it ever gets fixed

**Comment by saenzramiro** [comment]
@camrodam Are you sure is the same error?
In the latest version, we improve the code to prevent this. If this still happens, I think the error is related to group notifications and PM notifications badges.
