### ISSUE TITLE
I lost my number cause whastapp ban my number while conected to your software 

### ISSUE THREAD

**Issue by zydone** [ramboxapp/community-edition#1664]
I use your software to text from it and immediately my number got ban I send email to whastapp and hey say I am using a third party application the only thing I used if your software can you explain ?

**Comment by petarov** [comment]
That seems absurd. Rambox is UI tool where [web.whatsapp.com](https://web.whatsapp.com) is presented. And that website is Whatsapp' service. Ask them what is the 3rd party software name.
