### ISSUE TITLE
Rambox won't open links from Hangouts Chat

### ISSUE THREAD

**Issue by bcbane** [ramboxapp/community-edition#1672]
### Steps to reproduce

1. I'm on mac not sure if this affects other versions. Open Rambox and setup a Hangouts Chat window
2. Send or receive a message with a url and try clicking it

### Expected behavior

The Url should open up the link in the computer's default browser

### Actual behavior

nothing happens

### ENVIRONMENT

> Rambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

**Comment by thomasheidenreich** [comment]
Same hier on Windows 10

**Comment by weinpete** [comment]
For some reason, links to google.com and it's services seem to work. But only them ...

**Comment by rafaellages-hotmart** [comment]
Same on MacOS High Sierra (10.13.6)

**Comment by rsukonovs** [comment]
Same here on Ubuntu 18.04.

**Comment by rafaellages-hotmart** [comment]
Bump!
