### ISSUE TITLE
Telegram prevents computer from sleeping

### ISSUE THREAD

**Issue by svenjacobs** [ramboxapp/community-edition#1673]
### Steps to reproduce

1. Add Telegram as a service
2. Receive a video via Telegram 
3. Play the GIF (videos are displayed as GIFs in Telegram's web interface)
4. Do not pause the GIF

### Expected behavior

Rambox (Telegram) should not prevent computer from sleeping

### Actual behavior

Rambox (Telegram) prevents computer from sleeping.

The output of `pmset -g` is

```
System-wide power settings:
Currently in use:
 standbydelay         10800
 standby              1
 womp                 1
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 powernap             1
 gpuswitch            2
 networkoversleep     0
 disksleep            10
 sleep                1
 autopoweroffdelay    28800
 hibernatemode        3
 autopoweroff         1
 ttyskeepawake        1
 displaysleep         10 (display sleep prevented by Rambox)
 tcpkeepalive         1
 acwake               0
 lidwake              1
```

However when GIF is paused Rambox doesn't prevent the computer from sleeping.
By the way [Franz](https://meetfranz.com/) has the same problem ;)

### ENVIRONMENT

Rambox: 0.5.17
OS: macOS High Sierra 10.13.4

**Comment by svenjacobs** [comment]
Why has this been labelled as wontfix without any explanation? 😐

**Comment by GoOz** [comment]
I don't have Telegram but I believe any app with a running gif will prevent macOS from sleeping.
I myself have the same issue with Tweetdeck, Mastodon and Mattermost.
That's kinda annoying I must admit. :/

**Comment by dpinol** [comment]
is there any workaround?

**Comment by GoOz** [comment]
Besides deactivating auto-loading for gifs in each app (when possible), I don't think so.
