### ISSUE TITLE
can we have customizeable tabs?

### ISSUE THREAD

**Issue by dennyhalim** [ramboxapp/community-edition#1675]
just a matter of preferences.
the tabs is too big for my taste.
give options to set the tabs smaller or even on the sides instead of on the top.
franz5 seem to looks better in appearance.

thanks.

**Comment by reelism** [comment]
Yeah, I could have written the same

**Comment by vraravam** [comment]
Me as well. Franz looks much better where I can configure it to only show the icons without the text.
