### ISSUE TITLE
Blank space surrounding each web app

### ISSUE THREAD

**Issue by peterdalydickson** [ramboxapp/community-edition#1678]
There is now blank space on the right and bottom of all Rambox tabs. It occurred when I changed the zoom of one of the tabs.

<img width="1462" alt="rambox_-_2__rocket_chat" src="https://user-images.githubusercontent.com/17453188/40652048-1af94f48-632f-11e8-97ca-55eed8393771.png">

I've reloaded tabs; stopped and restarted Rambox; reinstalled Rambox... all to no avail.

How do I maximise the web apps inside each Rambox tab?

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> darwin x64 17.5.0

**Comment by muntact** [comment]
This is still a problem in the latest build.

 
![screen shot 2018-10-25 at 9 32 57 am](https://user-images.githubusercontent.com/13400754/47459600-101ef580-d839-11e8-97ef-d61835c0fc8c.png)
