### ISSUE TITLE
Feature request: Ability to sync (backup/restore/check) configuration to the filesystem, not Auth0.

### ISSUE THREAD

**Issue by frankhommers** [ramboxapp/community-edition#1680]
Instead of using Auth0, I would like to save and restore my config to the local filesystem instead of through Auth0.

That way I can save my config wherever I would like. (Dropbox, my own NAS, OneDrive, etc.).

**Comment by heber-junior** [comment]
Wonderful! I use different configs on my work and home. Today i have to login with different account in this places to save different configs.

**Comment by FredyC** [comment]
Would love to see this as well. I mean why such a long way around when filesystem export/import is more straightforward?

**Comment by frankhommers** [comment]
I still want this...

**Comment by FredyC** [comment]
Helloooo....some team response perhaps?

**Comment by maxerbox** [comment]
I will look for it if I implement the partition encryption
