### ISSUE TITLE
Multiple inboxes feature doesn't work in Gmail

### ISSUE THREAD

**Issue by Mossop** [ramboxapp/community-edition#1684]
### Steps to reproduce

1. Log in to Gmail and enable the new Gmail UI
2. Go into advanced settings and turn on multiple inboxes.
3. Save the settings and the page will reload.

### Expected behavior

Multiple inboxes should appear in the inbox and there should be a tab for multiple inboxes in the settings.

### Actual behavior

No multiple inboxes in inbox or settings.

### ENVIRONMENT

Rambox: v0.5.17
OS: Mac OSX 10.13.4
Arch: x64

**Comment by Ash258** [comment]
If you want more inboxes add them as separate service.

**Comment by Mossop** [comment]
You can't really do that, the other inboxes are all part of the same gmail account.

**Comment by iliu** [comment]
+1

**Comment by iliu** [comment]
it looks like this is the culprit:
https://github.com/saenzramiro/rambox/blob/3a4c89bd65c23284640d3f098c0b449f96ab6075/app/store/ServicesList.js#L116

multiple inbox is a labs feature, and your url seems to be `https://mail.google.com/mail/?labs=0` which disables labs. Can we remove the `labs=0` getparams?

**Comment by kingsinger** [comment]
I'm having the same problem with Google Labs being disabled. Is there a way for the user to change the URL for the service? Or do I need to wait for this to be fixed via an update? 

Environment:

Rambox: v0.5.17
Windows 10 (x64)
