### ISSUE TITLE
Download button in Fedora leads to .deb file

### ISSUE THREAD

**Issue by RPDiep** [ramboxapp/community-edition#169]
I'm running Rambox in Fedora 24 and I've got a notice that a new version is available.
The _Download_ button leads to the _.deb_ version.
The _.tar.gz_ or the _.zip_ version would be preferable here.

**Comment by saenzramiro** [comment]
Ok, for now just download from Releases section here in Github.

**Comment by RPDiep** [comment]
Thanks! Already did :smile:

Op di 2 aug. 2016 21:02 schreef Ramiro Saenz <notifications@github.com>:
