### ISSUE TITLE
[SUGGESTION] OWA Support?

### ISSUE THREAD

**Issue by RaydenX93** [ramboxapp/community-edition#1697]
Hi,
I think it would be nice to add support for OWA in Rambox with mail notification, badge update and all the regular features of an email client.

Would it be feasible?

Thanks

**Comment by saenzramiro** [comment]
We already have Outlook 365 in Rambox. Are the notifications and badge don't working?

**Comment by RaydenX93** [comment]
When I try to login via Outlook 365 I get an error while if I login in Rambox via the link my institution provides for web access (https://owa.exchange.mit.edu/owa/) I can login but I don't get notifications and the rest

**Comment by HoLLy-HaCKeR** [comment]
There was a UI update a while ago that broke notifications and the badge. I had to use some custom javascript to get it to work again. Curiously, my college email still uses the older outlook layout, but my personal account doesn't.

```js
function checkUnread() {
    var elem = document.querySelector('i[data-icon-name="Inbox"]+span+span>span');
    var e = elem.innerText.split('\n')[0];
    var t = parseInt(e);
    updateBadge(t);
}

function updateBadge(e) {
    e >= 1 ? document.title = "(" + e + ") " + originalTitle : document.title = originalTitle
}
var originalTitle = document.title;
setInterval(checkUnread, 3000);
```

**Comment by WhittlesJr** [comment]
That code isn't working for me at this point. This guy's code works for calendar notifications but not for emails:

https://github.com/ramboxapp/community-edition/issues/1071#issuecomment-325976188
