### ISSUE TITLE
Login to rambox.auth0.com is broken

### ISSUE THREAD

**Issue by jurgenhaas** [ramboxapp/community-edition#1698]
### Steps to reproduce

1. Clear cache
2. Clear local cache
3. Try to login

### Expected behavior

Should be logged in

### Actual behavior

It shows my profil image and a message "Welcom Jürgen!" follwed by the error message "We're sorry, something went wrong when attempting to login." See this screenshot:

![2018-06-08 09 51 28 screen](https://user-images.githubusercontent.com/1475675/41145808-8cb9b990-6b01-11e8-8343-a380773a42b9.jpg)

### ENVIRONMENT

> Rambox: v0.5.17

> OS: Linux Ubuntu 16.04

> Arch: x64

So, credentials must be correct, otherwise it couldn't find my picture and name. But why does it not login?

**Comment by pzdaniel** [comment]
Same here.

**Already tried**
Fresh installation AND fresh registration at auth0. Tried to change password several times, even to simple ones with only numbers and letters. Still the same error message...

**ENVIRONMENT**
`Version: 0.5.17
Platform: win32 (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1`
`OS: Win10`

**Comment by NielsSt** [comment]
Same error
Did a fresh install on new linux (x64). Did a logout on my old, cant login in there either.
Changed password, but no effect.
Br
**ENVIRONMENT**
Version: 0.5.17
Platform: linux (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

**Comment by jerdog** [comment]
@saenzramiro reach out to us at Auth0 and we can troubleshoot with you what's going on here. Either setup a [support ticket](https://support.auth0.com) or start a topic on [Community](https://community.auth0.com).

**Comment by NielsSt** [comment]
Feedback and close my issue.
Now I understand, if I try to login just with my user.name@xyz.com, it does not work.
But if i use the providers on top e.g. Facebook or Gmail. All works good.
Br

**Comment by jurgenhaas** [comment]
Well, my problem is that my settings are stored in an account with email address and password. If I were to login with one of the other providers I end up in a different account and I won't get access to my settings anymore.

I've just tried to login to auth0.com in the browser with my email address and that doesn't work either. Also the password reset doesn't send me an email. I conclude that my account with my email address doesn't exist anymore - but I'm sure that it's the correct email because it's stored in a vault, so typos are not the issue.

@saenzramiro what can I do to get access to my settings again?

**Comment by jurgenhaas** [comment]
Maybe the Rambox account over at auth0.com is broken? I've just tried this URL (https://rambox.auth0.com/login) and it shows details like the Rambox logo and support email from Rambox, but the message "Something went wrong"

**Comment by haroldogtf** [comment]
I can't login also. Has some workaround?

**Comment by allstarleb** [comment]
??? Has anyone figured a solution to this?

**Comment by saenzramiro** [comment]
I'm investigating this issue. Hopefully I can fix it ASAP.

**Comment by saenzramiro** [comment]
@jerdog Seems like when I turn off "Legacy Lock API" all username-password authentication fails. I turned on again and now works ok, but I know it have to be off because of the deprecation.

I think the solutions will be updating Lock to v11 and Auth0.js to v9 or latest like the documentation said.
https://auth0.com/docs/migrations/guides/legacy-lock-api-deprecation

**Comment by jurgenhaas** [comment]
@saenzramiro I've just tried to login again but it doesn't work. Have you turned it off again?

If it's only about deprecation then it sounds like it's not finally necessary to introduce the change but to prepare for it for some future versions. It would be really good if the system were brought back to a working stage until those questions got resolved.

**Comment by saenzramiro** [comment]
@jurgenhaas I turned on again until we release a new version of Rambox solving the problem by updating the libraries.

**Comment by allstarleb** [comment]
I am getting this error again... it just randomly started when i reformatted my computer at tried to load rambox. Last time it worked randomly after a week or so of my trying to log in. How do you fix this?!

**Comment by SatiricPanda** [comment]
I am also having this problem. I only just started using Rambox this week, but I am migrating to a new computer and want to keep the settings from my old computer. I am trying to log in using a personal domain email that is hosted by G Suite. I've successfully created an account and verified it by email, but I cannot login. I downloaded the application on Monday, so I assume it is the most recent version.

**Comment by edmundlaugasson** [comment]
Also having that problem.... Using 64-bit .deb version 0.5.17 and cannot log in. Even switching to English does not help. Looks like cannot use Rambox anymore as I cannot log in :(
Same happens with AppImage or unpacked version... Tried to renew password - did not help...

**Comment by allstarleb** [comment]
Is anyone going to fix this? @saenzramiro

**Comment by zetneteork** [comment]
Do you have any update for this incident?

**Comment by Tuplad** [comment]
Also have this error, can't login.

If using google or FB, yes, if using my personal account? No. Removed all data and cache (manually), uninstalled app, installed again, still can't log in.

**Comment by allstarleb** [comment]
IS ANYONE GOING TO FIX THIS?

**Comment by Tuplad** [comment]
Or can we fix this ourselves maybe with some piece of the code?

There are accounts to which I'm logged in through Rambox that I only have in Rambox and can't access otherwise (like Telegram for which I have no sim card anymore) etc.

**Comment by zetneteork** [comment]
Is there any update to this issue?

**Comment by allstarleb** [comment]
I stopped using rambox because of this, ridiculous!

**Comment by saenzramiro** [comment]
This will be fixed in the next release coming soon.

**Comment by kmfz07** [comment]
Do we have a solution for this? It seems like this issue has been ongoing and still no response from the devs... This is a bummer. I really wanted to use Rambox. Franz doesn't offer the same number of accounts I can sign in to, but Rambox isn't functional as well. A response would be appreciated.

**Comment by Ash258** [comment]
@kmfz07 You have response right above your comment.

> This will be fixed in the next release coming soon.

Next version will be next week. Release is drafted and all CIs are passing. Just need to be released.
