### ISSUE TITLE
Rambox not working with pen

### ISSUE THREAD

**Issue by Nikkulin3** [ramboxapp/community-edition#1699]
I kind of expected Rambox to function the same with a stylus like pen as with my touch screen, but the only thing I can select is the close/maximise/minimize button. I don't know if this is a bug, a missing feature or simply unavoidable for some reason.

### Expected behavior

Scroll through chats and select items with my stylus like on a touch screen.

### Actual behavior

Can only hover over everything but neither scroll nor select anything.

### ENVIRONMENT

Hardware (stylus): Huion 420 Osu (pen and graphics drawing tablet)

Version: 0.5.17
Platform: win32 (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

**Comment by alien2003** [comment]
There are also some minor issues with touchscreens on Linux
