### ISSUE TITLE
Icon in windows taskbar disappears after pinning the app

### ISSUE THREAD

**Issue by bpetrynski** [ramboxapp/community-edition#170]
When I pin Rambox to the taskbar, it's icon disappears. After unpinning, the icon returns.
_Before_
![image](https://cloud.githubusercontent.com/assets/10245427/17326934/f5ea1db2-58b4-11e6-88ec-fe73c6c8d886.png)

_After_
![image](https://cloud.githubusercontent.com/assets/10245427/17326951/0b2330a6-58b5-11e6-82bf-508f4584db52.png)
## 

> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.10586

**Comment by notnsane** [comment]
Can't confirm, this works as intended in Windows x64 10.0.14393 (anniv update).
I replaced Rambox icon with a custom icon later on, though.

**Comment by saenzramiro** [comment]
@notnsane Yes, for me works on. But in some use cases, I notice this bug. I think is an [electron-builder](https://github.com/electron-userland/electron-builder) bug, but I have to investigate.
