### ISSUE TITLE
Test notification button

### ISSUE THREAD

**Issue by Ash258** [ramboxapp/community-edition#1703]
Would be awesome to have some kind of "Test notification button" in settings.

Now It's mainly for my personal usage during debuging. (Now electron has problem with Windows 10 notifications (`17.134+` version), so i am testing which versions of windows have this problem), also different linux distros / guis use different launcher, which could be problematic too.

Mayber in later versions notifications could be editable for each service (icon, sound, ...) so this would be nice start.

For example Slack has "Show example notification" button inside settings.

**Comment by saenzramiro** [comment]
You mean adding a global "Test notification" or per service?

**Comment by Ash258** [comment]
Global.
