### ISSUE TITLE
Error al momento de instalar

### ISSUE THREAD

**Issue by MauricioAedo** [ramboxapp/community-edition#171]
Adjunto pantallazo que arroja al instalar la nueva versión, lo he probado en 2 PC distintos.
http://i65.tinypic.com/19o3gw.png

Saludos 

## 

> Rambox 0.4.1
> Electron 1.3.1
> win32 ia32 10.0.10586

**Comment by saenzramiro** [comment]
¿Estás usando arquitectura ia32?

Porque si estás usando 64bits, deberías instalar la de 64 bits. Puede que link que te brindó Rambox te haya dirigido a la de 32 bits, pero es porque es un error del servidor de Nuts.

**Comment by MauricioAedo** [comment]
Hola Ramiro

Tienes razón, se me descargó la versión 32 bits en vez de 64. He vuelto a instalar y se soluciona el problema de minimizar al system tray pero igualmente me arrojó este error al finalizar la instalación.

Saludos

**Comment by saenzramiro** [comment]
Ok, por favor corrobora ahora cerrando Rambox y volviendolo a abrir. Porque justo hace unos minutos estaba toqueteando el servidor de Nuts.

**Comment by MauricioAedo** [comment]
El error persiste al iniciar, adjunto imagen:
http://i64.tinypic.com/15qxbnn.png

Saludos

**Comment by MauricioAedo** [comment]
Ramiro, por si te sirve de algo te informo que reinstalé y en el primer inicio me lanzó el error, luego volví a iniciar unas 5 veces y el error persistía, modifiqué algunas opciones de las preferencias y ahora ya no me sale más.

Saludos

**Comment by saenzramiro** [comment]
Ok, voy a investigar a ver que puede estar pasando.

¡Gracias!
