### ISSUE TITLE
Messages offscreen and can't be resized on-screen

### ISSUE THREAD

**Issue by mittenchops** [ramboxapp/community-edition#1710]
Even Ctrl+ and Ctrl-, I can't get the window to resize so I can see the messages in hangouts or telegram.  I hear that they are there, but they are off-screen and resizing just makes them small and off-screen.  How can I force resize-to-window? Actual-size and reload service do not resize.

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> linux x64 4.15.0-22-generic

**Comment by mittenchops** [comment]
![image](https://user-images.githubusercontent.com/1584795/41271672-76bf17b0-6dd7-11e8-8cc1-6332af54251f.png)

**Comment by Ash258** [comment]
Right click on service tab and select **Reset Zoom**
