### ISSUE TITLE
Service Request: Android Messages

### ISSUE THREAD

**Issue by 33Fraise33** [ramboxapp/community-edition#1723]
Google Announced support for android messages on the web.

This would be a nice extra service.

More info: https://messages.android.com/

**Comment by abourdon** [comment]
In the meantime, you can define a new __Custom Service_ that points to https://messages.android.com/.

**Comment by thatgeek95** [comment]
Icon is: https://ssl.gstatic.com/images/branding/product/1x/messenger_96dp.png
