### ISSUE TITLE
Microsoft Teams - unread badge count error

### ISSUE THREAD

**Issue by istrasci** [ramboxapp/community-edition#1731]
I created a new team in Microsoft Teams.  The team name ended in "2018", and somehow Rambox took that value and decided that's how many unread messages I have, and placed "2,018" in the badge counter.  What's worse is that this count will _not go _away_!    Even when I go to the channel of the team, it remains there.  Closing and restarting Rambox did not help either.  I may be forced to delete the team just to get rid of it.

I ran the official Teams for Linux application as well, and that shows everything fine (no unread messages in Teams), so I believe this is a Rambox issue.

![rambox_error](https://user-images.githubusercontent.com/60842/41790418-c8b78c56-760f-11e8-8dc8-45b0d9e73128.png)

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> linux x64 4.13.0-45-generic

**Comment by Ash258** [comment]
MS Teams need proper way of `js_unread` and set `,dont_update_unread_from_title: true`. PR is welcome. (it will also solve #1010 )

**Comment by istrasci** [comment]
Whoops, my mistake.  Should I close this as a duplicate of #1010?

**Comment by Ash258** [comment]
I am not sure how Teams works. This is about Teams and #1010 about chats.

**Comment by dschibster** [comment]
Actually, #1010 only mentions Chats as a reference point, because in Chats the Notifications are reset again. It's also about the Teams tab giving the wrong number of Notifications.
