### ISSUE TITLE
Icon missing from Dock, ubuntu 18.04( rambox 1.5.7 appimage 64 bits)  

### ISSUE THREAD

**Issue by Lvaskz** [ramboxapp/community-edition#1732]
HI, the icon is missing from the ubuntu 18.04 dock, see :
![rambox](https://user-images.githubusercontent.com/29207169/41824666-7c9c6558-77d1-11e8-9a22-c22fcf7dd1e1.png)

**Comment by riprop** [comment]
Hi, 
I confirm, have same on xubuntu 17.10 and 18.04!
BR

**Comment by adidact** [comment]
same here. Ubuntu 18.04

**Comment by Lvaskz** [comment]
Now is working with the last release, at least for me, ubuntu 18.04
