### ISSUE TITLE
window resolution resizing issue

### ISSUE THREAD

**Issue by leenpaws** [ramboxapp/community-edition#1734]
### Steps to reproduce
using laptop with second display, have both displays going at same time
1. pic any service(try Riot)
2. resize 2nd display window(not laptop window) resolution (try going higher than 1920x1080)
3. have second display a different resolution than first

### Expected behavior
rambox resolution will adjust across displays

### Actual behavior
once rambox is on second display the window resizes and never goes back, all windows are now on that size even when that display is disconnected, it's important as that resolutioin is not native laptop resolution

### ENVIRONMENT
64bit ubuntu 16.04

> Rambox: v0.X.X
0.5.17
> OS: XXXX

> Arch: x64 or ia32

**Comment by guikcd** [comment]
Same issue for me with same setup `Ubuntu 16.04.4 LTS` and :

```
Version: 0.5.17
Platform: linux (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

```
