### ISSUE TITLE
I dont get a authentification mail

### ISSUE THREAD

**Issue by Lueh** [ramboxapp/community-edition#1737]
Yesterday I wanted to log in to my Rambox Account which I created at work at a different pc, then there was the message with "PLEASE VERIFY YOUR ACCOUNT BY CLICKING THE LINK WE SENT YOU TO "mymailadress"." - But when I checked my mails I didnt got everything, not even until now I got anything. Now I wanted to log in again at work with a new pc and I got the same problem (I tried it with 2 different accounts to), so theres no dependency to my system/account. 

### Steps to reproduce

1. Log in to your Rambox Account with Email and Password.
2. Wait for the authentification mail until youre dead.

### Expected behavior

Getting a mail to authenticate the use of my account on a new device.

### Actual behavior

Does not get a mail.

### ENVIRONMENT

Not important, because it happend on 2 different devices with 2 different accounts. Must be a problem at your side.

**Comment by Ash258** [comment]
Related to #1698
