### ISSUE TITLE
Buen dia, quiero reportar problema en escuchar audios de whatsapp desde la aplicación, uso Win10, y la app en ningun servicio tiene sonido.

### ISSUE THREAD

**Issue by xjohnyknox** [ramboxapp/community-edition#1739]
-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.17134

**Comment by heber-junior** [comment]
Tengo el mismo problema. Ya he comprobado el sonido del servicio y está habilitado.
El sonido del "Rambox" en el mezclador de windows también está activo.

**Comment by heber-junior** [comment]
I had this problem and I solved reinstalling the application.
I do not know what happened to be without sound.

**Comment by heber-junior** [comment]
I had this problem and I solved it by reinstalling the application.
I do not know what happened to be without sound.
