### ISSUE TITLE
problem with Whatsapp tab from some day

### ISSUE THREAD

**Issue by SiNaPsEr0x** [ramboxapp/community-edition#1756]
### Steps to reproduce
BLANK Page
<img width="255" alt="image" src="https://user-images.githubusercontent.com/5438823/42376779-b63c0bee-8120-11e8-903d-4e01ef012d8d.png">

### ENVIRONMENT

> Rambox: v0.5.17

> OS: MacOS

> Arch: x64

**Comment by ThunderAxe1782** [comment]
i am facing the same problem too .. any ideas?
