### ISSUE TITLE
Unread badge for HipChat messages in rooms with notifications turned off

### ISSUE THREAD

**Issue by jim5359** [ramboxapp/community-edition#176]
In HipChat I have rooms with notifications turned off or set to custom levels where I only receive notifications when my name is mentioned.  Rambox seems to be properly respecting these settings with respect to actual notifications.  However, whenever there is activity in any room, even in rooms where I have notifications turned off, the Rambox icon changes and the HipChat tab shows an unread message count for all messages in all the rooms.  It would be preferred if the icon and message count respected the notification settings and only changed the icon and showed the message count for messages I have set to be notified about.  Otherwise there is no way to know if there are pertinent messages without opening Rambox and going to the HipChat tab.

i.e. Only change the icon and update the message count when an actual notification occurs.

Thanks.

**Comment by justpusher** [comment]
Very important for me, too.

**Comment by justpusher** [comment]
Related issue: #814

**Comment by saenzramiro** [comment]
I will take a look on this in a future release.

**Comment by pjlsergeant** [comment]
This is a deal-breaker for using Hipchat in Rambox for me

**Comment by justpusher** [comment]
I found a workaround for this issue and for issue #814 too. 
Add Hipchat as a custom service and add this custom code: 

```
setInterval(function() {
	var length=$('link[rel=icon]')[0].href.length; 
	var hasNotifications = length !== 1818 && length!==2298;
	var displayedNotifications = document.title.indexOf('(1)') !== -1;
	if (hasNotifications && !displayedNotifications) {
		document.title += "(1)";
		console.log("Added notification");
	}
	if (!hasNotifications && displayedNotifications) {
		document.title = document.title.replace('(1)', '');
		console.log("Removed notification");
	}
}, 500);
```

The idea of workaround is to monitor hipchat favicon and add (1) to the title when the icon changes. 
Currently works perfectly for me.

**Comment by kaspermalfroid** [comment]
This is a deal-breaker for using Hipchat in Rambox for me. I have many muted rooms in HipChat for which I don't want to see notifications.

**Comment by philiplb** [comment]
+1

**Comment by Kianda** [comment]
+1

**Comment by joey-madwire** [comment]
+1 - Huge issue... My company has an open channel with hundreds of messages a day. I only need notifications for other channels. Getting constant notifications for other things is making this pretty much unusable.

**Comment by philiplb** [comment]
Not sure if this is still worth it: HipChat will be turned off in February 2019.

**Comment by Corchoneitor** [comment]
Closing, since HipChat is dead now.
