### ISSUE TITLE
[SECURITY] Please fix your security posture. (.. and don't use rambox until it is fixed)

### ISSUE THREAD

**Issue by menzow** [ramboxapp/community-edition#1765]
After going through the code for #1712 I noticed that rambox employs a handful of worst practices when it comes to webapp security. I was going to dig into them and contact the owner but after seeing someone has already reported the problem in https://github.com/saenzramiro/rambox/issues/1044 it isn't worth the effort.

What it comes down to is that electron apps can be configured to be relatively secure but by default they're basically giving system level access to any javascript embedded within the app.  On top of that rambox goes a step further by lowering the already weak security configuration so that you don't have to write proper access controls.

These lines are the biggest problem: https://github.com/saenzramiro/rambox/blob/3a4c89bd65c23284640d3f098c0b449f96ab6075/electron/main.js#L160-L161 

And:
https://github.com/saenzramiro/rambox/blob/master/app/ux/WebView.js#L177-L178

Even the [electron security tutorial](https://github.com/electron/electron/blob/master/docs/tutorial/security.md) highlight **specifically** that these things should never be done.

> :warning: Under no circumstances should you load and execute remote code with
Node.js integration enabled. Instead, use only local files (packaged together
with your application) to execute Node.js code. To display remote content, use
the [`<webview>`](https://github.com/electron/electron/blob/master/docs/api/webview-tag.md) tag and make sure to disable the `nodeIntegration`

**Comment by menzow** [comment]
To find more information on the impact of the highlighted lines of code and how to securely develop a electron app please refer to the following document: https://github.com/electron/electron/blob/master/docs/tutorial/security.md

**Comment by menzow** [comment]
I see the issue has been assigned so I guess someone will start working on it? Wanted to add that before writing any code attempting to fix the issue work out a plan on what to fix. By using a lax security configuration in favor of rapid development there's been a huge build up of technical debt. Enabling webSecurity and disabling nodeIntegrations means breaking many services and probably stuff you didn't even think would break.

If one or more people are serious about fixing these security issues I'd be happy to take a serious look at the code and provide some more in depth feedback.

**Comment by TheGoddessInari** [comment]
Comments left on this repo have got me encouraged to maintain things working and up to date downstream until this upstream repo is maintained again. I hate JS, but will accept PRs for the time being. Working on getting my local changes fixed and up to date, will focus on it more by Wednesday.
