### ISSUE TITLE
TUTANOTA: LINK NEEDS UPDATING.

### ISSUE THREAD

**Issue by G-i-o** [ramboxapp/community-edition#1766]
Hi. Rambox is currently using an old Tutanota login address, which loads a webapp that doesn't work when 2FA is enabled. The updated app reside at this address: https://mail.tutanota.com/ .This is the address that should be used now to login into Tutanota.
Thank You.

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> linux x64 4.14.48-2-MANJARO

**Comment by saenzramiro** [comment]
Fixed in #1828
