### ISSUE TITLE
Stride: Unable to view preview images.

### ISSUE THREAD

**Issue by oole** [ramboxapp/community-edition#1775]
First off, I love rambox. Lately me and a colleague are stumbling over the issue described below, I hope the report helps.

### Steps to reproduce

1. Use Stride in rambox.
2. Receive an image.
3. Click on it for a bigger preview.

### Expected behavior

The image should show as a preview (bigger than just in chat).

### Actual behavior

The image starts loading, and just keeps loading (Indicated by a loading circle).

### ENVIRONMENT

> Rambox: v0.5.17

> OS: Ubuntu 16.04, Ubuntu 18.04

> Arch: x64

**Comment by alex0520** [comment]
+1 Here 

ENVIRONMENT
Rambox: v0.5.17 (It works on Rambox v0.5.16)

OS: Ubuntu 16.04, Ubuntu 18.04

Arch: x64

**Comment by claystation** [comment]
Had the same problem. Running Fedora 27 x64 with Rambox 0.5.17.
I solved it by going to "Help" -> "Tools" -> "Clear local storage" in Rambox. Be advised, this will clear all configuration and you will have to reconfigure every app. (I didn't have to log in into most of them, but i had to re-add them all)
