### ISSUE TITLE
Ram,box as a black Window

### ISSUE THREAD

**Issue by Thats-me** [ramboxapp/community-edition#1796]
Rambox startet mit einem shwarzen Fenster. Die Menüzeile ist zu sehen.
Rambox starts everytime with a black windows. I can only see the menuline.

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 6.1.7601

**Comment by Ash258** [comment]
Run rambox with disable_gpu flag.
See https://github.com/saenzramiro/rambox/issues/1333#issuecomment-348459605
