### ISSUE TITLE
Hide / Collapse Top bar with services

### ISSUE THREAD

**Issue by MangaD** [ramboxapp/community-edition#1798]
The top bar with the services occupies too much space vertically. Screens usually have more width than height, the bar should be positioned on the left.

It would be nice if this bar also could be toggled! ^^

**Comment by TheGoddessInari** [comment]
I'm not sure what you mean by 'collapse' in this case, but aren't you describing the 'service bar location' preference?

**Comment by MangaD** [comment]
It is also the service bar location preference, but besides that it should be toggable (e.g. a shortcut key or a button to toggle the service bar), so that we can hide it.
