### ISSUE TITLE
Unable to zoom out.

### ISSUE THREAD

**Issue by subodhshtha** [ramboxapp/community-edition#1803]
-
	> Rambox 0.5.17
	> Electron 1.8.4
	> darwin x64 17.7.0

**Comment by kenyesoares** [comment]
I am with the same problema, but nothing works for me.
I reinstall the old release (0.5.16) and it worked, but when i restarted my desktop rambox had updated



-
> Rambox 0.5.17
> Electron 1.8.4

**Comment by Ash258** [comment]
Try this: https://github.com/saenzramiro/rambox/issues/1308#issuecomment-407213251
