### ISSUE TITLE
Steam Chat: No messages counter and new messages indicator on tray icon

### ISSUE THREAD

**Issue by wf-** [ramboxapp/community-edition#1805]
Most likely related to the recent major Steam Chat update.

### ENVIRONMENT

> Rambox: v0.5.17

> OS: Ubuntu MATE 18.04

> Arch: x64

**Comment by saenzramiro** [comment]
Right, they released a new UI that we need to investigate to get the messages.

**Comment by alien2003** [comment]
Still not fixed. Can somebody provide correct JS for new Steam?
