### ISSUE TITLE
Rambox Can't Minimized While It Startup (GNU/Linux)

### ISSUE THREAD

**Issue by jerryshaw12** [ramboxapp/community-edition#1806]
### Steps to reproduce

1. Install Rambox
2. Checked "Start minimized"
3. Reboot
4. Now Rambox launching without minimized

### Expected behavior

Startup wih minimized window

### Actual behavior

Startup with open window

### ENVIRONMENT

> Rambox: v0.5.17

> OS: Manjaro Budgie 17.11

> Arch: x64

**Comment by klocus** [comment]
Same problem on Ubuntu 18.04.
