### ISSUE TITLE
WhatsApp showing \xao code in status bar

### ISSUE THREAD

**Issue by BjoernDaase** [ramboxapp/community-edition#1813]
### Steps to reproduce

1. Set up WhatsApp
2. Make somebody else type while your are observing the status bar

### Expected behavior

You should see "schreibt..." ("schreibt" is german and means writes)

### Actual behavior

You see "schreibt\xao..." (see attached screenshot)

![screenshot from 2018-08-12 22-27-50](https://user-images.githubusercontent.com/24682367/44006196-26ecb9c0-9e80-11e8-9819-e599039e3c2b.png)

### ENVIRONMENT

> Rambox: v0.5.17

> OS: Ubuntu 18.04 

> Arch: x64

**Comment by michl-b** [comment]
In the official WhatsApp App it is all the same. Maybe not a issue of ramboxapp.
