### ISSUE TITLE
[Feature Request] Pulse SMS integration 

### ISSUE THREAD

**Issue by thedonquixotic** [ramboxapp/community-edition#1816]
I know this can be done just using a custom service, since [[Pulse SMS]](https://messenger.klinkerapps.com/overview/) has an online web platform: https://pulsesms.app/

But it still seems like it would be worth including in the default services list etc espc since Pushbullet is already (I actually specifically made the jump from pushbullet to Pulse because of greater reliability, and a better native integration with the phone. )

**Comment by munkymack** [comment]
this is actually available in Rambox Pro as a default service. So I'm sure it will come over to the community edition at some point. But even there, I've haven't been able to figure out how to get badges to work. Not sure if anyone has figured that out yet, but it would be great.

**Comment by thedonquixotic** [comment]
Sounds good! Thanks! I'll go ahead and close this since it's already being worked on in Pro. 

Thanks again for all the great work!
