### ISSUE TITLE
GMail Header is Hidden

### ISSUE THREAD

**Issue by youlogix** [ramboxapp/community-edition#1817]
The top section of GMail is hidden. 
![rambox - saurabh 2018-08-16 10-06-24](https://user-images.githubusercontent.com/9247453/44188629-3ee36600-a13c-11e8-83d1-84cee8a743b5.png)

Ideally, it should show like this 

![daily recap - thursday august 16th - saurabh youlogix com - youlogix infotech pvt ltd mail 2018-08-16 10-08-43](https://user-images.githubusercontent.com/9247453/44188667-74884f00-a13c-11e8-8d90-1325020a6d85.png)

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> darwin x64 17.7.0

**Comment by maaaaadn** [comment]
I have the same issue.
pressing ESC shows the header, very strange to me

Version: 0.5.17
Platform: linux (x64)
Electron: 1.8.4

**Comment by youlogix** [comment]
@maaaaadn Thanks for telling about the ESC trick. It works for me too. Until now, I was refreshing that particular tab to show the header.

**Comment by vraravam** [comment]
If you use the "_Custom Service" service to setup gmail, then the header is shown correctly.

**Comment by maaaaadn** [comment]
> If you use the "_Custom Service" service to setup gmail, then the header is shown correctly.

so there should be an easy fix then?
