### ISSUE TITLE
Android port? 

### ISSUE THREAD

**Issue by Patrik356b** [ramboxapp/community-edition#1820]
Or if anyone knows an android app that already covers irc and discord, that would be perfect.

**Comment by erotavlas85** [comment]
You can take a look at [disa](http://disa.im/).

**Comment by Patrik356b** [comment]
> 
> 
> You can take a look at [disa](http://disa.im/).

Sadly it only supports Telegram at the moment.

**Comment by erotavlas85** [comment]
> > You can take a look at [disa](http://disa.im/).
> 
> Sadly it only supports Telegram at the moment.

Telegram and facebook. In the past, it [also supported whatsapp](https://seaneliasson.github.io/)...

**Comment by Patrik356b** [comment]
Stupid bot.

**Comment by maxerbox** [comment]
Rambox is using the web version of chat apps.
Usually the web versionof chat apps are made for desktop, and not for mobile (it redirect you to the app).

So I guess a port is complicated

**Comment by erotavlas85** [comment]
> Rambox is using the web version of chat apps.
> Usually the web versionof chat apps are made for desktop, and not for mobile (it redirect you to the app).
> 
> So I guess a port is complicated

I do not think that the problem is about desktop and mobile redirecting.
The problem is [missing electron support by android](https://github.com/electron/electron/issues/9162) since [rambox is based on electron](https://electronjs.org/apps/rambox).

**Comment by TheGoddessInari** [comment]
The foundational problem here is more likely that everything depends on push messages to be battery friendly, and Android effectively no longer allows you to be battery unfriendly.
I know web apps can register notification hooks for Android now, but I think that depends on specific support?

See if something like [Hermit](https://play.google.com/store/apps/details?id=com.chimbori.hermitcrab&hl=en_US) can do what you need.

**Comment by Patrik356b** [comment]
That looks interesting. Thanks for the tip

**Comment by erotavlas85** [comment]
@TheGoddessInari thank you for the link it is interesting. There are two missing features really important for me: it is [closed source](https://hermit.chimbori.com/help/source-code) application, the [privacy policy](https://hermit.chimbori.com/terms) declares to use many user data.

**Comment by erotavlas85** [comment]
@TheGoddessInari Android is an [open source project](https://source.android.com) released under apache licence 2.0 (linux kernel is GPL 2.0). I personally use lineage OS custom android that is an open source project together with f-droid.

No, the privacy policy collects many data. Of course, it is better than google privacy policy, but I do not like to share any data without having the possibility to opt out. It is a choice...

**Comment by erotavlas85** [comment]
@TheGoddessInari Android is an [open source project](https://source.android.com) released under apache licence 2.0 (linux kernel is GPL 2.0). I personally use lineage OS custom android that is an open source project together with f-droid.

No, the privacy policy collects many data. Of course, it is better than google privacy policy, but I do not like to share any data without having the possibility to opt out. It is a choice...

P.S.
Moreover, I do not like rambox privacy policy...
