### ISSUE TITLE
No obvious way to enable "Pro" mode.

### ISSUE THREAD

**Issue by JoshKLPA** [ramboxapp/community-edition#1823]
1. Start up Rambox (either Windows or OSX, same issue on both)
2. Receive top-window notification that Rambox Pro is available.
3. Once notification is dismissed, there is no obvious way to switch to Pro mode.

Does switching to Pro mode require a new download? If so, more obvious ways to get it would be appreciated. I suggest adding an unobtrusive button on the home screen, next to the "Follow Us" buttons and with the same visually quiet styling, that says "Try Pro Now" or something similar. 

The large notification that Pro is available needs a call-to-action button as well. As it is, getting a huge "there's a new version of Rambox" notification, one that dominates over half the screen vs. a smaller bar-type notification at the top, with no obvious call-to-action button (e.g. "Try Pro Now", "Get Pro Today", "Download Pro Now") is very frustrating. In addition to a call-to-action button, there _needs_ to be an option to permanently dismiss the notification. For people who don't want to buy pro, they need to not be constantly harassed by intrusive ads for it, or they'll become less loyal to the product.

That said, thank you for making such a great product! Rambox is essential to my daily work, and this is the first nitpick I've had with it after months of heavy use. 

Cheers,

Josh KLPA

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 ia32 10.0.17134

**Comment by heuristicAL** [comment]
Pro mode is a seperate download. You can download the trial [here](https://rambox.pro/#home).

I agree about it being best to not constantly be harassed by pro mode notifications.
