### ISSUE TITLE
Video in MS Teams does not work

### ISSUE THREAD

**Issue by BGMcoder** [ramboxapp/community-edition#1829]
When using Microsoft Teams, there is the option to use video.  But when I click on the video icon, it says, "Video is not supported in your browser"
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 6.1.7601

**Comment by rlees85** [comment]
`https://github.com/ramboxapp/community-edition/blob/master/app/store/ServicesList.js`

Change:

```			,userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.2883.87 Safari/537.36'`
```

to

```
			,userAgent: 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136'
```

Should fix it.... I'd consider a PR but only been using rambox for 5 minutes so haven't had chance to build it yet.

**Comment by brad** [comment]
Thanks @rlees85 I made a PR with your idea in #1916. I tested it, works well for me

**Comment by brad** [comment]
@BGMcoder Until a build is made to fix this, you can fix it yourself by editing Teams configuration, opening the advanced settings, and pasting this:
```javascript
navigator.__defineGetter__('userAgent', function(){
    return 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.2883.87 Safari/537.36 Edge/12.246';
});
```
