### ISSUE TITLE
Custom service does't load/white page

### ISSUE THREAD

**Issue by xidiot** [ramboxapp/community-edition#1830]
### Steps to reproduce

1. Add self-hosted jira as custom service
2. Add the self-signed certificate to your nssdb or mark "Trust invalid authority certificates" option when creating the new custom service
3. Open the new service

### Expected behavior

To load the Jira web interface / login page

### Actual behavior

Only white page is shown. In the status bar "Ready" is shown.

### Logs
In the developer tools/Network when clicking F5:
`"net::ERR_INSECURE_RESPONSE"`

### More info
This web page (Jira) can only be accessed when connected to VPN. It's working on both Firefox and Chromium (Version 67.0.3396.79 (Developer Build) Fedora Project (64-bit)).
 Showing in Chromium/security tab under developer tools:
"The` connection to this site uses TLS 1.0 (an obsolete protocol), ECDHE_RSA with P-256 (a strong key exchange), and AES_256_CBC with HMAC-SHA1 (an obsolete cipher)." -. "This site is missing a valid, trusted certificate (net::ERR_CERT_COMMON_NAME_INVALID)." and "The certificate for this site does not contain a Subject Alternative Name extension containing a domain name or IP address." 

### ENVIRONMENT
Version: 0.5.17
Platform: linux (x64)
Electron: 1.8.4
 OS: Fedora 28

**Comment by mike391** [comment]
See #1880
