### ISSUE TITLE
Enable the Chromium sandbox in the generic webview configuration file

### ISSUE THREAD

**Issue by nvesely** [ramboxapp/community-edition#1831]
Since it looks like all webviews share a generic configuration file, it would be trivial to enable the Chromium sandbox by setting `sandbox: true` in the `webPreferences`. I.e., edit this line: https://github.com/ramboxapp/community-edition/blob/3a4c89bd65c23284640d3f098c0b449f96ab6075/app/ux/WebView.js#L177

This would be especially good for security because you have set `allowRunningInsecureContent=yes` in the default config. I don't know how Electron reacts to HTTP redirects nor if you always put the HTTPS URL in your templates when there is one nor if Electron maintains HSTS pins. A lot of questions I probably won't look into too much because the important thing is that unauthenticated JS will be executed unsandboxed as it is, and so not only are you running authenticated 3rd-party code unsandboxed, but potentially code from a malicious actor.

It seems reasonable to expect that will not cause problems for users because all the services work in Chromium proper. However, there may be complications in the Electron case because who knows, so you'll have to test for sure. For more see the [relevant Electron docs](https://github.com/electron/electron/blob/master/docs/api/sandbox-option.md).

**Comment by TheGoddessInari** [comment]
As already documented in the link provided at the bottom of your post, you have to pass --enable-sandbox to get the actual feature switched on as this isn't something you can trivially enable with code. It also only works in that way. It also requires the main application to **also** be sandboxed and without node integration. Preload can somewhat get around that, but it'd require an entire rework of how the app is designed.

Without that, it just restricts the webview to have no node integration, and only allow communication via IPC. 

These restrictions can be largely enforced without the "soft" sandbox on (although upstream Rambox doesn't try), and don't mean all that much without hard enforcement and context isolation (which has its own set of caveats).

**Comment by nvesely** [comment]
I was thinking they would use the mixed sandbox if the main app would require heavy reworking to make it compatible with the full sandbox:

> To enable OS-enforced sandbox on BrowserWindow or webview process with sandbox:true without causing entire app to be in sandbox, `--enable-mixed-sandbox` command-line argument must be passed to electron. This option is currently only supported on macOS and Windows.
