### ISSUE TITLE
Donate button link is broken

### ISSUE THREAD

**Issue by nvesely** [ramboxapp/community-edition#1832]
1. Click the heart in the top right of the app.

### Expected behavior

I'm taken to a page where I can make a donation.

### Actual behavior

I'm taken to https://fundraiseup.com/widget/FUNSGXPIJWQ/donate?key=KPCFEZKZ, which just says "Not Found."

Version: 0.5.17
Platform: linux (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

**Comment by Ash258** [comment]
Duplicate of #1749

**Comment by Ash258** [comment]
Fixed in #1782
