### ISSUE TITLE
Cannot hear voice notes on Whatsapp

### ISSUE THREAD

**Issue by aalises** [ramboxapp/community-edition#1835]
### Steps to reproduce

1. Open Whatsapp
2. Open a voice note

### Expected behavior

You hear the voice note through your audio output channel

### Actual behavior

You cannot hear the voice note. No error prompts on the console.

### ENVIRONMENT

Rambox: v0.5.17

> OS: Ubuntu 18.04

> Arch: x64

**Comment by sbol-coolblue** [comment]
At the risk of asking the obvious... I've had this situation a couple of times, but in the end traced it to "Do not Disturb" (top left button on the main Rambox tab). That option does not just block notifications, but it'll also block all audio output on all services, thus silencing Voice notes. Did you check whether or not you have DND turned on?

**Comment by aalises** [comment]
@sbol-coolblue Yes! That was it... simple :+1: , I think the don't disturb mode / mute sounds should not block the voice notes, as you are the one intentionally playing them... WDYT?
