### ISSUE TITLE
Vocal message in Messenger (Facebook)

### ISSUE THREAD

**Issue by AlexDep** [ramboxapp/community-edition#1836]
The vocal messages can't be heard into the Messenger app.

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.17134

**Comment by sbol-coolblue** [comment]
https://github.com/ramboxapp/community-edition/issues/1835#issuecomment-419891116 -> Possibly the same issue. Could it be you have Rambox set in Do Not Disturb mode? That mode not only disables notifications, but also stops your services from playing audio (to avoid "new message" ping sounds, I presume).

**Comment by AlexDep** [comment]
The issue has been solved by turning "OFF" the "Do Not Disturb mode". 
Is it an issue because when turning "ON" the "DO Not Distrub mode" it is turning off every sounds from the app ?
