### ISSUE TITLE
seems incompatible with xbindkeys/xdotool

### ISSUE THREAD

**Issue by Celforyon** [ramboxapp/community-edition#1838]
Setup:
- Debian 9.5
- XFCE 4.12
- Rambox 0.5.17
- xbindkeys 1.8.6
- xdotool 3.20160805.1

Expected result:
- `Super+.` inserts \`\`\`

Actual result:
- nothing happens

Details:
When I create a key binding (using `xbindkeys`) (e.g. pressing `Super+.` calls `xdotool getactivewindow key grave grave grave`), it works as expected in every program but Rambox where it simply does nothing.

	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> linux x64 4.9.0-5-amd64

**Comment by Ash258** [comment]
Does it work in other electron apps?? (Discord, Slack, ...)

**Comment by Celforyon** [comment]
I just installed Discord (using .deb from their website).
Indeed, it has the same issue.

So, it seems to be an issue more specifically from electron.
Should I close this issue?

**Comment by Ash258** [comment]
Leave it open until i find some reference to some usage / similar issues.
