### ISSUE TITLE
Screen does not align properly

### ISSUE THREAD

**Issue by andreashhpetersen** [ramboxapp/community-edition#1839]
I installed rambox-bin through yaourt, and most things work as expected. However, the page size within apps does not align with my screen (making it impossible to access stuff in the bottom and to the left of the screen).

Apps tried: Messenger, Slack, Gmail, iCloud Mail

Rambox home/main page looks fine, though.

**Environment:**
	> Rambox 0.5.17
	> Electron 1.8.4
	> linux x64 4.18.4-arch1-1-ARCH

**Comment by Ash258** [comment]
Yaourt is not official package / way to install. Cannot tell if that is not the reason.

**Comment by andreashhpetersen** [comment]
Hm, I see and I wondered that myself. Is there any other preferred way to install on Arch?

**Comment by Ash258** [comment]
Just download one of tons of linux installers from release page and run some deb, pacman, yum, snap or whatever.
