### ISSUE TITLE
Emoji not visible in text inputs

### ISSUE THREAD

**Issue by CBiX** [ramboxapp/community-edition#1840]
### Steps to reproduce

1. Write a message in Gmail or Telegram (didn't have this problem in WhatsApp Web) on Rambox
2. Insert Emoji in the message by either copying from the web (try these: `😅👨‍💻🏡`), [Unicode input](https://en.wikipedia.org/wiki/Unicode_input) or using an extension like the [Emoji Selector for Gnome Shell](https://extensions.gnome.org/extension/1162/emoji-selector/) (color emojis are supported by Gnome Shell >= 2.26
3. Send the message

### Expected behavior

The Emojis are visible in the text input before sending the message.
Firefox:
![emoji-firefox](https://user-images.githubusercontent.com/1295945/44724941-748d3500-aad4-11e8-82f7-7be211a6f914.png)
Chrome:
![emoji-chrome](https://user-images.githubusercontent.com/1295945/44724939-748d3500-aad4-11e8-8358-f462f65f4b0f.png)

### Actual behavior

The Emojis are only visible after sending the message, but not in the text input.
Rambox:
![emoji-rambox](https://user-images.githubusercontent.com/1295945/44724942-748d3500-aad4-11e8-8ca7-17a52ed4e483.png)

With gmail I figured out that the problem also exists in Chrome, so it might just be a Firefox feature of displaying emojis in text inputs correctly ... For me it's quite annoying because from Firefox I'm used to inserting Emojis directly from my keyboard (using the Gnome Shell extension) instead of the Emoji buttons in most web messengers.

### ENVIRONMENT

> Rambox: v0.5.17

> OS: Arch Linux with Gnome 3.28.2

> Arch: x64

**Comment by Ash258** [comment]
Could not reproduced in gmail on Windows 
![Prove](https://i.imgur.com/ttY7kSi.png)

**Comment by CBiX** [comment]
Ok I was able to break down the issue so far and it occurs in all Electron apps + Chrome on my system wherever the font is not explicitly set to an emoji color font existing on the system, see https://jsfiddle.net/o3c7hpjk/3/. I will try playing arount with my fontconfig settings and report back if I get it working.

**Comment by CBiX** [comment]
Solved it with this extra fontconfig:

https://github.com/googlei18n/noto-emoji/issues/36#issuecomment-343655365
