### ISSUE TITLE
Not autenticated on google account

### ISSUE THREAD

**Issue by fredericoallan** [ramboxapp/community-edition#1841]
Not autenticated on google account. after press on google icon, pop-up show off

**Comment by DenBrahe** [comment]
I have the same issue: 

- Version: 0.5.17
- Platform: win32 (x64) --> Windows 10
- Electron: 1.8.4
- Chromium: 59.0.3071.115
- Node: 8.2.1

Steps taken:

1. Open Rambox
2. Click 'Login'
3. Click 'Login with Google'
4. A popup window appears, no content visible
5. After a few seconds, popup window closes

**Comment by DenBrahe** [comment]
Error seems to be about auth0, there's a 400 error: `{"error":"invalid_request","error_description":"Missing id_token or refresh_token parameters"}` as response to the `https://rambox.auth0.com/delegation` call.
Possibly related to #1698 ?
