### ISSUE TITLE
Rambox blocks GNOME Shell power management

### ISSUE THREAD

**Issue by drivera73** [ramboxapp/community-edition#1842]
Rambox inhibits normal GNOME Shell power management support. When Rambox is running, GNOME Shell will not suspend or activate the screensaver at the configured timeouts.  When Rambox is closed, behavior goes back to the expected normal.

Explicit (i.e. manual) suspend still works fine regardless.

Rambox should NOT be inhibiting power management behavior.  This is on Ubuntu Bionic Beaver 18.04 LTS, fully updated.

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> linux x64 4.15.0-33-generic

**Comment by MurzNN** [comment]
What services are enabled in Rambox? I got the same issue when Dropbox Paper service is open in Rambox tab, if I close it - all becomes work well.
