### ISSUE TITLE
NO PUEDO INICIAR SESION

### ISSUE THREAD

**Issue by sjvgapt** [ramboxapp/community-edition#1844]
![sin titulo](https://user-images.githubusercontent.com/876358/44996138-d8e44480-af6b-11e8-9d35-f675faefb4ff.png)

intento iniciar sesión rambox pero me dice que ocurre un problema aunque mi contraseña y usuario estén correctos

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 6.3.9600

**Comment by Ash258** [comment]
Relate #1698 ??

**Comment by saenzramiro** [comment]
Please wait until next version.
