### ISSUE TITLE
Riot freezes when using markdown

### ISSUE THREAD

**Issue by leenpaws** [ramboxapp/community-edition#1845]
in Riot, using ubuntu 16.04, when you try to send a message to the room using "@room:" or a user "@user:" the application freezes, also, hangouts doesn't make or receive calls.

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> linux x64 4.15.0-33-generic

**Comment by danielmotaleite** [comment]
one problem per issue please.
Please rename title to "Riot freezes when using markdown"  as "doesn't work" is way too generic for other to find
