### ISSUE TITLE
Possibility to work with the css

### ISSUE THREAD

**Issue by BGMcoder** [ramboxapp/community-edition#1859]
Is is possible to add a style editor?

Reason I'm asking is that I'm using ICQ.  I have the main window set to about half my 1920p screen, and the chats sidebar in ICQ takes up half the space.  There is no way to close it.  But if I could alter the css, then I could shrink the width of the ICQ's sidebar.  It's about 200px too wide right now.

**Comment by Ash258** [comment]
You could do it via [inject js](https://github.com/ramboxapp/community-edition/wiki/Inject-JavaScript-Code)

Howto: https://www.w3schools.com/js/js_htmldom_css.asp, Google: javascript dom css, ...

**Comment by BGMcoder** [comment]
Okay, how do you get inject js into RamBox?

**Comment by Ash258** [comment]
Just go to rambox tab, click on gear next to your ICQ service, select advanced and paste code there.
