### ISSUE TITLE
Global connectivity detection.

### ISSUE THREAD

**Issue by bascht** [ramboxapp/community-edition#186]
This could be related to #108: It'd be really helpful if Rambox would detect if the services should start to connect. Right now I'm at a conference / hotel with a captive portal that will break SSL connections. If I reconnect to the WiFi or just close or reopen my laptop, I basically have to kill Rambox and restart it. :grin: 

![ramboxpro-offline](https://cloud.githubusercontent.com/assets/51264/17396961/18f9e24c-5a36-11e6-8d9a-d9b92a2eed0f.png)

Might be a minor issue / edge case, but I thought I'd report it nevertheless.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
