### ISSUE TITLE
Gmail preview pane doesn't work

### ISSUE THREAD

**Issue by shanecasey** [ramboxapp/community-edition#1860]
### Steps to reproduce

1.  Go to Gmail Settings > Advanced > Preview Pane 
2. Enable and reload inbox
![screen shot 2018-09-21 at 11 30 32](https://user-images.githubusercontent.com/1871492/45876166-c6eb0a00-bd91-11e8-9b53-a52f3f1387a9.png)

### Expected behavior

This icon should appear between the arrows and the settings icons to allow you to split the inbox with a vertical or horizontal preview pane
![screen shot 2018-09-21 at 11 29 09](https://user-images.githubusercontent.com/1871492/45876137-b2a70d00-bd91-11e8-8f90-fec67f37fb6a.png)

### Actual behavior

Icon doesn't appear. On both "new" Gmail and classic

### ENVIRONMENT

> Rambox: v0.5.17

> OS: macOS 10.13.5

> Arch: x64

**Comment by Mykoplasma** [comment]
I have two Gmail boxes in Rambox: One for work and one for my private Gmail.
My private Gmail works just fine with preview pane, but my work Gmail won't show it. Or it did for a brief moment, but then it disappeared again.

Visiting Gmail with Firefox displays the button for the preview pane, so it shouldn't have anything to do with the settings from the administrator. A colleague using Franz had no problem displaying the button for his work Gmail.

Rambox: v0.5.17
OS: 10.13.6 (had the same experience in latest version of Sierra)
Arch: x64

**Comment by jaklan** [comment]
That's true - "Preview Pane" works when you use your work account, but it doesn't when you use your private account.

**I found a workaround** - add a new Custom Service with "https://mail.google.com/" as an URL and enjoy the Pane :smile:

The default Gmail service in Rambox uses "https://mail.google.com/mail/" link - maybe changing that to the one above would solve that problem?

**Comment by shanecasey** [comment]
> **I found a workaround** - add a new Custom Service with "https://mail.google.com/" as an URL and enjoy the Pane 😄
> 
> The default Gmail service in Rambox uses "https://mail.google.com/mail/" link - maybe changing that to the one above would solve the problem?

That workaround works for me too. Thanks for that! Although it's not related to the "/mail/" on the URL as it works with or without it for me.

> That's true - "Preview Pane" works when I use my work account, but it doesn't when I use my private account.
> 
It's also working on my work email that's on a business account so doesn't seem to be related to work/personal G accounts either

🤔

**Comment by shanecasey** [comment]
Oops, closed by mistake. Reopened as it would be good to still get this fixed properly instead of the workaround @jaklan found
