### ISSUE TITLE
Enable dark mode support for macOS Mojave

### ISSUE THREAD

**Issue by leitmedium** [ramboxapp/community-edition#1870]
The recently released macOS Mojave introduced a new "dark mode" theme that can be enabled by users. Apps need to be updated to support the new mode. Here are some technical details about supporting the dark mode (don't know if suitable for Rambox, though):

https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface

**Comment by kinglouie** [comment]
Its really a shame that dark mode for rambox is a paid feature. I think there is no one willing to pay a monthly fee for getting a consistent dark mode experience on macOS Mojave or the latest windows 10 with dark mode support.
