### ISSUE TITLE
Outlook beta issues

### ISSUE THREAD

**Issue by Apollo-IT** [ramboxapp/community-edition#1871]
### Steps to reproduce

1. When use outlook in Rambox, users can see "Try beta".
2. I used outlook beta by selecting it.
3. But after that, I can't see any notification or badge for unread messages in outlook.

### ENVIRONMENT

> Rambox: v0.5.17 and Ramboxpro v1.0.6

> OS: ubuntu 16.04.3

> Arch: x64

**Comment by K5HV** [comment]
I have same problem with unread counter notifications with Rambox 0.6.1. Downgrade to 0.5.17 fix the issue.

### ENVIRONMENT
> Rambox: 0.6.1
> OS: Arch Linux
> Arch: x64

**Comment by muvor** [comment]
Since this outlook version is now out of beta, I can't switch back and have no notifications whatsoever..

> Rambox: 0.6.2
> OS: Windows 10
> Arch: x64
