### ISSUE TITLE
Not possible to log in to Rambox with email and password

### ISSUE THREAD

**Issue by HappyStinson** [ramboxapp/community-edition#1875]
It is no longer possible to log in to Rambox using email and password.
I have tried with the same email I used when signing up but also just a random string with @ and the result is the same (see image).

![rambox-login-failed](https://user-images.githubusercontent.com/10245351/46474642-adab7a00-c7e3-11e8-83f7-abfd0d9b846b.JPG)

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.17134

**Comment by Ash258** [comment]
https://github.com/ramboxapp/community-edition/issues/1698#issuecomment-418177164
