### ISSUE TITLE
Skype not working

### ISSUE THREAD

**Issue by bladerunner1980** [ramboxapp/community-edition#1876]
When I try to use Skype in Rambox, I have a white screen on the right, and can not see contacts.

	
	-
	> Rambox 0.6.0
	> Electron 2.0.8
	> win32 x64 10.0.17763

**Comment by rauldipeas** [comment]
+1 still doesn't working... :/

**Comment by maikcrew** [comment]
Use Franz messenger is better.

**Comment by rauldipeas** [comment]
> Use Franz messenger is better.

Tudumpish... ¬¬

**Comment by maikcrew** [comment]
You must delete files with setting and set all again. But work good now.
