### ISSUE TITLE
Cannot update to new version

### ISSUE THREAD

**Issue by pacstah** [ramboxapp/community-edition#1878]
### Steps to reproduce

1. Update Rambox 
2. Probably once it wants to start updating, it crashes with an exception popup

### Expected behavior

Updating to newest version

### Actual behavior

An exception popup

### ENVIRONMENT

Version: 0.5.17
Platform: win32 (x64)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

> Rambox: v0.5.17

> OS: Windows 10; Version1803, build 17134.286

> Arch: x64

![afbeelding](https://user-images.githubusercontent.com/20030653/46648762-c971a000-cb96-11e8-9379-6c0065606bcc.png)

**Comment by schousda** [comment]
Same problem here.
Also the downloadable file on the website does not contain an installer.

**Comment by Waize** [comment]
got the exception copied: 
`[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Command failed: 4294967295
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Net.WebException: Der Remoteserver hat einen Fehler zur�ckgegeben: (503) Server nicht verf�gbar.
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   bei System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- Ende der internen Ausnahmestapel�berwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bei System.Threading.Tasks.Task`1.get_Result()
   bei Squirrel.Update.Program.executeCommandLine(String[] args)
   bei Squirrel.Update.Program.main(String[] args)
   bei Squirrel.Update.Program.Main(String[] args)
---> (Interne Ausnahme #0) System.Net.WebException: Der Remoteserver hat einen Fehler zur�ckgegeben: (503) Server nicht verf�gbar.
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   bei System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.`

**Comment by Ash258** [comment]
@saenzramiro  You probably forgot to update heroku download links for new NSIS installer.

**Comment by schousda** [comment]
After a restart Rambox showed me the manual update to 0.6.0 now.
I changed the URL to directly go to 0.6.1 which could be found here:
https://github.com/ramboxapp/community-edition/releases/tag/0.6.1

Some of my accounts asked for a login after the update. Also the Rambox settings got lost.

**Comment by saenzramiro** [comment]
Sorry guys, the error is related with our Heroku instance that we are removing soon because now we use GitHub Releases server for auto-updates.

I fixed the error so now you shouldn't see it. To update to 0.6.0 or 0.6.1, you have to do it manually in all platforms because of the new technologies we implemented.

Downloading executables files from our website is also fixed.

Thank you for your patience!

**Comment by pacstah** [comment]
![afbeelding](https://user-images.githubusercontent.com/20030653/46716547-c0e79b00-cc64-11e8-98a6-5741f531e7bd.png)
