### ISSUE TITLE
After upgrading to 0.6.1 gets an alert to upgrade to 0.6.0!! 

### ISSUE THREAD

**Issue by krambock** [ramboxapp/community-edition#1883]
### Steps to reproduce

1. Open Rambox
2. Shows a msg stating that 0.6.0 is out! to download and install..
3. 

### Expected behavior
Show the msg about a new version when it's a newer version, not an older (0.6.0) 

### ENVIRONMENT

	> Rambox 0.6.1
	> Electron 2.0.8
	> linux x64 3.10.0-862.14.4.el7.x86_64
![seleccion_106](https://user-images.githubusercontent.com/18543383/46697337-090dab80-cbda-11e8-9b93-242f2a08ea5a.jpg)

**Comment by schuettecarsten** [comment]
Same here. Very annyoing.

**Comment by nocibambi** [comment]
It is perhaps the same issue for me: I am on Ubuntu 18.04 and just did an update but it also kept the previous version so now I have two.
![Two versions](https://ibin.co/4Ib8tdcbCqBU.png)

The original produces the update warning, the other does not.

**Comment by saenzramiro** [comment]
We removed the message, so now you haven't to see it anymore.
