### ISSUE TITLE
Outlook 365 doesn´t work!

### ISSUE THREAD

**Issue by manuegzl** [ramboxapp/community-edition#1885]
**Outlook 365 doesn´t work!**
	

	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> win32 x64 10.0.17763

**Comment by Ash258** [comment]
....

What is "doesn't work". What does it look like?? No screenshot?? Anything?

**Comment by manuegzl** [comment]
When I say that it does not work, it is that absolutely nothing works. It does not make sense to take a screenshot of something blank, with nothing. It does not go, nothing works. @Ash258 
![captura de pantalla 2 _li](https://user-images.githubusercontent.com/32573079/46757101-71878600-ccc9-11e8-8a2a-f72cfca2e211.jpg)
![captura de pantalla 1 _li](https://user-images.githubusercontent.com/32573079/46757150-95e36280-ccc9-11e8-8899-6ca7afb2c253.jpg)

**Comment by saenzramiro** [comment]
@manuegzl Did you read the note we added when you are trying to add Outlook 365? Seems like the answer is NO.

You need to add `com` or `de` for example.

**Comment by manuegzl** [comment]
Yes, if I read the note when I tried to access my account. But this is putting my mail and adding mail, I did not know what it was to simply add that and then access, sorry for the inconvenience caused. Thank you


> @manuegzl Did you read the note we added when you are trying to add Outlook 365? Seems like the answer is NO.
> 
> You need to add `com` or `de` for example.
