### ISSUE TITLE
tabs not open for any services/ mini size for newly added services

### ISSUE THREAD

**Issue by polrus** [ramboxapp/community-edition#1887]
after upgrading from 5.0.17 to 0.6.1 it is unusable
first none of the services that I had configured in 5.x was displayed, after restart it was listed in the list of services but cannot open any tabs.
I tried adding any  new service just to see that the window is 5% of the available space so not enough space to even navigate bassic service buttons.

	
	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> linux x64 4.12.14-lp150.12.16-default

**Comment by davidrei** [comment]
I'm experiencing the same issue on the Mac version.
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/1062251/46784236-931a5900-cd2d-11e8-82dc-02bef59649d1.png">

**Comment by kozliatko** [comment]
The same situation on Linux Mint :( 
kernel 4.15.0-34-generic #37~16.04.1-Ubuntu SMP
rambox: Rambox-0.6.1-linux-amd64.deb

**Comment by polrus** [comment]
still the same in 0.6.2
