### ISSUE TITLE
settings not being saved

### ISSUE THREAD

**Issue by polrus** [ramboxapp/community-edition#1889]
i tried to see if disabling hardware acceleration can help with the issues reported previously - but cannot make this settig persistant. I check the box "disable hardware acceleration' but when I restart rambox it is still unchecked.

	
	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> linux x64 4.12.14-lp150.12.16-default

**Comment by saenzramiro** [comment]
Please upgrade to version 0.6.2 and check if there works ok.

**Comment by polrus** [comment]
no it does not - but now I know what is the problem
theres no Cancel Save buttons at all
![obraz](https://user-images.githubusercontent.com/9408405/47387263-19ac3e80-d70f-11e8-885c-068234db5270.png)
