### ISSUE TITLE
Skype not opening images in 0.6.1

### ISSUE THREAD

**Issue by Ludo444** [ramboxapp/community-edition#1891]
### Steps to reproduce

1. Try to open image send over Skype
2. See JS error

### Expected behavior

Should download image to /tmp folder and open it in default system image viewer

### Actual behavior

![screenshot_20181010_162729](https://user-images.githubusercontent.com/7080959/46739665-c1565500-cca9-11e8-827a-25f4852fef65.png)

### ENVIRONMENT

> Rambox: v0.6.1

> OS: Ubuntu 18.04

> Arch: x64

**Comment by roland-d** [comment]
Just for the record, the same happens on Windows 10

**Comment by PauloGDPeixoto** [comment]
Issue still happening in 0.6.2.

**Comment by nzeppos** [comment]
Yes, replicated every single time in Ubuntu 18.04 running Rambox 0.6.2.

**Comment by Actiune** [comment]
Same here, been going on for the last ~2 updates.

    Rambox: v0.6.2

    OS: Win 10

    Arch: x64

**Comment by Digioso** [comment]
I've got the same issue.
	> Rambox 0.6.2
	> Electron 2.0.8
	> win32 x64 10.0.17134

![grafik](https://user-images.githubusercontent.com/10660450/48470404-a2d80200-e7f1-11e8-9c95-883c709ed890.png)

**Comment by matrevis** [comment]
Same issue in os x mojave with rambox 0.6.2.

**Comment by nzeppos** [comment]
Stale or not, the issue needs to be solved somehow as it's still there affecting all users.

**Comment by Emkej** [comment]
got the same problem
