### ISSUE TITLE
Whatsapp is really slow

### ISSUE THREAD

**Issue by achavazza** [ramboxapp/community-edition#1895]
After last update, Whatsapp app is really slower than previous update (typing, and every interaction) (Memory leak?)

	
	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> win32 x64 10.0.17763

**Comment by shawandpartners** [comment]
Ditto

**Comment by achavazza** [comment]
seems to be the lastest estable version of electron is v3.0.4, isnt?

**Comment by yafp** [comment]
@achavazza 
regarding Electron versions: right now 3.0.5 seems to be latest.
Reference for that topic might be #1909

**Comment by saenzramiro** [comment]
Switching to a major version of Electron is a huge step. We have to test all features, consumptions, etc. Because of that, we need to confirm that this problem is related to Electron.
