### ISSUE TITLE
No notification on facebook messenger since update 0.6.1

### ISSUE THREAD

**Issue by nikoslyk2093** [ramboxapp/community-edition#1897]
Since update 0.6.1 on facebook messenger i no longer have notifications on the app icon when i have a new message.

	
	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> win32 x64 10.0.17134

**Comment by saenzramiro** [comment]
Are you not seeing the red badge icon? Or are you talking about the desktop notification?

Both are working ok, remember that you have to enable desktop notifications inside Messenger by going to Messenger settings.
