### ISSUE TITLE
Services are not loaded without sudo on Ubuntu

### ISSUE THREAD

**Issue by ZZaphod** [ramboxapp/community-edition#1900]
After the recent update to v0.6.1, Rambox won't load my saved services and new added services are gone after restarting the app. It worked finde prior the update.
When I add a service that was previously configured the login etc is still working. The entries in ".config/Rambox/Partitions" for the previous saved services are still there as well.

### Expected behavior

Services are loaded and can be saved without superuser rights

### Actual behavior

I need superuser rights so load and save services

### ENVIRONMENT

> Rambox: v0.6.1

> OS: Ubuntu 18.04

> Arch: x64

**Comment by saenzramiro** [comment]
I think this is related with the way you installed Rambox CE.

Can you please reinstall it from scratch? Be sure to make a clean uninstall first.
