### ISSUE TITLE
[Suggestion] Portable Apps Version

### ISSUE THREAD

**Issue by acnickho** [ramboxapp/community-edition#1901]
Is there any plans to have a version that runs as a portable app?
i would love to be able to run Rambox from a USB and not have to worry about entering passwords to 10 accounts every time I am on a different PC

Apologies if there already is a working version, but the one community version I did find, had a lot of issues running.

**Comment by alexdevero** [comment]
Take a look at [releases page](https://github.com/ramboxapp/community-edition/releases). There are zip archives with portable version.
