### ISSUE TITLE
No notifications since 0.6.1 (Outlook 365)

### ISSUE THREAD

**Issue by tanay-bits** [ramboxapp/community-edition#1902]
### Steps to reproduce

1. Update to Rambox v0.6.1
2. Set up Outlook 365 account
3. Get new emails on this account

### Expected behavior

Notifications (pop-up and the ram icon turning red) upon receipt of new email on Outlook 365.

### Actual behavior

No notifications (neither pop-up nor the ram icon turning red) upon receipt of new email on Outlook 365.

### ENVIRONMENT

> Rambox: v0.6.1

> OS: Ubuntu 14.04

> Arch: x64

**Comment by saenzramiro** [comment]
Please upgrade to version 0.6.2 and check if there works ok.
