### ISSUE TITLE
Backup still doesn't work with 0.6.1

### ISSUE THREAD

**Issue by jurgenhaas** [ramboxapp/community-edition#1905]
Before updating to this version, login didn't work in the first place, now that's fixed. But I still can't backup. Restoring the latest backup did work after I logged out and then logged in again. But backup just reports an error without further detail.

	
	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> linux x64 4.4.0-137-generic

**Comment by Ash258** [comment]
#1036

**Comment by jurgenhaas** [comment]
@Ash258 this is not the same bug. The behaviour described in #1036 is what I saw before I logged out. But after I logged out and logged in again, the backup finishes with a message that there has been an error. But no further details. The other issues describes a popup that never finishes. But that's different. Would you mind re-opening this one?

**Comment by saenzramiro** [comment]
Sorry @jurgenhaas, we are not only interested in Pro users.

What @Ash258 should have explained is that ticket #1036 at some point is related to this one. Let's merge this to that ticket so we can continue there. I will be fixing this in next version.
