### ISSUE TITLE
JavaScript error occurred in the main process when dragging on Windows

### ISSUE THREAD

**Issue by RichSteele** [ramboxapp/community-edition#1906]
### Steps to reproduce

1. Drag the open Rambox window to reposition or resize

### Expected behavior

Window is in new position or with new size without an error.

### Actual behavior

An error dialog box appears:

A JavaScript error occurred in the main process

Uncaught exception:
Error: EPERM: operation not permitted, rename
'C:\Users\rsteele\AppData\Roaming\Rambox\config.json.1872916219' -> 'C:\Users\rsteele\AppData\Roaming\Rambox\config.json' at Object.fs.renameSync (fs.js:766:18) at Function.writeFileSync [as sync] (C:\Program Files\Rambox\resources\app.asar\node_modules\write-file-atomic\index.js:192:8) at ElectronStore.set store [as store] (C:\Program Files\Rambox\resources\app.asar\node_modules\conf\index.js:164:19) at ElectronStore.set (C:\Program
Files\Rambox\resources\app.asar\node_modules\conf\index.js:78:14) at BrowserWindow.<anonymous> (C:\Program Files\Rambox\resources\app.asar\electron\main.js:160:76) at emitOne (events.js:116:13) at BrowserWindow.emit (events.js:211:7)

### ENVIRONMENT

> Rambox: v0.6.1

> OS: Windows 10 version 1607

> Arch: x64

**Comment by EinPinsel** [comment]
Having the same issue, but interestingly if you run Rambox as Administrator (which should not be required at all!) the error does not occur on the first move. But to be honest I'm not sure how  to document this. 
It occurs after at least one move, then for several moves it doesn't (maybe it tries to save the position every X seconds?), then it occurs again.

**Comment by RichSteele** [comment]
I tried running as admin but that didn't seem to help. I checked the file's permission but don't see anything obviously wrong.

Question, did you upgrade?

**Comment by RichSteele** [comment]
Actually it does help: resizing the window doesn't cause errors when running as admin, but moving the window still does.

**Comment by EinPinsel** [comment]
Yeah, I did upgrade from 0.6.0 to 0.6.1, as the updater suggested.

**Comment by EinPinsel** [comment]
> ### ENVIRONMENT
> > Rambox: v0.6.2
> 
> > OS: Windows 10 version 1607
> 
> > Arch: x64

Still applicable for 0.6.2

**Comment by RichSteele** [comment]
Same here. I tried uninstalling and reinstalling clean, including making sure the directory in which the config.json is stored was deleted, but still running into the problem with 0.6.2. I'm actually ditching for now until this is resolved.
