### ISSUE TITLE
Upgrade Electron

### ISSUE THREAD

**Issue by vraravam** [ramboxapp/community-edition#1909]
### Steps to reproduce

1. 
2. 
3. 

### Actual behavior

Electron version is 2.0.8 - while the latest released version is 3.x. Please upgrade so that security-related issues are closed.

### ENVIRONMENT

> Rambox: v0.X.X
0.6.1

> OS: XXXX
MacOS 10.13.6
> Arch: x64 or ia32
x86

**Comment by saenzramiro** [comment]
We will do this in a future release once we tested all features works as expected. 👍

**Comment by vraravam** [comment]
@saenzramiro - i agree that upgrading electron by major versions is something of a huge step - but, we can keep this issue open as a meta one - and upgrade the minor/tiny version numbers. For eg, 2.0.8 to 2.0.12 (for which I have submitted a PR) could be done immediately.
