### ISSUE TITLE
After upgrading from 0.5.x to 0.6.1, all preferences and services are lost

### ISSUE THREAD

**Issue by localhorst** [ramboxapp/community-edition#1910]
### Steps to reproduce
1. Have Rambox 0.5.x installed (I guess my version was 0.5.17) 
2. Upgrade to 0.6.1 via Release download page (Windows Installer) https://github.com/ramboxapp/community-edition/releases
3. Result: Services are gone, preferences are set to default. 

### Expected behavior
Rambox should keep preferences and services after upgrading

### Actual behavior
After installation, Rambox starts without any services and with default preferences.

	
	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> win32 x64 10.0.17134

**Comment by Futhark** [comment]
In fact, there is Partition folder with all data still in place but the app itself is not using that data, everything is like after fresh install

**Comment by franmartosr** [comment]
Same for me, when I launch Rambox looks like a fresh install. Even if I add all the services again all is lost after I restart rambox.

**Comment by andreihavri90** [comment]
I get the same behaviour. The Rambox Partitions folder is still there and everything looks into place, but when I start Rambox, the service list is empty.
