### ISSUE TITLE
Right side of GMail windows cut off

### ISSUE THREAD

**Issue by BaronMind** [ramboxapp/community-edition#1914]
After zooming out on a few GMail windows, the right side of the screen became obscured/cut off in all of my active windows. I can't see the right 1/8th of any window. I've tried reloading Rambox and resetting zoom. Neither works.

![screen shot 2018-10-17 at 4 37 16 pm](https://user-images.githubusercontent.com/21083413/47166136-7a7be700-d2c9-11e8-9e97-53654eb8a261.png)

	
	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> darwin x64 18.0.0

**Comment by Ash258** [comment]
Try this: https://github.com/ramboxapp/community-edition/issues/1308#issuecomment-407213251
