### ISSUE TITLE
Missing indication of the number of messages

### ISSUE THREAD

**Issue by AlexKarel** [ramboxapp/community-edition#1917]
Good afternoon. Sorry to bother you. After the last update disappeared at the top of the numbers indicating the number of messages. The message is, and its designation at the top there. Please suggest a solution to the problem. Thank you!
![rambox](https://user-images.githubusercontent.com/17789731/47203788-10774680-d38a-11e8-8582-433b51b7acbb.jpg)

	
	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> win32 x64 10.0.17134

**Comment by Ash258** [comment]
Should be fixed in 770a8412fb7d3f14632643ade7bc832475fc7506.

**Comment by AlexKarel** [comment]
Jakub Čábera. 
Dobré odpoledne Promiňte, nerozuměl jsem, co znamená vaše zpráva. Mohu jen řečeno slovy - je to chyba nebo mám do programu zahrnout něco? Děkuji!

Good day. Sorry, I did not understand what your message means. Can I just say in words - is it a bug or should I include something inside the program? Thank!

**Comment by Ash258** [comment]
To znamená, že už to bylo opraveno a oprava bude zahrnutá v další verzi.

**Comment by AlexKarel** [comment]
Díky!
