### ISSUE TITLE
Splitscreen mode (apps side-by-side)

### ISSUE THREAD

**Issue by FunkMonkey** [ramboxapp/community-edition#1920]
This is a feature request, so I left out the bug report template. Hope that's ok.

It would be nice if rambox had a splitscreen-feature so apps/services can be viewed side by side. This way more screenspace could be used on ultra-wide-monitors. Also it would be great for apps that don't use much width (like messengers).

Thanks!

**Comment by PauloGDPeixoto** [comment]
This is a duplicate of #879
