### ISSUE TITLE
Latest version doesn't play well with mouse scroll wheel

### ISSUE THREAD

**Issue by unkinected** [ramboxapp/community-edition#1924]
Just scrolling with a standard mouse wheel anywhere in the app. This used to work in the previous version, though sometimes required you to click into specific boxes. Now, I can't get the scroll wheel to work at all. I have to explicitly grab the scroll bar and drag that. Testing with Microsoft Teams and Slack plugins.

	
	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> win32 x64 10.0.17763

**Comment by sxmanton** [comment]
I'm also experiencing the same issue on 0.6.2
