### ISSUE TITLE
automatic update via "relaunch now" button not working

### ISSUE THREAD

**Issue by leitmedium** [ramboxapp/community-edition#1926]
### Steps to reproduce

1. Click on "Download" besides "New version is available (0.6.2)
2. Wait until new banner appears
3. Click "Relaunch Now" besides "New version ready to install (0.6.2)"

![image](https://user-images.githubusercontent.com/305663/47482309-7d7d5700-d836-11e8-84ec-49dd5d9a88ed.png)

### Expected behavior

Relaunch Rambox and run new version 0.6.2

### Actual behavior

Rambox is going to background (visually). You need to click on it's icon in the tab bar or similar, to get it back, it is still running 0.6.1, still showing "New version is available" and "New version ready to install (0.6.2)"

### Fix for me

Quitting the app and starting it again brought up Rambox 0.6.2 as expected. 

### Remarks

It would be nice, if the "Download" banner disappears, when Rambox asks for a relaunch as it already has been downloaded then and the first banner is not needed anymore and might lead to confusion.

### ENVIRONMENT

Rambox: v0.6.1
OS: 10.14
Arch: x64

**Comment by saenzramiro** [comment]
Yes, we have to improve this behavior.

**Comment by saenzramiro** [comment]
Fixed in 0.6.7, but we need to hide the "Download" button because is always downloading in the background and the user don't have to download it manually. Will change this in next version.

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
