### ISSUE TITLE
Problem with Skype pics ! Rambox 0.6.2

### ISSUE THREAD

**Issue by monadah** [ramboxapp/community-edition#1928]
Hi, I have problems to open pictures that I send or receive on Skype chat.

Steps:

1. First send an image
2. try to open 
![image](https://user-images.githubusercontent.com/44467169/47497535-c500e480-d830-11e8-8921-b40f0f62e567.png)

3. this error appears (Image)
![image](https://user-images.githubusercontent.com/44467169/47497398-53289b00-d830-11e8-8c8b-a56313104e01.png)

3 or 2 updates before, this works opened the image with de Windows viewer.

	
	-
	> Rambox 0.6.2
	> Electron 2.0.8
	> win32 x64 10.0.17134

**Comment by larsmagnusherland** [comment]
Also happens on Linux
![image](https://user-images.githubusercontent.com/16826379/47515725-e7701d80-d883-11e8-8445-d6127e26c776.png)

But I manage to save the image after clicking the OK button.
After having this box, Rambox GUI breaks, so can't use help menu or other elements.

![image](https://user-images.githubusercontent.com/16826379/47515814-1b4b4300-d884-11e8-8078-52bf65a57418.png)

**Comment by jonaspm** [comment]
I confirm the issue. It happens to me also in GNU/Linux (Devuan)

**Comment by dmknght** [comment]
Confirmed same problem, Linux (Debian 10 amd64)

**Comment by cnotv** [comment]
+1 Ubuntu 18.04 64-bit
