### ISSUE TITLE
Add delay on startup

### ISSUE THREAD

**Issue by racuna** [ramboxapp/community-edition#1929]
### Steps to reproduce

1. On boot, some networks are slow to autenthicate my PC, or sometimes I have to config certain IP, DNS, gateway, etc
2. When that happens, Rambox sends an alert "Not connected to Internet"
3. After the PC is connected to internet, some services on Rambox have to be reloaded.

### Expected behavior

Add the option to enable some delay on the startup: 15, 30, or 60 seconds, then try to connect Rambox to Internet

### Actual behavior

Writed above. I know is normal behavior, and it is not an error. I only have the issue when I started to work with my laptopt in different network scenarios.

### ENVIRONMENT

> Rambox: v0.6.2
> OS: Windows 10 - win32 (x64)
> Arch: x64

**Comment by async-cdn** [comment]
You can do this yourself by creating a task that runs upon logon with a delayed start. I have the same issue and have had to do this with a few apps.

**Comment by async-cdn** [comment]
You can use Task Scheduler.

Create a task with a trigger that begins the task at log on.

In the advanced settings you can specify a delay.

![image](https://user-images.githubusercontent.com/44554070/47666354-3e833480-db9b-11e8-914b-4a12afd52f70.png)

**Comment by racuna** [comment]
Awesome! thanks!
