### ISSUE TITLE
rambox: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by markuslam** [ramboxapp/community-edition#1937]
### Steps to reproduce

1. Install rambox
2. 
3. 

### Expected behavior

Execute rambox
### Actual behavior

error message 
rambox: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
The command ls -la /usr/lib/x86_64-linux-gnu | grep libgconf shows libconf:
lrwxrwxrwx   1 root root       19 Jun  8  2017 libgconf-2.so.4 -> libgconf-2.so.4.1.5
-rw-r--r--   1 root root   192360 Jun  8  2017 libgconf-2.so.4.1.5

### ENVIRONMENT

> Rambox: v0.6.2

> OS: Ubuntu 

Thanks a lot for your help!

**Comment by asummers** [comment]
I am having this issue as well on Arch with Rambox installed from AUR.

**Comment by asummers** [comment]
The Arch install script succeeds but errors during the install with:

```
==> Checking runtime dependencies...
error: could not open file /var/lib/pacman/local/gconf-3.2.6+11+g07808097-4/desc: No such file or directory
```

Doing an `ls /var/lib/pacman/local/gconf-3.2.6+11+g07808097-4` yields: 

```
install
mtree
```

Unsure what the significance of the `desc` is there, but that file/dir does not exist.

Also unsure if this is an Electron issue further upstream, but cursory Googling suggests it may be. Seems Chrome dropped gconf as a dependency or something along those lines? But even having that package (gconf), the Rambox install is failing. Other packages on my computer including Spotify are also dependents on the gconf package, and are working properly, seemingly.

**Comment by qdelettre** [comment]
I'm having the same issue on xubuntustable (galliumos). Installing libgconf change nothing.

**Comment by adunna** [comment]
@markuslam Did you install the amd64 version or the i386 version of Rambox? Your listed lib is contained in the 64 directory, so that could be the issue.

**Comment by asummers** [comment]
@adunna For my purposes, it was working and then updating packages via package manager broke it. If the 64 v 32 bit is an issue, that is the result of an error outside user control.

**Comment by asummers** [comment]
Last I checked this is still broken. I stopped using Rambox entirely because I can't get it to launch on a fresh OS install due to the bug in the issue.
