### ISSUE TITLE
Notification Counter missing in Zoho Mail

### ISSUE THREAD

**Issue by jmejia32** [ramboxapp/community-edition#1946]
### Steps to reproduce

1. Go to Zoho Mail Tab
2. Go to Inbox folder in Zoho Mail

### Expected behavior

Notification Badge counter in red with unread messages over Zoho Mail Icon

### Actual behavior

Notification badge missing

### ENVIRONMENT

> Rambox: v0.6.2

> OS: Antergos 18.10 (Arch Linux based)

> Arch: x64
![image](https://user-images.githubusercontent.com/15973840/47802548-8078bb80-dcfe-11e8-8c87-bc48effdee7f.png)

**Comment by marcolussetti** [comment]
Wanted to note that this issue is still present in Rambox 0.6.3 (win64).
