### ISSUE TITLE
Is it possible to remove/disable the Rambox "Settings" tab?

### ISSUE THREAD

**Issue by leoheck** [ramboxapp/community-edition#1950]
Is it possible to remove/disable the Rambox "Settings" tab?

I use `Ctrl+Tab` a lot to switch between the clients, and this unnecessary tab adds one step more in this list.

![image](https://user-images.githubusercontent.com/1277920/47868899-38cc5f80-dde4-11e8-8276-72a5c9abfb6c.png)

**Comment by leoheck** [comment]
Ping.

**Comment by leoheck** [comment]
Wait!

**Comment by maxerbox** [comment]
Yup

**Comment by ambush** [comment]
How can I do that?
