### ISSUE TITLE
Can't backup new configuration

### ISSUE THREAD

**Issue by My-Name-Is-Adam** [ramboxapp/community-edition#1956]
Restored previous backup to new install of Rambox on fresh Windows 10 install.
Made some changes such as removing some services and adding some more.
Upon trying to backup the changes it tells me:
"Error occurred when trying to backup your configuration"

I've restarted Rambox but get the same error. 

	
	-
	> Rambox 0.6.2
	> Electron 2.0.8
	> win32 x64 10.0.16299

**Comment by MichaelDwucet** [comment]
Same problem on two clients.

**Comment by sebastienserre** [comment]
Nope nop the bot! Do not close, we can't backup!

**Comment by My-Name-Is-Adam** [comment]
Don't bother with Rambox.. Developer has abandoned it for the paid version. 

Use Wavebox. Been using this for a while and it is so much better than Rambox. Even made a few suggestions on Github and they implemented them in the next release. 

Lots of big names use them such as Shopify, Spotify, Adobe, and Microsoft to name just a few. (at least according to the website)

https://wavebox.io

Check it out and let me know what you think :)

**Comment by sebastienserre** [comment]
@My-Name-Is-Adam Seems great but not free....

**Comment by drjlm** [comment]
Not able to backup too. To make that worse, Rambox keeps logging itself out. So I need to manually recreate all my services about once a month. Major inconvenience. I'm running Lubuntu 18.04.

**Comment by Rik67** [comment]
Same for me, backup doesn't work.
