### ISSUE TITLE
Not working on Ubuntu 16.04 after upgrade to 0.6.2

### ISSUE THREAD

**Issue by manjusr81** [ramboxapp/community-edition#1960]
### Steps to reproduce

1. Simply hangs cant see anything
2. Ubuntu os
![selection_339](https://user-images.githubusercontent.com/9315238/48127568-0f12ad00-e2aa-11e8-8d9f-7663fe5c079a.png)

3. 

### Actual behavior

> Rambox: v0.6.2
> OS: ubuntu 16.04

> Arch: x64 or ia32

**Comment by yafp** [comment]
Please upgrade to 0.6.3 and try it again.

If it still fails, start Rambox and enable Developer tools via menu and switch to the console tab. Check if it lists some errors.
