### ISSUE TITLE
Need support for windows 10 Dark Mode. (Colored Titlebars like Office 2016)

### ISSUE THREAD

**Issue by yurividal** [ramboxapp/community-edition#1968]
Rambox could implement client-side decorations to suport new Windows 10 Dark Mode for app windows. This would make the top bar of Rambox become black (or dark) according to windows 10 light/dark mode selected by the user.

![annotation 2018-11-15 200738 jpg](https://user-images.githubusercontent.com/8555749/48585182-fc841d80-e912-11e8-9010-fa16e8cbf126.png)
 (Please see screenshots).

**Comment by Wursthandschuh** [comment]
you can modify the ressources/Rambox-all.css in the app.asar
![image](https://user-images.githubusercontent.com/32794633/49032844-ea756b00-f1ad-11e8-8863-d1cca0052633.png)

**Comment by yurividal** [comment]
@Hauwertlhaufn how did you do that? can you be more specific?
=)

**Comment by Wursthandschuh** [comment]
1) goto install directory. In my case C:\ProgramData\chocolatey\lib\rambox\
2) open tools\resources\app.asar ( There is a 7zip and some node module for that)
3) extract resources\Rambox-all.css
4) add your css to the file and save
5) put it your modified Rambox-all.css back in the .asar file
6) restart rambox

I tried creating my own css file and adding it in the app.json, but that didn't work for some reason :/

**Comment by yurividal** [comment]
Thanks @Wursthandschuh i i got it. now, it would be great if we could have the title bar custom color also, perhaps using Electron's method, with this 

https://github.com/sidneys/electron-titlebar-windows

**Comment by Wursthandschuh** [comment]
should be possible. 
I'm fine with  the global windows color though

**Comment by yurividal** [comment]
good question. I am on windows 10 insider preview, and microsoft is implementing global dark mode. So, most of my apps currently import that setting from Windows (Windows explorer, Firefox...) and set dark titlebar when dark mode is inabled. But, Rambox does not.

**Comment by yurividal** [comment]
Thanks @Wursthandschuh i i got it. now, it would be great if we could have the title bar custom color also, perhaps using Electron's method, with this 

https://github.com/sidneys/electron-titlebar-windows
