### ISSUE TITLE
Service Request: Verizon Message+

### ISSUE THREAD

**Issue by ncbaratta** [ramboxapp/community-edition#1970]
I'd love to see Verizon's Message+ plus service added for texting from my desktop.

Info URL: https://www.verizonwireless.com/solutions-and-services/apps/verizon-messages/
Service URL: https://web.vma.vzw.com/vma/web2/tnc/Show.do

**Comment by RogueScholar** [comment]
This would be simply brilliant, provided a method was found for more persistent authentication credentials than the web portal offers, akin to the desktop application available for Windows. It's the frequency of that onerous process, mandated by the fact that I'm a Linux user and thus excluded from the official desktop apps, that prevents me from making regular use of the service.
