### ISSUE TITLE
Referencing #1002 - Outlook365 / Teams / ADFS not opening

### ISSUE THREAD

**Issue by crollcomp** [ramboxapp/community-edition#1972]
### Steps to reproduce

1. Add Office 365 account URL
2. Sign in with account name on sign in page
3. White screen, no action

### Expected behavior

I would expect to see my webmail Outlook 365 application.

### Actual behavior

White Screen, no action

### ENVIRONMENT

> Rambox: v0.6.2 CE
> OS 10.14.1 Mojave
> 64bit Arch
> Electron 2.0.8
> Chromium 61.0.3163.100
> Node 8.9.3

**Comment by mike391** [comment]
I think it may have something to do with Issue #1880

**Comment by pszemus** [comment]
Still an issue with Rambox 0.6.3
