### ISSUE TITLE
Services edges cut off

### ISSUE THREAD

**Issue by mkasprz** [ramboxapp/community-edition#1975]
The initial issue #1028 got closed due to inactivity, but the problem seems to still exist in version 0.6.2. https://github.com/ramboxapp/community-edition/issues/1028#issuecomment-409127254 answer was helpful (thank You pietro909), but at the end it seems that the the problem (at least the one I experienced) comes from changing zoom level of the Rambox services settings page (main Rambox page). Changing zoom level for services, fortunately, seems to work well if that page zoom is unchanged.

Later on I discovered that https://github.com/ramboxapp/community-edition/issues/1028#issuecomment-322418736 seems to be exactly what I experienced (thanks m4rcu5!).  That's still kind of a workaround though. Or is it a bug that it's possible to zoom out that page?

### Steps to reproduce
1. Zoom out main Rambox page with <kbd>Ctrl</kbd>+<kbd>-</kbd>.
2. Switch to some service tab.

### Expected behavior
Service is displayed correctly.

### Actual behavior
Right edge is cut off.

### ENVIRONMENT
> Rambox: v0.6.2.
> OS: Ubuntu 18.04.
> Arch: x64.

**Comment by cmario92** [comment]
I have the same issue, the Rambox window is only rendering around ~90% of the width and ~70% of the height. 

In chat services like Whatsapp, messenger etc the chat layout is completely hidden.

**Comment by syamimh** [comment]
Thank you. Been bothering me for a month. ctrl + - solved my problem
