### ISSUE TITLE
Save zoom amount per service

### ISSUE THREAD

**Issue by KMamedoff** [ramboxapp/community-edition#1982]
Rambox: v0.6.2
OS: macOS

**Comment by carroarmato0** [comment]
Same.

You open any service.
Change the zoom level (View > Zoom In/Out)
Close Rambox and then reopen.

Expected behavior is that Rambox remembers the Zoom level per service.

Rambox 0.6.3
Arch: x64
Electron: 2.0.14
Chromium: 61.0.3163.100
Node: 8.9.3
