### ISSUE TITLE
Messages don't appear in microsoft teams.

### ISSUE THREAD

**Issue by SimonLefort** [ramboxapp/community-edition#1993]
### Steps to reproduce
1. Use Microsoft Teams (really not recommended...)
2. Add this service in Rambox < 0.6.3 (and it's work!)
3. Upgrade to Rambox 0.6.3 (and it doesn't work anymore.)

### Expected behavior
See my messages ?

### Actual behavior
Conversations are empty, no message appear.

### ENVIRONMENT
Version: 0.6.3
Platform: linux (x64)
Electron: 2.0.14
Chromium: 61.0.3163.100
Node: 8.9.3

**Comment by SimonLefort** [comment]
Similar to : https://github.com/ramboxapp/community-edition/issues/1641

Idea : Change the user agent ?

**Comment by SimonLefort** [comment]
It works with this solution : https://github.com/ramboxapp/community-edition/issues/1354#issuecomment-350966660

> As a quick and dirty hack: edit the service, open the “Advanced” section, and add the following JavaScript snippet in the “Custom Code” textarea:
> 
> ```
> navigator.__defineGetter__('userAgent', function(){
>     return 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36';
> });
> ```

**Comment by neilunderwood** [comment]
Just want to add to this.  I'm experiencing the exact same issue this morning after the update.  Where exactly am I supposed to add this code snippet?

**Comment by saenzramiro** [comment]
Guys, I will need help fixing this issue.
@neilunderwood You need to add @SimonLefort code in "Custom Code" field inside Advanced in Add/Edit service window.
If that doesn't work, we will need to find a fix.

**Comment by uuksu** [comment]
Same issue here and provided workaround does work.

Nevertheless it should work without need of workarounds so maybe somekind of fix should be invented.

**Comment by dhawk00** [comment]
Same issue, have been just "dealing with it" for a week or so. The code provided DOES seem to work, though this is a little annoying.

**Comment by neilunderwood** [comment]
I've tried this multiple times over the past month or so and that custom user agent string does nothing for me.  I'm still missing a chunk of like 3 months worth of chat messages.  FWIW.

Reverted to 0.6.2 until this gets sorted out.

Bummer since 0.6.3 actually has video enabled.
