### ISSUE TITLE
unread alarm in Gmail does not appear

### ISSUE THREAD

**Issue by jwhan77** [ramboxapp/community-edition#1999]
### Steps to reproduce

1. Unread notification does not appear on gmail despite unread mail exist.
2. It can be fixed by modifying gmail's js_unread in app/store/ServicesList.js

### Expected behavior

![expected](https://user-images.githubusercontent.com/33440610/49665188-75e8d900-fa97-11e8-92e2-3e1a2db6b100.PNG)

### Actual behavior

![unexpected](https://user-images.githubusercontent.com/33440610/49665192-797c6000-fa97-11e8-9a9b-ffc68ced07ee.PNG)

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Ubuntu 16.04 LTS

> Arch: x64

**Comment by maxerbox** [comment]
Fixed in #2034

**Comment by Upgreydd** [comment]
Still applicable
