### ISSUE TITLE
Custom service editing popup cannot be closed

### ISSUE THREAD

**Issue by bartmanus** [ramboxapp/community-edition#2005]
### Steps to reproduce

1. Add custom service (i added some privately hosted Outlook Web App)
2. Edit the service, something innocent like 'Display tab unread counter'
3. Click 'Edit <service name>'.

### Expected behavior

Popup closes and normal navigation between service tabs is possible.

### Actual behavior

Closing the editing popup is impossible, switching to service tabs is impossible. However, after an app restart the changes are persited.

### ENVIRONMENT

> Rambox: v0.6.3 

> OS: Fedora 28

> Arch: x64

**Comment by saenzramiro** [comment]
Did you try restarting Rambox to see if the problem persist? Maybe you had another error before and that causes malfunctions.
