### ISSUE TITLE
Whatsapp can't show enlarged profile photos.

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#2006]
Alright, I believe the issue started either with the latest Rambox update, or the latest Whatsapp update, or the latest Flash plugin update... I could try previous versions of Rambox and Flash but, perhaps someone has a solution. The issue is, I can no longer enlarge profile photos in Whatsapp. I mean, I go to a contact's profile, I click on their profile photo and instead of getting an enlarged version of it, outside the circle frame, I get... nothing. The whole screen gets a white, semiopaque layer over it and that's what is supposed to happen, but it should also have the image in the middle of it too. Well, it doesn't. I can exit this by clicking escape luckily. Any ideas on how this issue can be solved? Windows 7 here.

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 6.1.7601

**Comment by dd23** [comment]
Same here on Win10 x64 and a recent Manjaro Linux. 
Rambox 0.6.3
