### ISSUE TITLE
Whatsapp Web ask for Google Chrome Update

### ISSUE THREAD

**Issue by qwertyuser1983** [ramboxapp/community-edition#2009]
### Steps to reproduce

1. Open Rambox
2. Open Whatsapp Web
3. 

### Expected behavior

Show Whatsapp Web

### Actual behavior

![image](https://user-images.githubusercontent.com/22538918/49941646-b0c69300-ff15-11e8-915a-85d72af2f0df.png)

### ENVIRONMENT

> Rambox: v0.X.X
0.6.3

> OS: XXXX
Bodhi Linux 4

> Arch: x64 or ia32
x64

**Comment by abaumg** [comment]
Same here, on Windows 7.

Version: 0.6.2
Plattform: win32 (x64)
Electron: 2.0.8
Chromium: 61.0.3163.100
Node: 8.9.3

**Comment by kjuanman** [comment]
Same here, on Linux

Version: 0.6.3
Platform: linux (x64)
Electron: 2.0.14
Chromium: 61.0.3163.100
Node: 8.9.3

**Comment by Jeffrey04** [comment]
On mac it works after I reload the app with comand+R
Not sure on others platform, try reloading the tab maybe?

**Comment by ivoanjo** [comment]
> Not sure on others platform, try reloading the tab maybe?

Thanks for the suggestion -- reloading the tab worked for me 👍

**Comment by saenzramiro** [comment]
Like @Jeffrey04 said, reloading or removing WhatsApp and adding it again can solve the problem.

**Comment by abaumg** [comment]
For the sake of completeness: Reloading the tab didn't work for me, but removing+readding did.

**Comment by rfpolverini** [comment]
Same for me, removing+readding works OK!!
