### ISSUE TITLE
0.6.3 not showing badges for mail

### ISSUE THREAD

**Issue by KielHaym** [ramboxapp/community-edition#2017]
currently have my gmail attached, since the update the notification badges do not appear.
other badges working as intended.

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 10.0.17134

**Comment by maxerbox** [comment]
Fixed in #2034

**Comment by sebastienserre** [comment]
and what about an update that will implement this ?

**Comment by maxerbox** [comment]
Fixed in #2034
@sebastienserre
That's up to the repo admin to merge it
