### ISSUE TITLE
0.6.3 Reports wrong operating system to WhatsApp on mobile device

### ISSUE THREAD

**Issue by yafp** [ramboxapp/community-edition#2018]
### Steps to reproduce

1.  Install RamBox 0.6.3 (AppImage x64) on Linux
2.  Configure WhatsApp in Rambox
3.  Use WhatsApp in Rambox
4. Check the reported/connected device in WhatsApp on Android

### Expected behavior

WhatsApp (on Android) should report some kind of Linux under connected devices

### Actual behavior

WhatsApp (on Android) reports a Windows 10 host as last active device

### My 2 cents
* I assume this Rambox build reports the wrong operating system.
* I am not sure if its an issue which only occurs on the Linux AppImage x64 builds
* I reproduced it on several linux systems (Arch & Ubuntu)

### ENVIRONMENT

> Rambox: v0.6.3
> OS: Ubuntu / Arch Linux
> Arch: x64

**Comment by kalib** [comment]
Not only on Linux. I have the same issue (MacOS X Mojave).
Rambox:
Version: 0.6.3
Platform: darwin (x64)

**Comment by maxerbox** [comment]
Well, I checked the User Agent and it's good, that's weird, that's maybe how WhatsApp determine which OS you are on
![image](https://user-images.githubusercontent.com/12765875/50602665-2dff7b00-0eb8-11e9-995a-87bb62eacec9.png)

**Comment by Simon0Harms** [comment]
I like it, more market share for linux is a good market share ;)

**Comment by yafp** [comment]
....

**Comment by cvandermeer** [comment]
This is still an issue
Rambox 0.6.3
macOs Mojave 10.14.13

**Comment by maxerbox** [comment]
Should be fixed with #2111 , we just need to remove the user agent

**Comment by cvandermeer** [comment]
@maxerbox ah very nice, and quick response ;)

**Comment by maxerbox** [comment]
Fixed in #2139
