### ISSUE TITLE
MS Teams doesn't show chat history

### ISSUE THREAD

**Issue by kr3t3n** [ramboxapp/community-edition#2023]
### Steps to reproduce

1. Add MS Teams account
2. Send some messages
3. Open MS Teams the next day, all message history is not displayed

### Expected behavior

MS Teams keeps all the message history in the cloud and if the MS Teams tenant is accessed via the browser link, it shows all of the history. However, when opened in Rambox, it shows the empty team chat screen ("Let's get the conversation started")

### Actual behavior

After reloading Rambox all previous history is not displayed (it is not lost, as it is available and visible if the MS Teams tenant is loaded in browser). 

### ENVIRONMENT

Windows 10

> Rambox: v0.6.3

> OS: Windows 10

> Arch: x64

**Comment by blackscorpionster** [comment]
Current version: 0.6.3, Ubuntu 18. I upgraded Rambox this morning from the prev version (0.6.1) and now all my conversations do not show up. I checked teams on the browser and it works fine there.

**Comment by bkeefer** [comment]
Same situation. Been dealing with this for over a month, and it's getting frustrating... 

currently running 0.6.3 on Fedora 28. 

Looking under my .config/Rambox/Partitions directory, I see two distinct teams directories, one called teams_1 and the other called teams_5. Each of those has a Cache directory, and hte _5 one appears to be the current one, but closing and re-launching the Rambox app, and none of that matters.

**Comment by ZEROF** [comment]
Hi,

Same issue on my side, BackBox linux, based on 16.04LTS. Messages don't show in history.

**Comment by RadiRadiesel** [comment]
Signing Out and signing in again does solve that issue on my Mac...

**Comment by ZEROF** [comment]
Working for me now on Linux, thanks :+1:

**Comment by maxerbox** [comment]
@kr3t3n @remia @blackscorpionster Can you sign in and sign out ?
