### ISSUE TITLE
Global unread counter is not working for some services

### ISSUE THREAD

**Issue by kr3t3n** [ramboxapp/community-edition#2031]
### Steps to reproduce

1. Install Rambox
2. Add services MS Teams, Discord, GMail
3. Experience issue of global counter not working

### Expected behavior

Global counter should be showing the number of unread messages on the desktop icon in the Windows tray bar.

### Actual behavior
The Rambox icon does not change to show the global unread count, regardless if there are unread messages in the MS Teams, Discord or GMail services (and their counter indicates them)

### ENVIRONMENT

Windows 10

> Rambox: v0.6.3

> OS: Windows 10

> Arch: x64

**Comment by maxerbox** [comment]
Discord is still working on 0.6.3
Gmail Fixed in #2034

**Comment by kr3t3n** [comment]
Thanks, it works great now! Is this going to be in the next version update?
