### ISSUE TITLE
Still no unread badge gmail

### ISSUE THREAD

**Issue by lhalman** [ramboxapp/community-edition#2032]
### Steps to reproduce

1. Close and re-open Rambox
2. Refresh and change notification settings, turning off and then back on badge notifications
3. Check 'Show notifications', 'Display tab unread counter', 'Include in global unread counter'
4. Click 'Edit [gmail name]'
5. Confirm using most up-to-date Rambox

### Expected behavior

Rambox shows unread badge when receiving new unread emails in Gmail

### Actual behavior

No unread badge shows when unread messages arrive

### ENVIRONMENT

> Rambox: v0.6.3

> OS: MacOS Mojave 10.14.2 (18C54)

> Arch: x64

I've seen many threads about this, but none seem to have clear instructions for fixing this issue for n00bs like myself! Is it not already integrated into the new update to fix this?

**Comment by lhalman** [comment]
Screenshot of issue:
<img width="1440" alt="screen shot 2018-12-30 at 4 53 42 pm" src="https://user-images.githubusercontent.com/46271586/50553003-8b46c280-0c53-11e9-89f5-92af6952dff7.png">

**Comment by martin-g** [comment]
Same here

**Comment by maxerbox** [comment]
Fixed in #2034
