### ISSUE TITLE
Stale issue github bot is not working correctly

### ISSUE THREAD

**Issue by pirate** [ramboxapp/community-edition#2036]
https://github.com/ramboxapp/community-edition/issues/1629

This issue was closed due to inactivity when there was activity, please reopen it.

**Comment by MurzNN** [comment]
Related issue https://github.com/ramboxapp/community-edition/issues/2039

**Comment by MurzNN** [comment]
bump

**Comment by saenzramiro** [comment]
Stalebot from now will only work with issues with the label "more-information-needed".
