### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by VarunAgw** [ramboxapp/community-edition#2046]
Backing up is not working for me since 08.12.2018.

Rambox: Latest
OS: Win 1809 x64

![sync](https://user-images.githubusercontent.com/4201835/50741042-61b00d00-11f8-11e9-89ba-6e8fb97c79e9.png)

**Comment by douglasanpa** [comment]
configuration restore works, backup not works

**Comment by douglasanpa** [comment]
i'm in linux
