### ISSUE TITLE
whatsapp web not load 

### ISSUE THREAD

**Issue by Lvaskz** [ramboxapp/community-edition#2047]
### Steps to reproduce

1. install rambox 0.63
2. add whatsapp
3. try it

### Expected behavior

Load whatapp and working

### Actual behavior

not load, white screen

### ENVIRONMENT

Windows 7 Pro.
64 bit
Core i7

> Rambox: v0.6.3

> OS: windows 7 pro

> Arch: x64

**Comment by maxerbox** [comment]
Open Dev tools for what's app tab (right click on whatsap).
Do you have any errors in console tab ? Red   messages

**Comment by Lvaskz** [comment]
![clipboard02](https://user-images.githubusercontent.com/29207169/50834027-9b783500-1318-11e9-89ea-a70447276691.png)
![clipboard01](https://user-images.githubusercontent.com/29207169/50834028-9b783500-1318-11e9-9a5c-68222aa14363.png)

**Comment by MarvinMep** [comment]
Here, I get the message: 
"WhatsApp works with Google Chrome 36+
To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.
UPDATE GOOGLE CHROME"

**Comment by shanness** [comment]
Hey @MarvinMep , I was getting the same.  I upgraded to 0.63 and still had the same message as you.  I then did a reload and it reloaded OK.  Right click on your whatsapp tab heading and choose reload, I think it'll fix your problem.

**Comment by MarvinMep** [comment]
Thanks, @shannes! It worked here.

**Comment by Lvaskz** [comment]
Hi, now it is ok. No problem with rambox in fact, just with restiction in my pc. TI FIXED
