### ISSUE TITLE
WhatsApp brakes.

### ISSUE THREAD

**Issue by Hasermax** [ramboxapp/community-edition#2049]
Slows down viewing of a photo and video in WhatsApp.
The latest version in which there was no problem of "Rambox.Setup.0.5.17-x64". 
After updating to the version of Rambox-0.6... pulling and brakes of multimedia began.

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 10.0.14393

**Comment by snoopy-coder** [comment]
> The latest version in which there was no problem of "Rambox.Setup.0.5.17-x64". 

I apologize, but how did you manage to use WhatsApp in version 0.5.17-x64? In my case, it only shows [the following message](http://i63.tinypic.com/30lnozd.jpg) and nothing else happens.

**Comment by Hasermax** [comment]
Earlier version 0.5.17 and earlier versions worked perfectly.
Now they do not work for me too: - (
I hoped that will correct brakes in versions 0.6.x, but already 0.6.3 and is corrected nothing.

**Comment by snoopy-coder** [comment]
I have an absolutely crazy idea to take [UAParser.js](https://github.com/faisalman/ua-parser-js) which supports getUA() and setUA() methods and use it as a code when creating a custom service for WhatsApp. But I'm not sure that the Rambox allows you to use external libraries for the [JavaScript Code injection](https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code).

**Comment by Hasermax** [comment]
I will not understand for what then here a forum at all. 
I thought communication with the developer here, and here just correspondence with users.
