### ISSUE TITLE
Telegram is not working in latest version

### ISSUE THREAD

**Issue by cseas** [ramboxapp/community-edition#2054]
### Steps to reproduce

1. Add Telegram with default options

### Expected behavior

The app should open up asking for some login.

### Actual behavior

Just shows a blank white screen, even on Reload.

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Ubuntu 18.04.1 LTS

> Arch: x64

**Comment by tglhteam** [comment]
I have the same problem, help me fix it.
