### ISSUE TITLE
[Question] Is there a way to enable audio & video calls for WhatsApp & ICQ ?

### ISSUE THREAD

**Issue by Nokia808** [ramboxapp/community-edition#2058]
Hi.
Currently Rambox allow to use WhatsApp & ICQ. But no audio nor video calls on these services. 
Is there possibility to enable audio & video calls on these services without waiting till their web interfaces enable them from their side ?

**Comment by maxerbox** [comment]
Well, if it's not available on the web version, Reverse engineering whatsapp I guess, or maybe if they have an API, making a client

**Comment by Nokia808** [comment]
@maxerbox 
Do you mean this:
https://github.com/mailru/icqdesktop

**Comment by Nokia808** [comment]
Is it not important to make Rambox be able to utilize camera & mic ? Why "will not fixed" ??
