### ISSUE TITLE
Rambox does not notify me on steam, slack- or icq-message

### ISSUE THREAD

**Issue by o0Julia0o** [ramboxapp/community-edition#2059]
hi, 

i have the problem on serveral systems, friends, too. Rambox does not notify on steam incoming message, or from slack, icq. Notification and Sounds are turned on. It´s not the portable edition, because there this problem i read about more often.

Version: 0.6.3
Plattform: win32 (x64)
Electron: 2.0.14
Chromium: 61.0.3163.100
Node: 8.9.3

Windows 10 64bit 1809 Build 17763.253

It would be nice, if you could make shift+F1 to switch DND-Mode. F1 is to common.

**Comment by o0Julia0o** [comment]
No answer?

**Comment by saenzramiro** [comment]
Can this be related with #2189?

**Comment by o0Julia0o** [comment]
No chance to make the key editable?
