### ISSUE TITLE
Custom Service and multiple URLs

### ISSUE THREAD

**Issue by arctiqtim** [ramboxapp/community-edition#2063]
### Steps to reproduce

1. Try to add a custom service where the site references multiple URLs ... like a chat service or something

### Expected behavior

Should be an option to have multiple URLs be serviced.

### Actual behavior

When accessing a service/site that has additional URLs, those links open up in default browser every time you navigate anywhere in your custom app.

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Linux / Fedora

> Arch: x64

**Comment by maxerbox** [comment]
Which service is doing this behaviour ?
