### ISSUE TITLE
Slack will require Chromium 66 or later after March 15

### ISSUE THREAD

**Issue by bkimmett** [ramboxapp/community-edition#2064]
Slack has made it known that they're bumping up their [minimum browser requirements](https://get.slack.help/hc/en-us/articles/115002037526) as of March 15. They're going to require Chrome 66 or later.

### ENVIRONMENT

> Rambox: v0.6.3

> OS: macOS 10.12.6

> Arch: x64

**Comment by claui** [comment]
### Steps to reproduce

1. Open [https://get.slack.help/hc/en-us/articles/115002037526](https://get.slack.help/hc/en-us/articles/115002037526) in the browser.
2. Read announcement that on March 15, 2019, Slack is changing the browser requirements so that Chromium needs to be on version 66 or newer.
3. From the menu, select _Rambox_ » _About Rambox._

### Expected behavior

The About Rambox dialog shows a Chromium version of 66 or newer.

### Actual behavior

The About Rambox dialog shows a Chromium version of 61.0.3163.100.

### ENVIRONMENT



> Rambox: v0.6.3

> OS: macOS 10.14.3 (18D42)

> Arch: x64

**Comment by StormPooper** [comment]
Currently getting this notification now and then when using Slack:
![image](https://user-images.githubusercontent.com/1657182/51607938-fa8b9b80-1f0d-11e9-9551-e61e53471cd8.png)
The link goes to the help article listed above.

**Comment by saenzramiro** [comment]
We will release a new version of Rambox CE ASAP, and of course will be before March 15.

**Comment by daveaglick** [comment]
FWIW, I'm using Rambox Pro and have Amazon Music as one of my tabs - also getting a similar message (totally unrelated to Slack) about outdated Chromium version and deprecated support. Just another hint that it would probably be good to bump it.

**Comment by fvulich** [comment]
@daveaglick also a Rambox Pro update will be coming soon (with an updated Chromium)

**Comment by burtek** [comment]
@saenzramiro  what's the progress with 0.6.4? Just curious, I know it's not March 15th yet

**Comment by claui** [comment]
Anyone willing to review PR #2111?

I’ve tried on my machine; it refuses to launch the app even from upstream `master`:

```
Sencha Cmd 6.6.0.13 - Crash report
================================================
An error occurred while executing the following command: app watch
[…]
/opt/Sencha/Cmd/6.6.0.13/plugin.xml:378: The following error occurred while executing this line:
/Users/claudia/Documents/dev/rambox/.sencha/app/build-impl.xml:252: The following error occurred while executing this line:
/Users/claudia/Documents/dev/rambox/.sencha/app/watch-impl.xml:87: The following error occurred while executing this line:
/Users/claudia/Documents/dev/rambox/.sencha/app/build-impl.xml:291: The following error occurred while executing this line:
/Users/claudia/Documents/dev/rambox/.sencha/app/sass-impl.xml:205: The following error occurred while executing this line:
/Users/claudia/Documents/dev/rambox/.sencha/app/sass-impl.xml:297: Problem: failed to create task or type x-compass-compile
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
```

See [sencha-error-20190312.log](https://gist.github.com/claui/2d03e2a2521fdbc8a2ada9691a1aaff5).

**Comment by maxerbox** [comment]
Did you installed ruby ?

**Comment by claui** [comment]
@maxerbox Yes, I do have Ruby 2.6.1 installed. A 2.3.7 installation also came with the OS, which is macOS 10.14.3.

**Comment by claui** [comment]
I’ve upgraded `sencha` from 6.6.0.13 to 6.7.0.37 and run `sencha app upgrade`.

I still get the same error when running `sencha app watch`. 😞
Any ideas how to troubleshoot that?

Anyone else willing to review #2111? There’s only one day left in Slack’s grace period.

**Comment by maxerbox** [comment]
@claui 
Can you check if eveything required is installed https://stackoverflow.com/a/34339357 ?

**Comment by maxerbox** [comment]
If you would like to test it, I merged every open pull requests and made a build : 
https://github.com/maxerbox/community-edition/releases/tag/untagged-fe944ef70a27f5c75470
