### ISSUE TITLE
Keyboard input can bypass lockscreen

### ISSUE THREAD

**Issue by frommMoritz** [ramboxapp/community-edition#2065]
### Steps to reproduce
1. Place the cursor in a text input in your favourite chat programm
2. Lock Rambox (either using F2 key or the lock button on the start page)
3. Use alt + tab to tab out of the rambox windows and back in
4. Type something, maybe press enter as if you'd be sending a message

### Expected behavior
Once you tab back into Rambox, the password field should be selected automaticity. And everything you type, should be either voided or appended to the password field. 

### Actual behavior
Everything you type after tabbing back bypasses the lock screen and is being sent where your cursor is. This renders the lock screen, at least partially, useless.

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Linux Mint 19 Tara

> Arch: x86_64

**Comment by saenzramiro** [comment]
Wow! 👏 We have to prevent focus on the active app if the locking window is displayed.

**Comment by maxerbox** [comment]
Very weird indeed,
It seems related to chromium.
The latest focused input is restored in the webview, even if you have clicked elsewhere in the parent window.
I tried to unfocus it, with `blur()` alternative, and more, but it seems not working

**Comment by Redirts** [comment]
The find option should be added to the Edit menu

**Comment by maxerbox** [comment]
This is not related
