### ISSUE TITLE
update misreport

### ISSUE THREAD

**Issue by Sadi58** [ramboxapp/community-edition#2067]
Recently Rambobox started reporting an update from time to time although there's no update. 

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> linux x64 4.15.0-43-generic

**Comment by fvulich** [comment]
could you share a screenshot with us?

**Comment by Sadi58** [comment]
Here is the screenshot showing false update notice.
After clicking it, a thin green progress bar appears in the right panel for a couple of seconds (unfortunately I wasn't quick enough to catch it as well), and then the app window refreshes as usual without any change.
![rambox update notice](https://user-images.githubusercontent.com/6375934/52438783-1c4e6a80-2b2b-11e9-970c-d92896a11c6c.jpg)

**Comment by fvulich** [comment]
It's seems to be an issue of the whatsapp's app... some people had the same issue, check this link
[https://www.reddit.com/r/whatsapp/comments/4j5y7y/does_anybody_else_have_the_update_available_click/](https://www.reddit.com/r/whatsapp/comments/4j5y7y/does_anybody_else_have_the_update_available_click/)

**Comment by Sadi58** [comment]
Oh, thanks, I see now that it's not a Rambox issue.
