### ISSUE TITLE
Get new smilies from WhatsApp new release

### ISSUE THREAD

**Issue by Kwadz** [ramboxapp/community-edition#2068]
WhatsApp released new smilies that are available in the new updates only. 

> Rambox: v0.6.3

> OS: macOS 10.14.2

> Arch: x64

**Comment by fvulich** [comment]
Hi Kwadz, thanks for reporting this issue, sadly it's not an issue that we could resolve, the new smilies are not included, yet, in the web version of Whatsapp... they are only accessible through the Andriod/IOS app
