### ISSUE TITLE
No unread counter on Fleep

### ISSUE THREAD

**Issue by twinklebob** [ramboxapp/community-edition#2069]
I have been using Fleep for some time and have noticed, perhaps since the last update, that although I get notifications for new messages I do not have an unread count on the Fleep tab - although I'm sure it has been there in the past, even if it was just a generic unread notification (red dot).

	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> linux x64 4.4.0-139-generic

**Comment by fvulich** [comment]
Hi, it's working in my setup, but I made an alternative code to inject...

`function checkUnread(){var e=document.querySelector(".unread-toggle").querySelectorAll("div")[1].innerHTML.replace(".","").replace(/\D/g,"");updateBadge(e?parseInt(e):0)}function updateBadge(e){1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3e3);`

try it then tell me if it worked. :)
