### ISSUE TITLE
Showing wrong OS in WhatsApp

### ISSUE THREAD

**Issue by codesome** [ramboxapp/community-edition#2071]
### Steps to reproduce

1. Use WhatsApp web in Rambox.

### Expected behavior

In mobile it should show logged in `Linux` machine.

### Actual behavior

Says logged in using `Windows 10`. For a moment it scared me if anyone had hacked my account. Then logging out of all devices and logging in again using Rambox revealed the bug.

### ENVIRONMENT

> Rambox: v0.6.3
> OS: Ubuntu 18.04.1 (Linux 4.15.0-29-generic)
> Arch: x64

**Comment by maxerbox** [comment]
Duplicated
https://github.com/ramboxapp/community-edition/issues/2018
