### ISSUE TITLE
when signing with google some old setings are restored

### ISSUE THREAD

**Issue by polrus** [ramboxapp/community-edition#2072]
### Steps to reproduce

1. delete .config/Rambox
2. open Rambox and sign in with Google
3. 

### Expected behavior

SOme old - not working config is resotred - and I'm unable to modify it
The google copy is always master.
How do I delete the settings stored at google?

### Actual behavior

I would expect to be able to start form scratch and overwrite google settings
Or maybe it is just google sign in and config is stored somewhere else?

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Linux
> Arch: x64

**Comment by fvulich** [comment]
could you give us more info? what config still remains after you delete  .config/Rambox? some screenshots will help

**Comment by polrus** [comment]
after i remobe ./config/Rambox of course the app is blank but as soon as I do login (in rambox settings) and use my google credentials there some config from old rambox is imported from auth0.com I assume.
This config that is restored is unusable in 6.3 see this screen [https://send.firefox.com/download/1a4d97b4d5/#5HxMAaekcVAoKI8_gAUHDA
](url)
I would create a blank set of config as a workaround but as soon as I login with google the config will be downloaded - I think the app should find out or ask if the cloud store settings are more valid or the local copy is more valid and should overwrite (non functional in my case) config.

**Comment by schousda** [comment]
Kind of the same here with twitter login.
When i go to the sync section it shows me a backup from october 2017 even if i just did a complete new backup on my other computer.
If i do a restore i get a very old config which could be the one from 2017.
