### ISSUE TITLE
Android port? Ref: #1820 - stay away Stalebot! 

### ISSUE THREAD

**Issue by Ryder17z** [ramboxapp/community-edition#2074]
See referenced post #1820

**Comment by damongant** [comment]
Opening more issues wouldn't make it happen.

The tech Rambox is built on does not translate to Android. This wouldn't be a port, it'd be an outright new codebase.

So I'd suggest you dial down your expectations (especially from an open source project you expect to make a 180 degree turn on focus).

**Comment by Patrik356b** [comment]
@damongant

I opened a new issue because I couldn't re-open the old one. And here is a tip: read before you post a comment. 

All you need to know is in the previous issue.

**Comment by Ryder17z** [comment]
Stale bot deserves to be shot.

What would be beneficial to users is if Rambox recommend app <insert name> for mobile platforms while they point back to Rambox for desktop.
