### ISSUE TITLE
Rambox wiped all of my tabs

### ISSUE THREAD

**Issue by babolivier** [ramboxapp/community-edition#2077]
Last evening, for some reason (which is unrelated to Rambox), I ran out of free disk space. I'm using [Riot](https://riot.im) in Rambox and started seeing it display errors about IndexedDB connections closing. I restarted Rambox and all of my tabs had disappeared. I waited till today, so there would be a full stop and start of my laptop) to see if that was a permanent thing (as per "when in doubt, reboot"), which it apparently is.

This is particularly troublesome due to Riot storing a bunch of important stuff related to E2E encryption in the browser's LocalStorage and IndexedDB (which there are mechanisms to recover but they either require you to have an additional device connected to your account (which one of my accounts didn't have) or are hidden under an "experimental/idev" flag). I'm throwing away part of the template because there's not much I did myself Rambox-wise and wouldn't know how to reproduce this issue, and the expected vs actual behaviour seems pretty obvious to me (tabs stay there vs tabs are actually wiped out).

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Archlinux

> Arch: x64

**Comment by My-Name-Is-Adam** [comment]
Don't bother with Rambox.. Developer has abandoned it for the paid version. 

Use Wavebox. Been using this for a while and it is so much better than Rambox. Even made a few suggestions on Github and they implemented them in the next release. 

Lots of big names use them such as Shopify, Spotify, Adobe, and Microsoft to name just a few. (at least according to the website)

https://wavebox.io

Check it out and let me know what you think :)

**Comment by karfau** [comment]
For me the same just happened after rebooting after a long time.
Until before the reboot all tabs have been there and I was able to use them today before the reboot.

> Rambox 0.6.3
> Electron 2.0.14
> linux x64 4.20.3-1-MANJARO

I just switched to the above kernel when restarting, but could this really be the issue?
The interesting part is that I also had a disk space problem before my last restart.
I solved it (by deleting some stuff) and there was never any irregularities observed or reported by rambox as far as I know. but wanted to mention it.
Can I provide some log files, or something to help understand whats going on?

**Comment by karfau** [comment]
That is a strange way to treat stale tickets, marking them as "wontfix"...

**Comment by Vioner** [comment]
I also had this happen to me a few times, because of disk space depletion. Last time it happened was just today :D :<
I think Rambox needs a new feature that would act as protection against insufficient disk space scenario. Meaning it would periodically check free space and once it's nearing a threshold it should:
- warn the user
- freeze/stop whole app - in order to keep things saved until space is freed. 

I'll try to add this myself if main contributors won't, but I don't know when I'll have the time.

**Comment by rafenden** [comment]
Anyone found a way to restore the tabs?

**Comment by waldirio** [comment]
Hello folks, 

2020.07.10 and happened with me. Disk full and voilá, no more tabs in rambox.

Definitely, a feature to guarantee this will not happen when reaching 100% of usage is really required.

Thank you
Waldirio

**Comment by horaciohs** [comment]
Hi !
Same thing for me: yesterday I had /home full, did cleanup and today after boot all tabs in Rambox had gone.

Rambox (rambox-bin 0.7.5-1)
Linux 5.6.19-2-MANJARO x86_64

Thanks.

**Comment by Vioner** [comment]
Guys, I've made feature to account for this problem. Tested on Linux, works fine. Needs testing on Mac and Windows, so please help out. 
https://github.com/ramboxapp/community-edition/pull/2807
