### ISSUE TITLE
Use updated version of skype for web

### ISSUE THREAD

**Issue by rochamarcelo** [ramboxapp/community-edition#2079]
When I open the skype it shows 'Support for this version of Skype for Web is coming to an end. A new preview version is available now for Microsoft Edge and Google Chrome with HD video calling, call recording and much more. Try it out'.
The app should  use the updated version of skype for web.

### Steps to reproduce

1. Add skype service
2. Try to open the skype
3. Warning message is shown

### Expected behavior

The app should be using the updated version of skype for web

### Actual behavior

The app is using an outdated version of skype for web

### ENVIRONMENT

> Rambox: v 0.6.3

> OS: Ubuntu 18.04

> Arch: x64 

Electron: 2.0.14
Chromium: 61.0.3163.100
Node: 8.9.3

**Comment by My-Name-Is-Adam** [comment]
Don't bother with Rambox.. Developer has abandoned it for the paid version. 

Use Wavebox. Been using this for a while and it is so much better than Rambox. Even made a few suggestions on Github and they implemented them in the next release. 

Lots of big names use them such as Shopify, Spotify, Adobe, and Microsoft to name just a few. (at least according to the website)

https://wavebox.io

Check it out and let me know what you think :)

**Comment by danmdm** [comment]
> Don't bother with Rambox.. Developer has abandoned it for the paid version.
> 
> Use Wavebox. Been using this for a while and it is so much better than Rambox. Even made a few suggestions on Github and they implemented them in the next release.
> 
> Lots of big names use them such as Shopify, Spotify, Adobe, and Microsoft to name just a few. (at least according to the website)
> 
> https://wavebox.io
> 
> Check it out and let me know what you think :)

Cool, thanks a lot for link. You made my day!

**Comment by claui** [comment]
@danmdm @rochamarcelo According to @saenzramiro, the [upcoming Rambox version 0.6.4 is going to ship with an updated Chromium](https://github.com/ramboxapp/community-edition/issues/2076#issuecomment-456978591).

**Comment by fevangelou** [comment]
Sorry @My-Name-Is-Adam but unless you're working for Wavebox, comparing it with Rambox free and claiming the developer has abandoned it for the Pro version is plain stupid. It's stupid because Wavebox is already a commercial app (you might as well support Rambox Pro which also offers a decent free version) and their free version simply allows for 2 Google services only (whaaa?): https://wavebox.io/pricing/

The only free alternatives are [Franz](https://meetfranz.com/), [Manageyum](https://manageyum.com/), [Station](https://getstation.com/) (but it's using a single session like a normal browser so what's the point?) and [Stack](https://getstack.app/).

**Comment by fvulich** [comment]
> Sad to hear that it was abandoned, started to use recently. Thanks for sharing the link.

@danmdm @rochamarcelo  it's not abandoned, and this issue it's gonna be addressed in the new upcoming version 0.6.4

**Comment by saenzramiro** [comment]
Thank you @fevangelou for clarifying. We don't have plans to abandon the project! Indeed, we incorporate a new member to the team to help with the project, right @fvulich?😁

**Comment by fvulich** [comment]
> Thank you @fevangelou for clarifying. We don't have plans to abandon the project! Indeed, we incorporate a new member to the team to help with the project, right @fvulich?

Hell Yeah!

**Comment by fevangelou** [comment]
Appreciate the time and effort you put into Rambox guys :) Thank you.

**Comment by VarunAgw** [comment]
+1. I tried to manually add a custom service for that. But it crash if I click an external link.
