### ISSUE TITLE
No notifications from any service

### ISSUE THREAD

**Issue by fbegyn** [ramboxapp/community-edition#2081]
Since a couple of days I get no desktop notifications from any service in Rambox

### Expected behavior

1. Receive message
2. Get notification

### Actual behavior

1. Receive message
2. Not notification

### ENVIRONMENT

> Rambox: v0.6.3

> OS: 4.20.3-arch1-1-ARCH 

> Arch: x86_64 GNU/Linux

**Comment by fbegyn** [comment]
Somehow on my reboots the `Do not disturb` got toggled, so yeah ...

**Comment by SyntaxErrol** [comment]
>  Somehow on my reboots the `Do not disturb` got toggled, so yeah ...

OMFG. Thanks.
