### ISSUE TITLE
Strange Gmail bug

### ISSUE THREAD

**Issue by drjlm** [ramboxapp/community-edition#2084]
Sent an email from Gmail within Rambox.

When I checked my sent items by accessing Gmail in Chrome, most of the message was missing.

May be a Gmail bug unrelated to Rambox.

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> linux x64 4.15.0-44-generic

**Comment by fvulich** [comment]
Hi, @drjlm ! Was this a one time issue? If it wasn't, could you give us more info? a screenshot will be welcome
