### ISSUE TITLE
Prevent Outlook opening new tabs in browser

### ISSUE THREAD

**Issue by UncleSlug** [ramboxapp/community-edition#2085]
It would be nice if you could prevent opening tabs in the default web browser and instead open the link in the current (rambox) window/tab. A Google search tells me browsers can either do what the page/link tells it to, or override it to force a new tab or force it to open in the current one.

### Steps to reproduce

1. Change to new Outlook web interface
2. Click on calender button in the bottom left.

### Expected behavior

Screen changes to the calender.

### Actual behavior

Screen stays on the mail screen and the calender is opened in another window. Additionally if you were logged into another microsoft account in the browser that calender will open instead of the one for the account logged in from rambox.

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Ubuntu 18.04

> Arch: x64

**Comment by meonwax** [comment]
I have the same problem when using the Outlook 365 webapp integration in Rambox.
This only seem to happen when the _new Outlook_ flag is enabled.

**Comment by Letsch22** [comment]
I can confirm the same behavior happens for me on Windows 10, Rambox 0.6.3 x64. This used to be less of an issue since the new Outlook UI was toggleable, but now it has been rolled out with no way to revert to the old UI that worked (at least for outlook.com accounts).

**Comment by lleifermann** [comment]
I do have the same issue on my Rambox installation, when using the new Outlook design. I don't think this should be marked as wontfix. Any hope for this being fixed?

**Comment by Corchoneitor** [comment]
PR #2102 would address this issue.
