### ISSUE TITLE
gitter login to github leads to white screen of death

### ISSUE THREAD

**Issue by JoeyG1973** [ramboxapp/community-edition#2089]
### Steps to reproduce

1. launch rambox
2. add gitter
3. go to gitter tab
4. select "Sing in to start talking"
5. on popup select "SIGN IN WITH GITHUB"

### Expected behavior

It should ask me to login to github

### Actual behavior

White screen of death

### ENVIRONMENT

Version: 0.6.3
Platform: linux (x64)
Electron: 2.0.14
Chromium: 61.0.3163.100
Node: 8.9.3

**Comment by fvulich** [comment]
When I try to reproduce this issue, I just couldn't, it worked just as it should...  it asked me to log in with github... could you give us more data? do you have other apps (that use github's login) with the same issue?

**Comment by maxerbox** [comment]
Same here, try to reload app (right click on the gitter tab)
