### ISSUE TITLE
login screen splitted in half (two screens setup)

### ISSUE THREAD

**Issue by diego-betto** [ramboxapp/community-edition#2090]
### Steps to reproduce

1. setup dual screen in horizontal extend mode
2. start app with master password required

### Expected behavior
window centered in one of the two screens

### Actual behavior
window is centered so that it's splitted in half per screen

### ENVIRONMENT

> Gnome

> Rambox: v0.6.3

> OS: Ubuntu 18.10

> Arch: x64

**Comment by maxerbox** [comment]
Electron issue https://github.com/electron/electron/issues/3490
