### ISSUE TITLE
Spike Mail Chat

### ISSUE THREAD

**Issue by rauldipeas** [ramboxapp/community-edition#2092]
Is there any way(css) to get Spike notifications on _Custom Service_?

**Comment by GadgetStu** [comment]
I have not even been able to get Spike email working let alone the notifications, can you share how you did this as a Custom Service?

**Comment by rauldipeas** [comment]
I'm just add a custom service and put the Spike web adress, work very well.

**Comment by GadgetStu** [comment]
Thanks for the quick response, I have tried adding https://www.spikenow.com/ and https://spikenow.com/web/?ver=wip&ref=google-search and both of those come up with a separate Rambox window which just hangs :(

**Comment by rauldipeas** [comment]
I'm using `https://spikenow.com/web/?ver=wip&ref=website-direct`

**Comment by GadgetStu** [comment]
Ok I will try that thanks

**Comment by GadgetStu** [comment]
Ok,, so got it to work I had to enter my gmail address and then select not google then it opens up the correct window to authorise.

**Comment by rauldipeas** [comment]
I'm don't using GMail, but you could try with IMAP settings.
