### ISSUE TITLE
Slack "out-of-date" notification

### ISSUE THREAD

**Issue by yarons** [ramboxapp/community-edition#2093]
### Steps to reproduce

Launching the Slack interface pops up the following notification on the bottom right corner:
![image](https://user-images.githubusercontent.com/406826/52534327-eb4b8100-2d48-11e9-9128-23af82368d01.png)

(You're accessing Slack with a third-party
app that is out-of-date.)

### Expected behavior

Updating the Chrome backend?

### Actual behavior

A notification appears.

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Manjaro Illyria 18.0.2, Linux Kernel 4.20.7

> Arch: x64

**Comment by chicoff** [comment]
same problem here v0.6.3 on Ubuntu 18.10

**Comment by chicoff** [comment]
from https://get.slack.help/hc/en-us/articles/115002037526

"Starting on March 15, 2019, we are changing the minimum browser requirements needed to run Slack. Please make sure your browser is up to date."

**Comment by fvulich** [comment]
This issue it's gonna be addressed in the upcoming new version

**Comment by chnbz** [comment]
@fvulich When is that gonna be? Any ETA?

**Comment by holzfelix** [comment]
When will new version comes?

**Comment by vaisov** [comment]
Now I even get this:
![image](https://user-images.githubusercontent.com/3081137/54734327-66555200-4ba7-11e9-9e09-13c38eb5fe86.png)

**Comment by maxerbox** [comment]
@vaisov Did you update to 0.6.4?

**Comment by vaisov** [comment]
Works on 0.6.4. Thanks!
