### ISSUE TITLE
Injecting JS into Discord is not possible

### ISSUE THREAD

**Issue by schittler** [ramboxapp/community-edition#2095]
### Steps to reproduce

1. Add JS code as simple as a `console.log` to Discord
2. Refresh

### Expected behavior

Code is excuted.

### Actual behavior

Code is not run; Discord might be cleaning up the DOM intentionally or unintentionally.

### ENVIRONMENT

> Rambox: v0.6.3

> OS: darwin

> Arch: x64

**Comment by maxerbox** [comment]
Well it is working since the push request for discord notifications is working.

Try to use a timeout

**Comment by damongant** [comment]
Could you assume a baseline of competency, please?

It absolutely is not. Function definitions aren't there either. Pasting the code into inspector however works. Tested setTimeout with 100/1000, but the code doesn't seem to run at all.

**Comment by damongant** [comment]
Issue resolved.

The injected code does not have a trailing newline added to it, so it'll throw an error about an unrecognized token.
