### ISSUE TITLE
gmail not telling i have new mail!

### ISSUE THREAD

**Issue by syfer1987** [ramboxapp/community-edition#2096]
I have just instaled a fresh copy of your app. When a new email comes through Gmail should have a number on the bar or notify me but it does not. Can some look to this? Thanks
I am on windows 8.1 home.

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 6.3.9600

**Comment by maxerbox** [comment]
Dup #1999

**Comment by syfer1987** [comment]
I did not know this dup. Is their any fix?

**Comment by maxerbox** [comment]
https://github.com/ramboxapp/community-edition/pull/2034

**Comment by martin-g** [comment]
Just updated to 0.6.6 and again there is no unread messages counter for GMail.

**Comment by Corchoneitor** [comment]
Fixed in d619a66.

Wait until next release or temporarily add it as custom code.
