### ISSUE TITLE
Slack is complaining 3rd party tool (Rambox) is not up-to-date

### ISSUE THREAD

**Issue by lisandrocarmona** [ramboxapp/community-edition#2100]
Slack is saying Rambox is not using the updated version.
I'm using version 0.6.3 but seems, internally, that Rambox is not updating the APIs of Slack.

![image](https://user-images.githubusercontent.com/6163906/52955786-5eb64980-336c-11e9-97b0-4d5c6f10ef52.png)

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 10.0.17763

**Comment by lisandrocarmona** [comment]
![image](https://user-images.githubusercontent.com/6163906/52955847-873e4380-336c-11e9-94f8-f510ed5bcf83.png)

**Comment by pandruszkow** [comment]
I can confirm I'm also affected by this issue

**Comment by mrbmi513** [comment]
I just signed in to Slack on the same version but did not get this message.

**Comment by Boosik** [comment]
I'm also affected by this

**Comment by lissmeister** [comment]
Same

Version: 0.6.3
Platform: darwin (x64)
Electron: 2.0.14
Chromium: 61.0.3163.100
Node: 8.9.3

**Comment by apeltzer** [comment]
Yeah, they said they're going to release 0.6.4 soonish which updates the utilized electron framework to solve the issue. Just wait for the new update on 0.6.4.  

x-ref : 

https://github.com/ramboxapp/community-edition/issues/2076
