### ISSUE TITLE
Rambox hotkeys conflict with application hotkeys

### ISSUE THREAD

**Issue by guzzard** [ramboxapp/community-edition#2103]
### Steps to reproduce

1. Open and edit an excel file in MS Teams app
2. Press F2 to edit a cell in the excel sheet

### Expected behavior

Expected to edit cell in excel sheet

### Actual behavior

Dialog window appear to enter password to lock Rambox

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Arch Linux

> Arch: x64

It would be nice if it was possible to either rebind the hotkeys used by Rambox (F1, F2) to other keys, or to be able to setup so all keys including F1 and F2 are passed to apps that need this.

**Comment by guzzard** [comment]
unstale thx

**Comment by Corchoneitor** [comment]
There should be some key combination, not just F2.
