### ISSUE TITLE
apps do not fill window

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [ramboxapp/community-edition#2106]
My apps in Rambox only fill a part of the window. Restarting Rambox does not solve it. It happened while zooming in with the shortcut Ctrl+Alt+=

![image](https://user-images.githubusercontent.com/18427584/53209534-0ec0d680-363b-11e9-86c2-555de90a2c54.png)

	> Rambox 0.6.3
	> Electron 2.0.14
	> linux x64 4.19.20-1-MANJARO

**Comment by maxerbox** [comment]
Try resetting zoom and reload

**Comment by Hugo-Trentesaux** [comment]
Already did as well as resizing the window, maximize/minimize zoom, and other tricks that we try when we have no idea of the GUI bug we are facing, didn't work.

**Comment by maxerbox** [comment]
I see what's happenning, it's because you zoomed both rambox and webview.
Go to the rambox tab, (where you add services), and click on view > actual size
![img](https://imgur.com/a/6Iepomb)

**Comment by Hugo-Trentesaux** [comment]
Oh thanks ! That worked !
Back to the normal :1st_place_medal:
