### ISSUE TITLE
Please check sha512 in latest-linux.yml file urgently !

### ISSUE THREAD

**Issue by Nokia808** [ramboxapp/community-edition#2109]
Hi. Please check sha512 hash of Rambox 0.6.3 AppImage x86_64 bit.
In latest-linux.yml file it is:
fT+oysKFXilDJ5mLaBqoXIwuFu5m69bsRhuAGNU59CNXnSm14AUncr5LILxYXAaaJDe4P16YzeWXqNK0o3oHcw==

While on my side by "sha512sum" command, it is:
7d3fa8cac2855e294327998b681aa85c8c2e16ee66ebd6ec461b8018d539f423579d29b5e0052772be4b20bc585c069a2437b83f5e98cde597a8d2b4a37a0773

**Comment by maxerbox** [comment]
You gave a base 16 sequence.
The hash in latest-linuw.yml is in base 64.
Use this website to convert it : http://tomeko.net/online_tools/hex_to_base64.php

**Comment by Nokia808** [comment]
@maxerbox 
I did ! I copied/past result of my terminal output to uppermost field in page you refered me & conversion was exactly same as of that in latest-linux.yml !

This is completely new thing to me !

What is benefit of this method ! Terminal has no option for that, so why developer used this way ? Is it better to use usual sha512 hash ?

**Comment by maxerbox** [comment]
I guess that's the tool @saenzramiro is using.
There are no reasons of encoding in base64.
