### ISSUE TITLE
Messenger opening FB links

### ISSUE THREAD

**Issue by Foggalong** [ramboxapp/community-edition#2112]
### Steps to reproduce

1. Create and log into a standard Messenger service instance
2. Within that, click on any a link to Facebook (profile link, status, etc)

### Expected behavior

Page will open within the default browser

### Actual behavior

Page opens within Facebook, meaning the service needs refreshing to return to messenger.

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Ubuntu 18.04.2

> Arch: x64

**Comment by maxerbox** [comment]
Use CTRL + Click when clicking on a link

**Comment by Foggalong** [comment]
@maxerbox Thanks for the work around in the mean time, but this is still something which should be fixed. The same behaviour doesn't happen with other website and services, I'm guessing because the domains aren't as linked as `messenger.*` and `facebook.*`

**Comment by maxerbox** [comment]
Is it opening it in a new tab in your browser ?

**Comment by Foggalong** [comment]
@maxerbox No it's opening within the Rambox messenger service, that's the issue :)

**Comment by maxerbox** [comment]
Sorry, I meant if you open messenger in your default browser, like Firefox, if you click on a link does it open it in a new tab ?

**Comment by Foggalong** [comment]
@maxerbox Oh right, I get you! Yeah it opens them by default in a new tab without the need for any special middle clicks or keyboard presses.

**Comment by maxerbox** [comment]
Sort of electron / messenger issue. I will look for it

**Comment by Corchoneitor** [comment]
I think this was fixed with the new preferences "Link handling" under app configuration.

**Comment by Corchoneitor** [comment]
This could be done with PR #2102

**Comment by fvulich** [comment]
Is this still reproducible?
