### ISSUE TITLE
Ryver notifications stuck and cant be cleared

### ISSUE THREAD

**Issue by Corosauce** [ramboxapp/community-edition#2113]
### Steps to reproduce

1. Setup Ryver in rambox
2. Have notifications ever in ryver

### Expected behavior

Clearing notifications in ryver should clear them in rambox

### Actual behavior

Every notification ever is counted towards the notification count, regardless of being cleared in Ryver. A friend is also having the exact same issue.

![screenshot_20190228_180007](https://user-images.githubusercontent.com/1238621/53604545-c77a9e80-3b82-11e9-82e4-50bc84323705.png)

### ENVIRONMENT

OS: KDE Neon 18.04

Rambox:
Version: 0.6.3
Platform: linux (x64)
Electron: 2.0.14
Chromium: 61.0.3163.100
Node: 8.9.3

**Comment by fcamblor** [comment]
Same here on Mac OS X
```
Version: 0.6.4
Platform: darwin (x64)
Electron: 3.1.4
Chromium: 66.0.3359.181
Node: 10.2.0
```

**Comment by fcamblor** [comment]
I'm not sure if the bug is really that the count is "stuck" as I see it evolving sometimes.

However, I never saw it below 14 notifications, as if there was 14 notifications (or DOM elements matching some erroneous query selector) hidden somewhere in the Ryver webview
