### ISSUE TITLE
Links don't open in Skype chat (Skype version 8.40.0.70)

### ISSUE THREAD

**Issue by kodeva** [ramboxapp/community-edition#2116]
Links don't open with in the current version of Skype (8.40.0.70).

### Steps to reproduce

1. Click on a link in a Skype chat
or
2. Right-click on the link in the Skype chat

### Expected behavior

Ad 1. - Link is open in a web browser

Ad 2. - Pop-up menu with an item similar to 'Open / copy  URL' shows up.

### Actual behavior

Ad 1. - Nothing happens

Ad 2. - The pop-up menu contains just following items:
- Edit
- Quote
- Forward
- Select messages
- Remove

### ENVIRONMENT

> Rambox:
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 10.0.15063

> OS: Windows 10 x64

**Comment by nzeppos** [comment]
Having the same issue. Seems to be related to the new Skype web client which was switched on as default in the past few days, the old one used to work just fine.

**Comment by nzeppos** [comment]
Apparently there's an easy workaround for this: just **click the middle mouse button** and the link will open in the default browser.

**Comment by kodeva** [comment]
Works nicely! Thank you 👍

**Comment by saenzramiro** [comment]
We are investigating how to fix this problem.
