### ISSUE TITLE
Skype new Version on Rambox

### ISSUE THREAD

**Issue by wallnas** [ramboxapp/community-edition#2119]
### Steps to reproduce

The new version of skype web on rambox , call button isn't active: why ?

### ENVIRONMENT

> Rambox: v0.6.3

> OS: Windows 10

> Arch: x64

**Comment by kr3t3n** [comment]
Same here. What is weirder is that I can see the buttons are active if I use web.skype.com in Chrome but they are greyed out and inactive in Rambox

**Comment by Digioso** [comment]
I have the same issue.

**Comment by maxerbox** [comment]
I guess that's because skype is detecting the electron version, which is outdated
