### ISSUE TITLE
cannot Open link on New Skype

### ISSUE THREAD

**Issue by medeka77** [ramboxapp/community-edition#2121]
When my friends send link i cannot open it, i must copy the link and manualy paste on browser. Also i must disable link preview. This issue not occurs in previous skype, can using right click mouse and then open. there are no option to open link

Step:
1. Click Link
2. nothing happen

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 10.0.17134

**Comment by Digioso** [comment]
I have the same issue.

**Comment by nzeppos** [comment]
This is a duplicate of https://github.com/ramboxapp/community-edition/issues/2116, we have already proposed a workaround there.

**Comment by saenzramiro** [comment]
Duplicate #2116.
