### ISSUE TITLE
Slack integration outdated

### ISSUE THREAD

**Issue by mareng0** [ramboxapp/community-edition#2122]
Latest version of Rambox on Windows 10 is outdated for Slack. Everytime I start Rambox, Slack reminds me that my third-party app (Rambox) is out of date.

**Comment by brossow** [comment]
This is already covered by #2064, #2100 and #2111 (which supposedly will fix the problem when approved).

**Comment by BalintFarkas** [comment]
New 0.6.4 release that came out a few hours ago fixed this for me.

**Comment by holzfelix** [comment]
Can be closed! fixed for now.
