### ISSUE TITLE
CTRL+TAB no longer working in 0.6.4

### ISSUE THREAD

**Issue by fbasara-loft48** [ramboxapp/community-edition#2127]
In 0.6.3 I was able to make use of the next / prev tab shortcuts to switch between the services. In 0.6.4 that feature doesn't seem to work anymore.

1. Upgrade from 0.6.4
2. Have multiple services (tabs) enabled
3. Use CTRL+TAB (WIN & MAC) or CTRL+SHIFT+TAB to navigate tabs

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> darwin x64 17.7.0

**Comment by fbasara-loft48** [comment]
My bad. Duplicate of #2125

**Comment by maxerbox** [comment]
Since chromium's architecture has been reworked, events are not propaged globally anymore. Rambox was using this hack to handle CTRL+TAB, but with the new electron version, it's not working anymore.
A workaround is to handle the events fired by webview.
Fixed in #2138

**Comment by maxerbox** [comment]
I neee some reviewers for the push request ^^, feel free to review it
Pls close

**Comment by maxerbox** [comment]
Fixed pageup-pagedown-zoomin-zoomout issue
