### ISSUE TITLE
Telegram is not work

### ISSUE THREAD

**Issue by tglhteam** [ramboxapp/community-edition#2130]
Telegram does not work, when loading shows a white screen.

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> linux x64 4.15.0-46-generic

**Comment by Perflyst** [comment]
It is working here (maybe because I just updated rambox and not freshly installed), but I got 
```
The message is not supported on your version of Telegram Web. Update the app to view: web.telegram.org.
```
lately.
