### ISSUE TITLE
Rambox crashes after 0.6.4 update

### ISSUE THREAD

**Issue by hokkenmeijer** [ramboxapp/community-edition#2133]
- After update to 0.6.4
- Opening Rambox, starts normal
- Contains 1 Whatsapp and 2 Gmail accounts
- Minimize Rambox
- After, say 15 minutes, maximize Rambox and crash occurs

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 6.1.7601

**Comment by 613TheEvil** [comment]
I get the same, more or less. I am not sure what triggers it but it's definitely Whatsapp related.

**Comment by xannasavin** [comment]
+1

**Comment by 613TheEvil** [comment]
I am this close to reverting to the previous version of Rambox, better not showing the profile pics in large mode than random crashes...

**Comment by xannasavin** [comment]
just saw after crash, the process stays open several times and takes almost 80% CPU!

**Comment by hokkenmeijer** [comment]
It even crashes when minimalized. And 8 service instances of Rambox were running. 0.6.3 never gave problems. How to prevent it to update?

**Comment by dyominick** [comment]
Same problem. Whenever I get a new message to Whatsapp or Telegram while the app is minimized, it crashes. Had to roll back to 0.6.3.

**Comment by 613TheEvil** [comment]
I installed 0.6.3 and I prevented it from updating. Whatsapp doesn't crash us, but Facebook never remembers me and I have to log in every time, again and again. Any solution?

**Comment by maxerbox** [comment]
Could be related to electron/electron#14655 ,
are you using a proxy ?

**Comment by maxerbox** [comment]
Also, need better logs,
Open rambox.exe folder location
Open a terminal (Win + R > cmd)
Go to that folder location ```cd %Appdata%/...``
Now those commands inside the terminal:
```
> set ELECTRON_ENABLE_LOGGING=true
> set ELECTRON_ENABLE_STACK_DUMPING=true
> rambox 
```
And wait a rambox crash.
When it crash, copy past the logs, with the stack trace

**Comment by dyominick** [comment]
[15304:0325/155132.212:INFO:CONSOLE(62)] "notify", source: https://web.telegram.org/js/app.js (62)
Received fatal exception EXCEPTION_ACCESS_VIOLATION
Backtrace:
        (No symbol) [0x000000013FC46B38]
        (No symbol) [0x000000013FC3A61F]
        GetHandleVerifier [0x0000000141363083+23688275]
        IsSandboxedProcess [0x000000014155CB82+1548402]
        (No symbol) [0x000000013FC6D355]
        (No symbol) [0x000000013FCB8202]
        (No symbol) [0x000000013FCB83FA]
        (No symbol) [0x000000013FCB85E5]
        (No symbol) [0x000000013FCB9036]
        (No symbol) [0x000000013FCB8D44]
        (No symbol) [0x000000013FC7ECEE]
        GetHandleVerifier [0x0000000140F227F9+19229641]
        GetHandleVerifier [0x0000000140F35ED6+19309222]
        GetHandleVerifier [0x0000000140F359D2+19307938]
        GetHandleVerifier [0x0000000140F110AA+19158138]
        IsSandboxedProcess [0x000000014174BF97+3576967]
        IsSandboxedProcess [0x000000014174BE84+3576692]
        IsSandboxedProcess [0x00000001420EE29C+13678476]
        GetHandleVerifier [0x0000000140E14118+18121960]
        (No symbol) [0x000000013FAA3D57]
        IsSandboxedProcess [0x00000001428224B3+21232035]
        BaseThreadInitThunk [0x000000007741571D+13]
        RtlUserThreadStart [0x000000007767385D+29]
[12444:0325/155147.592:ERROR:broker_win.cc(57)] Error reading broker pipe: The pipe has been ended. (0x6D)
[8996:0325/155147.607:ERROR:broker_win.cc(57)] Error reading broker pipe: The pipe has been ended. (0x6D)
[11012:0325/155147.607:ERROR:broker_win.cc(57)] Error reading broker pipe: The pipe has been ended. (0x6D)

**Comment by youngerson** [comment]
having the same issue.

**Comment by maxerbox** [comment]
Is this still happening with the latest version (0.6.6)?

**Comment by hokkenmeijer** [comment]
No issues all morning so far with 0.6.6! Thanks for the update!

**Comment by Gaudenz77** [comment]
Rambox Version 0.6.7 when minimizing window (Woindows 10, latest OS) App shuts down. Does anyone know a fix for this?
Best Gaudenz
