### ISSUE TITLE
Change between Enabled services using "Ctrl"+"pg dn" is not longer working

### ISSUE THREAD

**Issue by estebanq1** [ramboxapp/community-edition#2136]
I can't change from one Enabled service to an other using "Ctrl"+"pg dn" or "Ctrl"+"pg up". In the last version it was possible. Also "Ctrl"+"Tap" only works if I'm on the tab name. Thanks.
	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 10.0.17134

**Comment by maxerbox** [comment]
Dup.
Since chromium's architecture has been reworked, events are not propaged globally anymore. Rambox was using this hack to handle CTRL+TAB, but with the new electron version, it's not working anymore.
A workaround is to handle the events fired by webview.
Fixed in #2138

**Comment by maxerbox** [comment]
I neee some reviewers for the push request ^^, feel free to review it

**Comment by maxerbox** [comment]
Fixed pageup-pagedown-zoomin-zoomout issue
