### ISSUE TITLE
Whatsapp keeps crashing.

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#2137]
After the latest Rambox update, Whatsapp keeps making the program crash. It shows a Whatsapp update, sometimes I do it, sometimes not, but the crashes continue anyway, every few minutes. It's super frustrating.

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 6.1.7601

**Comment by 613TheEvil** [comment]
The error I get from Windows:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Rambox.exe
  Application Version:	0.6.4.4
  Application Timestamp:	5c67161f
  Fault Module Name:	Rambox.exe
  Fault Module Version:	0.6.4.4
  Fault Module Timestamp:	5c67161f
  Exception Code:	c0000005
  Exception Offset:	0000000000276b38
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1032
  Additional Information 1:	9ba3
  Additional Information 2:	9ba3d02b12a58762609aeac3e056912b
  Additional Information 3:	6fa7
  Additional Information 4:	6fa7908d5a3640affff473bbcaa44c51

**Comment by xannasavin** [comment]
just saw after crash, the process stays open several times and takes almost 80% CPU!

**Comment by maxerbox** [comment]
Need better logs, can you try with http://www.windbg.org/ ?

**Comment by maxerbox** [comment]
Open rambox.exe folder location
Open a terminal (Win + R > cmd)
Go to that folder location ```cd %Appdata%/...``
Now those commands inside the terminal:
```
> set ELECTRON_ENABLE_LOGGING=true
> set ELECTRON_ENABLE_STACK_DUMPING=true
> rambox 
```
And wait a rambox crash.
When it crash, copy past the logs, with the stack trace
