### ISSUE TITLE
Click on tray icon no longer shows/hides but shows menu again

### ISSUE THREAD

**Issue by jerry1970** [ramboxapp/community-edition#2143]
On Ubuntu 18.04, Rambox 0.6.3, a click the tray icon opened/closed Rambox. When I wanted to close Rambox, I right-clicked and selected Quit.

Now I installed 0.6.4 and the menu shows again and I have to click Show/Hide.

Was that deliberate? Why the extra click for something I do dozens of times a day?

### Steps to reproduce
1. Start Rambox 0.6.4 with _Display behaviour_ = "Show in Taskbar and Tray Icon" and _When closing the main window_ = "Keep in tray".
2. Close the main window.
3. Click the tray icon.

### Behaviour in 0.6.3 (as expected, yay!)
Show/hide the main window

### Behaviour in 0.6.4
Shows tray icon menu with "Show/hide window" and "Quit"

### Expected behavior
Work like in 0.6.3.

### ENVIRONMENT

> Rambox: v0.6.4
> OS: Ubuntu 18.04
> Arch: x64

**Comment by jerry1970** [comment]
Damn, going back to 0.6.3 shows no tray icon at all anymore...

**Comment by maxerbox** [comment]
Dup #2128
