### ISSUE TITLE
Since the last update Rambox keeps constantly crashing after short time

### ISSUE THREAD

**Issue by xannasavin** [ramboxapp/community-edition#2146]
Not much to describe... Rambox runs a while and crashes then. happens since I updated to the latest version...

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 6.1.7601

**Comment by xannasavin** [comment]
just saw after crash, the process stays open several times and takes almost 80% CPU!

**Comment by 613TheEvil** [comment]
I am going back to 0.6.3 right now, let's hope for a fix soon. It's impossible to stand it as it is.

**Comment by 613TheEvil** [comment]
It keeps updating to 0.6.4 ffs. How to stop auto-update?

**Comment by maxerbox** [comment]
Run rambox with `--without-update` to stop updates.
Edit your shortcut by appending this argument.

**Comment by thowmeng** [comment]
So I am not the only one facing the hang and crashing.

For me, Rambox hang is cause by Yahoo mail, I have 2 Yahoo mail, Rambox keep loading Yahoo Mail when I click the tab.

Hope the info help to identify the issue.

**Comment by philipsr** [comment]
Also crashing with 0.6.4
Active services are: Telegram, Messenger, 2x Whatsapp
Inactive service: Whatsapp

> Rambox 0.6.4
> Electron 3.1.4
> win32 x64 6.1.7601

**Comment by r0zb0t** [comment]
Hello, rambox this is also happening with me, the issue seems focused on WhatsApp

	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 6.1.7601

**Comment by Salvaroc** [comment]
Same here. First time I use Rambox. Windows 7.
After crash, there are several precesses consuming +80% of my CPU.

**Comment by 613TheEvil** [comment]
I installed 0.6.3 and blocked the automatic update. The problem now is, my Facebook keeps asking me to log in whenever I start Rambox, even when I ask it to remember me. Oh well, it's not a huge problem, just annoying.

**Comment by YuriyPonomarov** [comment]
I have faced the same issue. It keeps crushing all the time and after crash the processor is loaded at 100% by rambox processes which I have to delete manually. I also guess that the issue is caused by WhatsApp.

**Comment by maxerbox** [comment]
Open rambox.exe folder location
Open a terminal (Win + R > cmd)
Go to that folder location ```cd %Appdata%/...``
Now those commands inside the terminal:
```
> set ELECTRON_ENABLE_LOGGING=true
> set ELECTRON_ENABLE_STACK_DUMPING=true
> rambox 
```
And wait a rambox crash.
When it crash, copy past the logs here, with the stack trace

**Comment by Gaudenz77** [comment]
Rambox Version 0.6.7 when minimizing window (Woindows 10, latest OS) App shuts down. Does anyone know a fix for this? 
Best Gaudenz
