### ISSUE TITLE
Change of UX - renaming the tab 

### ISSUE THREAD

**Issue by yami12376** [ramboxapp/community-edition#2147]
Regarding https://github.com/ramboxapp/community-edition/issues/1534
"How do you rename a tab? I created a tab and then accidently set it's name incorrectly and I would like to change it but I don't see how."

Renaming should be available on right clicking the tab also.
Please fix this UX.

Thanks

**Comment by maxerbox** [comment]
You can go in the rambox tab. Click on the small gear at the left of the service. Here you can rename your service.

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
