### ISSUE TITLE
Js fallo

### ISSUE THREAD

**Issue by sabroso** [ramboxapp/community-edition#215]
Tiene fallos con el js y ademas cada ves q lo inicio tengo que configurarlo para que no inicie con windows

## 

> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
¿Podrías dar más información de porque tiene "fallos el JS"?

Lo del inicio, ya fue reportado en otro ticket.

**Comment by sabroso** [comment]
/El programa se traba muy a menudo/

**Comment by saenzramiro** [comment]
Por favor, necesito más información para poder reproducir el problema y solucionarlo.

Si puedes grabar un video cuando "se traba", sería útil.

**Comment by sabroso** [comment]
/Ahi te mando una imagen del problema/
