### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by jonathan-realman** [ramboxapp/community-edition#2150]
Can't tell you how to reproduce it easily, but as soon as I clock on a server or a PM the discord client crashes. 

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> linux x64 5.0.2-arch1-1-ARCH

**Comment by maxerbox** [comment]
What do you mean by discord client ? Rambox ? Or just the discord tab ?

**Comment by jonathan-realman** [comment]
in this case it's just the tab, I have also opened an issue with the
Discord team. It seams like you guys got no fault in this.

**Comment by saenzramiro** [comment]
@jonathan-realman Any news on this? Was Discord problem?
