### ISSUE TITLE
mode "do not disturb" is not working anymore.

### ISSUE THREAD

**Issue by Amatcha-Boanerges** [ramboxapp/community-edition#2151]
-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 10.0.17134

**Comment by maxerbox** [comment]
What do you mean by do nto disturb ? Do you mean notifications or sounds ? It's working properly on Debian Gnome

**Comment by Amatcha-Boanerges** [comment]
Hello,

I found how to deal with the issue, but here is how I describe the problem.

Before the last update, I was able to activate or deactivate the « do not disturb » mode using the f1 key from anywhere in Rambox (either on a social network tab, email tab or on the main Rambox tab).
Now, I was trying from the social network tab (WhatsApp), but is wasn’t working. This is why I sent the issue. Then, I went to the main tab of Rambox and I was able to do activate or deactivate the « do not disturb » mode .

Best regards,

Jacques Boanerges Yannick AMATCHA
MEST Accra Incubator EIT, Huawei Seeds For the Future CI 2016-2017, Member of Frogans Community CI,  IT consultant, Community manager, Master degree in Information System Engineering and Management of Computer Project
Mobile : +225 01378269/+225 79829893
Email : jacquesyann@live.fr / jacques.amatcha@groupecerco.com / jacques.amatcha@meltwater.org
INSTITUT CERCO Côte d'Ivoire http://www.groupecerco.com/bj/

________________________________
De : Simon Sassi <notifications@github.com>
Envoyé : Monday, March 18, 2019 5:35:19 PM
À : ramboxapp/community-edition
Cc : Amatcha-Boanerges; Author
Objet : Re: [ramboxapp/community-edition] mode "do not disturb" is not working anymore. (#2151)


What do you mean by do nto disturb ? Do you mean notifications or sounds ? It's working properly on Debian with Gnome

**Comment by maxerbox** [comment]
It should be fixed in #2138 
Consider closing this issue.

**Comment by Amatcha-Boanerges** [comment]
Great !
Thank you very much for your quick answer and assistance.
