### ISSUE TITLE
Mattermost: Certification Warning since 0.6.4

### ISSUE THREAD

**Issue by riede** [ramboxapp/community-edition#2153]
Since 0.6.4 Mattermost doesn't work anymore with a self-signed certificate. You only see a white screen and while reloading the tab you can see "Certification Warning" in the status bar. Everything works fine in the browser. Downgrading to 0.6.3 fix the problem, too. While using a non-self-signed certificate everything also works fine.

### Steps to reproduce

1. Use Mattermost-Plugin with a server that uses a self-signed certificate.

### Expected behavior
You should be able to login or use Mattermost

### Actual behavior
Only a white screen is shown.

### ENVIRONMENT

> Rambox: v0.6.4

> OS: macOS Mojave 10.14.3

**Comment by maxerbox** [comment]
That's up to chromium security policy I guess (since chromium has been updated).
That's normal to not accept self signed certificate.
What we should consider is to implement a 'allow bad certificates' option

**Comment by riede** [comment]
Sounds good.

**Comment by riede** [comment]
Is there a way to use self-cigned certificates in newer versions?

**Comment by fvulich** [comment]
Does the issue persist in v0.7.3?

**Comment by riede** [comment]
> Does the issue persist in v0.7.3?
I don't know. Meanwhile I use a let’s encrypt certificate.
