### ISSUE TITLE
rightclick -> paste is not working

### ISSUE THREAD

**Issue by NLDev** [ramboxapp/community-edition#2154]
### Steps to reproduce

1. Have multiple tabs
2. Copy something
3. Focus textbox
4. Paste using rightclick -> paste (tested on discord)

### Expected behavior

The text gets pasted to the text box

### Actual behavior

The text gets pasted to a textbox on a different tab

### ENVIRONMENT

Version: 0.6.4
Platform: linux (x64) - Ubuntu 16.04
Electron: 3.1.4
Chromium: 66.0.3359.181
Node: 10.2.0

### Infos

Copying with CTRL + C seems to work. Copying by using Righ-click -> Copy does NOT work. It shows the context menu and the copy button, but upon pasting the "paste" entry is greyed out and CTRL + V does nothing. When text is copied using CTRL + C, pasting by using CTRL + V appears to work. But rightclick -> paste results in the issue describe above

This applies to Text and Images - in the attached GIF I used CTRL + V first, which works. Then I paste using rightclick. 

![screen-blur](https://user-images.githubusercontent.com/22935000/54531339-55c59180-4985-11e9-9c6d-0626c7f6de38.gif)

**Comment by maxerbox** [comment]
Yeah, I can confirm

**Comment by dz-igner** [comment]
confimed

**Comment by kenfallon** [comment]
I did some investigation and found the following in the man page for xsel

> The X server maintains three selections, called PRIMARY, SECONDARY and CLIPBOARD. The PRIMARY selection is conventionally used to implement copying and pasting via the middle mouse button. The SECONDARY and CLIPBOARD selections are less frequently used by application programs.

I did some tests showing what is happening in these three 'selections'
1. Copy from console using Right Click -> Copy Selection
```
clear;for i in primary secondary clipboard;do echo "⋄ ${i}";xsel --${i};echo "";done
⋄ primary
This is some console text copied using Right Click -> Copy Selection
⋄ secondary

⋄ clipboard
This is some console text copied using Right Click -> Copy Selection
```
2. Copy text from Rambox/Flowdock using centre click on the mouse
```
clear;for i in primary secondary clipboard;do echo "⋄ ${i}";xsel --${i};echo "";done
⋄ primary
This is some text in Rambox/Flowdock copied using centre click on the mouse
⋄ secondary

⋄ clipboard
This is some console text copied using Right Click -> Copy Selection
```
3. Copy text from Rambox/Flowdock using Right Click -> Copy
```
clear;for i in primary secondary clipboard;do echo "⋄ ${i}";xsel --${i};echo "";done
⋄ primary
This is some text in Rambox/Flowdock copied using Right click Copy
⋄ secondary

⋄ clipboard
This is some console text copied using Right Click -> Copy Selection
```
Based on the man page, it would appear that Rambox is updating the correct selection of PRIMARY.

**Comment by NLDev** [comment]
As you stated, the input is written correctly to `primary`. So it is indeed there. I doubt Rambox tries to read from `clipboard` instead of `primary` (this is just an assumption tho) because the text does get pasted. But unfortunately to the wrong tab. So I doubt it's a problem with `xsel`, but rather with the overlapping layers / tabs. 

Either way, this is just an assumption. I haven't looked into that yet. So thanks for the heads up!

**Comment by saenzramiro** [comment]
This will be fixed in next release. Thank you guys.
