### ISSUE TITLE
No notifications since update 

### ISSUE THREAD

**Issue by winn-digo** [ramboxapp/community-edition#2155]
-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 10.0.17763

**Comment by maxerbox** [comment]
Try
```js
new Notification("test")
```
in the developer console of a service.

By the way, we need more infos (which service are you using ?)

**Comment by lilas97** [comment]
It's ok for that but I mean the notification in red

**Comment by winn-digo** [comment]
Ok for that, but I was talking about the red notifications
I use Messenger, Gmail and Linkedin. It works on Linkedin only.

![notifications](https://user-images.githubusercontent.com/48684430/54612755-d05fe100-4a59-11e9-8bd2-15a74b92bf49.png)

**Comment by maxerbox** [comment]
Gmail can be fixed with #2034 
Pls, close this issue, and create a new one appriopriated.
