### ISSUE TITLE
Bad wiki documentation for « Add a Custom Service »

### ISSUE THREAD

**Issue by LuNiKoFf** [ramboxapp/community-edition#2157]
In this page : https://github.com/ramboxapp/community-edition/wiki/Add-a-Custom-Service

You should replace :
```
function updateBadge(e) {
    e >= 1 ? document.title = "(" + e + ") " + originalTitle : document.title = originalTitle
}
var originalTitle = document.title;
```

By
```
function updateBadge(a) {
   a>=1?rambox.setUnreadCount(a):rambox.clearUnreadCount();
}
```

The first one doesn't work. Certainly too old ?
I found the second working code by using debug tools on another service.

**Comment by maxerbox** [comment]
Yeah indeed
