### ISSUE TITLE
0.4.1 > app.asar makes problems

### ISSUE THREAD

**Issue by Vidarius** [ramboxapp/community-edition#216]
today i would test 0.4.1 - from 0.3.0 bevor...

i get the problem at the install and the portable version with the same error msg: problems with "app.asar"

> after i put the old app.asar (version 0.3.0) in the folder and overwrite the new version with there - no more problems

![error screenshot](https://abload.de/img/rambox2uqlq.jpg)

> Rambox: v0.4.1 @the moment
> OS: Win10Ent
> Arch: x64

sry for my bad english ;)

**Comment by saenzramiro** [comment]
Yes, I a known bug for portables. Please download the installable version for 64bits.

https://getrambox.herokuapp.com/download/win32_x64

In next version I will fix this.
