### ISSUE TITLE
Rambox shortcuts not working

### ISSUE THREAD

**Issue by LaserPiratePewPew** [ramboxapp/community-edition#2161]
My Ctrl+1,2,3,4,tab etc buttons don't work somehow

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 10.0.17134

**Comment by cesalazar** [comment]
Same issue. Impossible to switch tabs using Ctrl+number/tab/pagedown/pageup. It does work _once_ if the focused tab is Rambox settings (first tab).

	> Rambox 0.6.4
	> Electron 3.1.4
	> linux x64 4.14.101-1-MANJARO

**Comment by maxerbox** [comment]
Dup!  Fixed by #2138 
Consider closing this issue

**Comment by maxerbox** [comment]
Fixed pageup-pagedown-zoomin-zoomout issue
