### ISSUE TITLE
ERROR AFTER UPDATE

### ISSUE THREAD

**Issue by ascer0** [ramboxapp/community-edition#2162]
### Steps to reproduce

1. START RAMBOX
2.  LEAVE FOR A MINUTES
3. OPEN WHATSAPP AND MESSENGER
4. WHEN RAMBOX LOAD NOTIFICATIONS OR NEW MESSAGES.. CLOSE AND DEBUG..
5. IN TASK MANAGER SHOW ACTIVE PROCESS AND CONSUMPTION 100% OF PROCESSOR

### Expected behavior

AFTER DEBUG .. CLOSE ANS TERMINATE PROCESS (RAMBOX) OR PROCESSOR WORK WITH 100%
### ENVIRONMENT

DONT ANY ERROR BEFORE THE UPDATE

> Rambox: LATEST WITH AUTOUPDATE

> OS: WINDOWS 7

> Arch: X64

**Comment by S3x0r** [comment]
fix this crap pls 0.6.4 not working

**Comment by maxerbox** [comment]
We need better logs.
Can you start rambox in a terminal with the env variable :
```
> set ELECTRON_ENABLE_LOGGING=true
> set ELECTRON_ENABLE_STACK_DUMPING=true
> rambox 
```

**Comment by ascer0** [comment]
i'm on.. windows 7 environment please tell me step by step to enable detailed logs!

**Comment by maxerbox** [comment]
Open rambox.exe folder location
Open a terminal (Win + R > cmd)
Go to that folder location ```cd %Appdata%/...``
Now those commands inside the terminal:
```
> set ELECTRON_ENABLE_LOGGING=true
> set ELECTRON_ENABLE_STACK_DUMPING=true
> rambox 
```
And wait a rambox crash.
When it crash, copy past the logs, with the stack trace

**Comment by cgarde89** [comment]
> Open rambox.exe folder location
> Open a terminal (Win + R > cmd)
> Go to that folder location ```cd %Appdata%/...``
> Now those commands inside the terminal:
> 
> ```
> > set ELECTRON_ENABLE_LOGGING=true
> > set ELECTRON_ENABLE_STACK_DUMPING=true
> > rambox 
> ```
> And wait a rambox crash.
> When it crash, copy past the logs, with the stack trace

this is my log

`Received fatal exception EXCEPTION_ACCESS_VIOLATION
Backtrace:
        (No symbol) [0x000000013FD86B38]
        (No symbol) [0x000000013FD7A61F]
        GetHandleVerifier [0x00000001414A3083+23688275]
        IsSandboxedProcess [0x000000014169CB82+1548402]
        (No symbol) [0x000000013FDAD355]
        (No symbol) [0x000000013FDF8202]
        (No symbol) [0x000000013FDF83FA]
        (No symbol) [0x000000013FDF85E5]
        (No symbol) [0x000000013FDF9036]
        (No symbol) [0x000000013FDF8D44]
        (No symbol) [0x000000013FDBECEE]
        GetHandleVerifier [0x00000001410627F9+19229641]
        GetHandleVerifier [0x0000000141075ED6+19309222]
        GetHandleVerifier [0x00000001410759D2+19307938]
        GetHandleVerifier [0x00000001410510AA+19158138]
        IsSandboxedProcess [0x000000014188BF97+3576967]
        IsSandboxedProcess [0x000000014188BE84+3576692]
        IsSandboxedProcess [0x000000014222E29C+13678476]
        GetHandleVerifier [0x0000000140F54118+18121960]
        (No symbol) [0x000000013FBE3D57]
        IsSandboxedProcess [0x00000001429624B3+21232035]
        BaseThreadInitThunk [0x000000007765571D+13]
        RtlUserThreadStart [0x00000000777B385D+29]
`

**Comment by ascer0** [comment]
here my full log .. 


C:\Users\ascer0\AppData\Local\Programs\Rambox>set ELECTRON_ENABLE_LOGGING=true

C:\Users\ascer0\AppData\Local\Programs\Rambox>set ELECTRON_ENABLE_STACK_DUMPING=
true

C:\Users\ascer0\AppData\Local\Programs\Rambox>rambox

C:\Users\ascer0\AppData\Local\Programs\Rambox>
[6576:0326/111517.150:INFO:CONSOLE(1)] "USER NOT LOGGED IN", source: file:///C:/
Users/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111517.580:INFO:CONSOLE(1)] "Checking for updates...", source: file:/
//C:/Users/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111517.992:INFO:CONSOLE(1)] "Start loading...", source: file:///C:/Us
ers/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111518.037:INFO:CONSOLE(1)] "Start loading...", source: file:///C:/Us
ers/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111518.097:INFO:CONSOLE(1)] "Your version is the latest. No need to u
pdate.", source: file:///C:/Users/ascer0/AppData/Local/Programs/Rambox/resources
/app.asar/app.js (1)
[6576:0326/111518.861:INFO:CONSOLE(1)] "WHATSAPP - JS Injected to Detect New Mes
sages", source: file:///C:/Users/ascer0/AppData/Local/Programs/Rambox/resources/
app.asar/app.js (1)
[6576:0326/111518.862:INFO:CONSOLE(1)] "whatsapp", source: file:///C:/Users/asce
r0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111518.863:INFO:CONSOLE(1)] "function checkUnread(){const elements =
document.querySelectorAll('.CxUIE, .unread');let count = 0;for (let i = 0; i < e
lements.length; i++) {if (elements[i].querySelectorAll('*[data-icon="muted"]').l
ength === 0) {count++;}}updateBadge(count);}function updateBadge(count){if(count
 && count>=1){rambox.setUnreadCount(count);}else{rambox.clearUnreadCount();}}set
Interval(checkUnread, 1e3);(async()=>{try{const a=await window.navigator.service
Worker.getRegistrations();for(const b of a)b.unregister()}catch(a){}})();", sour
ce: file:///C:/Users/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app
.js (1)
[6576:0326/111518.864:INFO:CONSOLE(1)] "console.groupEnd", source: file:///C:/Us
ers/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111519.255:WARNING:quota_manager.cc(1632)] No storage quota provided
in QuotaSettings.
[6576:0326/111519.305:INFO:CONSOLE(1)] "var originalTitle=document.title;Object.
defineProperty(document,"title",{configurable:!0,set:function(a){null===a.match(
new RegExp("[(]([0-9ÔÇó]+)[)][ ](.*)","g"))&&a!==originalTitle||(document.getEle
mentsByTagName("title")[0].innerHTML=a)},get:function(){return document.getEleme
ntsByTagName("title")[0].innerHTML}});", source: file:///C:/Users/ascer0/AppData
/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111519.306:INFO:CONSOLE(1)] "console.groupEnd", source: file:///C:/Us
ers/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111522.925:INFO:CONSOLE(25)] "Internet Connection", source: file:///C
:/Users/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/index.html (25)
[6576:0326/111522.926:INFO:CONSOLE(25)] "Internet Connection", source: file:///C
:/Users/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/index.html (25)
[6576:0326/111631.648:INFO:CONSOLE(1)] "Start loading...", source: file:///C:/Us
ers/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111631.891:INFO:CONSOLE(1)] "Start loading...", source: file:///C:/Us
ers/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111634.265:INFO:CONSOLE(1)] "Start loading...", source: file:///C:/Us
ers/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111634.274:INFO:CONSOLE(1)] "Start loading...", source: file:///C:/Us
ers/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111634.282:INFO:CONSOLE(1)] "Start loading...", source: file:///C:/Us
ers/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111634.290:INFO:CONSOLE(1)] "Start loading...", source: file:///C:/Us
ers/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
[6576:0326/111634.295:INFO:CONSOLE(1)] "Start loading...", source: file:///C:/Us
ers/ascer0/AppData/Local/Programs/Rambox/resources/app.asar/app.js (1)
Received fatal exception EXCEPTION_ACCESS_VIOLATION
Backtrace:
        (No symbol) [0x000000013F836B38]
        (No symbol) [0x000000013F82A61F]
        GetHandleVerifier [0x0000000140F53083+23688275]
        IsSandboxedProcess [0x000000014114CB82+1548402]
        (No symbol) [0x000000013F85D355]
        (No symbol) [0x000000013F8A8202]
        (No symbol) [0x000000013F8A83FA]
        (No symbol) [0x000000013F8A85E5]
        (No symbol) [0x000000013F8A9036]
        (No symbol) [0x000000013F8A8D44]
        (No symbol) [0x000000013F86ECEE]
        GetHandleVerifier [0x0000000140B127F9+19229641]
        GetHandleVerifier [0x0000000140B25ED6+19309222]
        GetHandleVerifier [0x0000000140B259D2+19307938]
        GetHandleVerifier [0x0000000140B010AA+19158138]
        IsSandboxedProcess [0x000000014133BF97+3576967]
        IsSandboxedProcess [0x000000014133BE84+3576692]
        IsSandboxedProcess [0x0000000141CDE29C+13678476]
        GetHandleVerifier [0x0000000140A04118+18121960]
        (No symbol) [0x000000013F693D57]
        IsSandboxedProcess [0x00000001424124B3+21232035]
        BaseThreadInitThunk [0x00000000779959CD+13]
        RtlUserThreadStart [0x0000000077AF383D+29]
[8824:0326/111756.578:ERROR:broker_win.cc(57)] Error reading broker pipe: The pi
pe has been ended. (0x6D)
[14668:0326/111756.583:ERROR:broker_win.cc(57)] Error reading broker pipe: The p
ipe has been ended. (0x6D)

After crash occur and say debug.. or close... i select close but the process it still present .. i have a capture off process 

![Capture](https://user-images.githubusercontent.com/20917525/55018946-84f98580-4fb9-11e9-9760-aac8b4d35849.JPG)

**Comment by maxerbox** [comment]
Are you using a proxy ?

**Comment by ascer0** [comment]
no i dont use a proxy!

**Comment by maxerbox** [comment]
Is this still happening with the latest version (0.6.6)?
