### ISSUE TITLE
0.6.3 apps don't store log in data

### ISSUE THREAD

**Issue by jerry1970** [ramboxapp/community-edition#2163]
Since 0.6.4 had the tray icon problem, I downloaded and re-installed 0.6.3. Now, every time I start Rambox, I have to log in to Messenger, Slack, and Teams. They don't even have my email address stored, I have to type it in every time. Messenger's "log on automatically" doesn't work. It doesn't happen with Whatsapp - I am logged in automatically there.

Rambox knows my apps/tabs so Rambox stores those settings correctly. I know Messenger, Slack, and Teams are web apps inside a Rambox container and possibly don't have anything to do with Rambox, but does anyone recognise this?

Thanks

**Comment by maxerbox** [comment]
It's because you chromium got updated I guess.
Delete everything in you webview partition.

Linux: they are located under home/.config/rambox/partitions

Windows: maybe in appdata/roaming/rambox.

**Comment by jerry1970** [comment]
That did the trick (I tried to remove only the directories starting with `messenger` and `teams` and that alreday worked), thanks!!
