### ISSUE TITLE
Uable to open app by double-click in taskbar in last version 0.6.4

### ISSUE THREAD

**Issue by jhquentin** [ramboxapp/community-edition#2165]
Hi,
after upgrade to latest version 0.6.4, I am not able to open app from taskbar by double-click.
Please can you fix it?
Thank you

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> linux x64 4.20.16-200.fc29.x86_64

**Comment by ohaessler** [comment]
Same issue on RHEL 7.6 (Gnome 3.28.2). 

0.6.3 - I can click the tray icon with the left mouse button to show the window (not hide again)
0.6.4 - clicking on the tray icon shows the right mouse click menu (Show/Hide window, Quit)

It would be perfect if a left click on the tray icon could show the window and another left mouse click could hide the window again.

**Comment by maxerbox** [comment]
Dup #2128
Can't be fixed, electron issue.
We need another tray lib.
Please close
