### ISSUE TITLE
Websites don't take Rambox language preference into account anymore

### ISSUE THREAD

**Issue by oncle-anatole** [ramboxapp/community-edition#2169]
Since the last update, websites which would usually display in my selected language in Rambox now default to English.
For instance, before webapps such as Android Messages or Synology ones would automatically display in my selected language. Now they are all in english.

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 10.0.16299

**Comment by Corchoneitor** [comment]
Hi @oncle-anatole!

Most of webapps take language from the "Windows display language". I just tested it with Android Messages, and it only changes the language according to "Windows display language", not the language selected in Rambox. Rambox language is for the Rambox User Interface only.

Are you sure this was behaving as you said in previous versions? Could it be you changed the Windows display language there?

**Comment by oncle-anatole** [comment]
I really don't know what happened then but it seems resolved just after I updated to 0.6.6, so that's great (did you test for this behavious with version 0.6.4?). Until the update it was stuck to english though and my windows display language was set to french and I don't even have another display language set as a secondary one. I somehow figured that, like a web browser, websites would use the browser preferences to choose what language to display, but it seems that I was wrong.

**Comment by maxerbox** [comment]
> I somehow figured that, like a web browser, websites would use the soft preferences (through an HTTP language header of some sort) to choose what language to display, but it seems that I was wrong.

Of course it will, but more sophisticated websites also locate you with your ip

**Comment by maxerbox** [comment]
Even if it was not a default behaviour before, it is now, thanks to #2219
