### ISSUE TITLE
After updating, the program constantly crashing

### ISSUE THREAD

**Issue by 2671342** [ramboxapp/community-edition#2172]
After updating, the program constantly began to crash, after receiving several messages in WhatsApp. At the same time, the processor load is 100%

Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	Rambox.exe
  Версия приложения:	0.6.4.4
  Отметка времени приложения:	5c67161f
  Имя модуля с ошибкой:	Rambox.exe
  Версия модуля с ошибкой:	0.6.4.4
  Отметка времени модуля с ошибкой:	5c67161f
  Код исключения:	c0000005
  Смещение исключения:	0000000000276b38
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	9ba3
  Дополнительные сведения 2:	9ba3d02b12a58762609aeac3e056912b
  Дополнительные сведения 3:	6fa7
  Дополнительные сведения 4:	6fa7908d5a3640affff473bbcaa44c51

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 6.1.7601

**Comment by norswap** [comment]
Same issue. Additionally, the Rambox process(es) stay active despite the crash message and consume inordinates amount of CPU.

**Comment by maxerbox** [comment]
Open rambox.exe folder location
Open a terminal (Win + R > cmd)
Go to that folder location ```cd %Appdata%/...``
Now those commands inside the terminal:
```
> set ELECTRON_ENABLE_LOGGING=true
> set ELECTRON_ENABLE_STACK_DUMPING=true
> rambox 
```
And wait a rambox crash.
When it crash, copy past the logs, with the stack trace

**Comment by olinWong** [comment]
Same issue across 2 different PC's. Rambox crashes, or hangs a lot between tab switching.

**Comment by 2671342** [comment]
![2019-03-25_12-42-30](https://user-images.githubusercontent.com/45586051/54909528-7c427a00-4efb-11e9-9404-123fe98b702f.png)

**Comment by 2671342** [comment]
Необработанное исключение по адресу 0x000000013FDB6B38 в Rambox.exe: 0xC0000005: нарушение прав доступа при чтении по адресу 0x0000000000000000.
![2019-03-25_12-51-43](https://user-images.githubusercontent.com/45586051/54910132-c7a95800-4efc-11e9-81f4-857f9271e908.png)
![2019-03-25_12-51-10](https://user-images.githubusercontent.com/45586051/54910147-cd06a280-4efc-11e9-954d-345cd854e370.png)

**Comment by maxerbox** [comment]
Could be related to https://github.com/electron/electron/issues/14655 ,
are you using a proxy ?

**Comment by 2671342** [comment]
> are you using a proxy ?
Yes, I use a proxy

**Comment by cgarde89** [comment]
> Open rambox.exe folder location
> Open a terminal (Win + R > cmd)
> Go to that folder location ```cd %Appdata%/...``
> Now those commands inside the terminal:
> 
> ```
> > set ELECTRON_ENABLE_LOGGING=true
> > set ELECTRON_ENABLE_STACK_DUMPING=true
> > rambox 
> ```
> And wait a rambox crash.
> When it crash, copy past the logs, with the stack trace

>> Received fatal exception EXCEPTION_ACCESS_VIOLATION
>> Backtrace:
> >        (No symbol) [0x000000013FD86B38]
> >        (No symbol) [0x000000013FD7A61F]
> >        GetHandleVerifier [0x00000001414A3083+23688275]
> >         IsSandboxedProcess [0x000000014169CB82+1548402]
> >        (No symbol) [0x000000013FDAD355]
> >        (No symbol) [0x000000013FDF8202]
> >        (No symbol) [0x000000013FDF83FA]
> >        (No symbol) [0x000000013FDF85E5]
> >        (No symbol) [0x000000013FDF9036]
> >        (No symbol) [0x000000013FDF8D44]
> >        (No symbol) [0x000000013FDBECEE]
> >        GetHandleVerifier [0x00000001410627F9+19229641]
>         GetHandleVerifier [0x0000000141075ED6+19309222]
>         GetHandleVerifier [0x00000001410759D2+19307938]
>         GetHandleVerifier [0x00000001410510AA+19158138]
>         IsSandboxedProcess [0x000000014188BF97+3576967]
>         IsSandboxedProcess [0x000000014188BE84+3576692]
>         IsSandboxedProcess [0x000000014222E29C+13678476]
>         GetHandleVerifier [0x0000000140F54118+18121960]
>         (No symbol) [0x000000013FBE3D57]
>         IsSandboxedProcess [0x00000001429624B3+21232035]
>         BaseThreadInitThunk [0x000000007765571D+13]
>         RtlUserThreadStart [0x00000000777B385D+29]
>

**Comment by 2671342** [comment]
The official Whatsapp also crashes, apparently this is due to its update and the official refusal to support Windows 7.

**Comment by maxerbox** [comment]
Is this still happening with the latest version (0.6.6)?

**Comment by 2671342** [comment]
> Is this still happening with the latest version (0.6.6)?
Oh, yay! The new version 0.6.6 does not crash. Thank!
