### ISSUE TITLE
Add a confirmation message to enable Do not disturb mode

### ISSUE THREAD

**Issue by samwill** [ramboxapp/community-edition#2173]
After submitting this, noticed that I had accidentally enabled "Do Not Disturb" at some point, so I'm turning this into feedback to have an option to require confirmation before enabling DND since the keyboard shortcut is so close to the "Esc" key on most keyboards. 

~~Only tested Slack, Hangouts, Gmail, Inbox~~

~~### Steps to reproduce~~

~~1. Receive a message in any of the above services with desktop notifications enabled~~

~~### Expected behavior~~

~~A desktop notification will pop up and the global and tab unread counters will update for all services~~

~~### Actual behavior~~

~~The global and tab unread counter will update for Slack and Hangouts, but not Gmail or Inbox. None of the services will receive desktop notification~~

~~### ENVIRONMENT~~

~~> Rambox:  0.6.4~~

~~> OS:  Ubuntu 18.04.2 LTS~~

~~> Arch: x64~~

**Comment by maxerbox** [comment]
There is already a notification saying that do not disturb mode is enabled/disabled

**Comment by TheGoddessInari** [comment]
The notification is very easy to miss. 

It'd be more sensible to have a shortcut that isn't as easy to accidentally press as F1.

That's how I handled it.

**Comment by saenzramiro** [comment]
I think we need to change the color or add a small icon in the Rambox tab, so wherever you are, you can see the state of the DND. Also, we can change the shortcut.

**Comment by mikk150** [comment]
You have to make it super obvious, I always though that rambox does not have audio at all.. Literally make a no sound icon on right on tab bar ask if you wanna enable do not disturb and everything

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
