### ISSUE TITLE
Connection window. Can't get out of the window (no exit button)

### ISSUE THREAD

**Issue by Thomas-D-Ace** [ramboxapp/community-edition#2175]
Bonjour, quand j'appuie sur se connecter et que je ne souhaite pas me connecter. Il m'est impossible de quitter la fenêtre de connexion. Il serait intéressant de fermer cette fenêtre avec un clic à côté.

---

Hello, when I click on 'Connect' and I don't to log in, it's impossible to quit the connection window. It would be interesting if we could close that window.

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> darwin x64 18.2.0

**Comment by maxerbox** [comment]
Translation:
He want a close button on the Connection window.

**Comment by maxerbox** [comment]
What do you mean by connection window ?
Auth0 window ?
Rambox password prompt ?
