### ISSUE TITLE
Fenêtre connexion

### ISSUE THREAD

**Issue by Thomas-D-Ace** [ramboxapp/community-edition#2176]
Bonjour, quand j'appuie sur se connecter et que je ne souhaite pas me connecter. Il m'est impossible de quitter la fenêtre de connexion. Il serait intéressant de fermer cette fenêtre avec un clic à côté.

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> darwin x64 18.2.0

**Comment by maxerbox** [comment]
Dupliqué, merci de fermer l'issue

**Comment by saenzramiro** [comment]
Duplicate #2175
