### ISSUE TITLE
Building rambox on windows, builds but empty window with menu only

### ISSUE THREAD

**Issue by r4dius** [ramboxapp/community-edition#2177]
### Steps to reproduce

1. get 0.6.4 source code
2. remove "zip" steps from "all:win"
3. compile with npm install --no-audit ; npm run all:win
4. run from dist\win-unpacked

### Expected behavior

Normal window

### Actual behavior

It opens but all windows is empty / white except for the menu on top

### ENVIRONMENT

> Rambox: v0.6.4

> OS: Windows 10

> Arch: x64

> node 10.15.3
> jdk 8u201
> ruby 2.6.1-1
> sencha 6.7.0.63

**Comment by BalintFarkas** [comment]
Same here

**Comment by r4dius** [comment]
Manage to get it "working" on a different womputer but it's trying to use media from resources/rambox-build folder in the path where it's installed, not sure why,
so I copied the folder rambox-build that's created at compilation there for now
