### ISSUE TITLE
WhatsApp problem

### ISSUE THREAD

**Issue by Airgreg** [ramboxapp/community-edition#2179]
hello!
Each time I start application, I see message about update WhatsApp.
I clicked and update, but in a time, program suddenly have been shutting down.
This problem persists.

![Clip2net_190326131906](https://user-images.githubusercontent.com/35968817/54989612-f5100780-4fc9-11e9-8e8a-5e2d54d370e2.jpg)
	

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 6.1.7601

**Comment by maxerbox** [comment]
Open a terminal 
Now those commands inside the terminal:
```
> env ELECTRON_ENABLE_STACK_DUMPING=true ELECTRON_ENABLE_LOGGING=true rambox
```
And wait a rambox crash.
When it crash, copy past the logs, with the stack trace

**Comment by maxerbox** [comment]
#2134 dup

**Comment by Airgreg** [comment]
I have a last version of Google Chrome
