### ISSUE TITLE
Disappearing the view

### ISSUE THREAD

**Issue by kzkd8** [ramboxapp/community-edition#2180]
When I tried to upload file on Chatwork, the view suddenly disappears. The icon on the dock can be seen, but it can actually unable to see and use it.

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> darwin x64 18.2.0

**Comment by maxerbox** [comment]
Can you send a gif, showing what's happening ?

**Comment by kzkd8** [comment]
It shows "Rambox" on the menu bar and docking station, but the view window
cannot be seen on the screen.
Even if I click the menu and preferences, nothing happens. It's just
disappeared.
I uninstalled the software, put all setting and fixed, but happens after
few days.

https://gyazo.com/24ce11f10422da7b62cc8a0441e00d76

**Comment by saenzramiro** [comment]
@kzkd8 Can you please show to us a GIF when you are in Chatwork and upload the file?

**Comment by tobbi** [comment]
I am / was experiencing the same issue. I fixed it by deleting my config.json file. 

You can reproduce the issue by restoring it with these contents, restarting Rambox and double-clicking the menu bar in OS X.

This is the config.json file:
https://gist.github.com/tobbi/d1dd2830f155cc6cd2dc502b7eeb271d

**Comment by Corchoneitor** [comment]
Thanks @tobbi! We'll have a look at this.

**Comment by fvulich** [comment]
Does this issue persist in v0.7.3?

**Comment by tobbi** [comment]
For me this appears to be fixed. But, I'd rather have other people chime in as well to make sure it's really fixed.

**Comment by tobbi** [comment]
I'm sorry to report that the issue just re-appeared. So, it is not fixed.

**Comment by fvulich** [comment]
It seems that somehow the width and height are wrongly saved 
![image](https://user-images.githubusercontent.com/46904390/77429811-f892c600-6db8-11ea-8251-c2e6e6f36e29.png)
Please close Rambox, and delete the config.json
We couldn't reproduce this issue, if you find a way to reproduce it, please share it with us.
Also, we just released v0.7.4 could you test it there?

**Comment by tobbi** [comment]
I tested it again with 0.7.4 and was able to reproduce it. However, only once. After deleting the config.json and restarting, it goes back to working for a while.

I'll *try* to find steps to reproduce.
