### ISSUE TITLE
Crazy CUT and PASTE with mouse bug

### ISSUE THREAD

**Issue by retro-source** [ramboxapp/community-edition#2181]
### Steps to reproduce

1. right click with mouse+paste on telegram paste on wrong windows ie messenger
2. or right click with mouse+paste does not work at all in 0.6.4 linux x64
3. 0.6.3 linux x64 works as expected

### Expected behavior

to cut and paste with ctrl+v to works same with mouse in same window
in 0.6.3 this works

### Actual behavior
in 0.6.4 cut and past with right clickm mouse +paste does not work or it copy in wrong window,
in my case in messenger ?!?

### ENVIRONMENT

Linux x64

> Rambox: v0.6.4

> OS: Linux 5.0.4

> Arch: x64

**Comment by maxerbox** [comment]
Dup, #2154
