### ISSUE TITLE
Unable to hear voice messages (Whatsapp & Telegram)

### ISSUE THREAD

**Issue by mbnoimi** [ramboxapp/community-edition#2182]
Hi,

I can record and send voice messages without any problem while I'm unable to hear any played message whether I sent or received,

### ENVIRONMENT

> Rambox: v0.6.4

> OS: Linux Mint 19.1 XFCE

> Arch: x64

### PREFERENCES

![image](https://user-images.githubusercontent.com/284547/55021911-9dde5700-500a-11e9-832c-c3af6c43452e.png)

![image](https://user-images.githubusercontent.com/284547/55021981-bbabbc00-500a-11e9-9eb2-71dbfcbd662c.png)

**Comment by maxerbox** [comment]
Is do not disturb mode enabled ?

**Comment by mbnoimi** [comment]
@maxerbox no "do not disturb" mode is disabled

![image](https://user-images.githubusercontent.com/284547/55023248-6a50fc00-500d-11e9-9799-985d4deb6b2c.png)

**Comment by maxerbox** [comment]
I mean this:
![image](https://user-images.githubusercontent.com/12765875/55023342-dbd47e80-4ffc-11e9-9251-81b5e53c2d1f.png)

**Comment by mbnoimi** [comment]
@maxerbox Oops, silly me it's enabled!
