### ISSUE TITLE
GroupMe will no longer load in tab after recent update.

### ISSUE THREAD

**Issue by jovanie** [ramboxapp/community-edition#2184]
### Steps to reproduce

1. Add GroupMe as a new chat service
2. Navigate to GroupMe chat tab
3. Verify in another browser that you can load GroupMe's web app at https://web.groupme.com/signin

### Expected behavior

Expected to be greeted with the sign in dialog for GroupMe after initial loading logo

### Actual behavior

Persistent loading logo. It's either frozen or failing to load the site.

### ENVIRONMENT

> Version: 0.6.4
> Platform: linux (x64)
> Electron: 3.1.4
> Chromium: 66.0.3359.181
> Node: 10.2.0

Also tried on a Windows 10 Laptop running the most recent update.

**Comment by jovanie** [comment]
Developer console in Rambox reads:
`Failed to load resource: the server responded with a status of 404 (Not Found)
signin:1 Refused to execute script from 'https://d2xk3mdboeujlo.cloudfront.net/javascripts/static_application-1553275813.en.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
bugsnag-2.min.js:1 [Bugsnag] Ignoring cross-domain script error. See https://bugsnag.com/docs/notifiers/js/cors
angular.js:2034 Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.5.3/$injector/nomod?p0=groupme
    at angular.js:38
    at angular.js:2034
    at b (angular.js:1958)
    at Object.module (angular.js:2032)
    at signin:108`

**Comment by maxerbox** [comment]
dup #2149
