### ISSUE TITLE
Icon in notification area does not toggle the app on Linux

### ISSUE THREAD

**Issue by jpt-avaleo** [ramboxapp/community-edition#2185]
### Steps to reproduce

1. On Manjaro Linux with gnome click on Rambox icon in notification area 
![image](https://user-images.githubusercontent.com/35026733/55164616-3e985800-516c-11e9-95e6-b624850a3cc8.png)

### Expected behavior

Rambox window toggles
### Actual behavior

Nothing happens 
### ENVIRONMENT

> Rambox: v0.6.4

> OS: Linux Manjaro

> Arch: x64

**Comment by maxerbox** [comment]
Related to #2128, closing
