### ISSUE TITLE
Copy and Paste not reliable

### ISSUE THREAD

**Issue by kenfallon** [ramboxapp/community-edition#2186]
Connect to Flowdock, copy some text using either Right Click->Copy, Ctrl_C or Ctl+Insert
Try and paste and it fails to enter the clipboard.
Using the LXQT desktop.

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> linux x64 5.0.3-200.fc29.x86_64

**Comment by maxerbox** [comment]
Related to #2154 closing
