### ISSUE TITLE
Unable to play embedded audio from any tab.

### ISSUE THREAD

**Issue by foofly** [ramboxapp/community-edition#2187]
No embedded audio from any tab.

1. Try to play any embedded audio in any tab.

eg. Playing an embedded Youtube link in a Discord chat.

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 10.0.17134

**Comment by maxerbox** [comment]
Is do not disturb mode enabled ?

**Comment by foofly** [comment]
Yup, I didn't realise this mutes embedded audio also. I'll close this.
