### ISSUE TITLE
Still no audio in whatsapp

### ISSUE THREAD

**Issue by nicolangr** [ramboxapp/community-edition#2188]
Audio in messages and videos still not working like one year ago.
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> linux x64 4.4.0-142-generic

**Comment by maxerbox** [comment]
Is do no disturb mode enabled ?
Is service muted ?

**Comment by nicolangr** [comment]
All sounds are turned on, i tried to disable than enable but still not working.

**Comment by maxerbox** [comment]
Show me a screen of the entire rambox tap (where you add services)

**Comment by nicolangr** [comment]
![rambox1](https://user-images.githubusercontent.com/3909071/55328489-bf1cc880-548c-11e9-93ea-442753d64dc4.jpg)
![rambox_c](https://user-images.githubusercontent.com/3909071/55328490-bf1cc880-548c-11e9-8928-c50158a0efc4.jpg)
Ok, you found the screenshots attacched

**Comment by nicolangr** [comment]
![rambox_c](https://user-images.githubusercontent.com/3909071/55328601-0dca6280-548d-11e9-9034-6af3c7588bcb.jpg)
![rambox1](https://user-images.githubusercontent.com/3909071/55328604-0dca6280-548d-11e9-9ade-8995cb28c782.jpg)

**Comment by nicolangr** [comment]
![rambox1](https://user-images.githubusercontent.com/3909071/55328713-4b2ef000-548d-11e9-8e73-59112a811b27.jpg)
![rambox_c](https://user-images.githubusercontent.com/3909071/55328714-4bc78680-548d-11e9-8c3e-1f964b75a660.jpg)

**Comment by maxerbox** [comment]
![image](https://user-images.githubusercontent.com/12765875/55329799-c8f3fb00-548f-11e9-8b1b-d99d8fb33d78.png)

**Comment by nicolangr** [comment]
Ok, it works, thank you very much
