### ISSUE TITLE
Windows: Unread counter for Slack is only working when not minized to tray

### ISSUE THREAD

**Issue by CombeeMike** [ramboxapp/community-edition#2189]
### Steps to reproduce

1. Minimize Rambox to tray
2. Receive messages in Slack

### Expected behavior

The Rambox tray icon should turn red due to unread messages in Slack.

### Actual behavior

Windows notifications for new messages are shown but the tray icon does not turn red.
When opening Rambox, the unread counter is not shown on the `Slack` tab initially but shows up after some delay.

### ENVIRONMENT

> Rambox: v0.6.4

> OS: Windows 10

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @CombeeMike!

Thanks for your report, happens as you described. Hope it'll be fixed soon.

**Comment by Nastase** [comment]
Same issue here but on MacOS. If Rambox is in background, Slack messages are notified by a standard notification but the dock icon is not updated and does not show the message counter. Other services like Whatsapp or telegram work fine.

**Comment by CombeeMike** [comment]
Should this be fixed in latest version `0.6.7`?
If so, it still happens to me.
