### ISSUE TITLE
android messages has changed URL

### ISSUE THREAD

**Issue by brij1234** [ramboxapp/community-edition#2191]
Android Messages has changed its URL to [https://messages.google.com/web](https://messages.google.com/web)
![image](https://user-images.githubusercontent.com/9251787/55367749-8b599700-54bc-11e9-8e81-9d7afca5136c.png)

**Comment by brij1234** [comment]
Now, it seems like it's redirecting to the new link on its own.

**Comment by viperdriver2000** [comment]
until it will be fixed you can use "_Custom Service".
Name: Android Messages
URL: https://messages.google.com/web
Logo: https://ssl.gstatic.com/images/branding/product/1x/messenger_96dp.png

works for me. hope it will help you too.

**Comment by mrbmi513** [comment]
Contrary to @brij1234 mine does not automatically redirect to the new link, so it will have to be changed in a future release.

**Comment by mrbmi513** [comment]
Mine redirected to the new URL as well after restarting Rambox. Should still put the new URL into the next release.

**Comment by CristhianEcheverry** [comment]
Continue the problem in version 0.6.7
