### ISSUE TITLE
Rambox freezed if a new Message comes via Whatsapp

### ISSUE THREAD

**Issue by gerd1337** [ramboxapp/community-edition#2193]
Since the new version, Rambox freezed if a new Message comes via Whatsapp

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 6.1.7601

**Comment by Corchoneitor** [comment]
Hi @gerd1337 !

Try Rambox 0.6.6 to see if you keep having this issue. Otherwise, let us know for a follow up!

https://github.com/ramboxapp/community-edition/releases/tag/0.6.6

**Comment by gerd1337** [comment]
Hi, 
Thank You!
It is working with the new Release.
