### ISSUE TITLE
cannot attach or drag a file into flowdock

### ISSUE THREAD

**Issue by JoeyG1973** [ramboxapp/community-edition#2194]
In flowdock I cannot attach or drag in a file

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> linux x64 5.0.5-200.fc29.x86_64

**Comment by Corchoneitor** [comment]
Hi @JoeyG1973.

Is this happening in 0.6.6 also?

**Comment by alekseipanin** [comment]
ср, 1 мая 2019 г. в 17:51, no-response[bot] <notifications@github.com>:
