### ISSUE TITLE
Cannot unistall with check off.

### ISSUE THREAD

**Issue by iluyx** [ramboxapp/community-edition#2196]
1. Run Rambox which was installed from snap.
2. Execute Cisco Webex Teams and configure it.
3. Execute Hangouts and configure it.
4. Execute Hangouts Chat without configure it.
5. Try to uninstall it with the check down.
And in this point the Deleting bar just try to uninstall it in loop without a finish. It seems like a bug.

However i check on the mark and the uninstallation go successfully. 

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> linux x64 4.15.0-47-generic

**Comment by Corchoneitor** [comment]
Hi @iluyx, thanks for your report!

@saenzramiro can you check this out?

**Comment by saenzramiro** [comment]
@iluyx What do you mean with "check down"? Please, consider sharing screenshots or a video with us.

**Comment by iluyx** [comment]
One video with it.
[bug_rambox.zip](https://github.com/ramboxapp/community-edition/files/3149707/bug_rambox.zip)

**Comment by BramVer** [comment]
Can confirm this issue, just had it when I tried to remove a Slack workspace.  
If you first disable the service (Home under 'Enabled Services') and then delete it, it will get stuck in an "infinite" (for 10 mins minimum before I killed the app) loop.  

Enabling the service and then deleting it works without issue.

**Comment by Corchoneitor** [comment]
Duplicate #2107 and also fixed in aa1d051.
Let's wait next release.
