### ISSUE TITLE
PDF viewer not working, auto download pdf instead

### ISSUE THREAD

**Issue by andreaspiem** [ramboxapp/community-edition#2199]
### Steps to reproduce

1. Opening pdf attachment from mail (other file type is working as intended)

### Expected behavior

The file will be opened on a new tab of zoho mail (a'la Gmail)

### Actual behavior

The download window prompt is opened, asking me to download the attachment.
New tab of zoho mail is opened, but the file keeps loading.

### ENVIRONMENT

Version: 0.6.4
Platform: win32 (x64)
Electron: 3.1.4
Chromium: 66.0.3359.181
Node: 10.2.0

**Comment by Corchoneitor** [comment]
Hi @andreaspiem !

Thanks for your report. It behaves as you described.

Bye!

**Comment by Corchoneitor** [comment]
Further research led to an electron issue:
https://github.com/electron/electron/issues/12337

And a WIP PR promising to resolve it:
https://github.com/electron/electron/pull/17163

**Comment by MiXT4PE** [comment]
This might be of help: https://stackoverflow.com/q/52844135/7910454

**Comment by Corchoneitor** [comment]
> This might be of help: https://stackoverflow.com/q/52844135/7910454

Let's keep waiting then...

**Comment by RobertLRead** [comment]
I believe this was fixed and working at one time and is now (April 12th, noticed April 11th) broken. Clicking on PDF hangs indefinitely.

**Comment by fvulich** [comment]
0.7.8 Released, this issue is fixed in it. You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
