### ISSUE TITLE
VK.com does not send popup nitifications and badge counter does not work.

### ISSUE THREAD

**Issue by trurl123** [ramboxapp/community-edition#2200]
In VK settings notification feature can not be enabled inside of Rambox. When you enable notifications it automatically disables it.

Works as expected in browser.  Reopened #1725

**Comment by Corchoneitor** [comment]
Hi @trurl123 !

What we could see so far is there is a problem between Electron and the push service registration.

We will investigate this issue. Thanks for your report.

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
