### ISSUE TITLE
Ctrl + Page Up Not Working

### ISSUE THREAD

**Issue by bashprompt** [ramboxapp/community-edition#2201]
### Steps to reproduce

1. Open Rambox
2. Have multiple tabs
3. Try using Ctrl + Page Up or Ctrl + Page Down to move between the tabs

### Expected behavior

Have the currently focused tab, change from service to service upon clicking Page Up or Page Down

### Actual behavior

Absolutely nothing happens

### ENVIRONMENT

> Rambox: v0.6.4

> OS: Windows 10 LTSB 2019

> Arch: x64

**Comment by maxerbox** [comment]
Dup, closing

**Comment by bashprompt** [comment]
@maxerbox where is the other issue that this is a duplicate of?

**Comment by maxerbox** [comment]
#2138 that's the pull request which fix ut
