### ISSUE TITLE
App crashes constantly on win7 x64 sp1

### ISSUE THREAD

**Issue by AlexeyRogachenko** [ramboxapp/community-edition#2202]
App crashes constantly on win7 x64 sp1 (different device)
Rambox 0.6.4 
Was trying to install 0.6.3 since it doesn't crash but you guys made it auto-update with no option to turn updates off 😞 

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 10.0.15063

**Comment by maxerbox** [comment]
Please, list your active services 
Try to isolate the bad one 
Also, give a stack trace.

**Comment by maxerbox** [comment]
To disable updates, see
https://github.com/ramboxapp/community-edition/issues/2146#issuecomment-473533289

I suspect your issue has already been reported

**Comment by coolsplash** [comment]
Had same problem. Hoped 0.6.5 will fix.
