### ISSUE TITLE
Add a note to wiki about userstyles

### ISSUE THREAD

**Issue by beardhatcode** [ramboxapp/community-edition#2204]
Userstyles can be added by injecting JavaScript. I think it would be useful to add a note in the wiki page about script injection. (https://github.com/ramboxapp/community-edition/wiki/Inject-JavaScript-Code).

I suggest the following addition:

    An other example is injecting custom CSS (user styles). 
    This can be done with following snippet:
    
    ```javascript
    (()=>{ let css=`
    /* START OF STYLE */
    
    * {
        color: red;
    }
    
    /* END OF STYLE */
    `;
    
    var ss = document.createElement("style");
    ss.type = "text/css"; ss.innerHTML = css;
    document.getElementsByTagName("head")[0].appendChild(ss); })();
    ```

Since I cannot create a PR for the wiki, a path for the edit can be found below and in this file: [wiki-js-inject.patch](https://github.com/ramboxapp/community-edition/files/3076367/wiki-js-inject.patch.txt).

```patch
diff --git a/Inject-JavaScript-Code.md b/Inject-JavaScript-Code.md
index 02a812d..6610a9d 100644
--- a/Inject-JavaScript-Code.md
+++ b/Inject-JavaScript-Code.md
@@ -4,4 +4,24 @@ For example, some users want to make an Auto Refresh every X time because the se
 
 ```javascript
 setInterval(function(){location.reload();}, 600000);
-```
\ No newline at end of file
+```
+
+
+
+An other example is injecting custom CSS (user styles). This can be done with following snippet:
+
+```javascript
+(()=>{ let css=`
+/* START OF STYLE */
+
+* {
+       color: red;
+}
+
+/* END OF STYLE */
+`;
+
+var ss = document.createElement("style");
+ss.type = "text/css"; ss.innerHTML = css;
+document.getElementsByTagName("head")[0].appendChild(ss); })();
+```

```

**Comment by maxerbox** [comment]
Thanks you for your contribs, I've added it

**Comment by beardhatcode** [comment]
Thanks, there is a small error in the page, the code-block ends with ` ``` ` on the same line as the last line of the code. But it should be on the line below that. There is a newline missing.

**Comment by maxerbox** [comment]
Fixed
