### ISSUE TITLE
Whatsapp error (needs Chrome 36+) is back.  Using version 0.6.5

### ISSUE THREAD

**Issue by desapar** [ramboxapp/community-edition#2207]
After upgrading to Rambox 0.6.5, Whatsapp broke again.  I've tried removing and reinstalling the service.  Doesn't help.

	
	-
	> Rambox 0.6.5
	> Electron 4.1.4
	> win32 x64 10.0.17134

**Comment by cromerc** [comment]
Yes, it has returned for me as well. I downgraded back to 0.6.4 and can use whatsapp again.

**Comment by maxerbox** [comment]
Is the fix with 0.6.6 working ?

**Comment by Mic92** [comment]
No. ![screenshot](https://dl.thalheim.io/2Q2gf0Q6AsrlmlznNOSlZg/2019-04-16_11-31.png)
0.6.6 still has the issue.

**Comment by maxerbox** [comment]
@Mic92 I need an user agent. Can you try to open dev tools for whatsapp, and show the output of clientInformation.userAgent

**Comment by Mic92** [comment]
Weird. Did facebook already fixed it? Now it is working.

**Comment by Mic92** [comment]
Nevertheless. Here is output:

```
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rambox/0.6.3 Chrome/66.0.3359.181 Electron/3.1.8 Safari/537.36"
```

**Comment by Mic92** [comment]
Ah no. It is because I downgraded to 0.6.4. The issue still persists with 0.6.6.
Here is the output for 0.6.6:

```
> clientInformation.userAgent
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rambox/0.6.6 Chrome/66.0.3359.181 Electron/3.1.8 Safari/537.36"
```

**Comment by Mic92** [comment]
This is strange. The only difference is the rambox version. Do they hardcode on there servers?

**Comment by maxerbox** [comment]
I see what's hapenning

**Comment by saenzramiro** [comment]
Works for me in version 0.6.6. I know version 0.6.5 has the issue.

**Comment by Mic92** [comment]
What is your electron version?

https://dl.thalheim.io/8bvAfuuZQWmx3iYaWfIWAg/2019-04-17_15-28.png

**Comment by Corchoneitor** [comment]
Works in Rambox 0.6.6 and Electron 4.1.4. @Mic92 did you clear cache and/or local storage to see what happens?

> I see what's hapenning

What is it?

**Comment by maxerbox** [comment]
> What is it? @maxerbox 

The reg expression is matching Rambox, with case sensitive, but it should match also rambox.
I just added the i flag to the reg expression, in #2219 
```js
/Rambox\/([0-9]\.?)+\s/ig
```
