### ISSUE TITLE
Whatsapp web not working with 0.6.5

### ISSUE THREAD

**Issue by coolsplash** [ramboxapp/community-edition#2208]
Whatsapp comes up with a message to use Chrome 36+ or Firefox, etc. 

	
	-
	> Rambox 0.6.5
	> Electron 4.1.4
	> win32 x64 6.1.7601

**Comment by coolsplash** [comment]
Duplicate of #2207. Closing.

**Comment by cromerc** [comment]
It stopped working for me as well, I downgraded back to 0.6.4 to be able to use whatsapp again.
