### ISSUE TITLE
forget window sizes

### ISSUE THREAD

**Issue by Vidarius** [ramboxapp/community-edition#221]
all times the window have the same position an sme size, but not the size or position after the last session

**Comment by saenzramiro** [comment]
What OS are you using?

**Comment by Vidarius** [comment]
Windows 10 Enterpreise TH2 and Windows 10 Anv Pro. versions, same think

**Comment by WizardPC** [comment]
Same problem. Windows 10 Professionnel.

Rambox always open in the center of my screen.

**Comment by WizardPC** [comment]
Still not fixed? :disappointed:
