### ISSUE TITLE
Wrong font after fresh update

### ISSUE THREAD

**Issue by alienhunter3010** [ramboxapp/community-edition#2210]
Many services (WhatsApp, Telegram, Messenger) have wrong font, pretty unreadable (Linux/Ubuntu SNAP installation). 

	
	-
	> Rambox 0.6.6
	> Electron 4.1.4
	> linux x64 4.15.0-47-generic

**Comment by Corchoneitor** [comment]
Hi @alienhunter3010 !

@saenzramiro can you give us a hand testing this?

**Comment by nomeaning777** [comment]
I have same problem on rambox 0.6.6 installed from snapcraft.
In my environment, it is caused by impossible to read fontconfig. 
As in the following URL, `FONTCONFIG_PATH` and `FONTCONFIG_FILE` environment variable fixes the problem.
https://bugs.launchpad.net/ubuntu/+source/snapcraft/+bug/1576303
