### ISSUE TITLE
Can´t Login to my reddit account

### ISSUE THREAD

**Issue by Dexebal** [ramboxapp/community-edition#2211]
I have installed the Reddit Service. But if i try to logging in my account it turns so following info: Incorrect password  
But I am sure the password is correct. I try it with my browser and it works

 

	
	-
	> Rambox 0.6.6
	> Electron 4.1.4
	> win32 x64 10.0.17763

**Comment by Corchoneitor** [comment]
Hi!

Could it be that your password contains special characters? I'm guessing the ALT or Shift combinations are messing your input when trying to log in within Rambox. Try to change your password temporarely to some common password and see if that's it.

If that's not the case, let us know for a follow up.

**Comment by Dexebal** [comment]
hi!

now i tried to type my password in the username label to check the correct spelling. After then rightclick - copy and rightclick paste to the password label. Now, I´m logged in.
Thanks for the hint.
