### ISSUE TITLE
Automatically upgrading to an incompatible version

### ISSUE THREAD

**Issue by alvarogois** [ramboxapp/community-edition#2213]
### Steps to reproduce

1. Open the app (version 0.6.4)
2. Dismiss the update notification (green bar)
3. App updates just the same to 0.6.6, can't login after relaunch

### Expected behavior

I would expect Rambox NOT to update automatically, or have some kind of option to disable auto-update.

### Actual behavior

App updates just the same from 0.6.4 to 0.6.6, even if the Update alert is dismissed, can't login after relaunch.

### ENVIRONMENT

> Rambox: v0.6.4

> OS: MacOS 10.9.5

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @alvarogois !

The actual behavior is as expected, updates are mandatory. That been said, we could add "auto-update" as an option, making updates optional for this kind of situations.

Regarding you can't login after updating to 0.6.6, can you elaborate more? Do you see any error message? Are you able to launch and use the app at least?

Thanks.

**Comment by alvarogois** [comment]
Hi @Corchoneitor, login is impossible, 0.6.6 is not compatible with 10.9.5, therefore the app won't even load.

Updates that break system compatibility shouldn't be mandatory.

Thanks.

**Comment by Corchoneitor** [comment]
For the time been, try to avoid updates with this...

https://github.com/ramboxapp/community-edition/issues/2146#issuecomment-473533289

**Comment by alvarogois** [comment]
It's Windows only, right @Corchoneitor? If so, not useful for MacOS.

**Comment by arctouch-douglaskazumi** [comment]
I have a similar, if not exactly the same, problem. Running 0.6.4, if I try to run 0.66 I get a popup twice saying to check my internet connection or config the proxy. This only happens in the internal company network, on a public network it works fine. Can't tell what kind of restrictions are imposed by the company network.

**Comment by saenzramiro** [comment]
We will add an option to disable auto-updates in next version. Please, let's continue this in #1521.
