### ISSUE TITLE
Problem to download whatsapp files on fullscreen

### ISSUE THREAD

**Issue by cleyan** [ramboxapp/community-edition#2215]
When I try to download a file on whatsapp (a file sent or an image) the file dialog open behind the window, so in fullscreen mode, the file dialog seems to be missing but then i need to switch window mode, got o file dialog, click en save and return to rambox windows and make fullscreen again

This don't happend on previous version

regards and great software! btw

	
	-
	> Rambox 0.6.6
	> Electron 4.1.4
	> darwin x64 16.7.0

**Comment by Corchoneitor** [comment]
Hi @cleyan !

I'm guessing you have the "Always on top" option enabled and that's why you get the "file dialog" at the back. Check that option in the "Preferences" window.

If that's not the case, let us know!

**Comment by cleyan** [comment]
Hi and thank you

"The always on top" was enabled and the problem was solved after i disabled this option, but this problem don't happen on previous versions

The problem also affected the dialogs to upload files/images not only downloads

When i save the Preferences windows I got an error, 



**A JavaScript error occurred in the main process**

Uncaugh Exception:
ReferenceError: appLauncher is not defined
    at EventEmitter.<anonymous> (/Applications/Rambox.app/Contents/Resources/app.asar/electron/main.js:258:23)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Rambox.app/Contents/Resources/electron.asar/browser/api/web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)


Regards

Carlos

**Comment by Corchoneitor** [comment]
Hi @cleyan.

The "save preferences" error was fixed for version 0.6.7.
Since "always on top" is working as expected, I'm closing this issue.

Thanks!
