### ISSUE TITLE
Rambox Missing Services | Preferences Not Displaying Correctly

### ISSUE THREAD

**Issue by dravnt** [ramboxapp/community-edition#2218]
![Capture](https://user-images.githubusercontent.com/49743185/56339148-d97bc500-6161-11e9-8f1d-471fa9769b92.JPG)
![Capture1](https://user-images.githubusercontent.com/49743185/56339225-2d86a980-6162-11e9-97b8-1a8939a6e7a8.JPG)

	
I installed the latest update for Rambox free version and it shows my enabled services but, as can be seen in the attached picture, the Services aren't available to select.  Further, when I select the Preferences options, I get the menu in the lower left corner and cannot confirm any changes (please see attached picture).

Again, all I did was update to the newest version of Rambox.

What might I try to resolve this issue?

Thank you!!

	
	-
	> Rambox 0.6.6
	> Electron 4.1.4
	> win32 x64 10.0.17134

**Comment by maxerbox** [comment]
I got sort of this issue,
I deleted my rambox folder and it worked for me after.
That's not a good fix, but it's a temporary solution

**Comment by ericimthorn** [comment]
Could it be that a language file is missing? I get the following js error but I don't know if it's related:

`GET file:///Applications/Rambox.app/Contents/Resources/app.asar/ext/packages/ext-locale/build/ext-locale-nl.js net::ERR_FILE_NOT_FOUND`

**Comment by dravnt** [comment]
I completely uninstalled the app, searched for all Rambox files, deleted them, and then did a clean reinstall.  No dice.  :(

**Comment by fengapappit** [comment]
Exact same issue on Linux.

**Comment by dravnt** [comment]
On Windows 10, I delete all info from folder: ...\AppData\Local\Programs\Rambox\

It appears to completely clear the info but when I download/reinstall from the newest version online from the exe.  Same issue.  There's something cached preventing proper operation despite trying to clear all Rambox info.

The only way I can resolve the issue was to download the x64 zip folder, copy the info into a completely different folder, and everything appeared to work.

????

Guess that's the solution.  Don't download the exe/MSI package; download the zip folder instead.
