### ISSUE TITLE
[New Service Request] Zopim Chat

### ISSUE THREAD

**Issue by gdbytes** [ramboxapp/community-edition#222]
Would love to see Zopim Chat integrated (https://www.zopim.com). I can add it manually as a custom service but the way the chat box works causes problems.

A single account can only be logged in once at any given time, e.g. If i was logged in via browser, then logged in via phone, i would be logged out of the browser in the form of a popup telling me I have signed in elsewhere prompting me to logout or refresh(stay logged in).

The problem: The prompt is completely un-clickable for some reason, so the only way I can use the service again is by refreshing the entire app.

Zopim has a free plan that would be good enough for testing the implementation if it is at all possible.

Services like Zopim (live chat support apps) are a good shout for integration as most of them don't have dedicated apps and rely on the browser which I personally think is rubbish.

Thanks

**Comment by saenzramiro** [comment]
Thanks! I will take a look on this.
