### ISSUE TITLE
Error connection to android message with 0.6.6

### ISSUE THREAD

**Issue by ddalbera** [ramboxapp/community-edition#2220]
I upgrade to: Version: 0.6.6
                      Plateforme: linux (x64) 
                      Electron: 4.1.4
                      Chromium: 69.0.3497.128
                      Node: 10.11.0

And the connection with my phone seems to be impossible for "Android Messages" 
All other services seems to be OK ( hangout, messenger FB, Whatsapp, Slack, Skype)

I try to reload wifi or restart Rambox but same problem

My OS is Linux Mint 19 Cinamon with kernel 4.4.0-42 and my phont: OnePlus 5 with android 9

Thanks a lot

**Comment by ddalbera** [comment]
I try to disconnect totally Android message and reconnect with QRCode, but no response after qrcode scan
![Screenshot_20190418-105534](https://user-images.githubusercontent.com/33839496/56349303-96087180-61c8-11e9-99ee-3f2cde2590ab.jpg)

**Comment by ddalbera** [comment]
It's ok now, thank you if you find solutions :)

But I always have the same problem between version 0.6.4->0.6.5 , Rambox is very slow on linux mint after some hours of utilisation. I must restart it, or linux can be freezed or be very slowly.

Thanks ! ;)

**Comment by obahareth** [comment]
It's because it's no longer Android messages, they changed the URL too. It's now "Google Messages".

<img width="1185" alt="Screen Shot 2019-04-26 at 10 55 59 PM" src="https://user-images.githubusercontent.com/3428118/56833215-84813280-6876-11e9-9804-7dc5f36719ef.png">

**Comment by ddalbera** [comment]
Oh ok I don't know that, now it's ok ;) thanks

**Comment by obahareth** [comment]
I am still facing this in 0.6.7
