### ISSUE TITLE
Messages for android has changed URL

### ISSUE THREAD

**Issue by andersbusk** [ramboxapp/community-edition#2221]
Messages (for android phones) now point to the referal page to the new URL.
"Messages for web has a new URL
Everything else stays the same, now at messages.google.com/web.
To find it quick, add a bookmark. Learn more
"

	
	-
	> Rambox 0.6.6
	> Electron 4.1.4
	> win32 x64 10.0.17763

**Comment by maxerbox** [comment]
Dup, closing

**Comment by CristhianEcheverry** [comment]
Continue the problem in version 0.6.7
