### ISSUE TITLE
Problem with configurations in Rambox

### ISSUE THREAD

**Issue by ignacioaroche** [ramboxapp/community-edition#2222]
![image](https://user-images.githubusercontent.com/39389993/56439241-0c7da000-62ab-11e9-911c-f4be64386a6a.png)

Probably after deactivating the **Disable Hardware Acceleration** option. 

Those are my configurations. 
![image](https://user-images.githubusercontent.com/39389993/56439180-d6d8b700-62aa-11e9-84f7-9e5b9a7ac28f.png)
![image](https://user-images.githubusercontent.com/39389993/56439189-df30f200-62aa-11e9-8af3-5a00bc9dea9a.png)

	
	-
	> Rambox 0.6.6
	> Electron 4.1.4
	> linux x64 4.15.0-47-generic

**Comment by maxerbox** [comment]
Should be fiex with 0.6.7
