### ISSUE TITLE
Facebook Messenger scrollbar flicker

### ISSUE THREAD

**Issue by obvionaoe** [ramboxapp/community-edition#2225]
When you react to a Facebook Messenger message the screen goes crazy flickering the scrollbars.

### Steps to reproduce

1. Click on/hover over the reaction button for any Facebook Messenger message

### Expected behavior

It shouldn't flicker the scrollbars in and out.

### Actual behavior

Scrollbars(right and bottom) start appearing and vanishing giving a flicker effect.

### ENVIRONMENT

> Rambox: v0.6.6

> OS: Windows 10

**Comment by Corchoneitor** [comment]
Hi @obvionaoe.

I cannot reproduce it. Try updating to 0.6.7 to see if it still happening to you. Let us know!
