### ISSUE TITLE
Configurations (Backup/Restore) not Available over Version Mismatch

### ISSUE THREAD

**Issue by stellarpower** [ramboxapp/community-edition#2226]
I've updated to the Rambox 6.x series recently. I get a message frequently saying that a new version is available, but if I update on one machine, but don't on another, suddenly my configurations are lost.

In the update from 0.5.x -> 0.6.x, none of my services appeared.
In the update from 0.6.5 -> 0.6.6, my services were lost when restoring.

1. -  ### Steps to reproduce
    1. Use Rambox 0.5.x on machine A
    2. Backup configuration from machine A
    3. Install Rambox 0.6.x on machine B
    4. Restore configuration on machine B
  
  - ### Expected behavior
    Machine B has the accounts saved form Machine A

  - ### Actual behavior
    Machine B states that the restoration process was a success but no accounts are available.

2. 
   - ### Steps to reproduce
    1. Use Rambox 0.6.5 on machine A and machine B
    2. Backup configuration from machine A
    3. Use configuration happily on machine B
    4. Add a new service to Machine A
    5. Machine B upgrades Rambox from 0.6.5 to 0.6.6 automatically
    6. Restore configuration again on Machine B when realise this new service is missing. I'm not sure if I actually backed it up or not.
  
  - ### Expected behavior
    Machine B has the accounts saved from MAchine A, including then ew one

  - ### Actual behavior
    Machine B states that the restoration process was a success but all services were removed

### ENVIRONMENT
Machine A: Mint 17.1 AMD64, installed through dpkg
Machine B: Scientific Linux 7.5 AMD64 , installed through AppImage (No root access)
Rambox: v0.5.x -> 0.6.5 -> 0.6.6

### Comments
As a programmer, I understand that in the early days of this project, there may be incompatibilities between different versions' internal data structures that make backup and restore across different instances difficult, however as an end-user I find this issue very annoying, in particular when it's only a minor upgrade being applied in the second case, and when this was applied automatically; Rambox told me that the update was already installed and would be effective from next launch. I also find the backup/restore process clunky in general. I would far rather have my accounts synced across all devices; then I just have to open Ramboix on a different machine where I am logged in to my Rambox account and any changes in services will be available.

Keep up the good work though :)

**Comment by stellarpower** [comment]
Update: Closing Rambox fully, starting again, and then restoring a second time seems to be fine. Potentially the first instance wasn't terminated fully, or perhaps it's a blip (?).

**Comment by Corchoneitor** [comment]
Hi @stellarpower.

As you may know, it's very hard to mantain stability between different medium versions (0.5-0.6). So I'm guessing there will be no fixing coming up for now if it's a problem between 0.5 and 0.6 versions.

Can you double check this?

> Update: Closing Rambox fully, starting again, and then restoring a second time seems to be fine. Potentially the first instance wasn't terminated fully, or perhaps it's a blip (?).

Thanks!
