### ISSUE TITLE
Rambox Skype does not find camera

### ISSUE THREAD

**Issue by Eric-Sommer** [ramboxapp/community-edition#2233]
### Actual behavior
Under Settings -> Audio&Video -> Camera it says "No device found". The standard skype app however finds the camera and video calls work.

I'm not able to find out the webcam manufacturer, the computer is an ASUS F407UA

### ENVIRONMENT
> Rambox: v0.6.6. (via Snap)
> OS: Linux Mint 19.1
> Arch: x64

**Comment by saenzramiro** [comment]
This will be fixed in next version thanks to @maxerbox PR #2227.
