### ISSUE TITLE
No tray icon in Elementary

### ISSUE THREAD

**Issue by 4sStylZ** [ramboxapp/community-edition#2234]
### Possible duplicate

https://github.com/ramboxapp/community-edition/issues/1631
I can’t re-open it so feel free to do it if needed.

### Steps to reproduce

1. Use elementary OS 5.0 Juno
2. Start community edition 6.4.4 to 6.6.6
3. If needed, switch the settings for the tray icon.

### Expected behavior

Tray icon visible.

### Actual behavior

 No tray Icon visible (at least, for me. )

### ENVIRONMENT

> Rambox: v6.4.4 to 6.6.6

> OS: Elementary OS 5.0
Ubuntu 18.04.2 LTS
Gtk+ 3.22.30
Linux 4.15.0-48-generic
x64 

### Additional information

When I change the « Display behaviour » setting I got some issue : 

![image](https://user-images.githubusercontent.com/7487411/56733176-b2278800-675f-11e9-89a7-07eae75b81d6.png)

**Comment by saenzramiro** [comment]
@4sStylZ Please, check if latest version 0.6.7 have this issue.

**Comment by wolfposd** [comment]
eOS broke Trayicons for every app. You can follow this guide to get Trayicons back:
https://github.com/mdh34/elementary-indicators/blob/master/README.md



have you installed the following packages?

- wingpanel-indicator-ayatana
- indicator-application
