### ISSUE TITLE
RHEL 8 does not offer libappindicator anymore

### ISSUE THREAD

**Issue by ohaessler** [ramboxapp/community-edition#2235]
When trying to install Rambox on RHEL 8, it complains that libappindicator is no longer there. Only libappindicator-gtk3-12.10.0-19.el8.x86_64.rpm is available.

### Steps to reproduce

1. yum install https://github.com/ramboxapp/community-edition/releases/download/0.6.6/Rambox-0.6.6-linux-x86_64.rpm

### Expected behavior

Rambox installs

### Actual behavior

Error: 
 Problem: conflicting requests
  - nothing provides libappindicator needed by Rambox-0.6.6-167.x86_64

### ENVIRONMENT

> Rambox: v0.6.4+

> OS: RHEL 8

> Arch: x64

**Comment by Spacecat624** [comment]
You might be able to get around this problem by installing the old epel 7?
Example:
```
dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
```

**Comment by Corchoneitor** [comment]
Hi @ohaessler.

Did you find a solution?

**Comment by TomC4D** [comment]
> You might be able to get around this problem by installing the old epel 7?
> Example:
> 
> ```
> dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
> ```
That can get messy as it could start to downgrade other packages.  I'm still trying to find the solution.
