### ISSUE TITLE
Timestamps are off for Chile

### ISSUE THREAD

**Issue by oskapt** [ramboxapp/community-edition#2236]
### Steps to reproduce

I'm in Chile, who periodically changes when they go on/off DST. They changed it again for this year, but it was in the Oct 2018 tzdata update for the Internet/NTP. Everything seems to have updated fine, but I noticed today that Slack is an hour off. It's 1130 and all my messages in Slack show up as 1230. DND is also off by an hour. 

I set my time in Slack to US/Eastern, and I still show up an hour off.

But only in Rambox. Slack in browsers (Chrome, Safari, Vivaldi) is correct. Slack on my phone is correct.

![Screen Shot 2019-04-25 at 11 52 13](https://user-images.githubusercontent.com/171292/56750044-ed6e8a80-6750-11e9-8ae1-28e47b4145c9.png)

Upon further investigation, this is true of all Rambox windows:

- Mattermost
- WhatsApp
- Telegram
- Slack

### Expected behavior

I would expect that apps in Rambox would show the correct message time.

### Actual behavior

Messages are an hour off, as if Chile is still on DST.

### ENVIRONMENT

> Rambox: v0.6.6

> OS: MacOS High Sierra

> Arch: x64

**Comment by maxerbox** [comment]
Can you try
```js
var offset = new Date().getTimezoneOffset();
console.log(offset);
```
In the dev tools of slack in rambox, an then in your browser, and compare the results ?

**Comment by Orock** [comment]
Rambox 
![image](https://user-images.githubusercontent.com/6726959/57115755-c3076900-6d1e-11e9-863b-7184f7cddf50.png)

Chrome
![image](https://user-images.githubusercontent.com/6726959/57115760-d1ee1b80-6d1e-11e9-9045-0048d5667d70.png)

😢

**Comment by Corchoneitor** [comment]
Unfortunately, this is an electron issue with the timezones. Electron uses [moment/moment-timezone](https://github.com/moment/moment-timezone) which have some problems with Daylight Savings/time-changing laws.

See https://github.com/moment/moment-timezone/issues/651

**Comment by Corchoneitor** [comment]
Unfortunately, this is an electron issue with the timezones, as you can see here: https://github.com/mattermost/desktop/issues/679

**Comment by Corchoneitor** [comment]
Unfortunately, this is an electron issue with the timezones, as you can see here: https://github.com/electron/electron/issues/11670
