### ISSUE TITLE
Gmail print PDF file is not working

### ISSUE THREAD

**Issue by anudeepgannamaneni** [ramboxapp/community-edition#2237]
-
	> Rambox 0.6.6
	> Electron 4.1.4
	> win32 ia32 6.1.7601

**Comment by Corchoneitor** [comment]
Duplicate #2199

**Comment by Corchoneitor** [comment]
My bad, this is not a duplicate.

**Comment by mpsijm** [comment]
Thought I'd describe some symptoms while waiting for a fix: when clicking "Print", a blank window pops up with the title "_blank", as shown below. From the developer tools, it looks like the url of this window is `about:blank`.

![image](https://user-images.githubusercontent.com/9739541/59925996-95df5900-9439-11e9-808c-fa3d4dcda32c.png)

**Comment by mpsijm** [comment]
Still experiencing the issue, unfortunately.

**Comment by mpsijm** [comment]
Still experiencing the issue, unfortunately.

**Comment by adoello** [comment]
Still experiencing the issue, any solution? Thanks.

**Comment by fvulich** [comment]
0.7.8 Released, this issue is fixed in it. You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
