### ISSUE TITLE
Rambox Skype - no sound

### ISSUE THREAD

**Issue by 40OIL** [ramboxapp/community-edition#2238]
Rambox Skype - there is no sound, no signals are played, there is no interlocutor’s voice during the call - and on Friday 26.04 still worked.
In web skype in chrome - there is sound.

	
	-
	> Rambox 0.6.6
	> Electron 4.1.4
	> win32 x64 6.1.7601

**Comment by saenzramiro** [comment]
Please check if Do Not Disturb is turned off and "Enable sounds" option in app settings is checked.
