### ISSUE TITLE
Cursor disappears when typing a message.

### ISSUE THREAD

**Issue by leoheck** [ramboxapp/community-edition#2240]
Sometimes the cursor is missing on input message field. This was seen in Whatsapp and Google Chat. It happens sometimes but very often.

Using version 0.6.6 on Ubuntu 18.04 (64 bits)

**Comment by RicoLaaa** [comment]
same here on 0.66 and macOS 10.14.4

**Comment by saenzramiro** [comment]
Can you please check if this still happens in new version 0.6.7?

**Comment by leoheck** [comment]
Sure, I was installing it right now :)

**Comment by leoheck** [comment]
It looks good so far. I was using it for some hours until now. I will come back later if I see the problem again. Thanks @saenzramiro

**Comment by saenzramiro** [comment]
Thank you, hopefully it was fixed!

**Comment by mitchellnemitz** [comment]
On macOS Mojave with Rambox 0.6.7 I just lost the cursor when typing my username and password to login to GMail. Input still works just fine, there's just no visual feedback for which field is focused.

**Comment by Corchoneitor** [comment]
@leoheck, @mitchellnemitz, which services do you have active? Maybe that information would tell us something.

**Comment by mitchellnemitz** [comment]
GMail, Google Calendar, and Slack. The Google login form does not display the cursor for either username or password, and the Slack subdomain input did not display the cursor.

**Comment by leoheck** [comment]
I have Google Chat and WhatsApp.

**Comment by c-key** [comment]
I also have this behavior with textareas in Jira and input fields in RocketChat. But in some situations a reload of the service from the context menu can help, quite often.

**Comment by roman-yagodin** [comment]
Same here:
Version: 0.6.9
Platform: LMDE 3 Cindy (Debian 9) x64 
Services: Gmail, Simplenote (custom), Redmine (custom), Kiwi IRC

**Comment by rvavrik** [comment]
I noticed the missing cursor only in Facebook messenger input. Reloading the service does not help, but switching to another service (tab) and back does:
Version: 0.6.9
Platform: macOS Mojave 10.14.6
Services: Facebook messenger, Google Hangouts, Skype, Slack
