### ISSUE TITLE
How to get the software version?

### ISSUE THREAD

**Issue by leoheck** [ramboxapp/community-edition#2241]
I don't know how to get the Rambox version from inside de software. The interface is a mess. But I am using version `0.6.6` I know it I still have the installer on my downloads folder. 

Kicad has a good way to get its version. It is a button following the menus
```Help > About Kicad > Copy version info```

It is really useful for people who want to report and help the community.

By clicking the button, we get the following information:

```
Application: kicad
Version: 5.1.2-f72e74a~84~ubuntu18.04.1, release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Platform: Linux 4.20.11-042011-generic x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.22
    Boost: 1.65.1
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.58.0
    Compiler: GCC 7.3.0 with C++ ABI 1011

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=ON
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=ON
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON
```

Something similar may be really good info here for reporting bugs.

**Comment by maxerbox** [comment]
In Help, About rambox

**Comment by leoheck** [comment]
Ah, of course, thank you.

BUT WHERE IS THIS THING?
