### ISSUE TITLE
I created a Wechat account on Rambox, I used it a little, I moved to the standalone. Now I can't remove it.

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#2242]
As the title says, I used the Wechat inside Rambox for a few hours, then I decided I will use the official messenger. I had made one previously today, I could delete it without any problems. Perhaps because there is chat history connected to it, that's why I can't delete it?  Whenever I try, there is a loading bar that keeps reseting forever, trying to remove Wechat. I can escape it by restarting Rambox manually, no other way. Any advice?

	
	-
	> Rambox 0.6.6
	> Electron 4.1.4
	> win32 x64 6.1.7601

**Comment by Corchoneitor** [comment]
I tested on v0.6.7 and I removed it correctly. Try updating your Rambox version.

If you still have this trouble, I recomend you to clear Local Storage and Cache.

Tell us how it goes!
