### ISSUE TITLE
Template for Open-Xchange Mail Servers

### ISSUE THREAD

**Issue by jporzelt** [ramboxapp/community-edition#2243]
Support for Open-Xchange Mail Servers
https://www.open-xchange.com/

Currently I use it with an _custom Tab but it would be nice to have notifications about new e-mails, meetings, ...

Configuration parameters: Name, URL
Try in Sandbox: https://gold.ox.io/admin-api/tryme/user/gold/assignment
  
Open-Xchange is is used by many (at least in Germany) providers. E.g. 1&1, Mailbox.org

**Comment by Corchoneitor** [comment]
Thank you @jporzelt for the suggestion!

**Comment by jporzelt** [comment]
still interested :-)
