### ISSUE TITLE
Electron store is not stable, it is generating random errors.

### ISSUE THREAD

**Issue by Echobreaker** [ramboxapp/community-edition#2245]
Every time I click/minimize Rambox I get this error when on Gmail.

Uncaught Exception:
Error EPERM: Operation not permitted, rename
XXXXX/config.json.828590577
XXXX/config.json at Object.renameSync (fs.js.:591:3)
at Function.writeFileSync (as Sync) XXXX/index,jsL192:8 at ElectronStore.set store 
XXX index.js:164:19
BrowswerWindow<anonymous>
BrowserWindow.emit (events.js:182:13)

I couldn't type it all, but I tried to include the main bits. 

I never had a problem, but since 0.6.6 I have had a version work yet. The computer build is new. 

> Rambox: v0.6.6

> OS: Windows 7 64 Bit

> Arch: x64

See below for picture.
![2019-04-30 16_27_53-Rambox (1) - Gmail](https://user-images.githubusercontent.com/50154392/56991756-809b2c00-6b66-11e9-95c0-215ee4a4dd29.png)

**Comment by maxerbox** [comment]
Related to https://github.com/sindresorhus/electron-store/issues/31

Could be fixed with https://github.com/sindresorhus/electron-store/issues/31#issuecomment-346994405

**Comment by fvulich** [comment]
Is this still reproducible?
