### ISSUE TITLE
Wrong behaviour of keep in tray option, it is only minimizing when you close the window

### ISSUE THREAD

**Issue by rahulveparala** [ramboxapp/community-edition#2246]
When closing the main window with keep in tray option just minimizes the window. It shown in alt+tab options which was not the case in 0.6.6 version.  Looks like a bug in the functonality

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> win32 x64 6.1.7601

**Comment by maxerbox** [comment]
Related to https://github.com/ramboxapp/community-edition/commit/4b0c54f7fc0a81387d4b69fdf102e090c68bd396

**Comment by maxerbox** [comment]
Maybe, a workaround would be : 
1. Unhide the window
2. minimize it, and set skipTaskBar as true.
3. hide back the window
4 Repeat it every 15 minutes

**Comment by rahulveparala** [comment]
Can you tell me what is the solution for this?

**Comment by rahulveparala** [comment]
Iam not a developer . I would appreciate instructions or update for the bug identified.

**Comment by BjoernDaase** [comment]
Furthermore, this leads to clicking "Show/Hide Window" not focusing the window (if it was hidden) anymore, which is an essential part of the workflow.

**Comment by 613TheEvil** [comment]
I have the same problem, rambox is always in the alt-tab menu, no matter what I try.

**Comment by Corchoneitor** [comment]
@saenzramiro can you have a look at this?

**Comment by alien2003** [comment]
Confirmed on Manjaro Gnome.

It's pretty important, hotfix needed

**Comment by alien2003** [comment]
I tried fix from latest git version, still not fixed. Is it possible to revert previous behavior like in 0.6.6?
