### ISSUE TITLE
Webview is no longer focused when switching tabs

### ISSUE THREAD

**Issue by HesHeatingUp** [ramboxapp/community-edition#2247]
### Steps to reproduce

1. Ctrl+1/2/3/4, cursor does not appear in message box until clicking into it
2. Ctrl+tab, cursor does not appear in message box until clicking into it

### Expected behavior

In previous versions, moving to a new communication tab, cursor would appear directly in message box and you were able to type 

### Actual behavior

When clicking into a new tab, message cursor does not appear

### ENVIRONMENT

> Rambox: v0.6.7

> OS: Windows 10

> Arch: win32 (x64)

**Comment by maxerbox** [comment]
Confirmed, at least focus event is not fired anymore.

Debian Gnome x64
0.6.7

**Comment by mitchellnemitz** [comment]
Same problem on macOS Mojave, Rambox: v0.6.7.

Possibly related, I can't use `cmd+1/2/3` after focusing the message input with Slack and GroupMe.

**Comment by StormPooper** [comment]
Confirmed as a problem for me on both my Windows 10 and Arch Linux machines.

**Comment by Corchoneitor** [comment]
Happened to me in 0.6.6 and 0.6.7.

**Comment by JDHannan** [comment]
I thought this maybe worked in 0.6.6, but it definitely worked in 0.6.5
