### ISSUE TITLE
Microsoft Teams guest organization tab

### ISSUE THREAD

**Issue by StraggleCraft** [ramboxapp/community-edition#2248]
![rambox_teams](https://user-images.githubusercontent.com/10663364/57033253-6fabf280-6c1a-11e9-862c-0237d7a24165.png)
![2019-05-01 14_05_01-Join conversation](https://user-images.githubusercontent.com/10663364/57033266-76d30080-6c1a-11e9-8d87-38c410f909d9.png)

Msft Teams will launch a popup when selecting a different organization (a guest of a different company).  This URL looks like this:
https://teams.microsoft.com/dl/launcher/launcher.html?url=%2f_%23%2fl%2fteam%2f19XXXXXXXXX&type=team&deeplinkId=XXXXXXXXX&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true

Please have this loaded inside the RamBox tab, as users are currently unable to select a guest organization.

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> win32 x64 10.0.17134

**Comment by maxerbox** [comment]
#2102 should be a workaround ?

**Comment by kptkill** [comment]
Holding down control also works around the issue per #2102
