### ISSUE TITLE
I can't properly minimize, Rambox always stays in the alt+tab menu. Started after latest update.

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#2249]
As soon as I installed Rambox 0.6.7, closing Rambox no longer removes it from the Alt+Tab menu, (not sure how it is called). I did not change anything in the Preferences when I updated, I tried changing what happens "when closing the  main window" but no change, sadly. Any ideas?

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> win32 x64 6.1.7601

**Comment by maxerbox** [comment]
dup #2246
