### ISSUE TITLE
Please get rid of stalebot

### ISSUE THREAD

**Issue by pirate** [ramboxapp/community-edition#2251]
It's incredibly frustrating to constantly have to bump tickets and reopen duplicates because stalebot is buggy/overly aggressive.

**Comment by pirate** [comment]
#2036
#2039
#1629

**Comment by saenzramiro** [comment]
Stalebot from now will only work with issues with the label "more-information-needed".

**Comment by pirate** [comment]
Thanks for changing that, can you also reopen https://github.com/ramboxapp/community-edition/issues/1629 ?
