### ISSUE TITLE
Show/Hide window only works once

### ISSUE THREAD

**Issue by freddyw** [ramboxapp/community-edition#2254]
### Steps to reproduce

1. Start rambox (minimized)
2. Click show/hide => window appears
3. Click show/hide => window disappears
4. Click show/hide => nothing happens

### Expected behavior

The show/hide toggle always works

### Actual behavior

The show/hide toggle only works once. 0.6.6. does not have this issue.

### ENVIRONMENT

> Rambox: v0.6.7

> OS: fedora30 (tested on 29 as well)

> Arch: x64

**Comment by rishi-ramawat** [comment]
Facing the same Issue after upgrading to Rambox **v0.6.7** via the amd64 snap package.

> Rambox: v0.6.7
> OS: Ubuntu 18.04.2 LTS
> Architecture: x86_64

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
