### ISSUE TITLE
Window size/layout is destroyed when clicking on notification or tray icon

### ISSUE THREAD

**Issue by CombeeMike** [ramboxapp/community-edition#2257]
I oftentimes arrange my second desktop/screen to show Rambox side by side with some other app like a music player, ...

The problem is that when clicking on a windows notification from Rambox or when double-clicking on the tray icon, it "destroys" my desktop layout:

I'd expect it to only bring Rambox to the front and switch to the tab from which the notification came but keep its window dimensions, position etc.

![20190503_07h29_37](https://user-images.githubusercontent.com/30658772/57121191-1e187a80-6d76-11e9-99f7-90fb1ddcd284.gif)

### ENVIRONMENT

> Rambox: v0.6.7
> OS: Win 10
> Arch: x64

**Comment by Corchoneitor** [comment]
Thanks for your report, @CombeeMike.

It'd be a nice enhancement!

**Comment by CombeeMike** [comment]
Also, when minimizing it to tray in maximized state and clicking on a windows notification afterwards, the app won't restore its maximized state but opens up with some different size.

Whilst I'm not 100% sure, I believe this did not happen in earlier versions and was only introduced in the latest release `v0.6.7`.

@Corchoneitor 
Should I create a dedicated issue for this?

**Comment by Corchoneitor** [comment]
@CombeeMike don't. I think it's related.

Thank you! Hope it'll be fixed soon!

**Comment by CombeeMike** [comment]
@Corchoneitor Thank you for your response!
I'm really looking forward to this fix since the current behavior is really annoying ;)

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
