### ISSUE TITLE
Removing old Yahoo Messenger causes Rambox to freeze

### ISSUE THREAD

**Issue by antzpantz** [ramboxapp/community-edition#2259]
### Steps to reproduce

1.  Remove Yahoo Messenger from an existing backup
2.  "Removing... Please wait until we clear..."
3.  Rambox freezes
4.  Force quit application and restart clears all existing tabs, can not log out of profile, and general pop-up windows for Settings are broken
5. Have to manually delete Roaming Data from Windows User Profile to start clean.

### Expected behavior

Remove Yahoo Messenger app... app gets removed and nothing else breaks

### Actual behavior

1.  Remove Yahoo Messenger from an existing backup
2.  "Removing... Please wait until we clear..."
3.  Rambox freezes

### ENVIRONMENT

Version: 0.6.7
Platform: win32 (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0

**Comment by Corchoneitor** [comment]
Hi @antzpantz.

I cannot reproduce it. Since Yahoo Messenger is dead, can we leave it like that? Or this is causing you other problems?

Bye.

**Comment by antzpantz** [comment]
I've actually stopped using Rambox because of this issue. My backed up profile can't be cleared or wiped clean and still has this app in it. If there was a way to clear the backup, then it'd be fine.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
