### ISSUE TITLE
Google Drive doesn't work

### ISSUE THREAD

**Issue by daoktar** [ramboxapp/community-edition#2260]
### Steps to reproduce

1. Add Google drive as a custom service
2. login

### Expected behavior

Ability to add\create new docs\folders, 
ability to view content of folders

### Actual behavior

1. See folder tree, but folders shown empty while they are full
2. Buttons for add new file\folder is inactive

### ENVIRONMENT

Version: 0.6.7
Platform: win10 (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0

![Rambox_JFD6xvuAey](https://user-images.githubusercontent.com/18519029/57179826-bc960000-6e8a-11e9-9456-bc172621ae11.png)

**Comment by Corchoneitor** [comment]
Hi @daoktar.

Here is the way you can fix this:

1. Go to Rambox dashboard.

**Comment by Corchoneitor** [comment]
Hi @daoktar.

Here is the way you can fix this:

1. Go to Rambox dashboard.
2. Open the configuration window of your "Drive" service.
3. Open the "Advanced" frame and insert this code in "Custom Code":
`window.chrome = {};`

If you still have the problem, please reopen this issue. Enjoy :).
