### ISSUE TITLE
Window doesent come back up from Tray

### ISSUE THREAD

**Issue by dolour** [ramboxapp/community-edition#2261]
Window doesent come back up from Tray, which makes use with hidden
Taskbar entry impossible on Cinnamon.

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> linux x64 5.0.9-2-MANJARO

**Comment by Corchoneitor** [comment]
@saenzramiro can you take a look at this?

Thx!

**Comment by diogobaeder** [comment]
Not sure if it's the same issue, but in my Arch Linux installation it does come back, but inactive and doesn't pop up when clicked. I.e., I have to click the icon, then find where the window is.

**Comment by josedeleoncordon** [comment]
I've made a comment on another ticket which might be related to this #2265 

The problem started with Rambox 0.6.7 update, 0.6.6 works fine.

**Comment by diogobaeder** [comment]
On 0.6.8 it still happens, unfortunately.

**Comment by diogobaeder** [comment]
On 0.6.9 it still happens.

**Comment by jerry1970** [comment]
Keeping this issue alive. Highly annoying that none of the team even replies. Please acknowledge or reject, but please say something.

**Comment by diogobaeder** [comment]
@saenzramiro any chance this can be looked at? @alexandregv ? @weeman1337 ?
If there's no intention to fix it, can you guys at least let us know?
