### ISSUE TITLE
Unexpected behaviour when minimazing 

### ISSUE THREAD

**Issue by mariajesusmayor** [ramboxapp/community-edition#2262]
When I minimize Rambox, it quits. :( 

	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> win32 x64 10.0.17134

**Comment by Corchoneitor** [comment]
Hi @mariajesusmayor.

Is this happening every time you minimize, sporadically, or when you do something specific? Which Operative System do you use?

**Comment by mariajesusmayor** [comment]
Hola, Juan Manuel

No recordaba que sois argentinos… mejor hablamos en español. Os adjunto una captura con información básica del sistema operativo.

En cuanto a la frecuencia, me pasa siempre que minimizo la aplicación (lo acabo de comprobar). Es con la versión que instalé esta mañana, antes no pasaba.

Por cierto, os he preguntado por Twitter (soy @txuseta), pero no hace falta que me contestéis dos veces).

![2019-05-06 17_17_31-Window](https://user-images.githubusercontent.com/43144705/57235341-f00b9280-7022-11e9-8fcf-c1a276622a24.png)

**Comment by mariajesusmayor** [comment]
It's better described in this issue: https://github.com/ramboxapp/community-edition/issues/2263 so I close it.
