### ISSUE TITLE
Minimized window does not show in taskbar when "keep in tray"

### ISSUE THREAD

**Issue by Corchoneitor** [ramboxapp/community-edition#2263]
When I MINIMIZE Rambox to the Taskbar with config as shown in next image, it's minimized to tray instead of the taskbar. Happens only with this combination of configs.

![image](https://user-images.githubusercontent.com/2912593/57248978-285aa300-701a-11e9-993d-6353f20c5f47.png)

### Steps to reproduce

1. Set "Display behavior" config to "Show in Taskbar and Tray Icon" and "When closing the main window" config to "Keep in tray".
2. Minimize Rambox.

### Expected behavior

Rambox should be shown minimized in Taskbar.

### Actual behavior

Rambox is minimized to Tray and disappears from the Taskbar.

### ENVIRONMENT

> Rambox: v0.6.7

> OS: Windows

> Arch: x64

**Comment by mariajesusmayor** [comment]
I think that's exactly my bug. I didn't report it so accurately.  https://github.com/ramboxapp/community-edition/issues/2262

Two screenshots:
![taskadmin_Rambox](https://user-images.githubusercontent.com/43144705/57312824-96709a00-70ee-11e9-90b2-3f3600529d46.png)
![taskbar_noIcon](https://user-images.githubusercontent.com/43144705/57312825-96709a00-70ee-11e9-9d24-b6fac5e0399d.png)
