### ISSUE TITLE
Icon Problems Manjaro Linux

### ISSUE THREAD

**Issue by qlomro** [ramboxapp/community-edition#2265]
Hello, this is my problem. 
The icon of the system tray does not allow me to open the application and also I can't close the application in the system tray, it remains in the system bar.
I've already tried changing the program's preferences but they don't seem to work.
Thank you very much!

	> Rambox 0.6.7
	> Electron 4.1.4
	> linux x64 4.19.36-1-MANJARO

**Comment by Corchoneitor** [comment]
@saenzramiro can you have a look at this?

**Comment by saenzramiro** [comment]
@Corchoneitor This doesn't happens in other distros. We can investigate why is working like this in Manjaro by running it in a VM.

**Comment by diogobaeder** [comment]
I've made a comment on another ticket which might be related to this: https://github.com/ramboxapp/community-edition/issues/2261#issuecomment-494020796

I'm using Arch Linux, BTW, which is the base distro for Manjaro.

**Comment by josedeleoncordon** [comment]
Hello, I have the same issue

The problem started with Rambox 0.6.7 update, 0.6.6 works fine.

Rambox 0.6.7:
When I close the application to system tray the window doesn't disapper at all, it will disappear from task bar but with alt-tab you can switch to it again. If  I want it in task bar again I have to click on the system tray icon and choose show/hide window:

I reinstalled the 0.6.6 version and it fixes the problem but the application updates itself

I'm using Fedora 30, KDE 5.15.4

**Comment by snapshotpl** [comment]
Same on ubuntu 18.04.2

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
