### ISSUE TITLE
/Edit/Paste and Match Style broken under 0.6.7

### ISSUE THREAD

**Issue by wjaynay** [ramboxapp/community-edition#2266]
(N.B. Template appended below)

Greetings Team Rambox,

Thanks for all you do to support stable, inclusive chatting. 

Our end users have recently noticed that '/Edit/Paste and Match Style' (i.e., shift-command-V) no longer functions as a workaround to prevent Microsoft Word clipboard contents from being attached as a file. 

Under 'Version: 0.6.3; Platform: darwin (x64); Electron: 2.0.14; Chromium: 61.0.3163.100; Node: 8.9.3,' performing said operation resulted in the clipboard contents, having previously been copied from a Microsoft Word document - and with all the bananas formatting that implies - being rendered as plaintext (whereas, a simple command-paste opens a dialogue box offering the user the opportunity to attach the clipboard contents as a file, an ungainly approach in many cases).

However, under the more recent 'Version: 0.6.7; Platform: darwin (x64); Electron: 4.1.4; Chromium: 69.0.3479.128; Node: 10.11.0,' performing said operation has no result whatever. That is, the 'Edit' menu header flashes, indicating that the keyboard input is recognized, but nothing whatever is pasted into the field, nor is any dialogue engaged.

Note also that, under a full browser pointing at the same URL, the operation does work normally. Additionally, the issue is not restricted to esoterically formatted clipboard contents: even 'shift-command-pasting' plaintext has no effect.

Thanks for your help in resolving this former functionality.

Cheers,

Team LAssociates

Template:

### Steps to reproduce

1. Copy something to the clipboard;
2. Attempt to /Edit/Paste and Match Style using 'shift-command-V' into the 'Message' field;
3. watch as nothing whatsoever happens

### Expected behavior

Clipboard contents should be pasted into the Message field as plaintext

### Actual behavior

Nothin' at all (except the /Edit menu flashes to show that the keyboard input is recognized)

### ENVIRONMENT

> Rambox: v0.6.7

> OS: 10.11.6 (15G22010)

> Arch: x64

**Comment by Nosferous** [comment]
Also having this issue in recent update to Rambox. This was one of the benefits to Rambox over RocketChat's own electron app was this paste match style. Hopefully we see this bug fixed in next update.

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
