### ISSUE TITLE
Rambox crashes multiple times per day

### ISSUE THREAD

**Issue by VPatlin** [ramboxapp/community-edition#2268]
After the last 2 or 3 updates, Rambox crashes while simply clicking on different services.  I have to re-open it several times a day.  There does not appear to be any specific sequence of events that causes it.  The common problem seems to be when I click to change the service/email account I am looking at, it frequently just disappears out from under me.

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> win32 x64 10.0.16299

**Comment by Corchoneitor** [comment]
Hi @VPatlin.

Is this still hapenning? Did you try a fresh install? What services are you using?

**Comment by VPatlin** [comment]
Yes, this is still happening.  Um, I don't think I have tried a fresh install if you mean uninstall and then re-install.
I have these services:   
   - Android Messages
   - Google hangouts
   - Facebook messenger
   - WhatsAp
   - LinkedIn
   - Slack
   - Microsoft Teams
   - Microsoft outlook with a hotmail account.
   - Comcast mail
   - Google mail
   - Yahoo mail
   - Microsoft outlook with a microsoft 365 account.

Thanks,
Vivian Patlin
    On Friday, May 31, 2019, 12:10:08 PM MDT, Juan Manuel Gonzalez Alama <notifications@github.com> wrote:  
 
 
Hi @VPatlin.

Is this still hapenning? Did you try a fresh install? What services are you using?

**Comment by NegassaB** [comment]
> Hi @VPatlin.
> 
> Is this still hapenning? Did you try a fresh install? What services are you using?

Same here and I just installed it today. It just crashes when I swith between my emails.

**Comment by VPatlin** [comment]
Yes, this still happens.  Still happens through a fresh install.
    On Thursday, June 20, 2019, 5:12:44 AM MDT, Negassa Berhanu <notifications@github.com> wrote:  
 
 

Hi @VPatlin.

Is this still hapenning? Did you try a fresh install? What services are you using?


Same here and I just installed it today. It just crashes when I swith between my emails.

**Comment by Corchoneitor** [comment]
Hi guys.

Can you update manually to [v0.6.9](https://github.com/ramboxapp/community-edition/releases/tag/0.6.9) please?

I'm still unable to reproduce this error. @NegassaB you said your Rambox crashes when switching between emails... which are those emails?

Thanks.

**Comment by VPatlin** [comment]
How do I do that?  When I click, relaunch, it crashes.
Yes, it still happens.  I have gmail, yahoo mail, and outlook mail.  I turned off the comcast mail, but it still closes/crashes when I switch between different email sources.
Vivian
    On Thursday, July 4, 2019, 8:30:12 AM MDT, Juan Manuel Gonzalez Alama <notifications@github.com> wrote:  
 
 
Hi guys.

Can you update manually to v0.6.9 please?

I'm still unable to reproduce this error. @NegassaB you said your Rambox crashes when switching between emails... which are those emails?

Thanks.

**Comment by Corchoneitor** [comment]
@VPatlin use the link I gave, download the right installer for your environment and install Rambox again. This will "update" Rambox to v0.6.9.
