### ISSUE TITLE
Feature: auto reload 

### ISSUE THREAD

**Issue by penCsharpener** [ramboxapp/community-edition#2269]
Use case: I like to have github dashboard open in a tab but Github doesn't refresh itself except the bell icon.

### Expected behavior

Add a per-tab setting to refresh the tab every x minutes. This could be handy on Github dashboard, StackOverflow etc.

### ENVIRONMENT

> Rambox: v0.6.7

> OS: Win 10 1809

> Arch: x64 or ia32

**Comment by maxerbox** [comment]
PS: you can make a script, like
```js
setInterval(document.location.reload, 1000 * 60 * 10) // every 10 mins
```

**Comment by penCsharpener** [comment]
Sounds cool, but I don't know JavaScript so could you give me more detailed steps how to get there? Where do I put the script?

**Comment by maxerbox** [comment]
You go into the tab where you add services.
Click on the gear on the service you want at the right of your screen, it opens the service option.
Click in advanced settings
Copy past the code above
Save

**Comment by penCsharpener** [comment]
Ah, in that case it might be handy to have a page within RamBox with useful example scripts and not add this as a feature. The scripts are more flexible but too techy for those not familiar with javascript.

**Comment by Corchoneitor** [comment]
Here are some guides here https://github.com/ramboxapp/community-edition/wiki

**Comment by fvulich** [comment]
I'm gonna close this ticket because the js script seems to be a reasonable fix for this issue, feel free to open another ticket if the problem persists.
