### ISSUE TITLE
Ugly new header theme

### ISSUE THREAD

**Issue by drjlm** [ramboxapp/community-edition#2270]
### Steps to reproduce

1. 
2. 
3. 

### Actual behavior

New gray header theme. No options to change. 

https://imgur.com/a/gScHf7k

### ENVIRONMENT

> Rambox: v0.X.X

> OS: Lubuntu 18.04

> Arch: x64

**Comment by maxerbox** [comment]
It's because your are in not disturb.
I agree with you that color is not pretty, orange would be better

**Comment by drjlm** [comment]
I don't think I am in not disturb mode ... does Rambox even have such a feature?

**Comment by 4sStylZ** [comment]
Yes, 

Rambox have this feature.
Take a look : 

![image](https://user-images.githubusercontent.com/7487411/57511810-66054780-730a-11e9-967b-d17923a9c92a.png)
