### ISSUE TITLE
Rambox does not open after an update or a fresh install since 0.6.3

### ISSUE THREAD

**Issue by FXlife** [ramboxapp/community-edition#2271]
### Steps to reproduce

1. Install Rambox-0.6.3-linux-i386.deb and open or use
2. Update to Rambox-0.6.6-linux-i386.deb or later / Remove Rambox-0.6.3-linux-i386.deb then install Rambox-0.6.6-linux-i386.deb or later
3. Open Rambox from the start menu

### Expected behavior

Opening the software

### Actual behavior

Nothing, even in the task manager or in notifications tab

### ENVIRONMENT

LXDE

> Rambox: v0.6.6 or later

> OS: Debian 9 Stable

> Arch: ia32

**Comment by maxerbox** [comment]
Delete everything in ~/.config/Rambox

**Comment by FXlife** [comment]
> Delete everything in ~/.config/Rambox
> (You will loose your Rambox data)

Thanks for the reply, but it's not working either. I removed Rambox then I deleted the folder ~/.config/Rambox .

**Comment by Corchoneitor** [comment]
@saenzramiro can you take a look at this?
