### ISSUE TITLE
IRCCloud does not show notification badge

### ISSUE THREAD

**Issue by cjohnston1158** [ramboxapp/community-edition#2272]
### Steps to reproduce

1. Login to IRC Cloud.. 
2. Receive some sort of highlight

### Expected behavior

Visual indicator of new message

### Actual behavior

No visual indicator

### ENVIRONMENT

> Rambox: v0.6.7

> OS: OSX 10.14.4

**Comment by Corchoneitor** [comment]
Hi @cjohnston1158.

Try adding this Custom Code.

1. Go to Rambox tab.pen the Configure window for IRC Cloud

**Comment by Corchoneitor** [comment]
Hi @cjohnston1158.

Unfortunately, IRC Cloud badges changed somehow and the "checkUnread" function we used is no longer working. We'll have a look at it.

If anyone else has figured it out, please let us know.

Thanks!

**Comment by cjohnston1158** [comment]
@Corchoneitor I asked about this and the irccloud team suggested that it should be:

t=[].map ...

**Comment by fvulich** [comment]
Does this issue persist in v0.7.3?

**Comment by cjohnston1158** [comment]
@fvulich I'm on Version: 0.7.4 and still see it. Was there a specific change that you think could be related?

**Comment by fvulich** [comment]
The unreadCode was updated to other version, but that version seems to be outdated as well. Here I leave the old code, it could be a starting point for someone who wants to update it.

```
function checkUnread() {
    var t = 0;
    [].map.call(document.querySelectorAll(".bufferBadges > .badge"), n => n.textContent ? parseInt(n.textContent, 10) : 0).reduce((x, y) => x + y, 0);
    updateBadge(t)
}

function updateBadge(a) {
    a >= 1 ? rambox.setUnreadCount(a) : rambox.clearUnreadCount()
}
setInterval(checkUnread, 3e3);
```

**Comment by fvulich** [comment]
Please, if someone fixes it share the code here and I will update it in our database.

**Comment by cjohnston1158** [comment]
This seems to be working for me if I add it to Advanced:

`function checkUnread() {
    var title = document.title;
    var e = title.match(/^\((\d+)\)/);
    updateBadge(e[1]?parseInt(e[1]):0);
}

function updateBadge(e) {
    1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()
}
setInterval(checkUnread, 3e3);`

**Comment by fvulich** [comment]
That's great, thanks for your contribution. 

``` 
function checkUnread(){var e=document.title.match(/^\((\d+)\)/)[1];updateBadge(e?parseInt(e):0)}function updateBadge(e){1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3e3);
```

Could you check if this minimized version of your code still works?

**Comment by cjohnston1158** [comment]
I had tried doing that too, but it won't clear alerts because it errors on getting [1]


Uncaught TypeError: Cannot read property '1' of null at checkUnread (<anonymous>:1:403)

**Comment by fvulich** [comment]
Ok, could you try this one? 
`function checkUnread(){var e="",a=document.title.match(/^\((\d+)\)/);try{e=a[1]}catch(e){}updateBadge(e?parseInt(e):0)}function updateBadge(e){1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3e3);`

**Comment by cjohnston1158** [comment]
So far it looks ok

**Comment by fvulich** [comment]
I updated the service, please restart Rambox CE to get the changes (v0.7.4 and v0.7.5) and please tell me if it's working as it should.

**Comment by cjohnston1158** [comment]
So far so good. Has worked fine on two machines with two different OS. Thanks for your help @fvulich

**Comment by fvulich** [comment]
That's great. Have nice day!
