### ISSUE TITLE
whatsapp latency very high

### ISSUE THREAD

**Issue by riedoi** [ramboxapp/community-edition#2273]
Whatsapp is very slow for me, the latency between keyboard input and app is very high. Same for changing a chat window or searching for GIFS.. more or less everything is slow, but the rest works fine (gmail, telegram, outlook)

- did clear the cache and clear the local storage - no change

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> linux x64 4.15.0-29deepin-generic

**Comment by Corchoneitor** [comment]
Hi @riedoi.

Happens to me sometimes, and mostly in whatsapp. We'll investigate this issue.

Thanks!

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
