### ISSUE TITLE
Rambox Google Duo and Whatsapp does not find camera

### ISSUE THREAD

**Issue by akash-258** [ramboxapp/community-edition#2274]
Duo:
Under User Settings -> Sources -> Camera it says "No camera found". Microphone and Speaker are detected. The standard Duo website however finds the camera and video calls work. Browser is Firefox 66.0.5.
Whatsapp:
Same issue , it cant detect my camera but works in browser
 
ENVIRONMENT

> Rambox: v0.6.7

> OS: Linuxmint 19.1 kernel 4.15.0-48

> Arch: x64

**Comment by maxerbox** [comment]
Snap package ?

**Comment by akash-258** [comment]
> Snap package ?

yes

**Comment by akash-258** [comment]
The problem solved . All i did was uninstall the snap version and installed the deb file from github .
