### ISSUE TITLE
Pass code don't work

### ISSUE THREAD

**Issue by ascer0** [ramboxapp/community-edition#2275]
### Steps to reproduce

1. lunch rambox
2. unlock with pass code 
3. press f2 to lock when stay in any service (whatsapp and messenger try out) and prompt alert tu lock say yes .. and... nothing happen

### ENVIRONMENT

> Rambox: v0.6.7

> OS: Windows 7 pro x64

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @ascer0.

Happens as you described. Thanks for your report!
