### ISSUE TITLE
Rambox window always open minimized

### ISSUE THREAD

**Issue by kreuzman** [ramboxapp/community-edition#2277]
### Steps to reproduce

1. Start Rambox
2. Close window
3. Press Show/Hide Window button on tray icon

### Expected behavior

Rambox window is opened and visible.

### Actual behavior

Rambox window is opened but minimized.

### ENVIRONMENT

> Rambox: 0.6.7

> OS: linux (x64)

> Arch: x64

**Comment by cedmeister** [comment]
+1

Version: 0.6.7
Plattform: Ubuntu 19.04

**Comment by Corchoneitor** [comment]
Hi guys!

Let's see if this is fixed when https://github.com/ramboxapp/community-edition/commit/6b1fb166a32e2288f72df60a6540a6741cf0a680 gets released.

**Comment by roman-yagodin** [comment]
+1

Version: 0.6.9
Platform: LMDE 3 Cindy (Debian 9) x64

**Comment by kreuzman** [comment]
Hi @Corchoneitor ,

I'm trying version 0.6.9 (commit https://github.com/ramboxapp/community-edition/commit/6b1fb166a32e2288f72df60a6540a6741cf0a680 should be included from 0.6.8) and problem stays the same.

**Comment by zazy** [comment]
I have this same problem on Ubuntu 18.04 LTS. Futhermore if you choose not to show icon in taskbar from settings then there is no way tu access the application windows. You have to close it and run it again. When Alt + Tab is pressed application is not even listed.
