### ISSUE TITLE
RocketChat Desktop Notification No Longer Working After 0.6.3 MacOS

### ISSUE THREAD

**Issue by Nosferous** [ramboxapp/community-edition#2278]
### Steps to reproduce

1. Install and run any version of Rambox 0.6.4 - 0.6.7
2. Connect Rambox to Rocket Chat Service
3. In your RocketChat service + Logged into a user
4. Click on your account
5. Click My Account
6. Preferences Section of left side-bar
7. Notifications
8. Click Test Desktop Notifications

### Expected behavior

Upper right-hand corner MacOS Menu bar near Notification Center a box should appear with  notification.

Screenshot of Working Behavior in v0.6.3 last confirmed working version:
![ProperWorkingNotification](https://user-images.githubusercontent.com/22967603/57731390-6590e780-764f-11e9-985f-3894373512a1.png)

### Actual behavior

Nothing happens after clicking Test Notification

### ENVIRONMENT

> Last Working In Rambox: v0.6.3
> Confirmed Not Working In Rambox: v0.6.4 - v0.6.9

> OS: 10.11.6 (El Capitan) - 10.14.6 (Mojave)

> Arch: x64

Also confirmed working in latest Rocket Chat Electron app.

**Comment by wjaynay** [comment]
Also having this issue in recent update to Rambox. Hopefully we see this bug fixed in next update.

**Comment by Nosferous** [comment]
Still an issue. 
Stale bot is stale, can we close it?

**Comment by Nosferous** [comment]
Confirmed also an issue with listed versions of Rambox in original description in Mojave 10.14.6
