### ISSUE TITLE
centos7 rambox minimize button disappears

### ISSUE THREAD

**Issue by funixz** [ramboxapp/community-edition#2279]
### Steps to reproduce

1. start rambox 0.6.7 in centos7 default gnome desktop
2. see there is no minimize button on the window
3. that's it

### Expected behavior

to see and be able to use the minimize button

### Actual behavior

there is no minimize button, unless I quit and restart rambox

### ENVIRONMENT

> Rambox: v0.6.7

> OS: CentOS Linux release 7.6.1810

> Arch: x64

**Comment by LucesEnBabel** [comment]
I also have this problem.

Rambox:
```
Version: 0.6.9
Platform: linux (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0
```

Distro:
```
OS: elementary OS 5.0 Juno x86_64 
Kernel: 5.3.2-050302-generic 
DE: Pantheon 
WM: Mutter(Gala)
```

**Comment by cjdg** [comment]
i also has the same behaviour on ubuntu 19.10 
![Selección_005](https://user-images.githubusercontent.com/5726836/73042544-22665580-3e27-11ea-8dce-1596374454b6.png)

**Comment by fvulich** [comment]
Are you still having this issue in v0.7.5?
