### ISSUE TITLE
Skype's loggin page is in Arabian Language

### ISSUE THREAD

**Issue by MatiasGieco** [ramboxapp/community-edition#2280]
Hi! My computer is in spanish (or english in some programs), but when I open Skype to loging it shows in arabian language. 
Really difficult to use it.
I attach an image as you can see it.
 
Sincerely
Matías

![image](https://user-images.githubusercontent.com/46597282/58017734-4f63ab00-7ad7-11e9-9010-3cbf4b83dea6.png)

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> darwin x64 18.6.0

**Comment by GuxMartin** [comment]
Same in Ubuntu 19.04
> Rambox 0.6.7
> Electron 4.1.4
> linux x64 5.0.0-15-generic

**Comment by maxerbox** [comment]
Are you located in an Arabian speaking country ?
Try setting the Rambox language to Spain if it's not already set, and then reload
Try to also set it to english.

**Comment by MatiasGieco** [comment]
Hi @maxerbox 
No, I'm in Argentina :)
I had the language set to Spanish when I reported it (login in Arabian).
Now I set it to English and the login is in English too (and I could login).
I have no problems to use it in English, but I think is a problem for no speakers.

Thanks, best regards.

**Comment by Corchoneitor** [comment]
Hi.

I'm also from Argentina and I always had this issue with Rambox + Skype.

Further investigation lead me to this conclution:
Skype on web (using Chrome) uses "es" as language. But Skype on Rambox is trying to use "es-419" (Spanish-Latin America).
According to this [FAQ](https://support.skype.com/en/faq/FA34781/what-languages-are-supported-in-skype-on-desktop), Skype does not recognize "es-419" then I suspect it's selecting Arabic incorrectly.

I think this is mainly Skype error.
