### ISSUE TITLE
Audio Doesnt Work

### ISSUE THREAD

**Issue by xsudiptaster** [ramboxapp/community-edition#2282]
I can't hear to calls or videos sent on WhatsApp. 

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> darwin x64 18.6.0

**Comment by Corchoneitor** [comment]
Hi @xsudiptaster.

Are you sure you have the Do Not Disturb option disabled? You can check that in the Rambox tab, right at the top is the Do Not Disturb button.

If it's not the case, let us know.

**Comment by vlameiras** [comment]
I was having the exact same issue and the Do Not Disturb option did the trick.

Thanks @xsudiptaster !

**Comment by xsudiptaster** [comment]
Thanks, Ramboxapp/Community-Edition, This was the issue.
