### ISSUE TITLE
Links open the pages on chrome not in rambox

### ISSUE THREAD

**Issue by leopucci** [ramboxapp/community-edition#2285]
Rambox 0.6.7
Win 10 64bits

![Untitled](https://user-images.githubusercontent.com/38509299/58357793-9395d900-7e52-11e9-9f3f-a41d95f0cfe3.gif)

**Comment by Corchoneitor** [comment]
Hi @leopucci.

That's the actual behavior (inside Rambox) for every app link that opens a "_blank" page. Currently there's a PR #2102 trying to achieve internal linking.

**Comment by leopucci** [comment]
Nice...

I searched among issues and just found text issues..
I wanted to upload an image, as I think that could be more helpful
understanding the behavior

Em sex, 31 de mai de 2019 às 14:51, Juan Manuel Gonzalez Alama <
notifications@github.com> escreveu:

**Comment by MiguelNdeCarvalho** [comment]
Hey,
I am here just to say that I am having the same issue. Keep good work guys!
Thanks,
Miguel de Carvalho

**Comment by drjlm** [comment]
Same issue. Ubuntu 19.04.
