### ISSUE TITLE
No windows titles, RB gone crazy

### ISSUE THREAD

**Issue by mbnoimi** [ramboxapp/community-edition#2287]
Hi,

The interface responsive is very slow, all the windows titles disappear and all the services size is very small (unable to maximize them even if I call reload)

* Rambox 0.6.7
* Electron 4.1.4
* linux x64 4.15.0-50-generic

![image](https://user-images.githubusercontent.com/284547/58411651-6c6f1f80-807d-11e9-890c-48d0da3a4b46.png)

![image](https://user-images.githubusercontent.com/284547/58411674-798c0e80-807d-11e9-904d-da9422ec07f5.png)

**Comment by Corchoneitor** [comment]
Hi @mbnoimi.

Weird. Is this happening from start or when you do something inside Rambox? Have you tried reinstalling Rambox?

**Comment by mbnoimi** [comment]
> Hi @mbnoimi.
> 
> Weird. Is this happening from start or when you do something inside Rambox? Have you tried reinstalling Rambox?

I did reinstall it, still occurs!

**Comment by mbnoimi** [comment]
Oh yeh, I discovered which procedure trigger the bug.

This occurs just in case I enable "Yahoo Messenger" in "ALIGN Right"

**Comment by mbnoimi** [comment]
BTW, An another bug I occurs I believe it's related to this bug.

I'm no longer able to remove any service because RB keeps show "Removing..." windows to the infinity!
![image](https://user-images.githubusercontent.com/284547/58742834-41931b80-842f-11e9-977f-82b256fd8397.png)

**Comment by Corchoneitor** [comment]
Since Yahoo Messenger is no longer available, we won't fix this issue. If this happens with another service, create another issue :).

"Removing..." to infinity was fixed in #2107. Let's wait until it's released.
