### ISSUE TITLE
WhatsApp and Android Messages Unread Counter Not Working

### ISSUE THREAD

**Issue by themagpieswarble** [ramboxapp/community-edition#2289]
### Steps to reproduce

1. Open Rambox on Windows 10 
2. Add WhatsApp service (along with other services if you want to replicate my issue exactly. Make WhatsApp the 3rd service in the line of tabs)
3. Ensure that Notifications are turned on for the service
4. Receive a Whatsapp Notification

### Expected behavior

Whatsapp Unread Counter Badge appears on the WhatsApp tab in Rambox alerting user to unread message. (Same behavior when reproducing steps above using Google Messages)

### Actual behavior

WhatsApp Unread Counter Badge does not appear on the Whatsapp tab in Rambox. (Same behavior when reproducing steps above using Google Messages)

### ENVIRONMENT

> Rambox: v0.6.7 

> OS: Windows 10

> Arch: x64

### COMMENTS

This does not happen with my two Slack services that I use. Only Whatsapp and Google Messages do not display the unread. 

Attached a screenshot of my Services settings on the Rambox home page and also of the WhatsApp Web settings and Google Messages settings in case that affects it (the lighter colored one is Whatsapp the dark mode one is Google Messages.) 

![2019-05-31 15_05_05-Rambox](https://user-images.githubusercontent.com/42039852/58737189-81b5b800-83b5-11e9-804f-142344a8b5e6.png)
![2019-05-31 15_04_56-Rambox](https://user-images.githubusercontent.com/42039852/58737190-81b5b800-83b5-11e9-9c63-aef23fb97c59.png)
![2019-05-31 15_04_05-Rambox - Android Messages](https://user-images.githubusercontent.com/42039852/58737192-824e4e80-83b5-11e9-86ac-848ed361b558.png)
![2019-05-31 15_03_31-Rambox - WhatsApp](https://user-images.githubusercontent.com/42039852/58737193-824e4e80-83b5-11e9-9256-cf16f22e3916.png)
![2019-05-31 15_03_20-Rambox](https://user-images.githubusercontent.com/42039852/58737194-824e4e80-83b5-11e9-9362-d7d03d46128f.png)

**Comment by Corchoneitor** [comment]
Hi @themagpieswarble

I notice this today, only in Whatsapp. Will be investigating this ASAP.

**Comment by themagpieswarble** [comment]
Thank you!

**Comment by Corchoneitor** [comment]
Try building with this fix until this is included in next release.

Or you can put this snippet as Custom Code for WhatsApp:
`function checkUnread(){const elements = document.querySelectorAll(\'.P6z4j, .unread\');let count = 0;for (let i = 0; i < elements.length; i++) {if (elements[i].querySelectorAll(\'*[data-icon="muted"]\').length === 0) {count++;}}updateBadge(count);}function updateBadge(count){if(count && count>=1){rambox.setUnreadCount(count);}else{rambox.clearUnreadCount();}}setInterval(checkUnread, 1e3);(async()=>{try{const a=await window.navigator.serviceWorker.getRegistrations();for(const b of a)b.unregister()}catch(a){}})();`

**Comment by yafp** [comment]
@Corchoneitor 
thx - this seems to work.

**Comment by themagpieswarble** [comment]
Unfortunately the custom code didn't seem to work.  Put it in, reloaded WhatsApp and still doesn't show unread badges. Restarted Rambox too and that didn't work either. Tried it on Google Messages Custom Code which didn't work either. 

![2019-06-03 07_28_47-Rambox](https://user-images.githubusercontent.com/42039852/58809717-48599400-85d1-11e9-975b-a8509ee6eb8e.png)

**Comment by Gaafgeel** [comment]
Unfortunately it didn't work for me neither.

**Comment by Dareiko** [comment]
Same for me, I have two account and both didn't work 👎

**Comment by themagpieswarble** [comment]
@Corchoneitor why was this issue closed? Has it been fixed? Sorry I'm unfamiliar with how GitHub works.

**Comment by maxerbox** [comment]
Yup, it means that is it fixed and will come in the next release

**Comment by themagpieswarble** [comment]
Thank you!

**Comment by themagpieswarble** [comment]
Updated to the build from 2 days ago (0.6.9 win32 x64) and WhatsApp counter still isn't working.
