### ISSUE TITLE
New whatsapp messages no longer change the tray icon to red-blue. Also, still can't properly minimize Rambox.

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#2292]
Well, the issue about being unable to minimize is not so new, I hope everyone knows it already. It simply stays in the alt-tab menu, forever. The other issue is fresher, it started a few days ago I believe? Not sure. Anyway, the problem is, I receive new message on whatsapp, but there is no notification on Rambox. I know that I can't get popups because I am on Windows 7, but even the tray icon stays the same color. As a result, I keep replying to people late, it's very frustrating. I have to manually check for updates, if I don't notice the vibration from my smartphone. Not cool.

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> win32 x64 6.1.7601

**Comment by Corchoneitor** [comment]
Duplicate #2289

**Comment by ericzolf** [comment]
And "Well, the issue about being unable to minimize is not so new, I hope everyone knows it already. It simply stays in the alt-tab menu, forever." is, I guess, a duplicate of  Rambox dissapears after minimize Window (Windows) #2253
