### ISSUE TITLE
Windows: Unread counter for Slack is only working when not minized to tray

### ISSUE THREAD

**Issue by CombeeMike** [ramboxapp/community-edition#2293]
## Steps to reproduce

1. Minimize Rambox to tray
2. Receive messages in Slack

## Expected behavior

The Rambox tray icon should turn red due to unread messages in Slack.
Actual behavior

Windows notifications for new messages are shown but the tray icon does not turn red.
When opening Rambox, the unread counter is not shown on the Slack tab initially but shows up after some delay.

## ENVIRONMENT

> Rambox: v0.6.4
> OS: Windows 10
> Arch: x64

Duplicate of https://github.com/ramboxapp/community-edition/issues/2189 which has been closed by bot. As mentioned there, this is still not working on my machines.

**Comment by Corchoneitor** [comment]
Hi @CombeeMike.

Please, update manually to [v0.6.9](https://github.com/ramboxapp/community-edition/releases/tag/0.6.9). Rambox CE had some fixes since v0.6.4.

I'll close this issue, but if your problem persists, please reopen it.
