### ISSUE TITLE
Huge disk usage

### ISSUE THREAD

**Issue by FlorentCoppint** [ramboxapp/community-edition#2295]
Hi,

I'm using Rambox 0.6.7 on Ubuntu 19.04.
I have 6 services : 1 Messenger, 2 WhatsApp, 1 Tweetdeck, 1 Teams and 1 custom (simple html page).

Is it normal that Rambox is using more than 1 GB on my disk ?

```
$ du -h --max-depth=1 ~/.config/Rambox/ | sort -rh
1,2G	/home/florent/.config/Rambox/
1,1G	/home/florent/.config/Rambox/Partitions
4,8M	/home/florent/.config/Rambox/Cache
4,0K	/home/florent/.config/Rambox/Local Storage
```

```
$ du -h --max-depth=1 ~/.config/Rambox/Partitions/ | sort -rh
1,1G	/home/florent/.config/Rambox/Partitions/
186M	/home/florent/.config/Rambox/Partitions/tweetdeck_6_auth0%7C5a292fac042e340348a27cb8
175M	/home/florent/.config/Rambox/Partitions/teams_7_auth0%7C5a292fac042e340348a27cb8
149M	/home/florent/.config/Rambox/Partitions/messenger_1
139M	/home/florent/.config/Rambox/Partitions/whatsapp_2_auth0%7C5a292fac042e340348a27cb8
93M	/home/florent/.config/Rambox/Partitions/tweetdeck_6
86M	/home/florent/.config/Rambox/Partitions/whatsapp_3
82M	/home/florent/.config/Rambox/Partitions/whatsapp_2
79M	/home/florent/.config/Rambox/Partitions/whatsapp_3_auth0%7C5a292fac042e340348a27cb8
77M	/home/florent/.config/Rambox/Partitions/messenger_1_auth0%7C5a292fac042e340348a27cb8
60M	/home/florent/.config/Rambox/Partitions/custom_5
2,4M	/home/florent/.config/Rambox/Partitions/rambox
1,5M	/home/florent/.config/Rambox/Partitions/custom_5_auth0%7C5a292fac042e340348a27cb8
```

Is there any way to reduce it ?

Thank you.
Florent

**Comment by Corchoneitor** [comment]
Hi @FlorentCoppint.

Partitions are like "session data" each service uses: the more you use a service, the more space will take. Also when removing a service, Rambox CE do not clean up it's Partition folder (this is a known issue). But this is not your case, as you shown.

Sometimes services save useless data inside Partitions. If you want to lower their disk usage, you could delete each service's partition folder. This is not recomended, but I did this few times with no side effects.
