### ISSUE TITLE
screenshots not shown for rocket chat

### ISSUE THREAD

**Issue by gk100297** [ramboxapp/community-edition#2297]
when i get screenshots via rocketchat then they will remain diffuse. downloading them does not work either, just opening a blank browser page

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> win32 x64 10.0.17134

**Comment by Corchoneitor** [comment]
Hi @gk100297.

Please, update manually to [v0.6.9](https://github.com/ramboxapp/community-edition/releases/tag/0.6.9).

That been said, I cannot reproduce it. Is this happening only with screenshots? I tested also with Chrome and the only odd thing I found is clicking on "download" redirects you to the image itself.
