### ISSUE TITLE
Reddit not working

### ISSUE THREAD

**Issue by nasif25** [ramboxapp/community-edition#2298]
I simply added reddit in my rambox. I just installed rambox and added whatsapp, messenger, skype, discord, telegram, gmail. Then I added reddit, but it's just a white blank screen! No login page, no nothing. I've checked my internet and other things work just fine (including other services through rambox). But reddit is just not working. I'm giving you a screenshot. I'm pretty sure this is not normal. https://ibb.co/vZHs7RJ

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> linux x64 4.4.0-141-generic

**Comment by Corchoneitor** [comment]
Hi @nasif25.

Please, update manually to [v0.6.9](https://github.com/ramboxapp/community-edition/releases/tag/0.6.9).

That been said, are you able to open the Developers Tools to see if there's some error showing when loading Reddit?

**Comment by nasif25** [comment]
IT WORKS NOW!!!

I've updated Rambox. Earlier I was using it via an appimage, can't remeber
where I got the appimage from. Now I downloaded the debian version from the
link you provided, and tried to add reddit. and it works just fine. ^_^
