### ISSUE TITLE
Microsoft Teams one to one calls do not work

### ISSUE THREAD

**Issue by micd** [ramboxapp/community-edition#2299]
Direct one to one calls via Microsoft Teams are not supported in Rambox v. 0.6.8.

It had been fixed once, but after some changes it got back to not working state. Group or meeting calls work correctly.

## Steps to reproduce

1. Open chat with another person
2. Use call icon to call person

### Expected behavior

Call is being performed sucessfully

### Actual behavior

Popup with following message:

"Try a different browser
This feature isn't available yet for your browser. Try the web app with Microsoft Edge or Google Chrome, or switch to the desktop app."

is shown

### ENVIRONMENT

> Rambox: v0.6.8

> OS: UBUNTU

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @micd.

Seems to be a Teams known [issue](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/36203647-audio-calls-stopped-working-in-google-chrome). Also you can read [this article](https://techcommunity.microsoft.com/t5/Microsoft-Teams/TEAMS-and-LINUX-The-Future-is-Now/td-p/251876)

Let's hope they fix this again, as for me it's their problem.

**Comment by micd** [comment]
Thank you @Corchoneitor !
