### ISSUE TITLE
Signing into Auth0 hangs with an ok message.

### ISSUE THREAD

**Issue by burnsjake** [ramboxapp/community-edition#2301]
I tried to "login" via the auth0 login button on the upper right. I log in and a window shows up that only says OK. I cannot get rid of the window and I cannot access any services. If I close rambox and re-open, I need to re-sign into all of my services.

	
	-
	> Rambox 0.6.8
	> Electron 4.1.4
	> darwin x64 18.6.0

**Comment by Corchoneitor** [comment]
Hi @burnsjake.

Are you able to open de Developer tool and see if there's an error happening there? I think something is wrong with auth0 redirection.
