### ISSUE TITLE
"X" icon behave as "-" icon !

### ISSUE THREAD

**Issue by Nokia808** [ramboxapp/community-edition#2303]
### Steps to reproduce

1. open Rambox
2. at upper right corner there are 3 icons: - , minimize/maximize , X (close)
3. click on X icon

### Expected behavior

<program window closed but program still run & it's try icon upper in system panel>

### Actual behavior
it behave exactly as if "-" icon clicked (not X icon) !

### ENVIRONMENT

<Fedora 30 X 64 bit Cinnamon edition with Rambox AppImage installation>

> Rambox: v0.6.8

> OS: Fedora Linux

> Arch: x64

**Comment by AXeL-dev** [comment]
You can simply change this behavior in Rambox settings (see the picture below).

![Capture d'écran 2019-06-17 15:44:53](https://user-images.githubusercontent.com/30635693/59613706-4a663b80-9117-11e9-9c93-7978867a41e0.png)

**Comment by Nokia808** [comment]
@AXeL-dev 
Hi. It does not work at all !! I tried "Keep in try" but behave as if it were "Keep in try &/or taskbar" !!

I have to change "Display behaviour" from "Show in Taskbar & Try Icon" into "Show in Try Icon".  But when I did this, I discovered other bug ! The new bug is that "Show/Hide Window" option of right-click of Try Icon does not work at all !! I will open new bug about this. 

Very buggy release !

**Comment by AXeL-dev** [comment]
@Nokia808 you should try **Quit** if you want the window to close when you click the X button.

**Comment by Nokia808** [comment]
@AXeL-dev 

No ! There was no such thing in previous versions ! In previous versions, click exit resulted in sending program to system try icon & program continue to run NOT EXIT !

**Comment by Corchoneitor** [comment]
Hi @Nokia808.

As @AXeL-dev explained, the "close" icon works as you may configure it. You are right about the other issue with "Show/Hide Window", which you already reported in #2315.

I'll close this issue, but feel free to re-open it if you think it should be.

**Comment by Nokia808** [comment]
@Corchoneitor 
Dear can you inform me kindly what is the diffirence between:
1) "Show in Taskbar & Try Icon" + "Keep in try and/or taskbar"
&
2) "Show in Taskbar & Try Icon" + "Keep in try"

They are the same when I tried them ! No any change !! Is this normal behaviour ? Certainly not ! Please try them from your side ......
