### ISSUE TITLE
Rambox not utilize Tor proxy !

### ISSUE THREAD

**Issue by Nokia808** [ramboxapp/community-edition#2304]
### Steps to reproduce

1. install system Tor package & activate it
2. open Rambox & set proxy at 127.0.0.1 & port: 9050 then save & exit
3. reopen Rambox

### Expected behavior

<Should communicate with already enabled services via system Tor package>

### Actual behavior

<No communication: I tried ICQ & Whatsapp ! But other applications like Icecat browser can utilize system Tor package with same setting: 127.0.0.1/9050>

### ENVIRONMENT

<Cinnamon DE with Rambox AppImage installation>

> Rambox: v0.6.8

> OS: Linux Fedora 30

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @Nokia808.

Are you able to use Icecat, Tor and Whatsapp? If that's the case, then maybe we should do something about that in Rambox. If not, then it's an internal restriction of the service.

**Comment by Nokia808** [comment]
@Corchoneitor 
Hi. There is more precise test I already did it. I tried Protonmail both non-onion & onion services & both of them failed to open the page for enterance of login credentials ! Only blank page ! So, the problem is global - even if whatsapp refuse Tor, because Protonmail accept Tor .....

It is bug within Rambox.

Please disregard whatsapp because it seem that it refuse Tor ....... But as I said it is internal bug within Rambox: try Protonmail which already accept Tor.
