### ISSUE TITLE
Blank Screen on login

### ISSUE THREAD

**Issue by FaRosario** [ramboxapp/community-edition#2305]
### Steps to reproduce

1. Open app
2. Click on login button
3. 

### ENVIRONMENT

> Rambox: v0.6.8

> OS: Win10

> Arch: x64 
![rambox](https://user-images.githubusercontent.com/5143099/59577939-d20a6680-9093-11e9-9ee1-67fef94f7830.png)

![image](https://user-images.githubusercontent.com/5143099/59577965-eea69e80-9093-11e9-98b5-55e0463d17cd.png)

**Comment by Corchoneitor** [comment]
Hi @FaRosario.

Please update manually to [v0.6.9](https://github.com/ramboxapp/community-edition/releases/tag/0.6.9).

That been said, Auth0 login page seems to work fine for me. Are you behind a proxy? Are you able to see the Developer Console to see if there is any error?

Thanks!

**Comment by FaRosario** [comment]
Thanks for answer

After various win10 updates the page login worked fine.



Get Outlook for Android

________________________________

**Comment by Corchoneitor** [comment]
Glad to hear!

Closing.
