### ISSUE TITLE
Rambox opens links in default browser on mac osx

### ISSUE THREAD

**Issue by hunglinh8989** [ramboxapp/community-edition#2307]
Steps to reproduce:
Click a link on a link.

Expected behavior:
Link should only open in default browser

Actual behavior:
New blank tab is opened in Rambox and default browser regardless of link URL

ENVIRONMENT

Rambox: 0.6.8
OS: Mac Mojave 10.14.4
Arch: x64

**Comment by Corchoneitor** [comment]
Hi @hunglinh8989.

Is this happening for all links across services or in a particular service/link?

**Comment by hunglinh8989** [comment]
> Hi @hunglinh8989.
> 
> Is this happening for all links across services or in a particular service/link?
This happens with all links through all services ~~ :( especially at shopee.vn link
