### ISSUE TITLE
Discord tries to connect

### ISSUE THREAD

**Issue by david-camden** [ramboxapp/community-edition#2308]
when starting Rambox, the discord messenger tries to connect and stays at this state.
at mobile i am connected immediately and alltime.

### Steps to reproduce

1. open rambox
2. have a discord tab with discord autologin
3. let it try to connect

### Expected behavior

login into the servers and being able to chat

### Actual behavior

stays at the state "connecting" forever. no reload helps. even removing and readding of the tab doesnt help.

### ENVIRONMENT

> Rambox: v0.6.7

> OS: Win10 Pro

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @david-camden.

Please, update manually to [v0.6.9](https://github.com/ramboxapp/community-edition/releases/tag/0.6.9).

Let's see if the issue persists, as I'm on v0.6.9 and Discord works fine.
