### ISSUE TITLE
facebook messenger: not available at the moment

### ISSUE THREAD

**Issue by david-camden** [ramboxapp/community-edition#2309]
being online at the facebook messenger but over the userlist appears
"the messenger is not available at the moment" (Der Messenger ist derzeit nicht verfügbar)

### Steps to reproduce

1. start Rambox
2. have a messenger tab, logged in
3. chat

### Expected behavior

no warning above the userlist

### Actual behavior

warning "the messenger is not available at the moment" (Der Messenger ist derzeit nicht verfügbar) in a red warning bar above the userlist on the left side.
but it works, i can chat and everything.

### ENVIRONMENT

> Rambox: v0.6.7

> OS: Win10 Pro

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @david-camden.

Please, update manually to [v0.6.9](https://github.com/ramboxapp/community-edition/releases/tag/0.6.9).

I cannot reproduce your problem. Let's discard Rambox CE version as cause.
