### ISSUE TITLE
MySMS - logs out after every boot

### ISSUE THREAD

**Issue by drjlm** [ramboxapp/community-edition#2311]
### Steps to reproduce

1. Turn off computer
2. Turn on computer

### Expected behavior

MySMS session remains active

### Actual behavior

MySMS has logged out. Need to log in again to continue using. 

### ENVIRONMENT

Ubuntu 19.04

> Rambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32
x64

**Comment by Corchoneitor** [comment]
Hi @drjlm.

Is this working as expected in Chrome web version? Or it's needed a re-login also?
