### ISSUE TITLE
Notification Logo missing on notification messages

### ISSUE THREAD

**Issue by Redirts** [ramboxapp/community-edition#2312]
### Steps to reproduce

Wait until a notification is fired from any of the Rambox windows (i.e. Gmail, Whatsapp, etc.)

### Expected behavior

Notification shown with text and Logo of the app that fired the notification

### Actual behavior
Notification shown but with Logo part empty/blank

### ENVIRONMENT

> Rambox: v0.6.8

> OS: Windows 10 Pro

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @Redirts.

Please update manually to [v0.6.9](https://github.com/ramboxapp/community-edition/releases/tag/0.6.9).

That been said, I have Windows 10 and notifications are shown as expected: for example, Whatsapp notifications shows the contact avatar and the message text. Also tested with Slack and works fine for me.

![image](https://user-images.githubusercontent.com/2912593/60469754-44527d80-9c34-11e9-8001-9203c8a280a5.png)
