### ISSUE TITLE
Telegram stopped working today (Russian RKN censorship issue)

### ISSUE THREAD

**Issue by vit1-irk** [ramboxapp/community-edition#2313]
#### ENVIRONMENT
> Rambox: v0.6.8
> OS: linux x86_64

Telegram Web normally is blocked in Russia because of government censorship. But in Rambox it worked, because it seems Rambox added their own proxy to access Telegram servers.

Just today Telegram inside Rambox stopped working saying there is no connection. But it works well with VPN turned on. Looks like government blocked the Rambox proxy somehow.

So, please fix it with new version either by changing IP of Telegram proxy or by allowing to set up your own proxy settings for each provided service.

**Comment by Corchoneitor** [comment]
Hi @vit1-irk.

I don't think we are using any proxy for Telegram specifically.

What you can do is configure the Proxy option under Preferences. There's a link with some free proxy servers you can use.
