### ISSUE TITLE
Error when trying to relaunch-update into 0.6.9

### ISSUE THREAD

**Issue by OmriSama** [ramboxapp/community-edition#2315]
### Steps to reproduce
Launched Rambox today and it downloaded the update. When I click "Relaunch Now", I get this error message:
![image](https://user-images.githubusercontent.com/10534779/60034127-c18f5880-965e-11e9-9949-502b1dcf8e70.png)

### Expected behavior

Should be able to update.

### Actual behavior

Get an error message.

### ENVIRONMENT

```
Version: 0.6.7
Platform: win32 (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0
```

**Comment by OmriSama** [comment]
Currently trying to re-install Rambox with the latest version.

**Comment by OmriSama** [comment]
Stopping the application and re-installing worked, no complaints now.

**Comment by HesHeatingUp** [comment]
Were you able to actually get the update to work? I can force quit and re-launch but it continues to give me the new version pop-up and error message you posted above. Thanks!

**Comment by OmriSama** [comment]
> 
> 
> Were you able to actually get the update to work? I can force quit and re-launch but it continues to give me the new version pop-up and error message you posted above. Thanks!

@HesHeatingUp after quitting the application, re-installing, and launching, I see no issues.

**Comment by HesHeatingUp** [comment]
@OmriSama thanks - I have done the same and have a working updated version (had to re-load all my chat apps)

**Comment by leitmedium** [comment]
Similar behaviour on macOS. Hitting the relaunch button leads to:
![grafik](https://user-images.githubusercontent.com/305663/60046529-e53ab900-96c7-11e9-93c5-abad973d5249.png)

**Comment by saenzramiro** [comment]
Yes, that error was fixed in this commit: https://github.com/ramboxapp/community-edition/commit/51b4be02d6f129e3e22e2c94f0e2e1a0f118e87e

So, new version 0.6.9 has this fixed. Please, consider relaunching the app manually.
