### ISSUE TITLE
Snap Store updates missing

### ISSUE THREAD

**Issue by ThomasRitter75** [ramboxapp/community-edition#2316]
As the issue template makes no sense here:

The snapcraft store has 0.6.7 as latest version. Please update. Thanks.

**Comment by casperl** [comment]
Ditto

**Comment by casperl** [comment]
Not sure whether Github is the right place to report this issue with the snap packaged version of Rambox CE.  The above message appears, requesting an update.  However, the way to update SNAP packages is not through the APP, but by doing a "sudo snap refresh" after which snap automatically updates the package.  Doing a snap refresh reports all snaps are up to date.  The maintainer of the Rambox snap package will have to update the package.

For info, these are my specs

Ubuntu 19.04
Snap list outputs: rambox  0.6.7  5  stable  ramboxapp* ** -


![image](https://user-images.githubusercontent.com/1303185/60171015-fbe92900-9809-11e9-857d-83ec177c97f5.png)

**Comment by ThomasRitter75** [comment]
@casperl, as seen in #2252, the snap package maintainer is @saenzramiro, the project owner, so this should be the correct place unless he says otherwise. Maybe we need a task to automate snap packet upload on release.

**Comment by undpeter** [comment]
What kind of help do you need to get these updates into the snap store?

**Comment by hyviquel** [comment]
I agree, it would be nice to update the snap store with the latest version.

**Comment by 4selin** [comment]
+1

**Comment by pbek** [comment]
Meanwhile you could do a:

```bash
wget https://github.com/ramboxapp/community-edition/releases/download/0.6.9/Rambox-0.6.9-linux-amd64.snap
snap install Rambox-0.6.9-linux-amd64.snap --dangerous
```
