### ISSUE TITLE
Can't login to Gmail

### ISSUE THREAD

**Issue by eightieskhild** [ramboxapp/community-edition#2317]
### Steps to reproduce

1. Add gmail to a new tab
2. click login
3.  receive new browser tab with gmail login in chromium instead of login for gmail in Rambox

### Expected behavior

Login to gmail from Rambox

### Actual behavior

In Pop!_OS when i try to login to gmail, it opens a new window every time which doesn't allow me to sign into ram box.

### ENVIRONMENT

https://i.imgur.com/VHpDV7M.png

https://i.imgur.com/IJMxvUC.png

**Comment by silnose** [comment]
Same at Windows 10.

**Comment by eightieskhild** [comment]
Eww

**Comment by Corchoneitor** [comment]
This problem occurred when you navigate through google links... then you cannot turn back to the login page as normal, but with a popup.

Fixed. Will be released soon... or build it yourself if you want :).

**Comment by mbbroberg** [comment]
For reference, same issue on MacOS

**Comment by Sir-DEC** [comment]
When will it be released ? Or do you have any workaround ? Gmail is a major service :(

**Comment by StormPooper** [comment]
In the meantime you can right click the service icon, open the dev tools and paste `window.location = "https://accounts.google.com/AccountChooser?service=mail&continue=https://mail.google.com/mail/"` into the console, then hit Enter.

**Comment by aladdin-hub** [comment]
the same issue Win10

**Comment by aladdin-hub** [comment]
> In the meantime you can right click the service icon, open the dev tools and paste `window.location = "https://accounts.google.com/AccountChooser?service=mail&continue=https://mail.google.com/mail/"` into the console, then hit Enter.

can you please explain where to paste? There are "Elements", "Console" etc. tabs. If I should paste in Elements code, how to do it and in what string?

**Comment by fagianijunior** [comment]
@aladdin-hub Paste in console command line, and hit enter.

**Comment by drjlm** [comment]
Any resolution to this? Am using the latest Rambox on Ubuntu 19 and haven't been able to log in to Gmail for months at this stage!

**Comment by drjlm** [comment]
@fagianijunior The dev tools console paste doesn't work for me unfortunately
