### ISSUE TITLE
WebEx teams doesn't remain logged in

### ISSUE THREAD

**Issue by cjohnston1158** [ramboxapp/community-edition#2318]
### Steps to reproduce

1. Login to WebEx teams
2. Restart Rambox

### Expected behavior

Other services (gmail, calendar, twitter, etc) remain logged in when Rambox is restarted, WebEx teams doesn't.

### Actual behavior

Remain logged in like other services

### ENVIRONMENT

> Rambox: v0.6.9

> OS: OS X 10.14.5

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @cjohnston1158.

Actually, WebEx in normal browsers works the same, you must log in even if you close the tab and re-open it. At least it happened to me in Chrome. So nothing to do in Rambox :(.
