### ISSUE TITLE
Wrong url for Android Messages service

### ISSUE THREAD

**Issue by wstrik** [ramboxapp/community-edition#2320]
When opening Android Messages it says:
Messages for web has a new URL
Everything else stays the same, now at messages.google.com/web.
To find it quick, add a bookmark. Learn more

Rambox: v0.6.9

> OS: Winx64

**Comment by Corchoneitor** [comment]
Hi @wstrik.

Sorry, I'm not following you. I add a new Android Messages service and the QR page appears so I can bind with my phone. Can you be more descriptive? Am I missing something?

**Comment by mrbmi513** [comment]
The forwarding to the new URL only sometimes works; half the time it'll appear to work as normal, and the other half of the time it will tell you the service has moved. I've added the new URL as a custom service in the meantime.

**Comment by wstrik** [comment]
Hi @Corchoneitor, I deleted and re-added the service and now it works.
