### ISSUE TITLE
Discord is not loading

### ISSUE THREAD

**Issue by tbraz** [ramboxapp/community-edition#2321]
Discord is not loading after this update. The windows stays blank while everything else loads properly.

How to reproduce:

1. Have discord setup and configured.
2. Launch Rambox

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> darwin x64 18.6.0

**Comment by Corchoneitor** [comment]
Hi @tbraz.

I'm on windows and it works fine. Have you tryed to configure another discord service with v0.6.9?

**Comment by tbraz** [comment]
@Corchoneitor Thank you for the feedback.
You are right, removing discord and setting up again did the trick!
Didn't occur to me to try this, because never had this issue in the past (with Rambox updates).

All good now, closing this non-issue.

Thank you
