### ISSUE TITLE
Fixing Ryver unread count

### ISSUE THREAD

**Issue by fcamblor** [ramboxapp/community-edition#2325]
FYI, Ryver unread count is wrong (the selector takes into consideration some nodes that are not visible)

Just added this custom code snippet in the Advanced > Custom code configuration of Rambox to fix the count :
```
setInterval(function(){
    var unreadCount=0; 
    document.querySelectorAll(".scene-space-tab-button__badge-icon").forEach(el => { 
      if(el.offsetParent !== null){ unreadCount++; } 
    });
    document.querySelectorAll(".scene-space-tab-button__badge-count").forEach(el => {
        if(el.innerText){ unreadCount += Number(el.innerText); }
     });
    rambox.setUnreadCount(unreadCount);
}, 1000);
```

**Comment by Corchoneitor** [comment]
Hi @fcamblor.

Thanks for your report and your suggestion.

I just fixed it based on your code. Will be released soon... or build it yourself if you want :).

**Comment by fcamblor** [comment]
@Corchoneitor Cool thanks !

FYI, you didn't added the `scene-space-tab-button__badge-count` selector in your commit (516fa1c) and it may be helpful since `scene-space-tab-button__badge-icon` class will only be helpful for counting notifications in forums/teams/people discussions.

`scene-space-tab-button__badge-count` additionnally captures number of unread "notifications" (like, forum/topics creations) and should be added to the oveall rambox notifications count.

My 2c
