### ISSUE TITLE
Show/Hide opens window minimized

### ISSUE THREAD

**Issue by brandoningli** [ramboxapp/community-edition#2326]
### Steps to reproduce

1.  Make sure Rambox is hidden
2.  Press Show/Hide from the system tray icons

### Expected behavior
Rambox opens, non-minimized.

### Actual behavior
Rambox appears on my dock minimized. I have to click the icon to reveal the window.

### ENVIRONMENT

> Rambox: v0.6.9 (.deb)

> OS: Ubuntu 18.04.2 / GNOME 3.28.2

> Arch: x64

**Comment by Corchoneitor** [comment]
Duplicate #2277
