### ISSUE TITLE
Open Shared Mailbox in Outlook

### ISSUE THREAD

**Issue by H8to** [ramboxapp/community-edition#2328]
I would like to open multiple Outlook sessions side by side and several shared mailboxes. However Rambox does not support this correctly.

### Steps to reproduce

1. Login to your Microsoft mailbox account
2. Click on the profile icon
3. Click on "Open additional mailbox" (translated)
4. Enter name of mailbox
5. Click OK

### Expected behavior

Load shared mailbox in place within the tab, or create a new one

### Actual behavior
Opens default browser and loads the shared mailbox there

### ENVIRONMENT

> Version: 0.6.9
> Platform: linux (x64)
> Electron: 4.1.4
> Chromium: 69.0.3497.128
> Node: 10.11.0

**Comment by H8to** [comment]
I created a workaround for now.

In the profile settings go to `Avanced -> Custom Code` and add the following:
```
if (window.location.href.indexOf("shared") == -1) {
 window.location.href="https://outlook.office.com/mail/<shared@yourcompany>/inbox";
    }
```
This will redirect to the correct inbox :)

**Comment by Corchoneitor** [comment]
Hi @H8to.

This is a known issue for links inside Rambox :(. #2085 #2285 

Currently there's a PR #2102 trying to achieve internal linking.
