### ISSUE TITLE
Runaway resources after a few minutes of runtime (constant restarts needed)

### ISSUE THREAD

**Issue by joaomcarlos** [ramboxapp/community-edition#2334]
After a few minutes of Rambox running it will slowly creep to 100% CPU usage.
I am using:
- Facebook Messenger
- Gmail
- Slack
- Discord
- WhatsApp
- Outlook 365

Slowly the interfaces will start to become very slow and the fans blasting at full power. Checking HTOP shows the process running wild. Restarting the application solves the problem for a few minutes.

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> linux x64 4.15.0-54-generic

**Comment by fvulich** [comment]
Does this issue persist in v0.7.3?
