### ISSUE TITLE
Discord never remembers session

### ISSUE THREAD

**Issue by joaomcarlos** [ramboxapp/community-edition#2335]
The Discord tab will never remember the session and ask for login everytime I open Rambox.
Other tabs remain useful.

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> linux x64 4.15.0-54-generic

**Comment by fvulich** [comment]
I've been checking and it does remember the session. You could try deleting the app and adding it again.

**Comment by TheBelgarion** [comment]
I got the same problems after the last 2 updates every time i boot my pc I have to login again. 

Current version:
Version: 0.7.2
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by TheBelgarion** [comment]
Deleting Discord Tab in the App and re-adding it fixed the problem.

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
