### ISSUE TITLE
RamBox now captures all keyboard input - can't use Spectacle

### ISSUE THREAD

**Issue by mcint** [ramboxapp/community-edition#2337]
### Expected behavior

At version 0.6.6, I could select the RamBox application (with mouse or application switcher), and use keyboard shortcuts to tile it into position.

### Actual behavior

As of version 0.6.9, RamBox captures all keyboard input, preventing the "window manager" from moving the window. Whether I click inside the application, in the application tab bar, or in the web app page the keyboard input seems captured by RamBox to be directed to the web app, and is not allowed to be handled by Spectacle. No other applications observed to have input-capturing issues with Spectacle.

### ENVIRONMENT

Spectacle 1.2

> Rambox: v0.6.9

> OS: macOS 10.14.5

> Arch: x64

**Comment by Sakartu** [comment]
Strange, I'm using the same version of Rambox with a different window management tool (Moom) in which the global shortcuts still work fine... The keyboard shortcuts I use are opt+cmd+arrow keys for window placement on one display, ctrl+opt+cmd+arrow keys for moving to another display.
