### ISSUE TITLE
mooving windows issue

### ISSUE THREAD

**Issue by smesguich** [ramboxapp/community-edition#2342]
Hello,

When using multi-screen, i've some issue JS.
![image](https://user-images.githubusercontent.com/25209236/61201150-e87ffe00-a6e3-11e9-8273-ba305a014426.png)

### Steps to reproduce

1. Open Rambox
2. Resize Rambox
3. Try to move the windows in the same screen or into an other screen

### ENVIRONMENT

> Rambox: v0.6.9

> OS: W10 Pro

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @smesguich.

That's weird 🤔.
Tested on W10 Enterprise, with 2 screens and works fine. Is resizing working when having only 1 screen? Please try it and get back with an update :).

**Comment by smesguich** [comment]
Seem's to be the same issue after un-docking my laptop : same issue.
I precise that my screen is 1366x768 with 2 external screen FullHD 1920x1080

**Comment by smesguich** [comment]
After an update, issues automaticly closed ! Why ?
