### ISSUE TITLE
old Yahoo messenger cannot be removed

### ISSUE THREAD

**Issue by jkischel** [ramboxapp/community-edition#2343]
### Steps to reproduce

1. login with an account that has an existing entry for Yahoo messenger
2. click on the trashcan icon at yahoo messenger

### Expected behavior

Account will be removed as Yahoo shut down that service long time ago.

### Actual behavior

Dialog "Removing... please wait until we clear all." appears, and nothing more happens. You can wait forever. Problem is reproducible on three different machines.

In developer console, there appears this error:

Uncaught TypeError: Cannot read property 'get' of null
    at ctor.getUserAgent (app.js:1)
    at ctor.webViewConstructor (app.js:1)
    at ctor.initComponent (app.js:1)
    at ctor.constructor (app.js:1)
    at new ctor (app.js:1)
    at Object.widget (app.js:1)
    at ctor.create (app.js:1)
    at ctor.lookupComponent (app.js:1)
    at ctor.prepareItems (app.js:1)
    at ctor.add (app.js:1)
    at ctor.insert (app.js:1)
    at ctor.onEnableDisableService (app.js:1)
    at ctor.removeServiceFn (app.js:1)
    at Number.<anonymous> (app.js:1)
    at Object.each (app.js:1)
    at app.js:1
    at Object.callback (app.js:1)
    at ctor.<anonymous> (app.js:1)
    at ctor.btnCallback (app.js:1)
    at Object.callback (app.js:1)
    at ctor.fireHandler (app.js:1)
    at ctor.onClick (app.js:1)

[EDIT] Note: This leads to other problems because other features won't work:
- no service tabs displayed at all (making the whole app useless)
- option window attached to left lower corner and not saveable which makes the options useless

I think, this situation is generating the question: how to handle disabled service in the future? The current solution does not work.

### ENVIRONMENT

> Rambox: v0.6.9

> OS: Windows 10

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @jkischel.

I don't think we need to do anything for Yahoo Messenger in Rambox since it's a dead service. If you want to remove your account, you can do it with any browser. Since you can remove it as a Rambox service I don't see a problem to solve here.

And for other dead services in the future, they should work without problem. We cannot prevent any wrong behavior until it's present (if it presents). But when it does, that service will be dead... so again, no need to still add functionality to it.

But if anyone wants to make a PR about this, feel free to do it.

**Comment by jkischel** [comment]
Surely, yahoo IM was removed. Within Rambox it can NOT be removed, this results in an endless process bar and the effect I already described.

Also, this dead account leads to major problems in Rambox as the options don't work anymore (if you need screen shots, no problem), there are no service tabs what makes the whole app unusable!

Remove the account in any browser? So you tell me how, I don't see any login page as the whole functionality is done within the Rambox app.

The only way out of this is to dump the email address and register a new one. Is this really the way rambox works?

**Comment by Corchoneitor** [comment]
Sorry, now I'm not following. Please share screenshots or video (you can use [Loom](https://www.loom.com)) with us of what you are trying to achieve.

Thanks.
