### ISSUE TITLE
Application not updating

### ISSUE THREAD

**Issue by rapchic** [ramboxapp/community-edition#2344]
Hi, 

1. I am not being able to relaunch after updating, and I get this error. I also get this error when I try to move the window from one screen to another. 

![image](https://user-images.githubusercontent.com/6327371/61222831-1a6f7f80-a739-11e9-9417-d8234538d96c.png)

2. Rambox application quits when I minimize the window. I have tried clearing cache or uninstalling and re-installing, did not help.

	
	-
	> Rambox 0.6.7
	> Electron 4.1.4
	> win32 x64 10.0.17763

**Comment by Corchoneitor** [comment]
Hi @rapchic.

1- There was an issue with the updater. To update properly you should download the update manually and install Rambox: https://github.com/ramboxapp/community-edition/releases

2- Still cannot reproduce it, it's very strange. Try updating to v0.6.9 first and let's see if it is fixed.
