### ISSUE TITLE
Google Calendar not working

### ISSUE THREAD

**Issue by urielsalis** [ramboxapp/community-edition#2346]
### Steps to reproduce

1. Add google calendar 
2. Try to edit a meeting or add a new meeting
3. You cannot save or close the new meeting dialog without reloading rambox

### Expected behavior

I can save meetings and close the fullscreen meeting dialogs

### Actual behavior

You cannot save or close the new meeting dialog without reloading rambox

### ENVIRONMENT

> Rambox: v0.6.9

> OS: MacOS

> Arch: x64

**Comment by Corchoneitor** [comment]
Hi @urielsalis.

How is it that you cannot save or close? Buttons are not showing? Buttons do not respond?
I tested on Windows 10 and works fine.

Thanks.

**Comment by urielsalis** [comment]
Buttons show but they dont respond. Works fine in Chrome browser and in my normal account but not in the company account

macOs Mojang 10.14

**Comment by fvulich** [comment]
Does this issue persist in v0.7.3?
