### ISSUE TITLE
Microsoft Teams constant issues

### ISSUE THREAD

**Issue by kalusm** [ramboxapp/community-edition#2347]
Not only is application able to remember password but after newest update Teams is constantly crashing.  The workaround is to logout and login back  which makes the app complelely useless because I need to monitor internal company comunicatiob quite often!!!!

STR:
1. Add Teans accizbt;
2. Login;

AR1: white blank screen appears;

Workaround:
1. Wait for error to pop-out (several minutes);
2. Logout;
3. Login;
Result: it temporarly works, after few minutes it crashes to white screen again;

LET ME REMIND YOU: I have Slack, Ooutlook 365 and Skype attached to this tool. Outlook 365 uses directly same credentials as Teams (thanks to SSO) and these apps are working fine. Also Teams in Chrome Beta and Chromium browser is behaving corectly so the issue is in Rambox application NOT IN MY ENVIRONMENT!!!!

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> linux x64 5.1.16-200.fc29.x86_64

**Comment by dhawk00** [comment]
Having the same issue here. It will say it is loaded but all I get is a blank white screen. Eventually it will say it encountered an error and to sign out/in to fix it. Occasionally it will work but error out later.

**Comment by Corchoneitor** [comment]
Duplicate #2276

**Comment by ThomasRitter75** [comment]
As #2369 has been closed, I will note here that Teams was running for me until 2019-08-08 and since then, I need to remove and re-add Teams every time I close Rambox, otherwise I get the blank screen that will change to the logout/login - screen after some time, but logging out and back in inside Teams does not help.

**Comment by Lomanic** [comment]
Workaround from https://github.com/IsmaelMartinez/teams-for-linux/issues/171 (deleting cache)

`killall rambox; rm -r "$HOME"/.config/Rambox/Partitions/teams_1/Cache/* "$HOME"/.config/Rambox/Partitions/teams_1/Application\ Cache/*; rambox &`

and log in back.
To be done every time the page goes blank during loading (when there is some local cache, at Rambox launch for example). You shouldn't reload the page after initial successful load with Ctrl+Shift+R or you will have to repeat the operation of relaunching Rambox with emptied cache and login.

**Comment by kalusm** [comment]
You can close the ticket for all I care. Today I have heard that Microsoft is working on Teams on Linux solution. Once it will be done I am going to get rid of Rambox. It is unacceptable that in order to get Teams working I have to remove it from Rambox, shutdown Rambox, start it again and add Teams account. And it is working for 2-3 days.

**Comment by annicarol** [comment]
The issue is still occurring.

**Comment by xtools-at** [comment]
I may have found a workaround. toggle developer tools for the Teams-tab, then go to "Application > Service Worker", then tick "Bypass for network" and "Update on reload", that should at least help with the blank screen
