### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by rt-oliveira** [ramboxapp/community-edition#2348]
### Steps to reproduce

1. Install Rambox
2. Run Rambox
3. Let Rambox running for a long time

### Expected behavior

Rambox with acceptable memory consumption.

### Actual behavior

The program has a high memory usage, often over 1 GB, or even more, causing the computer to often "hang up" or very slow.

### ENVIRONMENT

> Rambox: v0.6.9

> OS: win32

> Arch: x64

**Comment by TheGoddessInari** [comment]
To be fair, this is a function of Chrome/Electron/the webpages themselves.

**Comment by fvulich** [comment]
The RAM consumption depends on how many and which apps are you running inside Rambox.
