### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Luraktinus** [ramboxapp/community-edition#2349]
### Steps to reproduce

1. install rambox
2. set up a service
3. restart rambox

### Expected behavior
A non white screen where the app should been

### Actual behavior

Every start it shows this white screen on every app
![2019-07-23-101512_grim](https://user-images.githubusercontent.com/33608674/61695196-5f944280-ad33-11e9-9525-3d8da0d44c07.png)

### ENVIRONMENT

> Rambox: v0.6.9

> OS: Linux/Arch
> Arch: x64

**Comment by Luraktinus** [comment]
awesome

**Comment by fvulich** [comment]
Does this issue persist in v0.7.3?
