### ISSUE TITLE
Video for MS Teams still not working

### ISSUE THREAD

**Issue by Lucas1983** [ramboxapp/community-edition#2352]
Video call is still not working in Rambox 0.6.9.
Seeing an error "Video isn't supported in your browser yet" when I hover over camera icon.
![1](https://user-images.githubusercontent.com/9946443/61910596-67233980-af35-11e9-99ad-d7e1afe434fb.png)
Trying to change user-agent setting via Developers Tools and by pasting custom code in "Advanced Settings" with no result.
![2](https://user-images.githubusercontent.com/9946443/61910802-e4e74500-af35-11e9-8d6b-0e7fce060636.JPG)

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> win32 x64 10.0.15063

**Comment by Lucas1983** [comment]
Hi,

It works when I pass different user-agent in Network Conditions ...
![3](https://user-images.githubusercontent.com/9946443/61912109-8cb24200-af39-11e9-8704-7a7a48d1de19.png)
_**Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240**_

But it doesn't when I put it like that in Advanced Settings ...
![image](https://user-images.githubusercontent.com/9946443/61912277-f6325080-af39-11e9-88b5-b74ab34d7b6a.png)

How can I pass this configuration in Advanced Settings to get at least a dirty solution for now?

Thanks

**Comment by Lomanic** [comment]
You can build Rambox locally and add `,userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240'` in teams dictionary in app/store/ServicesList.js

You can also override globally your useragent in Rambox preferences at File > Preferences > Override User-Agent for all services (needs to relaunch).

But then you will lose one-to-one chat history as in  #2152 or as explained [here](http://nelkinda.com/blog/microsoft-teams-on-linux/#d11e144).

**Comment by Lomanic** [comment]
Still an issue of course.
