### ISSUE TITLE
RamboxPro Skype "Something Went Wrong" reload loop

### ISSUE THREAD

**Issue by huang-jy** [ramboxapp/community-edition#2353]
### Steps to reproduce

1. Load up a Skype session
2. Wait for a bit
3. It'll come up with "Something went wrong, press OK to reload"
4. Repeat forever

### Expected behavior

Skype working

### Actual behavior

Skype can't be used

### ENVIRONMENT

> Rambox: Pro 1.1.5 (trial)

> OS: Linux (Ubuntu Disco)

> Arch: x64

**Comment by huang-jy** [comment]
In addition, the CE edition loads the Skype fine on this network

**Comment by akosma** [comment]
On RamboxPro, I could avoid the issue by unchecking the "unread counter" checkboxes in the settings page. Skype works fine then, but without that information.
