### ISSUE TITLE
Add Instagram Direct chat via user-agent override setting

### ISSUE THREAD

**Issue by MurzNN** [ramboxapp/community-edition#2365]
Instagram Direct chat already works in web version at url https://www.instagram.com/direct/inbox/ if we use user-agent from any mobile browser, eg `Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19 `

So we can easily add Instagram Direct chat to Rambox, if implement feature for override user-agent via service config object in `ServicesList.js` file! Can you add feature for allow set manual user-agent for single service?

**Comment by marcosrocha85** [comment]
Page is 404

**Comment by MurzNN** [comment]
https://www.instagram.com/direct/inbox/ with Android user-agent

**Comment by MurzNN** [comment]
Is this implemented? I don't see any commits about this...
