### ISSUE TITLE
Microfost Teams not loading (again)

### ISSUE THREAD

**Issue by neil89** [ramboxapp/community-edition#2369]
Hi, 

today, suddenly, Microsoft Teams is not connecting in my Rambox version. I've tried reloading the tab, restarting the Rambox app, and even adding some JS code to autoreload, but the tab is showing blank. 

Digging for in developer tools, I've found some Angular errors:

![Console screenshot](https://i.imgur.com/NT8ZqUJ.png)

I'm using Microsoft Teams in Google Chrome with no issues, so maybe is a Rambox browser error.

Thanks in advance!

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> win32 x64 10.0.18362

**Comment by ThomasRitter75** [comment]
For me, since yesterday, Teams does not load when restarting rambox, only if I remove and re-add Teams every time I start Rambox.

**Comment by Lomanic** [comment]
Duplicate of #2347

**Comment by neil89** [comment]
Right, close this
