### ISSUE TITLE
Unable to backup because auth0 fails

### ISSUE THREAD

**Issue by twinklebob** [ramboxapp/community-edition#2372]
I've been unable to backup my services for a while, which is frustrating as I'm trying to add rambox to a new machine.

Backup shows the generic "error occurred when trying to backup" message but a look into the developer tools shows a 400 error on the call to https://rambox.auth0.com/api/v2/users/google-oauth[etc, not sure if this part is sensitive]

Response message states: Request Header Or Cookie Too Large

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> linux x64 4.4.0-150-generic

**Comment by brij1234** [comment]
related to #1932 #2371
