### ISSUE TITLE
Gmail: "You're using a browser that Google doesn't recognize"

### ISSUE THREAD

**Issue by michaeldrouin** [ramboxapp/community-edition#2385]
### Steps to reproduce

1. add new gmail account
2. fill in username and password
3. click next

### Expected behavior

gmail account added

### Actual behavior

a message shows saying:

> Couldn't sign you in
> You're using a browser that Google doesn't recognize or that's set up in a way we don't support.
> To keep your Google Account secure, sign in on another browser or change your browser's settings. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en)

### ENVIRONMENT

> Rambox: v0.6.9

> OS: Ubuntu 18.04.3

> Arch: x64

**Comment by michaeldrouin** [comment]
oddlly, i have 3 gmail accounts. one is a gsuite business account, one is a gmail account used for business, and another is a gmail account used for personal. the first two work, but the gmail personal account doesn't.

**Comment by michaeldrouin** [comment]
i have also gone into my google account settings and enabled the feature to allow insecure apps. i am still unable to log in, but the error message is different:

> Couldn't sign you in
> You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
> Try using a different browser. Learn more

**Comment by Raphire** [comment]
I have the same error, the google documentation suggests the app should use oauth instead, no fixes on the user-side.

**Comment by GoodSoulGermany** [comment]
Same here. This is highly important, can we please prioritise this issue?

**Comment by michaeldrouin** [comment]
just a heads up to anyone else having this problem, a temporary work around is overriding the useragent for Rambox. you can do this with File > Preferences > Override User-Agent for all services.

i put the following in the box:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36`

and restarted Rambox, and it works fine.

**Comment by fvulich** [comment]
I will close this ticket because seems to be fixed, but if you have any issue regarding this topic, feel free to re-open it.
