### ISSUE TITLE
Whatsapp stopped working saying it needs "google chrome 49+"

### ISSUE THREAD

**Issue by waldner** [ramboxapp/community-edition#2386]
### Steps to reproduce

1. Open a whatsapp tab

### Expected behavior

You see whatsapp messages and chats

### Actual behavior

"WhatsApp works with Google Chrome 49+
To use WhatsApp, update Chrome or use Mozille Firefox, Safari, Microsoft Edge or Opera."

### ENVIRONMENT

Version: 0.6.9
Platform: linux (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0

**Comment by waldner** [comment]
Today it's working again. Not sure what's going on here.

**Comment by pbek** [comment]
I needed to reload the WhatsApp page a 2nd time, then it worked again.

Version: 0.6.9
Platform: linux (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0

**Comment by pnicorelli** [comment]
Same here, reloading the tab fixed

```
Version: 0.6.9
Platform: linux (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0
```

**Comment by brusch** [comment]
Can confirm ... it's happening again

**Comment by fvulich** [comment]
I will close this ticket because seems to be fixed, but if you have any issue regarding this topic, feel free to re-open it.
