### ISSUE TITLE
NO ANDA EL AUDIO DE LOS MENSAJES DE WHATSAP EN LINUX UBUNTU

### ISSUE THREAD

**Issue by FrenouxJuan** [ramboxapp/community-edition#2387]
NO SE ESCUCHAN LOS MENSAJES DE AUDIO NI EL AUDIO DE LOS VIDEOS EN WHATSAP
GRACIAS!!

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> linux x64 5.0.0-25-generic

**Comment by saenzramiro** [comment]
Asegurate de no tener el Do Not Disturb activado, ya que eso bloquearía todo sonido en tu app.

**Comment by fvulich** [comment]
Probado y en perfecto funcionamiento en Ubuntu 18.04 con snap y AppImage. Cierro el ticket.
