### ISSUE TITLE
There is no sound in new version

### ISSUE THREAD

**Issue by Nihon-To** [ramboxapp/community-edition#2388]
After installing a new version of rambox there is no more sound in the app.

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> win32 x64 10.0.18362

**Comment by wolv-dev** [comment]
Same for me. Using Linux (Ubuntu 19.04) with Rambox 0.6.9.
I tried to reinstall Rambox, tried to clear cache, even cleared local storage and removed all tabs (I appreciate https://github.com/ramboxapp/community-edition/issues/2209). And NO DND mode is on.

**Comment by fvulich** [comment]
I tested in Ubuntu 18.04 and the sound it's working fine (AppImage and snap). Which package are you using?

**Comment by wolv-dev** [comment]
I'm using Rambox-0.6.9-linux-amd64.deb from here:
https://github.com/ramboxapp/community-edition/releases/tag/0.6.9

**Comment by fvulich** [comment]
Are you still having this issue?

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
