### ISSUE TITLE
Sign in with a supported browser

### ISSUE THREAD

**Issue by malys** [ramboxapp/community-edition#2392]
### Steps to reproduce

1. Create a new gmail account
2. Add it to Rambox (4th account added)

### Expected behavior
Works fine

### Actual behavior

Gmail error message:
> Sign in with a supported browser
> https://support.google.com/accounts/answer/7675428?hl=fr

This message appears only for the new one.
With my 3 legacy gmail accounts, Rambox works fine.

### ENVIRONMENT

Version: 0.6.9
Platform: win32 (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0

**Comment by malys** [comment]
Duplicated with #2385 ?

**Comment by malys** [comment]
Workaround. Put:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
in User Agent.

**Comment by fvulich** [comment]
I will close this ticket because seems to be fixed, but if you have any issue regarding this topic, feel free to re-open it.
