### ISSUE TITLE
Create custom service Created 345+ Google Sheet Tabs instead of 1.

### ISSUE THREAD

**Issue by Hotshotdemon** [ramboxapp/community-edition#2393]
I went to create a google sheet tab with the "Create custom" option. This worked fine before. I added this new one and Rambox just kept creating that tab. 345+ times. It happend over about a second and i was too late to act. Rambox became unresponsive after that. Restarting Rambox instantly opens all the tabs and it becomes unresponsive again. 

I went to my AppData folder and found the Rambox partition folder. This folder holds all tabs. I found 345 Custom tabs. I deleted them all and opent Rambox. Rambox automatically recreated all 345 tabs and immediately loaded them. Because of this the program became unresponsive again. 

When i go to task manager to kill the process the amount of processes keeps increasing. Going way over 425 Rambox processes which take up 9GB's of RAM and it taking up 99% of my CPU. It starts at around 10 byt then goes all the way up to 425. That when i killed it. But it does this every time. It actually feels like Rambox keeps creating more tabs or something. 

Anyway. Rambox is completely unusable now. Im scared to open it on my pc since im logged in and scarred it will sync all the tabs to my pc or something. 

Now i cant use Rambox because it becomes unresponsive the moment I open it. Is it possible to remove tabs from rambox without actually being in rambox? The config file only holds you regular settings.

![image](https://user-images.githubusercontent.com/54799590/64110730-38458200-cd83-11e9-9151-b22f5d0b15d4.png)

![image](https://user-images.githubusercontent.com/54799590/64110828-72168880-cd83-11e9-8617-8a025e42f98f.png)

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> win32 x64 10.0.17763

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
