### ISSUE TITLE
mode "do not disturb" doesnt work again in linux

### ISSUE THREAD

**Issue by cjdg** [ramboxapp/community-edition#2394]
### Steps to reproduce
Install 0.6.9-171 x64 in Ubuntu Studio 19.04
1. Go to services tab,
2. Activate mode
3. Still getting notification and sounds

### ENVIRONMENT

> Rambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

**Comment by saenzramiro** [comment]
We will investigate this.

**Comment by fvulich** [comment]
Does this issue persist in v0.7.3?
