### ISSUE TITLE
Altering zoom settings in some services instance also changes it in others

### ISSUE THREAD

**Issue by morphine00** [ramboxapp/community-edition#2397]
I use multiple services. If I change the zoom settings on, say, my Whatsapp tab, then one or all of my Slack tabs will be affected, and vice-versa.

This may be related to [this issue] (https://github.com/ramboxapp/community-edition/issues/2288). If so, please close as a dupe.

	> Rambox 0.6.9
	> Electron 4.1.4
	> win32 x64 10.0.18362

**Comment by fvulich** [comment]
We're investigating this issue, we'll come back with some feedback.

Thanks for the patience.
