### ISSUE TITLE
Slack: Jump to hotkey

### ISSUE THREAD

**Issue by megaroeny** [ramboxapp/community-edition#2399]
### Steps to reproduce

1. Make or open a new Slack workspace
2. After logging in, try to use the `Jump to...` command which is `command K` (on Mac).
3. Nothing happens 

### Expected behavior

I would expect this common hotkey to work in a Slack service tab.
![image](https://user-images.githubusercontent.com/1559447/64622931-1cab2e80-d3b6-11e9-84dc-53d189146fcd.png)

### Actual behavior

Nothing happens when using `command K` or `command F` to search

### ENVIRONMENT

> Rambox 0.6.9
> Electron 4.1.4
> darwin x64 18.7.0

**Comment by jaminroe** [comment]
Maybe this is related to #2103 ? Where do I find the Rambox hotkeys though?

**Comment by fvulich** [comment]
Are still having this issue?

**Comment by megaroeny** [comment]
@fvulich I uninstalled rambox and went back to Franz. Sorry.

**Comment by cscuderi** [comment]
I'm able to use this command on Mac.

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
