### ISSUE TITLE
Custom Service URL without TLD

### ISSUE THREAD

**Issue by Pimon1** [ramboxapp/community-edition#2402]
I want to add local services to Rambox.

When adding a custom service, a (locally) valid URL like `http://company-server/phonenumbers` is not recognized as a valid URL, whereas `http://localhost/` is.

I think the problem resists in the grep pattern in `/ext/src/form/field/VTypes.js`, it doesn't allow domains without the TLD part (.com or else) except for `localhost` and `LOCALHOST`.

**Comment by fvulich** [comment]
We're investigating this issue, we'll come back with some feedback.

Thanks for the patience.

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
