### ISSUE TITLE
Whatsapp asks you to update Google Chrome 

### ISSUE THREAD

**Issue by OliverProgrammer** [ramboxapp/community-edition#2405]
### Steps to reproduce

1. Create a whatsapp service
2. Open it

### Expected behavior

Whatsapp web interface will display

### Actual behavior

Whatsapp asks you to update Google Chrome

### ENVIRONMENT

> Rambox: 0.6.9-1

> OS: Manjaro 18.1.0

> Arch: x64

**Comment by LionelBino** [comment]
This also affect too me

**Comment by ReneBerger** [comment]
#noob
a how-to-update Wiki entry would be great!

**Comment by fvulich** [comment]
I will close this ticket because seems to be fixed, but if you have any issue regarding this topic, feel free to re-open it.
