### ISSUE TITLE
Newly Updated FastMail Web App No Longer Works in RamBox

### ISSUE THREAD

**Issue by TristamAnthony** [ramboxapp/community-edition#2406]
Hi,

FastMail (https://www.fastmail.com/) updated it's web interface, and per attached screen shot it appears to have broken RamBox.

Happy to provide any further details I can upon request.  I hope this gets fixed.  Thank you.

![Screen Shot 2019-09-20 at 2 29 25 PM](https://user-images.githubusercontent.com/1986423/65350279-5ac50100-dbb3-11e9-89a7-019401ba71c3.png)
	

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> darwin x64 17.7.0

**Comment by fvulich** [comment]
I will close this ticket because seems to be fixed, but if you have any issue regarding this topic, feel free to re-open it.
