### ISSUE TITLE
UserStyle One Note

### ISSUE THREAD

**Issue by thib5** [ramboxapp/community-edition#2411]
Hi, I found some global dark mode on userstyle.org that work with OneNote Online

my issue is when I tried to applied it in Rambox it do not work... in fact I know is trying because when I refresh the page I see for a quick moment the right dark background...

Is there some javascript that I can inject to force it to work ? 

Thank you

**Comment by fvulich** [comment]
I seems that the mod it's not working anymore. The issue is not Rambox related.
