### ISSUE TITLE
Cannot sign in to Skype since this morning

### ISSUE THREAD

**Issue by Rik67** [ramboxapp/community-edition#2412]
### Steps to reproduce

1. Launch rambox
2. Sign in to Skype
3. Window freezes 

### Expected behavior

Signing in to the web client

### Actual behavior

Window freezes with that message:
Signing in to Skype, please wait

### ENVIRONMENT

> Rambox: v0.6.9

> OS: Win7

> Arch: x64

**Comment by Rik67** [comment]
I emptied the cache, uninstalled, reinstalled the app.
Nothing helps

**Comment by yuratux** [comment]
Same problem (

**Comment by Rik67** [comment]
Weird, today it's working again.
Shall I close this issue or leave it open?

**Comment by fvulich** [comment]
I will close this ticket because seems to be fixed, but if you have any issue regarding this topic, feel free to re-open it.
