### ISSUE TITLE
Gitter: unread message count not working

### ISSUE THREAD

**Issue by wolv-dev** [ramboxapp/community-edition#2413]
I checked if "unread counter" ->
 "display tab unread counter" and/or
 "include in global unread counter"
are enabled and both are checked.

Already tried to clear cache, cleared local storage (and removed all tabs) and reinstalled rambox. No change.

### ENVIRONMENT
> Rambox: v0.6.9
> OS: Ubuntu 19.04
> Arch: x64

**Comment by rauldipeas** [comment]
Rambox v0.7.3 here, same issue.

**Comment by fvulich** [comment]
duplicate #2391
