### ISSUE TITLE
Ding talk version is not up to date

### ISSUE THREAD

**Issue by dwifprasetyo** [ramboxapp/community-edition#2414]
1. Open rambox 
2. Choose ding talk and login
3. Go to work report
4. It will be po up error version ding talk is not up todate to use work report fitur

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> linux x64 5.0.0-29-generic

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
