### ISSUE TITLE
No sound in application

### ISSUE THREAD

**Issue by Black88ad** [ramboxapp/community-edition#2416]
No sound in application (discord, or videos in whatsapp).No possibility to volume up or unmute in sound settings Rambox is not listed. 

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> linux x64 5.3.5-1-MANJARO

**Comment by cgnunezbantics** [comment]
No sound in app. Rambox 0.6.9 on debian testing 64 bits.
