### ISSUE TITLE
Donate button does not work

### ISSUE THREAD

**Issue by strugk** [ramboxapp/community-edition#2417]
I wanted to explore donation option, but the address (that is `https://rambox.pro/#donate`) linked to those options comes up with an empty page.
You may want to fix the site or remove the option from software (which works very well in its core functionality, so thanks for making, maintaining, opensourcing it. And for everything else needed ;)

All the best!
Kris 

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> linux x64 5.2.20-1-MANJARO

**Comment by saenzramiro** [comment]
Yes, thank you. We will fix it.

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
