### ISSUE TITLE
Problems with Team´s account

### ISSUE THREAD

**Issue by jmmorenas** [ramboxapp/community-edition#2419]
When I add a Teams account, if I restart the app it appears blank

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> win32 x64 10.0.18362

**Comment by noxer** [comment]
Duplicate, for a temporary fix see https://github.com/ramboxapp/community-edition/issues/2380#issuecomment-542146198

**Comment by fvulich** [comment]
Thanks @noxer for the heads up.

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.
