### ISSUE TITLE
[Feature Request] Search within a webpage (find bar)

### ISSUE THREAD

**Issue by ekerazha** [ramboxapp/community-edition#242]
With a find bar, you can search for text inside pages (messages etc.).

Just like CTRL+F in web browsers.

**Comment by Stele77** [comment]
+1

**Comment by hombrepac** [comment]
+1. 
Enabling the "CTRL + F" for the find in page, as in Chromium, would be very useful while searching for something in an email or message. This is a showstopper for working with long emails where you need to find one paragraph.

**Comment by gimntut** [comment]
My Rambox: ![2016-11-19](https://cloud.githubusercontent.com/assets/1645084/20453292/c5ca9c92-ae40-11e6-8b45-855d4b4f566e.png)
Option "Search in App" is needed for some custom webapplications

**Comment by justpusher** [comment]
+1
I'm using Asana in Rambox (with custom code for notifications), and find-in-page would be very useful.

**Comment by Pierstoval** [comment]
Still has not been implemented, it seems, and I'd like to exhume this topic 😄

**Comment by swrobel** [comment]
For reference, this is implemented well in [appifier](https://github.com/webcatalog/appifier/blob/master/app/src/root/find-in-page.js) which is also electron-based.

**Comment by LeleDev** [comment]
+1, please implement this, it is the only feature preventing me from using rambox instead of other services

**Comment by maxerbox** [comment]
@LeleDev should comes with 0.6.7, See #2223

**Comment by Redirts** [comment]
The find option should be added to the Edit menu
