### ISSUE TITLE
Dowloading Files Removes the Extension

### ISSUE THREAD

**Issue by chiranz135** [ramboxapp/community-edition#2422]
-
	> Rambox 0.6.9
	> Electron 4.1.4
	> win32 x64 10.0.18362

**Comment by fvulich** [comment]
We couldn't reproduce this issue. Please, could you give us more information? On what OS (ex: Windows 10, Ubuntu 18.04) does the issue appear? Could you give us some screenshots? Or even a video of the issue? For the video, you could use www.loom.com

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
