### ISSUE TITLE
zulip chat stops receivng inputs

### ISSUE THREAD

**Issue by maxandersen** [ramboxapp/community-edition#2423]
### Steps to reproduce

1. upgrade to catelina osx
2. run rambox with multiple tabs, one is zulip
3. wait
4. eventually that window wont receive any mouse or keyboard inputs.
5. restart and go back to #2

### Expected behavior

not loosing ability to use mouse/keyboard and not having to do restart.

### ENVIRONMENT

> Rambox: v0.6.9

> OS: OSX Catalina

> Arch: x64

**Comment by maxandersen** [comment]
just reproduced with zulip owns app...so not rambox's fault ;/

**Comment by fvulich** [comment]
It appears to be an electron related issue with OSX Catalina. Thanks for reporting it.

**Comment by fvulich** [comment]
Does this issue persist in v0.7.3?

**Comment by maxandersen** [comment]
I haven't seen it for a long time...so i would say no...?
