### ISSUE TITLE
Rambox Sing Up & Login functions not working

### ISSUE THREAD

**Issue by alniro** [ramboxapp/community-edition#2424]
### Steps to reproduce

1. Launch Rambox from portable location (downloading .zip install file)
2. Click on Login button in the upper right. 
3. Either try to login or sing up

### Expected behavior

To login / sing up to rambox

### Actual behavior

After writing login or sing up info the floating login window just shows an Ok text and stays there doing nothing else. After closing that floating login windows there is no sign the process has taken place (the login button stays the same and clicking on it would just repeat the process.

### ENVIRONMENT

> Rambox: v0.6.9

> OS: Windows 10 Pro 

> Arch: win32 (x64) (using the  .zip version of Rambox)

![Untitled](https://user-images.githubusercontent.com/56417020/67571206-a418eb00-f733-11e9-9887-dd2fef69e840.png)

I tried launching Rambox as admin, and adding Rambox to Windows Defender Firewall with no success after app restart. I hope this wasn´t reported before cause i tried the search function and found nothing like this.

**Comment by alniro** [comment]
Ok, now i amd checking the current .exe download (v0.5.20) and that login button is not even threre, instead there are buttons to Backup and Restore but no Login that i can see... what am i missing? is any of this downloads outdated? is rambox supposed to have a login itself, or it is not? 
Any help would be appreciated

**Comment by alniro** [comment]
And now i see what i guess was the problem... i downloaded both files (.exe and .zip) from https://rambox.pro/#ce and they seem to be clearly outdated compared to the downloads here on github. Sorry for the disturbance, will try it again my free time in some hours, but i think those links can clearly lead to confussion.

**Comment by fvulich** [comment]
That's odd I tried to download both versions from https://rambox.pro/#ce and it downloaded the latest version. I will close this ticket because seems to be fixed, but if you have any issue regarding this topic, feel free to re-open it.
