### ISSUE TITLE
Gmail attachments do not print

### ISSUE THREAD

**Issue by ffviivince10** [ramboxapp/community-edition#2425]
### Steps to reproduce

1.  Login to Gmail within Rambox
2.  Open an attachment from an email that is either excel, word, or pdf.
3.  Attempt to Print

### Expected behavior

Have the print window come up

### Actual behavior

A blank rambox window opens up

### ENVIRONMENT

> Rambox: v0.6.9

> OS: Win 10

> Arch: x64

**Comment by fvulich** [comment]
related #2237

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
