### ISSUE TITLE
White windows

### ISSUE THREAD

**Issue by JeremyGermainClementine** [ramboxapp/community-edition#2426]
### Steps to reproduce

1. I start Rambox
2. Waiting
3. Click on "messenger"

### Actual behavior

![image](https://user-images.githubusercontent.com/57216509/67936909-ea0afe80-fbcc-11e9-87b9-f30151bf5e9d.png)

When i click on "messenger", the windows stay white and nothing happens.
I don't know why, i did nothing, Monday, Rambox was working but Tuesday not.
A refresh don't solde the problem.

### ENVIRONMENT

> Rambox: v0.6.9

> OS: Windows

> Arch: x64 or ia32

**Comment by fvulich** [comment]
We checked and it's working now. I'm gonna close this ticket but feel free to reopen it if you've got any issues regarding this topic.

**Comment by JeremyGermainClementine** [comment]
![image](https://user-images.githubusercontent.com/57216509/68278710-3a250d80-0072-11ea-981a-484b658fa617.png)
It's not working for me. I've already refresh but still.

**Comment by JeremyGermainClementine** [comment]
That's good for me now :)
