### ISSUE TITLE
Mouse Icon too small

### ISSUE THREAD

**Issue by HFR1994** [ramboxapp/community-edition#2430]
### Steps to reproduce

1. Get a 4k Monitor
2. Set monitor to 3840x2160_120.01 Hz
3. Open Rambox 

### Expected behavior

Mouse icon size show be inherit from parent

### Actual behavior

Mouse icon scales to a little size

### ENVIRONMENT

> Rambox: v0.6.9

> OS: Zorin OS (linux)

> Arch: x64

**Comment by fvulich** [comment]
duplicate #250
