### ISSUE TITLE
Rambox breaks when recovering account

### ISSUE THREAD

**Issue by prvst** [ramboxapp/community-edition#2431]
### Steps to reproduce

1. Open Rambox on Linux Mint
2. Recover account using Google auth
3. Try to open/edit/delete any apps or change settings

### Actual behavior

I started using Rambox about 2-3 years ago, I created and saved an account with some apps that I had to use. Today I reinstalled Rambox and after recovering my account the program became unusable. I cant add/delete/change any apps, the settings button is unresponsive and resizing the app breaks the the tiles. My issue seems similar to issue #566

### ENVIRONMENT

> Rambox: v0.6.9

> OS: Linux Mint 19.2 Cinnamon 

> Arch: x64

**Comment by fvulich** [comment]
Sorry for the late response. Do you still have this issue?

**Comment by prvst** [comment]
Sorry, I'm not using Rambox anymore.
