### ISSUE TITLE
White windows 2

### ISSUE THREAD

**Issue by JeremyGermainClementine** [ramboxapp/community-edition#2432]
https://github.com/ramboxapp/community-edition/issues/2426

I don't find where i can reopen the issue so i create another one.

![image](https://user-images.githubusercontent.com/57216509/68279197-39d94200-0073-11ea-9ca3-b6b53ded99a2.png)
It's not working for me. Do i have something to do ?

**Comment by fvulich** [comment]
Please make a Clean uninstall and then try again. 
[Clean Uninstall](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall)

**Comment by fvulich** [comment]
Does this issue persist in v0.7.3?
