### ISSUE TITLE
Crash on Rocket Chat Jitsi Video Call

### ISSUE THREAD

**Issue by J0kerFace** [ramboxapp/community-edition#2433]
### Steps to reproduce

1. Configure RC für Jitsi
2. Start Jitsi Video Call in Room
3. Full Crash (Windows inkl. Bluescreen)

### Expected behavior

Open new Browsertab with Jitsi

### Actual behavior

Full Crash (Windows inkl. Bluescreen)
### ENVIRONMENT

> Rambox: v0.6.9

> OS: Windows 10 1903

> Arch: x64

**Comment by fvulich** [comment]
Does this issue persist in v0.7.3?

**Comment by fvulich** [comment]
We're investigating this issue.

**Comment by fvulich** [comment]
0.7.8 Released. You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
Is this issue still reproducible in it?
