### ISSUE TITLE
Daylight Saving Time in Brazil

### ISSUE THREAD

**Issue by diasthiago** [ramboxapp/community-edition#2436]
Message times are in daylight saving time here in Brazil. But from this year we no longer have daylight saving time.

> Rambox: v0.6.9

> OS: macOS 10.15.1 Catalina

> Arch: x64

**Comment by fvulich** [comment]
We released 0.7.2 could you check if your issue is solved?

**Comment by diasthiago** [comment]
Working perfectly 😊
