### ISSUE TITLE
"Open with google Docs" gmail button just opens a blank window

### ISSUE THREAD

**Issue by roorco** [ramboxapp/community-edition#2438]
In Gmail tab, trying to open an attachment with "Open with Google Docs" button it just cause to open a blank window.

### ENVIRONMENT
Mac Book Pro 2012
Mac OSX 10.11.6
Rambox Version: 0.6.9
Platform: darwin (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0

**Comment by fvulich** [comment]
related #2425

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
