### ISSUE TITLE
Dont work TELEGRAM and MAIL.RU windows

### ISSUE THREAD

**Issue by ds205** [ramboxapp/community-edition#2439]
Dont work TELEGRAM and MAIL.RU windows

1) Telegram:

http://skrinshoter.ru/i/121119/B4aqZmtD.png

2) Mail.ru:

http://skrinshoter.ru/i/121119/6ua3sb8S.png

3) How to delete windows?

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> win32 x64 10.0.17763

**Comment by fvulich** [comment]
We released 0.7.2 could you check if your issue is solved?

**Comment by ds205** [comment]
Ok. I`m ready. Last public version 0.7.1? Cant check - https://rambox.pro/ don`t work now.

**Comment by ds205** [comment]
- Update to 0.7.2.
- Disable/Enable Service (Telegram & Mail.ru), Reload Services.
- issue is solved.

**Comment by fvulich** [comment]
Glad to hear that!

**Comment by ds205** [comment]
Sorry. I`m write incorrent. "do NOT solved" -_-
