### ISSUE TITLE
TweetDesk

### ISSUE THREAD

**Issue by maikcrew** [ramboxapp/community-edition#2440]
TweetDesk show me this message:

Sorry, something went wrong. Please try again later. (Unsupported time zone specified undefined)

And switch to normal Twitter.

I using appimage 64 bit in PCLinuxOS in Czech language.

**Comment by fvulich** [comment]
We released 0.7.2 could you check if your issue is solved?

**Comment by maikcrew** [comment]
Works well thanks.

**Comment by fvulich** [comment]
Glad to hear that!
