### ISSUE TITLE
Slack group icons aren't working

### ISSUE THREAD

**Issue by edwinramirez** [ramboxapp/community-edition#2443]
### Steps to reproduce

1. Add a Slack workspace

### Expected behavior
Rambox should display the tab with the Slack workspace icon

### Actual behavior
Rambox displays a generic Slack icon and it seems there is no easy way to switch.

### ENVIRONMENT

Version: 0.6.9
Platform: linux (x64) Ubuntu 18.04.3
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0

**Comment by edwinramirez** [comment]
Also, I'm trying the script posted here but it ain't working https://github.com/ramboxapp/community-edition/issues/113

**Comment by fvulich** [comment]
We released 0.7.2 which includes a fix for this issue.
