### ISSUE TITLE
Google services are signed out once a week

### ISSUE THREAD

**Issue by sleepyspider1** [ramboxapp/community-edition#2444]
About once a week, I'm signed out of all google services and have to log into each tab again individually. I'm not sure if this is a google thing or a rambox thing.

**Comment by fvulich** [comment]
It seems to be an isolated case, no one else reported it, and we couldn't reproduce it. I will close this ticket but if the issue continues please come back.

**Comment by boekkooi-fresh** [comment]
I can confirm that this happens every week on both gmail and calendar
