### ISSUE TITLE
Whatsapp check-marks through text

### ISSUE THREAD

**Issue by hokkenmeijer** [ramboxapp/community-edition#2445]
- See attached picture. Check-marks through text, speaks for itself :-)
- Problem also exists on Linux Mint!
![rambox](https://user-images.githubusercontent.com/48594233/69150989-12a25c00-0ada-11ea-8872-6ccbe3420e85.jpg)

	
	-
	> Rambox 0.6.9
	> Electron 4.1.4
	> win32 x64 10.0.18362

**Comment by yoshivda** [comment]
This is not a problem with Rambox, it is also present at the regular web.whatsapp.com interface.

**Comment by hokkenmeijer** [comment]
Maybe, I don't use the web interface. But in the Whatsapp app on my (Windows) desktop all looks normal.
By the way, the problem exists for a month or so, before that all was fine.

**Comment by fvulich** [comment]
@yoshivda is right it's a Whatsapp web app issue. Please refer to their support channel.
