### ISSUE TITLE
Rambox 0.7.0 overrides keyboard shortcut in other app [HAVE TO ABANDON RAMBOX CURRENTLY BECAUSE OF THIS]

### ISSUE THREAD

**Issue by tin-trong-nguyen** [ramboxapp/community-edition#2446]
### Steps to reproduce

1. Install Rambox 0.7.0 and launch
2. Open another app (e.g. Chrome) while Rambox is opened (or minimized to tray)

### Expected behavior

When another application's window is focused, the keyboard shortcuts that conflict with Rambox's  (e.g. Ctrl + 1) should work in that app

### Actual behavior

The keyboard shortcut doesn't work until Rambox is exited

### ENVIRONMENT

> Rambox: v0.7.0

> OS: Windows 10

> Arch: x64 or ia32

*Also there should be an option to rollback / or opt in to update to new versions. I cannot use Rambox at all now because of this issue, and reinstalling old versions doesn't work because update automatically happens.

**Comment by Sam-Hall** [comment]
Yes, I was just about to log this same issue! I am trying to use Confluence wiki in another browser and I can no longer use Ctrl+1,2,3... etc. hotkeys to create headings because Rambox steals these hotkeys even though Rambox window doesn't have focus. Just started to happen after todays update.

**Comment by Sam-Hall** [comment]
This looks like the culprit... https://github.com/ramboxapp/community-edition/commit/8992c2cddaeb1a8392d2dfd595dfcadc20901ede

**Comment by Sam-Hall** [comment]
@tin-trong-nguyen you can break the auto-updates by editing resources/app-update.yml and change something like "provider: yourmum".

**Comment by Kovah** [comment]
Same issue here, had to ditch Rambox because of this.

**Comment by StormPooper** [comment]
Not only that, but they _still_ don't focus the service when you use the keyboard shortcut, even when Rambox is in focus, so keyboard shortcuts within those apps won't apply until you click inside them. Clicking on the service icon directly does bring the service window in focus.

Related issue: #2447.

**Comment by fvulich** [comment]
We're working to fix this ASAP. We're gonna release a version with the fix very soon.

**Comment by Sam-Hall** [comment]
Thanks for the quick turnaround @fvulich , love your work!

**Comment by tin-trong-nguyen** [comment]
Confirm issue fixed on 0.7.1 <3. Thank you @fvulich
