### ISSUE TITLE
Tab switching in browser not possible anymore

### ISSUE THREAD

**Issue by MyNameIsOka** [ramboxapp/community-edition#2447]
With the current version, tab jumping in browsers is not working anymore.
The tabs of Rambox are switched instead, even if it is in the background.

	
	-
	> Rambox 0.7.0
	> Electron 7.1.1
	> darwin x64 18.7.0

**Comment by fvulich** [comment]
We're working to fix this ASAP. We're gonna release a version with the fix very soon

**Comment by MyNameIsOka** [comment]
Awesome, thanks a lot!

**Comment by fvulich** [comment]
We released 0.7.2 which includes the fix for this issue
