### ISSUE TITLE
Short F2 does not lock app

### ISSUE THREAD

**Issue by bademeister9001** [ramboxapp/community-edition#2450]
After receiving update F2 key does not lock the app. I have to use the button in order to unlock.

	
	-
	> Rambox 0.7.0
	> Electron 7.1.1
	> win32 x64 6.1.7601

**Comment by StormPooper** [comment]
Noticed this in the changelog:

> Change shortcuts: Now for "Do Not Disturb" is <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>D</kbd> and for Lock Rambox is <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd>.

They should probably have popped up a note the first time someone hits the old shortcut rather than only mention it in the changelog though.

**Comment by bademeister9001** [comment]
Unfortunately there ist still this hint within the app:

![grafik](https://user-images.githubusercontent.com/57985098/69237043-0fb87180-0b95-11ea-8813-1f26e20976c2.png)

**Comment by StormPooper** [comment]
Just raised a PR to fix those prompts, good spot.
