### ISSUE TITLE
Rambox 7.0 appimage Linux 64 bit crashes on start with "SUID sandbox helper binary was found"

### ISSUE THREAD

**Issue by laszlokertesz** [ramboxapp/community-edition#2451]
### Steps to reproduce

1. Trying to start rambox from appimage
2. 
3. 

### Expected behavior

It starts?

### Actual behavior

It does not start.
In terminal it shows this error:
```
[4226:1120/115207.508608:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_rambox6n1T2d/chrome-sandbox is owned by root and has mode 4755.
```
I cannot do anthing since the mount specified there is not persistent. Other Electron apps (not appimage) had the same issue but they pointed towards an existing binary that i could chmod.

/tmp is mounted with these options:
```
tmpfs on /tmp type tmpfs (rw,nodev,noatime,size=3145728k)
```
### ENVIRONMENT

Debian testing 64 bit

> Rambox: v0.7.0

> OS: XXXX

> Arch: x64 or ia32
64

**Comment by freezed** [comment]
Same message for `.deb` package.

See this [electron #17972 comment](https://github.com/electron/electron/issues/17972#issuecomment-516957971)

**Comment by fvulich** [comment]
Did you try launching Rambox with ` --no-sandbox` flag?

**Comment by freezed** [comment]
Yep, `rambox --no-sandbox` runs well :+1:

**Comment by Mef45** [comment]
That's not a good solution.

**Comment by freezed** [comment]
Ok, what could be a good solution?

**Comment by Mef45** [comment]
> Ok, what could be a good solution?

run with `--no-sandbox` by default, or something else, idk

but not at all like 'hey, you're installed our app, now go to google and find how to run it correctly, lol, run it from terminal each time with custom params, or create new running scripts, but not just install and start to use, 'cos linux is for hardcore users only'

But that's only my opinion it this situation.

**Comment by freezed** [comment]
I see, my long answer had to be : 
> `rambox --no-sandbox` runs well Rambox, but I have no idea of the consequences of using this option.

**Comment by nordcomputer** [comment]
Same issue here with 0.7.1 on Debian Buster and the AppImage...

**Comment by mmlo** [comment]
temporary fix:
sudo chmod 4755 PATH-TO/chrome-sandbox

**Comment by fvulich** [comment]
It's an electron related issue, we are working to get a better fix, the `--no-sandbox` switch seems to be the fix less intrusive.

**Comment by cchris-org** [comment]
Same on deb Package. Would it probably better to deploy deb and appImage with --no-sandbox in startup cmd?

**Comment by Scibearspace** [comment]
Just downloaded the Rambox-0.7.5-linux-amd64.deb to my system.

This issue may be closed, but I ran into the exact same problem. I agree with @cchris-org that the app should be deployed with the --no-sandbox in the startup command. Escpecially as @fvulich suggested this is a < less intrusive > fix.

**Comment by fvulich** [comment]
Duplicate #2481
