### ISSUE TITLE
CMD + 1 (any number), interferes with Google Chrome/Safari/Firefox on macOS

### ISSUE THREAD

**Issue by rwkyyy** [ramboxapp/community-edition#2452]
### Steps to reproduce

1. open rambox 0.7.0
2. open google chrome
3. open at least two tabs in Chrome
4. use CMD + 1,2,3 (any) in google chrome to swap tabs

### Expected behavior

expecting tabs to swap in chrome as usual

### Actual behavior

they swap in rambox (even if minimized), closing Rambox will restore the normal behaviour in Chrome.

### ENVIRONMENT

> Rambox: v0.7.0

> OS: macOS 10.15.1

> Arch: x64

**Comment by Streyder** [comment]
This is true for all applications. All CTRL + Number shortcuts dont work anymore

**Comment by Streyder** [comment]
Was fixed in this issue: https://github.com/ramboxapp/community-edition/issues/2446

**Comment by fvulich** [comment]
We released 0.7.2 which includes the fix for this issue.
