### ISSUE TITLE
Unable to jump between words with alt/option hotkey with Slack service

### ISSUE THREAD

**Issue by kellylawrence** [ramboxapp/community-edition#2454]
### Steps to reproduce
1. Type out a few words such as `This is my comment`.
2. On a Mac, press the `option` (`alt` on PC I believe) and `←` arrow keys.

### Expected behavior
The text cursor should move to the beginning of each previous word, each time the `option` and `←` arrow keys are pressed.

### Actual behavior
At least when using the Slack service in Rambox, it seems to jump between previous channels or private chats in my history. This was not the actual behavior in the previous version of Rambox. (At least, not that I experience)

### ENVIRONMENT
> OS: macOS Mojave (v10.14.4)
> Arch: x64
> Rambox Version: 0.7.0
> Platform: darwin (x64)
> Electron: 7.1.1
> Chromium: 78.0.3904.99
> Node: 12.8.1

-------------------------

I've tried restarting Rambox and my computer, as well as tried to replicate this behavior in the native Mac Slack app and web app in Firefox, but those seem to work as expected, leading me to believe this is an issue with Rambox or the way the web app service is connected?

**Comment by saenzramiro** [comment]
Seems like Slack is assigning those shortcuts to do something special:
![image](https://user-images.githubusercontent.com/2694669/69279537-558c2e80-0bc3-11ea-8673-4be65a7311d6.png)

**Comment by iBobik** [comment]
If I open Safari it works like expected, but I guess it is because Safari protects user against hijacking common shortcuts.

If somebody wants to solve it, write to Slack support.
