### ISSUE TITLE
The Mac App won't install on Catalina

### ISSUE THREAD

**Issue by AdamasFR** [ramboxapp/community-edition#2455]
Hi, just got a problem on macOS Catalina

### Steps to reproduce

1. Download the .dmg of the app on a Catalina mac
2. Click on it
3. Get greeted with a message indicating that you need to contact the developper because the app is not compliant

### Expected behavior

Launch the app

### Actual behavior

Not launch the app..?

### ENVIRONMENT

macOS Catalina 10.15.1

Might be related to 823

**Comment by SiNaPsEr0x** [comment]
open settings... privacy and general.... and add rambox flag in the window

**Comment by AdamasFR** [comment]
Oh, I know how to do that, that's not the problem, It's for all the people that don't that I'm writing this issue.

**Comment by fvulich** [comment]
Fixed in v0.7.4
