### ISSUE TITLE
makes shortcuts of other applications not work

### ISSUE THREAD

**Issue by radioterror** [ramboxapp/community-edition#2456]
The new shortcut to move between tabs (cmd+number) when Rambox is launched, makes that this shortcut doesn't work on other apps (e.g. Google Chrome cmd+number shortcuts, also used to move between tabs). fn+1 shortcut to (de)activate "don't disturb" mode doesn't work too.

Thanks!!

	
	-
	> Rambox 0.7.0
	> Electron 7.1.1
	> darwin x64 19.0.0

**Comment by Buzzmovies** [comment]
I have the same issue since this last update. Prevents me from using ctrl-1, 2, 3 on my Mail client (Newton Mail). Even if Rambox is not in the foreground or even minimized and my email client the selected foreground application.

Happens on Windows 10 Thanks

**Comment by fvulich** [comment]
We released 0.7.2 which includes the fix for this issue.
