### ISSUE TITLE
Skyp  UI not loading in new version

### ISSUE THREAD

**Issue by Ridoy1270** [ramboxapp/community-edition#2458]
New version can not load UI of Skyp .  Skyp web also have same issue if we try to load them from Rambox

	
	-
	> Rambox 0.7.1
	> Electron 7.1.1
	> win32 x64 10.0.17763

**Comment by fvulich** [comment]
We released 0.7.2 which includes the fix for this issue.

**Comment by Ridoy1270** [comment]
> We released 0.7.2 which includes the fix for this issue.

thank you . it  is working fine.
