### ISSUE TITLE
Keyboard shortcuts for switching apps do not focus the app

### ISSUE THREAD

**Issue by StormPooper** [ramboxapp/community-edition#2461]
Looking at the code for 0.7.1, I see that theoretically it should be focusing the tab content when they keyboard is used to switch apps, however it doesn't seem to be working. When using the mouse to switch apps, it behaves correctly.

### Steps to reproduce

1. Move to a service (Ctrl+Tab, Ctrl+Num, etc)
2. Attempt to press the shortcut (Alt+Shift+Up in Discord, for example) or start typing if a text field was previously in focus

### Expected behavior

The shortcut or other keyboard input should be forwarded to the app and it should react appropriately.

### Actual behavior

Nothing happens. Clicking within the app somewhere or on the app service icon and then trying a shortcut again will work.

### ENVIRONMENT

Version: 0.7.1
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by vpommier** [comment]
Same issues

**Comment by fvulich** [comment]
We released 0.7.2 could you check if you can still reproduce this issue?

**Comment by StormPooper** [comment]
Just checked and yes, it's still an issue in 0.7.2. I've just spotted an additional wrinkle too - the keyboard input is sent to the previously focused service, so if I switch away from Discord with Ctrl+Tab and press a Discord shortcut or type, when I go back to Discord with Ctrl+Shift+Tab, it's acted on those inputs.

**Comment by fvulich** [comment]
We're investigating this issue, all the information that seems relevant for you please share it with us.

**Comment by StormPooper** [comment]
Will do, let me know if you want me to check anything or try anything out (I've had trouble building Rambox locally in the past, but I can give it another go if need be).

**Comment by fvulich** [comment]
Thanks, but for the moment I need all the data that seems relevant for you, screenshots or videos are more than welcome. Anything that you think that could help. :)

**Comment by StormPooper** [comment]
Attached a video (had to zip it to be uploaded).
[RamboxFocusBug.zip](https://github.com/ramboxapp/community-edition/files/3879453/RamboxFocusBug.zip)

Reproduction steps for video (services just examples):

0. Forgot to include this in the video, focus the input field in Discord, then switch to Android Messages
1. Focus input field in Android Messages
2. Ctrl+2 to change to Discord - notice input field does not have focus
3. Type 'test' - not visible in Discord
4. Ctrl+4 to change to Messages - 'test' shows up in Messages input field
5. Type something else - shows up in same input field
6. Click on Discord icon
7. Type 'test' again - shows up in Discord input field

Hope this helps, if I think of anything else I'll let you know.

**Comment by StormPooper** [comment]
@fvulich, just tested this in 7.3 and it's still an issue for me.
