### ISSUE TITLE
Skype not Work

### ISSUE THREAD

**Issue by lor2ex** [ramboxapp/community-edition#2462]
Skype not Work. Rambox 0.7.1
https://img1.img1.de/20191121091933ec59d.jpg

	
	-
	> Rambox 0.7.1
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by LordBoos** [comment]
I have the same issue. Only white page with nothing on it loads.

**Comment by polkovnikvasin** [comment]
Teams also shows only the white page.

**Comment by ysying** [comment]
I have the same issue for both skype and teams.

**Comment by espudaro** [comment]
I hame the same problem!

**Comment by fvulich** [comment]
We released 0.7.2 which includes the fix for this issue.
