### ISSUE TITLE
Slack badges not updating, overzealous notifications (possibly all services)

### ISSUE THREAD

**Issue by StormPooper** [ramboxapp/community-edition#2463]
When marking messages as read in Slack, the badge doesn't update to reflect that. I've also noticed that when I receive a new message it doesn't always update either.

For example, the first Slack in focus has a message (on the right) but no badge, whilst the Slack below it has no unread messages.
![image](https://user-images.githubusercontent.com/1657182/69324218-f4ef0700-0c3f-11ea-82e5-546ec260773f.png)

I've also noticed that Slack now notifies me for every single direct message, even if I'm already in that current chat, which doesn't happen in the Slack client.

### ENVIRONMENT

Version: 0.7.1
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by tin-trong-nguyen** [comment]
Same issue

**Comment by StormPooper** [comment]
Update: It might actually be a general issue with the badges - just read all of my emails, but the badge hasn't updated:

![image](https://user-images.githubusercontent.com/1657182/69326661-15b95b80-0c44-11ea-8e32-57c418ae42bb.png)

**Comment by fvulich** [comment]
We apologize for this inconvenience.
We're investigating this issue, we'll come back with some feedback.
Thanks for the patience.

**Comment by StormPooper** [comment]
Thanks. Just noticed as well that clicking on the notifications doesn't appear to be switching to the service in question (so clicking on the notification for the email about your reply didn't switch to Gmail, for example).

**Comment by fvulich** [comment]
We already identify the error, and we are working on a fix.

**Comment by fvulich** [comment]
We released 0.7.2 which includes the fix for this issue.
