### ISSUE TITLE
Skype Not display

### ISSUE THREAD

**Issue by charliedaps1** [ramboxapp/community-edition#2466]
Since today and the last version, skype is loaded but nothing is displayed.

Thank you

	
	-
	> Rambox 0.7.1
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by askembris** [comment]
I can confirm this issue with the Linux version (x64 RPM). Reverting back to 0.7.0 fixed the problem. 

Also, in version 0.7.1 the custom javascript for styling does not seem to work (it does for 0.7.0). I can open a separate bug report for this.

**Comment by charliedaps1** [comment]
And another problem.   I need to relaod what's app and telegram to disabled the red notice (number of message not read)

**Comment by fvulich** [comment]
We apologize for this inconvenience.
We're investigating this issue, we'll come back with some feedback.
Thanks for the patience.

**Comment by fvulich** [comment]
We already identify the error, and we are working on a fix.

**Comment by fvulich** [comment]
We released 0.7.2 in that version this issue is fixed.

**Comment by charliedaps1** [comment]
Hello,

The version 0.7.2 works perfect.

Thanks.

Have a good day.
