### ISSUE TITLE
Alerts doesn't works

### ISSUE THREAD

**Issue by DausdasKreuz** [ramboxapp/community-edition#2467]
Alerts from emails, whatsapp and others applications don't be shown.

	
	-
	> Rambox 0.7.1
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by fvulich** [comment]
We apologize for this inconvenience.
We're investigating this issue, we'll come back with some feedback.
Thanks for the patience.

**Comment by fvulich** [comment]
We already identify the error, and we are working on a fix.

**Comment by fvulich** [comment]
We released 0.7.2 in that version we fix this issue
