### ISSUE TITLE
7.1 regressions

### ISSUE THREAD

**Issue by bxabi** [ramboxapp/community-edition#2468]
### Steps to reproduce

1. Update to 7.1
2. 
3. 

### Expected behavior

Skype works.
Whatsapp is not asking anything.

### Actual behavior

Skype shows a white page.
Whatsapp says it's used in another tab.

### ENVIRONMENT

> Rambox: v0.7.1

> OS: Arch linux

> Arch: x64 or ia32

**Comment by bxabi** [comment]
I downloaded the 7.0, everything works great. Will not update for now.

**Comment by Streyder** [comment]
I am not using skype but whatsapp works for me on 0.7.1

**Comment by mpapini64** [comment]
I too have re-downloaded 0.7.0 and everything works, including WhatsApp that doesn't ask the stupid question "WhatsUp in use other session ..." or something. !!!
Unfortunately it does not seem possible to disable the auto updating.

The patch is worse than the hole!

**Comment by askembris** [comment]
The javascript styling code also does not seem to work in 0.7.1, at least for hangouts chat.

**Comment by bxabi** [comment]
If you download the zip and not the appimage, that is not auto-updating.
The 0.7.0 is a pretty good version, not sure what happened in the last update.

**Comment by MrLeonix** [comment]
Same for me, Skype now shows a white page.

**Comment by fvulich** [comment]
We apologize for this inconvenience.



We're investigating this issue, we'll come back with some feedback.

Thanks for the patience.

**Comment by fvulich** [comment]
We already identify the error, and we are working on a fix.

**Comment by MrLeonix** [comment]
By the way, MS Teams had been fixed on 7.0 (white screen), but now I'm getting it once again in 7.1.

**Comment by fvulich** [comment]
We released 0.7.2 in this version this issue is fixed.
