### ISSUE TITLE
Slack notification alert is always on

### ISSUE THREAD

**Issue by SeidChr** [ramboxapp/community-edition#2470]
on our slack i get a continuous notification alert (red dot in tab)
only there after last rambox update this morning

Version: 0.7.1
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

	
	-
	> Rambox 0.7.1
	> Electron 7.1.1
	> win32 x64 10.0.17134

**Comment by brosquinha** [comment]
Same issue on Linux Mint.

Version: 0.7.1
Platform: linux (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by espudaro** [comment]
Me too!

**Comment by tsansom** [comment]
Same on Mac

Version: 0.7.1
Platform: darwin (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by Mte90** [comment]
with 0.7.1 I got that issues, with the previous version there wasn't this problem

**Comment by fvulich** [comment]
We released 0.7.2 in that version this issue is fixed
