### ISSUE TITLE
CSS Code Injection

### ISSUE THREAD

**Issue by FourPeaksAdmin** [ramboxapp/community-edition#2471]
Css code injections no longer work as of 0.7.1! All apps load but css code does not.

	
	-
	> Rambox 0.7.1
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by fvulich** [comment]
We apologize for this inconvenience.
We already identify the error, and we are working on a fix.

**Comment by fvulich** [comment]
We released 0.7.2 in that version this issue is fixed
