### ISSUE TITLE
Request: User Control of Rambox shortcut combos

### ISSUE THREAD

**Issue by pdelre** [ramboxapp/community-edition#2472]
### Expected behavior

Users have control over Rambox shortcuts, particularly for the case where they conflict with a Servcie's shortcuts.

### Actual behavior

`0.7.1` introduces **Shortcuts: "Do Not Disturb" is Alt + Shift + D & MacOs Cmd + D**, which conflicts with a Google Meet's shortcut. In particular, `Cmd + D` toggles the user's Mute state which in turn toggles Rambox's DND state.

This leads to a poor experience as toggling Mute happens frequently in meetings and DND is not a feature all users desire. It is easy to leave a meeting and end up having Rambox in DND which leads to the user missing business communcations.

Conflict introduced in https://github.com/ramboxapp/community-edition/commit/4ad7edc4ea936703a3341b04f9d04da119376637.

### ENVIRONMENT

> Rambox: v0.7.1
> OS: 10.14.6
> Arch: darwin x64

**Comment by pdelre** [comment]
I've learned this is quite impactful for Meet as DND stops all audio output leading to the following experience:

- User is muted and listening to conversation
- User unmutes to speak next with `Cmd + D`.
  - **Meet** unmutes the user.
  - **Rambox** enables DND and the rest of the conversation is muted.

**Comment by fvulich** [comment]
The macOS shortcut has been changed from Cmd + D to  Cmd + Alt +D in https://github.com/ramboxapp/community-edition/commit/c309c0f385941ba70873c784fb19df0170c1b40d and it's gonna be part of our new release
