### ISSUE TITLE
0.7.1 breaks tweetdeck layout

### ISSUE THREAD

**Issue by mielvds** [ramboxapp/community-edition#2474]
CSS issue with rambox

### Steps to reproduce

1. Run tweetdeck on OSX in rambox 0.7.1

### Expected behavior

same UI as in browser

### Actual behavior

Large blank space above columns

### ENVIRONMENT

> Rambox: v0.7.1

> OS: OSX 10.13.6

> Arch: x64

**Comment by fvulich** [comment]
We released 0.7.2 could you check if your issue is solved?

**Comment by dekaru** [comment]
The issue was still present on 0.7.2, @fvulich .

**Comment by mielvds** [comment]
The version bump solved it for me

**Comment by mielvds** [comment]
update: it still happens, but with 7.2:
- only after a certain action like a scroll
- the focused column remains in place
- a refresh solves it until it happens again.



<img width="1669" alt="Screen Shot 2019-11-29 at 15 27 57" src="https://user-images.githubusercontent.com/1032980/69875529-aaaffa80-12bd-11ea-8c54-57a92ea38bc7.png">

**Comment by fvulich** [comment]
Does the issue persist in v0.7.3?

**Comment by sieren** [comment]
Yes, I can reproduce this on my end in 0.7.3
