### ISSUE TITLE
7.1 update - Do not disturb is not working

### ISSUE THREAD

**Issue by peterszky** [ramboxapp/community-edition#2475]
With Do not disturb is on notification sounds not muted (Hangouts, Facebook Messenger).

	
	-
	> Rambox 0.7.1
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by fvulich** [comment]
We released 0.7.2 could you check if your issue is solved?

**Comment by peterszky** [comment]
> We released 0.7.2 could you check if your issue is solved?

It seems to be fine! Thanks!
