### ISSUE TITLE
Custom Service CSS

### ISSUE THREAD

**Issue by FourPeaksAdmin** [ramboxapp/community-edition#2477]
Custom CSS does not work in custom services. I tried to load a custom service that i know the custom CSS injection works with and it doesnt work. It actually hasnt worked since a few versions of rambox back. Do I need Rambox pro for this feature?

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by osky85** [comment]
This worked for sure on version <0.7 and now it's not working.

**Comment by FourPeaksAdmin** [comment]
Excuse my pointless issue report, I found out its related to the website im trying to run custom css code injection on (https://app.ninjarmm.com). The css code works, just doesnt apply in rambox. But I tried youtube as a custom service and the css code works. Not sure why app.ninjarmm.com doesnt like rambox lol.
________________________________

**Comment by fvulich** [comment]
Have you tried using a User Agent?

**Comment by FourPeaksAdmin** [comment]
Can you use a user-agent with rambox?







Thanks,
Dennis

________________________________

**Comment by fvulich** [comment]
Yes you can, 

1. Open Rambox, 
2. open the Rambox tab, 
3. open the settings dialog all the way on the right.
4. Scroll down until you see the user agent field

**Comment by fvulich** [comment]
I will close this issue because is not a Rambox problem.
