### ISSUE TITLE
mute all sounds for Whatsapp has stopped working since 0.7.1

### ISSUE THREAD

**Issue by roizcorp** [ramboxapp/community-edition#2478]
Long time user, the mute all sound setting in Whatsapp has been set forever, and worked, but suddenly since 0.7.1 it does not, regardless of unsetting-setting it again

### ENVIRONMENT

Archlinux

> Rambox: v0.7.1

> OS: LINUX

> Arch: x64

**Comment by fvulich** [comment]
We released 0.7.2 could you check if your issue is solved?

**Comment by roizcorp** [comment]
I think it has been fixed (or at least does not happen anymore)
