### ISSUE TITLE
opt + left/right arrow to navigate between words doesn't work on slack

### ISSUE THREAD

**Issue by dekaru** [ramboxapp/community-edition#2479]
### Steps to reproduce

1. add a Slack Service
2. write something in a channel, then try to navigate between the written words by pressing option + left/right arrow. 

### Expected behavior

The cursor should move freely between words

### Actual behavior

Navigation actually occurs between channels, not between words.

### ENVIRONMENT

Rambox: v0.7.2

OS: High Sierra 10.13.6

**Note:** This does not happen on Rambox 0.6.9

**Comment by pehbehbeh** [comment]
I am having the same issue. Slack is hardly usable with this behaviour...

**Comment by SebastianMueller87** [comment]
+1 
It's really annoying. :'(

**Comment by fvulich** [comment]
#2454 It seems to be a new feature of Slack

**Comment by pehbehbeh** [comment]
In the Browser everything is working fine...

**When I open Slack via Brave Browser:**

<img width="428" alt="brave" src="https://user-images.githubusercontent.com/133831/69426537-c64f5a00-0d2d-11ea-839f-a8e4e6d8dfa7.png">

**When I open Slack via Rambox:**

<img width="429" alt="rambox" src="https://user-images.githubusercontent.com/133831/69426549-ce0efe80-0d2d-11ea-939a-6ff9f9816c27.png">

**Comment by fvulich** [comment]
@pehbehbeh Ok, please try adding your Slack workgroup as a custom app and check it.

**Comment by pehbehbeh** [comment]
Thanks, it works now. This also changes the emojis back to the native ones. 👍 

Does Rambox load a custom Slack app or injects custom logic? 🤔

**Comment by fvulich** [comment]
Restart Rambox and the problem should be gone.

@pehbehbeh we do inject custom configuration to the apps.

**Comment by pehbehbeh** [comment]
Thanks!

**Comment by Sakartu** [comment]
That moment when you notice a bug, search for it on GitHub, find there is an Issue created for the exact problem you face and see that it's been fixed 20 minutes earlier.

**Comment by dekaru** [comment]
Thanks, it works now on v0.7.2! I didn't need to add it as a custom app nor update. 

> Restart Rambox and the problem should be gone.

@fvulich  Did you change something remotely on the service?
