### ISSUE TITLE
Full Crash on Rocket Chat

### ISSUE THREAD

**Issue by pcdog** [ramboxapp/community-edition#248]
### Steps to reproduce
1. Add Rocketchat (Newest Version, no Oauth)
2. Log In
3. Wait
4. Crash
### Expected behavior

It should show the chat as in Chrome (where it works)
### Actual behavior

Crash. Total Crash - Rambox dies. Reproducible on Ubuntu and Arch Linux
Chrome_IOThread[13071]: segfault at 30 ip 00000000034d1c74 sp 00007f1a59a58770 error 4 in Rambox[400000+3de5000]
### ENVIRONMENT

Linux thinkx220 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux

> aur/rambox-bin 0.4.1-1 [installed](13) (7.72)
> 
> OS: Arch
> 
> Arch: x64

**Comment by pcdog** [comment]
I got word from one of my users, 0.4.0 ("works with the previous") is not affected.

Might help.

**Comment by saenzramiro** [comment]
So it must be an Electron bug.

They fixed a crash bug in v1.3.2 ([check here](https://github.com/electron/electron/releases/tag/v1.3.2)), but seems to be for macOS. Maybe it's also for Arch.

Let's see if is fixed in next release of Rambox. I will use the latest Electron version.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
