### ISSUE TITLE
RocketChat stopped working after upgrade

### ISSUE THREAD

**Issue by liponcio** [ramboxapp/community-edition#2482]
# Steps to reproduce
1. upgrade from 0.6.9

### Expected behavior
The RocketChat configuration was supposed to function

### Actual behavior
Screen is blank (nothing is shown)

### ENVIRONMENT
Linux 5.0
Rambox: v0.7.2
OS: Mint 19.2
Arch: x64

**Comment by fvulich** [comment]
Could you try deleting the app and adding it again?

**Comment by liponcio** [comment]
Purged everything (run sudo dpkg -r rambox and deleted everything from -/.config/Rambox), reinstalled and it's the same.
Can see whatsapp, TweetDeck but no Rocketchat

**Comment by fvulich** [comment]
I mean remove your Rocketchat app and add it again.

**Comment by liponcio** [comment]
gone a little bit far from that. Removed all, fresh install (0.7.2) and nothing.
reverted to 0.6.9 (fresh install) and RocketChat is working again.
