### ISSUE TITLE
Taskbar Logo e WhatsApp Language

### ISSUE THREAD

**Issue by bukbr** [ramboxapp/community-edition#2483]
- Open Rambox
- On config turn it to show Taskbar and Tray
- It's not displaying Taskbar Rambox Logo
===
Also: WhatsApp is working just with English language

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> linux x64 4.15.0-70-generic

**Comment by fvulich** [comment]
The language issue in WhatsApp was an issue of WhatsApp.  About the other issue please attach some screenshots.

**Comment by bukbr** [comment]
Correct! Thanks!
