### ISSUE TITLE
ctrl c ctrl v

### ISSUE THREAD

**Issue by C-Nog** [ramboxapp/community-edition#2484]
With the last updates its not possible anymore to press ctrl c and ctrl V on Rambox
When I copy some text and then try to paste the following happens

 Ready

 Ready

 Ready

 Ready

 Ready

 Ready

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by Midway83300** [comment]
+1
It's super annoying haha

**Comment by pdecat** [comment]
Dupe of https://github.com/ramboxapp/community-edition/issues/2469
