### ISSUE TITLE
Service Icons Gone since 0.7.1

### ISSUE THREAD

**Issue by svoop** [ramboxapp/community-edition#2485]
Since the update to version 0.7.1 as well as after upping to 0.7.2 on Mojave 10.14.6, the service icons have mostly gone. This may be a local cache problem, but I don't know if/where to find a cache to zap:

<img width="835" alt="Screen Shot 2019-11-22 at 16 02 39" src="https://user-images.githubusercontent.com/7255/69436517-ceb19000-0d41-11ea-8fec-e6519a1b28e2.png">

**Comment by saalkom** [comment]
> I don't know if/where to find a cache to zap
Help (press `Alt` if the menu is auto-hidden) > Tools > Clear Cache

**Comment by svoop** [comment]
That sure did the trick, thanks @saalkom !
