### ISSUE TITLE
cant copy inside rambox

### ISSUE THREAD

**Issue by hasbimuharip** [ramboxapp/community-edition#2487]
Whenever i try to copy some text inside rambox ( e.g slack) and try to paste it in some text editor like notepad ++ it copies something weird like:

>  Ready
> 
>  Ready
> 
>  Ready
> 
>  Ready
> 
>  Ready
> 
>  Ready

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by pdecat** [comment]
Dupe of https://github.com/ramboxapp/community-edition/issues/2469
