### ISSUE TITLE
Black box with nested label in Gmail

### ISSUE THREAD

**Issue by mizzpenny** [ramboxapp/community-edition#2489]
Create a label within Gmail, when checking the nest label under box, there is an error with the dropdown box that populates all the existing labels. Half of that dropdown box is white/clear and other half is black. This issue didn't exist in the previous version, just updated to latest version. Screenshot: https://imgur.com/a/QOc2xEZ

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.

**Comment by fvulich** [comment]
It will be fixed in our new version.
