### ISSUE TITLE
Ram consumption

### ISSUE THREAD

**Issue by SanjaySRocks** [ramboxapp/community-edition#2490]
Rambox consume much n much ram , its a request to dev please can your reduce the usage of ram?

## ENVIRONMENT
Version: 0.7.2
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by fvulich** [comment]
The consumption of RAM depends on the apps that you are opening in Rambox. If you open all of the apps that you have in Rambox in Chrome you will get an idea of the RAM consumption of them. Also, it's not only the number of apps, but some apps also use more ram than others.
