### ISSUE TITLE
Unable to edit service when image link is broken

### ISSUE THREAD

**Issue by benmod** [ramboxapp/community-edition#2491]
### Steps to reproduce

1. Add a new service with a valid image URL
2. Remove the image from the server at the given URL
3. Click on the "wheel" icon next to the service name

### Expected behavior

It opens the window to edit the service. 

### Actual behavior

Nothing happens. (but other service without broken links can be edited fine). 

### ENVIRONMENT

> Rambox: v0.7.1

> OS: OSX 10.12.6

> Arch: x64

**Comment by fvulich** [comment]
Couldn't reproduce in 0.7.2
