### ISSUE TITLE
copy paste problems

### ISSUE THREAD

**Issue by jaal** [ramboxapp/community-edition#2492]
I cannot copy paste from Rambox via shortcuts ctrl+c and ctrl+v. Text ReadyReady appears. I can only copy via mouse's right button and menu Copy

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by pdecat** [comment]
Dupe of https://github.com/ramboxapp/community-edition/issues/246

**Comment by 0xCCD** [comment]
I have the same issue, sometimes when I copy it works but most of the time I have the Text:

Ready Ready Ready Ready Ready Ready You have the latest version of Rambox.
