### ISSUE TITLE
0.7.2 causes system freeze on Linux Mint

### ISSUE THREAD

**Issue by TheTinyProwler** [ramboxapp/community-edition#2493]
Trying to download a media file in linux mint 19 causes whole system to freeze. This happens in version 0.7.2 only. Previous versions work well, either as .ppa or .appimage.

### Steps to reproduce

1. Open Whatsapp in Rambox
2. Select some media to download ( picture, pdf...) 
3. Select save, the opening dialogue freezes and takes the system with it

### Expected behavior

Downloading the file.

### ENVIRONMENT

> Rambox: v0.7.2

> OS: Linux Mint 19.1

**Comment by fvulich** [comment]
Can you reproduce this error in 0.7.1?

**Comment by TheTinyProwler** [comment]
No it only accures in 0.7.2

**Comment by DasJott** [comment]
Appears to me too.

Services are: Slack, Telegram, WhatsApp, Gmail, Twitter, Facebook-Messenger, DevRant.

Used my system for days without any issues. Started Rambox and the system froze after some minutes. It is not always that quick, but this was only a good example.

It also pushes the CPU usage a lot if it doesn't freeze.
There is definitely something wrong with Rambox at the moment!

**Comment by TheTinyProwler** [comment]
Okay, meanwhile there is a slight improvement. As before it occurs only in Whatsapp.
If you open a picture in the chat newsfeed and try to download it from there, the opening dialog does not work, although you can hit the enter button to download it. Then it works!
If you try to download it directly from the chat-feed everything works fine.
OS = (meanwhile) Mint 19.3 Mint on AMD system.
See also attached screenshot.
![upload](https://user-images.githubusercontent.com/39658925/72896343-d5e42280-3d1f-11ea-8b5c-26d655c7abda.png)
