### ISSUE TITLE
[Bug] Copy / Pasting on WhatsApp

### ISSUE THREAD

**Issue by Locked-Key** [ramboxapp/community-edition#2496]
### Steps to reproduce

1. Select a chat message
2. For example, if you highlight "Hello world!" and hit Ctrl+C to copy
3. After pasting with Ctrl+V, the copied text will be:

 Ready

 Readyhttps://messages.google.com/web/conversations/32

 Ready

### Expected behavior

The pasted message should be Hello world!

### Actual behavior

The pasted text will be:
 Ready

 Readyhttps://messages.google.com/web/conversations/32

 Ready

### ENVIRONMENT

> Rambox: v0.7.2

> OS: Windows 10 - Version 10.0.18363 Build 18363

> Arch: x64

**Comment by mhajas** [comment]
Looks like duplicate issue: https://github.com/ramboxapp/community-edition/issues/2469
