### ISSUE TITLE
Custom notification sounds

### ISSUE THREAD

**Issue by madjoe** [ramboxapp/community-edition#2498]
Is there a way to customize a notification sound? It's just too loud for me and I would appreciate if I could choose my own sound for it. Thanks.

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> linux x64 4.19.85-1-MANJARO

**Comment by fvulich** [comment]
Notifications sound are reproduced by the OS and not from Rambox, so if you want to change the sound you will have to find a way to do it changing configurations of the OS.

**Comment by madjoe** [comment]
I can't find that specific sound notification inside /usr/share/sounds/ neither it happens during any of my other notification dialogues/events i.e. notify-send etc. Such notification sound only happens for Rambox **WhatsApp** messages. Could you be more specific: what kind of event is triggered, so I could track that loud sound in my Manjaro?

**Comment by madjoe** [comment]
Found it! It's the annoying Notification > Sound setting inside of WhatsApp (completely unrelated to Rambox)!
