### ISSUE TITLE
Ctrl+C problem

### ISSUE THREAD

**Issue by TonyQuach93** [ramboxapp/community-edition#2501]
I copy a text using Ctrl + C on rambox and below is result 
       (It's ok if u right click and choose copy)

 Ready

 Ready

 Ready

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> linux x64 4.15.0-70-generic

**Comment by fvulich** [comment]
duplicate https://github.com/ramboxapp/community-edition/issues/2469
