### ISSUE TITLE
Slack Plugin: I cannot edit a post

### ISSUE THREAD

**Issue by codekandis** [ramboxapp/community-edition#2502]
### Steps to reproduce

1. Post something to someone
2. Try to edit via `Ctrl+Up` or by the context menu

### Expected behavior

The latest post should be highlighted and be editable.

### Actual behavior

Slack just scrolls up some posts.

### ENVIRONMENT

>Version: 0.7.2
>Platform: linux (x64)
>Electron: 7.1.1
>Chromium: 78.0.3904.99
>Node: 12.8.1
> OS: XXXX

### Additional information

To ensure it's just Slack related I opened Chrome itself (Version 78.0.3904.108 (Official Build) (64-bit)) and experienced the normal behaviour. But there I won't experience this bug.

Furtheron I experienced some other weird Shortcut related behaviour but currently I'm not able to determine some specific occurrences.

**Comment by fvulich** [comment]
Couldn't reproduce in Ubuntu 18.04 and Rambox 0.7.3. Only need to press <kbd>Up</kbd> in order to edit the last post, also works if I press <kbd>Ctrl</kbd> + <kbd>Up</kbd>

**Comment by codekandis** [comment]
Works fine for me since last weekend. Since the services are updated on start this issue might has been fixed in the service without releasing a new Rambox version.

**Comment by fvulich** [comment]
Glad to her that!. Have a nice day.
