### ISSUE TITLE
Dont work TELEGRAM and MAIL.RU windows - part 2

### ISSUE THREAD

**Issue by ds205** [ramboxapp/community-edition#2504]
### Steps to reproduce

Isseus - Part 1: Dont work TELEGRAM and MAIL.RU windows

Retest:

1.  Take Other PC with other OS Win10 LTSB x64 ver.1809.
2.  Install https://github.com/ramboxapp/community-edition/releases/download/0.7.2/Rambox-0.7.2-win-x64.zip
3. Add New Whatsapp Tab - all ok working. 
4. Add New Telegram Tab - Tab adding - it dont ask me telegram auth. Tab Status "Ready". Unable any information in Tab.

**Comment by fvulich** [comment]
I couldn't reproduce this issue. Someone else can?

**Comment by ds205** [comment]
> I couldn't reproduce this issue. Someone else can?

Hello. I try this quest on two different pc with clear installation. the effect is the same. can show on skype.

**Comment by fvulich** [comment]
With other version, lets say 0.6.9 does it work? Any other user with this issue?

**Comment by ds205** [comment]
"Any other user with this issue?" - I did not ask other user.
"lets say 0.6.9 does it work?" - where can I download the version 0.6.9 ?

**Comment by ds205** [comment]
looked in Developer Mode - Errors:

USER LOGGED IN
app.js:1 Checking for updates...
ext/packages/ext-locale/build/ext-locale-ru.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
app.js:1 Start loading... https://web.whatsapp.com/
app.js:1 Start loading... https://web.telegram.org/
app.js:1 Your version is the latest. No need to update.
app.js:1 WHATSAPP - JS Injected to Detect New Messages
app.js:1 TELEGRAM - JS Injected to Detect New Messages
app.js:1 Start loading... https://web.whatsapp.com/
app.js:1 Start loading... https://web.telegram.org/
ipc-renderer-internal-utils.ts:28 Uncaught (in promise) Error: ERR_CONNECTION_REFUSED (-102) loading 'https://web.telegram.org/'
    at rejectAndCleanup (electron/js2c/browser_init.js:5808)
    at WebContents.failListener (electron/js2c/browser_init.js:5818)
    at WebContents.emit (events.js:208)
app.js:1 TELEGRAM - JS Injected to Detect New Messages
app.js:1 Start loading... https://web.telegram.org/
ipc-renderer-internal-utils.ts:28 Uncaught (in promise) Error: ERR_CONNECTION_REFUSED (-102) loading 'https://web.telegram.org/'
    at rejectAndCleanup (electron/js2c/browser_init.js:5808)
    at WebContents.failListener (electron/js2c/browser_init.js:5818)
    at WebContents.emit (events.js:208)
app.js:1 TELEGRAM - JS Injected to Detect New Messages
app.js:1 Start loading... https://web.telegram.org/
ipc-renderer-internal-utils.ts:28 Uncaught (in promise) Error: ERR_CONNECTION_REFUSED (-102) loading 'https://web.telegram.org/'
    at rejectAndCleanup (electron/js2c/browser_init.js:5808)
    at WebContents.failListener (electron/js2c/browser_init.js:5818)
    at WebContents.emit (events.js:208)
app.js:1 TELEGRAM - JS Injected to Detect New Messages
app.js:1 telegram
app.js:1 function checkUnread(){var e=document.getElementsByClassName("im_dialog_badge badge"),t=0;for(i=0;i<e.length;i++)if(!e[i].classList.contains("im_dialog_badge_muted")){t+=parseInt(e[i].innerHTML.trim())}updateBadge(t)}function updateBadge(e){e>=1?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3000);

**Comment by fvulich** [comment]
You can download older versions from [HERE](https://github.com/ramboxapp/community-edition/releases/)

**Comment by ds205** [comment]
Developer Mode Error on other PC (Rambox 0.7.3, win10 ltsc x64):

TELEGRAM - JS Injected to Detect New Messages
app.js:1 telegram
app.js:1 function checkUnread(){var e=document.getElementsByClassName("im_dialog_badge badge"),t=0;for(i=0;i<e.length;i++)if(!e[i].classList.contains("im_dialog_badge_muted")){t+=parseInt(e[i].innerHTML.trim())}updateBadge(t)}function updateBadge(e){e>=1?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3000);

Start loading... https://web.telegram.org/
app.js:1 TELEGRAM - JS Injected to Detect New Messages
app.js:1 telegram
app.js:1 function checkUnread(){var e=document.getElementsByClassName("im_dialog_badge badge"),t=0;for(i=0;i<e.length;i++)if(!e[i].classList.contains("im_dialog_badge_muted")){t+=parseInt(e[i].innerHTML.trim())}updateBadge(t)}function updateBadge(e){e>=1?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3000);
ipc-renderer-internal-utils.ts:28 Uncaught (in promise) Error: ERR_CONNECTION_TIMED_OUT (-118) loading 'https://web.telegram.org/'
    at rejectAndCleanup (electron/js2c/browser_init.js:5808)
    at WebContents.failListener (electron/js2c/browser_init.js:5818)
    at WebContents.emit (events.js:208)

**Comment by fvulich** [comment]
If you try to enter from a browser does it work?

**Comment by ds205** [comment]
https://web.telegram.org/ is working in browser.

**Comment by fvulich** [comment]
@ds205 Are you still having this issue?

**Comment by ds205** [comment]
@fvulich all the same. Telegram section does not display anything. 

Developer Mode log:

TELEGRAM - JS Injected to Detect New Messages
app.js:1 telegram
app.js:1 function checkUnread(){var e=document.getElementsByClassName("im_dialog_badge badge"),t=0;for(i=0;i<e.length;i++)if(!e[i].classList.contains("im_dialog_badge_muted")){t+=parseInt(e[i].innerHTML.trim())}updateBadge(t)}function updateBadge(e){e>=1?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3000);

**Comment by fvulich** [comment]
Could you try using this User Agent?
`Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36`

You must put it in Preferences

**Comment by ds205** [comment]
Hello. It work!

С уважением, Добрынин Сергей
Тел: +7 912 22-99-199
Эл. адрес arendator66@gmail.com




вт, 23 июн. 2020 г. в 19:00, Vulich Fernando <notifications@github.com>:

**Comment by fvulich** [comment]
Glad to hear that!

**Comment by trustin** [comment]
Could this be the default for Telegram? Telegram sign-in process doesn't work without setting the custom user agent at the moment. Tried on Rambox Pro 1.4.1.
