### ISSUE TITLE
Rambox Taskbar Logo Icon

### ISSUE THREAD

**Issue by bukbr** [ramboxapp/community-edition#2505]
Version: 0.7.2
Linux (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

### Expected behavior
Rambox logo should be on taskbar icon too

See attached image.
![screen](https://user-images.githubusercontent.com/43289255/69901358-4a719500-135f-11ea-9eb4-4992a39f9718.png)

**Comment by fvulich** [comment]
Did you try another Linux package? Which one are you using?

**Comment by bukbr** [comment]
Hi! I used Rambox-0.7.2-linux-amd64.deb and have not tried any other...

**Comment by sollymay** [comment]
same thing happening for me with 0.7.3 in elementary using the .appimage 64 bit version

**Comment by sollymay** [comment]
I was able to fix the issue by running the appimage using app image launcher. for some reason the dialog to integrate with system did not show up on 0.7.3 update but I reinstalled the app using this method and that fixed the issue

**Comment by fvulich** [comment]
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.

**Comment by bukbr** [comment]
Sorry fvulich, but it's not fixed! Issue persists, even after all instructions! 
![Captura de tela em 2020-04-10 23-35-16](https://user-images.githubusercontent.com/43289255/79033368-20897400-7b84-11ea-84e9-acfa012ace8a.png)
