### ISSUE TITLE
Outlook 365 high CPU usage after a while even when idle

### ISSUE THREAD

**Issue by LordBoos** [ramboxapp/community-edition#2506]
### Steps to reproduce

1. Open Rambox
2. Add Outlook 365 service
3. Just use the computer and Rambox for a while

### Expected behavior

CPU usage should be minimal while not interacting with Rambox or Rambox is in background or in the tray.

### Actual behavior

After some time working with Rambox and my computer, I can see unusually high CPU usage.
In Task Manager Rambox is taking 20% of CPU and it doesn't matter which tab is open or if Rambox is in the tray, minimised, in the background or in the foreground.
If I kill the procces that's taking 20% CPU, my Outlook 365 tab dies and shows gray page.
When the proccess is killed and I attempt to Reload Outlook 365 tab by right click -> Reload then whole Rambox completely crashes. After I launch Rambox again CPU usage is normal for a while, but after some time the same high CPU usage appears.

I have tried reinstalling the Rambox and even Windows (I had that in my plan for a while). This is a really big issue for me because I'm software developer and every percent of my CPU is required for my work.

### ENVIRONMENT

This problem started to occur after the 0.7.0 update.

Version: 0.7.2
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1
OS: Windows 10

**Comment by fvulich** [comment]
Someone else could reproduce this issue?

**Comment by LordBoos** [comment]
I've reinstalled windows recently - completely with formatting my HDD and installing from installation media. The issue still persists.
