### ISSUE TITLE
Rambox Pro Stupid High memory usage

### ISSUE THREAD

**Issue by darkeyce** [ramboxapp/community-edition#2514]
### Steps to reproduce

1. Install and run Rambox Pro
2. Create 3 Groups with any number of apps in each group
3. Open task manager and look at the memory consumption

### Expected behavior

A reasonable number of subtasks and memory usage

### Actual behavior

With 4 groups and 22 apps (not all signed in) across them I have RamboxPro consuming **6903MB** or memory with 82 ramboxpro subtasks

### ENVIRONMENT

> RamboxPro: v1.2.0

> OS: Win10 Pro 1909 (18363.476)

> Arch: x64

**Comment by fvulich** [comment]
This support channel is for Rambox CE users. If you are using Rambox Pro, please use our [Support Portal](https://rambox.freshdesk.com) to report your problems, and we will try to help you there.
