### ISSUE TITLE
gmail login fail

### ISSUE THREAD

**Issue by olybop** [ramboxapp/community-edition#2518]
not possible to log the gmail account : 
in french : Vous essayez de vous connecter via un navigateur ou une application ne nous permettant pas de protéger votre compte.

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> darwin x64 18.7.0

**Comment by delphym** [comment]
I believe this issue has been fixed in Rambox v0.7.3

**Comment by olybop** [comment]
Yes ! Fixed on 0.7.3.
Thx !
