### ISSUE TITLE
Couldn't sign into Hangouts

### ISSUE THREAD

**Issue by delphym** [ramboxapp/community-edition#2519]
### Background
I've used to use Hangouts in Rambox for a quite long period of time now without any issues.
Since yesterday,  it was displaying false notifications (like I have one unread message). No refresh could get rid of it, so I've decided to log out. Which turned out to be fatal.

### Issue
When you need to login to your Google account to make your enabled Hangouts service functional, after providing an account (email address) and password, Google reports this problem:

> **Couldn't sign you in**
> 
> xxxxx@gmail.com
> You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
> Try using a different browser. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-GB)

From the above link it is quite obvious that Rambox is not explicitly supported and they did some prevention Hangouts runs embedded:

> To help protect your account, Google doesn’t let you sign in from some browsers. Google might stop sign-ins from browsers that:
> 
> Don’t support JavaScript or have Javascript turned off.
> Have unsecure or unsupported extensions added.
> Use automation testing frameworks.
> Are embedded in a different application.
> 

### Steps to reproduce
1. Add a new service (choose Hangouts from the list) and leave default values
2. Go to the new Hangouts tab
3. Click on Sing In
4. Provide your email or phone and password
5. Click Next

## Expected results
- got signed in to Hangouts
- possibly are prompted for MFA (if enabled)

## Actual results
- Got message:

> You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
> Try using a different browser.

 

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> darwin x64 18.7.0

**Comment by kastnerp** [comment]
Same issue here.

**Comment by delphym** [comment]
Fantastic job @saenzramiro !
Immediate response and fix within a few hours from reporting.

The issue has been resolved now, so closing it.
