### ISSUE TITLE
No puedo acceder a Gmail

### ISSUE THREAD

**Issue by Monyinet** [ramboxapp/community-edition#2520]
Al tratar de acceder a Gmail, tras introducir el email y la contraseña, aparece el siguiente mensaje:

Estás intentando iniciar sesión desde un navegador o una aplicación que no nos permite mantener tu cuenta protegida.
Prueba con otro navegador. Más información

Salu2

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> win32 x64 10.0.17763

**Comment by delphym** [comment]
I believe this issue has been fixed in Rambox v0.7.3

**Comment by fvulich** [comment]
Fixed in 0.7.3

**Comment by Monyinet** [comment]
Thanks 😉
