### ISSUE TITLE
Electron Error upon execution

### ISSUE THREAD

**Issue by waltsims** [ramboxapp/community-edition#2522]
### Steps to reproduce

1. download  `Rambox-0.7.3-linux-amd64.deb`
2. `dpkg -i Rambox-0.7.3-linux-amd64.deb`
3. `cd /opt/Rambox/`
4. `./rambox`

### Expected behavior

Rambox starts and messaging begins

### Actual behavior

```
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
```

program returns
no window opens
 

### ENVIRONMENT

> Rambox: v0.3.7

> OS:
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan

> Arch: x64

**Comment by fvulich** [comment]
Tested in Ubuntu 18.04 and it's working as it should. Could you try with another package? Any other user having this issue?

**Comment by waltsims** [comment]
The issue seems to have been resolved. By a restart it would seem...
