### ISSUE TITLE
Chmod need after deb installation

### ISSUE THREAD

**Issue by brenard** [ramboxapp/community-edition#2523]
Rambox can't be run after installation of the amd64 deb file with the following error :
`[5270:1212/100020.130013:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Rambox/chrome-sandbox is owned by root and has mode 4755.
Trappe pour point d'arrêt et de trace`

To fix this problem, I just need to run the following command after each installation/upgrade : `sudo chmod 4755 /opt/Rambox/chrome-sandbox`

### Steps to reproduce

1. Download amd64 deb file from github
2. Install it, using `dpkg` command
3. Try to run Rambox (from command-line to see the error, but it's also fail from menu)

### Expected behavior

Rambox should get started.

### Actual behavior

Rambox fail to start.

### ENVIRONMENT

> Rambox: v0.7.3 (but I have this problem since 0.7.0 or 0.7.1)

> OS: Debian GNU/Linux 9.11 (Stretch)

> Arch: x64

**Comment by fvulich** [comment]
Duplicate #2451
