### ISSUE TITLE
FATAL:setuid_sandbox_host.cc(157)

### ISSUE THREAD

**Issue by stephanmq** [ramboxapp/community-edition#2524]
Everytime after updating the community version I get the following error when I launch the app :
**"[9147:1212/094249.405778:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Rambox/chrome-sandbox is owned by root and has mode 4755."**

To fix it I have to manually change the rights on /opt/Rambox/chrome-sandbox as mentionned in the message. 

This error started since some previous release (probably 0.6.9)

### ENVIRONMENT

> Rambox: v0.X.X

> OS: DEBIAN BUSTER

> Arch: x64

**Comment by sgobotta** [comment]
> Everytime after updating the community version I get the following error when I launch the app :
> **"[9147:1212/094249.405778:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Rambox/chrome-sandbox is owned by root and has mode 4755."**
> 
> To fix it I have to manually change the rights on /opt/Rambox/chrome-sandbox as mentionned in the message.
> 
> This error started since some previous release (probably 0.6.9)

Same here, 0.6.9 works fine but I've got the same permissions requirement notice on v > 0.7.x

Again, as @stephanmq says: `chmod 7455  /opt/Rambox/chrome-sandbox` does the trick.

> Rambox: v0.7.3
> OS: Debian stretch
> Arch: x64

**Comment by fvulich** [comment]
duplicate #2481
