### ISSUE TITLE
Gmail login problem

### ISSUE THREAD

**Issue by ugorur** [ramboxapp/community-edition#2525]
When I try to login its says this.

Bu tarayıcı veya uygulama güvenli olmayabilir. Daha fazla bilgi

Farklı bir tarayıcı kullanmayı deneyin. Zaten desteklenen bir tarayıcı kullanıyorsanız bulunduğunuz sayfayı yenileyip tekrar oturum açmayı deneyebilirsiniz.

For summary, my browser is unseccure.

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> linux x64 4.15.0-72-generic

**Comment by fvulich** [comment]
Could you try deleting the Gmail app and adding it again?

**Comment by ugorur** [comment]
I try and I couldn't again

**Comment by fvulich** [comment]
We want to know if you still have this problem.

**Comment by ugorur** [comment]
Yes I steel have problem. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Vulich Fernando <notifications@github.com> Date: 12/20/19  19:38  (GMT+03:00) To: ramboxapp/community-edition <community-edition@noreply.github.com> Cc: Umurcan Gorur <mail@ugorur.com>, Author <author@noreply.github.com> Subject: Re: [ramboxapp/community-edition] Gmail login problem (#2525) We want to know if you still have this problem.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ramboxapp/community-edition/issues/2525?email_source=notifications\u0026email_token=AAUTRER6GMWNZKK6DRMK5ALQZTYGVA5CNFSM4J2DCREKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHNM5DI#issuecomment-567987853",
"url": "https://github.com/ramboxapp/community-edition/issues/2525?email_source=notifications\u0026email_token=AAUTRER6GMWNZKK6DRMK5ALQZTYGVA5CNFSM4J2DCREKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHNM5DI#issuecomment-567987853",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by fvulich** [comment]
Are you still having this issue?

**Comment by ugorur** [comment]
With last update, its fixed.
~Umur

**Comment by SoylenHolger** [comment]
I got a new gaming machine and reinstalled rambox but I get the gmail log-in issue again.

"browser not safe" etc...

I tried to overwrite the user agent, cleared cache but that didn't help unfortunately. Any more workarounds?

**Comment by hg42** [comment]
I had this problem on Debian testing.
Deleting GMail and adding it again worked in this case.

**Comment by saenzramiro** [comment]
Let's merge this with #2835.
