### ISSUE TITLE
Tooltip hides button to close status bar

### ISSUE THREAD

**Issue by jerry1970** [ramboxapp/community-edition#2527]
I've seen this before but apparently it's back... When I move the mouse to the X to close the status bar the tooltip is hiding the X.

![image](https://user-images.githubusercontent.com/5627407/70780971-041c2d00-1d86-11ea-997d-0496b87eea0b.png)

### ENVIRONMENT
```
Version: 0.7.3
Platform: linux (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1
```

Isn't there a way to not have a status bar at all? What kind of messages can be shown there?

**Comment by fvulich** [comment]
You can disable the status bar from the app configuration.
![image](https://user-images.githubusercontent.com/46904390/70808419-6a14ae80-1d9e-11ea-9f3f-10dbe4d4c354.png)
