### ISSUE TITLE
problems with discord

### ISSUE THREAD

**Issue by LetsHaveKidsWithoutTheSex** [ramboxapp/community-edition#2529]
discord screen share doesn't work.
everything else is flawless. 

	
	-

	> Rambox 0.7.3
	> Electron 7.1.1
	> linux x64 5.0.0-37-generic

**Comment by ahake** [comment]
You can only screenshare from the Windows Desktop Client. Given that Rambox displays the Webinterface you won't be able to go live. [refer to this](https://support.discordapp.com/hc/en-us/articles/360030714312-Go-Live-FAQ)
