### ISSUE TITLE
Rambox detects my microphone, but not my voice

### ISSUE THREAD

**Issue by Endalaust** [ramboxapp/community-edition#2530]
### Steps to reproduce

1. Open Rambox
2. Open chat with vocal (trying discord)
3. Discord detects my microphone, but not my voice

I tried with 2 external microphones, they are recognized, but the voice is not transmitted either. I haven't tried any other applications than Discord.
<img width="702" alt="screenshot_08" src="https://user-images.githubusercontent.com/1420867/70944592-ade40e00-2053-11ea-9031-fd122fad20da.png">

### Expected behavior

Voice should be detected

### Actual behavior

Voice is not

### ENVIRONMENT

> Rambox: v0.7.3
> OS: OSX 10.15.2 (Catalina)
> Computer : mbp 16 late 2019

**Comment by Endalaust** [comment]
Update : Rambox doesn't have microphone access

<img width="768" alt="screenshot_18" src="https://user-images.githubusercontent.com/1420867/71324782-6b06b800-24e3-11ea-8c8d-650aa9b68452.png">

BUT, this access is generated by the apps automatically, I can't add an access manually. I have the impression that Rambox does not ask for access to the microphone (otherwise I would see it in this list...).

**Comment by Endalaust** [comment]
If it could help: I have two macintochs, one on Mojave (10.14.6) and one on Catalina (10.15.2).

Rambox is version 0.7.3 on both machines. The PC on Mojave detects my microphone, the one on Catalina does not. 

I think it's something with the new Apple Catalina OS, but it's just an idea...
Thanks a lot.

**Comment by fvulich** [comment]
Yes, it's related to Catalina, and we're investigating how to fix this issue.

**Comment by garethjax** [comment]
@fvulich actually i have mojave and i'm having the same issue.

**Comment by fvulich** [comment]
Sorry it's not only Catalina, the issue started with Mojave.

**Comment by Brockjava** [comment]
I have had problems with Mojave and now Catalina too.

**Comment by fvulich** [comment]
It will be fixed in our next release

**Comment by Endalaust** [comment]
Finally :)
Thanks dude

**Comment by Endalaust** [comment]
Works fine. Well played
