### ISSUE TITLE
Building Rambox on Windows - Only Blue Screen with Menu Bar

### ISSUE THREAD

**Issue by Sx3** [ramboxapp/community-edition#2531]
### Steps to reproduce

1. git clone https://github.com/ramboxapp/community-edition.git
2. cd rambox
3. cp env-sample.js env.js
4. npm install
5. npm run build:win64

Then either run Rambox.exe inside win-unpacked folder or install "Rambox-0.7.3-win" setup 
### Expected behavior

should work as the normal installer from Rambox

### Actual behavior

Blue background with menu.
![image](https://user-images.githubusercontent.com/3599933/71064812-00c5de80-2196-11ea-8ac4-b197c4da40d3.png)

### ENVIRONMENT

> Rambox: v0.7.3

> OS: WIN 7

> Arch: x64

NOTE:- The issue is with the **"app.asar"** file in resources folder...when the file **"app.asar"** from a original installer (after install just copy the file) is copied to the resources folder of the build (ex:- **\dist\win-unpacked\resources** ) it works normally.

**Comment by fvulich** [comment]
Try these steps:

1. git clone https://github.com/ramboxapp/community-edition.git
2. cd rambox
3. cp env-sample.js env.js
4. npm install
5. npm run sencha:compile
6. cd..
7. cd rambox-build
8. npm install
9. npm run build:win64

**Comment by Sx3** [comment]
Thank your very much. above steps worked perfectly !

**Comment by fvulich** [comment]
Glad to hear that! Have a nice day.
