### ISSUE TITLE
notification missiging while the application minimized

### ISSUE THREAD

**Issue by asmaa313** [ramboxapp/community-edition#2533]
I have added nextcloud service to rambox CE and while using nextcloud chating  or talk when i have anew message or any notification there wasn't any alarm or notification when the rambox minimized .

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> linux x64 5.3.0-24-generic

**Comment by fvulich** [comment]
We haven't received a response to our question in this ticket. With only the information that is currently in the ticket, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
