### ISSUE TITLE
No services icons after update

### ISSUE THREAD

**Issue by wedens** [ramboxapp/community-edition#2537]
I've updated the app to 0.7.3 (I don't remember which version I had before the update, but it wasn't too old) and almost all services icons disappeared.

This problem seems to be similar to [this](https://github.com/ramboxapp/community-edition/issues/2485) issue, but clearing the cache didn't help in my case. I tried removing ~/.config/Rambox directory and it didn't help either.

![image](https://user-images.githubusercontent.com/697162/71580255-6faa1c80-2b32-11ea-805f-c5fc5675ace8.png)

### ENVIRONMENT

> Rambox: v0.7.3

> OS: Arch Linux

> Arch: x64

**Comment by fvulich** [comment]
Could you try another package? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases)

**Comment by schuettecarsten** [comment]
I have the same problem with Rambox 0.7.3, but on Windows 10...

**Comment by wedens** [comment]
@fvulich Sorry, which another package? [this](https://github.com/ramboxapp/community-edition/releases/download/0.7.3/Rambox-0.7.3-linux-x64.tar.gz) is the package I use.

**Comment by schuettecarsten** [comment]
I was able to solve it:
firebasestorage.googleapis.com was accidentially added to a DNS blocklist.

**Comment by wedens** [comment]
I'm not sure what changed, but I no longer have this problem (with the same rambox version).
