### ISSUE TITLE
Install on Linux Instructions - Youtube Video instructions has violated TOS

### ISSUE THREAD

**Issue by sidouglas** [ramboxapp/community-edition#2540]
### Steps to reproduce

1. Go to page https://github.com/ramboxapp/community-edition/wiki/Install-on-Linux
2. Click on the Youtube link
3. Try and view the video at https://www.youtube.com/watch?v=SH6o92b7FlA

### Expected behavior

Should be able to view the tutorial video

### Actual behavior

Video has been blocked due to TOS violation.

### ENVIRONMENT

> Rambox: v0.7.3

> OS: popos 19.10

> Arch: x64

**Comment by fvulich** [comment]
Thanks for reporting it. I updated the wiki. Please check it up. https://github.com/ramboxapp/community-edition/wiki/Install-on-Linux
