### ISSUE TITLE
Error when moving Rambox window

### ISSUE THREAD

**Issue by Orioz** [ramboxapp/community-edition#2544]
After update to new version an error pops up every time the main window is moved.

### Steps to reproduce

1.  Start Rambox
2.  Move the Rambox window

### Expected behavior

No error

### Actual behavior

Error popup
![bild](https://user-images.githubusercontent.com/15891817/71674408-619b0c80-2d7b-11ea-998c-81fe6b072fdc.png)

### ENVIRONMENT

> Rambox: v0.7.3

> OS: Windows 10

> Arch: x64

**Comment by fvulich** [comment]
Could you try reinstalling Rambox? We couldn't reproduce this error.

**Comment by Orioz** [comment]
Reinstalling fixed the error, now it seems to work fine.

But when uninstalling I noticed that windows shows two versions of rambox installed, 0.6.9 and 0.7.3.
Probably just an unrelated issue.

**Comment by fvulich** [comment]
Glad to hear that you could solve it. Yes, it's an unrelated issue. Have a good day.
