### ISSUE TITLE
Missing window preview in Mission control

### ISSUE THREAD

**Issue by Vantomas** [ramboxapp/community-edition#2545]
Hi, after update to last version 0.7.3 I'm experiencing problem with missing preview in Mission control, I see just empty window (see in attachment). Previously I had 0.7.2 and everything was alright. 

I tried to disable hardware acceleration, but this option does not affect it. 

![Snímek obrazovky 2020-01-06 v 12 52 34](https://user-images.githubusercontent.com/5727555/71816596-73cec080-3083-11ea-8da1-319f5d947fe8.png)

### Steps to reproduce

1. Open mission control and look on previews of desktops

### Expected behavior

I want to see content of the window.

### Actual behavior

I don't see content of the window, just white area.

### ENVIRONMENT

Rambox: v0.7.3
OS: macOS Mojave 10.14.6
Arch: x64

**Comment by fvulich** [comment]
The bump from 0.7.2 to 0.7.3 did not have major changes, so if it worked in 0.7.2 it should work in 0.7.3. Could you try deleting the app and add it again? If that doesn't work, could you downgrade to 0.7.2 to check if it is still working?

**Comment by fvulich** [comment]
We haven't received a response to our question in this ticket. With only the information that is currently in the ticket, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Vantomas** [comment]
Hello,
sorry, I forget on this bug. 

Now I tried versions 0.7.3, 0.7.2 and 0.7.1 and preview missing in all versions, so it is related to macOS 10.14.6 update. 

I'm doing updates of macOS and Homebrew together, so I can lightly overlook what is cause. Now I'm stuck on Mojave due to missing 32bit support in Catalina, so I don't know if problem persist in newer versions of macOS. 

For this moment we can leave this bug closed.

**Comment by briankendall** [comment]
I'm also experiencing this bug. Rambox 0.7.3 and macOS 10.14.6.

**Comment by briankendall** [comment]
[This is apparently a bug with Electron 7.](https://github.com/electron/electron/issues/19430) That probably means there's nothing that can be done in Rambox itself until Electron fixes the bug, at which point hopefully updating to that new version of Electron in Rambox will fix this.

**Comment by fvulich** [comment]
0.7.8 Released. You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
Is this issue still reproducible in it?

**Comment by Vantomas** [comment]
Hi, sorry for the late response. I think this problem disappeared shortly after the release of the 0.7.4 update.
