### ISSUE TITLE
Rondcube don't refresh

### ISSUE THREAD

**Issue by yu-design** [ramboxapp/community-edition#2547]
I have connect my OVH web mail to Rambox with rondcube, the problem is who I can't refresh the page and well can't recieved my mails or read other.

Can you see if it's a problem or if I need to do a specific param.

Thank, yu-design.

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by fvulich** [comment]
Could you share with us some screenshots of the issue, including in them the Developers tools of the service? 
![image](https://user-images.githubusercontent.com/46904390/72619015-207a2f00-391b-11ea-8ae5-080ee83eb0ab.png)

**Comment by fvulich** [comment]
We haven't received a response to our question in this ticket. With only the information that is currently in the ticket, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
