### ISSUE TITLE
DON'T WORK DIRECT INSTAGRAM

### ISSUE THREAD

**Issue by aleksandrzm** [ramboxapp/community-edition#2548]
I launch Instagram Direct, but it does not open and it is not in the application

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.17763

**Comment by aleksandrzm** [comment]
I launch Instagram Direct, but it does not open and it is not in the application

**Comment by aleksandrzm** [comment]
Я запускаю Instagram Direct, но он не открывается и его нет в приложении

**Comment by fvulich** [comment]
Could you share with us some screenshots of the issue? 
Could you try this [link](https://www.instagram.com/direct/inbox/) from your browser? It may be blocked by location

**Comment by fvulich** [comment]
We haven't received a response to our question in this ticket. With only the information that is currently in the ticket, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
