### ISSUE TITLE
Keyboard shortcuts for switching services still does not focus the service

### ISSUE THREAD

**Issue by StormPooper** [ramboxapp/community-edition#2549]
Originally logged in #2461 but is still an issue in 0.7.3 - description below includes updates from that ticket.

---

Looking at the code for 0.7.1, I see that theoretically it should be focusing the tab content when they keyboard is used to switch apps, however it doesn't seem to be working. When using the mouse to switch apps, it behaves correctly. This is still an issue in 0.7.3.

Noticed whilst testing the original ticket that the keyboard input is sent to the previously focused service, so if I switch away from Discord with Ctrl+Tab and press a Discord shortcut or type, when I go back to Discord with Ctrl+Shift+Tab, it's acted on those inputs.

## Steps to reproduce

* Move to a service (Ctrl+Tab, Ctrl+Num, etc)
* Attempt to press the shortcut (Alt+Shift+Up in Discord, for example) or start typing if a text field was previously in focus

*Detailed steps with [video](https://github.com/ramboxapp/community-edition/files/3879453/RamboxFocusBug.zip):*

0. Forgot to include this in the video, focus the input field in Discord, then switch to Android Messages
1. Focus input field in Android Messages
2. Ctrl+2 to change to Discord - notice input field does not have focus
3. Type 'test' - not visible in Discord
4. Ctrl+4 to change to Messages - 'test' shows up in Messages input field
5. Type something else - shows up in same input field
6. Click on Discord icon
7. Type 'test' again - shows up in Discord input field

## Expected behavior

The shortcut or other keyboard input should be forwarded to the app and it should react appropriately.

## Actual behavior

Nothing happens. Clicking within the app somewhere or on the app service icon and then trying a shortcut again will work.

## ENVIRONMENT

*Original report:*
Version: 0.7.1
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

*Current version:*
Version: 0.7.3
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by fvulich** [comment]
I couldn't reproduce this error, all the tabs get the focus when they should. Could you check if there's and error in the Developers tools console when you use the shortcuts?

**Comment by StormPooper** [comment]
Just checked, the only error I can see is from when the app first launched, which doesn't look related:
![image](https://user-images.githubusercontent.com/1657182/72617997-17e12300-3932-11ea-8fed-d3383332caa6.png)
That's the entirety of the log, having been using the app for most of the day.
