### ISSUE TITLE
Can't lock Rambox by pressing F2

### ISSUE THREAD

**Issue by sp-ferran-mestres** [ramboxapp/community-edition#2550]
In the last version, I can't password-lock Rambox by pressing F2. This was something super useful I used everyday. Can you bring it back?
Thanks a lot!

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by fvulich** [comment]
In version 0.7.1 the shortcut was changed because the users complain that it was too easy to hit it by mistake
![image](https://user-images.githubusercontent.com/46904390/72616716-46e99b80-3916-11ea-9fd8-db8a45161950.png)

**Comment by sp-ferran-mestres** [comment]
Thanks for the info!
Just FYI, the Lock Rambox command (and by extension its shortcut) is nowhere to be found in the menus.
