### ISSUE TITLE
Adding Pulse SMS web client to rambox

### ISSUE THREAD

**Issue by noraj** [ramboxapp/community-edition#2551]
Type: Feature request

Adding Pulse SMS web client to rambox.

## Pulse SMS

Pulse SMS is a cross-platform SMS client:

• web
• iOS
• desktop (Windows, macOS, and Linux)
• Chrome
• Tizen OS

The web version source is here: https://github.com/klinker-apps/pulse-sms-web

[Now the Android client is open source](https://alternativeto.net/news/2020/1/pulse-sms-android-client-is-now-open-source/) like all other clients.

**Comment by fvulich** [comment]
Please try it as a custom app and if it works as it should share with us the URL, some screenshots or even better a video (you could use www.loom.com for it), so we can add it. I couldn't try it myself because in order to use it you'll a subscription and a credit card.

**Comment by noraj** [comment]
Yeah I saw all clients are open source a a paid subscription is needed to sync the messages. Thats sucks I'll close it.
