### ISSUE TITLE
Slack URL is not remembered

### ISSUE THREAD

**Issue by xannasavin** [ramboxapp/community-edition#2552]
Everytime I open Rambox, I have to enter the URL of Slack to be logged in again. User and PW is remembered...

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
Could you try deleting that app and adding it again?

**Comment by xannasavin** [comment]
you mean deleting the whole rambox app or only the slack app within rambox?

**Comment by fvulich** [comment]
Only the slack app.

**Comment by xannasavin** [comment]
that did the job! thank you!
