### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by lipefleming** [ramboxapp/community-edition#2556]
The message is not supported on your version of Telegram Web. Update the app to view: web.telegram.org.

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
I checked if they work in Chrome, and they don't. It seems to be a Telegram's restriction to its own web app. Sadly, there is nothing that we can do about it. For this issue you'll have to go to the Telegram's support page.
