### ISSUE TITLE
Changed Google Voice Password

### ISSUE THREAD

**Issue by BGMcoder** [ramboxapp/community-edition#2557]
I changed my Google Voice password, and now, in Rambox, when I log in with it, it tells me, "This browser or app may not be secure.  Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."

And I can't get past that screen.

If I use View > Reload Service, then it takes me back to the google login screen and I get the same responses when I try again.

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 6.1.7601

**Comment by fvulich** [comment]
We're investigating your issue. Could you try something? Add a new Gmail app and try to get logged using the same credentials that you used in Google Voice and share with us the results

**Comment by BGMcoder** [comment]
Thanks for your time!  I added gmail and can log into that fine.  I reloaded the Google Voice tab, but have the same issue.

**Comment by fvulich** [comment]
Thanks for the feedback. We are working on a workaround for this behavior.

**Comment by dmreagan** [comment]
Same issue here. I'm using the Linux snap package.

**Comment by BGMcoder** [comment]
Is there a way to clear the cache?

**Comment by isviridov** [comment]
Same issue (MacOS 10.14.6, Rambox CE 0.7.3).
There is no need to change password to trigger this; logged in session (cookie?) would eventually expire and then get stuck when trying to reauthenticate. This appears to be a change in Google treatment of Rambox's Electronic browser, with explanation link pointing to https://support.google.com/accounts/answer/7675428?hl=en

**Comment by BGMcoder** [comment]
I just upgraded to Win10-1909 x64 and with a fresh install of Rambox 0.7.3, I can only load one of my two Google Voice accounts.  The first one loads, but the second gets stuck at the login like I described in the original post.

**Comment by BGMcoder** [comment]
No clues on this?  I've tried everything.  I even tried it on a fresh install of Windows.

**Comment by fvulich** [comment]
It will be fixed in our next release.

**Comment by fvulich** [comment]
Please update to 0.7.4, In that version this issue is fixed.

**Comment by BGMcoder** [comment]
FIXED!  Just confirming!  (sorry to unclose the ticket, though)  but it works now!  Thanks so much!

**Comment by fvulich** [comment]
Glad to hear that! Have a nice day!
