### ISSUE TITLE
Microsoft Team: Screen Share not working

### ISSUE THREAD

**Issue by unknownankit** [ramboxapp/community-edition#2559]
I believe the way Microsoft teams is added to RamBox is by adding the website into it, like a Progressive Web Application. In its web version also, the screen sharing is not applicable. But it would be great if it can be added to RamBox.

Steps:- 
1) Start a call with a colleague.
2) From the menu bar at the bottom, try sharing the desktop/screen.

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
Sadly if the web app doesn't allow it, there is no way that we can get that behavior.
