### ISSUE TITLE
Add possibility to hide chat services icons

### ISSUE THREAD

**Issue by andrius** [ramboxapp/community-edition#256]
Icons take so much space and with my setup (12 chat-services), its better to remove them. I believe there is many people who would like to remove those icons too.

It is possible to disable icons somehow?

**Comment by saenzramiro** [comment]
Is not better to leave **Name** empty so only see icons?

I use 15 services and only two of them have a name in the tab, the others only the icon. With this setup I have enough space and also I have an empty space to keep adding.

**Comment by abazeed** [comment]
You can disable the services that you don't want, but it will stay appeared within the icons (grayed), it's better to have the option to hide the disabled services.

**Comment by Corchoneitor** [comment]
Functionality can be achieved by setting an empty Name for the service.
