### ISSUE TITLE
Slack group icons aren't showing

### ISSUE THREAD

**Issue by flyingnobita** [ramboxapp/community-edition#2561]
**Steps to reproduce**
Add a Slack workspace

**Expected behavior**
Rambox should display the tab with the Slack workspace icon

**Actual behavior**
Rambox displays a generic Slack icon and it seems there is no easy way to switch.

Just like [Issue #2443 ](https://github.com/ramboxapp/community-edition/issues/2443)

Tried deleting and re-adding the Slack service but didn't work

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
Could you try hitting Ctrl + R ? That way Rambox will try to get the workspace icon again.

**Comment by flyingnobita** [comment]
I tried this before I reported the issue but it didn't work.  Though for the past few days the icon seems to have come back again without me doing anything.  I'll close this issue as I don't currently see this problem.
