### ISSUE TITLE
Chat windows aren't loading

### ISSUE THREAD

**Issue by thechantaro** [ramboxapp/community-edition#2562]
As the title says. I have Rambox on Autostart with windows and I have to reload each window every time I start my pc.

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by fvulich** [comment]
Are you behind a corporate network or proxy or VPN?

**Comment by thechantaro** [comment]
I am not behind any proxy or VPN. Also the windows that don't load are pretty RNG.

**Comment by fvulich** [comment]
It seems that when Rambox starts there's no active internet connection.
