### ISSUE TITLE
Fail Login to Google Products

### ISSUE THREAD

**Issue by ypraw** [ramboxapp/community-edition#2563]
### Steps to reproduce

Google changed their API, so now they consider non-browser apps as insecure. The way to change this is doing some kind of catch the token using google-ways like this [Google Ways](https://developers.google.com/identity/protocols/OAuth2InstalledApp). 
I found this issue in several electron applications that access Google accounts such as Odrive.
I have tried to solve this issue (actually on Odrive repo) but still same.

### Expected behavior

can Login to All Google Product

### ENVIRONMENT

> Version: 0.7.3

> Platform: linux (x64)

> Electron: 7.1.1

> Chromium: 78.0.3904.99

> Node: 12.8.1

> OS: ManjaroLinux 18.1.5 x86_64 

> Arch: x64

**Comment by fvulich** [comment]
Could you check if you can get logged in a fresh-added Gmail app inside Rambox CE?

**Comment by fvulich** [comment]
We haven't received a response to our question in this ticket. With only the information that is currently in the ticket, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
