### ISSUE TITLE
Problem - no sound and no tag

### ISSUE THREAD

**Issue by AlexKarel** [ramboxapp/community-edition#2565]
Good afternoon.
There are two problems in the program:
1. There is no sound in any application. No, when you receive messages in social networks, there is no sound from the video.
2. It already was. The icon for a new message does not appear on the tab of the VK.COM social network account
http://prntscr.com/qs43or
I would be grateful for the recommendations

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.17134

**Comment by fvulich** [comment]
1. Please check if you have the "Do not disturb" feature on.
2. I made some changes and it should be working now. Please restart Rambox CE in order to get the latest apps configurations

**Comment by AlexKarel** [comment]
Good afternoon. After restarting the program, an alert and a sound are working. Many thanks!
There are two more questions:
1. In Russia, there is another very popular social network - Odnoklassniki (people who studied in the same class at school, college or university). https://ok.ru/ It is the second in terms of coverage in Russia after VK.COM. Are you planning to connect it to the program?
2. There may be a setting, but I did not find it. When the program is launched on the computer, the VK.COM tab is launched in the "for smartphone" format. http://prntscr.com/qsmqem
Where to turn on the settings so that the page starts immediately in the version "for the computer"?
Thanks!

**Comment by fvulich** [comment]
I just added OK.RU as a native service, restart Rambox to get the changes. Regarding the VK.COM tab I just added a new one and it shows me the desktop version. Could you try deleting the VK.COM app and add it again?

**Comment by AlexKarel** [comment]
Good afternoon. Thank you very much! There is one problem with ok.ru: the
numbers on the tab do not indicate the number of Messages, but indicate the
number of Discussions.
[image: Доработка приложения.jpg]

This is the only inconvenient moment in the application that you want to
change. The numbers should indicate the number of messages.
[image: Screenshot_1.jpg]


Otherwise, everything is fine! Thanks!


С уважением,
Алексей Глушков
+79215281111
Viber, WhatsApp, Telegram
skype alexsei.glushkov
alex@glushkovy.ru
https://vk.com/alexseiglushkov
Петрозаводск, ул.Л.Чайкиной, д.5
<https://yandex.ru/maps/18/petrozavodsk/?ll=34.362478%2C61.776542&z=18&mode=search&text=karelia.news&sll=34.362478%2C61.776542&sspn=0.004646%2C0.001903&ol=biz&oid=204161377834>

P.S. Пpосьба во всех слyчаях цитиpовать пpедыдyщyю
пеpепискy.


пт, 31 янв. 2020 г. в 19:21, Vulich Fernando <notifications@github.com>:

**Comment by fvulich** [comment]
It needs a custom-made unreadCode in order to get the notifications the way you want it.

Please check this [LINK](https://github.com/ramboxapp/community-edition/wiki/Add-a-Custom-Service) it's not exactly what you asked but it shows you an unreadcode to start with
