### ISSUE TITLE
New GroupMe tab just shows icon

### ISSUE THREAD

**Issue by Brittonlj** [ramboxapp/community-edition#2568]
Add new GroupMe tab.
All I see is the GroupMe logo in center screen with no options for anything else, including logging in etc.

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.17763

**Comment by fvulich** [comment]
I just checked and it's working as it should. Could you send us some screenshots? 
![image](https://user-images.githubusercontent.com/46904390/73087363-2b036e00-3eb1-11ea-8189-4df54ac0c3b4.png)

**Comment by Brittonlj** [comment]
Thank you for your quick response.  I have resolved the issue.  My PiHole
DNS server was blocking something.  I will look into it and figure it out.
Once I disabled my PiHole temporarily, it started working again.

Thanks!

**Comment by Brittonlj** [comment]
If you are keeping track of resolutions, the issue was this url was being
blocked by the PiHole default configuration:
https://d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js

That caused a JS error that stopped the page from loading.

**Comment by fvulich** [comment]
Thanks for the feedback. Have a nice day!
