### ISSUE TITLE
Problema pra rodar o Rambox no Debian 10

### ISSUE THREAD

**Issue by PauloTxJS** [ramboxapp/community-edition#2569]
### Debian 10 e Rambox

Uso debian 10, minha arquitetura é 64bits, baixei e instalei o pacote "Rambox-0.7.3-linux-amd64.deb", aparece o ícone do programa instalado mas quando clico não roda. Podem me ajudar?

**Comment by fvulich** [comment]
Could you try with snap or AppImage? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by PauloTxJS** [comment]
O Rambox-0.7.3-linux-x86_64.AppImage também não está funcionando.

**Comment by fvulich** [comment]
Zip package steps:

Go to https://github.com/ramboxapp/community-edition/releases and download zip file for Linux.
Unzip downloaded file. Be sure to extract all the files inside a new folder called Rambox for example.
In a Terminal, type: chmod +x Rambox.
Then, we have to install a library (probably missing) to allow tray icon. So type sudo apt-get install libappindicator1.
Last, in the same Terminal type: ./Rambox.

**Comment by PauloTxJS** [comment]
apt-get install libappindicator1
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
libappindicator1 is already the newest version (0.4.92-7).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.

Ainda não deu certo. Fiz do jeito que você falou...
