### ISSUE TITLE
Rambox and Arch Linux

### ISSUE THREAD

**Issue by CG57SUPPO** [ramboxapp/community-edition#2570]
When I right click on the Rambox icon in the system tray all a see are small boxes.  I would like to know which fonts you are using so I can see the menu items.

Thanks for your help,
Dave

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> linux x64 5.4.12-1-MANJARO

**Comment by fvulich** [comment]
What package are you using? Could you try a different one? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by CG57SUPPO** [comment]
Well,  I tried the snap through the arch linux software setup, the snap directly from your website, the AppImage from your website, and then I downloaded the tarball and ran rambox directly from the tarball.  So it worked!!!  The question still remains however: what fonts are used that don't get installed with the snap?

I have fixed this myself by extracting the tarball into /opt and then created the .desktop so I see it in the menu system for my DE (Budgie), but you may want to fix this in the snap so others don't have the same issue.

Thanks for the advice!!  I appreciate it!
Dave

________________________________

**Comment by kikislater** [comment]
Build with AUR works fine ! => https://aur.archlinux.org/packages/rambox-bin
