### ISSUE TITLE
Switching IM by Alt key

### ISSUE THREAD

**Issue by yantene** [ramboxapp/community-edition#2573]
In my environment, when Alt key is typed, the input method is switched.
However, when I type Alt key in Rambox, it focuses on the menu bar.
This behavior interferes with Japanese input.

It's due to electron.
Can I prevent this behavior in settings?

### ENVIRONMENT

> Rambox: v0.7.3

> OS: Arch Linux

> Arch: x64

**Comment by fvulich** [comment]
Sadly, there is no option in settings to prevent this issue.
