### ISSUE TITLE
Freezing with Outlook365

### ISSUE THREAD

**Issue by cryptolukas** [ramboxapp/community-edition#2576]
### Steps to reproduce

1. Integrate Outlook365
2. Make it fullscreen

### Expected behavior

Rambox don't freeze 

### Actual behavior

Rambox freeze with white screen

### ENVIRONMENT

> Rambox: v0.7.3

> OS: Ubuntu 18.04

> Arch: x64

WM: i3

**Comment by fvulich** [comment]
I couldn't reproduce the issue. Are you using snap? Could you try with a different package? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases)

**Comment by cryptolukas** [comment]
I use the amd64 Debian package

**Comment by crollcomp** [comment]
> I use the amd64 Debian package
> 
> `dpkg -l | grep -i rambox ii rambox 0.7.3-176 amd64`

@cryptolukas just out of curiosity, since dpkg doesn't resolve dependencies, have you tried installing the deb with apt instead of dpkg?

`sudo apt install ./path/to/deb/file` (might need to do sudo apt-get install)
