### ISSUE TITLE
Google calendar icon size

### ISSUE THREAD

**Issue by Lefky** [ramboxapp/community-edition#2577]
### Steps to reproduce

1. Open rambox
2. Add a google calendar service

### Expected behavior

Icon to be the same size as others

### Actual behavior

![image](https://user-images.githubusercontent.com/10397178/73637212-0d2fc900-4668-11ea-8dd1-d10677fa40f5.png)

### ENVIRONMENT

Version: 0.7.3
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by fvulich** [comment]
Fixed, reload Rambox to get the changes
