### ISSUE TITLE
Telegram Desktop Version

### ISSUE THREAD

**Issue by Marfo94** [ramboxapp/community-edition#2581]
Hello,

I cannot start Telegram in desktop mode but I have a view very unfriendly, instead a colleague of mine has automatically a popup that ask to start Desktop version of Telegram with Rambox.

In attachment a screenshot of my Telegram (Telegram.png) and the desired view (Desktop-version.jpg).

I've already looked in settings of the app.

![Desktop-Version](https://user-images.githubusercontent.com/60691363/73831352-82d19b80-4806-11ea-9a09-39114a4d60fb.jpg)
![Telegram](https://user-images.githubusercontent.com/60691363/73831356-8402c880-4806-11ea-8a96-da33169515bf.png)

Thank you.

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
It seems to be related to the size of the window where the Telegram app is running, when the size is smaller the app (Telegram) will suggest you to go mobile, and when you expand the window will suggest you to go Desktop view. This behavior is not from Rambox. Please check the app in your browser and you'll have the same results. If you don't, please, attach some screenshot of the view in the browser and inside Rambox CE, please check that the size of those windows (browser and Rambox) to be the same or similar.

**Comment by Marfo94** [comment]
Hello Fernando,

I can confirm that if I resize the Rambox window to smaller size, it asks if I want to switch to mobile version or desktop version if I get back to big size.

Thank you a lot,
Simone
