### ISSUE TITLE
Blank screen when using Workplace after the first time

### ISSUE THREAD

**Issue by phlnx** [ramboxapp/community-edition#2583]
### Steps to reproduce

1. Activate a Workplace tab, make sure it works correctly.
2. Close Rambox
3. Reopen Rambox and click on the Workplace tab

### Expected behavior

The Workplace tab loads and I can navigate in it as if I were on the web site.

### Actual behavior

White screen.

### ENVIRONMENT

Rambox: v0.7.3 portable
OS: Windows 10 x64
Arch: x64

Further notes: In my installation I also have a Slack and a Hangouts Chat tabs. They both work fine.

**Comment by fvulich** [comment]
Could you share some screenshots? Or even better a video? For the video you could use www.loom.com  
Also, are you using a custom-made build? Could you try with ours?

**Comment by phlnx** [comment]
Hello,

I am using the official client to the best of my knowledge, the only thing being it is the portable version.

I distinctly remember navigating in the Workplace tab the day I configured it and it worked. That was the only time it worked, I've been using Rambox for 10-15 days.

I use the Hangouts Chat and Slack tabs every day with no issue.

I guess I could try deactivating the Workplace tab and reconfiguring it, but I decided to leave a note here in case it was a known anomaly with a defined workaround.

I hope this attachment works. I originally decided not to attach anything because I wasn't sure how much you could get from a white screen :-)

![immagine](https://user-images.githubusercontent.com/7044713/74040995-1d77d900-49c5-11ea-959b-714be78bff77.png)

**Comment by fvulich** [comment]
Did you try deleting and re adding the Workspace app?

**Comment by phlnx** [comment]
If you re-read my previous comment, you will see that I considered doing that, but I held myself and asked here first (5th paragraph).

I shall try that, although such a process hasn't been needed for my other two tabs.

**Comment by phlnx** [comment]
So I removed and readded Workspace and this time it looks like it works fine. No idea why it stopped working before and maybe we'll never know. I guess this issue can be closed. Thank you for your help.

**Comment by fvulich** [comment]
Glad to hear that! Have a nice day.
