### ISSUE TITLE
Sometime entire sistem freezes when Rambox is running.

### ISSUE THREAD

**Issue by d0clight** [ramboxapp/community-edition#2585]
-
	> Rambox 0.7.3
	> Electron 7.1.1
	> linux x64 5.4.17-200.fc31.x86_64

**Comment by fvulich** [comment]
Please, could you elaborate a bit further?

**Comment by maikcrew** [comment]
Hi Also, the system freezes when I start Rambox. Through the Terminal I see this:
 (electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
(electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
(electron) 'setZoomLevel function' is deprecated and will be removed. Please use 'zoomLevel property' instead.

U using actual Rambox in LinuxMint 19.3 64 bit with CM.
