### ISSUE TITLE
Facebook messenger not able to start Voice/Video Call on linux mint 

### ISSUE THREAD

**Issue by szparag3** [ramboxapp/community-edition#2586]
There is a problem with messenger. 

I am not able to start video/voice call - looks like that pop up window do not work. (I have checked the same on hangout but that one works ok)

I am using Linux mint 19.3

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> linux x64 5.3.0-28-generic

**Comment by fvulich** [comment]
Which package are you using? Could you try with another? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
