### ISSUE TITLE
scroll bar gone

### ISSUE THREAD

**Issue by lselbach** [ramboxapp/community-edition#2590]
just installed and when adding services, the scroll bar that show all the services is gone.

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
Could you share some screenshots with us?

**Comment by kseitz10** [comment]
I think I'm having the same problem, so I will share what I have:

![image](https://user-images.githubusercontent.com/1263088/75696222-dc47b180-5c70-11ea-9f0f-1dd2c7056764.png)

- The scrollbar is not visible when you mouse near it.
- The mouse wheel does not work.
- You can click-and-drag on the window to get it to scroll (makes sense for touch, but not at all for a mouse) but sometimes it gets stuck and won't scroll beyond a certain point. It acts like you've reached the top of the page and "resists" your drag and snaps back, despite not actually being at the top of the page. Seems to depend on whether something has focus.

![TCCfvTogX5](https://user-images.githubusercontent.com/1263088/75696957-0057c280-5c72-11ea-8777-f34da4f71803.gif)
