### ISSUE TITLE
Random Crashes: libnotify failes to connect to proxy

### ISSUE THREAD

**Issue by JulioSDDR** [ramboxapp/community-edition#2595]
I am using Rambox 0.7.3-2 on Arch Linux since today morning (0.7.2 worked flawlessly). I am having random, very frequent crashes.  The issue occur when using telegram, gmail, or whatsapp (i have tested them separately and all fail the same way).

If i run rambox from the cl, i get this error: 
```  (rambox:46485): libnotify-WARNING **: 19:35:30.547: Failed to connect to proxy ```
Rolling back the upgrade seems to fix the problem

**Comment by fvulich** [comment]
What package are you using? Could you try with other? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases)
