### ISSUE TITLE
Javascript error when dragging main window

### ISSUE THREAD

**Issue by Karreg** [ramboxapp/community-edition#2597]
### Steps to reproduce

1. Start Rambox
2. Drag the main window
3. Enjoy.

### Expected behavior

The window is dragged without error

### Actual behavior

This is the same issue as #1906 and #2364
The following error appears:
```
Uncaught Exception:
Error: EPERM: operation not permitted, rename
'C:\Users\XXX\AppData\Roaming\Rambox\config.json.3667722756' ->
'C:\Users\XXX\AppData\Roaming\Rambox\config.json'
    at Object.renameSync (fs.js:609:3)
    at Function.writeFileSync [as sync]
(C:\....)
    at ElectronStore.set store [as store]
(C:\....)
    at ElectronStore.set
(C:\....)
    at BrowserWindow.<anonymous>
(C:\...electron\main.js:175:76)
    at BrowserWindow.emit (events.js:203:13)
```

It looks weird to me to try to change configuration and rename the file synchronously while the window is dragged... Especially if renaming in synchronous in RamBox but asynchronous at OS level, it could lead to this kind of issue? If I'm not wrong, configuration should be changed when the window is not dragged anymore...

### ENVIRONMENT

Version: 0.7.3
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by nf123git** [comment]
Same issue on 0.7.5

Version: 0.7.5
Platform: win32 (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by fvulich** [comment]
Is this still reproducible?

**Comment by Karreg** [comment]
I have not seen this issue for a while now...

**Comment by fvulich** [comment]
I close this for now then.
