### ISSUE TITLE
ramboxapp is not showing discord notifications

### ISSUE THREAD

**Issue by surak** [ramboxapp/community-edition#2598]
### Steps to reproduce

1. Receive any message on discord - be it private message, or group message
2. It might appear inside of discord on the `server`, but never on the tab above.
 

### Expected behavior

A red marker of unread messages

### Actual behavior

Nothing

### ENVIRONMENT

> Rambox: v0.7.3

> OS: Mac OS 10.15.3

> Arch: x64 or ia32

Similar to #2192, but I don't know how to fix on the Mac binary.

**Comment by fvulich** [comment]
![image](https://user-images.githubusercontent.com/46904390/75584059-ab3b6700-5a4d-11ea-9fb5-51d9850099ca.png)
Could you try the suggestions of this [LINK](https://github.com/ramboxapp/community-edition/pull/2124)?
 You have to paste the code in there, in the settings of the app.

**Comment by michaeldrouin** [comment]
i've had this issue as well pretty much since i started using rambox 6+ months ago. i tried the code in that link a few months back and it's never worked. only difference is i'm on Ubuntu 18.04.4. i get desktop notifications, but i (and i belive what OP here is saying) don't get unread counters.

**Comment by surak** [comment]
Doesn't work.
