### ISSUE TITLE
Clicking calendar or contacts in ProtonMail beta causes logout

### ISSUE THREAD

**Issue by aravindhp** [ramboxapp/community-edition#2607]
### Steps to reproduce

1. Goto beta.protonmail.com by clicking the beta link on protonmail.com within Rambox
2. Login
3. Click on Calendar or Contacts

### Expected behavior
Able to view the Calendar or Contacts

### Actual behavior
You are thrown back to the login screen

### ENVIRONMENT

> Rambox: 0.7.3

> OS: Fedora 31

> Arch: x64

**Comment by fvulich** [comment]
Could you try it in other device?

**Comment by aravindhp** [comment]
I see the same issue on RamBox 0.7.3 on Windows 10.

**Comment by aravindhp** [comment]
This has now been fixed on the ProtonMail end.
