### ISSUE TITLE
Tweetdeck columns shift down?

### ISSUE THREAD

**Issue by alucidwake** [ramboxapp/community-edition#2609]
Sometimes when I click on a tweet, or a link, or anything in Tweetdeck, the columns on all tabs move to the bottom of the screen.
The only way to get them back "up" is to click on a tweet inside that column and then go back

Rambox: v0.7.3
OS: 10.15.2

<img width="1112" alt="Screen Shot 2020-03-08 at 6 43 05 PM" src="https://user-images.githubusercontent.com/7723471/76168107-a7ee5c80-616c-11ea-991a-406c3c563b5a.png">

**Comment by fvulich** [comment]
Does this issue appear when you use it from Chrome?

**Comment by alucidwake** [comment]
Hm. Yes it does!

**Comment by fvulich** [comment]
It seems that it's more like a feature from Tweetdek (I don't know if it's a good one). It's not a Rambox CE related issue. Please, refer to the Tweetdesk support page.

**Comment by sieren** [comment]
Actually it is not. It's a bug that is hard to replicate as it's seemingly random and it still occurs in the current Rambox version (see also https://github.com/ramboxapp/community-edition/issues/2474).

I myself did not see this happen in the most recent version of Chrome.
