### ISSUE TITLE
Add a way to send instagram direct messages by pressing ENTER

### ISSUE THREAD

**Issue by obvionaoe** [ramboxapp/community-edition#2610]
It'd be incredible if you could send Instagram Direct messages by pressing the Enter key instead of having to click the send button with the mouse!

Is there any way to implement this?
Thanks

### ENVIRONMENT

> Rambox: v0.7.3-1

> OS: Manjaro

> Arch: x64

**Comment by fvulich** [comment]
It could be done by adding a JS script.
I made a very simple one that kinda works, but it needs more work. Sorry but I'm short of time but maybe someone could improve it. 
```
document.addEventListener('keydown', function(e) {
	if (e.key === 'Enter') {
		let a = document.querySelectorAll('button[type=button]').length;
		document.querySelectorAll('button[type=button]')[a-1].click();
	}
});
```

**Comment by fvulich** [comment]
@obvionaoe Did the script help you?

**Comment by obvionaoe** [comment]
It did, I completely forgot you could add javascript to the services xD As you said it still needs a little bit of work, I'm going to mess with it a little bit to see if I can remove the new line it prints in the input :)

**Comment by fvulich** [comment]
```
document.addEventListener('keydown', function(e) {
  if (e.key === 'Enter') {
    let a = document.querySelectorAll('button[type=button]').length;
    ["Enviar", "Send", "Senden", "Invia", "Skicka", "Envoyer", "Verzenden", "Отправить"].includes(document.querySelectorAll('button[type=button]')[a-1].innerText) && document.querySelectorAll('button[type=button]')[a-1].click();
  }
});
```
This one works better :-)

**Comment by fvulich** [comment]
I added the script to the service.
