### ISSUE TITLE
WhatsApp no longer works

### ISSUE THREAD

**Issue by Pahvi67** [ramboxapp/community-edition#2611]
WhatsApp no longer works

### Steps to reproduce

1. Open WhatsApp in Rambox CE

### Expected behavior

WhatsApp opening succesfully

### Actual behavior

WhatsApp wont open, shows a message: "WhatsApp works with Google Chrome 49+"

### ENVIRONMENT

> Rambox: v0.7.3

> OS: macOS Catalina 10.15.1

**Comment by fvulich** [comment]
I just tested and it's working as it should. Could you delete the WhatsApp service and add it again?

**Comment by Pahvi67** [comment]
> I just tested and it's working as it should. Could you delete the WhatsApp service and add it again?

Re-adding WhatsApp fixed this issue, thanks.
