### ISSUE TITLE
WhatsApp not working - update Chromium

### ISSUE THREAD

**Issue by JensKnipper** [ramboxapp/community-edition#2612]
### Steps to reproduce

1. Add WhatsApp service
2. Connect WhatsApp with phone

### Expected behavior

WhatsApp web should be shown

### Actual behavior

Message: "WhatsApp works with Google Chrome 49+"

### ENVIRONMENT

> Rambox: v0.7.3

> Platform: win32 (x64)

> Chromium: 78.0.3904.99

**Comment by fvulich** [comment]
I just tested and it's working as it should. Could you delete the WhatsApp service and add it again?

**Comment by JensKnipper** [comment]
Works fine now. Thanks!
