### ISSUE TITLE
Custom Service: Twitter shows wrong avatar

### ISSUE THREAD

**Issue by schousda** [ramboxapp/community-edition#2613]
Hi,
i added multiple Twitter accounts by using the custom service.
If i look at the tweets, for many users the page shows wrong avatars.
Any idea how to fix that?

**Comment by fvulich** [comment]
I don't fully understand your issue, could you elaborate a bit further? Some screenshots may help as well.

**Comment by schousda** [comment]
Sorry, for my bad description.
I hope, the screenshots help to understand the issue:
Wrong avatars showns in Rambox
![grafik](https://user-images.githubusercontent.com/21222928/76520322-f9476600-6462-11ea-9324-3edfb2427c0d.png)
![grafik](https://user-images.githubusercontent.com/21222928/76520335-fe0c1a00-6462-11ea-8b4f-8c0e90520cef.png)

Correct avatars shown in browser:
![grafik](https://user-images.githubusercontent.com/21222928/76520414-25fb7d80-6463-11ea-9224-f0bdbcf70739.png)
![grafik](https://user-images.githubusercontent.com/21222928/76520429-2ac03180-6463-11ea-9a30-3780bbe593c8.png)

**Comment by fvulich** [comment]
That's odd. Does it happen in all the Twitter apps? Could you try deleting the app and adding it again?
