### ISSUE TITLE
Copying (ctrl+c) has often no effect, only right-click -> "copy" works

### ISSUE THREAD

**Issue by punkr0ck** [ramboxapp/community-edition#2614]
Version: 0.7.3
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

after our ["READY READY READY"-problem](https://github.com/ramboxapp/community-edition/issues/2469) some weeks/months ago, i currently face the issue that often CTRL+C doesn't do anything. it doesn't copy the text i marked (no matter in what application). Only right-click -> copy works.

**Comment by fvulich** [comment]
Does it happen in all services? Once it happens, does it stay that way? If you reload the service, does it get fixed?

**Comment by punkr0ck** [comment]
It happens in all services I have, yes (Discord, Tweetdeck, Wire, Telegram).
Once it happens it stays that way.
Reloading Rambox fixed it.

**Comment by fvulich** [comment]
Do you still have this issue in v0.7.5?

**Comment by huang-jy** [comment]
I have 0.7.5 on Ubuntu (Linux) on x86 and can confirm this issue occurs there too.
