### ISSUE TITLE
Icons do not show in Rambox Community on Mac

### ISSUE THREAD

**Issue by realrill** [ramboxapp/community-edition#2616]
See title and picture below.

### Steps to reproduce

1. Install Rambox community edition on Mac

### Expected behavior

Icons in Rambox as usual

### Actual behavior

![image](https://user-images.githubusercontent.com/10846028/76607420-db820b80-650b-11ea-9caa-72373c98df9d.png)

### ENVIRONMENT

Version: 0.7.3
Platform: darwin (x64) | Catalina 10.15.3 (19D76)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by fvulich** [comment]
It seems that your ISP is blocking Firebase storage, we don't know why. Could you try this link and share with us what happen?

[LINK](https://firebasestorage.googleapis.com/v0/b/rambox-d1326.appspot.com/o/services%2F10000ft.png?alt=media&token=468a9287-bcd4-4970-a6dc-83e8c99e7b94)

You should see this
![10000ft](https://user-images.githubusercontent.com/46904390/76615663-3bbf8000-6501-11ea-8794-a67099b492a4.png)


Are you using SolarWinds RMM? It appears that they have classified Firebase as a potential threat. Adding it to the whitelist will restore the icons.

**Comment by realrill** [comment]
I can see that specific 10K image when I open your LINK.

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage and tell us how it goes?

![](https://user-images.githubusercontent.com/46904390/76256643-0d0a8680-622f-11ea-9c04-8a1855a30c34.png)

**Comment by realrill** [comment]
Just logged it at home, restarted Rambox then the icons appeared.
Strange that the icon with direct url did work in office but in app didn’t. Hope the client caches them.

I'd say the problem solved.

Thank you for your kindly help 🙏
