### ISSUE TITLE
Proxy not connecting

### ISSUE THREAD

**Issue by yaser-alazem** [ramboxapp/community-edition#2618]
Thank you for the great app, though since yesterday I was trying to connect the app through a premium proxy credentials but the app is not connecting even when I try to use some of the free proxies list you are suggesting.
  
### Steps to reproduce

1. Open Rambox and add proxy from preferences -> proxy section
2. Close the app and relaunch it again
3. A message appears in top says (Services couldn't be loaded, some Rambox features will not be available.) and none of the services is working.

### Expected behavior

Application connects to the servers and services work properly
 
### Actual behavior

The app is is not functioning and none of he services is working.

### ENVIRONMENT

> Rambox: v0.7.3

> OS: Ubuntu 19.10

> Arch: x64

**Comment by fvulich** [comment]
I could reproduce the issue, it's an electron bug. This will be fixed in our upcoming version.

**Comment by fvulich** [comment]
Please update to 0.7.4, in this version this issue is fixed.
