### ISSUE TITLE
OSX version CPU and memory at overload

### ISSUE THREAD

**Issue by agiveon** [ramboxapp/community-edition#2619]
### Steps to reproduce

1. Turn on Rambox

I do have several (many?) services:
2x Gmail
2x Slack
2x Trello
Whatsapp
Gchat
Skype
Google analytics
Freshdesk
A few custom ones

Is that too many?

### Expected behavior

Run like its on Chrome... 

### Actual behavior

As soon as I turn it on, fan starts running... lots of "Rambox Helper (renderer" ... like many more than services. everything is sluggish... as soon as I turn off Rambox and turn on ALL the services on different Chrome tabs, its all fine.

### ENVIRONMENT

> Rambox: v0.7.3

> OS: 10.15

> Arch: x64

**Comment by fvulich** [comment]
Could you try deactivating all the services and activating one by one? It seems that one of those services is crashing or consuming an abnormal amount of resources.

**Comment by davidemorra** [comment]
happens the same to me, i tried to deactivating all the services and then I have activated one service at time but it's not predictable-replicable (at least my situation). But when happens the processes go up to 98-99%. Next time, I'll go through activity monitor and inspect the calling stack.. did you catch other situations like this? can be a fault of Chromium?

**Rambox**:
Version: 0.7.5
Platform: darwin (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

here what I have:
2x Gmail
1x Calendar
1x Whatsapp
1x Telegram
1x Slack 
1x Skype
