### ISSUE TITLE
Rambox 0.7.x Freezes when message arrives

### ISSUE THREAD

**Issue by percona-csalguero** [ramboxapp/community-edition#2620]
### Steps to reproduce

1. Install rambox from .deb or running appimage on KDE
2. Start from console
3. Upon a new message arrives and Rambox tries to show notifications, you will see in the command output:
```
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
(electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
(electron) 'setZoomLevel function' is deprecated and will be removed. Please use 'zoomLevel property' instead.

(rambox:15958): libnotify-WARNING **: 09:19:22.938: Failed to connect to proxy

(rambox:15958): libnotify-WARNING **: 09:19:47.962: Failed to connect to proxy

(rambox:15958): libnotify-WARNING **: 09:19:58.296: Failed to connect to proxy

```
and it freezes

### Expected behavior

To not to freeze

### Actual behavior

Freezes
### ENVIRONMENT

> Rambox: v0.7.x

> OS: lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
64 bits

**Comment by fvulich** [comment]
Does it happen with all the messages from all the apps, or one in particular? Could you check if it happen with other package?

**Comment by akashsharma02** [comment]
For me this happens when I receive messages on 'Facebook messenger'. But otherwise works well with WhatsApp.
