### ISSUE TITLE
Discord service repeatedly logs out

### ISSUE THREAD

**Issue by michaelelleby** [ramboxapp/community-edition#2629]
### Steps to reproduce

1. Add Discord service.
2. Login.
3. Wait a few days and suddenly Discord requires you to login again.

### Expected behavior

Discord stays logged in.

### Actual behavior

Discord service prompts for login.

### ENVIRONMENT

> Rambox: v0.7.3

> OS: Windows 10 Enterprise N version 1909

> Arch: x64

> Discord account is configured with two factor authentication.

**Comment by fvulich** [comment]
I also experience something like that with Discord. It seems that when you get logged from many browsers (Chrome, Firefox and also Rambox Pro), Discord logs you out once a while. Now I only use Discord from Rambox and always stay logged. Also, to solve this behavior I deleted the Discord app and add it again.
