### ISSUE TITLE
Voxer Audio Not Working

### ISSUE THREAD

**Issue by rrhutch** [ramboxapp/community-edition#263]
I am not able to get the Audio from Voxer to play through my speakers. If I go directly to the web version in my browser, it is fine. However, when trying to play it through Rambox, no audio comes through the speakers.

## 

> Rambox 0.4.1
> Electron 1.3.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Did you check if **Dont Disturb** mode is OFF? Because enabling it it will mute all sounds.

**Comment by Joshuasony** [comment]
Dont Disturb was not ON, but I checked the box "Mute all sounds" on my channels settings.
