### ISSUE TITLE
Whatsapp - camera not found

### ISSUE THREAD

**Issue by sz2000** [ramboxapp/community-edition#2630]
When I try to take a photograph with Whatsapp it tells me that it cannot find the camera.
Just before he asks me for access to the camera and immediately after he reports the error.
The microphone works instead.
With other services, however, it works correctly.
Thanks	

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
I couldn't reproduce this issue, please share some screenshots of the issue or even better a video. By the way I tested it in v0.7.4 you can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by sz2000** [comment]
https://we.tl/t-rv6qnMowRa
I hope it is not too censored

**Comment by fvulich** [comment]
It seems that Rambox doesn't have access to the camera. Please check this link.
https://www.isumsoft.com/windows-10/allow-or-block-windows-app-use-camera.html

**Comment by sz2000** [comment]
I have enabled the policy but it is still not going.
rambox was already among the camera-enabled apps.

[image: image.png]
[image: image.png]


Il giorno mer 25 mar 2020 alle ore 19:09 Vulich Fernando <
notifications@github.com> ha scritto:

**Comment by fvulich** [comment]
I can't see your screenshots. Could you try doing a full uninstall and installing Rambox Pro again? 
This [LINK](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) may help you out.
