### ISSUE TITLE
Version Number ? Feature Request: Easy Environment Variables

### ISSUE THREAD

**Issue by cclambie** [ramboxapp/community-edition#2632]
### Steps to reproduce

1. Create a new issue
2. Look for the version Number, try the context menu, the Rambox screen, the preferences
3. Don't find it? Miss it?

### Expected behaviour

In RamBox screen show the current version number
Ideal Behaviour: right click the "version number" on that screen and it copies the environment variables required for this issue to the clipboard, ready to paste into this form.
![Annotation 2020-03-24 095450](https://user-images.githubusercontent.com/877921/77412509-e19ea480-6db5-11ea-977b-492238b824f1.jpg)

### Actual behaviour

As above, only way I could find it is to refer to the install file.

### ENVIRONMENT

> Rambox: v0.7.3

> OS: Win 10

> Arch: x64

**Comment by fvulich** [comment]
![image](https://user-images.githubusercontent.com/46904390/77427224-c8492880-6db4-11ea-9916-8009c3717354.png)
![image](https://user-images.githubusercontent.com/46904390/77427260-d5feae00-6db4-11ea-8628-56bd47bd309e.png)

**Comment by cclambie** [comment]
Ahah! Couldn't see that... but I pressed ALT on the keyboard in order for menu to appear.
Then  this elusive "help" menu appears :)

Thanks
