### ISSUE TITLE
Account log in for Google switches to main browser

### ISSUE THREAD

**Issue by miriam-neoworks** [ramboxapp/community-edition#2634]
### Steps to reproduce

1. Make sure you're logged out of your Google Account (eg, Gmail) 
2.  Rambox does not show Google sign in page, but instead a web page (for eg https://www.google.com/intl/en_uk/gmail/about/) 
3. Click log in and observe that default browser (not rambox) opens accounts.google.com
4. Proceed through sign in steps
5. Gmail remains open within browser, not Rambox 

### Expected behavior

Account sign in activity (and eventual logged in behaviour) happens within Rambox

### Actual behavior

No ability to log in from Rambox: CTA button opens browser. 

### ENVIRONMENT

> Rambox: 0.7.4

> OS: Mac 10.15.3

> Arch: x64

**Comment by fvulich** [comment]
Please remove the service where you have the issue and add it again, and your problem should be solved. Please, tell us how it goes.

**Comment by miriam-neoworks** [comment]
You're completely correct - I saw an account credentials screen, not a webpage, and logged in fine.
Thank you for pointing out the obvious :)
