### ISSUE TITLE
Service Team. Error share desktop/screen

### ISSUE THREAD

**Issue by Fenix135** [ramboxapp/community-edition#2640]
Cuando se intenta compartir pantalla desde el servicio Team, no funciona y la consola lanza el siguiente error:
[screenSharing][control] screenSharingControlService: unexpected, cannot find the call, teamsCallId [3]

Steps to reproduce it:
1º) Realizar una videollamada
2º) Intentar compartir pantalla

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18362

**Comment by fvulich** [comment]
duplicate #2655
