### ISSUE TITLE
Google voice will not load

### ISSUE THREAD

**Issue by musicmunky** [ramboxapp/community-edition#2641]
### Steps to reproduce

1. Open Rambox - if Google Voice is not enabled, enable it
2. Click the Google Voice tab - the list of calls / messages on the left side "spins" forever and never loads

### Expected behavior

Google voice should load

### Actual behavior

Google voice does not load

### ENVIRONMENT

> Rambox: v0.7.5

> OS: macOs 10.15.3

> Arch: x64

**Comment by fvulich** [comment]
Could you try deleting the Google Voice app and adding it again?

**Comment by zimmwisdom** [comment]
I had the same issue.
I removed the app from Rambox
I re-added it
I logged back in
and that DID fix the issue, thank you.

**Comment by fvulich** [comment]
Glad to hear that. Have a nice day.

**Comment by musicmunky** [comment]
That worked for me as well, sorry just saw your request and tried it out.  Thanks!
