### ISSUE TITLE
Whatsapp never load QRCode.

### ISSUE THREAD

**Issue by BragatteMAS** [ramboxapp/community-edition#2642]
-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.3.0-28-generic

**Comment by fvulich** [comment]
I've checked and it works as it should. Could you try deleting the WhatsApp service and adding it again?

**Comment by BragatteMAS** [comment]
Ok.
After deleting twice, the QRcode appear again.
Thanks.

At,te.

MSc. Bragatte, M.A.S.

Doutorando e representante discente dos pós-graduandos do Instituto de
Biociências.

Núcleo de Imunoinformática do Departamento de Genética
<http://www.ufrgs.br/ppgbm>.

* Ph.D. student and member of postgraduate students' representative council
of Bioscience Institute.

**A nucleus of Immunoinformatics from the department of genetics and
molecular biology <http://www.ufrgs.br/ppgbm>UFRGS

<https://www.researchgate.net/profile/Marcelo_Bragatte>
<http://lattes.cnpq.br/9594590199370154>
<https://www.linkedin.com/in/marcelo-bragatte-a655aa98/>

<https://www.instagram.com/marcelo_bragatte/?hl=pt-br>
<https://twitter.com/MarceloBragatte>
<https://www.facebook.com/marcelo.bragatte>

marcelobragatte@gmail.com

marcelo.bragatte@ufrgs.br

Bragatte_page
<https://www.notion.so/Bragatte-81b51fb0bd5c405199e5249b3aa052f9#967b7143174f4b38aad50495a92111a8>

+ 55 (51) 9 9718 0058
