### ISSUE TITLE
Counter label for Gmail is not displaying correct values

### ISSUE THREAD

**Issue by zorzysty** [ramboxapp/community-edition#2643]
The numbers displayed in the counter label are ridiculously high even when there's only one new message. This happens for each Gmail account - the numbers are very high, but they differ between accounts even if every account has exactly one new message.

This happens on windows and linux since more than 6 months now.

![obraz](https://user-images.githubusercontent.com/5398733/77741496-e5783400-700c-11ea-8798-37e58f8d5c2f.png)

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
The badge shows you the total of unread messages that you have, not only the ones of your Inbox but also the ones in other categories (social, notifications, etc). But if you want only the ones in your Inbox, inject this code in your Gmail app inside Rambox.

`function checkUnread(){if(null!==document.querySelector(".aim .aio").querySelector("div"))updateBadge(parseInt(document.querySelector(".aim .aio").querySelector("div").innerHTML.replace(".","")));else{var e=document.getElementsByClassName("aio")[0];updateBadge(-1!=e.textContent.indexOf("(")&&(t=parseInt(e.textContent.replace(/[^0-9]/g,""))))}}function updateBadge(e){1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3e3);`

**Comment by zorzysty** [comment]
@fvulich So why is it not showing a badge at all when there are 0 unread messages in the inbox, and then suddenly 4.4k when there's only 1? This is inconsistent.
