### ISSUE TITLE
snap version gets 'Permission denied'

### ISSUE THREAD

**Issue by andresespinosapc** [ramboxapp/community-edition#2644]
### Steps to reproduce

1. Install snap version using `sudo snap install rambox`
2. Open Rambox
3. Enable mute using `Shift + Alt + D`

### Expected behavior

Don't get an error

### Actual behavior

It successfully mute but I get a prompt saying: 
"A Javascript error occurred in the main process
Uncaught Exception:
Error: EACCESS: permission denied, open '/home/andres/snap/rambox/12/.config/Rambox/config.json.1974929325'"

Full error here:

![Screenshot_20200327_100710](https://user-images.githubusercontent.com/8888934/77759003-bc5aa200-7012-11ea-947c-7a8bdca69458.png)

### ENVIRONMENT

> Rambox: v0.7.4

> OS: Kubuntu 18.04

> Arch: x64

**Comment by fvulich** [comment]
Duplicated #2494 Please refer to this ticket for more information and workaround/solution.
