### ISSUE TITLE
Disable hardware media keys

### ISSUE THREAD

**Issue by alexcroox** [ramboxapp/community-edition#2645]
Is it possible to disable the hardware media keys being passed to Rambox? When I'm listening to MacOS Music app and I click play on my keyboard it tries to play a random video from one of my rambox tabs instead.

Chrome offers this via chrome://flags/#hardware-media-key-handling

Not sure if that's exposed via electron

**Comment by fvulich** [comment]
`--disable-features=HardwareMediaKeyHandling` add this parameter when you launch Rambox CE in order to disable the media key handling. 
This link could be helpful [LINK](https://superuser.com/questions/837525/adding-parameters-to-start-an-application-in-osx)
