### ISSUE TITLE
No notifications after update.

### ISSUE THREAD

**Issue by RochaNeto** [ramboxapp/community-edition#2647]
I have no notifications in whatsapp, facebook, skype, etc.

Can you help me?

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> darwin x64 19.0.0

**Comment by fvulich** [comment]
Could you restart Rambox CE and try again? Today we fixed the WhatsApp unreadCode.

**Comment by RochaNeto** [comment]
Fixed. Thanks
