### ISSUE TITLE
My webcam is upside down

### ISSUE THREAD

**Issue by laurelkropot67** [ramboxapp/community-edition#2648]
My manufactured webcam from my Assus K50IJ is reconized, but my image is upside down. 
I made a webcam test on Skype and on Discord, the problem remain the same. 

I also try to find a solution with VideoLinux Control Panel or followed some advise from this links : 

- https://community.linuxmint.com/tutorial/view/219
- https://www.linuxpedia.fr/doku.php/expert/retourner_image_webcam 
- https://doc.ubuntu-fr.org/v4l1
- https://askubuntu.com/questions/796082/how-to-fix-inverted-laptop-webcam-video

So, nothing changed at all. Exept with Cheese application, but it's not Rambow, isn't it ?

### Expected behavior

Fixed this problem of upside down webcam's image

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Linux Mint 18.03 'Sylvia' - Mate 32 bits

> Arch: ia32

**Comment by fvulich** [comment]
Sadly, we can't help you, it is not a Rambox issue, seems to be a driver's issue.
