### ISSUE TITLE
Rocketchat doesn't open new window with video call correctly

### ISSUE THREAD

**Issue by Samgarr** [ramboxapp/community-edition#2649]
### Steps to reproduce

1. Configure RC to use Jitsi video chat
2. "Always Open in New Window" enabled
3. Make/join video call

### Expected behavior

Window with new videocall is opened in new window

### Actual behavior

Window is opened in Rambox app and in default browser. Window opened in rambox very often freeze.

### ENVIRONMENT

>Version: 0.7.5
>Platform: linux (x64)
>Electron: 7.1.12
>Chromium: 78.0.3904.130
>Node: 12.8.1
> Arch: x64

**Comment by Samgarr** [comment]
Maybe related with #2433 ?

**Comment by fvulich** [comment]
We are investigating this behavior.

**Comment by fvulich** [comment]
duplicate #2433
