### ISSUE TITLE
Facebook video or call do now work

### ISSUE THREAD

**Issue by maikcrew** [ramboxapp/community-edition#2650]
1. In normal browser like Chrome, Brave, Firefox, Vivaldi ... video or call work excellent
2. New Facebook open new window for video call. Maybe your app block this window.
3. I try remove my old settings make the same.

Rambox: v0.7.5 deb install

OS: LinuxMint 19.3

Arch: x64

**Comment by fvulich** [comment]
We can reproduce this issue. We are investigating it.

**Comment by jrgong420** [comment]
Same issue here on MacOS

**Comment by netdev01** [comment]
I have the same issue with Windows 10.  It worked the first few times, but then it stops working.  Possible with the permission on whatever browser window it tries to open.

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by maikcrew** [comment]
Great thanks very much.
