### ISSUE TITLE
Telegram not working

### ISSUE THREAD

**Issue by pranav-dahiya** [ramboxapp/community-edition#2651]
### Steps to reproduce

1. Create a new Telegram service

### Expected behavior

Load Telegram login page

### Actual behavior

White screen with the following massage:
 The service failed at loading, Error: The connection was reset. Check your internet connection

Internet is working and so are all the other services in rambox

### ENVIRONMENT

> Rambox: v0.7.5

> OS: ArchLinux with kernel 5.4.28-1-lts

> Arch: x64

**Comment by fvulich** [comment]
I couldn't reproduce this issue, could you try in other device? Have you tried deleting the Telegram app and adding it again?

**Comment by pranav-dahiya** [comment]
I figured out the problem. There was an issue with the DNS server of my ISP. Telegram was not working in Firefox either. I connected to my mobile hotspot, and it started working. I'll close this issue
