### ISSUE TITLE
"Paste and Match Style" not working on Mac

### ISSUE THREAD

**Issue by sjmgarnier** [ramboxapp/community-edition#2653]
### Steps to reproduce

1. Copy text from any application.
2. Use the "Paste and Match Style" function in the "Edit" menu of Rambox or the associated shortcut.

### Expected behavior

The copied text should be copied and the style matched to the location it is pasted at. 

### Actual behavior

Nothing gets pasted. 

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Mac OSX 10.15.3 

> Arch: darwin (x64)

**Comment by fvulich** [comment]
Sadly, it seems to be an electron issue.

**Comment by sjmgarnier** [comment]
@fvulich Would that help? https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by sjmgarnier** [comment]
Or this https://github.com/onmyway133/blog/issues/67

**Comment by fvulich** [comment]
No, we do support it and it works well in Windows/Linux. Does common Paste work for you?

**Comment by fvulich** [comment]
It's an electron issue https://github.com/electron/electron/issues/15896 
Sadly, there's nothing we can do, we have to wait until they fix it.
