### ISSUE TITLE
Enhancement: add to DND button tooltip with "Mutes all sounds for the app (notification sounds and also sounds within the application like videos or sound messages". 

### ISSUE THREAD

**Issue by mikescrill** [ramboxapp/community-edition#2654]
Hello,

I cannot get videos to play with sound.  This happens regardless of what platform or what OS I have the software installed.  Would be great if this could be resolved since I receive plenty of videos in my various chat conversations

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18362

**Comment by taboolasean** [comment]
I'm also not getting any sound on videos from Whatsapp

**Comment by fvulich** [comment]
We couldn't reproduce this issue in Windows or Linux. Can you try reinstalling in windows and in Linux could you try other package? you can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by taboolasean** [comment]
@fvulich I'm on a mac if that helps at all?

**Comment by cod3monk** [comment]
Some problem on mac

**Comment by fvulich** [comment]
Please check if you have the "Do not disturb" feature on, if it's ON you'll not hear any sound from Rambox CE
![image](https://user-images.githubusercontent.com/46904390/78381741-2db6c980-75ac-11ea-840a-b2cfcdc37899.png)

**Comment by cod3monk** [comment]
It is off.

**Comment by fvulich** [comment]
Also, check this in the app config
![image](https://user-images.githubusercontent.com/46904390/78389795-c43db780-75b9-11ea-8f7c-7871343c54f7.png)

**Comment by cod3monk** [comment]
I'm embarrassed to say: this fixed it for me. :)

**Comment by fvulich** [comment]
@cod3monk Great!

**Comment by taboolasean** [comment]
Same for me, thanks team!

*Sean Adkins*
Product Specialist, EMEA
sean.a@taboola.com  |  +44(0)207 438 8886  |  taboola.com

**Comment by DennisGaida** [comment]
> Also, check this in the app config

Oh wow, I also didn't know about this. I thought this was about notification sounds, not all sounds (even though the option clearly says so), since the option below is about notifications.

I vote for adding a little hover-help text for this option like "Mutes all sounds for the app (notification sounds and also sounds within the application like videos or sound messages".

**Comment by mikescrill** [comment]
Second that… that was confusing to me as well

**Comment by saenzramiro** [comment]
> I vote for adding a little hover-help text for this option like "Mutes all sounds for the app (notification sounds and also sounds within the application like videos or sound messages".

Ok, we will add that help text in next version.

**Comment by tawhk** [comment]
This thread was so useful. Thanks goddess I look in the issues before a starting a new one. :D

**Comment by xhain** [comment]
Slightly hijacking this issue before I open a new one.
The closed ones from 2018 (#741, #1397, #1751) didn't help me.

OSX 10.15.5
Rambox 0.7.5

I couldn't ever get any sound out of Rambox. No sound on voicemails, videos, etc...

- Don't Disturb: OFF
- Telegram / WhatsApp settings: Mute all sounds OFF (unticked)

Can anyone help on how I can debug this issue?

**Comment by saenzramiro** [comment]
We believe is unnecessary to add more explanation to the DND button, it's clear to us.
