### ISSUE TITLE
Rambox crashes when downloading or uploading attachements

### ISSUE THREAD

**Issue by jscantamburlo** [ramboxapp/community-edition#2657]
Rambox crashes when I try to download or attach a file on any service.

Example:

1) Open Rambox
2) Go to Gmail service
3) Open an email having an attachment
4) Click download button
5) Rambox closes when it tries to save the download.

Thank you.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.3.0-42-generic

**Comment by fvulich** [comment]
I could reproduce this issue. Are you using snap? Could you try with other package? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by jscantamburlo** [comment]
Problem solved using Rambox-0.7.5-linux-amd64.deb. 
As added value, Rambox is not confined to snap any more. Great !!!
Thank you, very much !!!

**Comment by fvulich** [comment]
Great to hear that. Yes, snap it's not always the best option.
