### ISSUE TITLE
How can I backup my settings ?

### ISSUE THREAD

**Issue by rgarrigue** [ramboxapp/community-edition#2658]
Hi there

I've been looking for a doc or whatever, nothing. How can I backup my settings, including configured apps ? Like "copy this .json" or "tar this folder" ? On linux Ubuntu.

Best regards,

**Comment by fvulich** [comment]
This wiki will help you out.
[Backup Rambox CE services](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services)
