### ISSUE TITLE
OAuth window cannot be closed again once opened on MacOS

### ISSUE THREAD

**Issue by mhatvan** [ramboxapp/community-edition#2659]
When opening the OAuth screen, I cannot get rid of it again.
The "Steps to reproduce" below also happen when successfully logging in with OAuth, a screen with "OK" stays open and I need to quit and restart.

Be aware that this only happens on MacOS, on e.g. Ubuntu 19.10 it works fine.

### Steps to reproduce

1. Click on Login through OAuth
2. Try to exit the screen
3. Not closable through escape, no x button
4. OAuth screen stays open

### Expected behavior

Close the OAuth login modal again easily.

### Actual behavior

OAuth modal stays open indefinitely.

### ENVIRONMENT

> Rambox: v0.7.5

> OS: macOS Catalina 10.15.4

> Arch: x64

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
