### ISSUE TITLE
How to reset Rambox without resetting authentication information and settings?

### ISSUE THREAD

**Issue by DennisGaida** [ramboxapp/community-edition#2662]
Right now Rambox is pretty broken for me. I can't click on anything in most of the messengers nor write. I also can't reload the "tabs" by right clicking since I get an empty menu:
![image](https://user-images.githubusercontent.com/2392217/78471354-00475880-7731-11ea-8271-5d6198570280.png)

also some services look like this:
![image](https://user-images.githubusercontent.com/2392217/78500842-27b21b80-7759-11ea-925b-be59bb8a41ec.png)

I actually would love to:

- reinstall Rambox
- keep all settings (authentication information, Rambox settings per service)

Can I do that?

Secondly I sometimes would love to clear some caches for services - again without destroying authentication information. Is it enough to clear the `Cache` folder in `%AppData%\Rambox\Partitions\<servicename>` or should I also clear the `Code Cache`, `GPUCache`? `Session Storage` also sounds pretty temporary to me?

I'm asking since I often get authentication errors with Teams (previously reported) and clearing caches helps (and re-auth afterwards).

### ENVIRONMENT

> Rambox: v0.7.5
> OS: Win10
> Arch: x64

**Comment by fvulich** [comment]
We don't recommend doing this but you can delete 
`Cache`, `Code Cache`, `GPUCache`, `Local Storage` and `Service Worker` and in most of the cases you won't have to get logged again that app. This not recommended and the app could be broken after doing this make it on your own responsibility. 

> keep all settings (authentication information, Rambox settings per service)
It's not something that we support, or we encourage doing, but you could try saving your partitions and when you reinstall and add again the apps that you want (or get them from the auth0 backup) you could assign the old partition to the new app (it will not always work, it's a workaround).

I hope that you'll find this information useful. I will close this ticket
