### ISSUE TITLE
Update specific components used by Rambox

### ISSUE THREAD

**Issue by badsector3** [ramboxapp/community-edition#2664]
### Expected behavior

Possibility to upgrade specific componets such as Chromium.
Right now I use latest  Rambox 0.7.5 with Chromium 78.0.3904.130.
Latest Chromium available on Mac OSX is 84.0.4106 relased on 05/04/2020

### Actual behavior

Not possible to upgrade Chromium or I cannot find such option. I use latest Rambox v.0.7.5

### ENVIRONMENT

> Rambox: v0.7.5

> Chromium 78.0.3904.130

> OS: Mac OSX Catalina 10.15.4 

> Arch: x64

**Comment by fvulich** [comment]
The only way to do that is updating electron, but in order to do that we always have to make some changes in the code and fix incompatibilities. 

Feel free to try yourself.

https://www.electronjs.org/releases/stable
