### ISSUE TITLE
Broken image icons shown if can't connect to firebasestorage.googleapis.com

### ISSUE THREAD

**Issue by simonepri** [ramboxapp/community-edition#2666]
# Problem
When I connect to my university's network I can't see Rambox's apps icons. (image below)
Apparently my university (Cambridge) has blocked "firebasestorage.googleapis.com" because of pishing reasons (I will try to contact them to fix the issue).

**EDIT:**
They removed the DNS block.

### Expected behavior

When the images can't be fetched for whatever reason there should be a fallback to a default icon.

### Actual behavior

No icon is shown.
![image](https://user-images.githubusercontent.com/3505087/78649933-16325600-78b6-11ea-935e-67775a91b7db.png)

### ENVIRONMENT

> Rambox: v0.7.5

> OS: macOS

> Arch: x64

**Comment by fvulich** [comment]
We don't know why they do that, we also have been informed that SolarWinds RMM classified Firebase as a potential threat (you must add it to the whitelist to fix it). Sadly there's nothing we can do about policies like this one.

**Comment by fvulich** [comment]
Glad to hear that they removed that block. Have a nice day!

**Comment by simonepri** [comment]
@fvulich Sorry but the issue was more about adding a default icon other than reporting the issue with firebase, I don't think we should close this issue.

**Comment by fvulich** [comment]
At the moment we are happy the way that we load the icons, it allows us to change them without the need to release a new version. That's why I closed the issue.

**Comment by simonepri** [comment]
@fvulich  What I am suggesting is not to change the way the icons are loaded but rather to add a default icon when the one provided in the src attribute of the img cannot be loaded.

We can either use something like the follow or set a background image trough the css.
```html
<img src="foo.jpg" onerror="if (this.src != 'error.jpg') this.src = 'error.jpg';">
```

Also in the long term, it might be good to add a notification when critical URLs cannot be reached (i.e. showing an info bar like the one that is shown when a new Rambox update is available.
The text in the bar would warn the user that a particular URL (e.g. firebasestorage.googleapis.com) cannot be reached and thus the user might experience malfunctions.

**Comment by simonepri** [comment]
Something like that:
![image](https://user-images.githubusercontent.com/3505087/79887036-f80a4100-83f1-11ea-8048-57ae78c44e09.png)
