### ISSUE TITLE
High data usage in windows 10

### ISSUE THREAD

**Issue by bensonkb** [ramboxapp/community-edition#2667]
### Steps to reproduce

1. Using two whatsapp account cost me around 5.6 gb 
2. Here is the screenshot link. [Link](https://prnt.sc/rul7d5)

### ENVIRONMENT

> Rambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

**Comment by fvulich** [comment]
Could you try doing Clear cache and a Clear Local storage?
![image](https://user-images.githubusercontent.com/46904390/78679214-5565a480-78c0-11ea-84af-5209b33c4a45.png)
 
(take account that all your services will be erased, so please backup them, but if you have only two, you can add them again easily)
Also, you can try uninstalling Rambox CE and installing it again.
You can follow these [STEPS](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall)

**Comment by fvulich** [comment]
I checked your link and that's Internet data ... That's not a Rambox issue and depends on the usage of the apps inside Rambox and what you do in them.
