### ISSUE TITLE
cisco spark(now: webex teams) never loads

### ISSUE THREAD

**Issue by JoeyG1973** [ramboxapp/community-edition#2669]
### Steps to reproduce

1. login to webex teams
2. twiddle thumbs
3. 

### Expected behavior

it works

### Actual behavior

spinning wheel of waiting hell

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Fedora 30

> Arch: x64

**Comment by fvulich** [comment]
We don't have any accounts for webex teams, could anyone share a dummy account with us?
