### ISSUE TITLE
Hangouts doesn't connect 2020

### ISSUE THREAD

**Issue by nashu2k** [ramboxapp/community-edition#2670]
Since yesterday (09.04.2020) Hangouts fails to connect. Can load the list of friends though.

Works seamlessly in browsers (tested with Firefox, Edge Chromium)

![image](https://user-images.githubusercontent.com/6129893/78983023-aaedbb80-7b23-11ea-93f7-ec115342e597.png)

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
I Checked and it's working as it should. Could you try deleting the Hangouts service and adding it again?

**Comment by nashu2k** [comment]
it worked but this doesn't seem to be like a good approach; is there any log that I can check?

**Comment by fvulich** [comment]
Yes, you could check the developer tools for logs.

![image](https://user-images.githubusercontent.com/46904390/79003834-cc51a600-7b29-11ea-9b1b-860f9a07b3aa.png)
