### ISSUE TITLE
Google Voice will not load

### ISSUE THREAD

**Issue by BGMcoder** [ramboxapp/community-edition#2672]
I have two Google Voice accounts and normally load them in separate tabs in Rambox.  However, right now one of them will not complete loading and is unusable.

It seems like the same problem I had in issue #2557 except that now it's the other google account that won't load.

- I tried reloading the service to no avail (nothing changed).
- I tried restarting the program.
- I tried to reinstall Rambox with the latest version, but it didn't help.
- I also opened dev tools and tried disabling the cache and then reloading, but that didn't help either.
- Tried rebooting the computer (Windows 10.1909 x64)

I tried downgrading to version 7.3, but that didn't do the trick, either.  So I took a leap and downgraded to 6.4 and that put me to the google voice sign in screen where I was able to sign in again and the service loaded (although the google page's icons did not all load correctly).

I wish there was an option in the menu bar to let me clear the cache or something.

Here was my other thread:
Changed Google Voice Password #2557

> Rambox: v0.7.5
> OS: Windows 10 x64

**Comment by BGMcoder** [comment]
There doesn't seem to be any way to prevent Rambox from auto-updating itself.  This means I have to reinstall version 6.4 every time I close the program.

**Comment by fvulich** [comment]
Could you try deleting that app and adding it again?

**Comment by BGMcoder** [comment]
Ah, well!  That worked.  Don't know why I didn't think of trying that before.  Before you all fixed this the last time, deleting the app wouldn't have fixed it (I did try then), but now deleting it and re-adding it does work.  Thanks!

**Comment by fvulich** [comment]
Glad to hear that you could sort it out. Have a nice day!
