### ISSUE TITLE
Cmd + D doesn't work on Mac

### ISSUE THREAD

**Issue by radioterror** [ramboxapp/community-edition#2673]
Rambox 0.7.5: shortcut key: Cmd + D, for on/off Don't disturb mode doesn't work on Mac (macOS Catalina 10.15)

It would be nice to have a text checker/corrector

Thanks!!

**Comment by fvulich** [comment]
The shortcut is Cmd + Alt + D, the tooltip is wrong and will be fixed in our next version. Regarding the spellchecker, we do have it in our Pro version among other cool features. You can try it with a two-month free trial. You can download it from [Rambox Website](https://rambox.pro/)
