### ISSUE TITLE
Lock shouldn't ask for a password every time

### ISSUE THREAD

**Issue by clementukn** [ramboxapp/community-edition#2675]
When locking the app should lock right away with a password previously created. When in a hurry to lock the screen user doesn't necessarily have time to set a new password and take the risk of misspelling it.
The previously created password should be encrypted so it can't be retrieved from outside the app.

### Actual behavior

...the app asks for a temporary password before actually locking the screen.

**Comment by fvulich** [comment]
You can set a master password and use it when you lock Rambox
![image](https://user-images.githubusercontent.com/46904390/80001119-64d61780-8494-11ea-83b8-1d819aa4395d.png)
