### ISSUE TITLE
MS Teams won't work using macOS Catalina version 10.15.4

### ISSUE THREAD

**Issue by awamaia** [ramboxapp/community-edition#2676]
**Issue:** MS Teams won't work using macOS Catalina version 10.15.4 (19E287)

**Steps to reproduce:**

1
- open Rambox, preloaded Teams tab is blank
- reloading Teams tab
- status bar shows ready, but the tab is still blank

2
- add MS Teams as a new service, using the adress https://teams.microsoft.com/
- the tab works for a while, but after reloading is blank

	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> darwin x64 19.4.0

**Comment by awamaia** [comment]
It seems that the service is back to normal.

**Comment by awamaia** [comment]
Today the same problem started again.

**Comment by fvulich** [comment]
Please try deleting the Teams app and adding it again.

**Comment by fvulich** [comment]
Also, please add our Teams app instead of a custom one. It has some custom settings in it.
![image](https://user-images.githubusercontent.com/46904390/80223163-4b60d700-861e-11ea-87e1-0d50e6a63690.png)

**Comment by awamaia** [comment]
It didn't work the first time I did this, but now it worked. I tried to add Teams as a custom service just because the main app was not working even after I deleted and added again. I forgot to mention that I use two Teams accounts in Rambox. It seems the the problem is solved now. Thanks!
