### ISSUE TITLE
Impossible to pick up a call in Slack

### ISSUE THREAD

**Issue by damienbusch** [ramboxapp/community-edition#2677]
Impossible to pick up a call in Slack (no button tu pick up, only a message "this message can't be entirely displayed")
==> Had to use the slack application
	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18363

**Comment by PeterWagenaarNW** [comment]
Just so people copy pasting the message from their Rambox will also find this issue: the error actually says "We can't fully display this message."

It seems to have something to do with link previews: as soom as the preview loads the original link changes to this message.

**Comment by fvulich** [comment]
We are investigating this issue.

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
