### ISSUE TITLE
Whatsapp  "update is available" alert is recurring

### ISSUE THREAD

**Issue by teddytwist** [ramboxapp/community-edition#2681]
I've only been using Rambox for a week, but just in the last couple of days Whatsapp is showing the "Update available" alert in green for the last day or two even though I update it each time. I've just updated Whatsapp - quit the application, then opened again and I have the same alert. I am using Linux Mint 19.3 on a Macbook. 

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.3.0-46-generic

**Comment by fvulich** [comment]
WhatsApp web store its app on the browser (in this case Rambox CE) and when they made a change in the app, the update sign appear, normally you only need to click that link and the app will reload with the new version. Sometimes could happen that the sign doesn't disappear (the update somehow failed) and you could try again until the sign is gone or you can delete the WhatsApp app and add it again.
