### ISSUE TITLE
Unable to login to Rambox account with oAuth (3rd-party services) 

### ISSUE THREAD

**Issue by cJayyy** [ramboxapp/community-edition#2689]
### Steps to reproduce

1. Install Rambox CE from [Rambox-0.7.5-linux-amd64.deb](https://github.com/ramboxapp/community-edition/releases/download/0.7.5/Rambox-0.7.5-linux-amd64.deb)
2. Try to log-in using 3rd-party account (tried Google and Facebook) which is already connected to Rambox.
3. Restart Rambox and try to log-in using same account as previously.

### Expected behavior

Rambox will successfully log-in to my Rambox account using 3rd-party oAuth, load my services and configuration and keep running.

### Actual behavior

Rambox successfully logs me in via Facebook/Google account (login pop-up prints `OK` and closes) and after that whole Rambox app restarts itself with no user logged in. 

### ENVIRONMENT

> Rambox: v0.7.5

> OS: elementary OS - 5.1.3 Hera

> Arch: x64

**Comment by cJayyy** [comment]
It seems that simple reboot has fixed the problem. 
I guess it's still bug worth exploring so keeping the issue open.

**Comment by fvulich** [comment]
Thanks for reporting it. We'll take a look.
