### ISSUE TITLE
Problema pra rodar o Rambox no Debian 10

### ISSUE THREAD

**Issue by PauloTxJS** [ramboxapp/community-edition#2690]
Percebi que o "bug" do Rambox no Debian 10 está na versão do kernel: "4.19.0-8-amd64", testei com o kernel: "5.6.7" e deu certo.

_Originally posted by @PauloTxJS in https://github.com/ramboxapp/community-edition/issues/2569#issuecomment-585504018_

**Comment by JOduMonT** [comment]
Hola Paulo;

> En general, en Internet, tendrás más apoyo si escribes en inglés. No te preocupes por tu error, simplemente haz una frase corta que sea más fácil de entender. Sé cómo te sientes al respecto, soy franco-canadiense, pero soluciones como [DeepL](https://www.deepl.com/translator#en/es) ayudan mucho.

para su edición; tratar de ejecutar rambox en una terminal, que decirnos el resultado.

**Comment by fvulich** [comment]
duplicate #2679
