### ISSUE TITLE
Camera Permissions not visible for Google Duo

### ISSUE THREAD

**Issue by shaileshparanjpe** [ramboxapp/community-edition#2691]
For doing a Video Call using Google Duo, user must give Camera Access to Duo App/ Webpage. However, such permission can not be given in Rambox since the option to permit the Camera usage as is visible on normal Google Duo page on web browser is not visible. This makes Video Calling using Duo Impossible on Rambox.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.3.0-51-generic

**Comment by saenzramiro** [comment]
What distro of Linux are you using? Probably you will need to manually give permissions to Rambox.
