### ISSUE TITLE
Rambox CE : Locked up on Enter Master Password screen, None of Password working in app.

### ISSUE THREAD

**Issue by hardikkgoswami** [ramboxapp/community-edition#2692]
Hello, 

I am facing a problem with Rambox since a longtime that I'm stuck on Master Password screen. None of my previous password is working and even when I do uninstall (completely removed) and install latest new version. But Everytime launching on Rambox version only Master Password screen is showing and none of password working. 

From Support I received a solution : 

> You can try, closing Rambox CE and then deleting the config.json file from  ~/Library/Application Support/Rambox or  /Users/username/Library/Application Support/Rambox. Or you can try deleting all the content of that folder in case that you want a fresh start without your previous configurations.

But in my Mac Machine folder couldn't find this Rambox folder itself. 
![image](https://user-images.githubusercontent.com/45848276/80862416-8ef8b800-8c92-11ea-8268-46a0f8f29036.png)

Please review this video of entire issue. 
https://drive.google.com/file/d/1Xz1hd0OvIYfSN47RBen6t8XWYhp9pqGz/view?usp=sharing

### Actual behavior

None of my password does works in app and stuck on this page. 

### ENVIRONMENT

> Rambox: Version 0.7.5 (0.7.5.180)

> OS: MacOS Mojave (10.14.6 (18G4025)

> Arch: x64

**Comment by fvulich** [comment]
Please check this folder  /Users/your_username/Library/Application Support/Rambox

**Comment by hardikkgoswami** [comment]
Thanks I found the folder itself, Deleted all the contents.
Reinstalled latest version and everything works fine now. 

Thanks for your all help :)
