### ISSUE TITLE
Rambox logs me out of everything everytime I close it..

### ISSUE THREAD

**Issue by hosadokha** [ramboxapp/community-edition#2693]
Now Im using a portable version of rambox from portapps.io..
I'm logged into my ICQ and into my Rambox account via Google.. 
And when I close Rambox I get logged out of both..
Is there a way I can make it remember me both Rambox account and ICQ account?

### Expected behavior
It should remember me

### Actual behavior

Forgets all about me

### ENVIRONMENT

Windows 7 x64 using Rambox from portapps.io

> Rambox: v0.7.5

**Comment by fvulich** [comment]
Could you check if the non-portable version does that?

**Comment by hosadokha** [comment]
> Could you check if the non-portable version does that?

Yeah I went to the Rambox website again only to realize that I missed that there actually was an official portable version written in small font below the download button.. So I downloaded it and it works correctly!
