### ISSUE TITLE
AppImage version 1.3.1 could not log in

### ISSUE THREAD

**Issue by edmundlaugasson** [ramboxapp/community-edition#2696]
### Steps to reproduce

1. [download AppImage version 1.3.1](https://github.com/ramboxapp/download/releases)
2. after making it executable with chmod +x tryo to log in with existing Rambox account username, password
3. login will not succeed even username, password were copied.

Tried to use remind password feature but this did not work either - no email with an option to reset password. Checked continuously from spam and inbox - no email arrived.

### Expected behavior
Rambox will log in

### Actual behavior
Rambox says wrong credentials in case of AppImage. Using .deb the login works

### ENVIRONMENT
Rambox: v1.3.1 (AppImage version)
OS: Linux Mint 19.3 MATE
Arch: x64

**Comment by fvulich** [comment]
This support channel is for Rambox CE users. If you are using Rambox Pro, please use our [support channel](https://rambox.freshdesk.com) to report your problems, and we will help you there.
