### ISSUE TITLE
rocket chat auth not working via 3rd party auth service

### ISSUE THREAD

**Issue by edmundlaugasson** [ramboxapp/community-edition#2699]
### Steps to reproduce

1. add Rocket Chat with https://vestlus.eesti.ee/
2. try to login - it opens separate browser - Estonian or EU ID required to login
3. after successful authentication still cannot login

### Expected behavior
Browser redirection works and can login and stay logged in

### Actual behavior
Nothing happens - login does not go through

### ENVIRONMENT
Version: 0.7.5
Platform: linux (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by fvulich** [comment]
We are investigating this issue.

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
