### ISSUE TITLE
Error on renaming roaming rambox config when moving window

### ISSUE THREAD

**Issue by SeidChr** [ramboxapp/community-edition#2704]
I get the following error when MOVING THE WINDOW around on my desktop. Sometimes only when moving between screens with different zoom settings, but often on other moves too.
![image](https://user-images.githubusercontent.com/1927076/81417624-c01e3000-914b-11ea-8532-14c7e1329e60.png)

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18362

**Comment by lpuglia** [comment]
Sorry, i missed this ticket, I have opened a new one with detailed instructions:
https://github.com/ramboxapp/community-edition/issues/2706

**Comment by fvulich** [comment]
related. #2706 I will close this one and leave other because there's more info in it but thanks for reporting it.
