### ISSUE TITLE
cant use telegram in rambox

### ISSUE THREAD

**Issue by mukheshpraveen** [ramboxapp/community-edition#2705]
-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.4.0-29-generic

**Comment by mukheshpraveen** [comment]
cant use telegram in rambox

**Comment by fvulich** [comment]
Could you elaborate a bit further on your issue? Some screenshot will be helpful.

**Comment by mukheshpraveen** [comment]
when i open telegram in rambox, it just gives me a white page with nothing
in it. this happens even i reload it any number of times. resolve this issur

**Comment by fvulich** [comment]
Please share some screenshots of the issue, because we couldn't reproduce it. Also share with us is in the developers tools console of the app shows any error.
![image](https://user-images.githubusercontent.com/46904390/83911636-f8149500-a742-11ea-9d26-8d38cdd5f242.png)

**Comment by ProhoridZza** [comment]
![image](https://user-images.githubusercontent.com/66553307/83966371-88c5af00-a8c2-11ea-8b3e-16bc392ca67d.png)

**Comment by fvulich** [comment]
duplicate #2504
