### ISSUE TITLE
Error when RESIZE or MOVE: A javascript error occurred in the main process (conf and electron too old)

### ISSUE THREAD

**Issue by lpuglia** [ramboxapp/community-edition#2706]
### Steps to reproduce

1. Drag/Resize the open Rambox window to reposition/resize

### Expected behavior

Window is in new position or with new size without an error.

### Actual behavior

I get a javascript error:

![Untitled](https://user-images.githubusercontent.com/2184440/81540287-50858c00-9369-11ea-89e5-5e8345cc144c.png)

### ENVIRONMENT

Version: 0.7.5
Platform: win32 (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

### INFO

This error has been bugging me for the past year, it persisted after every single update. it seems to have been already referenced here:

https://github.com/ramboxapp/community-edition/issues/2713
https://github.com/ramboxapp/community-edition/issues/2704
https://github.com/ramboxapp/community-edition/issues/2644
https://github.com/ramboxapp/community-edition/issues/2597
https://github.com/ramboxapp/community-edition/issues/2544
https://github.com/ramboxapp/community-edition/issues/2553
https://github.com/ramboxapp/community-edition/issues/2364
https://github.com/ramboxapp/community-edition/issues/1906

It looks like the error is generated by:
https://github.com/sindresorhus/conf/blob/v2.0.0/index.js#L164

which is an old version of conf, the bug seems to be related to electron itself in write-file-atomic:
https://github.com/sindresorhus/electron-store/issues/75
https://github.com/npm/write-file-atomic/issues/49

The bug seems to be solved in Electron v7, alternatively there is a workaround in conf v6.0.0:
https://github.com/sindresorhus/conf/pull/82

do you mind any upgrades of the libraries?

**Comment by fvulich** [comment]
This issue will be address in our next release
