### ISSUE TITLE
How to search in page content

### ISSUE THREAD

**Issue by Mutahhar** [ramboxapp/community-edition#2712]
### Steps to reproduce

1. I think the **search in page content** functionality has been added to Rambox but I am unable to make it work.
2. Pressing `Ctrl + F` is not bringing the search dialog like we usually used to do in the browser.

### Expected behavior

Pressing `Ctrl + F` should bring a search dialog that can be used to search in the page content.

### Actual behavior

Pressing `Ctrl + F` doing nothing, so how to search in the page content?

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Windows 10

> Arch: x64

**Comment by fvulich** [comment]
Alt + Shift + F is the shortcut for searching inside the apps.
