### ISSUE TITLE
Error when resize window

### ISSUE THREAD

**Issue by xwoby** [ramboxapp/community-edition#2713]
When i try to resize window of Rambox, maximize to window size, or move the window from one screen to another (windows desktop extended) i have the error attached.

My appologize if this error is reported previusly.

Thanks and best regards!!

![error rambox](https://user-images.githubusercontent.com/65412902/82073494-53ed8000-96a7-11ea-9f07-6f5251a18cf1.png)

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18363

**Comment by lpuglia** [comment]
Hello, the bug is already open here:
https://github.com/ramboxapp/community-edition/issues/2706

**Comment by fvulich** [comment]
Duplicate #2706
