### ISSUE TITLE
Rambox keeps asking for 'System' keychain access on macOS

### ISSUE THREAD

**Issue by iliyang** [ramboxapp/community-edition#2716]
Today Rambox suddenly started asking for access to the System keychain on my macOS. What does it need it for? The prompt is really aggressive and appears constantly. It makes Rambox unusable.

> Rambox: v0.7.5

> OS: macOS 10.15.4

> Arch: x64

**Comment by fvulich** [comment]
Can you share some screenshots with us?

**Comment by iliyang** [comment]
I am sorry for the false alarm, this seems to be an issue with macOS and not Rambox.
