### ISSUE TITLE
keystroke/screen drawing delay when zoomed in on XFCE

### ISSUE THREAD

**Issue by s2hsieh** [ramboxapp/community-edition#2717]
### Steps to reproduce

1. Open chat window
2. Alt+WheelUp to zoom in
3. start typing/editing text in message box

### Expected behavior

Normal typing, text selection, deletion

### Actual behavior

Delays in text showing up, text selection not right, and overall delay in screen redraw.

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Xubuntu 20.04

> Arch: x64

**Comment by fvulich** [comment]
We couldn't reproduce this issue, could you share some screenshots or even better a video?
