### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by madjoe** [ramboxapp/community-edition#2718]
### Steps to reproduce

1. Set your Manjaro to reopen your open apps on reboot
2. Open Rambox + configure your Whatsapp to use it within
3. Restart Manjaro

### Expected behavior

Rambox should open without an error.

### Actual behavior

Sometimes Rambox will throw an error and you can't use the app afterward, unless you close the app and reopen it again:
https://i.imgur.com/QLE4C65.png

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Manjaro KDE Plasma v20.0.1 Lysia

> Arch: x64

**Comment by fvulich** [comment]
What package are you using? Could you try a different one? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) 
or the [AUR](https://aur.archlinux.org/packages/rambox-bin)

**Comment by madjoe** [comment]
I use `rambox-bin` from [AUR](http://aur.archlinux.org/packages/rambox-bin).

**Comment by fvulich** [comment]
Can you tell us a bit more about the issue? What were you doing before the issue appears? Please share with us any information that seems relevant for you

**Comment by madjoe** [comment]
The issue appeared during 2-3 sessions and I couldn't notice any pattern aka. I couldn't guess what exactly would trigger such issue, but it happened when my OS just freshly booted. Unfortunately, I can't purposely reproduce the issue today. I'll keep my eye on this in case it happens again. Until then, could you give me any hint which logs may help you with the debugging, eg. is there any specific command I could run?

**Comment by fvulich** [comment]
Ok. Please keep us updated.

**Comment by madjoe** [comment]
It just happened again, right after a fresh boot. I assume it may be related to `electron` itself, not necessarily to rambox.

https://i.imgur.com/rE8IYw5.png

**Comment by fvulich** [comment]
Is this still reproducible in 0.7.9?

**Comment by madjoe** [comment]
I decided not to use rambox anymore.
Partly to save my RAM usage and partly to minimize distractions when working.
