### ISSUE TITLE
Error popup on startup / preference change

### ISSUE THREAD

**Issue by zThana** [ramboxapp/community-edition#2719]
When starting up the program, it gives me the error in the screenshot twice, then moved on as if nothing happened. Happens when changing anything in preferences as well.

![image](https://user-images.githubusercontent.com/8803519/82898340-67c39c80-9f59-11ea-8601-76de3999876a.png)

### ENVIRONMENT

> Rambox: v0.7.5
> OS: Windows 10 x64

**Comment by fvulich** [comment]
seems related to #2706

**Comment by fvulich** [comment]
Seems to be fixed with https://github.com/ramboxapp/community-edition/commit/155a7fd2a24dd59928a79a69568d5ffd6efd68bd
