### ISSUE TITLE
Discord does not load properly on startup

### ISSUE THREAD

**Issue by huang-jy** [ramboxapp/community-edition#2724]
### Steps to reproduce

1. Load up Rambox with at least 1 Discord tab
2. The Discord service will not load properly and will show the loading screen forever until you reload the tab. Reloading the entire app will not fix this (it'll show the loading screen forever again until you reload the tab)
3. Reload the tab
4. Discord displays successfully

### Expected behavior

To not have to intervene each time Rambox loads

### Actual behavior

As described above

### ENVIRONMENT

> Rambox 0.7.5
> OS: Windows 8.1, Linux (Ubuntu) -- Verified on three different machines.
> Arch: x64

**Comment by olaulau** [comment]
same for me

**Comment by beljim** [comment]
Same for me.. It been like it for a while. Hopefully a fix soon.

**Comment by fvulich** [comment]
I've made some changes in the Discord app, please restart Rambox then delete the Discord app and add it again.

**Comment by huang-jy** [comment]
It seems to work intermittently. Sometimes it will load, and sometimes it will still hang.

**Comment by huang-jy** [comment]
I'm closing this issue, as it now seems to be fixed (I did not have to change anything on my side)
