### ISSUE TITLE
Horde login credentials deleted after closing app

### ISSUE THREAD

**Issue by wynstep** [ramboxapp/community-edition#2725]
Hello everyone, I hope you can help me in sorting this problem.
More than happy to provide further details if this could help in solving the issue.

### Steps to reproduce

1. Add Horde account 
2. Insert Username and password
3. Quit Rambox

### Expected behavior

After quitting the app, I would expect my login/password to be saved and the access to webmail should be automatic

### Actual behavior

Every time I re-open the app, I have to add username and password to be able to access the page again

### ENVIRONMENT
Version: 0.7.5
Platform: darwin (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by fvulich** [comment]
It seems to that you have set a wrong URL. Please, use the URL that shows Chrome after you get logged in Horde to set your Horde app in Rambox

**Comment by wynstep** [comment]
> It seems to that you have set a wrong URL. Please, use the URL that shows Chrome after you get logged in Horde to set your Horde app in Rambox

Ah okay, I'll have a try! What about if I do not have chrome installed on my system?

**Comment by fvulich** [comment]
You can check the URL in other browser.
