### ISSUE TITLE
Cannot open File Photos on Whatsapp

### ISSUE THREAD

**Issue by katsura23** [ramboxapp/community-edition#2727]
when i click the clip button then select photos & videos the rambox app shuddenly close. i already open in my application settings on ubuntu settings and allow it. but still the same result i have. please help me. thank you.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.4.0-32-generic

**Comment by fvulich** [comment]
What Linux distribution are you using? And what package? Could you try with another? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
