### ISSUE TITLE
How can I get rid of Google Hangouts notification?

### ISSUE THREAD

**Issue by s3hMC** [ramboxapp/community-edition#2729]
Hi,
Is there a way to get rid of [this](https://monosnap.com/direct/FxjqtugfttMIZV6Ak5Xq4TDcTabybz) message in Hangouts? 
Thanks!

**Comment by fvulich** [comment]
You could use some CSS code. Add the following code in the "advanced functions" box at the Hangout settings to hide that alert:

The name of the class could change but at this moment, this is working

```
(()=>{ let css=`
.g-B8pEb-Pa {
    display: none;
}
`;

var ss = document.createElement("style");
ss.type = "text/css"; ss.innerHTML = css;
document.getElementsByTagName("head")[0].appendChild(ss); })();
```
