### ISSUE TITLE
Custom Riot has different features showing in browser and rambox

### ISSUE THREAD

**Issue by arthurlogilab** [ramboxapp/community-edition#2731]
### Steps to reproduce

1. open custom riot 1.6.2 in browser, we get a lock icon on some rooms, and presence indicators
2. open custom riot 1.6.2 in rambox, no lock icons no presence indicator

With the upgrade of riot-web to 1.6.2 when loading it in the browser it asks permission to use "Local Storage", maybe that needs to be "activated" for Riot in rambox ? https://github.com/ramboxapp/community-edition/search?q=local+storage&type=Code shows this seems to be configured for some packages... 

### Expected behavior

Same interface as in chrome or firefox

### Actual behavior

Less features in rambox

### ENVIRONMENT

Version: 0.7.5
Platform: linux (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by Mte90** [comment]
Also on Riot the notification badge is not working

**Comment by johanricher** [comment]
> Also on Riot the notification badge is not working

Yes! I was going to open a specific issue about that. Should we do that?

**Comment by Mte90** [comment]
I don't know because this ticket is very generic

**Comment by arthurlogilab** [comment]
I'm not sure what happened (cache or upgrade) but I now have the same riot in the browser and in rambox. But I agree with @Mte90 the notification badge working would be awesome. Should we open a separate issue for that ?

**Comment by fvulich** [comment]
Sadly I don't have at this moment a Riot account to check or update the unreadCode, but I leave you here to old one if someone wants to update it. 

```
function checkUnread() {
    var a = document.getElementsByClassName("mx_RoomTile_nameContainer"),
        b = 0;
    for (i = 0; i < a.length; i++) {
        var c = a[i].getElementsByClassName("mx_RoomTile_badge");
        for (ii = 0; ii < c.length; ii++) parseInt(c[ii].textContent.trim()) % 1 === 0 && (b += parseInt(c[ii].textContent.trim()));
    }
    updateBadge(b);
}
function updateBadge(a) {
    a >= 1 ? (document.title = "(" + a + ") " + originalTitle) : (document.title = originalTitle);
}
var originalTitle = document.title;
setInterval(checkUnread, 1e3);


```

**Comment by fvulich** [comment]
Riot.io is now Element
