### ISSUE TITLE
WhatsApp badges no longer work

### ISSUE THREAD

**Issue by eugeneromero** [ramboxapp/community-edition#2734]
### Steps to reproduce

1. Text a friend on WhatsApp and ask them something :)
2. Receive their reply

### Expected behavior
First the notification should appear on the desktop, followed by a red badge on the service icon and a change to red on the taskbar icon

### Actual behavior
Notification appears correctly, but red badge never appears and taskbar icon does not change color. 

Service worked correctly up until some point earlier this week. I also upgraded from v1.3.1 to v1.3.2 around that time, so I though it could be related to that. However, a downgrade showed the same behavior, and even after clearing the .config/RamboxPro folder and trying a "fresh" session, nothing changed. Behavior observed on two separate machines, both running the same environment.

### ENVIRONMENT
> Rambox Pro: v1.3.1 and v1.3.2 (tested both), installed through deb package

> OS: Ubuntu 20.04

> Arch: x64

**Comment by LurchiStromberg** [comment]
I confirm!
Same Issues here

**Comment by abedjaber** [comment]
i updated rambox it seems working perfectly.. However, Microsoft Teams is unable to log in.. keeps on saying "We couldn't sign you in. Please try again.".

**Comment by eugeneromero** [comment]
@abedjaber I would suggest you create a separate issue, since here you will not be able to get any support...

**Comment by eugeneromero** [comment]
After a WhatsApp update today, (the usual "Update available" message on the WA window, top left corner), badges and tray icon color change seem to be working again. I will monitor for a few more days (and test at the office computer when I go there) and if it seems fixed I will close this issue :)

**Comment by eugeneromero** [comment]
After testing for a couple of days and in two separate devices, I can confirm WhatsApp badges work well again. This must have been related to one of the WA web updates on their side. I will close this ticket now :)
