### ISSUE TITLE
Unable to backup my configuration

### ISSUE THREAD

**Issue by yimir0** [ramboxapp/community-edition#2737]
I cannot backup anymore my configuration, I always get the error message:
**Error occurred when trying to backup your configuration.**
The window says my last backup was:
**Thu, 22 aug 2019, 18:31:38 GMT**

I created and delete a lot of services, but I am no longer able to backup. If I restor the last backup the program messes up my actual configuration.

	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
We are investigating this issue, seems that performing a logout and then login again could be a workaround for this issue (be aware that you may lose your services by doing this)

Duplicate #1932
