### ISSUE TITLE
`Clear Cache` menu option doesn't work

### ISSUE THREAD

**Issue by madjoe** [ramboxapp/community-edition#2739]
### Steps to reproduce

1. Help > Tools > Clear Cache
2. Doesn't delete anything from the cache

### Expected behavior

It should remove the cache content.

### Actual behavior

The cache content is still there.

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Manjaro KDE

> Arch: x64

**Comment by fvulich** [comment]
It does clear the app cache, it's not meant to clear the services cache. What cache do you want to delete?

**Comment by madjoe** [comment]
> It does clear the app cache, it's not meant to clear the services cache. What cache do you want to delete?

There are heaps of data in `~/.config/Rambox/Partitions/*/Cache` directory. I was hoping `Help > Tools > Clear Cache` would delete those, but it's not. What's the workaround?

**Comment by fvulich** [comment]
There's no integrated tool that makes that. If you really need it, please make a new ticket as a feature request and describe the feature that you need.

**Comment by madjoe** [comment]
Ok, could I just delete the content in those directories without breaking anything? The size of those directories are really big.

**Comment by funnyflowerpot** [comment]
Thank you @fvulich for the explanation. I also find oversized `Cache` directories and was confused why the _Clear Cache_ action caused no change. Maybe there could be a clarifying note, saying that only the application cache is cleared, not the cache for the services?

@madjoe Some services offer to have a _Clear Cache_ option, I think, but this is not generally true. I assume deleting the `Cache` for a partition would also log you out from the service.

**Comment by fvulich** [comment]
I'm not 100% sure that the Cache folder inside the partition's app are harmless to delete, but I've been testing deleting it from Slack, WhatsApp, and other apps and the app retains the login information and seems to be working just fine. If you delete the whole partition of one app, it will lose all the credentials and all the information related to it, but not the configuration of it in Rambox, that means a fresh start for the app, like adding it again.
