### ISSUE TITLE
Skype Unable to download Image

### ISSUE THREAD

**Issue by tzwei94** [ramboxapp/community-edition#2741]
### Steps to reproduce

1. Use Skype
2. Open a Image
3. Right click on image
3. Click open in new tab

### Expected behavior

Because cannot transfer session to browser, so open link in internally, then inside the internal browser, please having a download image as button.
OR 
Make it as Rambox normal edition that become download when open in new tab

### Actual behavior

Do not have download image button

### ENVIRONMENT

> Rambox Pro: v1.3.2

> OS: WIndows 10 Home

> Arch: x64

**Comment by fvulich** [comment]
This support channel is for Rambox CE users. If you are using Rambox Pro, please use our [support channel](https://rambox.freshdesk.com) to report your problems, and we will help you there.
