### ISSUE TITLE
Microsoft Teams WebFrame?

### ISSUE THREAD

**Issue by baylesa-dev** [ramboxapp/community-edition#2744]
### Steps to reproduce

1.  Login on teams with Office365 account

### Expected behavior

Should login and display Teams UI

### Actual behavior

![image](https://user-images.githubusercontent.com/37045374/85389580-e6572e00-b547-11ea-8ef9-1e7cf0307a99.png)

![image](https://user-images.githubusercontent.com/37045374/85389614-f40cb380-b547-11ea-90cd-a0e151ec4e9f.png)

### ENVIRONMENT

Windows 10-1909

> Rambox:

Version: 0.7.5
Platform: win32 (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

> Arch: x64

**Comment by fvulich** [comment]
Could you elaborate a bit further on your issue? Share some screenshots of the process in Chrome or your default browser?
