### ISSUE TITLE
Font problems when opening file dialog

### ISSUE THREAD

**Issue by mgzenitech** [ramboxapp/community-edition#2747]
### Steps to reproduce

1. Open any app that requires file dialog

### Expected behavior

Be able to see normal text

### Actual behavior

Everything in "squares"
![Screenshot from 2020-06-29 17-24-56](https://user-images.githubusercontent.com/64852480/86018101-8b34a800-ba2d-11ea-9fa0-4ec23fd06f53.png)

### ENVIRONMENT

> Rambox: v1.3.2

> OS: Linux marius-20l9002gmh 5.4.43-1-MANJARO #1 SMP PREEMPT Wed May 27 20:25:12 UTC 2020 x86_64 GNU/Linux

> Arch: x64

**Comment by mgzenitech** [comment]
BTW: This was installed with snap

**Comment by fvulich** [comment]
Could you try a different package? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or the [AUR]( https://aur.archlinux.org/packages/rambox-bin)

**Comment by mgzenitech** [comment]
This one works:
http://aur.archlinux.org/packages/rambox-pro-bin

So problem with the snap?

**Comment by fvulich** [comment]
Sometimes Snap is not the best choice for all Linux distributions. That's all.
