### ISSUE TITLE
Add test webrtc

### ISSUE THREAD

**Issue by Pablohn26** [ramboxapp/community-edition#275]
There is a website named [https://test.webrtc.org/](https://test.webrtc.org/) that tests if your microphone and webcam are supported and configured properly. Also it does test of network, connectivity and throughput. 

Would be nice to have it as service or as test button to know if everything is working.

**Comment by saenzramiro** [comment]
Sweet! Nice idea!

**Comment by pmgouveia** [comment]
Please, make webrtc optional, so that a user can block it... it can leak your local ip addr, and rambox is not even asking permission to use the cam or the mic.

https://www.perfect-privacy.com/webrtc-leaktest/
