### ISSUE TITLE
Rambox not loading services on startup Fedora 32

### ISSUE THREAD

**Issue by VigilantLoki119** [ramboxapp/community-edition#2750]
![image](https://user-images.githubusercontent.com/23733744/86566386-2f1ad800-bf87-11ea-9cc6-2861656e9af2.png)

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux ia32 5.7.7-200.fc32.x86_64

**Comment by fvulich** [comment]
Are you behind a proxy or a VPN? It seems that Rambox couldn't get the services. Check if you have access to this URL https://raw.githubusercontent.com/saenzramiro/rambox/gh-pages/api/services.json

**Comment by Ronarwithsonar** [comment]
Getting this issue when connected to a vpn. I can access the page linked by @fvulich while on the vpn though
