### ISSUE TITLE
BUG: Scrolling Through the Addons

### ISSUE THREAD

**Issue by kaylamillerdev** [ramboxapp/community-edition#2753]
I can't scroll through the list of addons with my mouse and i can't use the arrow keys either. The search works fine, but that requires me to know what add ons are available and not all the ones i want come to mind.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
Could you elaborate a bit further? Some screenshots or even better a video will help a lot.
