### ISSUE TITLE
Spotify in Rambox didn't work

### ISSUE THREAD

**Issue by jnpf** [ramboxapp/community-edition#2759]
open.spotify.com works until you will login, then it seems to block out rambox because of DRM :/

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> darwin x64 19.5.0

**Comment by fvulich** [comment]
In order to make this work in Rambox it needs a [Widevine](https://en.wikipedia.org/wiki/Widevine) integration. In Rambox Pro we have that feature.
