### ISSUE TITLE
Custom service, login popup stays blank

### ISSUE THREAD

**Issue by keccoz** [ramboxapp/community-edition#2762]
Hi am trying to login to my ManyChat account through the Rambox free app.
I create a custom service, and when I click on sign-in to facebook button it opens a popup but it stays blank, so I can't keep connecting my ManyChat account. Any workaround?

Thanks

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
