### ISSUE TITLE
Always update WHATSAPP in RAMBOX

### ISSUE THREAD

**Issue by josemanuelases** [ramboxapp/community-edition#2764]
-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 4.15.0-111-generic

**Comment by fvulich** [comment]
WhatsApp web stores its app on the browser (in this case Rambox CE) and when they made a change in the app, the update sign appear, normally you only need to click that link and the app will reload with the new version. Sometimes it could happen that the sign doesn't disappear (the update somehow failed) and you could try again until the sign is gone or you can delete the WhatsApp app and add it again. Duplicate https://github.com/ramboxapp/community-edition/issues/2217
