### ISSUE TITLE
Problem dowloading pictures from WHATSAPP in RAMBOX

### ISSUE THREAD

**Issue by josemanuelases** [ramboxapp/community-edition#2765]
-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 4.15.0-111-generic

**Comment by fvulich** [comment]
Could you try another package? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or the [AUR](https://aur.archlinux.org/packages/rambox-bin/)

**Comment by Yahatix** [comment]
Had the same problem with Rambox CE from the Ubuntu Snap Store. The version i downloaded from github (Rambox-0.7.5-linux-amd64.deb) worked for me. Now i can finally download stuff from Rambox without it crashing on me :-)

**Comment by fvulich** [comment]
Glad to hear that you could sort it out. Sometimes the SNAP package is not the best option for all distributions, that's why we offer different options.
