### ISSUE TITLE
Paste and Match Style (⇧⌘V) - Not working

### ISSUE THREAD

**Issue by simonsk1990** [ramboxapp/community-edition#2767]
### Steps to reproduce

Copy Content on clipboard (text)
Paste and Match Style (⇧⌘V)
Nothing happens

### Expected behavior
Paste and Match Style should work

### Actual behavior

nothing happens

MacOSX

Version: 0.7.5
Platform: darwin (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by fvulich** [comment]
Duplicate https://github.com/ramboxapp/community-edition/issues/2653
