### ISSUE TITLE
Fps low, lag

### ISSUE THREAD

**Issue by tsukasagenesis** [ramboxapp/community-edition#2768]
### Steps to reproduce

1. move the window on 144hz screen

### Expected behavior

it working without lag on firefox/chrome but only on rambox (even if it's chrome under ?)

### Actual behavior

https://tsukasagenesis.tinytake.com/tt/NDQ3MDE4NV8xNDE1MjE3MQ

it just lag

### ENVIRONMENT

Version: 0.7.5
Platform: win32 (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by fvulich** [comment]
Seems to be related with Electron (we don't have Chromium under the hood, but we have Electron that has Chromium under the hood), we couldn't do anything but to wait for an improvement on their side.
