### ISSUE TITLE
Skype disconnect call when download file

### ISSUE THREAD

**Issue by tzwei94** [ramboxapp/community-edition#2771]
### Steps to reproduce

1.  In a Skype call
2. Download any file
3. Will disconnect the call

### Expected behavior

When in call will not disconnected by downloading any files

### Actual behavior

Disconnected Skype call when downloading any files

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Windows 10 Home

> Arch: x64

**Comment by fvulich** [comment]
Could you elaborate a bit further? Does it happen when you download a file in the same Skype app? Or in Rambox CE? Or even in the Browser? Some screenshots or even better a video will help us a lot. For the video we recommend www.loom.com

**Comment by tzwei94** [comment]
I found out is because Skype Web will causing call end when trying to download anything.

**Comment by fvulich** [comment]
Thanks for the video! It seems indeed a Skype Web issue, please, refer to their support page.
