### ISSUE TITLE
Unable to login to reddit chat

### ISSUE THREAD

**Issue by sujay1844** [ramboxapp/community-edition#2773]
Even If I type the right credentials, it says incorrect password.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.4.0-7634-generic

**Comment by davecangit** [comment]
I have this issue too

**Comment by sujay1844** [comment]
Oops. I used wrong credentials. It works just fine

**Comment by davecangit** [comment]
im using the right credentials. im copypasting from a password manager and i can log in on a web browser to reddit just fine with the same copy

**Comment by sujay1844** [comment]
then you should try creating a custom service of reddit (not reddit chat)

**Comment by davecangit** [comment]
Interestingly, this happens, and the login window will load but won't accept my credentials.

I believe my reddit password is the maximum length, and I have 2FA - but I'm not sure that's the issue considering I had this problem too

![Screen Shot 2020-10-03 at 10 06 14 pm](https://user-images.githubusercontent.com/53610219/94991198-cf9f8900-05c4-11eb-8224-d6b38db5d1ce.png)
