### ISSUE TITLE
Cant Uninstall Rambox.

### ISSUE THREAD

**Issue by Naeem14733** [ramboxapp/community-edition#2774]
I cant Uninstall rambox. Its not even visible on my control panel.Help me asap.
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.17763

**Comment by fvulich** [comment]
That's really odd, could you try installing it again and see if appears in the control panel? Also, you can try going to this folder `%USERPROFILE%\AppData\Local\Programs\Rambox` and execute `Uninstall Rambox.exe`
