### ISSUE TITLE
Feature request: add WhatsApp Business or let customize the logo

### ISSUE THREAD

**Issue by vaites** [ramboxapp/community-edition#2779]
WhatsApp Web supports the normal app and the business version, but if you want to add two separated instances, the icon is the same. If you hide the labels from the service bar, the two services looks the same.

Another option is let users customize the logo of the service...

Thanks for your effort!

**Comment by fvulich** [comment]
Please could you test if this works?
Add a custom app with this settings
URL = https://web.whatsapp.com
Custom  code = `function checkUnread(){const e=document.querySelectorAll("#pane-side ._31gEB, .unread");let t=0;for(let n=0;n<e.length;n++)0===e[n].parentNode.parentNode.querySelectorAll('#pane-side *[data-icon="muted"]').length&&t++;updateBadge(t)}function updateBadge(e){e&&e>=1?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3e3),(async()=>{try{const e=await window.navigator.serviceWorker.getRegistrations();for(const t of e)t.unregister()}catch(e){}})();var titleEl=document.querySelector(".landing-title.version-title");titleEl&&titleEl.innerHTML.includes("Google Chrome 49+")&&window.location.reload(),document.body.scrollTop=0;`
Logo = an URL to your desired logo
![image](https://user-images.githubusercontent.com/46904390/90263150-a1ec5e00-de25-11ea-8823-887818c45405.png)


Please share with us if all the badges works on the business version, and we'll add WhatsApp Business with a custom logo.

**Comment by vaites** [comment]
Thanks, seems to work ok. I receive notifications and the icon shows the badge with the unread messages.
