### ISSUE TITLE
Unable to login via Google in apps

### ISSUE THREAD

**Issue by nemo-1999** [ramboxapp/community-edition#2780]
### Steps to reproduce

1. Add a new service
2. Choose any google service

### Expected behavior

Logins and connects to the respective google app successfully

### Actual behavior

Couldn't sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Ubuntu 20.04
Excerpt from About Rambox window:
Version: 0.7.5
Platform: linux (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by ogrimator** [comment]
I have the same issue.
> Ubuntu 20.04.1 LTS

	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.4.0-42-generic

**Comment by bro3234** [comment]
Experiencing the same. 

OS: macOS 10.15.6

Version: 0.7.5
Platform: darwin (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by ogrimator** [comment]
I just want to add a small observation, I have encounter the exact same error in a Firefox today while trying to log in to gmail in a private mode. Restarting private mode window resolved this issue.

**Comment by Laura1590** [comment]
I have the same issue, but other similar apps are experiencing the same issue (Franz)

**Comment by saenzramiro** [comment]
We are working on this.

**Comment by arjvik** [comment]
I'm facing the same issue too.

I did try doing a few things, all unsuccessfully:

- Changing the user agent string to multiple different values (i.e. Chrome on I
Windows, Chrome on Linux, etc)
- Removing all the electron-specific variables in JavaScript (from the devtools console). I did enough to fool [is-electron](https://github.com/cheton/is-electron).

Neither worked.

One more thing to note is that the sign-in error happens in both the Auth0 login page (for syncing with a rambox account) and when trying to log in to a Google account in any service page.

Hopefully this info is of use.

**Comment by 8227846265** [comment]
Same issue as well.

![image](https://user-images.githubusercontent.com/66582769/90586752-8b217f00-e20a-11ea-9030-73f70c2c48d9.png)

**Comment by joshxtra** [comment]
![grafik](https://user-images.githubusercontent.com/68787707/90764827-415b9600-e2e9-11ea-82bf-0d16aca358bf.png)

Tried to login today and: same.

**Comment by smooth-dev1l** [comment]
same issue here
Using Arch Linux, installed Rambox 0.75 via AUR, other services like skype, fb messenger or whatsapp working fine, except gmail.

may it has to do with security settings withing gmail. I remember I got similar problems to login like via Geary e.g.

**Comment by dantux** [comment]
Same using MacOS 10.13.6

**Comment by robross0606** [comment]
Same here on MacOS 10.15.16

**Comment by kaiju23** [comment]
Patience guys, let the dev handle this. I guess in the interim have to revert to web browser

**Comment by TalZiv** [comment]
Thanks for working on this issue 👍

**Comment by bendh** [comment]
Just installed Rambox CE 0.7.5 on ubuntu 20.04 and ran to simmilar issue when logging into gmail with MFA enabled. Got it working with using following steps:
- open development tools from tab context menu
- Selected more tools -> network conditions
- Unchecked "User agent automatic selection"
- Selected "Chrome --- Chrome OS"
- Keeping dev console open, used context menu to navigate back to email form
- Using context menu reloaded page
After following those steps i was able to enter pwd and MFA chalenge.

I exited the application and restarted and Gmail was still working. Hopes this workaround is helpfull

**Comment by pdxsam** [comment]
The above work around worked well.

**Comment by gogatv** [comment]
what about on windows? how to fix it?

**Comment by Jykinturah** [comment]
If you follow the instructions outlined by bendh, it may work.

You can access Developer Tools in Windows by pressing Ctrl + Shift + i

After following the steps to change the useragent, a refresh can be triggered by pressing Ctrl + r

**Comment by gogatv** [comment]
did not work😢
![shot-1](https://user-images.githubusercontent.com/70150317/91479573-a118ea80-e86f-11ea-8d6b-c079455ec234.jpg)

**Comment by gogatv** [comment]
i got it. i selected "microsoft edge" and works 👌

**Comment by xdhmoore** [comment]
> 
> 
> i got it. i selected "microsoft edge" and works 👌

That seemed to work for me, though I would guess it's just a matter of time till Google wises up to it. Idk this is a tricky problem.

**Comment by SergeiKaptelin** [comment]
> Just installed Rambox CE 0.7.5 on ubuntu 20.04 and ran to simmilar issue when logging into gmail with MFA enabled. Got it working with using following steps:
> 
> * open development tools from tab context menu
> * Selected more tools -> network conditions
> * Unchecked "User agent automatic selection"
> * Selected "Chrome --- Chrome OS"
> * Keeping dev console open, used context menu to navigate back to email form
> * Using context menu reloaded page
>   After following those steps i was able to enter pwd and MFA chalenge.
> 
> I exited the application and restarted and Gmail was still working. Hopes this workaround is helpfull

Working for me. Except step with reload page. In my case after change user-agent I removed google service (try on google calendar and gmail) from rambox enabled services at home page and add them again with changed user-agent.

**Comment by saenzramiro** [comment]
Soon we will release v0.7.6 with this fix.

**Comment by DizZii** [comment]
> Just installed Rambox CE 0.7.5 on ubuntu 20.04 and ran to simmilar issue when logging into gmail with MFA enabled. Got it working with using following steps:
> 
> * open development tools from tab context menu
> * Selected more tools -> network conditions
> * Unchecked "User agent automatic selection"
> * Selected "Chrome --- Chrome OS"
> * Keeping dev console open, used context menu to navigate back to email form
> * Using context menu reloaded page
>   After following those steps i was able to enter pwd and MFA chalenge.
> 
> I exited the application and restarted and Gmail was still working. Hopes this workaround is helpfull

This worked for me. Using Rambox 0.7.5 on Mac OS. The "Chrome --- Chrome OS" user agent didn't work but the MS Edge- Chromium agent did work. So, just keep trying different user agents. Didn't even need to relaunch Rambox... reloaded the tab was all I had to do.

Interestingly (?)... I had a second gmail account opened simultaneously in another Rambox tab that has been working fine.
