### ISSUE TITLE
Slack notifications not working

### ISSUE THREAD

**Issue by robross0606** [ramboxapp/community-edition#2782]
I missed several replies from people in critical threads because I was never notified from Rambox about any activity.  Using the regular Slack app or website, I am seeing notifications.  But never from Rambox.

**Comment by mhatvan** [comment]
Hey @robross0606 I am experiencing the same issue, how were you able to solve it?

**Comment by robross0606** [comment]
I really didn’t. I had to turn on ALL messages in the channel.  Not just messages to me. It sucks.
