### ISSUE TITLE
I can't log in to Gmail

### ISSUE THREAD

**Issue by sujay1844** [ramboxapp/community-edition#2793]
![Screenshot 2020-08-24 09:10:18](https://user-images.githubusercontent.com/68642484/91001599-c3013b80-e5e9-11ea-9b3c-2e3a7fb3b0b1.png)

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.8.1-3-MANJARO

**Comment by daishi-kayano** [comment]
me too.
> Rambox 0.7.5
> macOS big sur beta5

**Comment by daishi-kayano** [comment]
duplicate
https://github.com/ramboxapp/community-edition/issues/2794

**Comment by sujay1844** [comment]
I tried again today (after 24 hours) and works just fine.
