### ISSUE TITLE
Can not login using google account

### ISSUE THREAD

**Issue by Jozmen** [ramboxapp/community-edition#2794]
### Steps to reproduce

1. Click login
2. Select Google Account
3. Enter email
4. Click next

### Expected behavior

User is asked for password

### Actual behavior

Following message is displayed:

This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

### ENVIRONMENT

> Rambox: v0.7.5

> OS: CentOS 8
> Arch: x64

**Comment by Jozmen** [comment]
I found out that there is already issue in progress for the same problem. Duplicate #2780

**Comment by Jozmen** [comment]
Reopening as 0.7.6 did not fix this problem.

**Comment by fvulich** [comment]
Could you try deleting the app that is not working and add it again ? Also, could you share some screenshots?
