### ISSUE TITLE
Blank screen after Microsoft Teams redirects to company portal

### ISSUE THREAD

**Issue by MrJohanssons** [ramboxapp/community-edition#2795]
### Steps to reproduce

1. Launch Rambox
2. Add teams
3. Try to login

### Expected behavior

You should be able to login after being redirected to company portal.

### Actual behavior

After entering company email I am redirected to company portal but this is not displayed in Rambox. It's a blank screen.

### ENVIRONMENT

> Rambox: v0.7.5 - via snap

> OS: Ubuntu 20.04 LTS

> Arch: x64

**Comment by MrJohanssons** [comment]
It was working for a few hours and now the same issue is back... just a blank screen.

**Comment by fvulich** [comment]
Could you try deleting the Teams app and adding it again?
