### ISSUE TITLE
Notifications dont have any control!!

### ISSUE THREAD

**Issue by parasudilip** [ramboxapp/community-edition#2797]
Its not an issue exactly, rather a feature
Give an option to mute the notification of an app fully. At time it can get annoying when there is a bulk messaging going on in an group. Also please dont post notification when an app is already open in foreground.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
You can set this in the app configuration. 
![image](https://user-images.githubusercontent.com/46904390/91579697-61f7a180-e922-11ea-914d-0c9e61a696d7.png) or use the "Do not disturb" mode.
![image](https://user-images.githubusercontent.com/46904390/91579844-98352100-e922-11ea-9ad8-a001fdf7eec1.png)
If that's not what you meant please elaborate a bit further.

**Comment by parasudilip** [comment]
I will put an example.
Assume I mute group A on instagram.
But I am still getting notification from that group.

This is my issue

________________________________
