### ISSUE TITLE
Gmail Sign-in Impossible

### ISSUE THREAD

**Issue by weezyfiggs** [ramboxapp/community-edition#2801]
I changed my Gmail password earlier this week, and thus had to sign in again in Rambox.  But when I got to do so, I enter my e-mail address, click Next, and immediately get the following message:

Couldn't sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

Rambox is up-to-date and I've tried removing and re-adding the account with the same results.  I've also tried enabling "less secure apps" in my Gmail account settings with no luck.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18362

**Comment by saenzramiro** [comment]
Duplicate #2780
