### ISSUE TITLE
Gmail

### ISSUE THREAD

**Issue by Sukpmp** [ramboxapp/community-edition#2802]
Hi, I am getting an error trying to add a Gmail account to Rambox. 
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> darwin x64 19.6.0

**Comment by saenzramiro** [comment]
Duplicate #2780
