### ISSUE TITLE
brand new user - can't get started 

### ISSUE THREAD

**Issue by destiny911** [ramboxapp/community-edition#2803]
Everyting google related (main log in) and hang outs gives me this 
Couldn't sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.19041

**Comment by mexson** [comment]
This issue appeared on other all-in-one messaging apps such as Biscuit and Ferdi (not sure about the latter) so I suspect that Google made some changes that are interfering with electron

**Comment by saenzramiro** [comment]
This is duplicate with #2780. We fixed already in version 0.7.6.
