### ISSUE TITLE
Can't login into Google Calender because it says, rambox is not a safe browser

### ISSUE THREAD

**Issue by sbaghdadi** [ramboxapp/community-edition#2804]
### Steps to reproduce

1. Create Google Calender Service
2. Type in your e-mail address
3. Get the error message

### Expected behavior

I should be able to login into my google account.

### Actual behavior

I can't login into my google account, because auf this error message (german):
![Bildschirmfoto 2020-09-01 um 10 41 00](https://user-images.githubusercontent.com/127633/91828098-01c57000-ec40-11ea-9ef3-fd4cee7fde4a.png)

### ENVIRONMENT

> Rambox: v0.7.5

> OS: MacOS 10.15.6

> Arch: x64

**Comment by saenzramiro** [comment]
Duplicate #2780
