### ISSUE TITLE
0.7.6 Installer crashes itself, Rambox and Chrome if Rambox is running while installing.

### ISSUE THREAD

**Issue by incendor** [ramboxapp/community-edition#2805]
### Steps to reproduce

1. Have Rambox and Google Chrome running.
2. Run installation of Rambox 0.7.6 "For all users on this computer".

### Expected behavior

Normal installation of 0.7.6, maybe with exiting running programs manually.

### Actual behavior

Installer forcibly kills Google Chrome, running Rambox process and itself without installing the latest version.

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Windows 10 Pro 2004

> Arch: x64

### Workaround

Manually exit Rambox & Google Chrome before executing the update installer.

**Comment by fvulich** [comment]
We couldn't reproduce this issue. But thanks for reporting it.
