### ISSUE TITLE
0.7.6 is blocked by Windows Defender Smartscreen

### ISSUE THREAD

**Issue by nheinemans** [ramboxapp/community-edition#2809]
### Steps to reproduce

1. Download 0.7.6 for windows, installer or zip file
2. Run the installer, or run de rambox.exe

### Expected behavior

Start Rambox app

### Actual behavior

Error message:
Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

### ENVIRONMENT

> Rambox: v0.7.6

> OS: Windows 10 Enterprise

> Arch: x64

I don't have admin privileges on this machine. I can run 0.7.5 without any issues. I installed 0.7.5 through the installer. Replacing all files with the 0.7.6 causes the error. Also running the 0.7.6 causes the error immediately, as if the installer exe itself is not recognized.

**Comment by fvulich** [comment]
Since version 0.7.6 we changed our signer of the Windows Certificate from "Ramiro Pablo Saenz" to "Rambox LLC" that's why Windows may show you a Microsoft Defender SmartScreen alert, please read this [article](https://rambox.freshdesk.com/a/solutions/articles/42000079222)

**Comment by nheinemans** [comment]
Unfortunately, there is no "run anyway" button on my machine. Would it be possible to publish a new version signed with the previous certificate?

**Comment by fvulich** [comment]
No longer reproducible
