### ISSUE TITLE
Incorrect gmail notification badge number

### ISSUE THREAD

**Issue by TheChilliPL** [ramboxapp/community-edition#2810]
### Steps to reproduce

1. Add Gmail to Rambox, and log in
2. Have someone send you a message if you already have some messages on your Gmail.

### Expected behavior

Rambox should display the number of unread messages.

### Actual behavior

Rambox shows the number of total messages, including ones already read.
![image](https://user-images.githubusercontent.com/18823939/92252501-9c3ae300-eece-11ea-9404-9269227b9892.png)
![image](https://user-images.githubusercontent.com/18823939/92252508-9e04a680-eece-11ea-8059-e84f1092414c.png)

### ENVIRONMENT

> Rambox: v0.7.6

> OS: Windows 10 version 2004 build 19041.450

> Arch: x64

**Comment by fvulich** [comment]
The badge shows you the total of unread messages that you have, not only the ones of your Inbox but also the ones in other categories (social, notifications, etc). But if you want only the ones in your Inbox, inject this code in your Gmail app.

`function checkUnread(){if(null!==document.querySelector(".aim .aio").querySelector("div"))updateBadge(parseInt(document.querySelector(".aim .aio").querySelector("div").innerHTML.replace(".","")));else{var e=document.getElementsByClassName("aio")[0];updateBadge(-1!=e.textContent.indexOf("(")&&(t=parseInt(e.textContent.replace(/[^0-9]/g,""))))}}function updateBadge(e){1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3e3);
`

**Comment by TheChilliPL** [comment]
> The badge shows you the total of unread messages that you have, not only the ones of your Inbox but also the ones in other categories (social, notifications, etc). But if you want only the ones in your Inbox, inject this code in your Gmail app.
> 
> `function checkUnread(){if(null!==document.querySelector(".aim .aio").querySelector("div"))updateBadge(parseInt(document.querySelector(".aim .aio").querySelector("div").innerHTML.replace(".","")));else{var e=document.getElementsByClassName("aio")[0];updateBadge(-1!=e.textContent.indexOf("(")&&(t=parseInt(e.textContent.replace(/[^0-9]/g,""))))}}function updateBadge(e){1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3e3); `

Thanks a lot! The snippet works perfectly!
