### ISSUE TITLE
Skype 'download files in chat' functionality not work

### ISSUE THREAD

**Issue by onetuser** [ramboxapp/community-edition#2813]
### Steps to reproduce

1. Open skype, send file in chat
2. Other user tries to download file

### Expected behavior

File is downloaded somewhere

### Actual behavior

File is not downloaded and skype shows it as not downloaded. Several clicks - same result.

### ENVIRONMENT

> Rambox Pro: v1.3.2, snap packet

> OS: Ubuntu 19.10

**Comment by fvulich** [comment]
We apologize for this inconvenience. I just checked and it's working as it should, Could you share some screenshots or even better a video of your issue?. Also, this support channel is for the CE users. If you are using Rambox Pro, please use our [support portal](https://rambox.freshdesk.com/) to report your problems, and we will help you there.

**Comment by onetuser** [comment]
My fault. Download directory in settings was wrong.
