### ISSUE TITLE
Google Calendar - PopUps despite of disabled notifications

### ISSUE THREAD

**Issue by francwalter** [ramboxapp/community-edition#2814]
Hello

I am just a new user to Rambox, I come from Franz, where the Google products are not anymore supported in 5.3.3.
I have added Google Calendar in Rambox and after a short while I got a popup from a calendar entry with notification.
I have already Popups with Thunderbird, where I use the Google Calendar also and primarily, so I disabled the notification in Rambox's Google Calendar Settings:

![grafik](https://user-images.githubusercontent.com/927269/92300945-888b8d00-ef5f-11ea-8222-6749594e8dcd.png)

But they are still coming. 
Is it not possible to disable these Calendar notification popups in Rambox for Google Calendar?
The setting is not ment for this?

Thanks for clarification. If I cannot disable these, I will disable Google Calendar in Rambox :cry: 
frank

### ENVIRONMENT

> Rambox: v0.7.6
> OS: Windows 8.1 Enterprise 64-Bit

**Comment by fvulich** [comment]
I just tried and it's working as it should if you uncheck 
![image](https://user-images.githubusercontent.com/46904390/92948882-7febf880-f430-11ea-94d8-916f8b39dd46.png)
Rambox doesn't show the notification. Could you share some screenshots of even better a video of your issue?

**Comment by francwalter** [comment]
Maybe I didn't make it clear: I have disabled notification, as I showed in the screenshot before. 
But again, I show that Google Calendars notification is disabled:

![grafik](https://user-images.githubusercontent.com/927269/93058680-fdea1280-f66f-11ea-9cfa-2e7258645a5f.png)

![grafik](https://user-images.githubusercontent.com/927269/93058778-1b1ee100-f670-11ea-8e17-8f652fc82041.png)

So now I created a new entry in Google Calendar with a notification (as most of my calendar entries are):

![grafik](https://user-images.githubusercontent.com/927269/93059176-a4ceae80-f670-11ea-96c2-ee1b400fa802.png)

and at 9:50 a.m. a notification in Rambox is coming nevertheless, despite of disabled in Rambox:

![grafik](https://user-images.githubusercontent.com/927269/93058882-40abea80-f670-11ea-84a4-a7859584dcbb.png)

So I guess, it is just not possible to disable those?
Thanks.
frank

**Comment by francwalter** [comment]
I see the "mac" lable was added. But this bug was on both, Windows (see my first post) and Mac OS 10.11.6

I will test later if Rambox 0.7.7 still shows the unwanted (and unchecked) notification on Windows, on Mac I still had it yesterday.

At the moment I disabled the service (Google calendar) as it is the only way to get rid of these notification popups.

**Comment by fvulich** [comment]
We couldn't reproduce this issue yet. Could you try deleting the Calendar app and adding it again?

**Comment by francwalter** [comment]
> 
> 
> We couldn't reproduce this issue yet. Could you try deleting the Calendar app and adding it again?

I tried this before, it doesn't help.
Please try to reproduce this bug, it is not solved.

**Comment by francwalter** [comment]
I found now that there is "Google Calendar" in the services. I had it added as _Custom Service before.
So I added the service "Google Calendar" from services and put in my credencials. I disabled "Show notifications" and checked "Mute all sounds".
Now I added an entry in the calendar with notfication and waited till it came up and voila! 
Still I get the annoying PopUp:

![grafik](https://user-images.githubusercontent.com/927269/99087867-8e3ec800-25cb-11eb-9c40-0d636db29a99.png)

This is on Windows 10 and Rambox 0.77 (so definetly the mac osx tag was wrong):

![grafik](https://user-images.githubusercontent.com/927269/99088020-bdedd000-25cb-11eb-9182-de1f003cef91.png)

It cannot be sync because sync not working anyway: Error occurred when trying to backup your configuration.
So what can the reason be?

To reproduce: just add an entry in the calendar some minutes later with an notification (0 minutes) and wait till Rambox fires the popup for this calendar entry.
Thanks.

**Comment by francwalter** [comment]
Is there any likelyness, that this bug will be fixed?
It has got the "Service Bug" Tag now, but is this now very unlikely to be fixed, as it is likely not a real Rambox bug?
It is a while now, half a year :(

**Comment by francwalter** [comment]
Now, after reading and searching a while, all is clear: the Rambox community edition is not under real development so bugs wont be fixed. Good to know, I found [Hamsket](https://github.com/TheGoddessInari/hamsket), a fork under development and without this buggy Rambox login. Backup is made on disk, thats it.
Here a description of the fork: [Question: Original Rambox vs Fork?](https://github.com/TheGoddessInari/hamsket/issues/67)
Goodby Rambox 😄
