### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by PSNineteen** [ramboxapp/community-edition#2816]
I love the initiative and the project you've taken. As it is a new project, there's always bound to be problems but I will still use your product. 
The major problem is:
Whenever I open a message, the notification number decreases by 1. For eg. If I have 17 unread chats and I open one, the chats not opened become 16. This way I open many chats and these many times I had a problem. I dunno, if this is a one app bug or not, but it happened with e in Instagram. 
Still, I love the projetct

	
	-
	> Rambox 0.7.6
	> Electron 7.2.4
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
I don't fully understand your issue, could you share some screenshots or even better a video of your issue? for the video we recommend www.loom.com
