### ISSUE TITLE
Remove or rename a Tab?

### ISSUE THREAD

**Issue by jtpryan** [ramboxapp/community-edition#2817]
I want to rename or remove a tab once it is created.  I know I can rename it as I create it, but if created I can not rename it or remove it.

Jim

**Comment by fvulich** [comment]
In the Dashboard (where you add the apps) in the column in the right you can edit or delete them
![image](https://user-images.githubusercontent.com/46904390/92947882-f982e700-f42e-11ea-83e9-d0d5d5b423d6.png)
