### ISSUE TITLE
StackOverflow's allert-counter is broken.

### ISSUE THREAD

**Issue by LittleFire000000000** [ramboxapp/community-edition#2818]
Simple.  Create a custom entry named StackOverflow.  Point it to [https://stackoverflow.com/](https://stackoverflow.com/).  Sign in.  The site has an inbox and an achievements stream.  Rambox didn't detect a comment pending in my inbox.  Yes, StackOverflow is technically custom; but, it's popular enough for Rambox to try to monitor correctly.

> Rambox 0.7.5
> Electron 7.1.12
> linux x64 5.8.6-301.fc33.x86_64

**Comment by fvulich** [comment]
Rambox normally search for badges on the title of the app but you could add a custom code to read the badges from the dom, I made this one for you as a starter point.

```
function checkUnread() {
    var e = document.querySelector(".indicator-badge.js-unread-count._important");
    updateBadge(e ? parseInt(e.innerText) : 0);
}
function updateBadge(e) {
    1 <= e ? rambox.setUnreadCount(e) : rambox.clearUnreadCount();
}
setInterval(checkUnread, 3e3);

```

**Comment by LittleFire000000000** [comment]
> Rambox normally search for badges on the title of the app but you could add a custom code to read the badges from the dom, I made this one for you as a starter point.
> 
> ```
> function checkUnread() {
>     var e = document.querySelector(".indicator-badge.js-unread-count._important");
>     updateBadge(e ? parseInt(e.innerText) : 0);
> }
> function updateBadge(e) {
>     1 <= e ? rambox.setUnreadCount(e) : rambox.clearUnreadCount();
> }
> setInterval(checkUnread, 3e3);
> ```

Thank you, fvulich!  It works perfectly.
