### ISSUE TITLE
Copy paste broken on Linux rambox

### ISSUE THREAD

**Issue by huang-jy** [ramboxapp/community-edition#2822]
### Steps to reproduce

1. Copy something outside of Rambox (e.g. find an image on a website, right-click, then pick "Copy Image")
2. Go into Rambox into something that accepts an image paste (Discord, Slack, Telegram, etc.)
3.  Paste using CTRL+V
4. Nothing happens

### Expected behavior

Copy-paste to work

### Actual behavior

Rambox hangs briefly but then does nothing

### ENVIRONMENT

> Rambox: v0.7.5 (Snap Version)

> OS: Ubuntu

> Arch: x64

**Comment by fvulich** [comment]
I couldn't reproduce your issue (Ubuntu 18.04, snap). Also, please update to v0.7.6 you can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by huang-jy** [comment]
Here's a screen cap showing the issue.

**Comment by huang-jy** [comment]
https://photos.app.goo.gl/c18JsVXs9jxjg6hq6

**Comment by huang-jy** [comment]
And I just upgraded to 0.7.6 and it is still happening. :(

**Comment by huang-jy** [comment]
Additional, I switch to deb version 0.7.6 and still occurring.

**Comment by huang-jy** [comment]
Closing due to no action
