### ISSUE TITLE
Couldn't sign into Google with 2-step authentication mechanism

### ISSUE THREAD

**Issue by olekhy** [ramboxapp/community-edition#2824]
If i will connect to my google emeial account i get flow information shown

Couldn't sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

i use 2-step authentication on google.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.4.0-47-generic

**Comment by fvulich** [comment]
Please update to v0.7.6 you can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
