### ISSUE TITLE
Unable to connect to new google service

### ISSUE THREAD

**Issue by kabelanbalachandran99** [ramboxapp/community-edition#2825]
hey!  whenever I try to open new gmail tab it shows that your browser or app may not be secure, kindly check into it

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.8.7-200.fc32.x86_64

**Comment by renatofmsoares** [comment]
![image](https://user-images.githubusercontent.com/24680037/93144176-d458d780-f6bf-11ea-8e0d-aa85dcd14458.png)

**Comment by fvulich** [comment]
@kabelanbalachandran99 please update to v0.7.6 you can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

@renatofmsoares Could you try deleting the app with the issue and add it again?
