### ISSUE TITLE
[Service request] Add Xender & AirDroid

### ISSUE THREAD

**Issue by noraj** [ramboxapp/community-edition#2828]
It's similar to Whatsapp, it needs to be synched with a phone.

- Xender: http://www.xender.com/ - http://web.xender.com/
- AirDroid: https://www.airdroid.com/ - https://web.airdroid.com/

**Comment by chrispinkney** [comment]
Hey Guys,

I'm a first time open source contributor (and programming student) and would like to try and work on this issue if possible.

I'll get started (_if that's okay with everyone_) and send a PR if I make any progress 👍

**Comment by chrispinkney** [comment]
See #2841

**Comment by fvulich** [comment]
Fixed in #2841
