### ISSUE TITLE
Feature Request: Toggle Service Bar

### ISSUE THREAD

**Issue by autoteleology** [ramboxapp/community-edition#2830]
I use Rambox as a desktop client for a single application (Google Voice) because there are no other reasonable implementations of an official or unofficial desktop client. This use case makes the service bar a waste of screen space because I do not switch from service to service. Therefore, I would like to be able to toggle the service bar like the menu bar can be toggled.

> Rambox: v0.7.6

> OS: Windows 10

**Comment by fvulich** [comment]
I understand your request but it doesn't represent the spirit of Rambox, because it's made to handle several apps, that's why we are not going to develop that feature, but you can always try to do it yourself. Best of lucks.
