### ISSUE TITLE
Gmail limit notifications badge to count Primary Inbox emails only

### ISSUE THREAD

**Issue by Laura1590** [ramboxapp/community-edition#2831]
Currently the unread badge is shown only when there are unread emails in the `Primary` Inbox. When this badge is shown, it also includes the number of unread emails from all other Inboxes (e.g. `Social`, `Promotions`)

Is there a way to include only the number of emails from the `Primary` Inbox when displaying the notification badge?

**Comment by fvulich** [comment]
The badge shows you the total of unread messages that you have, not only the ones of your Inbox but also the ones in other categories (social, notifications, etc). But if you want only the ones in your Inbox, inject this code in your Gmail app inside Rambox.

```
function checkUnread(){if(null!==document.querySelector(".aim .aio").querySelector("div"))updateBadge(parseInt(document.querySelector(".aim .aio").querySelector("div").innerHTML.replace(".","")));else{var e=document.getElementsByClassName("aio")[0];updateBadge(-1!=e.textContent.indexOf("(")&&(t=parseInt(e.textContent.replace(/[^0-9]/g,""))))}}function updateBadge(e){1<=e?rambox.setUnreadCount(e):rambox.clearUnreadCount()}setInterval(checkUnread,3e3);
```
