### ISSUE TITLE
Google calendar says 'Not a secure browser'

### ISSUE THREAD

**Issue by kevinunger** [ramboxapp/community-edition#2834]
### Steps to reproduce

1.  Add google calendar to rambox 
2.  enter e-mail in google calendar

### Expected behavior

log in into google calendar

### Actual behavior

'Couldn't sign you in'
'This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.'
![image](https://user-images.githubusercontent.com/5601589/94015962-d00e7780-fdad-11ea-8243-a31fb3772cd9.png)

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Windows 10 Home 1909

> Arch: x64

**Comment by fvulich** [comment]
please follow #2835
