### ISSUE TITLE
Gmail app not working

### ISSUE THREAD

**Issue by Pravesh45** [ramboxapp/community-edition#2836]
If I try to gmail tab to rambox.It first shows the normal login screen but if i try to login it tells me this.....

This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

I tried to look for a way around this but failed.This is what it looks like....
![Screen Capture_20200924124659](https://user-images.githubusercontent.com/43530395/94113271-4372c080-fe64-11ea-94d5-3c146f5cfc9d.png)

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> linux x64 5.4.50-amd64-desktop

**Comment by rm-jamotion** [comment]
Same problem here with all google services like gmail, hangout, google drive. It is working on windows but not on linux desktops like ubuntu 20.04.

> Rambox 0.7.5
> Electron 7.1.12
> linux x64 5.4.0-48-generic

**Comment by T4mmi** [comment]
Same problem here under windows ... everything was working fine but I tried to remove/restore google services tabs and got this same error ...

**Comment by fvulich** [comment]
Please follow #2835
