### ISSUE TITLE
Slack reporting insecure browser

### ISSUE THREAD

**Issue by huang-jy** [ramboxapp/community-edition#2837]
### Steps to reproduce

1. Add Slack to the app
2. Attempt to sign in using Google auth
3. Get an error saying browser is insecure

### Expected behavior

Able to access slack

### Actual behavior

Unable to access Slack

### ENVIRONMENT

> Rambox: v0.7.6

> OS: Ubuntu

> Arch: x64

Version: 0.7.6
Platform: linux (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by huang-jy** [comment]
Worked around it a bit by inviting and creating a user that does not require the Google login. So this issue might be similar to #2835

**Comment by saenzramiro** [comment]
Yes, it's related with #2835. Let's merge with that one.
