### ISSUE TITLE
Snapstore does not show the latest version 0.7.6

### ISSUE THREAD

**Issue by sridharmane** [ramboxapp/community-edition#2838]
Although the snap package for 0.7.6 is built [here](https://github.com/ramboxapp/community-edition/releases/tag/0.7.6), looks like its not published to the snap store.
### Steps to reproduce

1. https://snapcraft.io/rambox
![Screenshot from 2020-09-30 16-32-35](https://user-images.githubusercontent.com/1156113/94738972-32cbba00-033e-11eb-939f-1afd2eeaf2fd.png)

2. Ubuntu Software > Rambox
![Screenshot from 2020-09-30 16-35-03](https://user-images.githubusercontent.com/1156113/94739018-4aa33e00-033e-11eb-81a0-027bfb71044d.png)

### Expected behavior

Should see latest version 0.7.6

### Actual behavior

Seeing older version 0.7.5

### ENVIRONMENT

> Rambox: v0.X.X

> OS: Ubuntu 20.04

> Arch: x64

**Comment by fvulich** [comment]
Thanks for the heads up. We fixed it.
![image](https://user-images.githubusercontent.com/46904390/94945175-a55ca700-04b0-11eb-8c99-c79439cad2a4.png)
