### ISSUE TITLE
Impossibile eseguire l'accesso (RamBox)

### ISSUE THREAD

**Issue by ziofai** [ramboxapp/community-edition#2839]
![errore google](https://user-images.githubusercontent.com/72209932/94820094-56efcf80-0400-11eb-954c-cb2dd3f300ee.JPG)
	

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
Please follow https://github.com/ramboxapp/community-edition/issues/2835
