### ISSUE TITLE
Example of filling out env.js?

### ISSUE THREAD

**Issue by chrispinkney** [ramboxapp/community-edition#2840]
### Steps to reproduce

1. Started following `CONTRIBUTING.md` to the 
2. Got kind of confused around the part regarding `env.js`

___

Sorry for the noob question. I've never used auth0 (and don't even know anything about it to be honest). Can anyone give me a quick and dirty explanation of what to do for this step?

I'd be more than willing to add it to `CONTRIBUTING.md` to help other first timers muddle their way through as well.

Thanks!

**Comment by fvulich** [comment]
That env.js is only need to the Auth0 configuration, for the backup of the services. 

```
var auth0Cfg = {
	 clientID: ''
	,clientSecret: ''
	,domain: ''
};
``` 
You only need to fill it up if you want that functionality and you'll need to open an account in Auth0
