### ISSUE TITLE
MacOS Keychain integration

### ISSUE THREAD

**Issue by surak** [ramboxapp/community-edition#2845]
### Steps to reproduce

1. Open Rambox
2. Some tabs' session expire
3. Rambox doesn't use credentials from Keychain

### Expected behavior

A way to use saved passwords from Keychain

### Actual behavior

Nothing.

### ENVIRONMENT

> Rambox: v0.7.5

> OS: MacOS Catalina 10.15.6

> Arch: x64

**Comment by fvulich** [comment]
Rambox doesn't support Keychain and for the moment it's not in our roadmap to support it.
