### ISSUE TITLE
Whatsapp voicenotes can no longer be heard. Whatsapp needs the window to be much larger, or else it hides the typing and profile areas.

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#2848]
Since yesterday, before and after I did the latest update, I have these 2 issues. The sound messages I receive on Whatsapp play but are "muted" somehow. And the place where I type messages, along with the top bar where the receiver's profile appears disappear when the window is as I used to have it, I need to enlrage it much more so they both appear.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 6.1.7601

**Comment by 613TheEvil** [comment]
To add some more info, when the window is smaller, I can scroll down and the chat bar appears, I can type messages normally and see them too. But no matter how much I scroll up, the recepient's profile bar doesn't appear.

**Comment by StrikeAgainst** [comment]
I can second that, sound output in general has been missing for me since recently. Maybe Rambox has issues picking the right output device? There should be an option for that.

**Comment by hokkenmeijer** [comment]
Same problem here with the window in Linux-version x64.

**Comment by fvulich** [comment]
We could reproduce your issue. Could you try deleting the WhatsApp app and adding it again? Also, could you share some screenshots or even better a video of the issue? For the video we recommend www.loom.com

**Comment by 613TheEvil** [comment]
I'll screenshot before and after deleting it

**Comment by 613TheEvil** [comment]
https://imgur.com/a/kPujI79 I took 4 screenshots, before and after, there was no change sadly. Anyway, from what I see, the problem is when the window is not large enough, like in the one of the four screensots, the extra elevator appears on the right side and it can't show both the profile bar and the message bar at the same time.

**Comment by fvulich** [comment]
Seems that you have "Don't disturb" on (that's why you couldn't hear the voice messages)
![image](https://user-images.githubusercontent.com/46904390/96284431-f04be380-0fb3-11eb-9e07-10605d69e8e2.png)
Also, you could try zooming out the page. 
![image](https://user-images.githubusercontent.com/46904390/96284574-225d4580-0fb4-11eb-8aca-44e855851449.png)

**Comment by 613TheEvil** [comment]
You are correct, I had it turned on, I feel like a complete idiot and I apologize for it. I don't remember turning it on, if this makes it any better... I think it makes it worse. :( Sorry again.

**Comment by fvulich** [comment]
Glad to hear that we could sort it out!. Have a nice day!
