### ISSUE TITLE
Rambox never downloads in the background nor updates itself despite message.

### ISSUE THREAD

**Issue by KshDi13** [ramboxapp/community-edition#2849]
### Steps to reproduce

1. Open up Rambox and message will appear
or
2. Restart Rambox and message will appear
or
3. Clear message and click _Help>Check for updates_ and message will appear.

### Expected behavior

Automatically installs new version.

### Actual behavior

Message top of application saying _New version is available (0.7.7) is downloading in the background and you will be notified when it is ready to be installed._

### ENVIRONMENT

> Rambox: v0.7.5
> OS: Win10
> Arch: x64

**Comment by Frank-Friemel** [comment]
+1 Had downloaded manually but the problem still persists

![image](https://user-images.githubusercontent.com/747676/95958022-ce5e2f80-0e00-11eb-8d77-8139b1aed64f.png)

**Comment by fvulich** [comment]
We are investigating this issue. For the moment please download the installer from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) and install it manually

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
