### ISSUE TITLE
New Messenger

### ISSUE THREAD

**Issue by edlas-github** [ramboxapp/community-edition#2851]
Hello, I installed your Rambox - it's very fine!!  So I removed "Franz" ....ok!  I can't find the Messenger "DeltaChat" in your program. Could you support it next time? DeltaChat ( https://delta.chat/de/ ) is an open source prog too. Thank you.    Ed Las

	
	-
	> Rambox 0.7.6
	> Electron 7.2.4
	> linux x64 5.4.0-48-generic

**Comment by fvulich** [comment]
Does it have a web app?

**Comment by fvulich** [comment]
No, I meant a web app to open in the browser (Chrome, Firefox, etc), for instance, the Skype web app URL is https://web.skype.com/
