### ISSUE TITLE
Snapstore does not show the latest version 0.7.7

### ISSUE THREAD

**Issue by mhatvan** [ramboxapp/community-edition#2852]
Same exact issue like https://github.com/ramboxapp/community-edition/issues/2838

**Comment by fvulich** [comment]
We are working on this issue.

**Comment by cawolf** [comment]
The snap store now shows 0.7.7 and my installation was automatically upgraded - this issue seems to be solved for me. :+1:

**Comment by fvulich** [comment]
Fixed
