### ISSUE TITLE
Version 0.7.7 asks me to upgrade to 0.7.6

### ISSUE THREAD

**Issue by LivingWithHippos** [ramboxapp/community-edition#2853]
### Steps to reproduce

1. Download and install Rambox-0.7.7-win.exe
2. Start it

Note: this was a new installation, not an upgrade

### Expected behavior

Getting no warning about the signature change

### Actual behavior

You will be asked to upgrade because of the [signature change,](https://rambox.freshdesk.com/support/solutions/articles/42000079222-how-to-install-rambox-ce-) and the linked version is 0.7.6

I should not be asked to upgrade and the link should be to the latest stable tag, probably.
I also manually checked and the signature to Rambox.exe is the updated one.

### ENVIRONMENT

Windows 10 x64

Rambox: v0.7.7

**Comment by rootwork** [comment]
I'm seeing this too on Linux (installed via Rambox-0.7.7-linux-amd64.deb).

If I go to Help...About Rambox, it reports that the version number is still 0.7.6. I tried removing Rambox entirely just to make sure there wasn't some remnant of the old version on my computer and reinstalling from the 0.7.7 file from scratch -- it still shows version 0.7.6 and prompts me to update.

**Comment by LivingWithHippos** [comment]
mmh that's not the case for me, it shows 0.7.7

**Comment by rootwork** [comment]
After a restart, it shows 0.7.7 for me too (and doesn't bug me about an upgrade).

**Comment by fvulich** [comment]
Sorry for the inconvenience. It has already been fixed.
