### ISSUE TITLE
VK Community Messages

### ISSUE THREAD

**Issue by OlegNT** [ramboxapp/community-edition#2854]
### Steps to reproduce

1. Add VK account that is Community Admin (able to recieve Community Messages)
2. Recieve a new message to Community.
3. The new messages count badge is shown on VK Page (in the left menu) but Rambox doesn't consider such messages.

Here is a screenshot: https://i.imgur.com/s2LFdH6.png

### Expected behavior

It would be better if Rambox notifies about Community Messages as well as Personal Messages.

### Actual behavior

Rambox doesn't notify about Community Messages.

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Windows 10

> Arch: x64

**Comment by fvulich** [comment]
Please check this ticket https://github.com/ramboxapp/community-edition/issues/103 to see how does the counter works and how you can modify it to get your desired behavior.
