### ISSUE TITLE
'Install on Linux' wiki page should include Debian package instructions

### ISSUE THREAD

**Issue by rootwork** [ramboxapp/community-edition#2855]
[Install on Linux](https://github.com/ramboxapp/community-edition/wiki/Install-on-Linux) needs updating.

I'd be happy to suggest these changes directly, but [your wiki is currently only open to editing from collaborators](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis).

This doesn't follow the usual issue template since it's about the wiki, not code.

Suggested second section, between the two current sections, in Markdown:

```markdown
Debian package steps (including Ubuntu, Linux Mint)

1. Go to [the releases page](https://github.com/ramboxapp/community-edition/releases) and download the latest `.deb` file (`amd64` for 64-bit systems; `i386` for 32-bit systems).
2. Open the file with your system's Package Manager or Software Manager.
3. Follow your system's prompts to install.
```

The Debian package automatically takes care of the `libappindicator1` installation. For that reason and the fact that the Snap version requires the scary-looking "dangerous" flag, I'd actually suggest putting this section first, but that's up to you.

**Comment by fvulich** [comment]
Thanks for your contribution, I just added the Debian instructions.
