### ISSUE TITLE
Facebook Messenger with 2FA

### ISSUE THREAD

**Issue by HSB-collab** [ramboxapp/community-edition#2856]
I have 2FA set with Facebook. When I try to sign into Messenger on Rambox it asks for the authorisation code, which I provide but then it keeps returning to the screen saying "Please verify your Facebook account". Each time I click "Continue" it just returns to that screen.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by HSB-collab** [comment]
It seems that this problem occurs when you have the service bar on this side (my normal preference). When I changed to the service bar at the top, I was able to login to Messenger (it logged me into Facebook first and then I selected Messenger)

**Comment by SEEN88** [comment]
I am running Rambox CE in a docker container with VNC  on unRAID and I am having the exact same issue. Unfortunately no changes I make to the interface will fix it for me. I have tried recreating the service and recreating the docker container as well.

**Comment by mhajas** [comment]
I am experiencing the same behaviour on Fedora + sway. I was able to workaround it with following steps.

1. On the messenger login screen click forgotten password (at the bottom of the page)
2. Facebook forgotten password page is opened with login form at the top of the page 
3. Logging in using login form (^^^) works for me and I am redirected to Facebook
4. Reload the messenger tab

**Comment by pfreiberg** [comment]
> I am experiencing the same behaviour on Fedora + sway. I was able to workaround it with following steps.
> 
> 1. On the messenger login screen click forgotten password (at the bottom of the page)
> 2. Facebook forgotten password page is opened with login form at the top of the page
> 3. Logging in using login form (^^^) works for me and I am redirected to Facebook
> 4. Reload the messenger tab

I can confirm this workaround. Thank you.

**Comment by fvulich** [comment]
Seems to be fixed. No longer reproducible.
