### ISSUE TITLE
Issue using wacom tablet - click doens't work

### ISSUE THREAD

**Issue by ccaiobb** [ramboxapp/community-edition#2857]
I work using a wacom intuos CTH-490 tablet and the clicks of the pen are not recognized, specifically on the minimize, restore and close buttons of the window.
it's a very small problem but I found it interesting to notify.

thanks!

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
Thanks for reporting it, seems to be electron related.
