### ISSUE TITLE
WhatsApps does not work after update to  Rambox to 0.7.7

### ISSUE THREAD

**Issue by alenzorbbn25** [ramboxapp/community-edition#2859]
After update to Rambox 0.7.7   when to check on all programs to see if I have access to them.  For WhatsApp I get the following window poping up stating

****_Trying to reach phone 
Retrying in invalid data 

Make sure your phone has an active internet connection. Learn more_**   
Then just below this message there a Log Out and  Retry Now buttons

The "**Learn more**" is link to the following page _**https://faq.whatsapp.com/web/troubleshooting/cant-connect-to-whatsapp-web-or-desktop?lang=en**_

So my phone and computer are on the same network,  In WhatsApp, I log off from all devices,  I click on the Log Out button in the error message, which it doesn't allow me to. Same with the Retry Now button click on that couple of times and nothing happing.

Seem like the new update has caused an error when trying to connect to the **https://web.whatsapp.com/**   site. 

Could you please have a look? 

This is the current version I have 
Version: 0.7.7
Platform: win32 (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

Sincerely
Anthony Lenzo
     

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 6.3.9600

**Comment by fvulich** [comment]
We couldn't reproduce your issue. WhatsApp is working as it should in our devices. Could you try deleting the WhatsApp app and adding it again?

**Comment by alenzorbbn25** [comment]
Hello

That what I end up doing,  and it work afterwards

Cheers


Anthony Lenzo

[ribboncommunications.com]

**Comment by fvulich** [comment]
Glad to hear that you could sort it out.

**Comment by alenzorbbn25** [comment]
It a good app.

Anthony Lenzo
Loadbuild Engineer, R&D Engineering Solutions
500 Palladium Drive, Suite 2100 | Ottawa, ON Canada K2V 1C2
office: +1.613.699.9624
email: alenzo@rbbn.com
Connect with us: [Image] <https://www.facebook.com/ribboncomm/> [Image] <https://twitter.com/ribboncomm> [Image] <https://www.linkedin.com/company/11338267/> [cid:image010.jpg@01D6A92D.8CE68B70] <https://ribboncommunications.com/>

[Ribbon-NoCommunications]
<https://ribboncommunications.com/>
[ribboncommunications.com]
