### ISSUE TITLE
Add print permission to the Rambox snap

### ISSUE THREAD

**Issue by nemoskapetanos** [ramboxapp/community-edition#2860]
Could you please add the print permission to the snap version of the app. That way I can print my emails. This is more of a feature request than an issue. Thanks!

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.4.0-52-generic

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by nemoskapetanos** [comment]
Thank you very much for adding this feature! Just updated the snap this morning & the new feature works great!
