### ISSUE TITLE
Unable to login into reddit 

### ISSUE THREAD

**Issue by Rain-of-fire** [ramboxapp/community-edition#2863]
when I type my credential it's showing the wrong password. I even tried using the custom service but it still doesn't work.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.4.0-52-generic

**Comment by fvulich** [comment]
We could reproduce your issue, we are investigating it.

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
