### ISSUE TITLE
Android messages slow typing

### ISSUE THREAD

**Issue by HSB-collab** [ramboxapp/community-edition#2865]
### Steps to reproduce

1. Compose a new message in Android Messages
2. The cursor and echoed characters are very slow to follow the typing
3. 

### Expected behavior

Characters appear as you type them

### Actual behavior

Characters appear a few seconds after you type them (leading to numerous typing errors)

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Windows 10

> Arch: x64

**Comment by fvulich** [comment]
We couldn't reproduce your issue. Could you try deleting the app and adding it again?
