### ISSUE TITLE
Rambox restart when I try to log in. 

### ISSUE THREAD

**Issue by Moosh-be** [ramboxapp/community-edition#2869]
-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.17134

**Comment by Moosh-be** [comment]
It was with facebook.  I've retry with google and it's work.

So perhaps  my account is not linked to facebook. But why restart  instead to display an error message

**Comment by fvulich** [comment]
Glad to hear that you could sort it out. We'll investigate your issue with facebook.
