### ISSUE TITLE
Controlling Updates in Rambox

### ISSUE THREAD

**Issue by AndreCahyaS** [ramboxapp/community-edition#2870]
Hello, I'm happy with rambox, up until the COVID-19 happens globally. It made me have to work from home, and sadly I'm on a metered connection.

Rambox suddenly updates their app, and sadly i didn't download my chat app before since I really liked rambox. Now I have to use Rambox and my speed is dropping so much while it updates in the background, using rambox is like a nightmare for me now since I need to do things quick without the need to wait for the update to finish.

It would be wonderful if I could update it at my leisure. Thank you.

	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
Thanks for the feedback. I will share your concerns with the team.

**Comment by fvulich** [comment]
Duplicate #2528
