### ISSUE TITLE
Update Electron: Important security fixes, v7 is EoL

### ISSUE THREAD

**Issue by ghost** [ramboxapp/community-edition#2871]
Please upgrade the current Electron version to v7.3.3 (the last release for v7). The current 
v7.2.4 is lacking a lot of security fixes as can be seen here: https://www.electronjs.org/releases/stable?version=7

Additionally, Electron v7 is now EoL and rambox really needs to consider migrating to v9 or v10. 

Please at least bump it up from v7.2.4 to v7.3.3 for now.

### ENVIRONMENT

> Rambox: v0.7.7
> OS: Linux
> Arch: x64

**Comment by fvulich** [comment]
Thanks for the heads up! We are working to make the necessary changes to update Electron.

Related #2879
