### ISSUE TITLE
UnreadCode: IrcCloud unread indicator not showing

### ISSUE THREAD

**Issue by masonc15** [ramboxapp/community-edition#2872]
### Steps to reproduce

1.  Have an unread message in a IRC channel in IrcCloud
2. 
3. 

### Expected behavior

It should have an unread message indicator on the Rambox IrcCloud tab when I have a new message in the specific IRC channel.  In the IrcCloud settings, I selected the options "Show unread message indicator" and "Notify on all messages".

### Actual behavior

The indicator is never showing up.

### ENVIRONMENT

> Rambox: v0.7.5

> OS: Windows 10

> Arch: x64

**Comment by fvulich** [comment]
It seems that the unreadCode for IrcCloud is outdated. Here I  leave you the one that it has at this moment, and takes the badges from the title of the document. Maybe you make some little changes to it and get it working again.

```
function checkUnread() {
    var e = "",
        a = document.title.match(/^\((\d+)\)/);
    try {
        e = a[1];
    } catch (e) {}
    updateBadge(e ? parseInt(e) : 0);
}
function updateBadge(e) {
    1 <= e ? rambox.setUnreadCount(e) : rambox.clearUnreadCount();
}
setInterval(checkUnread, 3e3);

```
