### ISSUE TITLE
Asked to update Whatsapp every day

### ISSUE THREAD

**Issue by mikescrill** [ramboxapp/community-edition#2873]
Hello,

This isn't a problem but instead an annoyance.  Each time Rambox is restarted, when Whatsapp service starts, I am prompted in Whatsapp that a update is available and to click the link to refresh.  I have not thoroughly tested if the issue happens each time the software restarts, or only upon initial startup after bootup of the laptop (I reboot daily).  

I only have to the refresh link the one time, but it's every day, and I thought to report it since it's starting to get on my nerves :-)

Thanks!
Michael Custer

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
Duplicate https://github.com/ramboxapp/community-edition/issues/2217

In that ticket you can find a workaround.
