### ISSUE TITLE
ProtonMail CH re-login after close and open Rambox

### ISSUE THREAD

**Issue by jebr** [ramboxapp/community-edition#2874]
### Steps to reproduce

1. Add ProtonMail CH
2. Login into ProtonMail CH
3. Close Rambox
4. Start Rambox
4. Again login into ProtomMail CH

### Expected behavior

One time login for application ProtonMail

### Actual behavior

Every time I open Rambox I need to fill in the credentials

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Windows 10 Pro

> Arch: x64

**Comment by fvulich** [comment]
I don't use regularly Protonmail but after a little bit of investigation it appears to be kind of a feature of Protonmail not giving the possibility of being keep logged. I made some time ago this script for Protonmail, it may work for ProtonmailCH or maybe you just have to make little adjustments.

Add it to the custom code option of the app.

```
setTimeout(() => {
    document.getElementById('username').value = 'mail@protonmail.com'; // your mail
    document.getElementById('password').value = 'password'; // your password
    document.getElementById('login_btn').click();
}, 1000);
```
