### ISSUE TITLE
New Install - Will not load after login - No Apps - Blank left column

### ISSUE THREAD

**Issue by instikt** [ramboxapp/community-edition#2875]
### Steps to reproduce

1. Open Rambox
2. Login
3. 

### Expected behavior
Render UI so I can add apps

### Actual behavior
White Left Column - RamBox logo in right Column
When I clear cache I am returned to login.
When I clear local data I am returned to login.

So far I have:
Cleared cache
Cleared local data
Rebooted
Uninstall and reinstall
Downloaded Free Community Version v0.7.7- Seemed to work fine
Downloaded v1.3.2 and went through update 
![1](https://user-images.githubusercontent.com/57531954/97629664-ca3b3000-1a04-11eb-9aa9-d532daf60362.PNG)
![after login](https://user-images.githubusercontent.com/57531954/97629678-d0c9a780-1a04-11eb-9d0b-0a68e6313225.PNG)

### ENVIRONMENT

> Rambox: v1.4.0

> OS: WIN10 1909

> Arch: x64

**Comment by fvulich** [comment]
Can you try doing a Clear Cache and a Clear Local Storage and then restart Rambox Pro?
![image](https://user-images.githubusercontent.com/46904390/97781289-10110900-1b69-11eb-8a75-74b4a9998962.png)


If that doesn't work, try doing an uninstall [following this tutorial](https://rambox.freshdesk.com/solution/articles/42000051684-how-to-uninstall-rambox-pro-) and then install the latest version of Rambox Pro by downloading it from [HERE](https://github.com/ramboxapp/download/releases/latest).

Please contact us again if none of those steps doesn't work, so we can give you more help.

Also, this support channel is for Rambox CE users. If you are using Rambox Pro, please use our [Support Portal](https://rambox.freshdesk.com) to report your problems, and we will help you there.

**Comment by instikt** [comment]
> Can you try doing a Clear Cache and a Clear Local Storage and then restart Rambox Pro?
> ![image](https://user-images.githubusercontent.com/46904390/97781289-10110900-1b69-11eb-8a75-74b4a9998962.png)
> 
> If that doesn't work, try doing an uninstall [following this tutorial](https://rambox.freshdesk.com/solution/articles/42000051684-how-to-uninstall-rambox-pro-) and then install the latest version of Rambox Pro by downloading it from [HERE](https://github.com/ramboxapp/download/releases/latest).
> 
> Please contact us again if none of those steps doesn't work, so we can give you more help.
> 
> Also, this support channel is for Rambox CE users. If you are using Rambox Pro, please use our [Support Portal](https://rambox.freshdesk.com) to report your problems, and we will help you there.

From my original post:
"So far I have:
Cleared cache
Cleared local data
Rebooted
Uninstall and reinstall
Downloaded Free Community Version v0.7.7- Seemed to work fine
Downloaded v1.3.2 and went through update"
