### ISSUE TITLE
Feature Request: Start Rambox Minimized to Tray

### ISSUE THREAD

**Issue by monkeylove** [ramboxapp/community-edition#2877]
### ENVIRONMENT

> Rambox: v0.7.7

> OS: Windows 10

> Arch: x64

I current have the ff. settings:

Start automatically on system startup: checked

Start minimized: checked

Display Behavior: Show in Taskbar and Tray Icon

When Closing the Main Window: Keep in tray

Always on Top: unchecked

Is it possible to have Rambox show up only in the tray icon only when it is starts up?

**Comment by fvulich** [comment]
duplicate #2806
