### ISSUE TITLE
Doesn't have dark mode??

### ISSUE THREAD

**Issue by pratik-devkota** [ramboxapp/community-edition#2880]
Ok maybe this isn't technically an issue, but I couldn't find an option to toggle **dark mode** for this app and it would be nice to have that. 
	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.9.2-arch1-1

**Comment by lulupointu** [comment]
See [my tutorial](https://github.com/ramboxapp/community-edition/issues/2882#issue-735311624) to add it manually. This is the best we got yet ^^

**Comment by fvulich** [comment]
related #107
