### ISSUE TITLE
WhatsApp not loading because it requires Chrome 60+

### ISSUE THREAD

**Issue by adstastic** [ramboxapp/community-edition#2883]
### Steps to reproduce

1. Log in to WhatsApp
2. Click the `Update to latest version` link 

### Expected behavior

WhatsApp reloads and shows chats.

### Actual behavior

<img width="889" alt="image" src="https://user-images.githubusercontent.com/9049273/98022459-8ded4280-1dfd-11eb-89ed-36bb2d0af0bd.png">

### ENVIRONMENT

> Rambox: v0.7.7

> OS: macOS 10.15.6 

> Arch: x64

**Comment by fvulich** [comment]
We can't reproduce this issue, did you added WhatsApp web as a custom app? If that so, please delete that app and add it from our preconfigured services.

**Comment by adstastic** [comment]
The issue has now disappeared. Thanks for looking into it!
