### ISSUE TITLE
Normal system tray icon becomes "missing icon" about 10 seconds after login

### ISSUE THREAD

**Issue by Steampunkery** [ramboxapp/community-edition#2887]
### Steps to reproduce

1. Set rambox to autostart minimized to the system tray
2. reboot
3. Wait about 10 seconds for the normal icon to be replace with a default "missing icon" icon

### Expected behavior

The system tray icon would remain the normal rambox icon

### Actual behavior

The normal system tray icon becomes a "missing icon" icon about 10 seconds after login

### ENVIRONMENT

* KDE Plasma 5.19.5
* Ubuntu 20.10
* Linux Kernel 5.8.0-26-generic

> Rambox: v0.7.7

> OS: Kubuntu Linux

> Arch: x64

**Comment by fvulich** [comment]
Seems that is not loading the tray icon that shows that you have a notification. Could you try with a different package? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)
