### ISSUE TITLE
Add Spike mail

### ISSUE THREAD

**Issue by rauldipeas** [ramboxapp/community-edition#2889]
Web adress: https://spikenow.com/web
Icon: ![](https://spikenow.com/web/res/2x/user.unified.png)
Notification badge:
```
function checkUnread() {
    var e = document.querySelectorAll('div.thread:not(.nobadge) div.badge');
    var t = 0;
    for (i = 0; i < e.length; i++) {
        t += e[i].innerHTML.trim() != '' ? parseInt(e[i].innerHTML.trim()) : 1;
    }
    updateBadge(t);
}

function updateBadge(e) {
    e && e >= 1 ? rambox.setUnreadCount(e) : rambox.clearUnreadCount();
}

setInterval(checkUnread, 3000);
```

**Comment by rauldipeas** [comment]
Spike mail get stucked on login screen...
![image](https://user-images.githubusercontent.com/12108031/100251799-ebb50c00-2f1d-11eb-9ec9-2d471678234d.png)

**Comment by rauldipeas** [comment]
Any updates?

**Comment by rafa761** [comment]
I'm having this issue too.

I would be very grateful if any super web developer from the team can fix this

**Comment by fvulich** [comment]
related #2959

**Comment by rauldipeas** [comment]
> related #2959

I'm using Spike on a custom entry, with JS that i wrote here, it's working fine.
