### ISSUE TITLE
Unable to reload services from local storage after manual upgrade.

### ISSUE THREAD

**Issue by Valiant-Mouse** [ramboxapp/community-edition#2890]
This is related to issues 2849 and 2875

### Steps to reproduce

1. experience issue 2849 (Rambox never downloads in the background nor updates itself despite message.)
2. manually download and install 0.7.7.7
3. loose all services
4. no provision for local import of services into new version, without cloud account

### Expected behavior

Ability to import database of services from previous installation or local backup 

### Actual behavior

I have to recreate all (20+, with several customized) services from scratch, even though I have a local backup.

### ENVIRONMENT

> Rambox Community Edition: v0.7.7.7

> OS: Windows 10 Pro Version 2004

> Arch: x64

**Comment by fvulich** [comment]
Sorry to hear this, seems that you lose your local storage config. That's one of the issues that address the backup feature.
