### ISSUE TITLE
 Messenger Video/Audio Call does not work

### ISSUE THREAD

**Issue by maxxu05** [ramboxapp/community-edition#2891]
### Steps to reproduce

1.  Open up messenger on rambox
2.  Try to start a video or audio call
3.  Does not work

### Expected behavior

Should open up a window on internet browser for video / audio call

### Actual behavior

After clicking, nothing happens on messenger.

### ENVIRONMENT

> Rambox: v0.7.7

> OS: win32 

> Arch: x64

**Comment by fvulich** [comment]
Duplicate #2650
