### ISSUE TITLE
can't login to reddit

### ISSUE THREAD

**Issue by HpVaC** [ramboxapp/community-edition#2894]
been trying for a while now to login to reddit, i'm able to on their website, but i added a custom module for it, set the url, and it gives me "incorrect password" everytime

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19041

**Comment by qkall** [comment]
I can confirm this.  As a work around, if you edit the url to old.reddit.com and log in, you can then return it to the regular url and you'll be logged in. or stay with '.old'.

**Comment by fvulich** [comment]
Duplicate #2863
