### ISSUE TITLE
iCloud Compose window doesn't work

### ISSUE THREAD

**Issue by ebiscaia** [ramboxapp/community-edition#2896]
Hi,

I have this issue with the snap version of Rambox

1. Rambox snap for Solus Linux
2. icloud
3. Compose

### Expected behavior

Compose box active on Rambox

### Actual behavior

Opens a new tab on Chrome but blank

### ENVIRONMENT

Solus Linux 4.1 Budgie

Version: 0.7.7
Platform: linux (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

Thanks,

Eduardo

**Comment by fvulich** [comment]
related #2366
