### ISSUE TITLE
Tray icon and taskbar remain unchanged when having unread messages (WhatsApp - Linux)

### ISSUE THREAD

**Issue by MosEisley34** [ramboxapp/community-edition#2898]
### Steps to reproduce

1. Add WhatsApp service to Rambox Version: 0.7.7 on linux (x64)
2. Get a message

### Expected behavior

Tray icon should turn red or taskbar should flash on unread message

### Actual behavior

Tray icon and taskbar remain unchanged

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Manjaro Linux

> Arch: x64

**Comment by fvulich** [comment]
Could you try with a different package? because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

**Comment by fvulich** [comment]
Related #2887

**Comment by fvulich** [comment]
Related #2876
