### ISSUE TITLE
Once again, whatsapp stopped its notifications, what happened, new update 2 days ago? That's when it started...

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#2899]
The Rambox tray icon doesn't change to red when whatsapp has new messages, when there are new facebook messages it works fine. What can I do? Try an older Rambox version?

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 6.1.7601

**Comment by LurchiStromberg** [comment]
Same here....
its annoying
Does nobody test the Version that rolls out?

Also annoying Isssue is, that unsing Rambox at Windows Whats App Service always offer Update...........
No matter how often you do that Update, next time you start Rambox it apears again

**Comment by Albirew** [comment]
same and linkedin notifications not working either

**Comment by fvulich** [comment]
Fixes in  https://github.com/ramboxapp/community-edition/commit/a88d7237cf0404bb33f35fd5938fbb37639ccb24 restart Rambox in order to get the latest changes.
