### ISSUE TITLE
cannot use rocketchat.wechange.de in rambox - redirecting to external browser window

### ISSUE THREAD

**Issue by devZer0** [ramboxapp/community-edition#2902]
### Steps to reproduce

1. Add https://rocketchat.wechange.de  to rambox
2. Click "enter chat" button inside window

### Expected behavior

focus stays in rambox window

### Actual behavior

being redirected to external firefox/browser window

### ENVIRONMENT

OSX high sierra
Rambox: latest
Arch: x64

**Comment by fvulich** [comment]
related #2677

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
