### ISSUE TITLE
[Bug] WhatsApp Message Notification

### ISSUE THREAD

**Issue by 8227846265** [ramboxapp/community-edition#2903]
### Steps to reproduce

Look at the WhatsApp in the Top Bar Section

### Expected behavior

If all messages are read, there should be no unread message's notification dot

### Actual behavior

All messages are read but there's still unread message's notification dot

**Screenshot**:
- https://i.imgur.com/eYnrdY9.png

### ENVIRONMENT

- Version: 0.7.7
- Platform: win32 (x64)
- Electron: 7.2.4
- Chromium: 78.0.3904.130
- Node: 12.8.1
- **WhatsApp Web: Version 2.2047.11**

**Comment by Arkentus** [comment]
Same issue

if I go down in my conversation list, the number of notifications decreases until it disappears. I try to update, clear cache, clear storage.

- https://ibb.co/tK4LyNG
- https://ibb.co/wKmJyXr
- https://ibb.co/km04zGz

**Comment by Lefky** [comment]
Having the same issue.
Referenced other issues (including mine) to this thread.

**Comment by Fran-ELS-AMS** [comment]
Same on Mac platform

**Comment by asantana8** [comment]
After the update for version 2.2047.11, in the windows, not more resize or move between screen.

**Comment by rgpublic** [comment]
Having the same issue. Theres a (1) that I can't clear. Is there any workaround on how to fix this?

**Comment by Fran-ELS-AMS** [comment]
FYI

It seems like the number counts the pinned chats as well as the unread chats.

While waiting for the official fix, I temporarily fixed this by adding the "Custom Code" below under "Advanced" in the Whatsapp configuration:
```
function checkUnread() {
	const elements = document.querySelectorAll('.CxUIE, .unread, ._2Q3SY');
	let count = 0;

	for (let i = 0; i < elements.length; i++) {
		if (elements[i].querySelectorAll('*[data-icon="muted"]').length === 0 && elements[i].querySelectorAll('*[data-icon="pinned"]').length === 0) {
			count += 1;
		}
	}
	
	updateBadge(count)
}
function updateBadge(count) {
	if (count && count >= 1) {
		rambox.setUnreadCount(count);
	} else {
		rambox.clearUnreadCount();
	}
}

setInterval(checkUnread, 1e3);
```
