### ISSUE TITLE
Whatsapp showing notification badge when there are none

### ISSUE THREAD

**Issue by mikescrill** [ramboxapp/community-edition#2909]
Hello,

Rambox Whatsapp console is showing 2 notification even though there are none.  So far, all I've done is restart the app and the computer, but the notifications still appear.  I have not started any further troubleshooting.

Thanks

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
Fixed, please restart Rambox
