### ISSUE TITLE
Skype does not find camera

### ISSUE THREAD

**Issue by s-ansa** [ramboxapp/community-edition#2910]
### Steps to reproduce

1. Click Settings -> Audio & Video -> Camera 
2. Or try starting a video chat.  

### Expected behavior

You should be able to preview image from your camera or videochat with people. 

### Actual behavior

It says "No device found".

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Ubuntu 20.04 LTS 

> Arch: x64 

iT says here https://github.com/ramboxapp/community-edition/issues/2233 that it's fixed but clearly it isn't.

**Comment by fvulich** [comment]
Check if you can access the camera from other programs or the system settings. Also check the Rambox permissions in Snapstore

**Comment by s-ansa** [comment]
It turns out that camera permissions for Rambox were off on Snap Store.
