### ISSUE TITLE
Rambox doesn't notify Linkedin's notifications

### ISSUE THREAD

**Issue by Albirew** [ramboxapp/community-edition#2916]
### Steps to reproduce

1. add  linkedin account in rambox
2. wait for new linkedin notification

### Expected behavior

rambox icon turn red and a notification badge with number of unread notifications pop on minkedin tab

### Actual behavior

nothing happens
![Sans titre](https://user-images.githubusercontent.com/2805161/100872420-136a1e00-34a2-11eb-9987-9a920dea076f.png)

### ENVIRONMENT

> Rambox: v0.7.7

> OS: windows 10 and sabayon linux

> Arch: x64

**Comment by fvulich** [comment]
The unreadCode works for the messages. If you want that the badge equal the sum of all the notifications you could add this script to the app.

```

function checkUnread() {
    let e = 0;
  	document.querySelectorAll(".notification-badge__count").forEach((n) => {
  	    parseInt(n.innerText) && (e += parseInt(n.innerText));
	}),
    updateBadge(parseInt(e));
}
function updateBadge(e) {
    e && e >= 1 ? rambox.setUnreadCount(e) : rambox.clearUnreadCount();
}
setInterval(checkUnread, 3e3);

```
And if you want only the notifications this one:

```
function checkUnread() {
    let e = 0;
  	document.querySelectorAll(".notification-badge__count").forEach((n) => {
  	    n.parentElement.parentElement.parentElement.href === 'https://www.linkedin.com/notifications/' && parseInt(n.innerText) && (e += parseInt(n.innerText));;
	}),
    updateBadge(parseInt(e));
}
function updateBadge(e) {
    e && e >= 1 ? rambox.setUnreadCount(e) : rambox.clearUnreadCount();
}
setInterval(checkUnread, 3e3);


```

**Comment by Albirew** [comment]
sorry, i forgot to specify "it was working before linkedin implement the new skin", still thanks (in app.js, right?) =)
