### ISSUE TITLE
Unable to scroll down to see the complete list of options

### ISSUE THREAD

**Issue by The1Gr8Scott** [ramboxapp/community-edition#2918]
Fresh install and I can't scroll down to see the complete list of options.  Also, I quit and restarted, and still doesn't work.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.8.0-29-generic

**Comment by fvulich** [comment]
Could you elaborate a bit further on your issue? Could you share some screenshots? Or even better a video. Also include your Linux distribution & the package that you used to install Rambox.

**Comment by The1Gr8Scott** [comment]
Linux Distro: Ubuntu 20.10 Gnome 3.38.1
 https://u.pcloud.link/publink/show?code=XZj4iLXZOqsK3O5VCLYd6t7FOcCAJzrI9eWX (Link to the video)

![2020-12-06_19-10](https://user-images.githubusercontent.com/420802/101301769-77bd1280-37ff-11eb-8084-a35e2a212703.png)

**Comment by fvulich** [comment]
What package are you using? Could you try with a different one? Because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

**Comment by The1Gr8Scott** [comment]
It's working now and I think I now know what I was doing wrong.
Apparently, you have to click while scrolling, at least that's the
discovery I recently made.  Thanks for all your help and I plan to
contribute to your efforts shortly and perhaps even become a Pro member.

Again, thanks,

**Comment by fvulich** [comment]
Glad to hear that! Have a nice day!
