### ISSUE TITLE
Telegram: Sticker not visible, not supported on your version of Telegram Web

### ISSUE THREAD

**Issue by francwalter** [ramboxapp/community-edition#2919]
Hallo
I have on my Mac OS 10.11.6 Rambox 0.7.7  :

Version: 0.7.7
Platform: darwin (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

In Rambox I have the Telegram service and every time when I get a sticker, it is not displayed but instead I read:

> Diese Nachricht wird von Telegram Web Version noch nicht unterstützt. Benutze stattdessen getdesktop.telegram.org.

It is german and I think it is translated from: 

> The message is not supported on your version of Telegram Web ...

I searched about this issue but cannot find it. Maybe the translation is wrong. 
Is it wellknown anyway?
Is there something I can do to display Stickers in Rambox's Telgram?

Thanky
frank

**Comment by fvulich** [comment]
Sadly, the Telegram's web app doesn't have that option (you can try https://web.telegram.org/ in Chrome) but as soon as they make possible to use animated stickers in their web app you'll have them in Rambox
