### ISSUE TITLE
My Rambox shows no sign of incoming messages below taskbar.

### ISSUE THREAD

**Issue by dovietnguyenlk** [ramboxapp/community-edition#2922]
My Rambox shows no sign of incoming messages below taskbar.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
We don't fully understand your issue. Could you elaborate a bit further? Some screenshots of the issue will help a lot.
