### ISSUE TITLE
Skype will not detect my webcam for calls. My cam works in non-Rambox apps

### ISSUE THREAD

**Issue by Atri7** [ramboxapp/community-edition#2923]
Hi,
I use Skype through Rambox for work. During a group call last night, I realized that Skype cannot detect my laptop-s built-in webcam. I'm not sure what the problem is -- Firefox and Cheese work fine. I have a Dell Inspiron 7000 Gaming Edition.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.8.0-31-generic

**Comment by fvulich** [comment]
If you are using snap, please check the Rambox permissions in the Snapstore. Or you could try using another package, you can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
