### ISSUE TITLE
No access to Duo

### ISSUE THREAD

**Issue by Dedjou59** [ramboxapp/community-edition#2924]
Hello everyone,
I can't use Goggle Duo on Rambox any more. When I try to connect, it says "sorry you don't have access to your service, contact the administrator of your organisation"... I've always used the same account.
I've changed mobile phones and reconnected to Duo on it.
Thank you for your help!

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
Duplicate #2914
