### ISSUE TITLE
Your popup is too small to display this page. Please enlarge it to proceed.

### ISSUE THREAD

**Issue by beamkiller** [ramboxapp/community-edition#2925]
### Steps to reproduce

1.  Try to sign up
2.  With Facebook I got the following message.
3.  Your popup is too small to display this page. Please enlarge it to proceed.

I cannot enlarge to windows. Cant maximaze and there are no rulers to drag the sides or corner to increase the size.

### ENVIRONMENT

> OS: Windows 10 Pro 64-bit
Version: 0.7.7
Platform: win32 (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by fvulich** [comment]
We don't fully understand your issue. Could you elaborate a bit further? Some screenshots of the issue will help a lot.
