### ISSUE TITLE
FB Messenger search issues

### ISSUE THREAD

**Issue by nheinemans** [ramboxapp/community-edition#2926]
### Steps to reproduce

1. Type a word in the search bar
2. FB messenger only shows pages/people, but doesn't show results for the search inside conversations.

### Expected behavior

It used to show results in conversations.

### Actual behavior

FB messenger in Rambox doesn't show any results in conversations

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Windows 10

> Arch: x64

**Comment by fvulich** [comment]
We couldn't reproduce your issue, it works as it should. Could you try with the same account if it works in Chrome? Also, you could try deleting the messenger app and adding it again.

**Comment by nheinemans** [comment]
I can reproduce the issue in chrome. When typing a word in the search bar, I expect to get results from my chats. This worked fine before, but I now only see people/pages in the results. It still works as expected in the messenger app on my phone.

**Comment by fvulich** [comment]
Seems that your account has an issue (because you can reproduce it in Chrome). Please refer this issue to the Messenger support.
