### ISSUE TITLE
Mistake Warning / Sync is not possible!

### ISSUE THREAD

**Issue by dakoenma** [ramboxapp/community-edition#2927]
Mistake Warning / Sync is not possible!
![No-Sync-Possible](https://user-images.githubusercontent.com/56632005/102201330-3c3cdb00-3ec6-11eb-9680-6be8e0bc71d2.jpg)

What can I do?

Best regards, Mathias (remail@mkoenig.eu)

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> darwin x64 20.1.0

**Comment by fvulich** [comment]
Please check if this can help you out. https://github.com/ramboxapp/community-edition/issues/1932#issuecomment-639763615

Also Duplicate #1932

**Comment by dakoenma** [comment]
The problem isn‘t silved yet!

The sync is still not possible!

BR, Mathias 



_________________________________

Mathias König
mobile & sms: +49 151-41415219
eMail: mail@mkoenig.eu

Truderinger Straße 348
D - 81825 München
phone: +49 89 20038442
fax: +49 89 20035475

**Comment by dakoenma** [comment]
The problem isn‘t solved yet!

The sync is still not possible!

BR, Mathias 



_________________________________

Mathias König
mobile & sms: +49 151-41415219 <tel:+49%20151-40517777>
eMail: mail@mkoenig.eu <mailto:mail@mkoenig.eu>

Truderinger Straße 348 <x-apple-data-detectors://1/0>
D - 81825 München <x-apple-data-detectors://1/0>
phone: +49 89 20038442 <tel:+49%2089%2020038442>
fax: +49 89 20035475 <tel:+49%2089%2020035475>
