### ISSUE TITLE
Scrolling does not function properly

### ISSUE THREAD

**Issue by The1Gr8Scott** [ramboxapp/community-edition#2928]
While trying to add a new service by scrolling through the available list the scroll does not allow you to properly scroll.  Also, while trying this on Linux (Ubuntu 20.10 - Gnome 3.3.8) I discovered that I had to click and scroll in combination.  In my opinion, that's a cumbersome and non-intuitive approach to design because I have never used any other app that required quite that level of complexity to do something as simple as scrolling.  Nevertheless, this is repeated in my experience on Windows 10 Home.  If at all possible, my suggestion is just to make a persistent scrollbar(s) that allows users to click and scroll or at least the option to turn that feature on or off.  Finally, after maximizing and restoring to the original window size and using the search feature did the scrolling functionality return.  I am having a hard time consistently replicating this issue, but I am submitting it because I think that it's important enough to bring to your attention.  The scrolling functionality on this app on two totally different platforms (Linux and Windows) has been problematic for me.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
We couldn't reproduce your issue either in windows 
![image](https://user-images.githubusercontent.com/46904390/102996919-b393ef80-4502-11eb-8a9c-f63e3f59e16a.png) 
nor Ubuntu
![image](https://user-images.githubusercontent.com/46904390/102999589-0ae88e80-4508-11eb-9764-cc59a7249678.png)


Could you share some screenshots of your issue or even better a video?
