### ISSUE TITLE
Feature Request: Delete Selected Services

### ISSUE THREAD

**Issue by monkeylove** [ramboxapp/community-edition#2932]
Please include an option to delete selected services that have been disabled.

**Comment by fvulich** [comment]
Could you elaborate a bit further on your request?

**Comment by monkeylove** [comment]
I add the Reddit Chat as a new service but change my mind. To delete the service, I can only use the "Remove all Services" option but it removes everything. Is there a way to remove only selected services?

**Comment by bkimmett** [comment]
This feature already exists in Rambox. 
When you mouse over a service in the 'Enabled Services' area, a button to delete the service you are mousing over will appear.

**Comment by monkeylove** [comment]
I didn't see it because I skinned Rambox to make it dark mode. The skinning isn't perfect because it darkened the buttons to the left of the check box. Sorry about that!
