### ISSUE TITLE
Icons Not Loading

### ISSUE THREAD

**Issue by eliyahillel** [ramboxapp/community-edition#2934]
The Icons are not loading sometimes, I couldn't understand when exactly. It happens to me on latest windows 10 and also on Linux mint 20... image attached 

![image](https://user-images.githubusercontent.com/73447394/103812945-f22fbb00-5067-11eb-9b4c-92b9ebdc7832.png)

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
It seems that your ISP is blocking Firebase storage, we don't know why. Could you try this link and share with us what happen?

​[Icon](https://firebasestorage.googleapis.com/v0/b/rambox-d1326.appspot.com/o/services%2F10000ft.png?alt=media)​​​​

You should see this
![image](https://user-images.githubusercontent.com/46904390/104218307-51504f80-541b-11eb-980d-8fcc42907390.png)

**Comment by eliyahillel** [comment]
> It seems that your ISP is blocking Firebase storage, we don't know why. Could you try this link and share with us what happen?
> 
> ​[Icon](https://firebasestorage.googleapis.com/v0/b/rambox-d1326.appspot.com/o/services%2F10000ft.png?alt=media)​​​​
> 
> You should see this
> ![image](https://user-images.githubusercontent.com/46904390/104218307-51504f80-541b-11eb-980d-8fcc42907390.png)

Thanks for the replay.
The icon in the link works just fine. I don't think that it's on the ISP level because it happens both on my home network and on my phone's hotspot...
Maybe I can somehow reset the icons cache or something like that?

BTW, since I opened that issue here it didn't came back to itself even once.

**Comment by eliyahillel** [comment]
So I have some more info:
you can see here that there are some icons that do work (like Facebook which is a "custom service"), but Gmail and WhatsApp don't, and you can also see that there are some buttons icons missing in the software itself (like the remove button)

I also tried removing and re-adding the "Android Messages" service (which I can see it's icon in the main page) but on the bar it was blank again.

![image](https://user-images.githubusercontent.com/73447394/104257247-ac1e9100-5485-11eb-8dc4-5124490e6497.png)

**Comment by fvulich** [comment]
Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

**Comment by eliyahillel** [comment]
> Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
> ![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)

Oh thanks! that's exactly the option I was looking for. The services icons are back but the "remove" button is still invisible.

**Comment by fvulich** [comment]
Could you try uninstalling Rambox and before installing  it again deleting the content of this folder?

%USERPROFILE%\AppData\Roaming\Rambox\
