### ISSUE TITLE
Always logged out from Discord on every new Rambox start

### ISSUE THREAD

**Issue by mhatvan** [ramboxapp/community-edition#2935]
### Steps to reproduce

1. Restart Rambox
2. You will be logged out in your Discord tab

### Expected behavior

Stay logged in on any Discord windows

### Actual behavior

User has to reenter his credentials and log in on any Discord windows fater new Rambox application start

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Ubuntu 20.10

> Arch: x64

**Comment by fvulich** [comment]
I also experience something like that with Discord. It seems that when you get logged from many browsers (Chrome, Firefox and also Rambox Pro), Discord logs you out once a while. Now I only use Discord from Rambox and always stay logged. Also, to solve this behavior I deleted the Discord app and add it again.

**Comment by Regala** [comment]
Can confirm this issue still persists, e.g. if I close Rambox (which I do often to have no notifications / red notification icon) Discord constantly logs out :(

**Comment by Telkhine** [comment]
This is still an issue. Discord also automatically logs out when you put the computer to sleep, then wakes up.
