### ISSUE TITLE
Rename Hangouts Chat to Google Chat

### ISSUE THREAD

**Issue by ricardo-mello** [ramboxapp/community-edition#2939]
Last year Google has rebranded Hangouts Chat to Google Chat. I think that we should rename the service on Rambox to keep consistency.

If you agree with it, I can open a PR changing the name. Just let me know 😃 

Source: https://www.theverge.com/2020/4/9/21215588/google-chat-hangouts-meet-g-suite-name-change-rebranding

**Comment by fvulich** [comment]
Thanks for the head's up. I also updated the logo.

https://github.com/ramboxapp/community-edition/commit/b9006c2f508cb0af44bbdb62e6db7519959016ae

**Comment by ssbarnea** [comment]
Last release was more than 6 months ago so nobody was able to benefit from this change. With the rage of service deprecations at Google I wonder if we may need to rename it again by the time a release is made.
