### ISSUE TITLE
Settings Dialog on left bottom corner when opening second time

### ISSUE THREAD

**Issue by francwalter** [ramboxapp/community-edition#2943]
Hallo
I am using Rambox Free version on Mac 10.11.6 and Windows 10 (64-Bit, Enterprise and Home). On both systems there is a bug in the latest Rambox version 0.77:
I open the settings of Rambox himself or of any service and the settings dialog is centered in the middle, which is good.
Then I close that dialog and the next time I reopen any setting, the dialog is in the left bottom of the window but too much at the bottom, so that the buttons are invisible.
I have to restart Rambox now to make any settings again, because I cannot save in the broken dialog.

Here is a screenshot:

![grafik](https://user-images.githubusercontent.com/927269/104919526-af8aae80-5996-11eb-8bfe-b32862e6bdc5.png)

I thought that it could be related to my login, so I logged out from my rambox account, but the only difference is, that I lost all my services, they are attached to my account (which I consider as a bug too).

I expect Rambox to open the settings dialogs any time at the same spot, visible and usable.

Beside of this, when I change settings, often the Icons of my services disappear all, so I cannot use the other services anymore and have to restart Rambox as well.

frank

**Comment by fvulich** [comment]
That'st really odd, and I couldn't reproduce it neither in Windows nor Linux (I couldn't test it in macOS). Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services)  because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

**Comment by francwalter** [comment]
I have problems with the account too, see #2944 
I get the error:

 `Error occurred when trying to backup your configuration.`

So maybe best would be to clear all data in the account but I dont think that is possible now (with this error).
If I cannot keep all the installed services, when logging out it is no option.
Then I rather live with these bugs.

**Comment by francwalter** [comment]
OK, on  my Windows 10 (64) tablet, I cleared everything, deleted all Rambox directories, downloaded it (0.77 64bit) again, installed (without this buggy Rambox-Login) Telegram and WhatsApp and wanted to add schul.cloud but again the dialog for a new service (custom service) now is in the left bottom, unusable, look:

![grafik](https://user-images.githubusercontent.com/927269/105608816-91adb700-5da5-11eb-888d-48204e3a4bc9.png)

![grafik](https://user-images.githubusercontent.com/927269/105608822-98d4c500-5da5-11eb-837f-77bca238273f.png)

Rambox is very buggy :(

**Comment by francwalter** [comment]
Now, after reading and searching a while, all is clear: the Rambox community edition is not under real development so bugs wont be fixed. Good to know, I found [Hamsket](https://github.com/TheGoddessInari/hamsket), a fork under development and without this buggy Rambox login. Backup is made on disk, thats it.
Here a description of the fork: [Question: Original Rambox vs Fork?](https://github.com/TheGoddessInari/hamsket/issues/67)
Goodby Rambox 😄
