### ISSUE TITLE
"Trust invalid authority certificates" not working

### ISSUE THREAD

**Issue by wonkieinc** [ramboxapp/community-edition#2945]
When I add a site with a self-signed cert, I cannot access this within Rambox
	
	This issue is still present after installing the cert on my system so that all browsers trust without warning
	
	
	
	-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
Did you try this setting?
![image](https://user-images.githubusercontent.com/46904390/105501657-414e3080-5ca3-11eb-948f-a4e9db603e80.png)

**Comment by wonkieinc** [comment]
Yes, I tried that setting and it did not make a difference

**Comment by fvulich** [comment]
Duplicate #2571
