### ISSUE TITLE
Electron update to 8/9/10: Skype's call/video calls stop working 

### ISSUE THREAD

**Issue by fvulich** [ramboxapp/community-edition#2947]
We are working on update the Electron of Rambox to a newer version, but when we do this update the call/video calls functionality  of Skype cease working.  We open this issue in part to explain why we are delaying the merge of #2897 but mostly to share this concern with the community and ask for help to find a workaround for this.

The issue consists in that Calls and Video-calls are not supported due Skype restriction to only work in Edge and Chrome, it doesn't in Firefox nor Vivaldi either.

**Comment by wpehrc** [comment]
Does simply spoofing a Google Chome UA work?

**Comment by fvulich** [comment]
Sadly, no.

**Comment by mhatvan** [comment]
Any updates on this? Quite a lot of time passed...

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it, and Skype calls are also working). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
