### ISSUE TITLE
Prevent right alt from activating the menu?

### ISSUE THREAD

**Issue by arielsalvo** [ramboxapp/community-edition#2949]
Is it possible to prevent the menu from activating when hitting the right alt key?
That's my hotkey for [Keyferret](https://www.keyferret.com/) and I end up closing Rambox unintentionally.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
It seems to be a very specific case, don't seem to be a good choice for everyone.
