### ISSUE TITLE
Rambox window not appearing in Big Sur

### ISSUE THREAD

**Issue by drsjb80** [ramboxapp/community-edition#2952]
### Steps to reproduce

1. Run /Applications/Rambox.app/Contents/MacOS/Rambox 

### Expected behavior

Rambox appears.

### Actual behavior

Rambox does run and I do see the menu, but no window appears. This appears to have coincided with an OS upgrade.

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Darwin MS200667 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

> Arch: x64

From the command line, these warnings are shown but probably not the issue:
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
(electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
(electron) 'setAudioMuted function' is deprecated and will be removed. Please use 'audioMuted property' instead.
(electron) 'setZoomLevel function' is deprecated and will be removed. Please use 'zoomLevel property' instead.

In the console I find:
Jan 31 08:00:15 MS200667 Rambox Helper (GPU)[9658]: getattrlist failed for /System/Library/Extensions/AppleIntelKBLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsGLDriver: #2: No such file or directory
Jan 31 08:00:15 MS200667 Rambox Helper (GPU)[9658]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory

A question: where is the configuration of services stored in OSX? I'm leaving the dumpster fire that is OSX but would like to know all the services I had set up in Rambox. Love Rambox. Thanks!

**Comment by fvulich** [comment]
That's odd, please try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

**Comment by drsjb80** [comment]
It is very odd. Did the clean install and reinstalled and no better. I'm good if we close this, I might well be the only person experiencing it and I'm moving to Rambox on Linux. Thanks!

**Comment by teundirectlease** [comment]
> It is very odd. Did the clean install and reinstalled and no better. I'm good if we close this, I might well be the only person experiencing it and I'm moving to Rambox on Linux. Thanks!

I have the same issue. Sometimes the window just dissapears and only the full screen options shows it.

**Comment by drsjb80** [comment]
So what I found on OSX is that if I mistakenly hit command-w there is no menu option to bring the normal window back, only full-screen seems to work. Many OSX applications have a command-1 or similar to bring the main window back, but Rambox doesn't. Going full-screen and then exiting full-screen works, but is a bit clunky and non-obvious.
