### ISSUE TITLE
Installation canceled

### ISSUE THREAD

**Issue by ziiCz** [ramboxapp/community-edition#2953]
Hi there,

I can't install last rambox version (0.7.7).

The install tool tell me that there already are an installed version at "C:\Users\USERNAME\AppData\Local\Programs" but there are no folder. Nothing.

How can I resolve this problem ?

Thanks

**Comment by fvulich** [comment]
Could you check with this program after you uninstall Rambox if there's a corrupted installation or anything related to Rambox?
The program is called Bulk Crap Uninstaller, it is free and open source : https://www.bcuninstaller.com/
