### ISSUE TITLE
Feature Request: mute only notifications sounds

### ISSUE THREAD

**Issue by Rij29** [ramboxapp/community-edition#2954]
Hi, I love using Rambox, but there is no option to simply mute the notifications. I can only mute all sounds completely.

I don't know Java, if anyone here would be willing to help me with a small code which can mute only the notification sounds of an app, that would be great! Thanks a ton!

Else, it would also be great if there was such an option inbuilt.

**Comment by fvulich** [comment]
If you want to explore a way to make this possible whilst the notification sound is still muted I suggest you to try something in the /resources/js/rambox-service-api.js file. Something like override the silent property of the options object of the notification. I couldn't test this but seems to be a good starting point.
