### ISSUE TITLE
bug at the whastapp scroll bar within the conversations

### ISSUE THREAD

**Issue by wills-jamerson** [ramboxapp/community-edition#2955]
### **STEPS TO REPRODUCE**
Added Whatsapp
Scroll down to a conversation (preferably in groups) that has some new messages

### **ACTUAL BEHAVIOR**
Scrolling bar locks temporarily while scrolling (down, and sometimes up) through some new messages in whatsapp chats

### **EXPECTED BEHAVIOR**
Getting navigated through conversations without the scroll bar locking

### **obs:** 
I tested several versions and if my memory serves me correctly, starting with version 0.6.4 or below, this type of problem does not happen. In the Franz application that is similar to this software I don't have that kind of problem.
![image](https://user-images.githubusercontent.com/78479811/106742204-79d30000-65fb-11eb-80f2-9e044f7ba2b1.png)
(tested with several others pc also)

**### ENVIROMENT:**
![image](https://user-images.githubusercontent.com/78479811/106741852-05985c80-65fb-11eb-8650-02d60f17b3d2.png)
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
We couldn't reproduce your issue. I leave this open because there's a chance that other users can reproduce it.
