### ISSUE TITLE
Links that open in a new window do not work because they lose authentication.

### ISSUE THREAD

**Issue by wvrocha** [ramboxapp/community-edition#2959]
Exchange OWA functions that open in a new window do not work because they lose authentication.
         Like writing an email for example. This option opens in a new window and asks for new authentication in Rambox / Chromium

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
Related #2677

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
