### ISSUE TITLE
Custom Service do not load on evernote login

### ISSUE THREAD

**Issue by vmendezg** [ramboxapp/community-edition#2967]
Before evernote version 10.8.4-web, you can load evernote on rambox as a custom Service, but now if you try to login, rambox do not load anything.

**Comment by fvulich** [comment]
Evernote needs Chromium > 84, this issue will be fixed once we update Electron

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
