### ISSUE TITLE
Messenger buggy display

### ISSUE THREAD

**Issue by T4mmi** [ramboxapp/community-edition#2970]
Hi, I have random display problems with messenger (only messenger, other services are fine).

The central part (dicussion panel) is not fully displayed, it misses either the header (conversation name, not so enoying) either the "reply" part where you type your messages... (more enoying).
It seems to be existant since some tricks makes invisible parts reappear (link clicking on reply that shows the top of the input bar) or reload the whole messenger service.

Thanks

**Comment by Julusian** [comment]
I have been hitting this too, but only the reply box and last few messages being hidden and no way to scroll.

I have found that collapsing the 'Shared files' and 'Shared photos' sections in the right bar cause it to be displayed properly

**Comment by fvulich** [comment]
We are investigating this issue, seems to be an issue that will get fixed with an Electron update.
