### ISSUE TITLE
No more sound

### ISSUE THREAD

**Issue by kira0269** [ramboxapp/community-edition#2972]
I don't have any sound from services from Rambox

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
Please check if you have the "Do not disturb" feature on, if it's ON you'll not hear any sound from Rambox CE
![image](https://user-images.githubusercontent.com/46904390/78381741-2db6c980-75ac-11ea-840a-b2cfcdc37899.png)
Also, check this in the app config
![image](https://user-images.githubusercontent.com/46904390/78389795-c43db780-75b9-11ea-8f7c-7871343c54f7.png)

**Comment by kira0269** [comment]
Ok, my mistake... ^^"
I close the issue, thanks :)
