### ISSUE TITLE
Missing Service Names

### ISSUE THREAD

**Issue by louisjjjames** [ramboxapp/community-edition#2974]
On reboot, the "Service name in Tab" disappears.  I have to go and edit the service and then click "edit (service name".  It is already checked off "Show service name in Tab".  In other words, the "Show service name in Tab" is always checked but on reboot, it does not show the service name.  

Not all services use the "Show service...." 

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
Uncheck this in general preferences
![image](https://user-images.githubusercontent.com/46904390/110125212-d44db080-7da1-11eb-8524-5c640ee58056.png)
