### ISSUE TITLE
Auto sync changed services across devices

### ISSUE THREAD

**Issue by mhatvan** [ramboxapp/community-edition#2976]
### Expected behavior

It would be helpful if Rambox could detect when a new service is added and syncs the configuration in the background.

### Actual behavior

I need to remember whenever I added a new service to synchronize the configuration, so that I am able to use it fast on another computer.

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Ubuntu 20.10

> Arch: x64

**Comment by fvulich** [comment]
We have this feature among other cool ones in our Pro version. We have a 30 days free trial. You can learn more of it in our [WEB](http://rambox.app/) and download it from [HERE](https://github.com/ramboxapp/download/releases/latest)

**Comment by mhatvan** [comment]
Ok, thank you for the heads up!

I actually downloaded Rambox Pro recently and wanted to get started with it, but didn't receive any emails for my created account or to forgot password functionality.
