### ISSUE TITLE
Discord's video conference screen sharing functionality isn't working using Rambox

### ISSUE THREAD

**Issue by JoaoPauloAntunes** [ramboxapp/community-edition#2979]
Discord's video conference screen sharing functionality isn't working using Rambox. When I need to use this functionality, I'm having to open Discord in the browser, instead of using Rambox.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.11.6-arch1-1

**Comment by fvulich** [comment]
Related #2842

**Comment by bkzshen** [comment]
Ram box 0.7.9 still can't share screen on Discord
