### ISSUE TITLE
Rambox Start-up time

### ISSUE THREAD

**Issue by christo070** [ramboxapp/community-edition#2980]
The system without enabling 'start automatically on startup' is taking around 5.5 seconds for 'last bios startup time' whereas after enabling 'start automatically on startup', it takes around 20.1 seconds. It would be nice if the developers could reduce startup time of rambox as opening rambox just after computer startup takes less time than 'start automatically on startup'.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
Doesn't seem a critical task, but we are always open to any PR.
