### ISSUE TITLE
Guilded

### ISSUE THREAD

**Issue by rauldipeas** [ramboxapp/community-edition#2986]
Web address: https://guilded.gg
Icon: ![](https://cdn-images-1.medium.com/max/280/1*vCc1TiaN1QAZKRptiEgP1Q@2x.png)
Notification badge:
```
???
```

**Comment by fvulich** [comment]
Guilded added https://github.com/ramboxapp/community-edition/commit/575bfda26893d72acc487776bce3b3c74237c011
