### ISSUE TITLE
Telegram is not syncing

### ISSUE THREAD

**Issue by Ghedeon** [ramboxapp/community-edition#2988]
### Steps to reproduce

1. Add Telegram service
2. Leave it running for a while

### Expected behavior

Telegram is in sync and delivers new messages

### Actual behavior

Telegram silently stops synchonizing and is in stale state. You have to restart it manually in order to trigger the get it in sync.

### ENVIRONMENT

Version: 0.7.7
Platform: darwin (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
OS: macOS BigSur 11.2.3

**Comment by fvulich** [comment]
We couldn't reproduce this. Could you try deleting the Telegram app and adding it again?
