### ISSUE TITLE
Bug: Android Messages Notification

### ISSUE THREAD

**Issue by 8227846265** [ramboxapp/community-edition#2991]
### Steps to reproduce

1. Received any SMS on Android Messages
2. Upon reading the SMS
3. The Notification Number on the Android Messages doesn't go down
![image](https://user-images.githubusercontent.com/66582769/113975440-1622b880-9872-11eb-8bc1-b01b57d0c960.png)

### Expected behavior

Android Messages Notification Number will be cleared

### Actual behavior

Android Messages Notification Number get stucks

### ENVIRONMENT

Version: 0.7.7
Platform: win32 (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by fvulich** [comment]
I couldn't reproduce your issue, Once I marked as read to all my messages the badge disappear as it should. Check if you didn't miss one.

**Comment by 8227846265** [comment]
You're right, it seems I have missed 1 unread SMS from a long time ago. My bad.
