### ISSUE TITLE
Keyboard shortucts cannot be disabled

### ISSUE THREAD

**Issue by warrado** [ramboxapp/community-edition#2992]
### Steps to reproduce

1. Go to "View" -> "Shortcuts" and uncheck the checkbox next to any shortcut (e.g. "Last App `Ctrl Ctrl`), press "Save and Close" button
2. Pres the shortcut keys, this will perform the shortcut action (e.g. take you to the last app)
3. After a minute or so open the "View" -> "Shortcuts" window again, the checkbox next to the shortcut is checked again

### Expected behavior

The shortcut should stay inactive. Pressing the shortcut keys doesn't do anything.

### Actual behavior

Even when disabling the shortcut, it will stay active. The UI will also show the shortcut as active, though after some delay.

### ENVIRONMENT

> Rambox: Pro v1.5.0

> OS: Ubuntu linux 20.04 LTS (kernel 5.4.0-66-generic x86_64)

> Arch: x64

Sorry if that's the wrong place to file an issue with Rambox Pro, but I couldn't find any other place.

**Comment by fvulich** [comment]
First of all, please use our [Support Portal](https://support.rambox.app/) to report your Rambox Pro issues.

We apologize for this inconvenience. Seems that the "Settings" file is corrupted or something. Could you try closing Rambox Pro and deleting it?

It must be in one of these folders depending on the Package that you use.​
Linux (deb, AppImage): ~.config\RamboxPro\
Linux (snap): ~\snap\ramboxpro\current\.config\RamboxPro\

If that doesn't work can you try doing a Clear Cache and a Clear Local Storage and then restart Rambox Pro?
![image](https://user-images.githubusercontent.com/46904390/114190488-bd125d80-9921-11eb-88e6-211ea56edb6b.png)



If that doesn't work, try uninstalling Rambox Pro by [following this tutorial](https://rambox.freshdesk.com/solution/articles/42000051684-how-to-uninstall-rambox-pro-) and then install the latest version of Rambox Pro by downloading it from [HERE](https://github.com/ramboxapp/download/releases/latest).

Please contact us again if none of those steps doesn't work, so we can give you more help.
