### ISSUE TITLE
How to recover Master Password

### ISSUE THREAD

**Issue by Lakshmikanth999** [ramboxapp/community-edition#2995]
### Steps to reproduce

1. 
2. 
3. 

### ENVIRONMENT

> Rambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

**Comment by fvulich** [comment]
Find config.json, open it and set master_password to blank

Locations: 

Windows
C:/Users/your_user/AppData/Roaming/Rambox

macOS
/Users/username/Library/Application Support/Rambox

Linux
~/.config/Rambox
