### ISSUE TITLE
No sound in Appimage version

### ISSUE THREAD

**Issue by dambito** [ramboxapp/community-edition#2996]
### Steps to reproduce

1. Have PC with multiple sound outputs (back, front, hdmi monitors with repro)
2. Receive 
3. Play message

### Expected behavior

Sound directed to default sound output. (or actual selected)

### Actual behavior

Sound redirected to, don't know where because not even monitors are playing.

### ENVIRONMENT

> Rambox: ./Rambox-0.7.7-linux-x86_64.AppImage 

> OS: 20.04.1-Ubuntu

> Arch: x64

### Comment
Nice to have: switchable sound outputs, but I know it's not media player.
I don't know much about how Appimage works, but would be willing to learn to know why it doesn't use correct sound output.

**Comment by fvulich** [comment]
Please check if you have the "Do not disturb" feature on, if it's ON you'll not hear any sound from Rambox CE
![image](https://user-images.githubusercontent.com/46904390/78381741-2db6c980-75ac-11ea-840a-b2cfcdc37899.png)
Also, check this in the app config
![image](https://user-images.githubusercontent.com/46904390/78389795-c43db780-75b9-11ea-8f7c-7871343c54f7.png)


Also, could you try with another package (Snap, deb)?
