### ISSUE TITLE
2 Features Requests

### ISSUE THREAD

**Issue by JOduMonT** [ramboxapp/community-edition#3007]
I love Rambox and I use it since a very long time but I'm also amaze by those features proposed by others MultiApps App such Stack and I wonder if it would be possible to integrate them in Rambox or RamboxPro

- **Chrome extension**: and it would be great, such as being able to use Grammarly and/or ProWritingAid
- **2 services bars location**: 1 horizontal and 1 vertical

**Comment by fvulich** [comment]
There's another ticket opened for the Chrome extensions, and for the two-service bar, it's not in our plans to make this happen, but PRs are always welcome.
