### ISSUE TITLE
Gitter: Sign in with gitlab causes grey background, refreshing the tab then quits / crashes Rambox

### ISSUE THREAD

**Issue by dantronik-markus** [ramboxapp/community-edition#3010]
### Steps to reproduce

1. Create a new Gitter service, wait for the tab to load.
2. Click the "Sign in to start talking" button, then click "Sign in with Gitlab".
3. Wait for the page to load, after some time, a grey background is displayed.
4. Right-click the Gitter tab, select "Refresh" from the context menu.

### Expected behavior

Rambox shouldn't crash, nor should it display a grey background

### Actual behavior
Sign in with Gitlab works.

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Windows 10

> Arch: x64

**Comment by fvulich** [comment]
It seems that this option it's not available in our current Electron version. Once we update it, this should be sorted.
Related #2947

**Comment by fvulich** [comment]
0.7.8 Released. You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
Is this issue still reproducible in it?
