### ISSUE TITLE
Help Needed: Facebook unreadCode.

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#3013]
Well, sometimes it works, but more often than not, it doesn't. I receive messages on Facebook messenger, I get notifications on the phone but Rambox remains oblivious, I have to go to the tab to check the messages by myself. The badge in the tray doesn't become red, the red balloon of new messages doesn't appear... You get the idea.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 6.1.7601

**Comment by fvulich** [comment]
As Facebook isn't a preconfigured service, Rambox takes the badges from the page's title. If you want you can add a custom JS script to update the badges. Here I leave you the Android Messages's one as an example.

```
function checkUnread() {
    var a = 0;
    document.querySelectorAll(".text-content.unread").forEach(function (b) {
        b.querySelector(".notifications-off") || a++;
    }),
        updateBadge(a);
}
function updateBadge(a) {
    1 <= a ? rambox.setUnreadCount(a) : rambox.clearUnreadCount();
}
setInterval(checkUnread, 3e3);

```

This [LINK](https://github.com/ramboxapp/community-edition/wiki/Inject-JavaScript-Code) will help you out on how.

**Comment by 613TheEvil** [comment]
Thank you. So I just copy this code in the Configure tab, under Advanced, where it says custom code, yes? No need to add or change anything? Ok let's see.

**Comment by fvulich** [comment]
No, you have to tweak it to work with Facebook, I just provide you an example to give you a starting point.

**Comment by 613TheEvil** [comment]
Sorry, I am clueless, any idea how to tweak it?

**Comment by fvulich** [comment]
You can use the Messenger service to manage Facebook messages that has badges and notifications for new messages
