### ISSUE TITLE
Wechat no longer logging in.

### ISSUE THREAD

**Issue by assasukasse** [ramboxapp/community-edition#3015]
Trying to associate a wechat account results in an error on the phone.
Changing the user agent doesn't solve the issue, apparently there is also a cookie problem.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.10.0-5-amd64

**Comment by fvulich** [comment]
Can you try deleting the WeChat app and adding it again?

**Comment by assasukasse** [comment]
Done it a few times.
No change

**Comment by fvulich** [comment]
Sadly, it seems that WeChat is blocking connections to their web app from Chrome and other browsers. We're looking for a workaround.

**Comment by fvulich** [comment]
Sadly, it seems that WeChat is blocking connections to their web app from Chrome and other browsers. We're looking for a workaround.

**Comment by tazus** [comment]
I have the same problem.  Search China community who use Linux also have the same problem.  It seams need to enable these 2  websites: wx.qq.com wx2.qq.com  for cookies access by wechat.com.
But I can't find any settings in Radmbox.
