### ISSUE TITLE
Services bar background is now grey (instead of white)

### ISSUE THREAD

**Issue by desapar** [ramboxapp/community-edition#3016]
-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19041

**Comment by desapar** [comment]
![image](https://user-images.githubusercontent.com/49664543/118369785-53980580-b5d7-11eb-8f1d-e5f3da797ece.png)

**Comment by fvulich** [comment]
Deactivate Don't disturb to make it white again.
![image](https://user-images.githubusercontent.com/46904390/119144358-f6f57a00-ba1e-11eb-86a0-b77566331069.png)
