### ISSUE TITLE
Unable to log in to Telegram

### ISSUE THREAD

**Issue by fuzk23** [ramboxapp/community-edition#3018]
I am unable to log in to telegram. I am stuck at the sign in page. After entering my phone number AND verifying that it is indeed my number, it leads me BACK to the page where I am supposed to enter my phone number.
![Screenshot 2021-05-19 at 12 31 03 PM](https://user-images.githubusercontent.com/84432355/118756766-347ec980-b89e-11eb-8769-e21469201d3a.png)
![Screenshot 2021-05-19 at 12 32 20 PM](https://user-images.githubusercontent.com/84432355/118756892-7a3b9200-b89e-11eb-83f6-de9200b67c7d.png)

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> darwin x64 18.7.0

**Comment by fvulich** [comment]
I just checked and works as it should. Try deleting the telegram app and adding it again.
