### ISSUE TITLE
Slack requiring Chromium 82

### ISSUE THREAD

**Issue by infernix** [ramboxapp/community-edition#3019]
> Starting September 1, 2021, your team members will need to be on supported Desktop, Mobile and Browser versions to  continue using Slack. Your impacted team members will begin seeing in-product reminders starting June 2021.

> Browser Chrome Version: 82

Can we have a newer build with that version of chromium (or higher) soon?

Thanks!

**Comment by fvulich** [comment]
Yes, you are right, please comment in this PR https://github.com/ramboxapp/community-edition/pull/2897
