### ISSUE TITLE
Slack Stuck Notification Badge

### ISSUE THREAD

**Issue by dhancock07** [ramboxapp/community-edition#3021]
### Steps to reproduce

1. N/A

### Expected behavior

Clear tab/no notification

### Actual behavior

Persistant (1) notification (indicating direct message, mention, or tag). 

### ENVIRONMENT

Reproduced in linux and windows

> Rambox: v0.7.7

> OS: Fedora 32/Windows 10

> Arch: x64

Have tried stop/starting Rambox, Esc+Shift (clear workspace), completely removing tab/channel and re-adding to no avail. Opening the slack app and web version (chrome and FF) show no notifications as well.

**Comment by fvulich** [comment]
We checked this, and work as it should in our devices. But we are keeping an eye on it.

**Comment by dhancock07** [comment]
@fvulich thank you for checking. I've been using rambox for the last year or so with no issues or stuck notification badges. This is something that just started the last week and only for 1 of my slack tabs (4 more currently functioning with no issues/badges stuck) and I can't seem to get it to clear. Appreciate any help!

**Comment by dhancock07** [comment]
Another note: when I get a direct message/mention I get an audio notice (which is expected) but it's doubled, i.e. I hear the audio bell twice in quick succession.

**Comment by pdecat** [comment]
Apparently, drafts are now counted as unread messages in notifications.

**Comment by dhancock07** [comment]
@pdecat That was the issue! Deleted my draft message and the banner badge is finally gone. Thanks!

**Comment by pdecat** [comment]
This issue is really a regression that did not happen up until last week, and still does not happen when using Slack web, so it should probably not be closed.

**Comment by dhancock07** [comment]
Sounds good. Your timeline is correct, I have had several "Drafts" for months with no issues. Will reopen the issue.
