### ISSUE TITLE
F11 has no effect. Can't getting back from full screen

### ISSUE THREAD

**Issue by rocketrobin777** [ramboxapp/community-edition#3022]
by using full screen mode (Window/Toggle Full Screen) on Ubuntu 20.04.2 LTS it's not possible to change to normal view with F11 again. The only way is to restart Rambox. The F11 button has no function in normal view as well. Tested on Dell Latitude E5470

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.4.0-73-generic

**Comment by fvulich** [comment]
I just tested this in Ubuntu 20.04 and 18.04, and it works as it should. Does it work if you try this in the main section?

![image](https://user-images.githubusercontent.com/46904390/120808302-52476200-c51f-11eb-8a84-4d099bb7f871.png)

**Comment by rocketrobin777** [comment]
> Hey,


thanks for answering. It's a little bit embarrassing and I apologize for
disturbing, but I checked that I made a hotkey with F11 on my
Ubuntu-System. By changing it, Rambox runs as it should. So, we can close
for now ;-).

take care!

**Comment by fvulich** [comment]
Glad to hear that you could sort it out. Have a nice day!
