### ISSUE TITLE
Whatsapp is missing a calling option 

### ISSUE THREAD

**Issue by MichaelGoldshmidt** [ramboxapp/community-edition#3023]
The desktop Whatsapp app has an option of a voice call. 

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
If you try WhatsApp in the browser, it is still lacking that option, until they support it in their web app, there's nothing we can do in our end to provide it.

**Comment by MichaelGoldshmidt** [comment]
ok, thank you Fernando.
