### ISSUE TITLE
Rambox CE isn't respecting preferred applications

### ISSUE THREAD

**Issue by jason-mehmel** [ramboxapp/community-edition#3024]
I have been using Firefox and decided to switch to Chromium for my browser. When I switched I changed the default browser to Chromium inside Chromium and system settings.

(It is worth noticing that within Firefox it still thinks it's the default browser.)

### Steps to reproduce

1. Click on a link in Rambox

### Expected behavior

It would open in the new default browser (chromium)

### Actual behavior

It opens in Firefox instead.

### ENVIRONMENT

> Version: 0.7.7
Platform: linux (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

> OS: Ubuntu 20.04 - Xubuntu Desktop

> Arch: x64 or ia32

**Comment by fvulich** [comment]
This seems to be a system configuration issue, when Rambox is asked to open a link it asks the OS to open it and the OS provide the  default app for the type, in this case a link. If you ask me, it's very relevant that Firefox still thinks that it is the default browser, it seems to me that some settings may be clashing in your OS.

**Comment by jason-mehmel** [comment]
That was what was confusing; I double checked that I'd changed the default browser within the OS. But I'll check again!
