### ISSUE TITLE
Cannot Connect to Google Duo

### ISSUE THREAD

**Issue by Len-B** [ramboxapp/community-edition#3025]
This issue is still causing problems. I have tried numerous times to create a  Duo entry in Rambox (on two different PCs) and it always gives me the same error as the original poster. It seems that this failure is widespread and just needs your team to create a Gmail account and you'll almost certainly be able to reproduce it!

_Originally posted by @Len-B in https://github.com/ramboxapp/community-edition/issues/2914#issuecomment-854993133_

**Comment by fvulich** [comment]
Duplicate #2914 Just reopened #2914
