### ISSUE TITLE
Problem with microphone access discord

### ISSUE THREAD

**Issue by andersonscmota** [ramboxapp/community-edition#3026]
Steps to reproduce

1. Open Rambox
2. Open Discord
3. Open User Settings/Voice & Video

![image](https://user-images.githubusercontent.com/69721212/121229231-11738400-c864-11eb-8164-1ac2b4eca86b.png)

Expected behavior

Microphone from headset works

Actual behavior

Microphone not being picked up by Discord / Rambox

ENVIRONMENT

Free and Open Source messaging and emailing app that combines common web applications into one.
Version: 0.7.7
Platform: linux (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by fvulich** [comment]
Please ensure to give the proper permissions to the snap.
This link may help you out.
https://www.linuxandubuntu.com/home/snap-application-permissions

**Comment by andersonscmota** [comment]
That was the solution I found.
I used the reset voice settings button.
And it started working again.

![image](https://user-images.githubusercontent.com/69721212/123309433-4b4ab880-d4fb-11eb-919b-65c5573c4568.png)
