### ISSUE TITLE
Feature Request: Upload custom icons for groups

### ISSUE THREAD

**Issue by arildojr** [ramboxapp/community-edition#3030]
Hi,

Any possibility to support uploading custom icons for groups? So I don't need to use the existing ones in the app and instead use proper ones.

Thanks,

**Comment by fvulich** [comment]
This seems to be a Feature Request for the Pro version. This feature is already in our roadmap for future Rambox Pro versions. 
Also, this support channel is for Rambox CE users. If you are using Rambox Pro, please use our [Support Portal](https://rambox.freshdesk.com/) to report your problems, and we will help you there.
