### ISSUE TITLE
New version of telegram dosen't show notification

### ISSUE THREAD

**Issue by Fruschangbang** [ramboxapp/community-edition#3031]
### Steps to reproduce

1. Install rabmox
2.  activate telegram 
3. get a message

### Expected behavior
When a new message comes they should be a notification in the taskbar, and also in the tabs of the clients.

### Actual behavior
Telegram dosn't show any notification, with other messengers it works fine. ¨
The problem apeard today since the message to update to the new version of telegram web.

Edit: testet it also on Linux it's the same issue

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Windows 10, Linux Mint 20

> Arch: x64

**Comment by degoya** [comment]
same problem here too



    Rambox: v0.7.7

    OS: Windows 10

    Arch: x64

**Comment by SpookDroid** [comment]
+1   
Also, trying to revert to the old Telegram version within Rambox doesn't seem to be able to connect.

**Comment by degoya** [comment]
Still no notifications for me on 

```
Version: 0.7.9
Plattform: win32 (x64)
Electron: 11.4.10
Chromium: 87.0.4280.141
Node: 12.18.3
```

anything i need to do?
