### ISSUE TITLE
Whatsapp Web

### ISSUE THREAD

**Issue by jeandnava** [ramboxapp/community-edition#3033]
Whatsapp web is requiring an updated browser to work.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by SpookDroid** [comment]
I'm using Whatsapp right now and not seeing that error...

**Comment by jeandnava** [comment]
I think it was because of the latest whatsapp updates. It works sometimes and sometimes it doesn't. Order at least chrome 60.
