### ISSUE TITLE
Newest Telegram version does not trigger Windows notification anymore

### ISSUE THREAD

**Issue by xannasavin** [ramboxapp/community-edition#3035]
Telegram Web got an update some days ago. Though all notifications are on, it does not trigger the Windows notifications anymore like it did with the previous version.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19043
> Telegram web Z alpha 1.2.1

**Comment by fvulich** [comment]
Can you elaborate a bit further on your issue? Can you share some screenshots of it? How did you add Telegram?
