### ISSUE TITLE
Mac OS Big Sur / Rambox 0.7.7 > Teams missing settings & options

### ISSUE THREAD

**Issue by SeBr28** [ramboxapp/community-edition#3037]
### Steps to reproduce

1.  Add Teams to Rambox
2. Accept Microphone / Video change for Rambox
3. Make video/audio call

### Expected behavior

Normally you can change the webcam and/or mic settings. Also you can enable webcam filters (like blurred or diff. background)

### Actual behavior

There are NO settings (no devices tab) what so ever for cam/mic and thus also no Webcamfilters...
If you open the regular teams app (next to Rambox.. there you have everything right away..

### ENVIRONMENT

Platform: Darwin (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

Machine: Mac Mini M1 with Big Sur 11.4

WHAT WE SHOULD SEE:
![image](https://user-images.githubusercontent.com/86455299/123370726-978c0c00-d580-11eb-8935-0f6c35df69f7.png)

![image](https://user-images.githubusercontent.com/86455299/123370788-bdb1ac00-d580-11eb-8fb4-6db7250196ff.png)

IN RAMBOX:
![image](https://user-images.githubusercontent.com/86455299/123370836-d7eb8a00-d580-11eb-9ec9-7ae0ee35dd01.png)

**Comment by fvulich** [comment]
Those settings are only part of their desktop app, this screenshot is from Teams in Chrome.
![image](https://user-images.githubusercontent.com/46904390/123431442-a504be80-d59f-11eb-9690-a02f97569ea8.png)
As long as they don't provide it in the web version of the app, there's nothing we can do.
