### ISSUE TITLE
YOUR TRIAL PERIOD HAS EXPIRED

### ISSUE THREAD

**Issue by drumsmasher** [ramboxapp/community-edition#3041]
### Steps to reproduce

1. I've downloaded the community edition, and might click accidentally on start trial button, now my trial is expired and can't access rambox. It keeps saying "YOUR TRIAL HAS EXPIRED. To continue using Rambox, you have to subscribe to a plan or buy a Lifetime license"
2. 
3. 

### Expected behavior

There is no any "Go with Community Edition" button

### Actual behavior

I'm stuck here!

### ENVIRONMENT

> Rambox: v1.5.2

> OS: MacOS 11.4 (Big Sur)

> Arch: x64

**Comment by fvulich** [comment]
You are using the Pro version, the Pro and the CE version are two different applications, you can download it from [our web page](https://rambox.app/#ce) or from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by drumsmasher** [comment]
@fvulich  I tried the link you sent me, installed it and still have the same issue. I uninstalled everything, reinstalled from the link you sent me... and even created a new account with a different email and it says that my trial will finish in 30 days :-/
