### ISSUE TITLE
Slack not showing channel members

### ISSUE THREAD

**Issue by tschiew** [ramboxapp/community-edition#3042]
### Steps to reproduce

1. Connect to Slack in Rambox and open the Slack tab
2. Select a channel where you are a member of
2. Click on "View all members of this channel" (upper right corner)
3. Select "Member" tab (second tab)

### Expected behavior

I like to see the list of the channel memebers. 

### Actual behavior

I see the members count and a search bar, but not the list itself. Typing in something in the search bar doesn't help either. 
![Rambox_Bug](https://user-images.githubusercontent.com/11558132/124553998-c2eee080-de35-11eb-913d-66ab612d85dd.PNG)

The same window in the original Slack app:
![Rambox_Bug2](https://user-images.githubusercontent.com/11558132/124554293-1b25e280-de36-11eb-8a6e-93c2a8566359.PNG)

### ENVIRONMENT

Version: 0.7.7
Platform: win32 (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by fvulich** [comment]
It seems to be related with our Electron version. It should be fixed once we bump to a newer version.

**Comment by nzeppos** [comment]
Good to know. Hopefully tracked in https://github.com/ramboxapp/community-edition/pull/2897 then

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by tschiew** [comment]
Thanks for fixing. I've just tested it with 0.7.8 - works fine! :-)
