### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by gerasua** [ramboxapp/community-edition#3044]
No sound. If I play a video from whatsapp in Rambox is mute. If the same video I play from Whatsapp the same video I have sound.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19043

**Comment by fvulich** [comment]
Please check if you have the "Do not disturb" feature on, if it's ON you'll not hear any sound from Rambox CE
![image](https://user-images.githubusercontent.com/46904390/78381741-2db6c980-75ac-11ea-840a-b2cfcdc37899.png)
Also, check this in the app config
![image](https://user-images.githubusercontent.com/46904390/78389795-c43db780-75b9-11ea-8f7c-7871343c54f7.png)
