### ISSUE TITLE
Whatsapp notifications not appearing in the tray again, for some reason.

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#3045]
It started again, sigh... Whatsapp has new messages, but the system tray icon doesn't change color. I tried reloading, restarting, clearing the cache... Nothing.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 6.1.7601

**Comment by eugeneromero** [comment]
Can confirm this is also happening on Rambox Pro, on Linux. Started about 3 or 4 days ago.

Rambox Pro 1.5.2
Ubuntu 20.04

**Comment by 613TheEvil** [comment]
It comes and goes, I might install a previous version if I don't see it fixed soon.
