### ISSUE TITLE
Not font on Fedora 34

### ISSUE THREAD

**Issue by Mebus** [ramboxapp/community-edition#3048]
Hallo,

recently I upgraded my Fedora Linux from version 32 to 34. After the upgrade the file open dialogues in i.e. Whatsapp don't have a font any longer, so I only see boxes instead of text. I attached a screenshot.

[](url)
![rambox_problem](https://user-images.githubusercontent.com/271557/125209128-0662a800-e297-11eb-9778-15e9569c902d.png)

My Rambox version is: 0.7.7

I installed Rambox via snap. What can I do to solve the problem?

Thanks!

Mebus

**Comment by fvulich** [comment]
It seems that the snap is having some troubles with fedora distros, can you try with rpm or deb? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by Mebus** [comment]
> It seems that the snap is having some troubles with fedora distros, can you try with rpm or deb? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

The issues has been resolved for me by using the RPM version of Rambox. Thanks!
