### ISSUE TITLE
Facebook/Messenger video and audio call does not work.

### ISSUE THREAD

**Issue by zelop81** [ramboxapp/community-edition#3052]
**Steps to reproduce**

1. Open up messenger on Rambox.
2. Try to start a video or audio call.
3. Does not work.

**Expected behavior**

Should open up a window on internet browser for video and audio call.

**Actual behavior**

After clicking, nothing happens on Messenger.

**ENVIRONMENT**

Hamsket: v0.7.7
OS: win32
Arch: x64
Windows 10

**Comment by fvulich** [comment]
Duplicate #2650
