### ISSUE TITLE
outlook wont login automatically and gmail alerting incorrect amount of new emails.

### ISSUE THREAD

**Issue by RefaelBeneli** [ramboxapp/community-edition#3053]
Hello,
I am using the outlook and i have to login each time i start rambox, is it possible to auto login?
More over when i have a new email in the gmail, the rambox is alerting 3293 new emails.
Should alert for 1.
Thank you.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.8.0-59-generic

**Comment by fvulich** [comment]
As we can't make the native notifications work, the alerts are triggered by the badge change and shows the number of unread emails.
Please, delete the current Outlook service and add it again and be sure to check this box
![image](https://user-images.githubusercontent.com/46904390/126782445-afcf92cc-1089-4ee0-b89d-fd3d119ec1ac.png)

If that doesn't do the trick it could be that sometimes snap has some troubles with some Linux distros, can you try with AppImage or deb? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by fvulich** [comment]
Regarding the Gmail badge this is a workaround https://github.com/ramboxapp/community-edition/issues/2831#issuecomment-700777731

**Comment by fvulich** [comment]
Closed for lacking a response from the user who created it.
