### ISSUE TITLE
Opening attachment causes Rambox to quit

### ISSUE THREAD

**Issue by motorambler** [ramboxapp/community-edition#3054]
I'm running Rambox Free version 0.7.7 on Zorin OS Core 15.3. 
The app quits/crashes immediately if click on an email attachment (pdf, jpg, or anything else) in any of my connected accounts (Hotmail, iCloud, Gmail, etc.).

I pretty much cannot use the app if I can't open attachments.

Any idea on how to resolve this?

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> linux x64 5.4.0-80-generic

**Comment by fvulich** [comment]
It seems that the snap is having some troubles with fedora distros, can you try with rpm or deb? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
