### ISSUE TITLE
Feedly started breaking

### ISSUE THREAD

**Issue by Lefky** [ramboxapp/community-edition#3055]
### Steps to reproduce

1. Add feedly as a custom service
![Screenshot 2021-07-26 at 08 43 57](https://user-images.githubusercontent.com/10397178/126944570-32acb229-5933-4078-8011-1d937cbc91a7.png)

### Expected behavior

Feedly loads to your today screen.

### Actual behavior

This screen is shown
![Screenshot 2021-07-26 at 08 43 38](https://user-images.githubusercontent.com/10397178/126944525-1780d417-365d-4cf3-bcc0-d7d7a026800e.png)
Cache clearing doesn't help.
This link does but when clicking to redirect to feedly.com you get the same error screen again:
https://feedly.com/v3/auth/auth?client_id=feedly&redirect_uri=https%3A%2F%2Ffeedly.com%2Ffeedly.html&scope=https%3A%2F%2Fcloud.feedly.com%2Fsubscriptions&response_type=code&ck=1512679618405&ct=feedly.desktop&landingPage=welcome&cv=30.0.1409&pageRef=welcome&mode=login
Already removed the service completely.

### ENVIRONMENT

> Version: 0.7.7
> Platform: darwin (x64)
> Electron: 7.2.4
> Chromium: 78.0.3904.130
> Node: 12.8.1

> OS: OSX 11.4 Big Sur

> Arch: x64

**Comment by fvulich** [comment]
I just tried this with this URL https://feedly.com/i/welcome and works as it should, but I'm on Windows. Can you try with it?

**Comment by Lefky** [comment]
For some reason it started just working again since yesterday using the same configuration as posted here.
Maybe it was on the feedly side but I tested everything on 2 computers and got the same results.


> I just tried this with this URL https://feedly.com/i/welcome and works as it should, but I'm on Windows. Can you try with it?

**Comment by fvulich** [comment]
No longer reproducible.
