### ISSUE TITLE
Slack Service needs browser update

### ISSUE THREAD

**Issue by takabanana** [ramboxapp/community-edition#3058]
Run Slack in Rambox.
In my Slack Service, I get a notification at the bottom:
"This browser won’t be supported starting Sept. 1, 2021. Update your browser or get the latest app to keep using Slack. Learn more

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19043

**Comment by fvulich** [comment]
Duplicate #3036
