### ISSUE TITLE
Can't see Members of a Channel in Slack 

### ISSUE THREAD

**Issue by takabanana** [ramboxapp/community-edition#3059]
Open Slack
Pick a Channel
Click "View all members of this channel" at the upper right of the channel.
The Members list shows empty.  (It looks like it is loading the list, and then the height compresses to show none)
On a native browser (outside of Rambox) this shows the list of members correctly.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19043

**Comment by fvulich** [comment]
Duplicate #3042
