### ISSUE TITLE
Keyboard Shortcuts - FIND and BACK/FORWARD doesn't work...?

### ISSUE THREAD

**Issue by takabanana** [ramboxapp/community-edition#3060]
Alt-[Right Arrow] and Alt+[Left Arrow] only seems to work within Slack, but does not work within Gmail, Android Messages, Facebook Messenger, Google Voice, any Custom Service, etc

Also - How can we get FIND (Control+F) to work within each Service window?  
(Oddly enough, in a Custom Service where I bring up a sheet in spreadsheet.com, it works - but not in any other Service).

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19043

**Comment by fvulich** [comment]
You can use the find in page option with the [Cmd+Alt+F] in macOS  or [Shift+Alt+F] in Windows or Linux.

For the navigation shortcuts, we don't have an implementation but, there are some workarounds in this thread https://github.com/ramboxapp/community-edition/issues/690

**Comment by huyz** [comment]
> [Cmd+Alt+F] in macOS

Is that supposed to still work? Cause I can't get it to work when I'm using Slack
