### ISSUE TITLE
Make a new release 

### ISSUE THREAD

**Issue by wpehrc** [ramboxapp/community-edition#3061]
First of all, thanks for merging #2897! Would you please consider making a new release soon?

Unfortunately, it's been over half a year since this PR was made, and since then Electron has made new releases with lots of new CVE fixes, so please also consider updating electron from 11.0.2 to 11.4.10.

In the meantime, @mhatvan, if you could spare the time, would you mind taking a look at this again and see if there any major issues with Electron 13.x? I'd do it myself but unfortunately I have zero experience with this type of stuff so I don't know where to even start from. :(

Thank you all for your time and effort, I really appreciate it.

**Comment by fvulich** [comment]
We are pretty close to release the new version. It will come with 11.4.10

**Comment by mhatvan** [comment]
Hey @wpehrc, sorry but my focus for contributions moved to https://github.com/getferdi/ferdi, which I am now using instead of Rambox, for some of the same reasons you mentioned in your comment above.

It looks like there will be a new release coming anyways, so just a bit more patience needed ;)

**Comment by fvulich** [comment]
0.7.8 Released. You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
