### ISSUE TITLE
Reddit web not available

### ISSUE THREAD

**Issue by noraj** [ramboxapp/community-edition#3065]
On https://rambox.app/#apps I can see there is Reddit web  supported, but in my Rambox client I see only Reddit chat:

![image](https://user-images.githubusercontent.com/16578570/128045917-1d5dd5c9-ed59-4536-8e4c-76b2835aedbd.png)

### Steps to reproduce

1. Open Rambox
2. Browse apps

### Expected behavior

Reddit web available in the client.

### Actual behavior

Reddit web not available in the client.

### ENVIRONMENT

```
Version: 0.7.7
Platform: linux (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1
```

### Extra note

Reading the website it doesn't seem to be a pro feature  and reading the changelog the support was not added in 0.7.8.

**Comment by fvulich** [comment]
You can add it as a custom service.
![image](https://user-images.githubusercontent.com/46904390/128552114-4b9d6e41-1045-494c-879d-9206ea360895.png)

**Comment by noraj** [comment]
Why is-it here if it is not already pre-set?

![image](https://user-images.githubusercontent.com/16578570/128553031-2cfd510a-0741-4e77-8537-353cc71e83f2.png)

**Comment by fvulich** [comment]
It's supported in the Pro version. If you click in the Community Edition, it will list you the services available for your version.
![image](https://user-images.githubusercontent.com/46904390/128559116-ce9c20d4-6909-4493-b0f1-416cfc2a2a67.png)

**Comment by noraj** [comment]
It wasn't clear to me; thx.
