### ISSUE TITLE
Facebook doesn't work anymore

### ISSUE THREAD

**Issue by radioterror** [ramboxapp/community-edition#3068]
Facebook page (that is useful to be logged in multiple accounts, doesn't work anymore in new version update.

Thanks

	
	-
	> Rambox 0.7.8
	> Electron 11.4.10
	> darwin x64 20.6.0

**Comment by RedDwarfCoder** [comment]
No longer working for me either

**Comment by fvulich** [comment]
I just added Facebook to the pre-configured services, please delete your older one and add the preconfigured one.
