### ISSUE TITLE
Twitter tab is blank

### ISSUE THREAD

**Issue by Mariyo** [ramboxapp/community-edition#3069]
Twitter tab is blank, it used to work fine.

### Steps to reproduce

1. add custom service
2. set url to https://twitter.com/home 

![image](https://user-images.githubusercontent.com/1678254/128138197-fdcc7a93-61ee-4dcc-91a6-d8526fade77b.png)

### Expected behavior

I can see twitter site

### Actual behavior

Blank page

![image](https://user-images.githubusercontent.com/1678254/128138251-3fa3f68b-686d-4299-b999-0d04ab579c6d.png)

### ENVIRONMENT

Version: 0.7.8
Platform: linux (x64)
Electron: 11.4.10
Chromium: 87.0.4280.141
Node: 12.18.3

**Comment by RedDwarfCoder** [comment]
It is blank for me too.

**Comment by tinect** [comment]
Same here

**Comment by fvulich** [comment]
We are working in a better fix, but for the moment you can add `--disable-features=CrossOriginOpenerPolicy` to the shortcut

**Comment by fvulich** [comment]
Related #3063

**Comment by Mariyo** [comment]
@fvulich thank you, I am going to complete solution if somebody would land later to this issue:

I use Rambox installed via snap on Ubuntu:

```bash
cd /var/lib/snapd/desktop/applications
sudo vim rambox_rambox.desktop
```
add fix to Exec part:
![image](https://user-images.githubusercontent.com/1678254/128665165-2eaf5c03-2265-431e-b603-73fb8ca4e082.png)

Save & restart Rambox
