### ISSUE TITLE
failure after new update

### ISSUE THREAD

**Issue by Eneyen** [ramboxapp/community-edition#3071]
Hello, yesterday I updated to the new version of Rambox and it gave me problems with Facebook, it loaded it but nothing was seen, the screen was blank. So I deleted it and installed the previous version again, but now Gmail does not work, because it does not let me put it, since when I go to put the password, a sign says that it is not allowed in this browser. I pass you a capture of what it puts me when I try to activate it in Rambox, although the sign is in Spanish because I am from Spain. Before it worked perfectly ...
![fallo](https://user-images.githubusercontent.com/88395839/128236359-4a8c0840-1855-40e2-969a-e7a681ced95e.jpg)

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.19043

**Comment by fvulich** [comment]
The version 0.7.3 is very old, please update at least to 0.7.7. We recommend 0.7.8, we are working on a fix for your issue, but for the moment you can add `--disable-features=CrossOriginOpenerPolicy` to the shortcut and it will work as it should.

**Comment by fvulich** [comment]
Related #3063
