### ISSUE TITLE
Workplace is not working in the latest version 0.7.8

### ISSUE THREAD

**Issue by zhenghaolee** [ramboxapp/community-edition#3074]
select the workplace tab at the top bar, and it will shows a blank page. If you refresh the tab, Rambox will crash

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
We are working in a better fix but for the moment you can add `--disable-features=CrossOriginOpenerPolicy` to the shortcut

**Comment by fvulich** [comment]
Related #3063
