### ISSUE TITLE
WhatsApp not work! need Chrome up more than 60v

### ISSUE THREAD

**Issue by xVRVx** [ramboxapp/community-edition#3075]
Hello my friends!
WhatsApp  do not work! need Chrome up more than 60v

	
	-
	> Rambox 0.7.8
	> Electron 11.4.10
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
I just checked, and it works as it should, try removing the service and adding it again, be aware that it will not work if you have a custom user agent set in preferences.
