### ISSUE TITLE
Download window doesn't render fonts

### ISSUE THREAD

**Issue by ersiq** [ramboxapp/community-edition#3076]
Today I can't save any attached file in my hard drive using Rambox

![imagen](https://user-images.githubusercontent.com/88512925/128419089-23e369a1-2533-444d-96e5-1b12711c35ba.png)

	-
	> Rambox 0.7.8
	> Electron 11.4.10
	> linux x64 5.4.0-80-generic

**Comment by fvulich** [comment]
Can you try with a different package because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

**Comment by twardnw** [comment]
I was seeing this issue, Ubuntu 20.04, Rambox 0.7.9 installed via Snap.

Removing the Snap package and installing from the .deb resolved the issue
