### ISSUE TITLE
Facebook not loading in new update rambox ce 0.7.8

### ISSUE THREAD

**Issue by bjpier** [ramboxapp/community-edition#3078]
### Steps to reproduce

1. install rambox 0.7.8
2. add https://www.facewbook.com
3. 

### ENVIRONMENT

> Rambox: v0.7.8

> OS:LINUN MINT

> Arch: x64

**Comment by fvulich** [comment]
We are working in a better fix but for the moment you can add --disable-features=CrossOriginOpenerPolicy to the shortcut, also we added Facebook as a preconfigured service, you can add it from there, and it will work.
![image](https://user-images.githubusercontent.com/46904390/128708307-b6d6a94d-43a5-4c2b-b3b3-c597eaf62ca5.png)

Related #3063
