### ISSUE TITLE
FACEBOOK not Loading  on Rambox CE v 0.7.8

### ISSUE THREAD

**Issue by bjpier** [ramboxapp/community-edition#3079]
### Steps to reproduce

1. install rambox 0.7.8
2. add https://www.facewbook.com
3. 

### Expected behavior

Facebook shud load and you can view posted

### Actual behavior

Can not see the face book site

### ENVIRONMENT

> Rambox: v0.7.8

> OS:LINUN MINT

> Arch: x64

**Comment by bjpier** [comment]
This is the same issue as the one listed below the lists...
I guess a fix has not been released

Custome Services show white screen, then rambox crashes when refresh the service #3063

**Comment by fvulich** [comment]
We are working in a better fix but for the moment you can add --disable-features=CrossOriginOpenerPolicy to the shortcut, also we added Facebook as a preconfigured service, you can add it from there, and it will work.
![image](https://user-images.githubusercontent.com/46904390/128708307-b6d6a94d-43a5-4c2b-b3b3-c597eaf62ca5.png)

Related #3063

**Comment by bjpier** [comment]
Thank you, found the preconfigured service and now it works!
I dont know what you mean by:
add --disable-features=CrossOriginOpenerPolicy
can you explain that for future cases? thanks again.
