### ISSUE TITLE
Recent Rambox 0.7.8 update will not display Facebook page - everything else works as usual though

### ISSUE THREAD

**Issue by katzpajamas** [ramboxapp/community-edition#3080]
Most recent Rambox 0.7.8 update will not show Facebook page at all. Only the number of 'Notifications' (small red box with number inside top right cornier of my Facebook icon and name). All other services e.g. Gmail work and display as usual.

Never happened before with any Community version of Rambox. Testing out Ferdi as a replacement if or whenever Rambox repairs this odd issue.

Tried reinstalling with downloadable full Community version over existing update, uninstalling then reinstalling with downloadable full version, removing Facebook account entirely then adding it again = no change. Facebook will login as before, but no page will load on the Rambox screen for it.

Plus, I personally would appreciate NOT having forced updates while using the Community version of Rambox, and allow me to choose to update or not, and to roll-back if an issue like this results, etc.

Thanks for your understanding and help!

	
	-
	> Rambox 0.7.8
	> Electron 11.4.10
	> win32 x64 10.0.17763

**Comment by fvulich** [comment]
0.7.9 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
