### ISSUE TITLE
CE 7.8 update automatically reverts back to 7.7 version

### ISSUE THREAD

**Issue by clintlalonde** [ramboxapp/community-edition#3081]
### Steps to reproduce

Rambox doesn't seem to remember that I have updated from CE 7.7 to 7.8 as everytime I open Rambox I am prompted to update to 7.8 despite having already updated to 7.8.

1. Update Rambox CE from v 7.7 to 7.8
2. Restart Rambox. All application login info is lost and so I must reauthenticate in all my applications
3. Close Rambox
4. Start Rambox and am prompted to download and install the 7.8 update
5. This cycle repeats over and over

### Expected behavior

After updating to 7.8 Rambox should not revert back to 7.7 and prompt me to update to 7.8 each time I open Rambox.

### Actual behavior

Each time I open Rambox after updating to 7.8 I am prompted to update from 7.7 to 7.8

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Win 10 Pro ver 20H2 OS build 19042.1110

> Arch: x64

**Comment by AciDCooL** [comment]
Hey, had the same issue. Search your registry "Computer\HKEY_LOCAL_MACHINE\SOFTWARE" for rambox, you'll find a key named: "InstallLocation". Change that to your location your shortcut is pointing towards. Maybe this helps, don't know why this update decided to default to "c:\program files\rambox" but it did for me.

**Comment by clintlalonde** [comment]
Thanks. It wasn't the registry for me, but your comment made me check the shortcut I had and that was the issue. I deleted and recreated the desktop shortcut and that worked for me.
