### ISSUE TITLE
Workplace crashe

### ISSUE THREAD

**Issue by jmadeira** [ramboxapp/community-edition#3084]
`The workplace component is not loading on this new version, and it's forced to reload the service, crashes.`	

	
	-
	> Rambox 0.7.8
	> Electron 11.4.10
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
0.7.9 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
