### ISSUE TITLE
Twitter Module Not Working

### ISSUE THREAD

**Issue by TonyEAncg** [ramboxapp/community-edition#3087]
The twitter module is not working. When you open it and click Login, the screen goes blank and nothing happens

	
	-
	> Rambox 0.7.8
	> Electron 11.4.10
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
0.7.9 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)
