### ISSUE TITLE
Start minimised option not working

### ISSUE THREAD

**Issue by SinTan1729** [ramboxapp/community-edition#3089]
### Steps to reproduce

1. Enable the  "Start minimised" options
2. Start app

### Expected behavior

App should minimise after asking for password.

### Actual behavior

App minimises for a while but then opens again.

### ENVIRONMENT

> Rambox: v0.7.9-1

> OS: Manjaro Linux

> Arch: x64

**Comment by fvulich** [comment]
Can you provide us a video of the issue? What package are you using?

**Comment by SinTan1729** [comment]
Here's a recording:
![Screen recording](https://user-images.githubusercontent.com/35728385/129063346-c3ab01ce-2da0-46fd-aecf-3e2909a90ec8.mp4)
I'm using the `rambox-bin` package from AUR.

**Comment by AXeL-dev** [comment]
Hello, i'm facing the same issue here on Ubuntu 21.04, even if the start minimized option is activated under the settings, the app still don't open minimized when first launched.
Thanks in advance for your help.

**Comment by fvulich** [comment]
Thanks for the feedback, there's an older ticket reporting this.

Duplicate #3067
