### ISSUE TITLE
Hangouts-image not loading

### ISSUE THREAD

**Issue by KochFolie** [ramboxapp/community-edition#309]
### Steps to reproduce
1. Receive or send a Hangouts image
2. Click on it
### Expected behavior

Image is shown in full size in dedicated window or default browser.
### Actual behavior

New window opens with the google header, then the black image-background overlays the whole page. So far, so good, but then the image does not load. Maybe an error, which is not visible, since the dev-tools are not available in the new window.

![image](https://cloud.githubusercontent.com/assets/5193312/18382444/34a6c2b4-7681-11e6-9ce0-4b1ad13ed63e.png)
### ENVIRONMENT

> Rambox: v0.4.2
> 
> OS: Windows 10
> 
> Arch: x64

**Comment by saenzramiro** [comment]
Can you tell me what happens when you click on the image using Hangouts in Chrome? Is opening Google Plus with the image?

**Comment by KochFolie** [comment]
Yes, it looks exactly like in my screenshot, only that the image loads in the black area.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
