### ISSUE TITLE
all services and settings gone if started manually

### ISSUE THREAD

**Issue by augugusto** [ramboxapp/community-edition#3090]
### Steps to reproduce

1. set the app to auto start on login
2. reboot
3. add a service to the open window
4. open the menu and open rambox

### Expected behavior

either focusing the already open window, opening the minimized to tray window, or a message that only one instance can run at a time

### Actual behavior

a new window opens with none of the previous services or settings, and rightl clicking on the tray icon shown the menu with missing fonts
(the missing fonts might be an issu with my arch install but i thought that snaps where supposed to ship with all the requirements.

this is a problem because if i accidentally close the window, the only way i found to get it back is to log back in

### ENVIRONMENT

archlinux system with gnome DE

> Rambox: v0.7.9 (accoring to snap)

> OS: (rolling release)
> Arch: x64

**Comment by fvulich** [comment]
It seems that you have two packages installed, please delete one of them. Also, SNAP is not the best choice for Arch Linux, we recommend AUR? Could you try with a  different package? You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)
