### ISSUE TITLE
Slack-Call screen sharing does not work due to missing permissions

### ISSUE THREAD

**Issue by kurthuwig** [ramboxapp/community-edition#3091]
1. Open or join a call in a Slack channel.
2. try to share the screen

Expected result: screen sharing starts, just like when doing this in Chrome with version 0.7.7
Actual result: button flickers but no screen sharing

Logs:

gantry-shared.fd09dfd.min.js?cacheKey=gantry-1629022649:1 Aug-16 09:36:09.710 [FREE-WILLY-SDK] (TDTLZ231P) API/DefaultAudioVideoFacade/4e3990d5-4ed0-48f6-bfd4-392916e80706/eccc2bd9-1cec-c4f9-055d-cac4623c4416/startContentShareFromScreenCapture
gantry-shared.fd09dfd.min.js?cacheKey=gantry-1629022649:1 Aug-16 09:36:09.718 FREE-WILLY-CONTENT-SHARE (TDTLZ231P) getUserMedia error during huddle screenshare attempt: NotAllowedError Permission denied

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> linux x64 5.13.8-1-MANJARO

**Comment by fvulich** [comment]
Duplicate #3083
