### ISSUE TITLE
I have an error with the text in the file selection dialog box.

### ISSUE THREAD

**Issue by baneonstore** [ramboxapp/community-edition#3094]
I have an error with the text in the file selection dialog box.

This is all operating system resources/availability:

- Xunbutu 20.04.1
- Font type: Open Sans
- Theme: Victory (21.07) for xfce4
- From where it was installed: Snap repository (Snapcraft)
- Version: Community Edition (sorry for the obvious)

###
Version: 0.7.9
Platform: linux (x64)
Electron: 11.4.10
Chromium: 87.0.4280.141
Node: 12.18.3

![capture](https://user-images.githubusercontent.com/59712047/129948838-9baf822e-87ad-4eea-be62-fcd8947fb5d6.png)

###

I hope this information is useful 😀

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> linux x64 5.11.0-25-generic

**Comment by fvulich** [comment]
Can you try with a different package because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)

Related #3076
