### ISSUE TITLE
Scrolling necessary on Element chats makes it hard to use 

### ISSUE THREAD

**Issue by arthurlogilab** [ramboxapp/community-edition#3095]
### Steps to reproduce

1. Configure Element
2. Use element in chats
3. You have to scroll down on every chat window to see new messages

I think this a regression introduced by recent release of 0.7.9

### Expected behavior

Autoscrolling as it is done when accessing Element though a browser, or element-desktop

### Actual behavior

Messages (even when typing them) appear below the visible area

### ENVIRONMENT

> Rambox: v0.7.9

> OS: Ubuntu

> Arch: x64

**Comment by fvulich** [comment]
Can you provide us  some screenshots or even better a video of it. It will be really helpful when we try to fix it.
