### ISSUE TITLE
[twitterdeck] 0.4.2 loads (randomly) clicked URL in the same tab

### ISSUE THREAD

**Issue by soulchainer** [ramboxapp/community-edition#310]
### Steps to reproduce
1.  Change to your Tweetdeck service tab
2. Click some links in a tweet and, randomly, the issue appears.
### Expected behavior

Well, the expected behavior is Rambox sending the link URL to your browser, to display it there.
### Actual behavior

The actual behaviour is that, randomly (it doesn't occur all the times, but it pretty annoying), Rambox loads the clicked link in the same Tweetdeck tab (apart of also sending it to your browser).
The worse part of this is that, even if you open the Developer Tools and try `history.back()`, it doesn't work :D. So if you want to use Tweetdeck after the issue happens (and that's probably the case), you need to close Rambox and start it again (yes: using `View → Reload` neither works).
### ENVIRONMENT

> Rambox: v0.4.2
> 
> OS: Antergos (Arch Linux x86_64)
> 
> Arch: x64

**Comment by forteller** [comment]
Same problem here, except:

1. So far it has consistantly happened when clicking a link in a profile bio, every time (4 times, 3 different bios) and only then, not in tweets (tested like 5 times or something).

2. It takes over not only the tab, but the whole of Rambox, so I can not use any part of it any more until I restart it.

Maybe this is a different bug?

**Comment by soulchainer** [comment]
@forteller Oh. You are... right. **But** I just realized that, in the case you descrbe, it really doesn't take over it. It only opens the link in a new undecorated «window» (so it looks like it take over rambox, but not) at full screen. If you click on *Window → Close* or use the hotkey *Control + W*, you can close it and continue with rambox, that is under it.

Still a bug, because I thing this shouldn't happen and wasn't the behavior till now.

I guess that, in my case, the error is the same (so, I guess, it also is opening a window fullscreen undecorated), just I didn't notice till now. l still (from I just read you) couldn't reproduce it again, because it happens more erratically than with URL in BIO. I intend it on purpose now and it doesn't please me.

**Comment by saenzramiro** [comment]
Both of you have the same OS? (Antergos (Arch Linux x86_64)

I tested in Windows 10 x64 and works for me. I can't reproduce this bug, so I will need your help.

**Comment by forteller** [comment]
No, I'm on Ubuntu Gnome 16.04 (With the Gnome Staging PPA to update my version of Gnome from 3.18 to 3.20, if that matters)

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
