### ISSUE TITLE
Feature Request: WhatsApp no notifications/unread label for archived chats

### ISSUE THREAD

**Issue by sneeed** [ramboxapp/community-edition#3103]
### Expected behavior

Give an option for WhatsApp to not show notifications and unread counter label, when only unread archived chats are there.

### Actual behavior

We get notification and unread counter label regardless if its an archived or not archived chat.

### ENVIRONMENT

> Rambox: v0.7.9
Platform: linux (x64)
Electron: 11.4.10
Chromium: 87.0.4280.141
Node: 12.18.3

> OS: Fedora 34, Gnome 40.4

> Arch: x64 or ia32

**Comment by CristianoCricas** [comment]
up!
