### ISSUE TITLE
Telegram does not notice anymore I'm not active on the last selected chat and does not produce any notification for it

### ISSUE THREAD

**Issue by tmortagne** [ramboxapp/community-edition#3105]
### Steps to reproduce

1. Go to Telegram
2. Select one of the chats you have with some user
3. Leave it like this and go to another tab for a little while
4. Ask the other user to send you a Telegram message

-> You do receive the message, but you don't get any notification about it from Rambox or any other device (in my case, the Telegram app on my phone) as if you were still active on the Telegram chat.

Note that I tried the same thing on Telegram Web through Chrome (91.0.4472.114) and I don't reproduce it, so it does seem to be a bug on Telegram Web side (but the trigger might still be a Telegram Web change I guess). Unfortunately, I'm not able to tell exactly when this started (did not use Rambox much this summer or at least not long enough to notice it earlier), but I'm sure I did not have this issue 2 months ago. It's possible that it started when I upgraded to Rambox 0.7.9, but I'm not 100% sure.

### Expected behavior

I would expect to receive some notification when I'm not active anymore.

### Actual behavior

As long as there is a Rambox tab with Telegram selecting some user chat I will never get any notification on any device about new messages sent by this user.

### ENVIRONMENT

> Rambox: v0.7.9

> OS: Ubuntu 21.04

> Arch: x64

**Comment by fvulich** [comment]
Are you using the Z or the K version, please, try switching from one to another?

![image](https://user-images.githubusercontent.com/46904390/132014313-2400551e-275c-4fab-abec-b8a87104b1c6.png)

**Comment by tmortagne** [comment]
I just checked, and I have `Telegram WebZ alpha 1.11.13` on both Rambox and Chrome.

**Comment by fvulich** [comment]
Can you try with K version?

**Comment by tmortagne** [comment]
I confirm that the Rambox bug only affects version Z. If I switch to another tab with K version I get notifications right away even for the last chat I selected.

**Comment by fvulich** [comment]
I'm closing this ticket for now, but you can open a new one once Telegram decides which version will be the official one, if  there's the issue in it.
