### ISSUE TITLE
Backbutton does not work anymore for navigation.

### ISSUE THREAD

**Issue by johan-horst** [ramboxapp/community-edition#3107]
I have custom services for specific websites. Since one of the latest updates the navigation (back button on my mouse) does not give any response.

Reproduction: create custom service for youtube. Select a random video. Use back button of your mouse to go back to list of video's. 

	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.18363

**Comment by fvulich** [comment]
Duplicate #3088
