### ISSUE TITLE
Update Whatsapp and Whatsapp business

### ISSUE THREAD

**Issue by halphas91** [ramboxapp/community-edition#3113]
Hello,

I have a problem with Whatsapp and Whatsapp Business messages.
Several times per day, I see a message inform me there is an update available for theses app. But when I click on it, a can see a quick window telling I have to update Chrome (I don't use Chrome, but Opera... wich update already). So, sometimes the message disappears itself after that, and sometimes not.

(sorry I'm french... bad english)

COuld you help me, please ?

Thanks.

Regards.
Yann

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.19043

**Comment by fvulich** [comment]
Duplicate #2217 You can try the [workaround](https://github.com/ramboxapp/community-edition/issues/2217#issuecomment-562023784) posted there
