### ISSUE TITLE
Is there a api? ( for Awesome Window Manager)

### ISSUE THREAD

**Issue by SHU-red** [ramboxapp/community-edition#3124]
### Steps to reproduce

I want to access informations from rambox via awesome Window Manager
Is there a way to get informations about installed/activated services?

### Expected behavior

If i get e.g. a new Message from WhattsApp
I can get this information via an API
Then i can highlight this on my custom made icon in my awesomeWM titlebar

(same for e.g. Google Mail etc...)

### Actual behavior

I have no idea if there is somethin
The only thing i coud do is try to capture notifications from Rambox and get information from that

### ENVIRONMENT

> Rambox: 0.7.9

> System:    Kernel: 5.14.9-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 Desktop: awesome 4.3 vt: 1 dm: SDDM 
           Distro: Manjaro Linux base: Arch Linux

**Comment by fvulich** [comment]
There's no API, and we don't have plans to implement something like it. Thanks for the suggestion.
