### ISSUE TITLE
[Notifications] for Telegram not working

### ISSUE THREAD

**Issue by SHU-red** [ramboxapp/community-edition#3125]
Somehow i do not get notifications on new Messages in Telegram service.
I also have installed WhattsApp --> Notifications working there.

Can i provide more infos like log-files or something?

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> linux x64 5.14.9-1-MANJARO
    > Awesome Window Tiling manager with naughty notification

**Comment by fvulich** [comment]
Change to the K version, the Z one doesn't throw notifications. Or at least we can't catch them.
![image](https://user-images.githubusercontent.com/46904390/140576162-f038ca45-067a-4f61-9922-a74f170e3a90.png)

**Comment by SHU-red** [comment]
Today I got it working by catching the right class name
Now I'm making the right notifications myself by parsing the unread batch from Zalpha
