### ISSUE TITLE
Can't login to Google Chat

### ISSUE THREAD

**Issue by stevendejongnl** [ramboxapp/community-edition#3128]
Trying to log in on Google Chat, I can't go to the password step.
There is a console error: `This document requires 'TrustedHTML' assignment.set @ VM367:1`

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> linux x64 5.13.0-7614-generic

**Comment by krejcp19** [comment]
I have the same issue. Cannot pass entering password screen. Console says: "This document requires 'TrustedHTML' assignment."

	> Rambox 0.7.9
	> Electron 11.4.10
	> linux x64 5.4.0-88-generic

**Comment by leandrosouza** [comment]
Same issue 
```
Version: 0.7.9
Platform: darwin (x64)
Electron: 11.4.10
Chromium: 87.0.4280.141
Node: 12.18.3
```

**Comment by gisseh** [comment]
Same issue here with deb package 0.79 on Ubuntu 20.04.

@Braintelligence thank you for sharing the workaround!

All the best,

**Comment by gisseh** [comment]
> @gisseh did you find custom code for the unread messages? I tried copypasting the one from
> 
> https://raw.githubusercontent.com/ramboxapp/community-edition/gh-pages/api/services.json
> 
> but it didn't work.

The notification icon didn't work for me neither =((

**Comment by SpookDroid** [comment]
Pardon the noob question then, but since this is marked as closed, How do I get it to work?  There's no new version out, so how do I use the JSON file? :(

**Comment by InitPatch** [comment]
Pardon me as well, but it looks like I can't login into Google Chat anymore since today (possibly yesterday too, last I used it was on 02/25/22
![Rambox (14) - Google Chat 2022-03-01 14-35-45](https://user-images.githubusercontent.com/15719066/156236616-9af7cc50-1211-42fb-85ac-c92016c9a44b.png)

**Comment by woropajj** [comment]
This problem happened for me again but for Gmail. Also, I found out that Rambox has a dark mode. It says so on its website but I couldn't find it. I'm using Linux. That being said: I ditched Rambox and moved to Ferdi.
