### ISSUE TITLE
Google Chat not allowing me to log in

### ISSUE THREAD

**Issue by dasbrey** [ramboxapp/community-edition#3129]
I was previously logged in to Google Chat with no issues. However, it asked me to log in again, as it sometimes does, and after entering in my email address and clicking Next, nothing happens. I can refresh the tab and the same thing happens; I can't process the log in at all, screenshot as below shows the tab in Rambox and the screen I can't move past.

![image](https://user-images.githubusercontent.com/50765434/137458542-f40bbe1b-4309-49bf-80d6-afb31334c0f3.png)

I can log into my Google Chat account online without any issues, so my account shouldn't be the problem

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.19043

**Comment by th-lange** [comment]
:+1:

**Comment by marcosrocha85** [comment]
+1

**Comment by fvulich** [comment]
Duplicate #3128
