### ISSUE TITLE
Services Tabs Not Showing After the Update

### ISSUE THREAD

**Issue by rrhutch** [ramboxapp/community-edition#313]
After installing the update that was just pushed, the individual service tabs are no longer appearing for me. I still the the services setup on the main screen, but not the tabs to interact with them. I uninstalled Rambox and reinstalled from the website. I guess the installation file is the old version because when I downloaded and installed it then asked to apply the update again. Once the update was applied the service tabs were gone. I am running the 64-bit Windows version.

## 

> Rambox 0.4.2
> Electron 1.3.5
> win32 x64 10.0.14393

**Comment by Hammster** [comment]
I just installed Rambox i've encountered the same issue, Blank tabs.

> Rambox 0.4.2 
> Ubuntu Gnome 16.04 LTS

**Comment by saenzramiro** [comment]
@rrhutch Can you open the developer tools and share the error here please?

I'm using Rambox in a same environment and works ok for me.

@Hammster Your problem is more related with #181.

**Comment by brwolfgang** [comment]
Hi there @saenzramiro, here's the log:

[log.txt](https://github.com/saenzramiro/rambox/files/467310/1473684194619.txt)
