### ISSUE TITLE
just shows a white screen when the app launch. #3085

### ISSUE THREAD

**Issue by Nicolay-Maker** [ramboxapp/community-edition#3130]
### Steps to reproduce

1. Running the program on a macbook
2. Shows a white screen window
3. 

### ENVIRONMENT

> Rambox: v0.7.8 Mac

> OS: X YOSEMITE v10.10.5

> Arch: x64 or ia32

**Comment by Nicolay-Maker** [comment]
Please help me

**Comment by fvulich** [comment]
We tried to help you in this #3085 please stop creating new ones.
