### ISSUE TITLE
Error when trying to login in Google Chat

### ISSUE THREAD

**Issue by rpelisam** [ramboxapp/community-edition#3131]
Hi guys, I'm facing an issue when I try to login in Google Chat, after enter my password I got an error screen and couldn't go futher. I've tryed the same process in the web browser and everything have worked fine.
![step1](https://user-images.githubusercontent.com/45097066/137534929-92c6a3d2-bbbd-474e-8bb0-939bcc8ecd9f.png)
![step2](https://user-images.githubusercontent.com/45097066/137534941-35bdaacb-c4a4-45c2-8012-d7826a055975.png)

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.17134

**Comment by DeanoAus** [comment]
That solution works for me. Unread counters are a bit funky, but notifications and chat works fine - which is  better than running another browser window.

**Comment by fvulich** [comment]
duplicate #3128
