### ISSUE TITLE
rombox --hidden shows it

### ISSUE THREAD

**Issue by mizzunet** [ramboxapp/community-edition#3132]
### Steps to reproduce

1. Run `rambox --hidden`

### Expected behavior
Start Rambox in tray without displaying the program

### Actual behavior
Rambox opens normally

### ENVIRONMENT

> Rambox: v0.7.9-3

> OS: Debian

> Arch: x64

**Comment by fvulich** [comment]
![image](https://user-images.githubusercontent.com/46904390/140574929-1d1eda94-bf99-432c-a3f2-03a2bc4c3d97.png)

We don't have any code to implement that.
