### ISSUE TITLE
Unable to login to google chat

### ISSUE THREAD

**Issue by DeanoAus** [ramboxapp/community-edition#3134]
- I was logged out of google chat (as per normal).
- When I attempt to log back in, I am asked for a valid email
- Sometimes I am able to enter the email and proceed to the password prompt, other times I am unable to click the next button (it does nothing when I click it, neither does pressing enter on the keyboard)
- If I make it to the password screen, enter the password I get "Something went wrong" with no further details.

I have been using rambox and google chat now for months without issue.
Of note, going to the developer console I can see an error `VM262:1 This document requires 'TrustedHTML' assignment.`

If I remove google chat from rambox and re-add it, I am able to progress to the password screen, but as soon as I submit my password I am shown the "Something went wrong" error. `Sorry, something went wrong there. Please try again.` If I click next, i'm shown a blank white page.
﻿

![can't click next](https://user-images.githubusercontent.com/35859910/137661803-547131d2-f240-4c62-aecd-1e3e36077f7d.gif)

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> linux x64 5.4.0-88-generic

**Comment by takigama** [comment]
Im on the same version with the same issue, however... If I open the developer tool and on the network tab, do "disable cache", then reload, I get past the login screen onto the password screen. After that it fails with:

![Screenshot from 2021-10-19 13-16-13](https://user-images.githubusercontent.com/151283/137832768-76ea2757-8b3d-451e-a3e6-2490810ad929.png)

Worth noting that "help->tools->clear cache and/or clear storage" dont change the original error at all, i.e. after "clear cache/storage" it'll just get stuck on the login screen with the "next" button doing nothing.

**Comment by fvulich** [comment]
Duplicate
