### ISSUE TITLE
Message: WhatsApp works with Google Chrome 60+

### ISSUE THREAD

**Issue by cleyan** [ramboxapp/community-edition#3139]
Today when I opened rambox in the whtasapp tab i got the error WhatsApp works with Google Chrome 60+

https://www.dropbox.com/s/pnszyd85vtft0m0/Captura%20de%20Pantalla%202021-10-20%20a%20la%28s%29%2009.29.23.png?dl=0

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> darwin x64 20.6.0

**Comment by fvulich** [comment]
Please remove the WhatsApp app and add  it again

**Comment by clifficious** [comment]
if somebody stumbles across this issue again. Actually disabling and re-enabling worked for me.
