### ISSUE TITLE
onbeforeunload not triggering

### ISSUE THREAD

**Issue by dantronik-markus** [ramboxapp/community-edition#3141]
### Steps to reproduce

1. Add a new service to https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onbeforeunload and open it
2. On the service, click the "Click here to go to w3schools.com" link.

### Expected behavior
A prompt appears asking the user whether they'd really like to switch to the site.

### Actual behavior

Nothing happens

### ENVIRONMENT

> Rambox: 0.7.9

> OS: Windows 10

> Arch: x64

**Comment by fvulich** [comment]
Electron doesn't support natively prompt read more in this thread #694
