### ISSUE TITLE
audio probleme

### ISSUE THREAD

**Issue by BlockFree** [ramboxapp/community-edition#3143]
Hello
I'm not able to listen to my audio messages. Not in telegam, neither in messenger. Yes the volume is on and I'm able to listen to youtube videos on my browser or to listen my messages if I dont use Rambox, so I think it may come from the app. 

thank you!

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.19042

**Comment by fvulich** [comment]
Please check if you have the "Do not disturb" feature on, if it's ON you'll not hear any sound from Rambox CE
![image](https://user-images.githubusercontent.com/46904390/78381741-2db6c980-75ac-11ea-840a-b2cfcdc37899.png)
Also, check this in the app config
![image](https://user-images.githubusercontent.com/46904390/78389795-c43db780-75b9-11ea-8f7c-7871343c54f7.png)
