### ISSUE TITLE
Cannot access work gchat

### ISSUE THREAD

**Issue by jpmika** [ramboxapp/community-edition#3145]
<I have been unable to log in to my work Gchat from WFU.edu for 48 hours now. Is there anything I need to change in my Rambox to access academic Gmail Gchats or how do I reconnect? I tried going back to Hangouts as well. No luck. I enter my wfu.edu email address, and Rambox will not recognize the email address. I am stuck in the sign-in stage/page>

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.19041

**Comment by fvulich** [comment]
Duplicate
