### ISSUE TITLE
Google chat no longer logs in

### ISSUE THREAD

**Issue by outerregion** [ramboxapp/community-edition#3146]
Since Sunday, I've been unable to log in to google chat. Every time it comes back with 

"Something went wrong
Sorry, something went wrong there. Try again."

I have no issue in firefox or chrome. Tested on 3 separate computers across 2 OS's (Windows and Linux Mint)

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> linux x64 5.4.0-88-generic

**Comment by fvulich** [comment]
Duplicate
