### ISSUE TITLE
Problem with add Google Chat Service

### ISSUE THREAD

**Issue by spectro55** [ramboxapp/community-edition#3147]
1.Add the Google Chat service and login with your account
2. Enter email
3. Enter password and then:

![image](https://user-images.githubusercontent.com/93222606/138951884-fad9f707-7364-4935-8fa6-a8f385024bb8.png)

Thanks in advance

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.19043

**Comment by fvulich** [comment]
Duplicate
