### ISSUE TITLE
Icons on tabs. 

### ISSUE THREAD

**Issue by HederaCo** [ramboxapp/community-edition#3154]
I was wondering how I can get the company icon for all the app tabs to show up. Some apps show up and some don’t. 

Thank you! 

> Rambox: v0.X.X

> OS: XXXX

> Arch: x64 or ia32

**Comment by fvulich** [comment]
Can you elaborate a bit further? Is a custom app?

**Comment by HederaCo** [comment]
Hi there! Yes, it is a "Custom Service" that I am adding. Everything works fine, except I'm really not sure what URL to use for the custom logo that goes within the tab. Right now it is blank. I've tried a few different URLs to images online and none of them work.

Thanks in advance for your help!
Benjamin Alicea
Owner, Hedera LLC

E: ***@***.*** ***@***.***)
P: (888) 228-0648 (tel:(888)%20228-0648)
A: 177 Huntington Ave (https://maps.google.com/?q=177%20Huntington%20Ave)
W: https://hedera.co/

**Comment by fvulich** [comment]
Not all URLs can be access without a context, please be sure to use one that can do this or upload them to a web that host images.
For instance, this one works
https://j2logo.com/wp-content/uploads/slack-logo.png

**Comment by HederaCo** [comment]
Okay great, thanks!

Benjamin Alicea
Owner, Hedera LLC

E: ***@***.*** ***@***.***)
P: (888) 228-0648 (tel:(888)%20228-0648)
A: 177 Huntington Ave (https://maps.google.com/?q=177%20Huntington%20Ave)
W: https://hedera.co/
