### ISSUE TITLE
Custom-Code: Include script from file

### ISSUE THREAD

**Issue by SHU-red** [ramboxapp/community-edition#3155]
### Steps to reproduce

1. Insert custom code to include .js file

### Expected behavior

JavaScript is executed
I want to do this to be able to backup and version control my custom code-files
I know, that the custom code shall only be minimal but maybe it could be done to not include code but choose a .js file which is then executed?

### Actual behavior

Nothing worked for me

### ENVIRONMENT

Version: 0.7.9
Platform: linux (x64)
Electron: 11.4.10
Chromium: 87.0.4280.141
Node: 12.18.3

**Comment by fvulich** [comment]
It doesn't seem to be a feature that we'll going to develop, but PRs are welcome.
