### ISSUE TITLE
Rambox not identified my OS in mobile phone

### ISSUE THREAD

**Issue by apradoc** [ramboxapp/community-edition#3161]
### Steps to reproduce

1. Open my Rambox Apimage
2. Add Whatsapp Business servide
3. Scan the QR Code with my mobile phone
4. The session is successfully started in Rambox
5. The application on my device indicates that I have an active session in Windows

### Expected behavior

The application on my device should indicate that I have an active GNU/Linux session or at least mention "Linux"

### Actual behavior

The application on my device indicates that I have an active session in Windows

### ENVIRONMENT

GNU/Linux , Intel® Core i7-4510U 2GHz, 8GB RAM

> Rambox: v0.7.9 Appimage

> OS: Deepin 20.2.4

> Arch: x64 

> ![image](https://user-images.githubusercontent.com/92080/141615266-490e7572-6b76-41f9-aa82-cf24eaf6942d.png)

**Comment by fvulich** [comment]
For WhatsApp, we use a Chrome user agent to make it work, that's why you see Chrome instead of Rambox.
