### ISSUE TITLE
Camera not working in Slack

### ISSUE THREAD

**Issue by davelbit** [ramboxapp/community-edition#3165]
Unfortunately, I don't necessarily know how to reproduce the issue, but I noticed that I'm not able 
        use my laptop camera when I'm using slack in Rambox, but when I'm using the actual slack application
        it works. Which makes me believe that the issue lies in the rambox support. 

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> linux x64 5.13.0-7620-generic

**Comment by fvulich** [comment]
Please ensure to give the proper permissions to the snap.
This link may help you out.
https://www.linuxandubuntu.com/home/snap-application-permissions

**Comment by sdbeuf** [comment]
> Please ensure to give the proper permissions to the snap. This link may help you out. https://www.linuxandubuntu.com/home/snap-application-permissions

As @fvulich mentioned, this is a permissions issue. You can always go to your permission of your applications in the UI to toggle them on or off
