### ISSUE TITLE
Ctrl+Enter don't work, cannot send in Discord

### ISSUE THREAD

**Issue by numpad0** [ramboxapp/community-edition#3167]
Log into Discord, type in something, try to send with Ctrl + Enter but it won't work, Shift + Enter is assigned to newline, send button isn't present because Discord, and cannot send any message. 

This is potentially due to Discord disabling Enter key to send for CJKV language users, as these languages are typed using a system called IME that make heavy use of Space and Enter keys.

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.22000

**Comment by fvulich** [comment]
Can you reproduce this issue in the browser?
