### ISSUE TITLE
Slack reports it will not support this browser

### ISSUE THREAD

**Issue by srambach** [ramboxapp/community-edition#3168]
Slack reports that it will not support this browser version after March 2022.

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> darwin x64 20.6.0

**Comment by jonmchan** [comment]
Here's the actual error message:

![image](https://user-images.githubusercontent.com/1827190/143156370-b0bbd678-a966-4782-9ab0-c771b78a8843.png)

Link: https://slack.com/help/articles/1500001836081-Slack-support-lifecycle-for-operating-systems-app-versions-and-browsers
