### ISSUE TITLE
Rambox: Mic not working

### ISSUE THREAD

**Issue by vhemdr** [ramboxapp/community-edition#3171]
Before, using microphones is working but not now. I've tried for both MS Teams and GMeet.

Steps to Reproduce:
1. Enable Custom Service - MS Teams / GMeet.
2. Login to MS Teams / GMeet.
3. Try to call a contact or start a meeting.
4. Speak during the call. Notice that you won't be heard by the others.

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.19043

**Comment by fvulich** [comment]
We couldn't reproduce this issue. Please share a video of the issue, so we can have a better picture of it.
