### ISSUE TITLE
--hidden option doesn't work

### ISSUE THREAD

**Issue by iHnR** [ramboxapp/community-edition#3172]
Short summary. When setting the app to startup minimized on system startup, it just opens normally. Similarly, when opening from a terminal using `rambox --hidden`, the app simply opens normally. It does minimize to tray when closing the window.

### Steps to reproduce

1. open terminal
2. run `rambox --hidden`

### Expected behavior

The tray icon appears, but no window is opened.

### Actual behavior

Rambox opens normally

### ENVIRONMENT

Gnome

> Rambox: v0.7.9 Linux amd64 deb installer

> OS: 'Pop!_OS 21.04'

> Arch: x64

**Comment by fvulich** [comment]
Duplicate #3132
