### ISSUE TITLE
We have sent you a message in Telegram with the code. - i dont have telegram

### ISSUE THREAD

**Issue by cxbignekoc** [ramboxapp/community-edition#3177]
Okay in the previous version i was able to use telegram, without that "we have send u..." but i am not sure how i get run it.
i accidently install the previous version because there was 2 versions installed in windows->apps.
mostly i can delete older versions but not here....
so then my rembox was completely uninstalled...dang

i reinstall new version and not found my account data (where are my buddys in and so on).
so i installed rambox new and empty. add my account and started with discord, its runnig
starting with telegram.....  

### Steps to reproduce

1. Adding Telegram
2. insert Phone number
3. issue happens

### Expected behavior
i expected that i can now use telegram like before or in the previous version.
i have no smartphone or handy with telegram is running on it wehre i can get the "code"

### Actual behavior

i dont get any message with a code, because i dont have any telegram on any phone.

### ENVIRONMENT

windows 10
old android handy

> Rambox: 
Version: 0.7.9
Platform: win32 (x64)
Electron: 11.4.10
Chromium: 87.0.4280.141
Node: 12.18.3

> OS: Win 10 64bit

> Arch: x64

**Comment by fvulich** [comment]
This issue is for Telegram support not Rambox, we can't change this behavior it's from Telegram itself..
