### ISSUE TITLE
Ms Teams can't share screen

### ISSUE THREAD

**Issue by munkid** [ramboxapp/community-edition#3179]
### Steps to reproduce

1. Join the Teams meeting
2. Start Share Screen
3. No pop up selection of screen

### Expected behavior

It should have selection of Entire screen, screen1, screen 2 and so on

### ENVIRONMENT

> Rambox: v0.7.0

> OS: Windows 10 pro Version 1909 OS build 18363.1556

> Arch: x64

**Comment by fvulich** [comment]
Duplicate #2655
