### ISSUE TITLE
Yet again the taskbar icon doesn't change to red when new messages arrive. I am tired of this... :(

### ISSUE THREAD

**Issue by 613TheEvil** [ramboxapp/community-edition#3181]
This problem is permanent on Facebook, I have lost hope of it ever being solved. But on Whatsapp, it comes and goes. Now it appeared again, for my whatsapp. New messages are sent to me, I see the popups if I am looking at the screen, but the taskbar icon remains white, no change.

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 6.1.7601

**Comment by 613TheEvil** [comment]
Closed? But... Nothing changed... I guess there is another topic open for the same problem?

**Comment by fvulich** [comment]
Restart Rambox to get the changes.

**Comment by 613TheEvil** [comment]
Thank you all done.

**Comment by OlegNT** [comment]
The same problem. Some part of new messages doesn't appear in tray icon. 
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.19044
