### ISSUE TITLE
Rambox shows a white screen when searching for files

### ISSUE THREAD

**Issue by Bishal-Mahanta** [ramboxapp/community-edition#3183]
No files or directories are recognizable

![Screenshot from 2021-12-09 12-46-22](https://user-images.githubusercontent.com/64310226/145352227-11c44ea0-87cc-47f4-a29b-3ad1bb12d9ea.png)

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> linux x64 5.13.19-2-MANJARO

**Comment by fvulich** [comment]
Try with a different package because depending on your Linux distribution some are better than the others. You can download them from [HERE](https://github.com/ramboxapp/community-edition/releases/latest) or AUR from [HERE](https://aur.archlinux.org/packages/rambox-bin/)
