### ISSUE TITLE
Hi Fernando.  Just shows a white screen when the app launch. #3085

### ISSUE THREAD

**Issue by Nicolay-Maker** [ramboxapp/community-edition#3186]
### Steps to reproduce

1. Running the program on a macbook
2. Shows a white screen window
3. 

### ENVIRONMENT
![images 2021-12-10 at 14 03 02](https://user-images.githubusercontent.com/74589116/145564168-60ec7497-1818-4dcf-ad32-4cb7262809e2.jpg)

> Rambox: v0.7.8 Mac

> OS: X YOSEMITE v10.10.5

> Arch: x64 or ia32

**Comment by fvulich** [comment]
Try following this tutorial, and all the help that I can give you is in your other issue.
https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall
