### ISSUE TITLE
Menu about logout doesn't show up

### ISSUE THREAD

**Issue by krapans** [ramboxapp/community-edition#319]
When I click on my profile, it just shows that small white circle.
[Image](http://image.prntscr.com/image/8a01694005164b65874f95a87281b4b0.png)

## 

> Rambox 0.4.2
> Electron 1.3.5
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Did you updated from 0.4.1 and was already logged in?

**Comment by artukrap** [comment]
Yes

**Comment by saenzramiro** [comment]
Please try opening DevTools and remove all in your LocalStorage. Then Reload Rambox and login again.

**Comment by artukrap** [comment]
I haven't tried that, but when I deleted all rambox files from my users folder, it helped.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
