### ISSUE TITLE
GMail won't allow sign in

### ISSUE THREAD

**Issue by aRcHmaGe333** [ramboxapp/community-edition#3190]
GMail says the browser is not secure. 
It's probably their new system of using the phone to ask if it's you signing in. 

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.19042

**Comment by mcopik** [comment]
Same problem here - Google services no longer allow signing in.

**Comment by matgardon** [comment]
same here

**Comment by albolea** [comment]
same here

**Comment by marrws** [comment]
I'm using Firefox's UA string:

`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0`

And I can login successfully into gmail.

Go to `File > Preferences > Override User-Agent for all services (needs to relaunch)` and paste a UA string from an up to date browser in your machine. You can get your current UA string using duck duck go -> https://duckduckgo.com/?q=user+agent

---

The optimal solution would be to build Rambox using a newer version of Electron that uses a newer version of Chromium, [ie: 16.0.0](https://github.com/electron/electron/releases/tag/v16.0.0).

_Originally posted by @marrws in https://github.com/ramboxapp/community-edition/issues/3187#issuecomment-1010383314_

**Comment by Rohan-Thoma** [comment]
For all the users for whom the user agent trick is not working, they should allow for less secure app access for google account in their google settings as shown in the given below tutorial...
https://support.reolink.com/hc/en-us/articles/360003525833-How-to-Allow-Less-Secure-Apps-to-Access-Your-G-mail-Account
This has worked for me.

**Comment by saenzramiro** [comment]
Duplicate #3187
