### ISSUE TITLE
Unsupported browser

### ISSUE THREAD

**Issue by iscsolitario** [ramboxapp/community-edition#3192]
When trying to enter gmail from rambox, the google site tells me the following:

Login failed
The browser or application may not be secure.

I hope you can help me.

Best regards

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> win32 x64 10.0.19044

**Comment by girtsl** [comment]
Same issue here. Signed out of an account and can't log back in. Other accounts continue to work.
The workaround described in #2495 - setting a different UA string - didn't work. Tried the UA string from the latest Chrome version - `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`.

**Comment by girtsl** [comment]
FWIW, the workaround mentioned in #3187 - setting the UA string to `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/96.0` worked.

**Comment by saenzramiro** [comment]
Duplicate #3187
