### ISSUE TITLE
Gmail cannot login

### ISSUE THREAD

**Issue by baz8ka2th** [ramboxapp/community-edition#3200]
After inputting my gmail username and pressing next I get the following error message:
"Couldn't sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can try again to sign in."

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> linux x64 5.15.13-zen1-1-zen

**Comment by LeSnake04** [comment]
Does it work after realoading the page? Often it works then

**Comment by baz8ka2th** [comment]
Unfortunately not, even after restarting the app and even after a system
restart as well as attempting a system update.

**Comment by massiws** [comment]
Same problem on Linux Mint after a kernel upgrade (loosing Rambox config).
Solved changing User Agent as described in #3187 .

**Comment by Rohan-Thoma** [comment]
Just allow for less secure app access in the google settings as shown in the given below tutorial
https://support.reolink.com/hc/en-us/articles/360003525833-How-to-Allow-Less-Secure-Apps-to-Access-Your-G-mail-Account

**Comment by saenzramiro** [comment]
Duplicate #3187
