### ISSUE TITLE
Not able to have multiple WhatsApp instances

### ISSUE THREAD

**Issue by khalilayache** [ramboxapp/community-edition#3207]
### Steps to reproduce

1.  Configure one WhatsApp account
2. Configure a second one (doesnt matter if is Business or dont)
3. Change to first WhatsApp account tab

### Expected behavior

You are being able to access the n different WhatsApp accounts

### Actual behavior

When you logged in on second WhatsApp account and change to tab for the first one, the first one was logged out and when you refresh the tab the second account is load

### ENVIRONMENT

> Rambox: v2.0.1

> OS: Mac and Windows

> Arch: x64 or ia32

**Comment by fvulich** [comment]
If you are using v2.x.x, please refer to support@rambox.app.

In the new Rambox, we introduce profiles. You can create a profile for a group of apps, let say that you create a Work profile where you get logged to Gmail using your work credentials, then you can add, let say, a Google Drive app anywhere in Rambox and assign to it the Work profile, and it will get logged using those credentials.

Also, you can set a profile scheme for a workspace and all apps that are in it (and have the "inherit from Workspace" setting, by the way, is the default for nested apps), a certain profile or private if you want that all nested apps have their own profile.
For apps like WhatsApp, Telegram or Android messages, we recommend the private profile (isolated per app). In v2.0.1 this is the default when adding them.


You can read a bit more in https://rambox.app/feature/session-manager
