### ISSUE TITLE
Unable to open different gmail accounts.

### ISSUE THREAD

**Issue by ArjunTheArcher** [ramboxapp/community-edition#3209]
Hi team, great work. I am not able to open different gmail accounts in different tabs. All tabs are having the same gmail account. Please support in this issue.

**Comment by fvulich** [comment]
If you are using v2.x.x, please refer to support@rambox.app.

In the new Rambox, we introduce profiles. You can create a profile for a group of apps, let say that you create a Work profile where you get logged to Gmail using your work credentials, then you can add, let say, a Google Drive app anywhere in Rambox and assign to it the Work profile, and it will get logged using those credentials.

Also, you can set a profile scheme for a workspace and all apps that are in it (and have the "inherit from Workspace" setting, by the way, is the default for nested apps), a certain profile or private if you want that all nested apps have their own profile.
For apps like WhatsApp, Telegram or Android messages, we recommend the private profile (isolated per app). In v2.0.1 this is the default when adding them.

Also, you can use different Gmail accounts in the same profile, and once you get your desired email in the app you can set that URL as the app's default.
![image](https://user-images.githubusercontent.com/46904390/151987159-6eb45aa7-18e0-4ea0-93b2-355faf26d023.png)


You can read a bit more in https://rambox.app/feature/session-manager

**Comment by ArjunTheArcher** [comment]
Thanks for the support, Rambox Team. We will check & revert.
