### ISSUE TITLE
Usage of multiple Microsoft Teams Instances

### ISSUE THREAD

**Issue by christophberinger** [ramboxapp/community-edition#3210]
### Steps to reproduce

1. Create a MS Teams Instance, log in (Option "Keep me signed in" does not matter)
2. Create another MS Teams Instance that uses a different account, log in

### Expected behavior

Each MS Teams Instance should show the app content for the respective account. Should be possibe to use different accounts here

### Actual behavior

Different MS Teams instances show the content of the same account, so usage of different accounts is not possible

### ENVIRONMENT

> Rambox: v2.0.1

> OS: BigSur 11.6

**Comment by fvulich** [comment]
If you are using v2.x.x, please refer to support@rambox.app.

In the new Rambox, we introduce profiles. You can create a profile for a group of apps, let say that you create a Work profile where you get logged to Gmail using your work credentials, then you can add, let say, a Google Drive app anywhere in Rambox and assign to it the Work profile, and it will get logged using those credentials.

Also, you can set a profile scheme for a workspace and all apps that are in it (and have the "inherit from Workspace" setting, by the way, is the default for nested apps), a certain profile or private if you want that all nested apps have their own profile.
For apps like WhatsApp, Telegram or Android messages, we recommend the private profile (isolated per app). In v2.0.1 this is the default when adding them.

You can read a bit more in https://rambox.app/feature/session-manager
