### ISSUE TITLE
Google apps won't log in

### ISSUE THREAD

**Issue by brinesharks** [ramboxapp/community-edition#3219]
Google Calendar and Google Hangouts won't allow login via Rambox. Message says browser is out of date.

	
	-
	> Rambox 0.7.9
	> Electron 11.4.10
	> linux x64 5.3.18-150300.59.46-default

**Comment by marcelb** [comment]
Same here.

Version: 0.7.9
Platform: win32 (x64)
Electron: 11.4.10
Chromium: 87.0.4280.141
Node: 12.18.3

**Comment by Rohan-Thoma** [comment]
Just allow less secure app access in the google settings as shown in the given below tutorial
https://support.reolink.com/hc/en-us/articles/360003525833-How-to-Allow-Less-Secure-Apps-to-Access-Your-G-mail-Account

**Comment by liwenjing93** [comment]
Same here for Google Mail.

I hope dev team could take some time fix it. @saenzramiro

**Comment by saenzramiro** [comment]
Duplicate #3187
