### ISSUE TITLE
[Feature Request] Away Lock

### ISSUE THREAD

**Issue by rdsu-pt** [ramboxapp/community-edition#334]
Hi,

Can you make an option to auto-block Rambox after a specified time interval of inactivity?

Something like Signal gave on their android app.

Thanks!
## 

> Rambox 0.4.2
> Electron 1.3.5
> win32 x64 10.0.10586

**Comment by saenzramiro** [comment]
I tried to do this but the libraries for Node JS that provide this functionality are not stable. I think we will need to wait until we find a library to handle this.

**Comment by ruiumbelino** [comment]
Thanks for let us know.

Keep the good work!

**Comment by andrey-yantsen** [comment]
Can anyone please explain me, what is the reason to have away lock in desktop application? If you would like to protect your chats — just lock your computer. Almost any OS can do it with easy-to-remember hotkey.
Also, you can configure your computer to auto-lock after few minutes of inactivity.

**Comment by ruiumbelino** [comment]
It's useful if you share your computer account at your home or work...

**Comment by andrey-yantsen** [comment]
Hey, you shouldn't hide anything on your home computer :) Anyway: it's much better to have different users (at work or even at home). IMO only couple types of apps should be able to lock on your desktop: your password manager and any money-related staff. Multi-userness is awesome! People can have different wallpapers, and even different OS behavior preferences — it all can be done with multiple users. You can even forbid your wife to install applications! :)
Also, if you're caring about your chat's privacy — don't you care about privacy in other parts of computer usage? Even your web-browser knows much more than Rambox about your activity.
Most stand-alone messaging apps I know also have no lock-compatibility: Slack, Skype, even thousands ICQ clients, all of them relies on OS in case of protecting your privacy.

**Comment by ruiumbelino** [comment]
I know what you are talking about, but to give you an example, I need to share my desktop, through Remote Desktop, and sometimes they could click on Rambox by accident, and see something private...

Or I could live my account unlocked, and could define a less away lock timer than auto windows lock timer...

For me is useful.

**Comment by andrey-yantsen** [comment]
That makes sense, thank you.

**Comment by pandruszkow** [comment]
I second the argument about just locking your user account.

If you're about to share your desktop, you'll need to go through all your open applications to close anything private anyway.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
