### ISSUE TITLE
About the Updater

### ISSUE THREAD

**Issue by nachog4** [ramboxapp/community-edition#346]
There's seems to be something odd about the Updater

![image](https://cloud.githubusercontent.com/assets/14312852/18586080/09941f50-7c1b-11e6-9dce-adba34b03090.png)

**Comment by saenzramiro** [comment]
Rambox use Squirrel for Windows to make the auto update. I don't know how the process works.

Maybe this issue needs to be posted in Squirrel.Windows Github repo.
