### ISSUE TITLE
Javascript Crash

### ISSUE THREAD

**Issue by Vidarius** [ramboxapp/community-edition#348]
Version: 0.4.2 (portable)
Platform: win32 (x64)
Electron: 1.3.5
Chromium: 52.0.2743.82
Node: 6.3.0

> https://abload.de/img/faild6r1s.jpg
> https://abload.de/img/fail2iwp5j.jpg

**Comment by saenzramiro** [comment]
What version of Windows are you using?

**Comment by Vidarius** [comment]
Windows 10 10586.1511 and 14393.1607

**Comment by Ash258** [comment]
Continue in #1656
