### ISSUE TITLE
Javascript error when checking for updates- command failed: 4294967295

### ISSUE THREAD

**Issue by BuildTheRobots** [ramboxapp/community-edition#352]
### Steps to reproduce
1.  Open Rambox
2.  See error. 
3. Close error box.
4. "Check for updates"
5.  Get error again
### ENVIRONMENT

> Rambox: v0.4.2
> 
> OS: Windows 10 64bit (anniversary update).
> 
> Arch: x64

This error only started occuring after installing the windows 10 anniversary update. I have since tried reinstalling Rambox but it still errors on startup and when manually checking for updates.

![rambox jserrorupdate1](https://cloud.githubusercontent.com/assets/5307527/18639574/5ad6e4b0-7e8c-11e6-9fde-904535efc0bd.PNG)
![rambox jserrorupdate2](https://cloud.githubusercontent.com/assets/5307527/18639575/5ae33210-7e8c-11e6-9d50-bd522fa698f4.PNG)

**Comment by saenzramiro** [comment]
Yes, I had this error in my PC. I think it happens when Heroku Update server is down or something like that. I will check this.

**Comment by BuildTheRobots** [comment]
Thank you for looking into it. I was just coming back to say that the issue seems to have disappeared and that I can't reproduce. Issues on the server end would make perfect sense :)

**Comment by zeitnger** [comment]
A mi me pasa exactamente lo mismo....
