### ISSUE TITLE
Skype Problems - Mac

### ISSUE THREAD

**Issue by mdudhani** [ramboxapp/community-edition#355]
Provider: Skype
Platform: Mac
Version: El Capitan 10.11.6

Skype sometimes doesn't send or receive any messages until done a manual refresh. Generally happens after sleeping/hibernating Mac. 

Rest all work. Very nice app. Awesome job!

## 

> Rambox 0.4.2
> Electron 1.3.4
> darwin x64 15.6.0

**Comment by Vakhrushev** [comment]
Confirm.
If send message from browser work, but rambox does not.
Rerun rambox, does not help
No sleep or hibbernate 

```
Version: 0.4.4
Platform: linux (x64)
Electron: 1.4.1
Chromium: 53.0.2785.113
Node: 6.5.0

uname -a                                                                                                                           
Linux UWC 4.7.6-1-ARCH #1 SMP PREEMPT Fri Sep 30 19:28:42 CEST 2016 x86_64 GNU/Linux

```

**Comment by urbels** [comment]
Same for me. Also sometines it goes offline every 5 min or so. Or shows that I have 1 new notification but I doesn`t.

**Comment by Nidre** [comment]
Same happening here. Not sure if it is a Skype issue or RamBox issue but I can't get most of the new messages throughout day. I realize I've them when I force refresh Skype tab on RamBox or check my mobile. Started to happen approx 7-10 days ago. 

Maybe related to new Skype release on mobile? API changes?

Version: 0.5.9
Platform: win32 (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by saenzramiro** [comment]
We don't do nothing for Skype to "sleep or hibernate". I think it's a Skype bug.

A temp fix is make an automatic reload of the service every X time, like:
https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
