### ISSUE TITLE
[Feature Request] New service Discourse

### ISSUE THREAD

**Issue by jurgenhaas** [ramboxapp/community-edition#362]
More and more projects seem to be utilising Discourse (see https://github.com/discourse/discourse) as their forum and support platform. It is possible to add any Discourse URL as a custom service. The only problem seems to be that the tray icon is always showing a notification if a new post or comment is available, even if notifications are turned off for those services.

Therefore it would be great it Rambox could integrate Discourse natively. What do you think?

**Comment by ric2b** [comment]
+1

**Comment by tareko** [comment]
As a note here, while Rambox doesn't integrate discourse "natively", it's very easy to add a discourse instance by using a custom. All this requires additionally is the link to an icon. Even the unread counter works well. It would be great if this were automated, but it still works well in the current state.

**Comment by mdbraber** [comment]
@tareko regarding the unread counter: what code have you used to check for unread msgs?

**Comment by tareko** [comment]
No additional code needed! It "just works"

**Comment by mdbraber** [comment]
Hmm - I might have missed something than, it didn't for me so I just quickly cobbled up this code:

`function checkUnread() {
    var a = 0;
    var b = 0;

    if (document.querySelector(".widget-link.badge-notification.unread-private-messages")) {
        a = parseInt(document.querySelector(".widget-link.badge-notification.unread-private-messages").title, 10);
}

    if (document.querySelector(".widget-link.badge-notification.unread-notifications")) {
        b = parseInt(document.querySelector(".widget-link.badge-notification.unread-notifications").title, 10);
}

updateBadge(a+b);
}

function updateBadge(e) {
    e >= 1 ? document.title = "(" + e + ") " + originalTitle : document.title = originalTitle
}
var originalTitle = document.title
setInterval(checkUnread, 3000);`

**Comment by tareko** [comment]
Very cool. I didn't need this, but looks great. Also, it gives a great hint about how to do this for other services!

**Comment by Mte90** [comment]
+1

**Comment by KajKandler** [comment]
Does anybody know how to use discourse with an OAuth2 login, lets say "with Google" or "with GitHub"? When I click, the authentication goes to the default browser and that has no effect.
