### ISSUE TITLE
High cpu usage and slow keyboard response

### ISSUE THREAD

**Issue by kvannotten** [ramboxapp/community-edition#366]
### Steps to reproduce
1. Use version 0.4.4 on linux
2. Try to type anything in any chat window (tested with hipchat, whatsapp, flowdock)
3. There's visible +100ms lag with every keystroke
### Expected behavior

For there to be no lag when typing.
### Actual behavior

There's lag when typing + the cpu usage is very high (60-100% on 1 core, tested on a skylake 6600k)
### ENVIRONMENT

> Rambox: v0.4.4
> 
> OS: Arch Linux
> 
> Arch: x64

EDIT: changed the title, since it doesn't seem to be OS specific

**Comment by andrey-yantsen** [comment]
Same lag on macOS 10.12. Tested in Slack.

**Comment by jbbr** [comment]
I can't notice a lot's of lag. I'm also on Arch Linux with latest Rambox 0.4.4

When pressing a key in a chat window an keep in pressed, I get around 18-20% on a single core, Haswell 4570

But I get the same in other electron apps e.g skype for linux or even more: ~40% when doing this in Atom.

**Comment by Koenig70** [comment]
Same here, slow keyboard response in Linux (Xubuntu). All previous versions were pretty good. 

Rambox 0.4.4
Xubuntu 16.04
Arch: 32

**Comment by unixfox** [comment]
Same behavior with CPU usage of Rambox increases when typing something.
Maybe it's related to Electron.

**Comment by KonradHolubek** [comment]
+1 Same issue here on Mac OS (10.11.6). Can I please download the older version of Rambox in the meantime because this is making me lose enormous amount of time ?

**Comment by unixfox** [comment]
@KonradHolubek https://github.com/saenzramiro/rambox/releases/download/0.4.2/Rambox-0.4.2.dmg

**Comment by Alexus230** [comment]
+1 Same issue on Ubuntu

> Rambox 0.4.4
> Uubuntu 16.04
> Arch: 64

**Comment by MrChick** [comment]
My 0.4.4 on Win10 1607 Enterprise feels pretty sluggish as well, especiall yon whatsapp web and kiwiirc

**Comment by nobol** [comment]
Also on arch linux, same error, but only on slack!

**Comment by clementlamoureux** [comment]
On Ubuntu 16.04, same problem on Skype & Slack mostly

**Comment by soulchainer** [comment]
Same here. Same problem in Arch Linux. Is most noticeable in Messenger, but also happens in Tweetdeck.

> Rambox: 0.4.4
Platform: linux (x64)
Node: 6.5.0
Arch Linux

**Comment by bascht** [comment]
Looks like it could be caused by the tooltip.io Overlay. I did a quick JS profile (via Chrome DevTools):

![screenshot from 2016-09-27 17-25-33](https://cloud.githubusercontent.com/assets/51264/18880242/873567a6-84d7-11e6-9140-e10e66c5228b.png)

**Comment by jbbr** [comment]
Now I have the problem too. CPU is on 80% even when not typing.

I also did a JS profile and have the same stack causing this problem as @bascht

**Comment by unixfox** [comment]
Same for me, Rambox is using 70% of the CPU without typing anything :/.

**Comment by dtoebe** [comment]
Rambox Bouncing from 3% CPU to 75% CPU after update 

- OS: Arch Linux x64
- Installed From: AUR
- Desktop: KDE Plasma 5
- Rambox Version: 0.4.4
- Electron: 1.4.1
- Chromium: 53.0.2785.113
- Node: 6.5.0

**Comment by jbbr** [comment]
I just downgraded to 0.4.2 and after some time the problem occurred again.

As tooltip.io is loaded from an external server - maybe it's not related to the upgrade but changes by tooltip.io or due to problems with pushed tooltips?

Can someone else confirm that this problem is not going away with downgrading? (Keep in mind: It takes a while after opening rambox until the CPU spikes begin)

**Comment by soulchainer** [comment]
@jbbr I can confirm it. In fact, I already had a comment written, waiting to be published after recheck this. In my case, CPU don't spikes (about 10%, octacore, 7 services in Rambox), but keyboard entry **so slow**. It takes time, but it gets slow after that. But I didn't measure the tme. I left the PC alone and after an hour or so, it was so slow. And, obviously, before it wasn't like this.

**Comment by jbbr** [comment]
@soulchainer thanks for confirming. Then I will upgrade the AUR package again as keeping it on the old version doesn't fix this issue.

**Comment by KonradHolubek** [comment]
+1 I confirm

**Comment by nobol** [comment]
I just deleted all js which comes from cdn.tooltip.io. Simply got to sources, select the content from cdn.tooltip.io, set a breakpoint at the first line, reload and when the breakpoint is reached, delete all content of the file. Then the CPU drops again to the usual level.
![screenshot from 2016-09-27 22-10-51](https://cloud.githubusercontent.com/assets/7189919/18890012/db4fddf8-84ff-11e6-8c3e-0c6250377bd2.png)

**Comment by unixfox** [comment]
I temporally fixed the issue by setting my hosts file to:
````
127.0.0.1 cdn.tooltip.io
127.0.0.1 tooltip.io
```

**Comment by nobol** [comment]
@unixfox "solution" is better than mine, as the tooltip stuff get's reloaded after some time (don't know why)

**Comment by adambro** [comment]
Same for me, I've also pin down tooltip.io as the offender. Hack with /etc/hosts helped. Xubuntu 14.04 64bit.

**Comment by MrChick** [comment]
hosts-Hack helped here as well, thanks!

**Comment by bascht** [comment]
Quick update: I nudged Tooltip.io on Twitter – they're [looking into it](https://twitter.com/tooltipio/status/781074314237992960).

**Comment by FValetudie** [comment]
Noticed the same problem on Ubuntu Gnome 14.04, Rambox 0.4.4.
@unixfox 's temporary solution (editing hosts) seems to be enough for now (got down from 70% of the CPU to 0 to 5% depending on the moment).

I guess it's not related (probably 100% facebook's fault) but when Facebook messenger tab is focused, CPU jumps to 20%.

**Comment by KonradHolubek** [comment]
But how can I apply this solution to my Mac app ... ?

**Comment by andrey-yantsen** [comment]
@KonradHolubek almost same way: open Terminal.app and type `sudo open /Applications/TextEdit.app /etc/hosts`, it will ask your password and then open TextEdit.app with contents of file /etc/hosts.

**Comment by andrey-yantsen** [comment]
@KonradHolubek one more try :)
Almose same way: open Terminal.app and type `sudo vi /etc/hosts`, navigate to the last line of the file with arrows, type `o` and paste ```
127.0.0.1 cdn.tooltip.io
127.0.0.1 tooltip.io```
After this hit ESC couple times, enter `wq` and hit return.

**Comment by saenzramiro** [comment]
Thank guys for the temporary solution. 

I just removed one of the tooltips of Tooltip.io that I created for 0.4.4. Can anyone relaunch Rambox and check if keeps using a lot of CPU?

**Comment by kvannotten** [comment]
@saenzramiro  I tested it for a few minutes now and it seems to be fine. However, the problem might still occur when the application is running a bit longer. I will get back to you if it does.

Regardless of that, whenever I am typing, rambox's cpu usage still seems to spike a bit (from 1-2% to 20-40%). I'd like to think I'm super fast and my computer has problems following my instructions, but that probably unlikely :smiley:

**Comment by unixfox** [comment]
@saenzramiro Same results as @kvannotten

**Comment by samuba** [comment]
same Problem on Windows

**Comment by va-al** [comment]
same problem, ArchLinux x64, previous builds is pretty

**Comment by dare023** [comment]
Confirming issue.
All used tabs/services affected, skype almost unusable, slack and whatsapp lags, evernote and rambox also.
OS: Arch Linux x64
Installed From: AUR
Desktop: KDE Plasma 5
Rambox Version: 0.4.4
Electron: 1.4.1
Chromium: 53.0.2785.113
Node: 6.5.0

**Comment by saenzramiro** [comment]
Can anyone also confirm if running `Tooltip.API.stop();` in the console will improve Rambox performance?

**Comment by clearmisp** [comment]
I did Tooltip.API.stop() in the console and have now been running Rambox a couple of hours without seeing any increase in CPU usage, the performance seems to be much better.

**Comment by bascht** [comment]
I'm back on 0.4.4, without the `/etc/hosts` file hack and so far everything is smooth. In case CPU starts boiling again, I'll try the `Tooltip.API.stop()` trick and will report back. :)

**Comment by texpert** [comment]
Tooltip.API.stop() immediately improved CPU usage and eliminated keyboard lag.

**Comment by jurgenhaas** [comment]
I have had that issue as well. After a couple of hours, Rambox just stalled and kept one of my 8 cores busy all the time. Shutting down and starting Rambox again "solved" the issue for a while.

Yesterday, I re-enabled hardware acceleration and restarted Rambox. It behaves nicely ever since. Let's see if that has an effect on the long run.

**Comment by kvannotten** [comment]
Been running with the `Tooltip.API.stop()` trick for a couple of hours now, and it seems to be the culprit. Runs much better now.

**Comment by jduzan** [comment]
Tooltip.API.stop() removed keyboard lag, and improved cpu usage.
will post back if it change on the long run

**Comment by dare023** [comment]
Tooltip.API.stop()
works, everything seem to work nice now.

**Comment by jbbr** [comment]
I haven't had any problems since your server-side change.
0.4.4, no hosts fix. Usual CPU usage over the day.
Thanks!

**Comment by saenzramiro** [comment]
In my main PC (Windows 10 x64), Rambox always works ok and normal CPU and RAM usage. I never had to stop Tooltip.io or block requests in hosts file.

I think in some cases this problem exist.

**Comment by Pablohn26** [comment]
Confirming issue.
OS: Fedora 24  x64
Installed From: RPM
Desktop: Cinnamon 3.0.7
Rambox Version: 0.4.4
Electron: 1.4.1
Chromium: 53.0.2785.113
Node: 6.5.0

Running `Tooltip.API.stop()` drop me the next:
> Tooltip.API.stop()
> undefined

Not sure if it is ok, and not sure if it works.

**Comment by saenzramiro** [comment]
@Pablohn26 Are you blocking Tooltip.io from hosts file?

**Comment by Pablohn26** [comment]
@saenzramiro no, I do not. I hope a fix rather than that kind of workarounds.. I cannot reproduce easily a delay of keyboard response but I have seen a huge increase of resources from Rambox.

**Comment by dare023** [comment]
Actually, it works same at mine also
`Tooltip.API.stop()
undefined`
But I am noticing also this error
`Uncaught TypeError: Cannot read property 'fireEvent' of undefined (program):1 `
This is without hosts block, with block I get 
`Failed to load resource: net::ERR_CONNECTION_REFUSED`
but not that other error

**Comment by saenzramiro** [comment]
@dare023 The Uncaught error, I know that it is, is not important. I will fix it for the next release.

**Comment by pluma** [comment]
Just chiming in to say that the current release (on Ubuntu 16.04 LTS) is extremely sluggish for me too, including scrolling on the start screen (although the initial loading/teaser animation runs smoothly).

I have experienced similar problems with the (electron-based) Slack desktop client but not other electron apps (Skype Beta, Franz, Unofficial Google Play Music) so I'm not sure what could be causing it.

**Comment by saenzramiro** [comment]
We have to make an investigation why this problem is happening.

@pluma Are you using Arch Linux also?

**Comment by pluma** [comment]
@saenzramiro No, I'm on Ubuntu. However the problem went away after a reboot so I'm not sure what caused it. As I said, other electron-based apps and Chrome were unaffected.

**Comment by saenzramiro** [comment]
Ok, the difference here is that we use Rambox to run a lot of services inside. That of course takes a lot of RAM (less than if you run it in Google Chrome).

This problem is related with the services the user is running inside Rambox, and what kind of service.

**Comment by pluma** [comment]
@saenzramiro I have four physical cores and 32 gigs of RAM. I doubt Rambox should justifiably degrade performance in a way that causes scroll stuttering when e.g. Franz is doing fine.

Note that I also experienced this out of the box before adding any services.

**Comment by dare023** [comment]
@saenzramiro: I use it on Arch, latest Rambox.
Works fine on laptop and desktop I have couple slack accounts, skype, WhatsApp, Evernote and gistbox. I did not notice anything strange so far.
Except  that icon in icon-only task  manager is wrong on the desktop, while on the laptop is the correct one.
But I am ok with that as long rest of things work ok

**Comment by saenzramiro** [comment]
@pluma Ok, you are right. I don't remember if I told you to turn on *Disable Hardware Acceleration (needs to relaunch)" in Preferences and see if works ok.

@dare023 Thank you for the info.

**Comment by dare023** [comment]
@saenzramiro No problem, I forgot to say I have hosts block for tooltip.io

**Comment by bretterer** [comment]
Having this issue.  Rambox Helper is using 100% CPU most of the time.  Restarting does not help.  Causes lots of lag on system with keyboard and mouse. Also causes system to be laggy
<img width="866" alt="screen shot 2017-09-15 at 1 24 48 pm" src="https://user-images.githubusercontent.com/1906920/30495374-c469c326-9a19-11e7-98ba-4dbd9227f287.png">

Rambox Info

Version: 0.5.12
Platform: darwin (x64)
Electron: 1.7.5
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by SaswatPadhi** [comment]
Same issue for me too. Even when the window is minimized, it uses 100% CPU (one core).

![screenshot from 2017-10-18 19-47-00](https://user-images.githubusercontent.com/1577944/31751964-5382fbbc-b43d-11e7-8910-87aeb0dd1b74.png)

Version: 0.5.13
Platform: Ubuntu 17.10 (x64)

**Comment by bhanquier** [comment]
Same issue all of a sudden. Never had this problem before. It makes the system virtually inoperable and Rambox unusable. 
![capture d ecran 2017-10-19 a 12 13 46](https://user-images.githubusercontent.com/6447099/31768377-1355b838-b4c7-11e7-9cca-363f02938ae7.png)
 
Version: 0.5.13
Platform: darwin (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by highintothesky** [comment]
same issue here on 0.5.13, linux mint 18.1. its use of both RAM and CPU resources is about 3 times as high as ~15 firefox tabs combined. tabs used are whatsapp, telegram, and fb messenger.

**Comment by rafalenden** [comment]
I think this is not caused by the Rambox code itself, the same thing happens in the Franz app: https://github.com/meetfranz/franz/issues/24

When I run messenger.com in the browser then Chrome Helper doesn't use so much CPU so I suspect that the issue is related to Electron.

**Comment by daimpi** [comment]
If this is only happening to you with Facebook Messenger active, there is a new open issue specifically on this problem: #1248

**Comment by SaswatPadhi** [comment]
As @daimpi reported in #1248, the CPU usage seems normal now. I confirm it too.

**Comment by iamcxa** [comment]
I confirm @rafenden 's opinion. when I close Message Service in Rambox, it responds normally, no more lags.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
