### ISSUE TITLE
Signup with Google account

### ISSUE THREAD

**Issue by Skybeat** [ramboxapp/community-edition#37]
If i try to signuip and typ in my g-mail and my password and press de aignup button, i get a smal wintow with the title "Connecting...." and de message "Please wait until we get your configuration".
Then nothing more happens until i go to the Menu of Rambox "View -> Reload". 
After that i'm logged in with my google account.

**Comment by Jimi-James** [comment]
Thanks for the tip. Mine got stuck, and I didn't know how to fix it until reading this and trying View -> Reload.

**Comment by saenzramiro** [comment]
Thanks guys for this report. I will take a look for the next release.

**Comment by yafp** [comment]
@Skybeat & @Jimi-James 
is that still a valid issue or is it fixed in the current 0.5.16 version?

**Comment by Jimi-James** [comment]
Well, since it's an issue when you first sign up, and I've already done that, I couldn't really tell you. Is the reload workaround not working anymore?

**Comment by ozskywalker** [comment]
Wasn't able to reproduce this on macOS 10.13.4 with rambox 0.5.17 / electron 1.8.6 ... would say it's been solved?
