### ISSUE TITLE
Services management is buggy in last release

### ISSUE THREAD

**Issue by PofMagicfingers** [ramboxapp/community-edition#372]
### Steps to reproduce
1. Update Rambox
2. Add the new Pushbullet Service
### Expected behavior

Pushbullet service must be added
### Actual behavior

Pushbullet service is added but with wrong label, and everything go crazy
### ENVIRONMENT

> Rambox: v0.4.4
> 
> OS: Mac OS 10.11.6
> 
> Arch: x64
### More details

I updated Rambox to the last release via the DMG, added  the new PushBullet service and eveything was going crazy : 
- First pushbullet was added with wrong label
  ![capture d ecran 2016-09-28 a 11 35 32](https://cloud.githubusercontent.com/assets/469501/18908919/dd43970e-8571-11e6-964d-8a358ab02518.png)
- Then after a restart of the app, some services started to duplicate themselves :
  ![capture d ecran 2016-09-28 a 11 36 19](https://cloud.githubusercontent.com/assets/469501/18908941/f89c97f8-8571-11e6-94b1-eff26d2dfba2.png)
- After some cleaning between duplicates and renaming services to empty string to gain some space all icons were gone gray (but services were working fine when clicking on them)
  ![capture d ecran 2016-09-28 a 11 38 16](https://cloud.githubusercontent.com/assets/469501/18908959/03bc69ce-8572-11e6-82e2-1dea19ff3046.png)
- Finally during renaming, pushbullet lost (temporary) track of services alignements :
  ![capture d ecran 2016-09-28 a 11 39 14](https://cloud.githubusercontent.com/assets/469501/18909034/51aac446-8572-11e6-8322-1f1ef1e7e8d3.png)
  -> See pushbullet is aligned right on the tab bar despite being set to left

![capture d ecran 2016-09-28 a 11 39 49](https://cloud.githubusercontent.com/assets/469501/18909049/613d0072-8572-11e6-861e-b9f3f8614551.png)
-> Here everything was reset to left after renaming 1 service without any action on my side. Only on the list, on the tab bar it was as before

-> After another restart services alignements was restored as intended

After some restarts of the app all icons got colors again, no duplication, no alignement issues and everything seems to work fine. I think it's only when modifying the services that the app has difficulties to keep track of things.

Anyway thanks for the great work with this app, I was using Franz before but yours is getting more and more powerful every release, you have more services supported, and you're open source : it's perfect. 👍 

Pof.

**Comment by saenzramiro** [comment]
Thank you @PofMagicfingers for your support.

I have to redo all the synchronization code (Rambox Account), because this problems are related with that. Sorry for any problem caused, you can use it without a Rambox Account to get a more stable Rambox for now.

**Comment by PofMagicfingers** [comment]
Don't worry, if I don't touch anything, it works most of the time :joy:

**Comment by Jimi-James** [comment]
I just started getting this bug now. For me, what triggers it is moving any service to the left of my [Google] Hangouts tab, and it always starts with said moved tab being renamed to Hangouts.

**Comment by PofMagicfingers** [comment]
Really strange, for me it occurs anytime I move or rename any service, not related to hangout

**Comment by arvenil** [comment]
This killed me today. I've added 13 services, just to find out I need to re-enter passwords for every of them again after restarting app. After reading this bug report, I've decided to logout from account, but then all services got removed! Now I need to add them again and never ever press login button again. Well I give up for today.

**Comment by arvenil** [comment]
Any chance I could just restore the services and disable account, without getting services removed? At least I would be saved with re-arrangement.

**Comment by arvenil** [comment]
Or what folders I need to backup to restore app fully? Can configuration be moved from osx to linux? Which folders I need to copy?

**Comment by PofMagicfingers** [comment]
Since the account system has totally changed and now is not a two way sync but a backup restore sync, I close this ticket. It is irrelevant.

**Comment by arvenil** [comment]
@PofMagicfingers Does the new account system work? Is it safe to use it?

**Comment by PofMagicfingers** [comment]
@arvenil It works. It's basically manual, you backup a config on one side and restore the last backup on the other side.
