### ISSUE TITLE
Notificaciones Inbox

### ISSUE THREAD

**Issue by MauricioAedo** [ramboxapp/community-edition#374]
Hola Ramiro, gracias nuevamente por traernos una nueva versión siempre con mejoras.

Tengo un problema y es que las notificaciones de correo en Inbox no dejan de aparecer cada 5 segundos aproximadamente lo cual antes no ocurría.

Saludos

## 

> Rambox 0.4.4
> Electron 1.4.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
¿Podrías proveerme de pasos para reproducir el problema por favor?

**Comment by MauricioAedo** [comment]
En algunas ocasiones cuando me llega un correo la notificación se repite constantemente mientras no lo lea, otras veces. Es raro, no se como más poder darte indicaciones.

**Comment by saenzramiro** [comment]
Las notificaciones en Inbox fueron realizadas a mano en Rambox, porque Inbox no notifica nativamente cuando tienes un nuevo mail.

El código que se hizo para notificar, lo que hace básicamente es notificar cada vez que el indicador de mensajes no leídos (unread badge count) es mayor al indicador anterior. Ejemplo: cuando el indicador pasa de 1 a 2, o de 0 a 1.

Por favor, cuando te suceda este problema de nuevo, corrobora que el indicador no esté vasilando entre dos números constantemente.

**Comment by markoshorro** [comment]
A mí también me ocurre lo indicado, no sé si es el comportamiento esperado pero al menos en mi caso no es deseado. No me oscila entre diferentes valores pero sí se me repite constantemente.

**Comment by saenzramiro** [comment]
Necesito que me puedan proveer de pasos para reproducir el problema. Porque al testearlo normalmente, no me sucede lo mismo a mi.

Traten de encontrar el caso especial en que pasa ésto.

**Comment by alambike** [comment]
Hola, entiendo entonces que no es posible ver en la notificación de inbox, un resumen o el subject del correo nuevo recibido. Solo la notificación de que hay un nuevo mensaje, pero no habría posibilidad de tener acceso a su contenido, no?

**Comment by saenzramiro** [comment]
No, las notificaciones de Inbox como algunos pocos otros servicios, las tenemos que generar manualmente porque dichos servicios nos tienen ésta funcionalidad.

Aclarado eso, nos es muy complicado poder detectar qué mensaje nuevo es el que llegó, obtener el mensaje y mostrarlo como notificación. Ésto generalmente lo hacen los mismos servicios.

**Comment by wmertens** [comment]
Hijacking this issue :) Inbox unread count is not correct - it shows the count for the current view, not the total unread emails. Maybe there is some internal API to get the correct count?
