### ISSUE TITLE
Download of Files in slack doesn't work

### ISSUE THREAD

**Issue by mr-gosh** [ramboxapp/community-edition#380]
if i want to download a file in slack - it opens a new tab in the standard browser and is not directly downloading...

## 

> Rambox 0.4.4
> Electron 1.4.1
> linux x64 4.4.0-38-generic

**Comment by DustinWoods** [comment]
The issue here is because your session in your browser is not the same as in Rambox. This is an issue in Office 365 too, if you want to download an email attachment.

One solution may be to add support for downloading files in the same window. I don't know about services that try to open in new windows though.

**Comment by saenzramiro** [comment]
@DustinWoods Right, that's the solution, But I have to add a handler to open some URL (because other URL's needs to be opened in the default browser) in a popup window inside Rambox.

**Comment by Mte90** [comment]
This problem is very boring :-(

**Comment by yumyo** [comment]
Same here on Mac OSX El Capitan

**Comment by daviddewhurst** [comment]
Does not save preferences for folder download on High Sierra.

**Comment by mitchkramez** [comment]
I had this issue as well on MacOS High Sierra - re-choosing my download folder in the Preferences -> Advanced rectified the issue. #probablysandboxing

**Comment by HeinoLengfelder** [comment]
MacOS Sierra: I had this issue as well. Had to re-choose my download folder after every new startup of slack. Works fine in Firefox.

**Comment by FlorianLudwig** [comment]
@mitchkramez @HeinoLengfelder I cannot find any download-folder option. Is it gone? Would love to have a workaround for this.

```
Version: 0.5.16
Platform: linux (x64)
Electron: 1.8.3
Chromium: 59.0.3071.115
Node: 8.2.1
```

**Comment by mitchkramez** [comment]
@FlorianLudwig on mac, it's under settings -> advanced. In my case, I abandoned the mac app store version (because it kept breaking), and just using the stand-alone installer. It's been working fine for me since the switch.

I don't think that'll be helpful for your situation though :(

**Comment by caseytp** [comment]
Checking in to see if I can help. Can anyone confirm if this is still an issue?

**Comment by bnagamalla** [comment]
I am not able to download on Mac even after re choosing the downloads directory from Advanced options
