### ISSUE TITLE
Gmail, blank window open when I want to see recent added contact window

### ISSUE THREAD

**Issue by MaikoID** [ramboxapp/community-edition#399]
Receive an email from a new contact, added it with the Add Contact from drop down menu bellow Google+ Profile Picture (top right).
In the message of  success, click in see contact details.
The blank window opens.
Ubuntu 16.04

Always reproducible even when I make a reload, or reload current service.

## 

> Rambox 0.4.4
> Electron 1.4.1
> linux x64 4.4.0-38-generic

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
