### ISSUE TITLE
Add privacy settings options

### ISSUE THREAD

**Issue by magicvince** [ramboxapp/community-edition#416]
We noticed that our uses are tracked by google analytics and others.
Is it possible in the next version to add privacy settings to agree or not tracking use?

**Comment by saenzramiro** [comment]
Sure. we must add it.

Just for the record, the data tracked is only on how many people use each service and Rambox.

**Comment by magicvince** [comment]
Thanks for your answer and the adding of the options in milestone 1.0.0

**Comment by pmgouveia** [comment]
And what about https://auth0.com/ ? it seems its also tracking all the rambox users...

**Comment by saenzramiro** [comment]
auth0 don't track anything, just we use it to store users configurations.

**Comment by jfml** [comment]
Yes, please!

**Comment by albjeremias** [comment]
and what about google analytics? 
https://github.com/saenzramiro/rambox/blob/84aebd19e625c5fb3962c3f0c297f2b59516c94c/app/view/main/MainController.js

**Comment by Ash258** [comment]
#1712
