### ISSUE TITLE
Slack did not show new message the Rambox tray icon

### ISSUE THREAD

**Issue by thowmeng** [ramboxapp/community-edition#421]
Unlike new email (GMail/Yahoo) which able to show the number on incoming message on the Rambox tray icon, New Slack message show nothing on the icon (For Franz it will show a Red Dot for Slack on incoming message)

## 

> Rambox 0.4.4
> Electron 1.4.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
PM on Slack shows a badge with a number and groups messages with a dot. Groups messages will not change the tray icon.

**Comment by codeweb** [comment]
Hi it will be useful also for Groups message (green color instead of red?)

**Comment by nmat** [comment]
https://github.com/saenzramiro/rambox/pull/806 see this pull request for the work in progress of changing the icon.

**Comment by codeweb** [comment]
Ok you can close this issue.
