### ISSUE TITLE
Feature request: Unified messages view

### ISSUE THREAD

**Issue by bendikl** [ramboxapp/community-edition#422]
Hi guys, I`m not sure where to discuss feature requests so here we go, got a few ones.

I think it would be very beneficial to have a unified "Home" view that consolidates all recent messages, you could defer them so they disappear from the view, and only important ones you want to follow up on will stay. You could even group multiple services into separate "streams". E.g. Work, Personal, Project2

This would add lots of benefits as more and more of us are involved in multiple projects and multiple tools per project. In this way you could see whats going on quickly and remove noise in an efficient way.

Here are some feature ideas:
1. Streams (Need to either save last notifications (intercept notifications first?) in localstorage for display in separate view, or via DOM-extraction from each service tab. You could make a standardized stream with a standard message-format. Then you could make adapters for each service to connect to the streams. In this way you can roll out the streams without worrying about every service in the beginning. (Some disclaimers needs to be displayed towards user before using this module if we "scrape the data".)
2. Mute groups of tabs or directly streams (E.g. mute personal when at work or vice versa.)
3. Save a hashed password in local db so user does not have to enter password everytime before lock.
4. Auto lock after time e.g. (30min, 1hr, 1day) This prevents unauthorized access to this if you are sharing computer with others at work or home, or others know your pc login.
5. Show if there is any new notifications on unlock screen, for example with icons and number above them, then the user does not have to unlock and get distracted if there is not important services that have waiting notifications. This can increase productivity for many users who check in on all services all the time and cant resist clicking on each one.
![image](https://cloud.githubusercontent.com/assets/9542610/19554831/9bf2e4da-96ba-11e6-89f3-2c79e62dc6ae.png)

I`m also interested in contributing on these parts but would be nice to hear your thoughts first, if this is something that could bring value to users.

**Comment by MrChick** [comment]
I like the idea to have a "Notifications"-Tab listing all new messages, this could potentially be combined with #244

**Comment by saenzramiro** [comment]
Great features!

1. Is an awesome feature, but it will be very difficult to do it I think. DOM-extraction requires to write code for each service.
2. I was thinking to do it in v1.0.0 (that it will have #244).
3. I don't think it's necessary to do this.
4. We have some feature requests about this. I tried to implement it but no luck yet.
5. Good idea.

Of course you can contribute, PRs are welcome!
