### ISSUE TITLE
[REQUEST] Change user agent

### ISSUE THREAD

**Issue by ghost** [ramboxapp/community-edition#440]
### ENVIRONMENT

> Rambox: v0.4.4

> OS: Linux (Debian Stretch)

> Arch: x64 

### Request
Hi, would it be possible to allow changing the user agent? I'm using a custom service to connect to my work's microsoft OWA. The problem is that OWA shows a basic interface if it's not MS Edge or Firefox.

**Comment by saenzramiro** [comment]
I will think about it and comes with a solution. 😉

**Comment by zeratul021** [comment]
Would be cool to add this because in our team we can't connect to some services anymore. Overriding in injected JS is bit too late.

In our company a security gateway is 403ing you saying you are using non-standard web browser.

**Comment by ozskywalker** [comment]
Submitted pull request #1632

**Comment by wido-gg** [comment]
Thanks! I'll give it a try during weekend

**Comment by ArmeF97** [comment]
We can close this
