### ISSUE TITLE
Image drag bug

### ISSUE THREAD

**Issue by triinoxys** [ramboxapp/community-edition#452]
Hi, I just randomly found a bug: you can drag an image on rambox and it open it like a webpage, so your tab is replaced by it
It also bug the notifications amount :c

I did a video to show the bug, you can found it here: https://youtu.be/XP7K5YzLhPE.

-
> Rambox 0.4.4
> Electron 1.4.1
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Ok, seems like if you drop it in a non enabled drop area, that's what happen. Because if you drop it in areas enabled for attach images, like Gmail, Slack, etc., works.
