### ISSUE TITLE
duplicate icons for Rambox in Ubuntu 16.10 Unity Launcher

### ISSUE THREAD

**Issue by dln949** [ramboxapp/community-edition#474]
64 bit ubuntu 16.10
Rambox 4.5-x64 AppImage

I downloaded the Rambox-0.4.5-x64.AppImage file, and then started Rambox.  I selected "Yes" when asked if I wanted system integration.  Then I exited Rambox.  

From the Unity Dash, I typed "Rambox" to start Rambox again.  The Rambox icon was visible in the Unity Launcher, so I locked it to the launcher.  Thereafter, anytime I started Rambox from either the Unity Dash or from that locked Rambox icon in the Unity Launcher, Rambox would be "indicated" by that Rambox icon I had earlier locked to the Unity Launcher.  

Then, I added the Rambox to the desktop with a desktop configuration file.  Here is the problem:  When I start Rambox from the desktop, it creates a duplicate icon on the Unity Launcher.  

Why does it do that, and how do I fix that so that Rambox will always only be associated with the one, single Rambox icon I have locked to the Unity Launcher?  

Some more information, in case it is helpful:  

I noticed that when I start Rambox by double-clicking the file Rambox-0.4.5-x64.AppImage, it not only creates a duplicate icon on the Unity Launcher, but that duplicate icon is not the Rambox icon, instead it is a grey question mark.  

Also, both configuration files appear to be exactly the same.  Here I first show the configuration file that Rambox created in ~/.local/share/applications, and then I show the configuration file that I have on the desktop:  

[Desktop Entry]
Name=Rambox
Comment=Rambox
Exec="/home/main1/applications/Rambox/Rambox-0.4.5-x64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-Rambox
X-AppImage-Version=0.4.5.89
X-AppImage-BuildId=4c24f430-ace4-11a6-1b9d-81e8fe14ffb2
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_xAdgP9/AppRun
TryExec=/home/main1/applications/Rambox/Rambox-0.4.5-x64.AppImage

[Desktop Entry]
Name=Rambox
Comment=Rambox
Exec="/home/main1/applications/Rambox/Rambox-0.4.5-x64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-Rambox
X-AppImage-Version=0.4.5.89
X-AppImage-BuildId=4c24f430-ace4-11a6-1b9d-81e8fe14ffb2
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_xAdgP9/AppRun
TryExec=/home/main1/applications/Rambox/Rambox-0.4.5-x64.AppImage

**Comment by Slaventsiy** [comment]
Same on Ubuntu 17.04, Rambox 0.5.13
