### ISSUE TITLE
lenter of laoding

### ISSUE THREAD

**Issue by ghost** [ramboxapp/community-edition#489]
### Steps to reproduce

1. I just opened the software. 
2. It takes a while, and even see it restart to display the dashboard

### Expected behavior

I was just waiting for the software to open and display directly after loading the dashboard, as well as the configured tabs.

### Actual behavior

Currently, at startup, I am obliged to restart the service so that it finally displays the tabs.
And in the evening when I want to turn off the computer, I am forced to call the manager to close the software, instead of simply cutting through the cross like all other software.

### ENVIRONMENT

> Version: 0.4.5
> Platform: win32 (x64)
> Electron: 1.4.7
> Chromium: 53.0.2785.143
> Node: 6.5.0

> OS: Windows 7 Home Famille Premium

> Arch: 64bits

**Comment by ValentinCMS** [comment]
up
Thank you for seeing my message, but we should find a solution, it starts again.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
