### ISSUE TITLE
Request: Add a spell-checker

### ISSUE THREAD

**Issue by twinklebob** [ramboxapp/community-edition#509]
Bit of a frustrating one, really. If you use any of these services within Chrome you get a spell-checker, but you don't have it in Rambox. Any chance one could be added? Maybe Electron already includes it but it just needs to be enabled?

-
> Rambox 0.4.5
> Electron 1.4.7
> linux x64 3.19.0-32-generic

**Comment by weeman1337** [comment]
It looks like there is an option in electron. Will have a look and send a PR.

**Comment by weeman1337** [comment]
Looks like it's a little bit more work than simply enabling an option: https://github.com/electron/electron/pull/942

**Comment by simonwiles** [comment]
bit of a show-stopper for many people, I think, this one...

**Comment by ylluminate** [comment]
In macOS the integrated system spellchecker should be present.  It is very difficult to use HipChat and other messaging applications for professional applications without the normal integrated spellchecking that we have in other apps such as Franz, HipChat native client, etc.

**Comment by taniadaniela** [comment]
on mac os sierra 10.12.2 spell checking is not being activated in any of the services I'm using in rambox (telegram, slack, WhatsApp )

**Comment by saenzramiro** [comment]
I'm planning to add it in version 1.0.0 using https://github.com/electron-userland/electron-spellchecker.

**Comment by pcuinty** [comment]
multiple language check would be really nice, or alternatively a way to change the dictionary language quickly

**Comment by ylluminate** [comment]
How close is the 1.0.0 release @saenzramiro?

**Comment by ylluminate** [comment]
How close are we to this @saenzramiro? I have to step away from Rambox with no Spelling support. It's just impossible to use an app without spell checking on macOS now that I'm used to integrated spell checking everywhere else.

**Comment by saenzramiro** [comment]
Now, we are working in v0.5.4. So I think Spellcheck have to wait little bit more, because it was not easy to us implement it. Any PR will be great!

**Comment by habGegeben** [comment]
Just curious how far out this feature is from implementation? I love Rambox and still currently use it. This feature would really be awesome to have!

**Comment by Mte90** [comment]
Any news about it?

**Comment by ylluminate** [comment]
Might want to note this along with accompanying links: https://github.com/yakyak/yakyak/issues/683

**Comment by GervaisdeM** [comment]
Zulip Electron has speel checking working.... I don't know how it was added exactly, but the source code is over here: https://github.com/zulip/zulip-electron

**Comment by devourment77** [comment]
I am hitting this with slack as well.

**Comment by davidmoore-io** [comment]
I'm gonna have a go at making it work in Zoho and Messenger, as it's doing my head in. My speeling erorz are making me look a bit dim on occasion. Rambox iss ace, but it's becoming a deal breaker for me.

**Comment by Mte90** [comment]
The ticket of electron where ping https://github.com/electron/electron/issues/3189

**Comment by AGonLen** [comment]
This would be a REEEEEALLY great feature.
Any ETA for version 1.0.0 (or to have this spell check implemented)???
Thanks!

**Comment by SimJoSt** [comment]
@AGonLen If you want to help with the development of the software and get the [release](http://rambox.pro/100/) on the way faster, you might want to consider [donating](https://salt.bountysource.com/teams/rambox).

**Comment by wilpso** [comment]
Hell yeah, I'd like to see that option for "multi-languages" on options on/off, would be great

**Comment by marcofl** [comment]
This really is a missing feature and for a lot of people a reason no to use rambox at all. I would already be happy with english spellchecking for a start :D

**Comment by xenithorb** [comment]
RocketChat Electron has a working spellcheck implementation on Linux, see: https://github.com/RocketChat/Rocket.Chat.Electron/pull/266

**Comment by ben8p** [comment]
manageyum also has one
https://github.com/sivaramsi/manageyum

**Comment by funkycram** [comment]
+1

**Comment by ionutdurlea-okta** [comment]
This is so needed right now.. +1

**Comment by AndreyBulgakow** [comment]
Absolutely needed feature and also a show stopper for me

**Comment by kaliberr44** [comment]
+1

**Comment by hugobarthelemy** [comment]
+1

**Comment by phillip-white-sociomantic** [comment]
+1 Currently using Wavebox which also has the spell checker. Rambox would be nice as It's open source

**Comment by pedrofusc** [comment]
Any news about this? this is one of the most important feature for me. All the other apps have this already implemented.

**Comment by beevabeeva** [comment]
If I had time I'd try doing this myself :( :(
Can't we crowd fund this specific issue ?
Make a kickstarter or something.
If everyone who commented on this issue is contributing it could be  $200-$300 !

**Comment by xenithorb** [comment]
@beevabeeva Here you go 

#### Bountysource: 

#### https://www.bountysource.com/issues/39803901-request-add-a-spell-checker

**Comment by beevabeeva** [comment]
@xenithorb Awesome! Thanks

**Comment by nzeppos** [comment]
Definitely a **must**-have feature.

**Comment by aabuhasan** [comment]
Yes definitely

**Comment by saenzramiro** [comment]
The spellchecker library is now "stable" so I will try to add it in next release. 👍

**Comment by twinklebob** [comment]
Thanks for your hard work, can't wait to see it working!

**Comment by ylluminate** [comment]
Wow that is tremendous news @saenzramiro. Anything we can do to help? With Franz not supporting Mattermost and some services properly we're looking to migrate over to Rambox entirely.

**Comment by nzeppos** [comment]
It looks like the Pro version of Rambox will include a spell checker: https://rambox.pro/#feature-details/spell_check
Should we be concerned about this? Will this service be reserved for pro users only?

**Comment by xenithorb** [comment]
I think this makes it pretty clear:

![image](https://user-images.githubusercontent.com/10273878/43767405-11fcf790-9a03-11e8-9b6e-8984a6649da2.png)

Ugh. I didn't know he was going in that direction, when he just talked about adding it. 

![image](https://user-images.githubusercontent.com/10273878/43767465-3ab7c8d6-9a03-11e8-956a-75353a6455e1.png)

Also this

If you compare the two they look significantly diverged, so I think we're just witnessing that transition. Oh look, this repo was renamed "community-edition" too - yeah we're hosed. I'm guessing the owner was offered some money to start this up as a proprietary app - and you can't fault people for wanting to make some money, but doing it in such a surprising underhanded way is distasteful, to me at least. 

$4 is way to high for a glorified web browser, on top of thing.

**Comment by AndreyBulgakow** [comment]
I already donated 30 Euros for this feature and now kind of doomed to use the pro version.

Anyway... a CLEAR and TRANSPARENT communication from the project owner is highly appreciated

**Comment by HaleTom** [comment]
We can always do a parallel implementation in the community edition no matter what is done in the closed-source Pro edition...

**Comment by ylluminate** [comment]
Seeing the release of Rambox Pro was really depressing. I'm now seeing other features we've requested and pushed for also implemented into this, even after a lot of community action.

I wonder if we're going to have to fork Rambox at this point and just go down a different path?  The creator has the right to income and support for his efforts, but what's happened here seems... off putting.  

I definitely don't want to misjudge or misspeak here.  Again, you've gotta live and pure open source isn't the best path for surviving!  I just think there's some level of frustration created by this.

**Comment by beevabeeva** [comment]
Yea I've forked it already.
Happy to work on trying to figure out how to import the Electron spellchecker js into the build in my free time.
I don't have any experience with electron but I have plenty of experience with JavaScript. So if anyone wants to point me to some recommended tuts other than the official electron docs, that'd be nice.

**Comment by grpace** [comment]
So because it's in the pro edition does it mean someone can't fork this over to the community edition. 

This is kind of a dealbreaker here?

**Comment by AndreyBulgakow** [comment]
I'm really upset about this after donating so much money for this feature. And there is no reaction from the rambox folks whatsoever...

**Comment by KenMacD** [comment]
@grpace & @AndreyBulgakow: You may want to read issues #1810 and #1811, and then check out the fork [TheGoddessInari/rambox](https://www.github.com/TheGoddessInari/rambox )
