### ISSUE TITLE
Clicking Link to Open in New Tab opens Two Windows

### ISSUE THREAD

**Issue by dotcarls** [ramboxapp/community-edition#510]
### Steps to reproduce

1. Activate a service like Gmail
2. Open your default browser
3. On Mac, CMD+Click a message in your Inbox

### Expected behavior

A new tab should be opened in the default browser.

### Actual behavior

Two windows are opened, one as a popup in Rambox and the other as a tab in the default browser.

### ENVIRONMENT

> Rambox: v0.4.5

> OS:  OSX 10.11.6 El Capitan

> Arch: darwin (x64)

### Implementation Suggestion

This behavior could be defined as a preference on a per-service basis. Alternatively, providing access to the Electron webview methods in the custom code section (or a new section to define custom webview behavior) would allow users to customize this behavior themselves, and it would enable better control for things like custom services.

Further, moving this behavior to the services themselves would allow you to decouple the hacky Skype / Hangouts code from `app/ux/WebView.js` which, in my opinion, would help improve maintainability.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
