### ISSUE TITLE
GUI frozen after receiving a notification

### ISSUE THREAD

**Issue by seza443** [ramboxapp/community-edition#515]
### Steps to reproduce

1. Open rambox
2. Receive a notification from any tab
    a. To receive a notification, either put the app in background or be in another tab than the one receiving new message

### Expected behavior

It should simply show the notification

### Actual behavior

It shows the notification and then it freezes.
Rambox is not "not responding". It still plays the sounds.
But the GUI is frozen.

### ENVIRONMENT

> Rambox: v0.4.5
> OS: Windows 10
> Arch: x64

**Comment by seza443** [comment]
Hu weird but today it works just fine.
I don't know if I should let this issue open ?

**Comment by seza443** [comment]
Ok today it freeze again 😭

**Comment by fjacobi** [comment]
Can confirm the issue today. Fresh install.

### ENVIRONMENT
> Rambox: v0.4.5.
> OS: Windows 10
> Arch: x64

**Comment by Sudiukil** [comment]
Same problem here but I made a few tests on two different machines.

Fresh Rambox 0.4.5 install and config on all machines and OS.

Machine 1 and 2 are quite similar in environment, only hardware differs. Machine 1 has two monitors though.

Machine 1, Debian 8 x64: Rambox does **not** freeze.
Machine 1, Windows 10 x64 (**with** anniversary update): Rambox **does** freeze.

Machine 2, Debian 8 x64: Rambox does **not** freeze.
Machine 2, Windows 10 x64 (**without** anniversary update): Rambox does **not** freeze.

**Comment by saenzramiro** [comment]
Interesting... Did you test disabling GPU acceleration in Preferences?

**Comment by Sudiukil** [comment]
I think I have tried that yes but I'm not completely sure.

I'll try that but I can't before the week-end, I'll keep you posted.

Although, FYI, I updated Rambox to 0.5.3 on the machine where the freeze occurs and it's still freezing (clean 0.5.3 install + services restored from account).

**Comment by nmat** [comment]
I tested it with removing the accelerator but the app does indeed freezes from time to time. (very random)

**Comment by nmat** [comment]
What I did now was to test not using zoom in some of the services. Using standard layout and no zooming then the client seems stable. @Sudiukil did you use zoom when testing?

**Comment by nmat** [comment]
....followup...this still happens on windows 10 at least. Seems the interface freezes when notifications are getting sent to the system. Really annoying. :/

**Comment by Sudiukil** [comment]
@nmat No I don't use zoom.

I also tested without GPU acceleration but the freezes are still here.

I don't use Windows 10 much these days but if I have time by the end of the week i'll try to do some extensive testing on the machine where the app freezes.

**Comment by FallenKN** [comment]
I disabled GPU acceleration and its working without freezing now

**Comment by Sudiukil** [comment]
Ok, so I did a few tests and it's quite interesting because freezes seems completely random:

### Env
>Rambox 0.5.3
>Windows 10 x64 (with anniversary update)
>Five services: MySMS, TweetDeck, Messenger, Discord, Steam
>Hardware acceleration enabled

Tests, in that order (manual notification = `new Notification("title", {body: "Body"});` in dev console):

- Manual notification, **freeze**
- MySMS notification (many), **no** freeze.
- Discord notification, **freeze**
- Discord notification, **no** freeze
- Manual notification, **no** freeze
- Discord notification, **freeze**
- Discord notification, **freeze**

And so on...

I tried many things like disabling and enabling services, restarting Rambox, etc... but I could not find any pattern, freezes really seem random.

**Comment by nmat** [comment]
@Sudiukil I start to wonder if it could have something to do with calculation of unread messages?......or even....if it could have to do with sending the notification to the system itself?

I get the same effect here but I can't really figure out at the step of when the problem occurs.

**Comment by Sudiukil** [comment]
@nmat To be honnest, I even think it might come from Electron itself, since manual notifications from the console can make Rambox freeze.

**Comment by FallenKN** [comment]
to confirm seems to crash randomly thats why I thought Hardware Acelleration fixxed it.

**Comment by Gittyperson** [comment]
Using only Skype and FB atm, and the freezes always occur when receiving Skype messages, it doesn't happen with FB. Disabling acceleration doesn't help.

**Comment by saenzramiro** [comment]
Like @Sudiukil said, I think is related with Electron. We have to keep investigating to solve this problem, and I really appreciate your help folks.

**Comment by ajgassner** [comment]
This issue occurs with Hipchat and WhatsApp on Windows 10 x64 on my machine. Each notification freezes the app for about 1-2 minutes.

I have disabled notifications for all services, this seems to be a temporary workaround.

Also tried to profile the application with dev tools to find the root cause for the issue. No success for now...

**Comment by FallenKN** [comment]
@ajgassner did you update your Rambox installation yet?

_Sent from my ZUK Z2 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ajgassner** [comment]
![image](https://user-images.githubusercontent.com/2866145/28357693-92e12c84-6c6c-11e7-9d59-5ae15a8d3bc4.png)

**Comment by saenzramiro** [comment]
@ajgassner Is this happening also with latest release?

**Comment by ajgassner** [comment]
With version 0.5.12 it's still occurring.

**Comment by wheelsofsteel** [comment]
Hey all, I was also experiencing this problem and switched to a Whatsapp Electron app in the AUR and I still had the same problem. Therefore, I think it could be related to Whatsapp (I don't believe I had problems with Messenger etc). I had the same problem on both Ubuntu and Manjaro (both KDE) and when I turn off the notifications then it works. 

It only froze when I received a few messages at once; could be related.

**Comment by heitorPB** [comment]
@saenzramiro  This problem appeared to me a faw days ago and I just found out it is related to the notification stuff

	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.13.8-1-ARCH

If i disable notifications, works like a charm. But when I enable notifications, it freezes for a while. Hardware acceleration is enabled.

I use Telegram, Facebook Messenger and Whatsapp now. But Messenger did not freeze rambox, the other two froze when I got a notification.

I use ArchLinux with dwm as window manager. So this bug not a KDE/GTK/Qt/bla related.

**Comment by fungs** [comment]
I'm also having problems with some messengers like Skype and sometimes Telegram freezing. I have to reload the tab to make them work again. Lately, it has become so bad that I had to disable Telegram in Rambox.

**Comment by paco3346** [comment]
Similar issues here- I have 2 slack windows, 5 gmail windows, telegram, google voice, pushbullet, whatsapp, and messenger.

The issue only started happening today (been running Rambox for about 2 weeks now).

Running Arch Linux w/ KDE.

**Comment by Sceinox** [comment]
I have the same problems and I'm using following services

- Telegram
- WhatsApp
- Messenger
- Skype
- Mattermost
- o365
- GMail
- Protonmail

I'm running arch linux with i3wm and have the following versions:
- rambox 0.5.13-2
- electron 1.6.15-1

> Also, I've noticed it only freezes if the notification comes from a service other than the one I'm currently on.

Can confirm this

**Comment by paco3346** [comment]
After paying attention for a few days I wonder if this is related to a third party library. My entire window manager freezes along with Rambox. I can continue using whatever programs are open but can't switch between programs for 10 to 15 seconds.

**Comment by AllanWang** [comment]
Having the same issue using Antergos. For me, I can freely minimize/resize Rambox and use any other program, but the contents of Rambox freezes for a solid few seconds. This is with slack.

**Comment by brigadier** [comment]
I always have this issue with skypeforlinux in KDE Plasma. 100% reproducible.

**Comment by phaazon** [comment]
I have a problem very similar with `slack` and `gitter`. Has anybody pinpointed the third-party library causing the harm?

**Comment by MurzNN** [comment]
As descibed in https://github.com/electron/electron/issues/7831#issuecomment-257564038 and https://github.com/electron/electron/issues/7831#issuecomment-260876386 - seems this is happens because of using user's code hacking. Can Rambox try to remove hacky code and rewrite notifications in recommended way?

**Comment by gponickjw** [comment]
I found a solution that seems to resolve this for me, though it was intermittent enough I can't be 100% sure.

My config: Kubuntu with SDDM -> i3 WM. 

I found that my `/usr/share/dbus-1/services/org.freedesktop.Notifications.service` file was pointing to notify-osd, but I wasn't actually *running* `notify-osd`. I added it to my i3 config with an `exec --no-startup-id` and so far I haven't had `Slack` or `Rambox` hardlock on me as @paco3346 and others have mentioned.

Can anyone else comment on if this helps the issue for them?

**Comment by gponickjw** [comment]
@heitorPB 

I actually switched to using Dunst overnight as it can fit better visually with my i3 setup. I'm like 80-90% certain this was it, because even nm-applet has stopped locking up periodically.

**Comment by paco3346** [comment]
I'm running plasma which has its own notification server built in so I don't have anything else like dunst installed. From the link @MurzNN shared back in July (https://github.com/electron/electron/issues/7831#issuecomment-257564038) I see that this is a pretty common issue with Electron.

There was a new issue opened https://github.com/electron/electron/issues/14006 that tracks the Linux problems. My suggestion is that this issue be closed and we can help out on 14066.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
