### ISSUE TITLE
Pop-up windows may not have a title

### ISSUE THREAD

**Issue by MakisH** [ramboxapp/community-edition#519]
I noticed this issue with Google Calendar, but it may affect more services.

### Steps to reproduce

1. Add Google Calendar:
  1.1. Name: Calendar
  1.2. URL: https://calendar.google.com/
  1.3. Logo: https://calendar.google.com/googlecalendar/images/favicon_v2014_3.ico
2. Add an event and ask for a notification.
3. Wait until the notification triggers a pop-up window.

### Expected behavior

The pop-up window has a title (e.g. "Google Calendar" - the service name, or "Rambox").

### Actual behavior

The pop-up window has no title (see attachment).
![screenshot from 2016-12-12 13-00-56](https://cloud.githubusercontent.com/assets/4943683/21144318/78e509cc-c14a-11e6-8a3f-e08be058ca13.png)

### ENVIRONMENT

> Rambox: v0.4.5

> OS: Ubuntu 16.04

> Arch: x64

Update: Just to confirm, this still holds in November 27, 2017.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
