### ISSUE TITLE
"A JavaScript error occurred in the main process" messagebox

### ISSUE THREAD

**Issue by maseal** [ramboxapp/community-edition#525]
I've got hundreds of ther same Messageboxes when left PC alone for some hours:
"A JavaScript error occurred in the main process" (screenshot attached)
![rambox-bug](https://cloud.githubusercontent.com/assets/575760/21215810/4135e5f6-c2c5-11e6-86d7-35aff226064f.png)
If it helps, I have the following services enabled in rambox: Slack, Telegram, WhatsApp
-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Did you install Rambox using the .exe file or run in using the .zip file?

**Comment by pheijmans** [comment]
i get the same error, this seems to trigger the unread post in Gmail. When i set this mail to unread i get the error again. I i leave the mail unread the error is gone

**Comment by maseal** [comment]
I've installed rambox via installation exe-file.

**Comment by saenzramiro** [comment]
Did you tried to reinstall Rambox? Before install it again, clean your PC and registry with CCleaner or something similar.

**Comment by Ash258** [comment]
Continue in #1656
