### ISSUE TITLE
Movim doesn't show red counter on tab when receive message

### ISSUE THREAD

**Issue by alien2003** [ramboxapp/community-edition#543]
Steps to reproduce
1. Log in to Movim
2. Receive message

Expected behavior:
There should be a counter with unread messages on tab on Rambox

Actual behavior:
Only libnotify notification appears

Version: 0.4.5
Platform: linux (x64)
Electron: 1.4.7
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
