### ISSUE TITLE
`disablewebsecurity` prop on webview is preventing Google Drive to authenticate

### ISSUE THREAD

**Issue by raulmatei** [ramboxapp/community-edition#544]
### Steps to reproduce

1. Add GoogleDrive as a Custom service
2. Login and authenticate as you'd normally do in a browser

### Expected behavior
GoogleDrive service is added and I should be able to login

### Actual behavior
The service is added but the page is saying that I'm not authenticated:
![image](https://cloud.githubusercontent.com/assets/1718341/21581057/69a282f4-d028-11e6-908b-0649c59632f6.png)

### ENVIRONMENT

> Rambox: 0.4.5

> OS: Mac OS 10.12.2

> Arch: x64

Removing `disablewebsecurity` from `app/ux/WebView.js` and building it on my machine solves the issue. Why is this property set on the element, are there services that require this to be 'on'? 

Thanks,
Raul

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
