### ISSUE TITLE
Detailed notification appname

### ISSUE THREAD

**Issue by xintron** [ramboxapp/community-edition#556]
When receiving notifications the application name is set to "Electron". Using a notification daemon like [dunst](https://github.com/knopwob/dunst) which allows formatting to be changed depending on appname (title and body is also possible to match) it makes it hard to use when the name is just "Electron". Below is an example message picked up in dunst:

```
{
        appname: 'Electron'
        summary: 'Philip - Tech Channe...'
        body: 'Notification test'
        icon: 'info'
        category:
        urgency: 1
        formatted: '<b>Philip - Tech Channe...</b>
Notification test'
        fg: #ebdbb2
        bg: #1d2021
        id: 4
        actions:
        {
                 [default,View]
actions_dmenu: #View [Electron]
        ]
        script: (null)
}
```

My suggestion would be that the appname is set to "Rambox - <service>" instead so for example: `Rambox - HipChat`. This allows for easy matching on the application name in the actual notification.

### ENVIRONMENT

Rambox: v0.4.5
OS: (Arch) Linux
Arch: x64

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
