### ISSUE TITLE
Slow transfer speed of files in Rambox compared to original client (Telegram)

### ISSUE THREAD

**Issue by hirkah** [ramboxapp/community-edition#561]
Downloading files in Telegram in Rambox is _much_ slower than downloading them directly in the official Telegram client.

-
> Rambox 0.4.5
> Electron 1.4.7
> win32 x64 10.0.14393

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
