### ISSUE TITLE
Surface Pro 3 Touchscreen Lag

### ISSUE THREAD

**Issue by antzpantz** [ramboxapp/community-edition#562]
### Steps to reproduce

1. Switch to another tab 
2. Touch with finger to focus on an element in the new tab... but it doesn't register until tapped (on average) around 30 times before focus is given. Once focus is available, swipe to scroll and tap to select work fine.
3. This lag does not seem to appear when using the Surface Pen. Tapping with a finger between tabs is immediate, but once you try touching fields in that new tab, it defaults to behaviour in Step 2.

### ENVIRONMENT

> Rambox: v0.4.5
> OS: Windows 10
> Arch: x64

Version: 0.4.5
Platform: win32 (x64)
Electron: 1.4.7
Chromium: 53.0.2785.143
Node: 6.5.0

Using a Surface Pro 3, i5-4300U processor with 8GB RAM

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
