### ISSUE TITLE
Many pop-ups when connecting to wifi requiring sign in

### ISSUE THREAD

**Issue by msbentley** [ramboxapp/community-edition#564]
### Steps to reproduce

1. Connect to a wireless access point requiring a browser sign-in with Rambox running

### Expected behavior

Rambox complains once (per service?) about access or certificate problems.

### Actual behavior

Never-ending pop-ups are produced, so many that a normal terminal window cannot be opened and I had to switch to a virtual console to kill Rambox.

### ENVIRONMENT

> Rambox:

Version: 0.4.5
Platform: linux (x64)
Electron: 1.4.7
Chromium: 53.0.2785.143
Node: 6.5.0

> OS: ubuntu 16.10
> Arch: x64

**Comment by DBX12** [comment]
I would propose a limit of n popups per Service or Rambox instance. Would also prevent too much popups in the recent certificates issue #573

**Comment by saenzramiro** [comment]
Please update to latest version, and confirm if this issue it's remains.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
