### ISSUE TITLE
Set window hints for window managers

### ISSUE THREAD

**Issue by eonpatapon** [ramboxapp/community-edition#565]
For example _NET_WM_STATE_DEMANDS_ATTENTION can be set when the user is notified in the app.

https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html

This allows the window manager to know that something happenend for a particular window. Usually the workspace where is the application will be highlighted.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
