### ISSUE TITLE
Preferences save bug

### ISSUE THREAD

**Issue by pzryumov** [ramboxapp/community-edition#567]
### Steps to reproduce

1. Open Preferences of Messenger
2. Change "Show Notifications" Setting 
3. Click "Edit  Messenger" to save and close Preferences
4. Open Preferences of Telegram
5. Change "Show Notifications" Setting 
6. Click "Edit  Telegram" to save and close Preferences
7. Type cmd+R to refresh the window

### Expected behavior

Preferences for both services have been saved

### Actual behavior

Only the preferences for Messenger were saved

### ENVIRONMENT

> Rambox: v0.4.5

> OS: macOS 10.12.1

> Arch: x64

**Comment by jerry1970** [comment]
As I described in #1104, on Rambox 0.5.10, the settings *are* saved but the dialog does not close.
I guess this issue can be closed?
