### ISSUE TITLE
Handle system mailto: URIs

### ISSUE THREAD

**Issue by agharbeia** [ramboxapp/community-edition#578]
Since it supports some mail services, it would also be cool if Ramboxapp could be registered as the default mail client to handle incoming mailto: URI requests coming via the OS, properly handling "to" and "subject" parameters, etc.

**Comment by saenzramiro** [comment]
Ok, but before the user had to define what service will be taking the "mailto:" passed from Rambox. Right?

**Comment by weeman1337** [comment]
Web mail services could have a flag. Custom services must be marked by the user.
The trick is to create a new message. This must be custom code for every service.
I'll investigate a little bit.

**Comment by libora** [comment]
This issue is same/similar as https://github.com/saenzramiro/rambox/issues/246

**Comment by twinklebob** [comment]
Can I suggest this issue is closed as #246 predates it and has a bit more helpful information.
