### ISSUE TITLE
Unable to drag tweets to collections in Tweetdeck in Ubuntu

### ISSUE THREAD

**Issue by agharbeia** [ramboxapp/community-edition#583]
Tweetdeck's functionality of dragging tweets into collections isn't working as it does in the Tweetdeck app in the browser.

### Steps to reproduce

1. log into Tweetdeck
2. using the mouse, drag a tweet to a collection's column
3. drop

### Expected behavior

Dropped, the tweet is added to the collection and displayed there.

### Actual behaviour

Nothing happens.

### ENVIRONMENT

Version: 0.4.5
Platform: linux (x64)
Electron: 1.4.7
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
