### ISSUE TITLE
On boot all services require a reload.

### ISSUE THREAD

**Issue by hughwilliams94** [ramboxapp/community-edition#599]
### Steps to reproduce

1. Arch Linux, logout desktop and login again

### Expected behavior

Rambox automatically loads previously opened services

### Actual behavior

Open services are blank and require manual reload via context menu.

### ENVIRONMENT

> Rambox: AUR package, rambox-bin 0.4.5-1

> OS: Arch Linux

> Arch: x64

**Comment by madsprite** [comment]
Are you on wifi? I've had this problem and I notice if RamBox loads before connecting to the wifi the pages will stay blank.

**Comment by hughwilliams94** [comment]
Ah OK, Rambox often loads before my connections, I will trying putting a delay on the autostart.




Get Outlook for Android









On Mon, Jan 23, 2017 at 10:49 PM +0000, "madsprite" <notifications@github.com> wrote:












Are you on wifi? I've had this problem and I notice if RamBox loads before connecting to the wifi the pages will stay blank.

**Comment by saenzramiro** [comment]
Yes, like @madsprite said. Probably when Rambox wants to load service, you don't have internet connection yet.

I'm planning to fix this in next release.
