### ISSUE TITLE
pop-up blocker interferes with gmail attachments etc

### ISSUE THREAD

**Issue by jonpday** [ramboxapp/community-edition#61]
How is it possible to disable the pop-up blocker?

**Comment by saenzramiro** [comment]
Can you give more details about this? Steps to reproduce it, etc.

**Comment by jonpday** [comment]
this is running on centos 7. chrome is my default browser. when I open an attachment to a gmail message it shows a preview as normal, then if I click the pop-out icon which normally opens that attachment in a new tab, I get the warning re pop-up blocker. 

![image](https://cloud.githubusercontent.com/assets/752408/16705270/a1f14130-45c3-11e6-84db-931fe4e2710f.png)

the browser then gets four new tabs, but none of them actually show the attachment correctly :(

![image](https://cloud.githubusercontent.com/assets/752408/16705276/c12d5bd8-45c3-11e6-84d2-2c1f2ea52520.png)


i've also noticed that clicking a link in a gmail message will often open the link in 4 new tabs (!) which may be related?

![image](https://cloud.githubusercontent.com/assets/752408/16705287/eb6a0edc-45c3-11e6-8402-02fe6b2307c7.png)

**Comment by saenzramiro** [comment]
Ok, got it. The opening several tabs is fixed but I will take a look for the attachments. Thanks!

**Comment by fvulich** [comment]
I will close this ticket due to inactivity, feel free to open another ticket if the problem persists.
