### ISSUE TITLE
HTTPS Mixed Content blocking reintroduced?

### ISSUE THREAD

**Issue by MrChick** [ramboxapp/community-edition#611]
Seems like 0.5.x reintroduced the HTTPS Mixed Content blocking from #202 

### Steps to reproduce

1. Add Service using HTTPS (in my example: tiny tiny RSS)
2. Try to display image in a rss entry
3. get 'Mixed Content [...] This request has been blocked; the content must be served over HTTPS.' message in console

### Expected behavior

Image is displayed

### Actual behavior

Said mixed content blocked message is written to the console

### ENVIRONMENT

> Rambox: v0.5.2

> OS: Win10 Enterprise

> Arch: x64

**Comment by MrChick** [comment]
seems to be fixed with 0.5.7, thanks!

**Comment by SimJoSt** [comment]
@MrChick, did you mean 0.5.3?

**Comment by Bebef** [comment]
@MrChick Where can I find 0.5.7 for Windows?

**Comment by nmat** [comment]
@Bebef you have to wait for the release to occur. It was pulled back due to problems on mac os platform.

**Comment by MrChick** [comment]
@Bebef yeah, I got lucky when I downloaded it right after release before it got pulled... there should be a new release soon, though
