### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by nicolangr** [ramboxapp/community-edition#616]
### Steps to reproduce

1. Request password recovery on login

### Expected behavior

Email with recovery password link

### Actual behavior

Any email received

### ENVIRONMENT

> Rambox: v0.5.2

> OS: Linux Mint 17

> Arch: x64

**Comment by saenzramiro** [comment]
Please try again. This should be an Auth0 bug/problem.

**Comment by nicolangr** [comment]
I have just retried but i don't receive the emial...
