### ISSUE TITLE
[Request] Modify the way of use IRC

### ISSUE THREAD

**Issue by ceso** [ramboxapp/community-edition#633]
Hi, first english isn't my mother tongue, so please tell me if something isn't written in the right way.

Actually, rambox for IRC is using IRC Proxys instead an implementation of the IRC protocol, could rewrite this?

So, remove everything about IRC, and rewrite it for to talk through the IRC protocol and not through IRC Proxys via http/s.

Regards!
Leandro.

**Comment by MrChick** [comment]
Why on earth would you want to create yet another IRC client?
Rambox is a software made for using existing webclients

**Comment by ceso** [comment]
I've always thought that the reasoning behind Rambox was to be able to access all the chat networks from a single client. That's why it should be way saner to access the IRC networks using the native IRC protocol, instead of just another gateway/translator...

**Comment by MrChick** [comment]
it meant to access all the messengers, by using their own official webclients.
Implementing own clients for all the supported networks (either open or closed protocols) would be insane. 

What speaks against using the already added (or other?) web IRC clienta?
