### ISSUE TITLE
Rocket.Chat Sign In Via Google/Github/... is not supported

### ISSUE THREAD

**Issue by tobiasmuehl** [ramboxapp/community-edition#64]
Hi,
using other service providers to sign in to rocketchat doesn't work. The reason is that the popup window is opened in the default browser, but it should be a popup of Rambox. 

When you log in in the browser popup, the redirection doesn't work and you're unable to login.

**Comment by saenzramiro** [comment]
Ok, I will take a look on this.

**Comment by kingofsevens** [comment]
I cannot login to https://chat.hyperledger.org/ since it is using an external page for authentication. I believe this is related to this issue. Any update on this?

**Comment by AllanHBC** [comment]
@kingofsevens  
Have you tried to add like a _Custom Service? For me, its worked ! :) 
sorry for my english :P

**Comment by JCQuintas** [comment]
Can confirm adding as a _Custom Service does work for me
