### ISSUE TITLE
Support U2F standard for Two Factor Authentication

### ISSUE THREAD

**Issue by HoracePGreeley** [ramboxapp/community-edition#663]
Many online services support two factor authentication. The [FIDO U2F keys](https://www.yubico.com/products/yubikey-hardware/fido-u2f-security-key/) for example can be used to authenticate on several google services. More information about [U2F](https://en.wikipedia.org/wiki/Universal_2nd_Factor) can be found on [wikipedia](https://en.wikipedia.org/wiki/Universal_2nd_Factor).

.
### Steps to reproduce

1. Organize a U2F security key
2. Enable U2F two factor authentication on a google account
3. Try to login on Rambox
4. Two factor authentication is aborted (by the website)

### Expected behavior

Login with U2F is supported by Rambox. I can easily e.g. insert the security USB key and authenticate on online services, inside of Rambox.

### Actual behavior

Unfortunately, if U2F authentication is enabled, Rambox cannot deal with it and the website (Google for example) returns an error

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Windows 10

> Arch: x64

**Comment by xasx** [comment]
Check electron/electron#3226 - it is long awaited.

**Comment by otlet** [comment]
Any updates to the topic?

According to the original [electron/electron#3226](https://github.com/electron/electron/issues/3226) thread, it should work in Electron 4+

**Comment by pconwell** [comment]
Is anyone still seeing this issue? In 0.7.3 I am able to log in to gmail using a U2F key. I just checked on two different accounts and they both worked without issue.

Version: 0.7.3
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by fvulich** [comment]
I'm gonna close this ticket because it seems fixed. Feel free to open another ticket if the problem persists.
