### ISSUE TITLE
"Couldn't load plugin" message trying to view attached PDF in Outlook 365 tab

### ISSUE THREAD

**Issue by ZaLiTHkA** [ramboxapp/community-edition#670]
Clicking on the link for a PDF file attached to an email, Outlook 365 OWA shifts the email body to the side and tries to load the PDF file into a preview pane.

I expect to see the document in the preview at this point, but instead I see a message stating "Couldn't load plugin.", along with two flashing dots at the bottom of the pane (looks like an activity indicator). This means I need to download every PDF before I can view it.

I had a look in the Developer Tools and there are no errors or warnings in the console tab, or any serious errors in the network tab. There was one `HTTP 307` error, but the URL is of a format that doesn't make any sense to a person, so I don't know how much help that would be.

Just for reference, I've had no issues previewing the following file formats:

* text files
* image files
* Word/Excel files

There's some additional behaviour that makes this little issue that much more annoying: while viewing an email, if I click directly onto the "Download" link of any attachment (either directly below the attachment block, or using the same link from the attachment drop-down menu), then Rambox opens a new tab in my system browser - in this case redirecting me to a login page.

However, if I try preview the attachment, then click the "Download" button after it fails to render, it downloads the file directly. I suspect this has more to do with the way MS are building the links for their UI, so I'm going to assume there isn't much we can do about this from Rambox itself.

### ENVIRONMENT

> Rambox: v0.5.3
> OS: Windows 10 Pro
> Arch: x64

**Comment by saenzramiro** [comment]
The `Couldn't load plugin` seems to be related with PDF plugin that every normal browser have pre-installed.

To download the file, we can handle pretty the same we are handling for Skype for example. See lines https://github.com/saenzramiro/rambox/blob/master/app/ux/WebView.js#L215

**Comment by ZaLiTHkA** [comment]
Only noticed your reply now, apologies for the lack of response until now..

Sounds like a pretty straight forward solution when you put it like that; let me know if there's anything I can do to help this along. :)

**Comment by saenzramiro** [comment]
I don't know if is my PC or Outlook is not working correctly... I tried with different browsers and I cannot preview PDFs.

Can you check now please with Google Chrome and if not work, with Microsoft Edge.

**Comment by nikobockerman** [comment]
I tested with Edge on Windows 10 and I see preview of PDF in the browser. I don't have Chrome so I wasn't able to test with that.
But at least Chromium in Fedora shows preview of PDF in browser.

1. Edge in Windows 10 Build 15063.250.
2. Chromium 57.0.2987.133 Fedora 25.

Hopefully this helps.

**Comment by nikobockerman** [comment]
Just tested on Office 365 with Chrome browser on Windows 7 and I see preview of PDF in browser.

**Comment by ZaLiTHkA** [comment]
@saenzramiro, as per your request to test in different browsers, here are some screenshots (with details blurred) of previewing a PDF in Chrome 58.0.3029.81 (64-bit), Edge 38.14393.0.0 and Rambox 0.5.3:

![2017-05-02 08_33_24-pdf preview - chrome](https://cloud.githubusercontent.com/assets/2149312/25606841/e34b6e64-2f13-11e7-95d6-488786326ab9.png)

![2017-05-02 08_35_04-pdf preview - microsoft edge](https://cloud.githubusercontent.com/assets/2149312/25606846/e59f6396-2f13-11e7-80dd-07c76c427166.png)

![2017-05-02 08_33_37-pdf preview - rambox](https://cloud.githubusercontent.com/assets/2149312/25606849/e77c95da-2f13-11e7-95fa-1abfecffe3eb.png)

Could I perhaps get any more information for you if I ran Rambox from source? Perhaps in some sort of debug mode? Or maybe I should ask, would something like that be helpful in this case..?

**Comment by npichot** [comment]
Hi,
Any news on this ?
I'm also having trouble downloading attachments of any kind (except maybe for zip files).
When I select download it opens a link in my web browser (Firefox 57.0.1) but nothing happens then. 
The link doesn't trigger anything and I have to connect directly from my web browser to download my attachments.
Best regards

**Comment by saenzramiro** [comment]
@npichot No, I didn't have time to see this. Will try to investigate this for a future release.

**Comment by npichot** [comment]
ok thank you for the update.
Keep us posted ! Good luck
