### ISSUE TITLE
[Feature request] Open in launcher when minimized in taskbar (windows - working under linux)

### ISSUE THREAD

**Issue by Mumrau** [ramboxapp/community-edition#671]
Hi, 
I didn't really know how to search the existing issues for this but I believe I found nothing related.
I'm using rambox on windows but I suppose there might be the same things under other OS.
I would like to open rambox from when it is minimized in tasker back on my screen by using the launcher:

Metakey on windows + search rambox + press enter would be the sequence

I hope the feature described is clear enough,

Thanks, regards,

**Comment by saenzramiro** [comment]
We can try to do that in a future release.

**Comment by Mumrau** [comment]
Thank you for the consideration! Looking forward to this!

**Comment by Mumrau** [comment]
I can add the fact that I am also using under Linux (Ubuntu 18.04 and 17.10), and that feature requested is working with appindicator and such.
