### ISSUE TITLE
blurry text for all services

### ISSUE THREAD

**Issue by epaumier** [ramboxapp/community-edition#674]
### Steps to reproduce

1.  Launch Rambox
2. Open any services available
3. Text is blurry in general and to make it clear you must move your mouse on the text

### Expected behavior

clear text easy to read

### Actual behavior

blurry text difficult to read

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Win 10
> Arch: x64

**Comment by saenzramiro** [comment]
That's weird. =S

Happens in all services? Did you try by disabling hardware acceleration in Preferences?

**Comment by ibrokemypie** [comment]
same here

**Comment by xhikofff** [comment]
Same here.
I confirm disabling HW acceleration solves the problem.

**Comment by saenzramiro** [comment]
@xhikofff Thank you for sharing.
@epaumier Did you tried what @xhikofff said?
