### ISSUE TITLE
certificate warning with services

### ISSUE THREAD

**Issue by taniadaniela** [ramboxapp/community-edition#676]
I'm seeing the certificate warning with slack, whatsapp and Skype.. Anyway to fix this?

**Comment by saenzramiro** [comment]
Are you using version 0.5.3?

**Comment by taniadaniela** [comment]
I realize this issue was related to a http proxy I was using. Shouldn't these go through https? if I opened the browser there's no issue with the http proxy..

**Comment by saenzramiro** [comment]
I will investigate on this.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
