### ISSUE TITLE
Rambox Helper Terminal Window Opens and Hangs at Startup

### ISSUE THREAD

**Issue by RobertAlan** [ramboxapp/community-edition#677]
Upon start of my MacBook pro, Rambox opens up a terminal window that hangs.

Image: 
<img width="1237" alt="rambox_helperambox_ _172x24_and_rambox" src="https://cloud.githubusercontent.com/assets/5241923/22856419/a5da1af4-f056-11e6-9a9d-088321307da7.png">

### Steps to reproduce

Not sure how to reproduce this outside of my machine.

### ENVIRONMENT

> Rambox:  0.5.3
Platform: darwin (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

> OS: 10.12.4 Beta (16E154a)

**Comment by saenzramiro** [comment]
There is an issue related with this but I fixed it... Well, on latest version is not happening for me. 

Did you tried to uninstall Rambox and install it again?

**Comment by RobertAlan** [comment]
I haven’t yet. I’ll see if that helps.

On Feb 11, 2017, at 9:46 PM, Ramiro Saenz <notifications@github.com> wrote:

There is an issue related with this but I fixed it... Well, on latest version is not happening for me.

Did you tried to uninstall Rambox and install it again?
