### ISSUE TITLE
Facebook Messenger voice calls do not work

### ISSUE THREAD

**Issue by jamesonson** [ramboxapp/community-edition#678]
Clicking the voice call button on Facebook's Messenger does nothing. On a normal browser (Firefox/Chrome) the same button would open a new window using "window.open" Javascript call.

Same for video calls.

### Steps to reproduce

1. Open a contact on Messenger
2. Click "Start a voice call" icon

### Expected behavior

A message showing a call screen opens up (or at worst - a new window in default system browser).

### Actual behavior

Nothing. No new window. No errors or warnings in console.

### ENVIRONMENT

Version: 0.5.3
Platform: linux (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by saenzramiro** [comment]
There is an issue related with this. I was trying to fix this in latest version but no luck. I don't know why Messenger is not firing call in Rambox. Tried to define user agent and others things but don't know... 

I think is related with the integration with Node in Webviews.

**Comment by jamesonson** [comment]
I'll try to dig around the Messenger's javascripts, next week - maybe it's a security feature integrated by Facebook.

**Comment by mirfilip** [comment]
A fact that Franz manages to do exactly what "expected behaviour" states, might be a clue.

**Comment by CryptoD** [comment]
By default on the website calls are opened in the new window. Maybe this is causing the error?

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
