### ISSUE TITLE
JavaScript error...

### ISSUE THREAD

**Issue by ruiumbelino** [ramboxapp/community-edition#684]
After using Rambox for a while, I start to have this error message:
![2017-02-14_10h44_43](https://cloud.githubusercontent.com/assets/10651797/22927303/6a29c6f4-f2a8-11e6-8459-ff2c52ecae6e.png)
If you need more information...

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.14393

**Comment by saenzramiro** [comment]
Seems like this is related with the portable app.

Did you try to install Rambox in your PC?

**Comment by ruiumbelino** [comment]
I can install it and see if this message also appears...

**Comment by ruiumbelino** [comment]
It still happens with Rambox installed on my PC...

![2017-02-27_15h18_58](https://cloud.githubusercontent.com/assets/10651797/23364738/9548bfae-fd00-11e6-8bc7-562b336dc89f.png)

**Comment by ruiumbelino** [comment]
?

**Comment by ruiumbelino** [comment]
I still have this.

How can I help to fix this?

**Comment by nmat** [comment]
@ruiumbelino does this happen on 0.5.9 also?

**Comment by ruiumbelino** [comment]
@nmat , yes.

**Comment by nmat** [comment]
If I where you I would first test to:

1. Uninstall rambox
2. Clear the content (backup to desktop or something) for rambox in: %APPDATA%\Local\
3. Try to install again to see if the error gets removed

Suggestion is also to try and install 0.5.9. I am using windows 10 x64 and works fine for me here I have never encountered this error.

**Comment by ruiumbelino** [comment]
@nmat , I will have to try that...

Thanks

**Comment by ruiumbelino** [comment]
@nmat , I did a fresh install, and still have the same issue...

**Comment by nmat** [comment]
@ruiumbelino can you also test with creating a new account on the machine and install rambox there to see if the error occurs in 0.5.10?

**Comment by ruiumbelino** [comment]
@nmat ,

I don't have a Rambox account, just local services.

Do you want that I delete all services, remove everything from Rambox, and start again with v0.5.12?

**Comment by nmat** [comment]
No I mean a new login on the same computer. And try with that.

**Comment by ruiumbelino** [comment]
@nmat ,
I tried a new login, and get the same...

**Comment by Ash258** [comment]
Continue in #1656
