### ISSUE TITLE
No more notifications on Telegram channel

### ISSUE THREAD

**Issue by ktrls** [ramboxapp/community-edition#688]
Hi,
I don 't n know if this is a behaviour of this version, but in the lasta weeks I don't see any notification on Telegram's post

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Linux Manjaro Cinnamon

> Arch: x64

**Comment by saenzramiro** [comment]
Do you have "Show notifications" option in Rambox service settings?

**Comment by ktrls** [comment]
yes, I confirm it

**Comment by saenzramiro** [comment]
And what about "Don't Disturb"? Is OFF?

**Comment by ktrls** [comment]
yes, is off
