### ISSUE TITLE
Support common back/forward keyboard shortcuts

### ISSUE THREAD

**Issue by TravisCarden** [ramboxapp/community-edition#690]
Similar to #243, there are some common keyboard shortcuts for navigating back/forward in a browser that (I think) should be supported inside Rambox, e.g., `⌘+[` and `⌘+]` on Mac (I *think* it's `CTRL+←` and `CTRL+→` on Linux/Windows).

**Comment by shr1k4nt** [comment]
Is this functionality added to the app?

**Comment by saenzramiro** [comment]
Ok, I just checked in Windows and is `Alt` instead of `Ctrl` key.

**Comment by adavidzh** [comment]
Just to note that on MacOS X, these are usually `⇧⌘[` to switch to tab on left and `⇧⌘[` to switch to tab to right.

**Comment by hoelzro** [comment]
For Slack, I just added this custom code to make `Ctrl + [` and `Ctrl + ]` go back/forwards:

```javascript
document.addEventListener('keydown', function(e) {
  if(e.getModifierState('Control')) {
    if(e.key == '[') {
      history.back();
    } else if(e.key == ']') {
      history.forward();
    }
  }
});
```

There's probably a more elegant way to get this working more generally within Rambox itself, but I'm not familiar enough with the codebase to be able to say what that is.

**Comment by shanness** [comment]
Thanks very much @hoelzro !  Works perfectly, and a been driving me crazy not having a way back to my last convo in slack in Franz and Rambox..  Here's the code for Linux (and I think it's the same on Windows).

```javascript
document.addEventListener('keydown', function(e) {
  if(e.getModifierState('Alt')) {
    if (e.keyCode == '37') { // left arrow
      history.back();
    } else if (e.keyCode == '39') { // right arrow
      history.forward();
    }
  }
});
```

**Comment by el-seirh** [comment]
@shanness Nice! The JS-code looks easy as pie but my problem I currently don't have a clue where to put it ... did you edit the app.js directly or where did you place it?

**Comment by hoelzro** [comment]
@el-seirh If you go to the services tab in Rambox, click on the gear next to a Slack service, and click on the "Advanced" section, there's a "Custom code" input where you can paste that code.

**Comment by el-seirh** [comment]
@hoelzro Cool, did not know that custom code feature. Works like a charm, thanks!

**Comment by fvulich** [comment]
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Comment by shanness** [comment]
Damn, I upgraded and it's working worse than my fix..  Works a couple of times then stops.  And if you change tabs and come back, it doesn't work at all (Alt left and right). 

Without changing the tab, I can got back, then forward, but then it stops working..
