### ISSUE TITLE
Replace prompt/alert/confirm with electron alternatives

### ISSUE THREAD

**Issue by Zottelchen** [ramboxapp/community-edition#694]
### Steps to reproduce

1.  Try to open a website with javascript prompt/alert/confirm

### Expected behavior

Prompt/alert/confirm opens

### Actual behavior

Error: prompt() is and will not be supported. (see electron/electron#472)

### Idea

Maybe automatically replace promt/alert/confirm with an appropriate alternative:
https://www.npmjs.com/package/vex-js
https://www.npmjs.com/package/dialogs
https://www.npmjs.com/package/smalltalk

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Win10

> Arch: x64

**Comment by s1113950** [comment]
This will help with Kerberos/IWA auth as well! It shows up to users as a popup box to enter username and password. It's also how browsers prompt for BASIC auth.

**Comment by hashdang** [comment]
This will also help with renaming grains in Sandstorm, which is currently impossible in Rambox since Sandstorm uses `prompt()`.
