### ISSUE TITLE
[Feature Request] use favicon as logo for custom services

### ISSUE THREAD

**Issue by SimJoSt** [ramboxapp/community-edition#699]
Most web services provide a favicon and provide it in different sizes and qualities.
In my opinion, it should be possible to automatically pick the logo for a custom services, by using the favicons.
If web services differ too much in their standard and behavior of favicons, I suggest pulling all of them into the service settings and giving the user the opportunity to choose one of them.

Only if a custom logo is wanted, the user could provide a link.

This would help a lot of non-advanced users, as they lack the expertise to find a link to the logo in the source code.

**Comment by Bonez76** [comment]
An option when you create a custom service if you want to use the favicon of the URL would be a nice idea. But only if the URL provides a reasonable size, 32x32 or 16x16 px would not look very good as service icon.

**Comment by bcbane** [comment]
I would love to see this as well. some custom services only change their favicon to represent whether something has changed. So if custom badging isn't working then the favicon would resolve this

**Comment by fvulich** [comment]
I'm gonna close this ticket because it seems to be fixed by now, feel free to open another ticket if the problem persists.
