### ISSUE TITLE
OSX - Service bar scrolling does not work properly

### ISSUE THREAD

**Issue by ziritrion** [ramboxapp/community-edition#7]
OSX El Capitán, Rambox 0.3.0, Macbook Pro. When Rambox has more services than what the service bar can display, scrolling is jerky with the touchpad and it's not easy to switch between services.

**Comment by saenzramiro** [comment]
Interesting! I can reproduce it, so I will take a look for the next release.

In the meantime, you can use the arrows that displays on each edge.

**Comment by raveem** [comment]
Can we get rid of the scrolling and have a wrapped service bar please? It destroys the point of at-a-glance checking for any notifications. This is one area where Franz certainly delivered (see screenshot).

![image](https://user-images.githubusercontent.com/6374306/27218589-9f38ce16-5276-11e7-8586-a2edc36e5ed3.png)

**Comment by saenzramiro** [comment]
We will add an option for this in a future release.
