### ISSUE TITLE
Bad rendering when disabling Hardware Acceleration

### ISSUE THREAD

**Issue by joaomlneto** [ramboxapp/community-edition#701]
Due to issue #538 I've resorted to disabling hardware acceleration in Rambox.

However, some of the services, some of the time, will not render correctly. This may include flickering, or even incomplete renders.

The one that is easiest for me to reproduce is enlarging an image on a WhatsApp chat.

### Services that see some weird behavior
- Rocket Chat (messages flicker)
- WhatsApp (enlarging an image in a chat causes flickering and incomplete/unstable rendering; scrolling in a chat causes flicker)

### Services that seem to work OK
- Gitter
- Hangouts
- Messenger
- Telegram

### Steps to reproduce
1. Open an WhatsApp conversation that has an image in the chat
2. Click the image to enlarge it -- it will render badly -- with flickers, and incomplete rendering.
#### Without hardware acceleration
![with_hw_accel](https://cloud.githubusercontent.com/assets/1539767/23237021/cf4dd4b2-f95b-11e6-9c39-32e7585d72bc.png)

#### With hardware acceleration
![without_hw_accel](https://cloud.githubusercontent.com/assets/1539767/23236953/935af14c-f95b-11e6-92c7-4f0a7cb969fe.png)

### ENVIRONMENT
> Macbook Pro (Mid 2015) with Discrete Graphics
> Rambox: v0.5.3
> OS: macOS 10.12.3
> Arch: x64

**Comment by Aktariel** [comment]
Related, but not quite the same thing - would be very helpful to have an option to not use the dedicated card for hardware acceleration on MacBook Pros. (or even just use the integrated card period). Having Rambox use the dedicated GPU kills battery life.

**Comment by joaomlneto** [comment]
Issue is still valid.

**Comment by joaomlneto** [comment]
If it's an upstream bug, then I think this can be closed.

It would be nice if there is a *semi-automatic* workaround in the meantime, since it has remained unpatched for so long and there's no ETA.
