### ISSUE TITLE
[services request] Quassel Webserver

### ISSUE THREAD

**Issue by ideologysec** [ramboxapp/community-edition#704]
Tried adding quassel-webserver to Rambox as a custom service, and it didn't work. (https://github.com/magne4000/quassel-webserver). All that happens is a blank white screen comes up with no options to log in, or anything really.

Works in Chrome 56 on OS X; not sure if I need to add custom code or what the issue is.

**Comment by saenzramiro** [comment]
Is there a possibility to share with us a URL to try it and test?

You can send me a PM in Gitter.

**Comment by Aktariel** [comment]
All of the instances I have running are currently logged in to private/sensitive channels. I can see about setting up a demo server somewhere, but it might take a while.

**Comment by rodneyrod** [comment]
Confirmed not working for me either.

**Comment by rodneyrod** [comment]
Found out that this is fixed in a yet to be merged pull request

https://github.com/magne4000/quassel-webserver/pull/240
