### ISSUE TITLE
Links in Skype-Chat don't work

### ISSUE THREAD

**Issue by gossi** [ramboxapp/community-edition#711]
### Steps to reproduce

1. Add Skype and start chatting with somebody
2. Send a link
3. Click the link

### Expected behavior

Link opens in system default browser

### Actual behavior

Nothing happens

### ENVIRONMENT

> Version: 0.5.3
> Platform: darwin (x64)
> Electron: 1.4.15
> Chromium: 53.0.2785.143
> Node: 6.5.0

**Comment by Stanzilla** [comment]
can confirm

**Comment by saenzramiro** [comment]
Did you follow this steps?

https://github.com/saenzramiro/rambox/wiki/Skype#links

**Comment by nmat** [comment]
Just tested it. Clicking the link no matter if the option is enabled or disabled did not work.

Right click -> Open works just fine though (even if option for weblink is enabled or disabled)

**Comment by gossi** [comment]
I didn't know about that option. Yet, tried to disable it. I use the german version of skype, when I right click a link (or preview) I only do have two options in the context menu (1) Copy as quote (2) Copy text. I was hoping for a "open" option as third item, I don't have such. Unfortunately the mentioned todos on your document don't work.

**Comment by Mutahhar** [comment]
I am experiencing sam issue as @gossi.
There is no option of "Opne" on right click

**Comment by saenzramiro** [comment]
I just tested and realized that now Skypes switched that functionality to preview links. I updated the wiki, so please take a look.

**Comment by Mutahhar** [comment]
@saenzramiro thanks thats working.

**Comment by gossi** [comment]
Unfortunately doesn't work with the german version of skype. That's what's my skype-web-versions info says:

> App-Version: 1.87.47
> 
> Version der Assets: 0.0.300

What's your App-Version?

**Comment by saenzramiro** [comment]
> App version: 1.91.33
> Assets version: 0.0.300

If is the version for german, you will have to wait until Microsoft release the new version for german.

**Comment by gossi** [comment]
@saenzramiro They updated the german version to `1.91.33` and with preview it works. Any chance getting this done without preview?

**Comment by dluciv** [comment]
Preview helps.

But actually I tried dirtier hack to allow just clicking, but it faied. I tried adding following JavaScript to Skype settings:

    document.onmousemove = function(evt) {
      var t = evt.target;
      if(t && t.localName == 'a' && t.target == '_blank') {
        t.removeAttribute('onclick');
        t.removeAttribute('rel');
      }
    };

Any ideas about why it fails to help?

**Comment by lukaszblacha** [comment]
upvote, that would be really useful

**Comment by divory** [comment]
if you have a mouse you can click using the wheel (press vertically down on it) that opens the links in my browser :) (windows 10 using Chrome)

**Comment by pierrerigal** [comment]
+1 same error here in 0.5.12 on a mac.

**Comment by saenzramiro** [comment]
@pierrerigal @lukaszblacha Did you tried https://github.com/saenzramiro/rambox/wiki/Skype#links?

**Comment by pierrerigal** [comment]
Yes, it's already activated. Right click just allow me to "copy as quote" and "copy text". (in french).

**Comment by roland-d** [comment]
Just to give my experience. When a user sends me a link in the text, I can click it but nothing happens. Enabling the preview mode, shows me the preview but I can only 'Copy as quote' or 'Copy as text'. So I tried directly on Skype web via web.skype.com and if I disable the preview mode I can click the link in the user text and it opens the link. When I enable preview mode it shows the preview and I can right click and have the two options to  'Copy as quote' or 'Copy as text' but clicking on the preview opens the link. Not sure if this is useful to debug the issue but opening links in Rambox doesn't work for me in Skype.

**Comment by randydod-teamunify** [comment]
Similar problem to roland-d using Rambox 0.5.16. I'm on a MacBook Pro (15 inch, early 2013) using High Sierra 10.13.3. My default browser is Firefox 58.0.2 (64-bit). When I right click a link, the only options are Copy as Quote and Copy Text. Clicking the link does nothing. Behavior is same whether or not Web link previews are enabled.

I logged into Skype for Web in Firefox and had the same setting enabled. Right clicking gives four options (Copy as Quote, Quote Message, Copy link, Open), and clicking a link opens it in a new tab.

**Comment by saisurya-k** [comment]
@gossi  Using Ctrl + Click or Cmd+Click is opening the links in browser.(Fallback option)

**Comment by randydod-teamunify** [comment]
@saisurya-k That does not work in the Mac version.

**Comment by saisurya-k** [comment]
@randydod it's working for me.

**Comment by randydod-teamunify** [comment]
Well, I don't know what to say, because it's not for me. I've rebooted many
times since I originally wrote this. I checked today and have the latest
version for Mac (0.5.17). It's behaving exactly like it did when I
originally commented. Left clicking a link in Skype does nothing. Right
clicking and command+clicking both bring up a context menu that only has
"Copy as Quote" and "Copy Text" available.

[image: Randy Dod]
*Randy Dod*
*Senior ​Product Trainer and ​Technical​ Writer*
*TeamUnify, LLC*
541.306.4982
TU Blog <http://hubs.ly/H03W7vB0> | Facebook
<https://www.facebook.com/teamunify> | Twitter
<https://twitter.com/TeamUnify>
[image: TeamUnify powered by SportsEngine]
<http://www.teamunify.com/swim-team-management/>
​

**Comment by roland-d** [comment]
On my Windows machine, nothing happens clicking on the link, also no go when I hold the CTRL. At least when I right click I have the option to Open the link and that works for me.

**Comment by roland-d** [comment]
On my Mac machine it is the same as on my Windows machine, except that I don't even have the `Open the link` option. Just `Copy as quote` and `Copy Text`.

**Comment by maxerbox** [comment]
Bump

**Comment by saenzramiro** [comment]
This will be fixed in next version.

To make it work, user needs to disable Links Previews in Skype settings.
