### ISSUE TITLE
[Request] keep chosen Zoom for each service

### ISSUE THREAD

**Issue by ruiumbelino** [ramboxapp/community-edition#716]
Hi,

I would like to request that Rambox keep chosen Zoom for each service...

Thanks

**Comment by guedressel** [comment]
As I just mentioned in #539:
Stored zoom levels may not be synced between different hosts.

But resolving this issue would really improve the experience to run Rambox on machines with higher resolutions or for people with impaired eyesight.

**Comment by saenzramiro** [comment]
Zooms for each service it should work, and should be persistent. But I know there was a bug related with this in Electron and they fixed, so probably in next version it will work ok.

**Comment by jaklan** [comment]
> Zooms for each service it should work, and should be persistent. But I know there was a bug related with this in Electron and they fixed, so probably in next version it will work ok.

Still doesn't work ok, it's not persistent.
