### ISSUE TITLE
The facebook messenger session, has disappeared

### ISSUE THREAD

**Issue by eduengler** [ramboxapp/community-edition#725]
There are chrome version mismatch warnings,
"This version of Google Chrome is no longer supported. Upgrade to a supported browser."
and,
The facebook messenger session, has disappeared. 

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-62-generic

**Comment by saenzramiro** [comment]
Can you share a screenshot of the warnings?
