### ISSUE TITLE
Laptop web camera stays on after trying to click a photo in Whatsapp. 

### ISSUE THREAD

**Issue by meets7** [ramboxapp/community-edition#726]
1. Integrate Whatsapp.
2. Select any contact and click on attachment icon and then camera icon.
3. Camera starts up. Without clicking any picture, turn off the camera from the top left corner in the Whatsapp interface. Camera stays on - apparent because of the web cam indicator light stays on. 

Needed to quit Rambox and start again to turn it off. 

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.4.0-64-generic

**Comment by gossi** [comment]
Confirmed. Same if you take a photo.

**Comment by saenzramiro** [comment]
I think is a Chromium bug, because if I video-call someone in Hangouts with Google Chrome and finish the video-call, my light still on. But if I video-call again and finish it asap, it will turn off.
