### ISSUE TITLE
Pic and Gif an other telegram bots does not work 

### ISSUE THREAD

**Issue by Koma-Andrea** [ramboxapp/community-edition#730]
if you try to use @gif or @pic it shows white boxes instead of the images.

-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.15048

**Comment by Bruce17** [comment]
A similar issue occurs using [Rocket.Chat](https://rocket.chat/). Already existing gifs are loaded and animated. If a add/paste a new gif e.g. using the giphy bot an image will be displayed, but the gif is not animated.

> Rambox: 0.5.3
> Electron: 1.4.15
> win32 (x64) Version 6.1 (Build 7601: Service Pack 1)

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
