### ISSUE TITLE
Support for Chrome extensions?

### ISSUE THREAD

**Issue by orschiro** [ramboxapp/community-edition#732]
Dear all, 

I am not sure if it is technically possible and I would like to hear your opinion. 

Rambox is great. I use it to work in my Inbox by Gmail.

I used to use Inbox by Gmail in my Chrome web browser. 

On Chrome I have access to the [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen) and the [LanguageTool](https://languagetool.org/) extensions that help me write my emails better. 

I really miss them on Rambox. 

Is it somehow possible to integrate and support the installation of Chrome extensions?

This would be a game changer!

Yours,

Robert

**Comment by fortran77** [comment]
It would be great to have more of the native browser functionality. Not just extensions, but also as many other things as possible. E.g.: copy-and-paste via a context menu; highlight text and do a web search for it; highlight text and invoke Google Translate on it; view Downloads; etc.

The essential feature offered by Rambox is to provide a separate environment for local data in each tab. Ideally all other web browser functionality should be accessible to the user.

**Comment by danielmcoelho** [comment]
Grammarly is a must. MailTracker also.
Without these extensions, my Gmail inbox looks naked. Read only!
Any support for extensions on the roadmap?

**Comment by saenzramiro** [comment]
Sadly, Electron don't support this and seems like they don't have plans to do it.

Check it here: https://github.com/electron/electron/issues/1498#issuecomment-96995155

**Comment by bundyo** [comment]
https://github.com/electron/electron/releases/tag/v1.7.6
https://github.com/electron/electron/pull/9918
:)

**Comment by danielmcoelho** [comment]
I stopped using Rambox 5 months ago because of the essential extensions I use (I've been using Chromium has a replacement). Finally, some good news!

**Comment by mkusz** [comment]
@saenzramiro Hey. Please reopen this issue. Take a look at @postadelmaga link. It's possible to install extensions so it will be great to at Grammarly and/or other extensions into Rambox.

**Comment by kuyen** [comment]
any news/update about this issue? it will be great if Rambox can support custom extensions...

**Comment by saenzramiro** [comment]
I have been playing around with this a few months ago but no luck. Does anyone have an example how to do it?

**Comment by coollorenzo** [comment]
Any updates? I'm a new rambox user and I really need the hubspot extention in order to use it :(. I saw wavebox supporting chrome extentions but it seems like they have to add manual support for every extention. So i guess I won't be using rambox for my email

**Comment by ugachmaaz** [comment]
Love Rambox but desperately need this.. Please reopen!

**Comment by dakipro** [comment]
+1 - Just wanted to support this feature. I would like to use todoist extension in gmail. Thanks!

**Comment by burtonator** [comment]
+1 . this seems to be a major feature...  I want this!

**Comment by ReyPena** [comment]
This can be done in electron using the BrowserWindow api this is the code for electron I will like to help to add this feature https://github.com/electron/electron/blob/5dcc354432bd9b6ca09c5cb887eac3a216820b8a/lib/browser/chrome-extension.js#L360

**Comment by geofflittle** [comment]
Heyo, has this feature been added?  Would love to see this supported in Rambox

**Comment by geofflittle** [comment]
@saenzramiro Would it be possible to reopen this issue?  Thanks.
