### ISSUE TITLE
Note Services

### ISSUE THREAD

**Issue by cukabeka** [ramboxapp/community-edition#74]
Another Idea; I'd love to have Note services in Rambox: OneNote, Evernote and Synology NoteStation for example. The last one would be extremely helpful, as there is no standalone App yet (but a chromium extension exists). 

## 

> Rambox 0.3.0
> Electron 1.2.5
> darwin x64 14.5.0

**Comment by fungs** [comment]
SimpeNote (www.simplenote.com) works nicely. This could be added to the list of services.

Use https://app.simplenote.com as address.

**Comment by fvulich** [comment]
Since the creation of the issue several note apps has been added to Rambox CE. For that reason I will close this ticket.
