### ISSUE TITLE
Notifications MightyText

### ISSUE THREAD

**Issue by rominail** [ramboxapp/community-edition#746]
### Expected behavior

Rambox doesn't handle notifications for MightyText, you have to manually check if you receive a message, could be cool and handy to get it

PS (to everybody supporting the code) your work is wonderful and really handy everyday ;)

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Ubuntu 16.04

**Comment by saenzramiro** [comment]
Did you check the configurations of MightyText to see if you can enable it there?

**Comment by rominail** [comment]
Didn't find something relating to notifications

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
