### ISSUE TITLE
Steam Chat: no unread count on tab

### ISSUE THREAD

**Issue by Jimi-James** [ramboxapp/community-edition#76]
I just switched over from Franz, which does not have this bug, and I could've sworn Rambox didn't have this bug when I first started using it 5 days ago, but now it definitely does (even though I have not upgraded it or reinstalled it since). If I receive a new message in Steam Chat, no unread count shows up in the tab. That means I have to keep checking that tab if I want to know that other people messaged me. I'm not having this issue with any other service I'm using: Facebook, Google Hangouts, Discord, GroupMe, and Skype.

**Comment by BastiPfa** [comment]
I've experienced the same issue with Telegram

**Comment by thejoycekung** [comment]
I'm having the same issue with Office 365 !

**Comment by saenzramiro** [comment]
Thanks! I will take a look on this.

**Comment by Jimi-James** [comment]
Running 0.4.0. Still not getting an unread count in my Steam tab. I have all the notification checks checked, both in the Steam Chat page and in Rambox.

**Comment by saenzramiro** [comment]
For Steam, it will be fixed in 0.4.1.

I will take a look on Discord.

**Comment by Alex314Ru** [comment]
Version: 0.5.17 (AppImage)
Platform: linux (x64) (Linux Mint 18.3)
Electron: 1.8.4
Chromium: 59.0.3071.115
Node: 8.2.1

Steam Chat notifications are enabled in both - the tab and Steam Chat options. OS shows notifications with its popup messages, but there is no messages counter on the tab, and tray icon doesn't turn red when I receive new messages. For example, with WhatsApp tab everything works fine.

**Comment by Ash258** [comment]
Steam changed its GUI. Not sure if it break our counter. Reoping since i can investigate.
