### ISSUE TITLE
feature request: unseen.is

### ISSUE THREAD

**Issue by edmundlaugasson** [ramboxapp/community-edition#770]
### Steps to reproduce

1. try to add Unseen.is account (https://unseen.is))
2. not listed option
3. currently can added using _Custom Service

### Expected behavior
App listed among available options.
Unseen has both chat and e-mail.

### Actual behavior
currently can added using _Custom Service
every time Rambox refresh or reopen, Unseen is logged out...

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1 MATE
> Arch: x64

**Comment by saenzramiro** [comment]
Unseen seems to not preserve session by default, because if you use it in your default browser and reload it once you are in, it will ask again for your credentials. So it's not a Rambox issue.
