### ISSUE TITLE
feature request: MEGA.nz

### ISSUE THREAD

**Issue by edmundlaugasson** [ramboxapp/community-edition#773]
### Steps to reproduce

1. try to add mega.nz
2. not listed among current apps
3. cannot add

### Expected behavior
App is listed and can be added, preferally as browser extension. Even MEGA is famous with its cloud storage, it has also text, audio, video chat.

### Actual behavior
App not listed but can added as custom app. Actually MEGA suggests to use browser extension to log in more securely. Currently adding browser extension is not possible. Only logging using username, password would be possible in case of custom app.

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1 MATE
> Arch: x64

**Comment by saenzramiro** [comment]
We are not planning to add this services by default because is not an Email or Messaging app. Sorry.

**Comment by edmundlaugasson** [comment]
Actually MEGA has also text, audio, video chat.

**Comment by saenzramiro** [comment]
Ok, so we will take a look then.

Thank you.
