### ISSUE TITLE
tutanota second account disappeared

### ISSUE THREAD

**Issue by edmundlaugasson** [ramboxapp/community-edition#774]
### Steps to reproduce

1. add e.g. two tutanota accounts
2. after refreshing second account disappeared
3. also not listed among other accounts

### Expected behavior
All acounts listed and exist also after Rambox refresh or reopen.

### Actual behavior
Second account disappeared.

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1 MATE
> Arch: x64

**Comment by saenzramiro** [comment]
What about in your default browser? Works?

**Comment by edmundlaugasson** [comment]
Yes - no problem. I need to open in two different browsers. Also using normal and private session would help to log in with two different accounts. I guess this session handling is not an issue for Rambox.

**Comment by saenzramiro** [comment]
You can add two Tutanota services in Rambox for each account.
