### ISSUE TITLE
zyptonite missing after refreshing or reopening

### ISSUE THREAD

**Issue by edmundlaugasson** [ramboxapp/community-edition#775]
### Steps to reproduce

1. add zyptonite account
2. refresh or reopen Rambox
3. zyptonite is missing

### Expected behavior
Added zyptonite will remain logged in

### Actual behavior
zyptonite account were missing

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1 MATE
> Arch: x64

**Comment by saenzramiro** [comment]
Do you still have this issue?

Did you tried to remove Zyptonite service and add it again?

**Comment by edmundlaugasson** [comment]
Yes. When adding and then refreshing then Zyptonite is disappeared.
