### ISSUE TITLE
Riot freezes (cannot use)

### ISSUE THREAD

**Issue by edmundlaugasson** [ramboxapp/community-edition#784]
### Steps to reproduce

1. log in with Riot account
2. try to interact (use the program)
3. interaction not possible - cannot click

Even reloading either Riot service (CTRL+SHIFT+R) or whole Rambox (CTRL+R) does not help. When closing app at all and reopen - then it finally works.

### Expected behavior
Riot can be used.

### Actual behavior
Riot can NOT be used.

### ENVIRONMENT
> Rambox: v0.5.3
> OS: Linux Mint 18.1 MATE
> Arch: x64

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
