### ISSUE TITLE
WhatsApp vocal messagess

### ISSUE THREAD

**Issue by nicolangr** [ramboxapp/community-edition#79]
Vocal messages are mute when played in mute notifications mode

## 

> Rambox 0.3.0
> Electron 1.2.5
> linux x64 3.19.0-32-generic

**Comment by dingsbums** [comment]
fyi videos on messenger are also muted when in "mute notifications mode"

**Comment by saenzramiro** [comment]
Ok, I will take a look. Thanks!

**Comment by saenzramiro** [comment]
**Don't disturb mode** or muting a service is like silencing a tab in any web browser. All sounds produced in that tab will be muted.

But, I can try to find a way to detect when the user produced manually a sound and play it. I don't think this is possible but I will give it a try.

http://electron.atom.io/docs/api/web-view-tag/#event-media-started-playing

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
