### ISSUE TITLE
Blank after first start without proxy

### ISSUE THREAD

**Issue by matrixik** [ramboxapp/community-edition#797]
### Steps to reproduce

1. Install new version on clean computer that need proxy to connect to internet
2. Start app without setting proxy

### Expected behaviour

Open main app page and allow me to go to settings to set up proxy (first page and settings should work regardless of internet connection).

### Actual behaviour

Blank page, sometimes showing starting animation but not going to main menu with all services. Not able to go to settings.

### ENVIRONMENT

Version: 0.5.3
Platform: linux (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

## Workaround

Found in comment https://github.com/saenzramiro/rambox/issues/203#issuecomment-242400620 that I need to set up proxy with cmd line.
Rambox started properly with `--proxy-server=` switch and then I was able to set up proxy in settings.

**Comment by matrixik** [comment]
Also looks like it also does not read system `http_proxy` nor `https_proxy` environment variables.

**Comment by Tronic69** [comment]
Nearly the same here. I added proxy in settings on Rambox tab, but all tabs of added services stay blank. Maybe because proxy needs authentication and I´m not asked for it by Rambox.

Version: 0.5.3
Platform: win32 (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by adocampo** [comment]
Startings it the first time with the `--proxy-server=` parameters workarounds for me, but to be fair, it would be a great improvement to let configure it inside the GUI.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
