### ISSUE TITLE
MacOS 10.12 fullscreen/splitscreen restore

### ISSUE THREAD

**Issue by krobipd** [ramboxapp/community-edition#799]
i have a splitscreen setup on my Mac (macOS 10.12.4) - so in the left site I have the apple messenger app and on the right the Rambox app - 50 % / 50% split.

when I restart the Mac with the option so save the apps and restore them. Rambox doesn't remember that is was fullscreen and doesn't remember that it was in split view with apples messenger app.

-
> Rambox 0.5.3
> Electron 1.4.15
> darwin x64 16.5.0

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
