### ISSUE TITLE
Mac icon replacement

### ISSUE THREAD

**Issue by hacknug** [ramboxapp/community-edition#800]
I wasn't feeling the not-full-native look of the icon on macOS and I decided to tweak it a little. Showing what I came up with just in case anyone else is interested.

I can share the .icns files and/or open a PR if you'd want to include it.

<img width="1680" alt="captura de pantalla 2017-04-13 a las 17 15 07" src="https://cloud.githubusercontent.com/assets/1107521/25012524/0de74d66-2071-11e7-86e4-5dfa74624c97.png">

**Comment by saenzramiro** [comment]
This is awesome! Please, send to us the vectorized logo and we will create the icns.
rambox[at]protonmail.com

Thanks!
