### ISSUE TITLE
Add default JS to hide 'download app' links

### ISSUE THREAD

**Issue by jamy015** [ramboxapp/community-edition#803]
Some services (e.g. Slack and Discord) show prominent links in their web interface to download their desktop apps. There can also be other unwanted elements, such as the 'sign in to another team' link in Slack (users should do this by adding another Slack service to Rambox).

Some examples:
![image](https://cloud.githubusercontent.com/assets/3188721/25037885/f9f7ee74-20fb-11e7-9a1e-e0ce4887ff71.png) ![image](https://cloud.githubusercontent.com/assets/3188721/25038003/9b03916a-20fc-11e7-96f1-837f57bf3e06.png)

These links could probably be hidden using some JavaScript (e.g. for Slack, it's a matter of hiding 2 CSS classes). I wanted to work on this, but I didn't see any way to add 'default custom JS' to services (only `js_unread`, but that wouldn't be the right place, of course).

To clarify, this JS should run once when the page has completed loading.

**Comment by saenzramiro** [comment]
You can add Custom Code to each service in the the Service settings.

https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code

In a future release, we will add CSS Injection.

**Comment by jamy015** [comment]
Yes, every user can do that individually in the service settings. However, I am talking about doing this by default to hide some things that don't make sense in Rambox.

It shouldn't be necessary for every Rambox user to hide these links individually if we can provide some sensible defaults.

**Comment by saenzramiro** [comment]
Oh, I see... Ok, we will consider it.
