### ISSUE TITLE
Javascript error on startup

### ISSUE THREAD

**Issue by taniadaniela** [ramboxapp/community-edition#813]
On MacOs 10.12.4
Version: 0.5.3
Platform: darwin (x64)
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

![screen shot 2017-04-18 at 8 16 45 pm](https://cloud.githubusercontent.com/assets/5315791/25158164/3b2cffd0-2474-11e7-98fc-8dfa8b8c1c89.jpg)

**Comment by saenzramiro** [comment]
Did you installed the app or you just run it?

**Comment by taniadaniela** [comment]
I just restart my computer and when I opened the app I get the error.

**Comment by saenzramiro** [comment]
But did you installed it or are you running like a portable app?
