### ISSUE TITLE
No indication of a new message to a selected Hipchat chat 

### ISSUE THREAD

**Issue by justpusher** [ramboxapp/community-edition#814]
If a new message comes to a chat that is already selected, Rambox does not indicate there is a new message. 
Most likely this is because Hipchat does not display (1) indicator for a selected chat. 
Nevertheless, Hipchat displays an unread indicator with favicon (I've tested in Firefox). 

Popup notifications are displayed as usually. But it's very easy to miss the message if I missed the popup accidentally. 

### Steps to reproduce

1. Open a private chat with someone in Hipchat
2. Minimize Rambox
3. This person sends you a private message

### Expected behavior

Rambox displays there is an unread message with a red tray icon

### Actual behavior

Rambox's tray icon is white.

### ENVIRONMENT

> Rambox: 0.5.3
> OS: Ubuntu 16.04.2 LTS
> Arch: x64
Electron: 1.4.15
Chromium: 53.0.2785.143
Node: 6.5.0

**Comment by philiplb** [comment]
Confirmed, this is very annoying causing missed conversations.

**Comment by Kianda** [comment]
A solution (for now) is to create a new private room (with no one inside) and remember to select it every time we close/minimize rambox.
I know is very annoying so my question is:
The is a way to catch with JavaScript code the minimize/close of rambox/hipchat service event and then select this 'empty room' created previously?
Or maybe set an inactivity timer and then after that select the 'empty room' as active chat.

I know it's just a workaround but it's something...

**Comment by joe776** [comment]
There is the following error in the console:
```
PATCH https://hipchat.mycompany.com/v2/readstate?expand=items.unreadCount 502 (Bad Gateway)
value @ readstate_request.js:48
value @ readstate_request.js:80
value @ index.js:195
value @ index.js:295
r @ readstate_request.js:25
```
