### ISSUE TITLE
Tray icon in Ubuntu 17.04 needs workaround

### ISSUE THREAD

**Issue by ivoanjo** [ramboxapp/community-edition#818]
### Steps to reproduce

1. Start rambox on Ubuntu 17.04

### Expected behavior

Tray icon is present.

### Actual behavior

No tray icon appears.

### ENVIRONMENT

**Rambox**: v0.5.3-94
**OS**: Ubuntu 17.04
**Arch**: x64

---

After upgrading from Ubuntu 16.10 to 17.04 today, Rambox's tray icon was gone. Googling around I found that this also affected other applications:

* http://www.webupd8.org/2017/04/fix-appindicator-not-working-for.html
* http://www.webupd8.org/2017/03/fix-dropbox-indicator-menu-not-working.html

The workaround is simple enough, and I have my tray icon back, but I would like to request that it be included in the official packages, so other users don't need to google around and fix it manually as I had to :)

Thanks for Rambox!

**Comment by saenzramiro** [comment]
Thank you @ivoanjo, I will take a look on this.

**Comment by MaxySpark** [comment]
`[Desktop Entry]
  Name=Rambox
  Comment=Rambox
  Exec=env XDG_CURRENT_DESKTOP=Unity "/opt/Rambox/rambox"
  Terminal=false
  Type=Application
  Icon=rambox
`

not working in Ubuntu 17.04

http://www.webupd8.org/2017/04/fix-appindicator-not-working-for.html
it works on Slack, Nylas Mail and Discord

**Comment by MaxySpark** [comment]
finally working 
edited the .desktop file from `/usr/share/application'

```
[Desktop Entry]
Name=Rambox
Comment=Rambox
Exec=env XDG_CURRENT_DESKTOP=Unity /opt/Rambox/rambox %U
Terminal=false
Type=Application
Icon=rambox
```

**Comment by flexiondotorg** [comment]
@saenzramiro To fix the issue libappindicator not being able to write the icon export `TMPDIR=$XDG_RUNTIME_DIR` in the `command:`, something like this:

command: env TMPDIR=$XDG_RUNTIME_DIR PATH=/usr/local/bin:${PATH} ${SNAP}/bin/desktop-launch $SNAP/usr/share/example/Example

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
