### ISSUE TITLE
Gmail Email Notification Opening Blank Pages

### ISSUE THREAD

**Issue by JamesValero** [ramboxapp/community-edition#834]
### Steps to reproduce

1. Wait for new email
2. Click on email notification
3. A small blank window will appear and a new tab will open in Chrome (default browser)

### Expected behavior

The small popup window will have contents of email

### Actual behavior

The small popup window is blank and a new empty tab in Chrome is opened

### ENVIRONMENT

> Rambox: v0.5.3

> OS: Sierra

> Arch: x64

**Comment by rbhalla** [comment]
I would personally expect the notification to open the email in Rambox (like some other notifications do)

**Comment by saenzramiro** [comment]
I tried to prevent popup in Gmail but no luck. Seems like they open it manually in their code.

I will keep this issue opened until we find a way to do it.

**Comment by maxerbox** [comment]
Fixed in #1864
