### ISSUE TITLE
Programmatically get unread message count for a service?

### ISSUE THREAD

**Issue by iliyang** [ramboxapp/community-edition#841]
Since there are (unfortunately) no plans for a menu bar icon for macOS, I'm trying to create one myself, using [Hammerspoon](https://github.com/Hammerspoon/hammerspoon). For this, I need to: 1. Hook somewhere in Rambox (e.g. at the point where it updates the unread counts), and
2. Notify Hammerspoon of any changes. 
Any idea how to achieve any of the two?

Or is there a better way? All want is to have an indication on the menu bar if a particular Rambox service has unread messages.

**Comment by iliyang** [comment]
I've figured out that I can notify Hammerspoon by making it handle "hammerpoon://" URLs, which I can launch from a script inside Rambox.

So only one question remains: Where should I hook in Rambox to process unread count update events?

**Comment by saenzramiro** [comment]
Every time Rambox have to process unread count, it goes here:

https://github.com/saenzramiro/rambox/blob/master/app/Application.js#L281
