### ISSUE TITLE
Elementary OS Loki notifications

### ISSUE THREAD

**Issue by Vliro** [ramboxapp/community-edition#883]
I am running Elementary OS Loki (Pantheon Desktop) and the desktop notifications aren't working properly. Elementary OS has support for banner notifications, however so far I've only seen the custom-added Couple app deliver notifications while Messenger only lights the icon up but no notification is shown. 

-
> Rambox 0.5.3
> Electron 1.4.15
> linux x64 4.8.0-53-generic

**Comment by saenzramiro** [comment]
Can you check this with the latest version 0.5.9?
