### ISSUE TITLE
Ctrl+Q is *incredibly* annoying

### ISSUE THREAD

**Issue by xarinatan** [ramboxapp/community-edition#892]
### Steps to reproduce

1. use program
2. try to press ctrl+tab on tiny laptop keyboard
3. fail miserably
4. weep silently as everything you were working on is instantly gone 

### Expected behavior
"Would you like to quit? [Y/n]"

### Actual behavior
HE'S DEAD JIM

### ENVIRONMENT

> Rambox: v0.*.*

> OS: Linux, Windows, MacOS

> Arch: x64 and ia32

**Comment by Bebef** [comment]
I can't confirm this for Rambox 0.5.13 and WIndows 10 x64.

Could you check whether this still is an issue?

**Comment by xarinatan** [comment]
On 4.13.5-1-ARCH Linux with KDE 5.11 it still does it for me. I assume it's the same on all Linuxes and probably Mac too (except with super/applekey/winkey+Q instead of ctrl+Q because of reasons only obvious to Apple.)

Also sorry it took me a bit to get back, I had to install it first because I kind of switched over to a portable firefox profile script thing (I just put it on my github as well) that gets the job done as well for me :) I don't use Rambox much anymore. Ironically Firefox has this issue as well but at least there I can install an addon that disables the behavior. It seems like a standard shortcut in many applications these days.. as if Alt+F4 wasn't enough or something 😛
