### ISSUE TITLE
Enabling Service does not bring the tab back. 

### ISSUE THREAD

**Issue by mdudhani** [ramboxapp/community-edition#894]
Recently updated to 0.5.9. Already had some services active and some inactive. 

**Initial State:**
2 Active services (resulting in 2 tabs)
3 Inactive services. 

**Steps**:
- Have a service which is disabled with at least one active service (in my case i had 2 active and 3 inactive)
- Enable Service. 
     - Expected: Third service tab should be visible and accessible.
     - Actual: Third service tab not visible but accessible. Also, the content of tab is not completely visible. 

**Workaround:**
Restarting the app fixes the issue. 

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> darwin x64 15.6.0

**Comment by saenzramiro** [comment]
Ok, I will take a look on this for next version.

**Comment by mdudhani** [comment]
I have been using it for a while but that has not happened again. Sometimes the tabs appear on the far right but that's about it.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
