### ISSUE TITLE
feature request: Chromium plugin support

### ISSUE THREAD

**Issue by edmundlaugasson** [ramboxapp/community-edition#896]
### Steps to reproduce

1. try to find a choice in Rambox where to add a Chromium plugin
2. looked from menus and dialog boxes
3. cannot find a way to add a plugin

### Expected behavior

Found a way to add Chromium plugin, also in incognito mode. E.g. Lastpass or similar to use with log in.

### Actual behavior

Not possible to add.

### ENVIRONMENT
> Rambox: v0.5.9
> OS: Linux Mint 18.1
> Arch: x64

**Comment by jacebenson** [comment]
Looks like since this is build on electron this issue could be partially solved by using this to load up some common password managers plugins like brave does;
https://www.npmjs.com/package/electron-devtools-installer

**Comment by arvenil** [comment]
I'm currently using [gopass](https://github.com/justwatchcom/gopass). Would be amazing to see that integrated with rambox e.g. via browser plugin:
* https://github.com/dannyvankooten/browserpass
or
* https://github.com/martinhoefling/gopassbridge

**Comment by Creanimo** [comment]
+1 for internal password manager (maybe with a required master password) or plugins like LastPass

**Comment by bignick8t3** [comment]
+1 for LastPass would make it pretty sweet

**Comment by stidch** [comment]
still not possible to use a password manager, or is it?
