### ISSUE TITLE
Loading icon does not go away

### ISSUE THREAD

**Issue by tommica** [ramboxapp/community-edition#902]
### Steps to reproduce

1. Start the app 

### Expected behavior

Big loading rambox icon disappears

### Actual behavior

It does not disappear

### ENVIRONMENT

OSX 10.11.6

> Rambox: v0.5.9

> OS: Mac

> Arch: x64

![screen shot 2017-06-01 at 14 15 20](https://cloud.githubusercontent.com/assets/1391027/26679356/fbe8a652-46d4-11e7-8f57-2c72642d2892.png)

**Comment by saenzramiro** [comment]
Clear the LocalStorage and Cache going to Help -> Tools in the menu bar or reinstall Rambox.
