### ISSUE TITLE
Selector for special chars does not appear.

### ISSUE THREAD

**Issue by taniadaniela** [ramboxapp/community-edition#903]
### Steps to reproduce

1. Start the app
2. Try to use special chars like ñ or áéí (press the n or a, e any key longer)
3. The native selector in Mac OS for those characters don't pop up n

### Expected behavior
The selector should appear (it used to appear on the last release)

![screen shot 2017-06-01 at 9 17 25 am](https://cloud.githubusercontent.com/assets/5315791/26681487/4f0299e4-46ab-11e7-832a-65dc5db02873.jpg)

### Actual behavior

The selector doesn't appear and I can use any special char.

### ENVIRONMENT

Version: 0.5.9
Platform: darwin (x64) Sierra 10.12.5
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
