### ISSUE TITLE
rocket.chat notifications not shown

### ISSUE THREAD

**Issue by msbentley** [ramboxapp/community-edition#905]
Previously (before some weeks?) rocket.chat notifications in Rambox worked fine. As of a few weeks ago, notifications seem not to be picked up by Rambox - they are shown in e.g. the rocket app itself, but no longer appear in the badge, system tray or Unity dock in Rambox.

### ENVIRONMENT

> Rambox: v0.5.9
> OS: ubuntu 17.04
> Arch: x64

**Comment by Bruce17** [comment]
I believe it just never worker in my application. I only see it in Rambox itself, but no notifications like in Telegram. Same behavior on 15 other Win10 and one Ubuntu 16.04 machine in our office. 

**Environment**
> Rambox 0.5.10
> OS: Win10
> Arch: x64

**Comment by saenzramiro** [comment]
Did you updated Rocket Chat version before start not working?

What about now in version 0.5.10?

**Comment by Bruce17** [comment]
@saenzramiro Yes it was an update.

A few weeks ago I did a fresh install of v0.5.10 on another machine (Win 7). That worked for me.

**Comment by Pliind** [comment]
I did a fresh install on a completely new computer, no notifications in rocketchat...
