### ISSUE TITLE
Unable to Drag and drop images to any service

### ISSUE THREAD

**Issue by notNSANE** [ramboxapp/community-edition#908]
### Steps to reproduce

1. Open any service (Telegram, Whatsapp, etc.)
2. Find any image in a browser
3. Drag and drop the image to any service that allows drag and dropping

### Expected behavior

Image gets automatically uploaded/embedded

### Actual behavior

Nothing happens

### ENVIRONMENT

> Rambox: v0.5.9

> OS: Win10

> Arch: x64

**Comment by saenzramiro** [comment]
Is this also happening in latest version?

**Comment by notnsane** [comment]
Just checked with 0.5.10! Tried to drag an image into Telegram, Whatsapp or Discord, none of them worked though Whatsapp opened the "image preview".

Important note that I forgot to include: this dragging **directly from my browser (Vivaldi) to Rambox**. If I drag and drop from Vivaldi to desktop, then from desktop to any service, it works.

**Comment by saenzramiro** [comment]
Oh, nice point. Because I was testing from Desktop to Rambox and works ok.

I just tested and seems not to work as you said. I can take a look in the future but it's not a big issue right now.

Thanks!

**Comment by notnsane** [comment]
For some reason this works as intended now in Whatsapp but not in other services (Telegram, Discord)

**Comment by tdchien** [comment]
I'm facing the same this problem. I unable drag and drop to any server with rambox. Some services I test are slack, telegram, skype and messenger.

I have tried with franz 5 which app builded with electron and noticed it's worked.

This is my rambox version
![image](https://user-images.githubusercontent.com/1614393/41906734-d82211e6-7968-11e8-8fa5-bc4de8a23ab1.png)

System information
![image](https://user-images.githubusercontent.com/1614393/41906760-f3126898-7968-11e8-909c-757696fd219b.png)

**Comment by tdchien** [comment]
Hello, I tried again and confirmed drag and drop is working on window 7. I thing this feature seen have problem on window 10
![image](https://user-images.githubusercontent.com/1614393/42126758-fbac7858-7cb6-11e8-8e7a-91ccd4f3fdec.png)
![image](https://user-images.githubusercontent.com/1614393/42126761-039977a0-7cb7-11e8-8eb7-2a5ba41c7975.png)

**Comment by notnsane** [comment]
I can confirm that it was working for Whatsapp but not anymore. Says something like "unable to render image".
