### ISSUE TITLE
Updating to 0.5.9 won't show installer and won't launch. Downgrade to 0.5.3 works, clean cache/local storage won't work.

### ISSUE THREAD

**Issue by syscheck** [ramboxapp/community-edition#913]
-
> Rambox 0.5.3
> Electron 1.4.15
> win32 x64 10.0.15063

**Comment by choman** [comment]
+1

**Comment by saenzramiro** [comment]
Did you update using auto update or you downloaded `.exe` file from the page manually?

**Comment by syscheck** [comment]
I tried both. Including deleting the program and trying again, including an extra reboot.
Workaround is to use/install the 32bit version. (I have W10 64bit).

**Comment by saenzramiro** [comment]
What about version 0.5.10?

**Comment by syscheck** [comment]
0.5.10 : I'm using the 32bit version. Not tested 64 bit version.
