### ISSUE TITLE
COUNT SPAM

### ISSUE THREAD

**Issue by radioterror** [ramboxapp/community-edition#915]
How can i do to count spam emails as tab and global counter badge? Thanks

### ENVIRONMENT

> Rambox: v0.5.9

> OS: MacOS Sierra 10.12.5

> Arch: x64

**Comment by saenzramiro** [comment]
You will need to inject JavaScript code to the service.

https://github.com/saenzramiro/rambox/wiki/Inject-JavaScript-Code
