### ISSUE TITLE
Support LHC

### ISSUE THREAD

**Issue by ArjonBu** [ramboxapp/community-edition#917]
[Livehelperchat](http://livehelperchat.com/) is a selfhosted livechat for your website. It lacks a proper desktop client. Can you please add it to Rambox?

**Comment by nmat** [comment]
Does this have a web interface? because rambox uses external webinterfaces to connect and present information in rambox. Else you can test to use the custom service to see if you can connect it to rambox.

**Comment by Arjoni** [comment]
Yes, it is a web app. You can check the demo at 
https://livehelperchat.com/demo-12c.html

Yes the custom service works but it doesn't get the notifications.

**Comment by Arjoni** [comment]
Any update on this? Is there any plan on supporting it?

**Comment by saenzramiro** [comment]
@Arjoni We will consider to add it in a future release.

**Comment by Arjoni** [comment]
@saenzramiro thanks!
