### ISSUE TITLE
Add the Join app (SMS/MMS+notification client)?

### ISSUE THREAD

**Issue by markusviktorius** [ramboxapp/community-edition#918]
Hi :)

The Join app has both a Chrome client and a windows app client. Is that possible to add? 

Here is the chrome app (which I prefer): https://chrome.google.com/webstore/detail/join/flejfacjooompmliegamfbpjjdlhokhj

The Join website:
https://joaoapps.com/join/

Thanks for the great software

**Comment by nmat** [comment]
Sounds like pushpullet, should be kept as a feature release.

**Comment by nmat** [comment]
why did you close it?

Keep it open so that they can look at it when time comes. :)

**Comment by markusviktorius** [comment]
Im new here and thought I posted it in the wrong thread. And that I should have posted it in pull requests, but I couldn't figure out how to do it with all the branches and stuff😆

**Comment by nmat** [comment]
pull requests are for doing patches. If you have a patch to add the integration you can do a pull request to have the developers look at it and test it out.

**Comment by eckhardt83** [comment]
yes lets get Join in the Rambox :)
