### ISSUE TITLE
Javascript error on updating

### ISSUE THREAD

**Issue by KITSJamesWalker** [ramboxapp/community-edition#925]
### Steps to reproduce

1. Open Rambox
2. 
3. 

### Expected behavior

Rambox updated to latest version

### Actual behavior

Javascript error popup

"Uncaught Exception:
Error: Command failed: 4294967295
System.AggregateException: One or more errors occured. ---> System.Net.WebException: The remote server returned an error: (500) internal server error.

### ENVIRONMENT

Windows 7

> Rambox: v0.5.3

**Comment by saenzramiro** [comment]
Seems like it couldn't reach update server. Please, try again by going to Help menu, then Check for updates.

**Comment by brendanjones** [comment]
I just had this (or similar. I'm no dev, I don't speak error code) first time I opened the app after installation:

![screen shot 2017-07-21 at 11 34 33](https://user-images.githubusercontent.com/16049594/28459009-104f62c6-6e0c-11e7-8acc-e81cae5f6a8c.png)

The update was completed fine and no error was received after I closed and reopened the app.

My arch:

![screen shot 2017-07-21 at 11 59 42](https://user-images.githubusercontent.com/16049594/28459026-22506f60-6e0c-11e7-8f42-764ea65c0473.png)

**Comment by saenzramiro** [comment]
@brendanjones Are you still having that problem?

**Comment by brendanjones** [comment]
I didn't have it on the latest update, no.
