### ISSUE TITLE
Remove bottom status bar (Ready) forever

### ISSUE THREAD

**Issue by stanis64** [ramboxapp/community-edition#933]
Option to remove status bar forever => will not appear again after reload service or whole app.
It could be an option in service settings to display that or not.

**Comment by Mte90** [comment]
It is very boring, I disabled in all the service that I added

**Comment by brendanjones** [comment]
Agreed. It's completely superfluous. If the service is displaying then it's obviously ready, I don't need a status bar to tell me that.

**Comment by stanis64** [comment]
Ha, it's already there :-D Service settings -> Always display Status Bar

**Comment by brendanjones** [comment]
That's per service. What about a global setting that's off by default?

**Comment by stanis64** [comment]
I don't have much services, so I am disable it for all of them but for better user experience the global settings would be great.

**Comment by Bak3y** [comment]
There should absolutely be a global toggle for this.

**Comment by poisonborz** [comment]
+1 for some solution on this. Didn't know about this option until I found this thread.
However, having global + per service toggle is too complicated, and the per-service _is_ useful.

I recommend: besides the service window, this option should **also** be present next to the current status bar close button eg. as "always disable"

**Comment by m106** [comment]
This setting shouldn't be at least on by default! It is like the most useless function every I think for the most of us :)

**Comment by wilomgfx** [comment]
yes pls, its quit annoying ! haha
