### ISSUE TITLE
Untranslated strings - some strings are not implemented as locale variables

### ISSUE THREAD

**Issue by libora** [ramboxapp/community-edition#938]
I see few untranslated strings in the Czech language, but I cannot find these string on the Crowdin (on the Crowdin all string looks as translated for the Czech language).

_In menus:_
Delete
Reload current service
Zoom in
Zoom out
Actual size
Tools
Clear cahce
Clear local storage
Paste and match style

_In the main window:_
Help us with
Translation
Follow us

_Preference window:_
Display behaviour
Show in Taskbar
Show Tray Icon
Show in Taskbar and Tray Icon
When closing the main windows:
Keep in tray
Keep in tray and taskbar
Always on top
Show system Tray indicator on unread messages
Disable Hardware Acceleration (needs to relaunch)
Master Password - Ask for password on startup
Proxy (needs to relaunch)

_Add service:_
Show service name in Tab
Always display Status Bar
Display tab unread counter
Include in global unread counter

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.14393

**Comment by nmat** [comment]
You can provide and help with translation using: https://crowdin.com/project/rambox/invite

Also the readme states information of the translation help.

**Comment by libora** [comment]
@nmat These strings are not on Crowdin then they are cannot be translated.

**Comment by libora** [comment]
It is necessary to define these strings as locale variables and add these string to languages files. For example, The add service window is defined in file add.js and four strings (posted above) are defined in lines 167, 183, 213 and 220. All other strings in this windows are defined as variables.

**Comment by saenzramiro** [comment]
@libora Thank you, we know there are a lot of strings that we need to add it to Crowdin. We will do it ASAP.
