### ISSUE TITLE
After prolonged usage Slack and Telegram don't update unread count after viewing channel

### ISSUE THREAD

**Issue by z0rc** [ramboxapp/community-edition#939]
Unfortunately I haven't found a way how to distinctly reproduce this.

After some time (varied from 30 minutes to 2-3 hours) the Slack and Telegram stop's marking new messages as read after opening a channel with them, Slack's Esc hotkey stops working either. I might be terribly wrong, but it loos like the web application doesn't receive focus events.

Ultimate fix is a Rambox restart, which I have to do 2-3 times during the day after upgrade to 0.5.9.
 
### ENVIRONMENT

> Rambox: v0.5.9

> OS: Kubuntu 17.04

> Arch: x64

**Comment by saenzramiro** [comment]
Wow, I didn't notice that. I use Slack every day, so I will pay attention for this.

**Comment by Daegalus** [comment]
I am having this same issue with Slack, but not only with Rambox, but the official Slack client too. So it could be potentially an issue with Electron itself, as thats what the official slack client uses for Linux

Rambox v0.5.13
Electron v1.7.8
OS: Kubuntu 17.10
Arch: x64

**Comment by Daegalus** [comment]
![selection_007](https://user-images.githubusercontent.com/670212/31910505-86fe3a7a-b7f2-11e7-81c5-ac71fe3c9b08.png)
Seems its an issue with KDE. Fixes are coming, but might be worth investigating what KDE issue it is and how Slack fixes it on their end, so that Rambox can get the same fix.

**Comment by fvulich** [comment]
I'm gonna close this ticket due to inactivity, feel free to open another ticket if the problem persists.
