### ISSUE TITLE
Password cannot be pasted into master password field

### ISSUE THREAD

**Issue by betsythefc** [ramboxapp/community-edition#945]
### Steps to reproduce

1. Set master password
2. Close and re-open app
3. Cannot paste password into master password field

### Expected behavior

To be able to paste password into the field.

### Actual behavior

Command+V does nothing in master password field.

### ENVIRONMENT

> Rambox: v0.5.9

> OS: macOS 10.12.5

> Arch: x64

**Comment by betsythefc** [comment]
To specify, I am using a randomly generated password, that is very difficult and long to type in.

**Comment by saenzramiro** [comment]
Oh, I see... I will allow this in next release.
