### ISSUE TITLE
service not remembered

### ISSUE THREAD

**Issue by edmundlaugasson** [ramboxapp/community-edition#947]
### Steps to reproduce

1. add new service
2. reopen a program
3. service disappeared

Also tried to save settings manually but did not help either. I had 25 services - deleted one and tried to add a new one (ProtonMail CH) - not saved. Even after backing up the deleted service is back and newly added service is disappeared.

### Expected behavior
Service should be saved (with all of its settings).

### Actual behavior
Service is not saved and it is disappeared.

### ENVIRONMENT
Version: 0.5.9
Platform: linux (x64)
Electron: 1.7.1
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by jrbell989** [comment]
I've hit a similar issue since upgrading to 0.6.1 - Sometimes, when I start Rambox (or maybe when I shut down), it loses _all_ of my services.

**Environment**
Version: 0.6.1
Platform: win32 (x64)
Electron: 2.0.8
Chromium: 61.0.3163.100
Node: 8.9.3

**Comment by Gby56** [comment]
Happens sometimes on Version: 0.6.3
Platform: win32 (x64)
Electron: 2.0.14
Chromium: 61.0.3163.100
Node: 8.9.3
