### ISSUE TITLE
Replace scrolling with wrapping in services bar

### ISSUE THREAD

**Issue by raveem** [ramboxapp/community-edition#949]
Can we get rid of the scrolling and have a wrapped service bar please? Or at least have an option to switch it to wrapped? 

It destroys the point of at-a-glance checking for any notifications. This is one area where Franz certainly delivered (see screenshot).

![image](https://user-images.githubusercontent.com/6374306/27218589-9f38ce16-5276-11e7-8586-a2edc36e5ed3.png)

**Comment by nmat** [comment]
http://rambox.pro/100/

Just a FYI

**Comment by raveem** [comment]
Duly donated. Any confirmation we'll get the scrolling?
