### ISSUE TITLE
Rambox won't start after OS update

### ISSUE THREAD

**Issue by dchara01** [ramboxapp/community-edition#952]
### Steps to reproduce

1. Install Manjaro
2. Install rambox-bin from AUR
3. Update Manjaro

### Expected behavior

Start normally.

### Actual behavior

The program won't start.
It does not return an error, it just won't start.
Deleting the configuration files under /home the app starts.
The tray icon does not appear though.
Changing settings in preferences results in the app not starting again.

### ENVIRONMENT

Manjaro KDE 17.0.1 with latest updates

> Rambox: v0.5.9

> OS: Manjaro 17.0.1 up to date

> Arch: x64

**Comment by saenzramiro** [comment]
Sorry but seems like it's a Manjaro or rambox-bin problem. We don't support AUR officially, but a user @jbbr it's the maintainer.

**Comment by jbbr** [comment]
@dchara01 sorry I missed the notification for this issue. Do you still have problem with the AUR package?

The AUR package should behave mostly the same as the official packages as it mostly copies the contents of the official binary release.

**Comment by dchara01** [comment]
No. It is OK now. Thanks.
