### ISSUE TITLE
Certification Warning

### ISSUE THREAD

**Issue by Les-Linux** [ramboxapp/community-edition#959]
Hi, since yesterday I have a blank (white) screen for the mattermost service. It was working fine, not quite sure what happened since. Un-Install, Clear Cache etc. not making any difference - on reload 'certificate warning' shown in the bottom task bar.

Setting the mattermost service up as a 'custom' service and selecting 'trust invalid authority certificate' also makes no difference. There is an issue with the certificate it would seem and related to the date.

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 10.0.10586

**Comment by nmat** [comment]
Is there any specific service that gives you this? I am using rambox 0.5.9 on windows without any problems at all with certificates.

**Comment by 317537** [comment]
Hey nmat,

Just mattermost. Skype is fine.

**Comment by iPublicis** [comment]
Same issue with Hangouts
