### ISSUE TITLE
Blank page roundcube with invalid SSL certificate

### ISSUE THREAD

**Issue by rodolphopivetta** [ramboxapp/community-edition#967]
This is a private webmail server and the certification is not an issue for us at the moment.

### Steps to reproduce

1. Add Roundcube service with HTTPS NET::ERR_CERT_AUTHORITY_INVALID

### Actual behavior

![image](https://user-images.githubusercontent.com/6686047/27518868-4bba96d2-59b7-11e7-8b53-bba1b4149ada.png)

### ENVIRONMENT

> Rambox: v0.5.9

> OS: Windows 10

> Arch: x64

> Electron: 1.7.1

> Chromium: 58.0.3029.110

> Node: 7.9.0

**Comment by zlo2107** [comment]
The same issue with adding private zimbra server with untrusted certificate:
 
**Steps to reproduce**

Add Zimbra service with Error code: 
(firefox) SEC_ERROR_UNKNOWN_ISSUER
(chrom) NET::ERR_CERT_AUTHORITY_INVALID

There is no difference by adding Zimbra or _Custom Service with checked "Ignore untrusted ssl certificate".

	> Rambox 0.5.13
	> Electron 1.7.8
	> linux x64 4.9.47-1-rt37-MANJARO

**Comment by rodneyrod** [comment]
Getting a similar problem with another self hosted web app.

Could be that the permit untrusted cert setting is no longer working.

**Comment by zlo2107** [comment]
I'm not so familiar with javascript, can anyone provide some tips what couses the problem?
