### ISSUE TITLE
No desktop notifications in Riot.im

### ISSUE THREAD

**Issue by dluciv** [ramboxapp/community-edition#969]
1. Riot plugin successfully displays number of unread messages in header tab.
2. When opening web console for Riot in Rambox and writing `setTimeout(function(){new Notification("Test");}, 5000);` here, and then switching to another tab and closing window, everything works ok. E.g. notifications theirselves are ok.
3. When opened in usual web browser, Riot.im shows notifications.
4. All this was checked on the both matrix.org and my own dluciv.name Matrix servers.
5. In addition, Rambox displays notifications from some messengers, e.g. ICQ, successfully.

And no desktop notifications for Riot at all. Right now did not succeed in digging this out.

	
	-
	> Rambox 0.5.9
	> Electron 1.7.1
	> win32 x64 6.1.7601

**Comment by dluciv** [comment]
On Linux x64, Rambox 0.59, Electron 1.4.16, Node 6.5.0 notifications are ok!

**Comment by saenzramiro** [comment]
Is this happening also in version 0.5.10?

**Comment by dluciv** [comment]
Yes, unfortunately...

**Comment by gnouts** [comment]
On my end, Rambox 6.2 fixed the issue.
