### ISSUE TITLE
Unread notification being read from service name

### ISSUE THREAD

**Issue by Cezille07** [ramboxapp/community-edition#981]
### Steps to reproduce

1. Visit settings page.
2. Edit any service name into a string with a number (for example, my username is `Cezille07`, or `ABC123D4`).
3. Switch to that service tab. It shows `7`, or `1k`, based on the title, no matter what the number of unread messages is. 

I think it seems to be related to #471 , which is where I got the hint that it might be from the title. 

### Expected behavior

The unread counter shows the number of unread messages, or none if there aren't any.

### Actual behavior

It seems to be parsing the title for any numbers, and displays that number instead. 

### ENVIRONMENT

> Rambox: v0.5.10

> OS: Windows 8.1

> Arch: x64

**Comment by talyssonoc** [comment]
I'm noticing this on OS X as well. Environment:

```
Rambox: v0.5.10
OS: OS X El Capitan 10.11.6
Arch: x64
```

**Comment by saenzramiro** [comment]
This is weird because we read the title of the service and not from Rambox service title.

Can you specify a service that causes this for example?
