### ISSUE TITLE
telegram web isn't using the whole screen like in Franz

### ISSUE THREAD

**Issue by rwolupo** [ramboxapp/community-edition#984]
-
	> Rambox 0.5.10
	> Electron 1.7.4
	> win32 x64 10.0.15063

**Comment by gameguy95** [comment]
I am having the same issue. Telegram is surrounded by a big gray border with the chat client in the middle. It's not a huge deal, but it is starting to become obnoxious after only a few days of use.

**Comment by rnyberg** [comment]
Can confirm, affects me too.

**Comment by jdaberkow** [comment]
Can confirm this as well. Gets slightly annoying after time. :(

**Comment by jerry1970** [comment]
Also happens on Xubuntu 17.04
