### ISSUE TITLE
Upgrate from 0.5.3 to 0.5.9, cann't load Hipchat login page anymore.(custom server)

### ISSUE THREAD

**Issue by longnight** [ramboxapp/community-edition#988]
And I downgrade to 0.5.3, it works well again.

> Rambox: v0.5.9

> OS: ubuntu

> Arch: x64

**Comment by bechtoldt** [comment]
I can confirm such a behaviour on 0.5.3, .9 and .10. Rambox suddenly stopped showing the HipChat login/chat after it worked for some "time".

<img width="1673" alt="screen shot 2017-07-31 at 11 05 46" src="https://user-images.githubusercontent.com/1507504/28770645-3ae51f4a-75e0-11e7-9f26-9131e49b1244.png">

**Comment by SnoFox** [comment]
Hi there,

I'm having this issue as well. I'm unable to load a custom server; dev tools reflect it's not allowed to load a local resource: %LOCALAPPDATA%\Rambox\app-0.5.12\resources\app.asar\<custom server domain>

**Comment by joe776** [comment]
Same error message in console here. Hipchat custom server, Rambox 0.5.12, macOS Sierra.

**Comment by joe776** [comment]
Adding it as a custom service solved this for me...
I also put `document.getElementsByClassName("aui-button aui-button-primary")[0].click()` as a custom JS to skip the "Go to desktop version" window after startup.
