### ISSUE TITLE
Welcome screen on every start

### ISSUE THREAD

**Issue by ghost** [ramboxapp/community-edition#989]
### Steps to reproduce

1. have Rambox pro 0.5.9 installed
2. upgrade to 0.5.10
3. restart Rambox

### Expected behavior

The "Welcome to version 0.5.10" box should be displayed once.

### Actual behavior

The "Welcome to version 0.5.10" box will be displayed on every start.

### ENVIRONMENT

> Rambox: v0.5.10

> OS: Win 10 Pro

> Arch: x64

**Comment by modulebaan** [comment]
Confirmed on OpenSUSE Tumbleweed x64

**Comment by gingerbeardman** [comment]
Related: https://github.com/saenzramiro/rambox/issues/932

It seems opening on settings/welcome is the way of nagging for donations?

**Comment by saenzramiro** [comment]
We use Tooltip.io to create those windows. Once the user close it, it will store in the localStorage the id of that window, so the next time if that window id is in your localStorage, it will prevent to show up. Seems like the ID of that windows is not saving it correctly or clearing once you close Rambox. So, it's a Tooltip.io bug I think.

Can you check your localStorage and search for this?

**Comment by gingerbeardman** [comment]
I simply blocked tooltip.io at my router

**Comment by Bebef** [comment]
@saenzramiro Where exactly would I have to look on a Windows 10 installation?

**Comment by FranzSkuffka** [comment]
Still there. Very ***** annoying. I think I'll create a fork or something.

**Comment by gingerbeardman** [comment]
I've moved back to Franz, which is once again being updated

**Comment by FranzSkuffka** [comment]
yeah franz looks better. I'll take a look around. I did not like that it's open source but better closed source than nagware with mediocre UI.

**Comment by FranzSkuffka** [comment]
https://github.com/wavebox/waveboxapp

Here's an alternative if someone wants to check out.
