### ISSUE TITLE
Rambox not open in Debian. (Deepin 15.4)

### ISSUE THREAD

**Issue by soycamiloypunto** [ramboxapp/community-edition#994]
### Steps to reproduce

1. Install Rambox 0.5.10
2. Open Rambox
3. Not Open GUI. :(

### ENVIRONMENT

> Rambox: v0.5.10

> OS: Deepin 15.4 (Debian based)
> Arch: x64

**Comment by marxistvegan** [comment]
Please specify which debian, as I a running Debian Buster/Testing and have no problem with 0.5.10

**Comment by breescorner** [comment]
I can't get it to open in Ubuntu 14.04 LTS
